### ISSUE TITLE
trouble with fulltext search on Android 5 while not on Android 4

### ISSUE THREAD

**Issue by Herve5** [kiwix/kiwix-android#1]
Hello all! I am an extremely happy user of Kiwix on a relatively old tablet (samsung on Android 4), where everything ls perfect, among others I have the Wikipedia and the related index file, and fulltext search activated.
Recently I tried to install the same config on a phone with Android 5, and I find the zim files are found and used, but the .idx folder (that I locate at the same place as the .zim) is not found, or not used, apparently.
Where am I wrong? Is there a more specific location in the Android 5 file hierarchy, for instance?
This issue is the same I discussed on the #kiwix channel on the 24@21:40, but I don't need an instant answer, nor do I want to impose a new point in the bugtracker if I am just goofing on the folder location, for instance...
On the andro 4 machine where everything works, the zim files and .idx folder are in /android/content ; on the andro5 machine I did put them elsewhere, straight in /content (aside the /android folder) because initially without .idx files this just worked. 
Is this my error?

On both machines I am using the last official kiwix straight from google apps; the zim for which I add the .idx folder is the latest french wikipedia, wikipedia_fr_all_2016-6.zim and the folder with same name plus .idx at the end…

Thank you!
Hervé

**Comment by kelson42** [comment]
@Herve5 How does that work with 2.2?

**Comment by Herve5** [comment]
Sorry for this delayed answer. I actually installed Kiwix from the F-Droid repo, where it is still at version 2.1.
If things do not change in the coming days I'll switch at least temporarily to the Google repo to try version 2.2.

Thank you for the excellent work!

-- fh.sainct@laposte.netvia html interface

----- Mail d'origine -----De: Kelson <notifications@github.com>&Agrave;: kiwix/kiwix-android <kiwix-android@noreply.github.com>Cc: Herve5 <fh.sainct@laposte.net>, Mention <mention@noreply.github.com>Envoy&eacute;: Mon, 13 Mar 2017 08:24:51 +0100 (CET)Objet: Re: [kiwix/kiwix-android] trouble with fulltext search on Android 5 while not on Android 4 (#1)

@Herve5 How does that work with 2.2?
&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by kelson42** [comment]
@Herve5 Yes, I think this is fixed in 2.2. You can also download the apk from http://download.kiwix.org/. Please reopen the ticket if you still have the problem with 2.2
