### ISSUE TITLE
Remove (or keep up-to-date) this repository

### ISSUE THREAD

**Issue by nicolas-raoul** [kiwix/kiwix-android#1]
The source code in this repository is two years older than the source code at https://sourceforge.net/p/kiwix/kiwix/ci/master/tree/android

It would be good to remove it as it can lead to people developing on top of old code.

**Comment by kelson42** [comment]
For now, Sourceforge is the master git repo, and github is a mirror. It's not 2 years old, you can see commits which are a few hours old.

**Comment by nicolas-raoul** [comment]
Strange, files are all marked "two years" in my browser :-/
![2-years](https://cloud.githubusercontent.com/assets/99590/7978915/b4e0247a-0ad5-11e5-86a8-ba1775dac6e2.png)
