### ISSUE TITLE
Test Suite doesn't compile in Android Studio

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#1003]
**Describe the bug**
Android studio can't find various classes in the test folders including the main packages and external packages. I have gone back a bit and couldn't get this working so it might be an Android studio change. Anyone else having this issue @siddharth2010 @abdulwd 

**Screenshots**

![image](https://user-images.githubusercontent.com/2286937/52980760-a623f080-33d3-11e9-857a-c861e254c6fa.png)

**Comment by iadeelzafar** [comment]
That's right. I'm facing the same issue too.
