### ISSUE TITLE
Leaving The App While Downloading Crashes App & Stops Download

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1007]
**Describe the bug**

Leaving The App While Downloading Crashes App & Stops Download

**Expected behavior**

* App should not crash when leaving the app.
* Download should continue

**Steps to reproduce the behavior:**

1.  Start downloading.
2. Press home button.
3. App will crash and download will stop.

**Screenshots**

<img src = "https://user-images.githubusercontent.com/36811908/53034854-fa8fa480-3495-11e9-880d-deb39dab19a7.gif" height="700" width="394">

**Environment**
Galaxy Nexus API 24

**Comment by iadeelzafar** [comment]
Is everyone else facing the same issue too?

**Comment by mhutti1** [comment]
There are a lot of download related issues.  This is likely one of them.

**Comment by iadeelzafar** [comment]
I can't reproduce this now. Can anyone try to reproduce this?

**Comment by sonusourav** [comment]
@iadeelzafar I am also getting the same.

**Comment by iadeelzafar** [comment]
@sonusourav Brother can you reproduce this issue or not?

**Comment by sonusourav** [comment]
@iadeelzafar yes, I am able to reproduce it.

**Comment by sidkathuria14** [comment]
I would like to work on this issue. Is someone already working on it?

**Comment by iadeelzafar** [comment]
Go for it. Good Luck!

**Comment by iadeelzafar** [comment]
@sidkathuria14 First check if you're able to reproduce this bug or not. I was able to reproduce this when I created this ticket but after a while I couldn't reproduce this again.

**Comment by macgills** [comment]
Fixed in #1170
