### ISSUE TITLE
Set up proguard

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#101]
Set up Proguard to reduce apk size for #86.

**Comment by kelson42** [comment]
@mhutti1 the goal is to have it in the CI? That would be really great!

**Comment by mhutti1** [comment]
Yeah it would be done on CI but also locally.

**Comment by kelson42** [comment]
A manual cleanup has been done with #177, but nothing automated so far.

**Comment by brijeshshah13** [comment]
Working on this issue @mhutti1.

**Comment by mhutti1** [comment]
@brijeshshah13 I am not sure if @rishabchirania is working on this already. https://github.com/kiwix/kiwix-android/pull/357

**Comment by brijeshshah13** [comment]
@mhutti1 Just enabling `minifyEnabled true` isn't making any difference in the apk size. I'm trying to monitor and analyze apk size after everfy build.

**Comment by rishabchirania** [comment]
@mhutti1 @brijeshshah13 you can go ahead...i am currently working on lint issue...

**Comment by brijeshshah13** [comment]
@rishabchirania Alright.

**Comment by RajaVamsi11** [comment]
AS @brijeshshah13  says  Just enabling `minify Enabled true` isn't making any difference in the apk size. I also tried it.

**Comment by brijeshshah13** [comment]
@RajaVamsi11 Indeed. Necessary proguard rules will have to be written.

**Comment by macgills** [comment]
I will hopefully be setting up R8 - the successor to proguard - as part of this ticket
