### ISSUE TITLE
Add an EmptyView To Bookmarks Activity

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1010]
**Is your feature request related to a problem? Please describe.**

It's a good practice to have an empty view. In bookmarks activity, there's absence of an empty view.

**Describe the solution you'd like**

* Adding an emptyview to the bookmarks activity.

**Additional context**

Currently, here's how it looks. 

<img src = "https://user-images.githubusercontent.com/36811908/53138196-4716d500-35a7-11e9-98ca-443b7dab1c10.gif" height = "700" width = "394">

For example:
Here's an example of a good empty view.

<img src = "https://user-images.githubusercontent.com/36811908/53137993-a88a7400-35a6-11e9-9a9b-4b697f010749.png" height="700" width="394">

We can have an image that matches with our app's design colors. (i.e. B&W) and also one for the NIGHT MODE or we can have TEXT only. 
>**_I'm looking for suggestions here._**

**Comment by abdulwd** [comment]
Make sure you use a vector image instead of raster image and follow the material guidelines for empty states.

**Comment by kelson42** [comment]
@iadeelzafar @abdulwd We have now something displayin “No bookmark”... therefore I guess this has been alredy imolemented?

**Comment by abdulwd** [comment]
Yes, implemented in #1710.
