### ISSUE TITLE
RemoveTab Button Should Be Disabled and Grayed When Zero Tabs

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1011]
**Describe the bug**
RemoveTab Button not Disabled and Grayed When there are no tabs.

**Expected behavior**
RemoveTab Button Should Be Disabled and Grayed( OR hidden) When Zero Tabs.

> _I'm looking for suggestions here._

**Steps to reproduce the behavior:**
1. Close all tabs

**Screenshots**
<img src = "https://user-images.githubusercontent.com/36811908/53139328-19338f80-35ab-11e9-9db2-6a186fbc8631.gif" height="700" width="394">

**Environment**
API 24 Galaxy Nexus

**Comment by mhutti1** [comment]
I am pretty sure I wrote somewhere that in my mind you shouldn't be able to close all the tabs and if you do we add a new home screen tab. So I don't know if this change is needed. Thoughts?

**Comment by iadeelzafar** [comment]
@mhutti1 Yes but while the user is still in the tab overview, there can be times where he closes all tabs. At that moment in particular, closeAllTabs button should he hidden. It's weird to have that button even when there are zero tabs. Have a look at the PR I made for this issue.

**Comment by mhutti1** [comment]
I think my point is that it shouldn't be possible to close all tabs.

**Comment by prajurock** [comment]
Yes @mhutti1 i also think that

**Comment by iadeelzafar** [comment]
@mhutti1 I got your point. So, I think we can close this issue as there's going to be no time when all tabs are closed.
