### ISSUE TITLE
Text in Zim files load improperly in portrait mode

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1015]
**Describe the bug**
The text in some Zim files are not displayed properly in portrait mode. While they look perfect in landscape mode, in portrait mode they do not wrap properly. Even some of the links contained in them are broken. Till now, I have found only such file and searching if there are more. 

**Expected behavior**
The contents of Zim files should load properly. 

**Steps to reproduce the behavior:**
1. Download Vikidia (4.5 MB).
2. Rotate to see it in both the modes.

**Screenshots**

 In portrait mode

![portrait_text](https://user-images.githubusercontent.com/34706326/53185167-7cadd380-3624-11e9-9873-2bc60b42dfeb.jpeg)

In landscape mode
![landscape_text](https://user-images.githubusercontent.com/34706326/53184968-0f01a780-3624-11e9-8092-a34644223579.jpeg)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Nougat 7.1

**Comment by kelson42** [comment]
@sonusourav Does that work properly with the same resolution on https://en.vikidia.org/wiki/Main_Page ?

**Comment by sonusourav** [comment]
@kelson42  In desktop, it seems to be fine but in mobile device, there is text wrap issue

**Comment by mhutti1** [comment]
@kelson42 This isn't an issue with kiwix-android more so zim generation.

**Comment by kelson42** [comment]
@mhutti1 Not even sure with the ZIM generation, looks like to be a problem with the upstream HTML/wiki code?!

**Comment by mhutti1** [comment]
Ah ok. Can we close this then?
