### ISSUE TITLE
Swipe to refresh hides the list of files selected to delete

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1019]
**Describe the bug**
In Device tab in Library screen, when you select some files to delete and swipe down to refresh it, the files selected to delete are no more selected, but the option to delete is still there, i.e. you can still delete those on pressing the delete button on the action bar.

**Expected behavior**
Upon selecting files to delete, swipe to refresh feature should be disabled.

**Steps to reproduce the behavior:**
1. Go to the device tab in the library screen.
2. Select files to delete.
3. Swipe down to refresh.
4. The selected files are no more selected but the user can still delete them.

**Screenshots**

![swipe_before_delete](https://user-images.githubusercontent.com/34706326/53246177-f18d1600-36d5-11e9-8aed-08669985975a.gif)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Nougat 7.1

**Comment by mhutti1** [comment]
It will be easiest to disable swipe to refresh when deleting files.

**Comment by sonusourav** [comment]
@mhutti1 I would like to work on this issue. Could you please assign me to this issue?
