### ISSUE TITLE
Selected files get unselected on screen rotation

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1023]
**Describe the bug**
When files in Device tab in Library screen are selected on long press and device is rotated, the selected files get unselected. While Contextual Action Bar (CAB) is still visible even after rotation, no files remain selected and when the delete button is pressed, CAB just disappears.

**Expected behavior**
On screen-rotation, the selected files should remain selected and the user could still delete/share them (similar to Gmail).

**Steps to reproduce the behavior:**
1.  Open Device tab in Library.
2. Select some files and rotate the device.
3. Selected files get unselected but CAB is still visible.

**Screenshots**

![rotate_deselect_file](https://user-images.githubusercontent.com/34706326/53266398-aa6b4900-3706-11e9-90b8-91d4c597991a.gif)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Nougat 7.1

**Comment by sonusourav** [comment]
@mhutti1 Would like to work on this. Please assign me to this.

**Comment by kelson42** [comment]
@sonusourav Just out of curiosity: how do select a content without generating an action: open the content or download it? I can not reproduce the problem because of that.

**Comment by macgills** [comment]
In the device tab a long press shows the delete option? Or that is the case for 2.5, I may be behind on some 3.0 functionality

**Comment by kelson42** [comment]
@macgills I'm not even sure this is a real selection, it does only show a dialog box. Even if we consider this like a selection, then this is impossible to have multiple selection like in the video. That said the delete dialog disappears when rotating the screen.

**Comment by macgills** [comment]
Then that would be another issue. Unless @sonusourav can shed some light on this problem I say we close

**Comment by kelson42** [comment]
@macgills Agree.
