### ISSUE TITLE
Night Mode Tab should be gray in night mode

### ISSUE THREAD

**Issue by prajurock** [kiwix/kiwix-android#1028]
**Describe the bug**
Night mode Tab should be gray in Night Mode because its not clickable.

**Screenshots**
![screenshot_20190223-193016](https://user-images.githubusercontent.com/26791135/53287642-184f5900-3777-11e9-9228-f9695adbac26.png)

**Environment**
- Version of Kiwix Android : latest master
- Device : Asus m1
- OS version :API 27

**Comment by mhutti1** [comment]
? Why should it be grayed out. Surely it should be clickable so you can disable night mode.

**Comment by prajurock** [comment]
Sorry i forget to mention properly.
Like when we click Automated night mode then night mode tab look like this


![screenshot_20190224-181731](https://user-images.githubusercontent.com/26791135/53299464-6d9c7080-3832-11e9-8718-1154432bd4ab.png)

**But in night mode it should be grey**

![screenshot_20190223-193016](https://user-images.githubusercontent.com/26791135/53299471-a0deff80-3832-11e9-9e22-e44c3b6e548d.png)

**Comment by kelson42** [comment]
@prajurock @mhutti1 Seems to make sense to me.

**Comment by prajurock** [comment]
Ok.I will work on it

**Comment by waahm7** [comment]
@prajurock If you are not currently working on this issue. Can I start working on it?

**Comment by prajurock** [comment]
I am working but you can take this issue.

**Comment by kanupriyaa** [comment]
I am working on this issue.
