### ISSUE TITLE
Some text not changing to Hindi. 

### ISSUE THREAD

**Issue by prajurock** [kiwix/kiwix-android#1029]
**Describe the bug**

Some text not changing to Hindi. 

**Screenshots**

![whatsapp image 2019-02-23 at 8 42 11 pm](https://user-images.githubusercontent.com/26791135/53288212-03d98380-37ac-11e9-8db8-067b4571a9d1.jpeg)

**Environment**
- Version of Kiwix Android : Latest Master
- Device : Asus Zenfone
- OS version : API 27

**Comment by prajurock** [comment]
I am facing this issue of my language and I guess there are problems with others.
@iadeelzafar you can also check this for your language.

**Comment by mhutti1** [comment]
This is because we don't have a complete translation of every string in every language.
