### ISSUE TITLE
CAB remains visible even after clearing all history

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1030]
**Describe the bug**
When user selects files to delete in history screen, CAB (Contexual Action Bar, blue action bar here) appears. If user deletes all history using clear history in overflow menu, the CAB remains visible.

**Expected behavior**
The CAB should disappear as soon as all history is cleared using clear history item in overflow menu. 

**Steps to reproduce the behavior:**
1. Open history screen.
2. Select some file history to delete.
3. Press clear all history in overflow menu.
4. Even after clearing all history, CAB is still visible.

**Screenshots**

![cab_visible](https://user-images.githubusercontent.com/34706326/53293802-0914ed80-3801-11e9-8231-270d24e22b1d.gif)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Android Nougat 7.1

**Comment by soloturn** [comment]
@sonusourav what is "CAB" ?

**Comment by sonusourav** [comment]
@soloturn yes, its Contextual action bar. Well, both are different. In #1031 the issue is that the history is still present even after clearing all history because when you press the back button, the user can still open the files which were opened before. While in this case, the issue is that after the action mode ( clearing all history in this case) is finished it is not disappearing.

**Comment by mhutti1** [comment]
Why not replace the main bar with the deletion bar?

**Comment by sonusourav** [comment]
@mhutti1 I also think that would be the best.

**Comment by sonusourav** [comment]
@mhutti1 I want to work on this to replace action bar with CAB. Please assign this to me.
