### ISSUE TITLE
Files can be traced back even if all history is cleared

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1031]
**Describe the bug**
Even after the user clears all the history, the user can still track back all the files by pressing the back button.
Also, while going back after clearing the whole history, history of files get recorded( in reverse order in this case). So, it seems that none of history is getting cleared until it is done from the home screen.

**Expected behavior**
The user should land on home screen on back pressed upon clearing all history.

**Steps to reproduce the behavior:**
1. Open history.
2. Clear all history
3. Press back and check the history
4. History is recovered in reverse order

**Screenshots**

![delete_recorded](https://user-images.githubusercontent.com/34706326/53294014-f3a1c280-3804-11e9-9f12-ef09ef1245a1.gif)

**Environment**
-  Version of Kiwix Android: 2.4 Build 55
- Device: Redmi 4
- OS version:  Android Nougat 7.1

**Comment by soloturn** [comment]
@iadeelzafar you worked on the history with yesterday and today, can you imagine where this is coming from?

**Comment by iadeelzafar** [comment]
I think this behavior is usual. That's the reason in webview apps i.e. browsers, when clicking on history a new tab opens where you clear the history. Maybe, we can implement such a thing.

**Comment by mhutti1** [comment]
I imagine you can tell the webview to refresh its history. (Would need to be done for every tab).

**Comment by iadeelzafar** [comment]
Same happens when deleting a ZIM file and going back or if the file is opened in a new tab going there, you can still access the file. I think there can be a mutual solution that solves this issue as well. @mhutti1 @soloturn 
<img src="https://user-images.githubusercontent.com/36811908/53360053-6078a200-3956-11e9-8d3e-f9dadebb9804.gif" height="700" width="394">

**Comment by sonusourav** [comment]
There are two more bugs associated with it:
1. If the file which is to be deleted is already open in one tab, and a user deletes it in another tab, the user can find it is still open in the first tab.
2. After deleting the file, when the user comes back to the main screen (where the list of files and Kiwix banner is present) by pressing back arrow in action bar, the list is not refreshed and the deleted file is still present in the list.
![refresh_delete](https://user-images.githubusercontent.com/34706326/53682610-7f43b380-3d1d-11e9-9403-21566ab6526f.gif)

**Comment by sonusourav** [comment]
@mhutti1 @abdulwd  Would like to work on this issue. Please assign me.

**Comment by sonusourav** [comment]
@abdulwd  Are `Clear History` in overflow menu of History same as  `Clear History` of Settings. I mean, is it like former just clears the history while latter one clears the history and closes all tabs also?

**Comment by abdulwd** [comment]
The clear history in HistoryActivity is just to clear the browsing history. It has nothing to do with the clear history of settings which clears everything including the browsing history. If a user clears only the browsing history he/she can go back to the same tab and trace back the pages. I don't think of it as an issue. But if a user selects clear history from settings then everything should be cleared.

**Comment by sonusourav** [comment]
@abdulwd If a user clears the browsing data, and go back to the webView page, IMO, he/she can definitely find the all the opened webView but history should not be traced onBackPressed ( because history is actually cleared). Even Google chrome does that.
And could you please specify what is *everything* in `clears everything including the browsing history`. Do you mean all preferences or all the (browsing data + opened tabs)?

**Comment by abdulwd** [comment]
I meant browsing history and recent searches are cleared from the settings but only browsing history is cleared from history activity.
