### ISSUE TITLE
zim file not recognized (translated from german)

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#1033]
Maybe it is related to #293

**Describe the bug**
The german, splitted zim works. The english, unsplitted zim doesn't. The external sd card has an exFat FS. After selecting the english zim I get the error "ZIM file is not recognized" (translated from german "nicht gültig") after selecting the german file I get the same, even though it worked before. After stopping kiwix in the Task-Manager I can start kiwix and select the german file w/o problems. The md5sum of the english zim is OK.

**Expected behavior**
The file should be used normally by kiwix. If it is not a valid file then the previous used german file should be selectable without problems.

Kiwix could also offer to check the md5sum and download it from Internet. Since the file could be renamed it would be nice to use the internal file identifier from the zim file.

If the checksum is wrong it would be nice if kiwix would offer to finish/repair the file. Old versions can be found at <https://web.archive.org/web/20180427045312/http://wiki.kiwix.org/wiki/Content>. 

**Steps to reproduce the behavior:**
I don't know if you can reproduce it. I can do other steps, if you want to. I can install APKs with special versions/debug if it it helps.

**Environment**
- Version of Kiwix Android :  2.4 Build:55 (from F-Droid)
- Device : Samsung Galaxy S3 GT-i9300
- OS version : LineageOS-Version 14.1-20190217-NIGHTLY-i9300
- files: wikipedia en 2018-10 and de-2018-11

**Comment by kelson42** [comment]
@JensKorte Thank you for your report, would you please be able to tell us if the problem still occur with the version 2.5.3?

**Comment by JensKorte** [comment]
I switched from F-Droid Kiwix 2.5.1 to Yalp-Store Wikipedia 2.5.3 and had still the same problem. With 2.5.1 and 2.5.3 I have a problem to open the splitted WP german 2019-08 all maxi novid. With 2.5.3 the splitted file worked once.

The md5sum of the big file after copying to SD-Card was Ok.

**Comment by kelson42** [comment]
@JensKorte Thank you for your feedback. We don't support anymore splited ZIM files like in the past. Are all the files you have problem with splited?

**Comment by JensKorte** [comment]
No, I removed the splitted version copied the whole file on the SD card. Afterwards I copied the splitted file again.

**Comment by kelson42** [comment]
@JensKorte Thx, give around month to tacle your ticket properly.

**Comment by kelson42** [comment]
@JensKorte We want to release 3.0 soon and think this bug might have been fixed with this new version. Would you be able to test it in beta? You should join the beta testers group here https://play.google.com/apps/testing/org.kiwix.kiwixmobile

**Comment by JensKorte** [comment]
I downloaded 3.0.2 from download.kiwix.org and now I have no problems with big files. How about closing this report in 1 week? Till then I will have used kiwix some time.

**Comment by kelson42** [comment]
@JensKorte Great to hear. I would better close the ticket now, but feel free to reopen it... or maybe an other one if you find other weird behaviours.
