### ISSUE TITLE
Access A Deleted File After Closing All Tabs

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1034]
**Describe the bug**
After you've deleted a ZIM file, you can re-access it by going to the tab overview, closing all tabs, and then clicking on the <img src="https://user-images.githubusercontent.com/32238400/52534452-9703c980-2d67-11e9-9f6a-9573ffb95576.png" height="20" width="20"> button

**Expected behavior**
* It should not be possible to close all tabs as @mhutti1 suggested this earlier.
* When user tries to close the last opened tab, a new tab such as default tab that opens now after 1500ms should open immediately. So, that the user is not able to open the previous file using the <img src="https://user-images.githubusercontent.com/32238400/52534452-9703c980-2d67-11e9-9f6a-9573ffb95576.png" height="20" width="20"> button.

**Steps to reproduce the behavior:**
1. Delete a ZIM File
2. Go to tab overview,
3. Close all tabs.
4. Click on <img src="https://user-images.githubusercontent.com/32238400/52534452-9703c980-2d67-11e9-9f6a-9573ffb95576.png" height="20" width="20"> button
5. You will be able to access the deleted file.

**Screenshots**
<img src="https://user-images.githubusercontent.com/36811908/53424616-506bcb80-3a05-11e9-97f1-d89a75e3eefd.gif" height="700" width="394">

**Environment**
Galaxy Nexus API 24

**Comment by prajurock** [comment]
Yeah I notice now.I didn't reproduce that bug.Good Luck
