### ISSUE TITLE
Material Design for CloseAllTab FAB not followed

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1040]
**Describe the bug**
Material design is not followed in the CloseAllTabs FAB. Material design says 
*An app’s color scheme determines its color fill, which should contrast with the area behind the FAB.* 
The black background used dissolves its boundary and when the user press it, the action triggered is not visible.

**Expected behavior**
CloseAllTabs floating action button should have black color on a white background. It would be nice if animation could also be added to show all tabs closed as shown below.

**Steps to reproduce the behavior:**
1. Open the main screen.
2. Press tab switcher icon on the action bar.

**Screenshots**
![closeallwebview](https://user-images.githubusercontent.com/34706326/53684482-e53b3580-3d33-11e9-9b56-730b98afdc3e.gif)

**Environment**
- Version of Kiwix Android : Build 55
- Device : Redmi 4
- OS version : Android 7.1

**Comment by abdulwd** [comment]
You can change the color of FAB to white and add an animation.

**Comment by sonusourav** [comment]
> 
> 
> You can change the color of FAB to white and add an animation.

@abdulwd Please assign me to this.
