### ISSUE TITLE
Search option in FindInPage does not work upon switching tabs

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1041]
**Describe the bug**
When multiple pages in different tabs of the same file are open and user searches for some text using FindInPage option, text is only searched in the tab in which search was triggered, even if user switches the tab.

**Expected behavior**
Text should be searched in the tab which is open.

**Steps to reproduce the behavior:**
1. Open mutiple tabs of the same files.
2. Press FindInPage and search for some text.
3. While searching, switch tabs.
4. The app still searches in the tab in which seach was initiated.

**Screenshots**
![findinpage](https://user-images.githubusercontent.com/34706326/53685108-5e3e8b00-3d3c-11e9-8e0b-a426116114ba.gif)

**Environment**
 -  Version of Kiwix Android: 2.4 Build 55
 -   Device: Redmi 4
 -  OS version: Android Nougat 7.1

**Comment by mhutti1** [comment]
Imo Find in page should replace the top bar but idk
