### ISSUE TITLE
Search button disappears when search option in action menu bar is selected

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1042]
**Describe the bug**
In Bookmark/History page, when a user presses search button present in action bar, and types the text followed by selecting Search option from the action menu, search button disappears upon pressing back arrow button or closing search bar.

**Expected behavior**
Search option should be still present after pressing back arrow button in action bar.

**Steps to reproduce the behavior:**
1. Open Bookmark/History page.
2. Press search icon and type some text.
3. Select the search option from the action menu (three dots in action bar).
4. Press the back arrow button or cross button. The search icon and search option in the action menu both disappear.

**Screenshots**
![search_disappears](https://user-images.githubusercontent.com/34706326/53685329-1a00ba00-3d3f-11e9-8f61-626fd372d5a5.gif)

**Environment**
- Version of Kiwix Android : Build 55
- Device : Redmi 4
- OS version : Android Nougat 7.1

**Comment by mhutti1** [comment]
I'm a bit confused. Could you explain the expectedd behaviour a bit more?

**Comment by sonusourav** [comment]
@mhutti1  The search icon which is present when bookmark activity is opened hides when the above steps are followed. But, this should not happen i.e it should not disappear.

**Comment by sonusourav** [comment]
@mhutti1 Please review this.
