### ISSUE TITLE
Contents of TableDrawer not visible

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1047]
**Describe the bug**
The headings and sub-headings of TableDrawer are not visible in day mode. But it works fine in night mode.

**Expected behavior**
The headings and sub-heading should be clearly visible. All levels of text colors of drawer items for day mode should be defined in styles.

**Steps to reproduce the behavior:**
1. Open any Zim file.
2. Swipe left to open the drawer.
3. The Headings and sub-headings are not visible.

**Screenshots**

![navigation_drawer](https://user-images.githubusercontent.com/34706326/53721623-b20aba80-3e89-11e9-9d5d-051ca49de2dd.gif)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Android Nougat 7.1

**Comment by iadeelzafar** [comment]
I was also curious of this weird behaviour. I'm glad you opened a ticket for this issue.
