### ISSUE TITLE
History is cleared even when no history is present

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1058]
**Describe the bug**
In history activity, even when no history is present if the user selects clear no history, the Toast says *All history cleared*.

**Expected behavior**
The Toast should be **No history present**.

**Steps to reproduce the behavior:**
1. Open history and select Clear History from the overflow menu.
2. Once again, select Clear history.
3. Toast says **All history cleared**.

**Screenshots**
![clearhistory](https://user-images.githubusercontent.com/34706326/53784525-9102a200-3f3b-11e9-8811-cc59601f1867.gif)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Android Nougat 7.1

**Comment by ritik2017** [comment]
I would like to work on the issue

**Comment by abdulwd** [comment]
Instead of making a different toast hide the option from the menu.

**Comment by kelson42** [comment]
@mhutti1 @abdulwd @macgills Do we really need that? I'm not sure this is really worth it.

**Comment by macgills** [comment]
I will admit to being largely indifferent. it is a good first issue though

**Comment by kelson42** [comment]
@mhutti1 @abdulwd @macgills Do we really need that? I'm not sure this is really worth it.

**Comment by kelson42** [comment]
After discussing with @macgills we want the following:
* Remove the menus
* Create an icon in the topbar to enable/disable the display of all (versus current) book/tab history
* Replace the 3dots menu with a simple trash icon. The click on trash should simply delete what is displayed.

**Comment by abdulwd** [comment]
@kelson42 IMO I think we don't need it.

**Comment by devanshi7799** [comment]
can i work on this?

**Comment by kelson42** [comment]
@devanshi7799 Yes, you are welcome.

**Comment by devanshi7799** [comment]
@kelson42 Thank you so much :)

**Comment by devanshi7799** [comment]
can you tell me how to claim this issue?

**Comment by macgills** [comment]
@devanshi7799 you are now assigned

**Comment by devanshi7799** [comment]
@macgills I have worked on the issue but when i am trying to make a pull request it is showing me some error. Can you help me solve it?

**Comment by kelson42** [comment]
@devanshi7799 What happens exactly?

**Comment by devanshi7799** [comment]
@kelson42 
![Screenshot 2019-12-19 at 12 11 44 PM](https://user-images.githubusercontent.com/51824493/71150972-cf621700-2258-11ea-8388-2101b81eae2f.png)

It is showing me this type of error

**Comment by kelson42** [comment]
@devanshi7799 OK, this is a compilation error. This is not related to a PR I believe. To make a PR, you just need to https://github.com/kiwix/kiwix-android/pulls. @macgills will try to help you witin a few hours.

**Comment by abdulwd** [comment]
It seems like pre-commit hook is failing. @devanshi7799 Are you able to build & install this app?

**Comment by devanshi7799** [comment]
@abdulwd yes, the application is running perfectly fine on my phone

**Comment by abdulwd** [comment]
@devanshi7799 Try to commit using command line `git commit -m <some-message>` and then check why the pre-commit hook is failing. If you're not able the figure that out then paste those logs here.

**Comment by devanshi7799** [comment]
![Screenshot 2019-12-19 at 8 51 19 PM](https://user-images.githubusercontent.com/51824493/71185373-53d88800-22a1-11ea-9d58-86f6c48f6967.png)
 
@abdulwd it is showing this.

**Comment by macgills** [comment]
one of these tasks is failing
```
gradlew ktlintCheck app:lintDebug core:lintDebug custom:lintCustomexampleDebug
```
run them in terminal and post the output here.
Also verify you do in fact have the file `custom/src/customexample/info.json`

**Comment by macgills** [comment]
Ah no it is just that you don't have JDK8 installed
>If the build failed for another reason please make sure JAVA_HOME is set to JDK8

**Comment by macgills** [comment]
I'm gonna update that message to be way more prominent

**Comment by devanshi7799** [comment]
@macgills is it necessary to have JDK version set to 8? or higher version is okay?

**Comment by macgills** [comment]
8 is absolutely necessary. Higher is not, android does not support it

**Comment by devanshi7799** [comment]
@macgills can you guide me and tell me why the checks are failing?
