### ISSUE TITLE
History not cleared completely

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1061]
**Describe the bug**

History is not cleared completely when history is cleared using *Clear history* from overflow menu if  *History from current book* is checked. Only history of that page is cleared.

**Expected behavior**
Whole history should be cleared. If this is how it is intended to work then the *Clear history* should be replaced with some other text like *Clear List* ( clears only whatever is present in current history list)  which tells more clearly what it actually does.

**Steps to reproduce the behavior:**
1. Open History page.
2. Check *History from current book* and then clear history.
3. Uncheck *History from current book* and rest history could be seen.

**Screenshots**
![historynotcleared](https://user-images.githubusercontent.com/34706326/53834234-7d455300-3fb0-11e9-8244-7af7bb2443cc.gif)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Nougat 7.1

**Comment by sonusourav** [comment]
@abdulwd @mhutti1 @soloturn how should it work?

**Comment by vkk2018** [comment]
@sonusourav ,the error is not seen on my device.I think you should check your system configurations.

**Comment by abdulwd** [comment]
@sonusourav It is intended to work like this.
