### ISSUE TITLE
Sections not expanding on opening from Nav bar

### ISSUE THREAD

**Issue by ritik2017** [kiwix/kiwix-android#1064]
**Description**
The collapsed sections does not expand on jumping to them from the navigation drawer.

**Expected behavior**
The collapsed sections should expand on opening it from the navigation drawer and the other sections should be collapsed.

**Steps to reproduce the behavior:**
1. Open any file containing the sub-sections in its bottom.
2. Open the navigation drawer.
3. Jump to the sub-section from the drawer.
4. The sections does not expand.

**Screenshots**
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/33036254/53884890-8bdc4a80-4042-11e9-98bd-4f762d88d921.gif)

**Environment**
- Version of Kiwix Android :  2.4 Build 55
- Device : Redmi Note 4
- OS version : Android 7.0

**Comment by ritik2017** [comment]
@abdulwd Is the app expected to behave this way?

**Comment by sonusourav** [comment]
@ritik2017  I too observed that but I think that's the problem with the kiwixLib. That has nothing to do with android or navbar. Even if you will open it generally without using navbar, this happens. @kelson42 @mhutti1 @soloturn could give a better answer.

**Comment by abdulwd** [comment]
@ritik2017 Can you check how does the Wikipedia do it?

**Comment by ritik2017** [comment]
@abdulwd The Wikipedia behaves the way I suggested. It expands the subsections on moving to them through the navbar

**Comment by abdulwd** [comment]
@ritik2017 Then you should work on it.

**Comment by ritik2017** [comment]
Working to resolve the issue

**Comment by kelson42** [comment]
This is a serious usability problem. I see no good solution without using the new to be implemented ZIM JS API.

**Comment by shotintoeternity** [comment]
Really appreciate all of your hard work on this project, but this software isn't currently functional if users can't expand different sections and read them. The issue is also occurring on Chrome on Windows 10 x64.

**Comment by kelson42** [comment]
Duplicate of #309
