### ISSUE TITLE
Dropping down animation for sub-sections

### ISSUE THREAD

**Issue by ritik2017** [kiwix/kiwix-android#1065]
**Describe the bug**
On clicking the collapsed sub-sections it open with a blink.

**Expected behavior**
The sub-sections should open with a dropping down animation instead of a blink.

**Steps to reproduce the behavior:**
1. Open any file with sub-sections in bottom.
2. Open the sub-sections by clicking on them.
3. Sub-sections open with a blink.

**Screenshots**
Current Behavior - 
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/33036254/53888374-5c314080-404a-11e9-93ac-f44f5e94461e.gif)

Enhancement - 
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/33036254/53888466-96024700-404a-11e9-9d91-9bf10b157f99.gif)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi Note 4
- OS version : Android 7.0

**Comment by ritik2017** [comment]
@abdulwd @mhutti1 Can this be an enhancement to the existing behavior?

**Comment by mjthompson2** [comment]
I would like to work on this.

**Comment by ritik2017** [comment]
@mjthompson2 Please go ahead

**Comment by mhutti1** [comment]
Imo this should be done in Javascript/CSS @kelson42 ?

**Comment by mjthompson2** [comment]
I will have to drop this unforunately.  I need to switch my attention to a
school project.

**Comment by kelson42** [comment]
This is a request for MWoffliner IMO.
