### ISSUE TITLE
App exits onBackPressed from first page of Zim file

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1067]
**Describe the bug**
When a user is in the first page of any Zim file and the user presses the back button, app exits. To open a new book,everytime he/she has to open a new tab which is not a good user experience.

**Expected behavior**
If a user is in the first page (or user can't go backward), onBackPressed user should land up in the Main screen where books are listed.

**Steps to reproduce the behavior:**
1. Open a Zim file.
2. Go to the first page by pressing back arrow in the bottom toolbar or back button.
3. Press the back button and app exits.

**Screenshots**
![appexits](https://user-images.githubusercontent.com/34706326/53931674-32186680-40bc-11e9-9fbc-d25b97abcbfc.gif)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Android Nougat 7.1

**Comment by iadeelzafar** [comment]
@sonusourav I opened #935 for the same cause. I thought adding an up button would've been the solution that would take the user back to the default tab. But @mhutti1 suggested not to add the up button for it. Now, I'm thinking that we can use the bottom toolbar "HOME" icon to open the Default Tab everytime it is pressed(currently, it opens the home page of the book). What do you think?

**Comment by abdulwd** [comment]
@iadeelzafar The home icon should take the user to the home page of the ZIM file this is the expected behavior. @sonusourav I don't think this is an issue if you open a link in Google Chrome from some other app and press back the browser will be closed.

**Comment by iadeelzafar** [comment]
@abdulwd How about we implement it this way. When the user clicks on the HOME icon and the user is already on the HOME Page i.e. The Home Page of the ZIM File, the user should be taken back to the Default Tab. 
So, the user will only be taken back to the Default Tab in case when the user is already on the HOME Page of the ZIM File and clicks on the HOME icon.

**Comment by iadeelzafar** [comment]
Otherwise, the HOME icon should be grayed and disabled, when the user is already on the Home Page.

**Comment by sonusourav** [comment]
@abdulwd  I did not get the meaning of this line `open a link in Google Chrome from some other app and press back the browser will be closed`. Do you mean, let's say open facebook from chrome and then press back, app exits without landing home screen? If this is what you mean, then I think Google chrome does not do what you told. Infact it does the same what I am requesting for. 

![chrome](https://user-images.githubusercontent.com/34706326/53970494-dc29da00-4120-11e9-8c32-1a5464d6354c.gif)

Here the three links on the gif (fb, youtube and wikipedia) can be considered similar to Zim files. When user presses back button on the first page ( when he/she can't go back), he/she land on the main screen where list of links are present.
I just want to add a back to main screen feature on pressing back button of mobile ( not arrow button on tookbar) if user is in the first page. 
But still, the final decision lies with you and the maintainers @mhutti1 @kelson42 @soloturn .
@iadeelzafar I think we should not confuse users with the dual use of home button. Simply back press would be fine.

**Comment by abdulwd** [comment]
@sonusourav Suppose you open a link from WhatsApp in Google Chrome and then press back the browser is closed. This is what I meant.
@iadeelzafar I agree with @sonusourav, we should not confuse the user with such behaviour of home button.

**Comment by iadeelzafar** [comment]
@sonusourav I got your point. I think the HOME icon should be grayed and disabled, when the user is already on the Home Page. What's your opinion about this @abdulwd.

**Comment by sonusourav** [comment]
@abdulwd  So, in our case isn't 
Zim files ----> links in Whats App
and Web view screen ---> Google Chrome?
Consider this, when you open a link in whats app, it takes you to google chrome and then when you press back button in the first page of chrome(when no more it can go back), you are back to Whats App.You don't exit Whats App when back button is pressed in google chrome, correct?

That is what I am telling, when the user presses back button on the first page of web view ( browser), he/she should land up on the home screen (Whats App).

**Comment by abdulwd** [comment]
@sonusourav I got your point. @mhutti1 I think you should give your opinion on this.

**Comment by mhutti1** [comment]
In my opinion this is the correct behaviour and until we have multizim implemented back should exit the app.

**Comment by kelson42** [comment]
Yes, this is a feature, not a bug.
