### ISSUE TITLE
Create Test ZIM file

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#107]
Create a small (< 1MB) ZIM file for testing that can be added to the repository. It should contain features that a normal ZIM file would.

**Comment by kelson42** [comment]
@mhutti1 Please let me know the requirements you have and I will prepare one (with a montly update) ASAP. Let me know what you have in mind, we can easily then upgrade it with additional kind of content.

**Comment by mhutti1** [comment]
@kelson42 For now it should be as small as possible while containing images and text. Other features should come later.

**Comment by kelson42** [comment]
@mhutti1 So one article ZIM file would be good enough?

**Comment by mhutti1** [comment]
I think that at least 3 would be good.

**Comment by kelson42** [comment]
It's here http://download.kiwix.org/zim/wikipedia/wikipedia_fr_test_2017-07.zim.

A new version should be generated each month.

**Comment by kelson42** [comment]
The corresponding permalink is download.kiwix.org/zim/wikipedia_fr_test.zim (will work in the next hours).
