### ISSUE TITLE
Online tab should show no internet when on data and wifi only option is enabled

### ISSUE THREAD

**Issue by waahm7** [kiwix/kiwix-android#1074]
**Describe the bug**

Online tab shows loading icon when user is using data and Download content via Wifi only is enabled.

**Expected behavior**

It should show no internet connection or disable wifi only option.

**Steps to reproduce the behavior:**
1. Enable Download Content Via Wifi Option
2. Disable Wifi
3. Turn on Mobile Data
4. Goto Online tab

**Screenshots**

![1](https://user-images.githubusercontent.com/7613045/54084510-5cd01c80-4353-11e9-98b9-80e72e327bfb.png)
![2](https://user-images.githubusercontent.com/7613045/54084512-5f327680-4353-11e9-9768-b6e04e9cd6ec.png)

**Environment**
- Version of Kiwix Android : 2.4 
- Device : Nokia 6.1
- OS version : 9

**Comment by sonusourav** [comment]
@waahm7  I may not be correct but what I could figure out from the switch text is, it is intended to confirm for wifi vs mobile use only for downloading books, and not for fetching the list of files. @abdulwd and @mhutti1  could give better answer.

**Comment by waahm7** [comment]
@sonusourav After a while it just says no item found and does not even fetch the list.

**Comment by sonusourav** [comment]
@waahm7  The app can use your mobile data( provided mobile data is on) to fetch books but when it comes to downloading it depends on the permission of the user which one to use. 
Many times, it does not load because of network issues but this is how it made to work.
