### ISSUE TITLE
Add more filters/search capabilities in the library

### ISSUE THREAD

**Issue by sidkathuria14** [kiwix/kiwix-android#1077]
The application currently has the feature to search using a language filter. I suggest there could be other factors added as well for better User Experience. Some of these filters could be Size of Zim, Popularity, has media content or not.

**Comment by sidkathuria14** [comment]
Also, I would like to request it to be assigned to me, if it is considered a good feature to be worked upon.

**Comment by scopulorum** [comment]
I was about to add a feature request for the same until I found this. What is the status? This seems very important, particularly to new users. The current searchability is quite poor , particularly if you don't know the keywords (e.g. "maxi") in advance. Checking a language doesn't actually restrict results.

**Comment by macgills** [comment]
Checking a language partitions results, the results get divided into 2 sections "Selected Languages" & "Other Languages".

As regards this feature it is important to us but requires migration to a new endpoint and it will require reworking of various parts of the app. It is very much on our roadmap

**Comment by kelson42** [comment]
To me the prio are:
* Category
* Content type (has media content or not)
* Popularity (not possible for now but important)

**Comment by kelson42** [comment]
I really think we need to support filtering by categories and flavours. For the rest in the original description, I’m not in favour because:
* this would complexify much the UI
* This should not really be necessary, most of the pertinence stuff should be decided in the library.kiwix.org. Maybe a few oth global settings could appear
