### ISSUE TITLE
Floating Action Button for Scroll to top.

### ISSUE THREAD

**Issue by sidkathuria14** [kiwix/kiwix-android#1078]
If Bottom Toolbar is enabled, then the toolbar overlaps back to top button. Therefore, I suggest adding a FAB(Floating Action Button) on the Bottom Right area of the screen (above the bottom toolbar).
I also thought of adding another FAB for scrolling to top. Both the FAB's would be at bottom right similar to this image:
![nvJ3u](https://user-images.githubusercontent.com/29261743/54094549-c5f17780-43c7-11e9-948e-498b7b11d3da.jpg)
 
If it is considered as a viable feature to add, I would like to request it to be assigned to me.

**Comment by prajurock** [comment]
This issue is earlier solved. Check for the latest version of the code.

**Comment by sonusourav** [comment]
@sidkathuria Are you using app from the playstore or repo? Also, just check if the build variant is set to KiwixDebug.

**Comment by sidkathuria14** [comment]
My repo is updated with latest commits and I cannot see a floating action button for scroll to top. 
Anyways, I am suggesting to add 2 floating action buttons: one for scroll to the very top and second to scroll back to the very  bottom.

**Comment by sidkathuria14** [comment]
@sonusourav I am using the app from repo. Is there any issue with the code?

**Comment by prajurock** [comment]
> My repo is updated with latest commits and I cannot see a floating action button for scroll to top.
> Anyways, I am suggesting to add 2 floating action buttons: one for scroll to the very top and second to scroll back to the very bottomi 

> My repo is updated with latest commits and I cannot see a floating action button for scroll to top.
> Anyways, I am suggesting to add 2 floating action buttons: one for scroll to the very top and second to scroll back to the very bottom.

I think there is no need of adding scroll to bottom.

**Comment by sonusourav** [comment]
> 
> 
> My repo is updated with latest commits and I cannot see a floating action button for scroll to top.
> Anyways, I am suggesting to add 2 floating action buttons: one for scroll to the very top and second to scroll back to the very bottom.

![backtoTop](https://user-images.githubusercontent.com/34706326/54103681-51343280-43f3-11e9-928a-5ae8d534378c.jpeg)

BackToTop button is already there. You have to toggle on from settings(default is off). And do any google app has scroll to bottom button?

**Comment by sidkathuria14** [comment]
Pdf readers do have a scroll to bottom button therefore, I thought of adding this feature for better UX. It is okay if it is not considered to be viable, I just added a suggestion. :)

**Comment by kelson42** [comment]
It's done and available in 3.0. Before we had also a similar option which should work as well.
