### ISSUE TITLE
Come up with alternative to mocking file system

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#108]
Its impracticable to mock the file system but we also need to sandbox some of our device tests so they are not conflicting with other ZIM files already on the device. This might be done by setting up a test ZIM folder and restricting file scans to this.

**Comment by mhutti1** [comment]
The best way of doing this seems to be to inject a FileSearch object.

**Comment by kelson42** [comment]
@macgills Here again we are around automated testing. I'm not sure exactly here what kind of problem @mhutti1 wants to fix.

**Comment by macgills** [comment]
The unit tests of FileSearch are validating that functionality so a mock FileSearch is probably the avenue to go? I'd need to consider the code for a bit.
I am pretty uniformly against most automated tests hitting any external dependency, file system/endpoint/database etc as we should be testing our rendering handles expected input

**Comment by macgills** [comment]
I don't think we have need of this, we have unit tests to guarantee FileSearch.
Maybe if we write a massive e2e test? 
With #1212 nearly merged there is a pretty easy mechanism to supply your own mocks/fakes to an activity if you need to.

**Comment by mhutti1** [comment]
Ok I think we can close this then.
