### ISSUE TITLE
Saving scroll position in SharedPreferences.

### ISSUE THREAD

**Issue by sidkathuria14** [kiwix/kiwix-android#1080]
**Is your feature request related to a problem? Please describe.**
When we exit the app and re-open a Zim file which we were reading earlier, the view loads starting from the very top. If the file loads and starts from the same position where the user left earlier, the UX would significantly improve.
**Describe the solution you'd like**
I am suggesting to save the scroll view of a Zim file when the user exits the application or goes to another activity. When the user again opens the same file, the view would load at the same position so the user can start reading from where he left earlier.
I have thought of some approaches to tackle this problem and would like to work on it if approved.

**Comment by Frans-Lukas** [comment]
I can not replicate the behavior that you are describing. When opening a zim file and scrolling in it and then restarting the app: The scrollbar is in the same position as before the app was closed. However, if I open a zim file, scroll a bit, click the home button in the app and then open the zim file again: The scrollbar is reset.

### Scroll position is restored when:

1. Start kiwix app.
2. Open zim file.
3. Scroll to other position than initial scroll position.
4. Close kiwix app.
5. Start kiwix app.
6. The scroll position is the same as after before closing the app (before step 4, after step 3).

### Scroll position is reset when:

1. Start kiwix app.
2. Open zim file.
3. Scroll to other position than initial scroll position.
4. Go back to home view. (Press the 'home' button)
5. Open the zim file again. 
6. The scroll position is at the 'default' scroll position. That is, same scroll position as before step 3. 

Is this the correct behavior or should the scroll position **_never_** reset for each individual zim file?

**Comment by macgills** [comment]
Scroll position should be retained on activity resume or restart. From a few rapid experiments on my side this is the case.

"closing the app" is imprecise terminology
 you can press back to finish your current task in an app, 
you can while in the overview screen swipe or tap x and this behaviour is _undefined_ and varies per manufacturer,
you can force close an app in the settings.

I am not sure what you are describing when you say "home view", do you mean pressing the actual device's home button? If you have left a zim file open and then navigate to device home screen and return to the app either by pressing the launcher icon or clicking the task in the overview screen you will be shown the zim file exactly where you left off. If you were then to go to the Library and select the same zim it would "reopen" this zim as a fresh instance and leave you on the home page of that book.

To me it looks like there is nothing to be done here but maybe I have misunderstood the feature.

relevant code snippet
```
 private fun restoreTabStates() {
    val settings = getSharedPreferences(PREF_KIWIX_MOBILE, 0)
    val zimFile = settings.getString(TAG_CURRENT_FILE, null)
    val zimArticles = settings.getString(TAG_CURRENT_ARTICLES, null)
    val zimPositions = settings.getString(TAG_CURRENT_POSITIONS, null)

    val currentTab = settings.getInt(TAG_CURRENT_TAB, 0)

    if (zimFile != null) {
      openZimFile(File(zimFile))
    } else {
      Toast.makeText(this, "Unable to open zim file", Toast.LENGTH_SHORT).show()
    }
    try {
      val urls = JSONArray(zimArticles)
      val positions = JSONArray(zimPositions)
      var i = 0
      currentWebView.loadUrl(reformatProviderUrl(urls.getString(i)))
      currentWebView.scrollY = positions.getInt(i)
      i++
      while (i < urls.length()) {
        newTab(reformatProviderUrl(urls.getString(i)))
        currentWebView.scrollY = positions.getInt(i)
        i++
      }
      selectTab(currentTab)
    } catch (e: Exception) {
      Log.w(TAG_KIWIX, "Kiwix shared preferences corrupted", e)
      // TODO: Show to user
    }
  }
```

**Comment by Frans-Lukas** [comment]
> you can press back to finish your current task in an app,

> you can while in the overview screen swipe or tap x and this behaviour is undefined and varies per manufacturer,

These two are what I meant. Did not know that the overview screen swipe to close/ tap x was defined per manufacturer. 

> If you were then to go to the Library and select the same zim it would "reopen" this zim as a fresh instance and leave you on the home page of that book.

This is also what I meant. That is, going 'back' to the library via the in-app 'home' button and 'reopening' the zim as a fresh instance. 

> To me it looks like there is nothing to be done here but maybe I have misunderstood the feature.

I agree that there is nothing to be done here.

**Comment by macgills** [comment]
Marvelous, I will close this ticket. @sidkathuria14 if I have mangled your original point please do reopen it
