### ISSUE TITLE
Adjusting order of zim files in device

### ISSUE THREAD

**Issue by sidkathuria14** [kiwix/kiwix-android#1081]
**Is your feature request related to a problem? Please describe.**
I am adding a suggestion to list the files in the device in a manner such that the files recently accessed are listed on top because those files have a high probability of being opened again by the user.

**Describe the solution you'd like**
I plan to save the recently opened files in the shared preferences along with the count.  When the showFiles() function is called, I plan to reorder the mFiles list to show the files first which have been opened recently and the maximum number of times.

**Additional context**
![Screenshot_20190312_184958](https://user-images.githubusercontent.com/29261743/54203306-0d772100-44f8-11e9-848d-62cf5fe2d8b0.jpg)

Like in this screenshot, if Wiktionary is opened more often by User, it should be listed prior to Granblue.
If it is considered to be a good upgrade, I would like to work upon it.

**Comment by waahm7** [comment]
I think alphabetical order makes more sense, otherwise, the user will have a hard time finding a less used entry.

**Comment by sidkathuria14** [comment]
I have written the code to swap the recently opened zim file with the 0-index file in the arraylist. I feel that the recently opened should be on top. After the first file, all the files are listed in alphabetical order.

**Comment by abdulwd** [comment]
@sidkathuria14 There must be material guidelines on what basis the items in a list should be sorted. Please do check them.

**Comment by sidkathuria14** [comment]
@abdulwd  The code is written such that as soon as a file is found in storage, it is added to the arraylist. There is no particular order followed for listing the files.

![Screenshot from 2019-03-22 22-01-50](https://user-images.githubusercontent.com/29261743/54838491-bab71980-4cee-11e9-8844-79f5c27fc773.png)

The ZIM files are also listed in the same order in which they are found (in the logcat)

**Comment by abdulwd** [comment]
Yes. Suppose according to material guidelines we should list the files alphabetically. You can sort the files on a background thread after the file search is finished. As I have told you before check the material guidelines on what basis we should sort the books.

**Comment by sidkathuria14** [comment]
Where are the material guidelines written?

**Comment by abdulwd** [comment]
https://material.io/

**Comment by sidkathuria14** [comment]
![Screenshot_20190325_072650](https://user-images.githubusercontent.com/29261743/54890472-8d759180-4ecf-11e9-8655-297233de30a2.jpg)
Yes, I think we should sort the list alphabetical wise.
Also Should I work on sorting the list in the current Pull Request itself or would that be merged and I create another PR?

**Comment by mhutti1** [comment]
I don't think this is needed.
