### ISSUE TITLE
Improve Settings Urdu Language 

### ISSUE THREAD

**Issue by waahm7** [kiwix/kiwix-android#1083]
**Is your feature request related to a problem? Please describe.**
If you change the application language to Urdu, Most of the text is still displayed in English. 

**Describe the solution you'd like**
I would like to improve the translation of Settings screen So that it displayed in Urdu.

**Screenshots**
![53604395_2292074684450130_2404187460960518144_n](https://user-images.githubusercontent.com/7613045/54424588-0ab53f80-4735-11e9-92ae-b26d3680c791.png)
![54198805_409056946340256_4236646179900751872_n](https://user-images.githubusercontent.com/7613045/54424600-10ab2080-4735-11e9-9a8f-16993cc62de8.png)

**Comment by mhutti1** [comment]
This isn't an issue with the app. If you want to improve our translation head to translatewiki.net
