### ISSUE TITLE
Adding Online search option for Wikipedia Pages

### ISSUE THREAD

**Issue by ritik2017** [kiwix/kiwix-android#1084]
**Is your feature request related to a problem? Please describe.**
Having two apps(Kiwix and Wikipedia) in my device always causes some irritation. I love the way kiwix delivers me the wiki pages but at the same time not able to find all wiki pages in kiwix.

**Describe the solution you'd like**
 To load a file from wikipedia if there is no search result for the querry and the user has internet connection.

**Describe alternatives you've considered**
Manually adding zim files to kiwix server but everyday thousands of wikipedia pages are added .

**Comment by ritik2017** [comment]
@abdulwd @mhutti1 
What are your opinions regarding the issue ?? 
I am very much interested in working upon the issue

**Comment by sidkathuria14** [comment]
We could implement MediaWiki API as Wikipedia is built on MediaWiki API and it is completely free and open source as well. User's search keyword could be searched on MediaWiki API as well and the related pages could be shown to the User. What do you think? @abdulwd @ritik2017

**Comment by mhutti1** [comment]
This sounds interesting but its likely the backend would be built out in C++ as its a large change.

**Comment by sidkathuria14** [comment]
Yes working on JNI would be efficient but it can also be implemented in Java itself using a library like Retrofit or Volley.

**Comment by ritik2017** [comment]
MediaWiki API sounds very interesting. I read the documentation its actually written in PHP. I going through some of the docs I was able to find this https://m.mediawiki.org/wiki/API:Page_info_in_search_results
@mhutti1 @abdulwd what are your views??
Any suggestions

**Comment by mhutti1** [comment]
As I said, it would add a lot of Android specific complexity which we are hoping to avoid where possible.

**Comment by ritik2017** [comment]
@mhutti1 any other way to implement the feature??

**Comment by mhutti1** [comment]
Yes as I suggested it might eventually be built into the c++ kiwix lib library.

**Comment by ritik2017** [comment]
@mhutti1  I went through the repo of kiwix lib library.
Can you please enlighten me on how to link that to the android app?

**Comment by mhutti1** [comment]
It is linked by the JNI. Its a bit fiddly to setup. If you want to compile using your own code you should use kiwix-build

**Comment by kelson42** [comment]
I dont understand the primary problem. It seems that is is difficult to find things, but we don't know what. Therefore I have no clue if at the root of this request there is a bug. My feeling about the idea is pretty much the same as @mhutti1: sounds a bad idea. In favour of closing that ticket with: wontfix.

**Comment by mhutti1** [comment]
Yeah I would label this won't fix for now at least,
