### ISSUE TITLE
To Add Sort / Filters (eg By Size,date) while searching contents  in Library  Enhancement

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1085]
*Version 2.4 Build:1182160*

**If there should be sort/ filters option in library searching in that option all fields should be add there with size ,date,lang all in one button**

**Adding Filter Option at top Left  instead of just lang**
![Screenshot_2019-03-17-15-37-35-96 - Copy](https://user-images.githubusercontent.com/24877361/54488987-ae395800-48cd-11e9-9bf2-4e12feddfc0f.png)

![Screenshot_2019-03-17-15-37-35-96](https://user-images.githubusercontent.com/24877361/54488988-aed1ee80-48cd-11e9-80d0-066fe2acf217.png)

**Comment by sidkathuria14** [comment]
Hey! I have already addressed this issue in #1077.
