### ISSUE TITLE
Intro Should be added for newcomer at starting of app

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1086]
***Or Simply  The help section is not enough***

**It should be added how to use the app and what steps to follw  for a newcomer, because its easy for a developers who are very much aware about function but new users don't view app like that**

Even I'm was really frustrated for mine's first time when i opened this app and to figure out .

**Comment by aadhitya98** [comment]
Yeah.. I also felt the same @gptshubham595 

First I am so was unable to understand the layout. The main content (For eg: Wikipedia/Ted Talks) download screen should be put up as the home screen rather than the details about the app.

**Comment by abdulwd** [comment]
@aadhitya98 You're using an older version of the app from Play Store. Build this repo we do have the downloaded books on the home screen.
![image](https://user-images.githubusercontent.com/20206262/54738327-cf55bd80-4bd9-11e9-9752-df439e8c1cb3.png)

**Comment by mhutti1** [comment]
Closing this as it is not very specific. If you have some specific improvements then please open another issue to suggest them.
