### ISSUE TITLE
Preference List should be added there while searching

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1088]
**There should be the option of selecting preference list to select and get data accordingly and that should be dependent on that person's feld of interest.**
![to](https://user-images.githubusercontent.com/24877361/54490026-6a981b80-48d8-11e9-8247-8699c6d8910f.png)
![Screenshot_2019-03-17-15-37-35-96 - Copy](https://user-images.githubusercontent.com/24877361/54490031-74ba1a00-48d8-11e9-80b6-9968832fb032.png)

*Because its very difficult to get what a person wants in that 100s of documents moreover perason is not sure what to see for getting info about something.*

**Comment by mhutti1** [comment]
What kind of filters would you suggest?

**Comment by gptshubham595** [comment]
Like on basis of  size ,preference, popular

**Comment by gptshubham595** [comment]
Also if a person wants material related to Biology then it will list only those

**Comment by kelson42** [comment]
Revampinf library is 3.2 maingoal.

**Comment by kelson42** [comment]
Duplicate of #1077
