### ISSUE TITLE
There should be the mainpage of the app

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1091]
**There should be a main page of the app that would display the last accessed website in the device can be called a type of history**

andd on clicking back button while reading any of the website it should go to this main page instead of closing of app ,this made app bit frustrating for the users i manually tested this with multiple users (20) and according to that around 18 users were confused and were unable to find how to go the main page and get though the data available for new reading.

**Comment by mhutti1** [comment]
This is in the plan for multizim. Closing this issue as it is covered by that general plan.
