### ISSUE TITLE
Open Home page on closing last tab

### ISSUE THREAD

**Issue by sauravchandra** [kiwix/kiwix-android#1095]
### Describe the bug

When the last tab is closed in Tab switcher, instead of opening the Home page the app remains in the Tab switcher view.

![kiwix](https://user-images.githubusercontent.com/10370619/54592112-b02c2400-4a51-11e9-9cba-7670705089ae.gif)

### Expected behavior:

Closing the last tab should open up Home page. 

*Example behaviour:*

![firefox](https://user-images.githubusercontent.com/10370619/54593221-1023ca00-4a54-11e9-9d0c-806f90fa27a8.gif)

### Steps to reproduce the behavior:
1. Click on Tab switcher icon.
2. Make sure to have only one Tab open. Close rest of them if open.
3. Click on the close button of last tab.
4. Observe the behaviour.
5. App remains in Tab switcher view.

### Environment:
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi Note 4
- OS version : Android 7.0

**Comment by sauravchandra** [comment]
@mhutti1 Can I work on this if this is an issue and not the intended behaviour?

**Comment by sauravchandra** [comment]
@abdulwd Can I work on this?

**Comment by abdulwd** [comment]
@sauravchandra Yes!

**Comment by abdulwd** [comment]
It will be great if you can add the animation for this too. Check out the material guidelines to see which animation to use.

**Comment by kelson42** [comment]
@macgills @abdulwd @siddharth2010 I think this has been fixed in 3.0. I can not reproduce the bug anymore. Could you confirm please?

**Comment by macgills** [comment]
I confirm that the bug cannot be reproduced
