### ISSUE TITLE
Getting error how to resolve this while building

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1096]
![IMG20190319181751](https://user-images.githubusercontent.com/24877361/54607209-d82c7f00-4a73-11e9-8589-95d62f79b8fe.jpg)

**Comment by abdulwd** [comment]
These are only warnings. You can complete the build and install the app.

**Comment by gptshubham595** [comment]
How to remove this warning

**Comment by abdulwd** [comment]
You can search stackoverflow.com/google and make a PR to fix these warnings.

**Comment by shashwatkathuria** [comment]
The first and third warnings are related to the jetifier's experimental settings which may be unused in the built variant and some maybe unsupported. The second warning is related to the server address whose value is being changed, so its not something which is wrong with the application as such. 

The application is working fine without these issues, you can ignore them as the first and third are just kind of additional things and the second is not really an issue.

**Comment by mhutti1** [comment]
Closing this as it is misleading.
