### ISSUE TITLE
Home Screen of Wikipedia looks so clumsy

### ISSUE THREAD

**Issue by aadhitya98** [kiwix/kiwix-android#1097]
**Describe the bug**
The Home screen looks so congested with the frames having unequal size.

**Expected behavior**
A Proper usage of Frame Layout with equal padding may be a better deal

**Steps to reproduce the behavior:**
1. 

**Screenshots**

**Environment**
- Version of Kiwix Android : 
- Device : 
- OS version : 

**Logs**

**Comment by abdulwd** [comment]
A screenshot will better explain this.

**Comment by aadhitya98** [comment]
![WhatsApp Image 2019-03-20 at 9 12 55 PM](https://user-images.githubusercontent.com/38691254/54698595-91af5100-4b55-11e9-995f-ffa3114d0dd4.jpeg)

Here....watch out for Cretaceous ...it is not clearly visible and the size of Charlie Chaplin is dominating over it.

Hence equal padding with proper frame layout placements can wrap up this UI issue.

**Comment by abdulwd** [comment]
Please install the app by building this repo instead of installing it from Play Store and check if this issue persists. Also, we are loading a web page in a web view we are not using any layout.

**Comment by aadhitya98** [comment]
I will work on, building a specialized app for Kiwix instead of using a web view. I would like to take this as my GSOC project 2019 if I am fortunate enough to get selected.
