### ISSUE TITLE
Abnormal behaviour on pressing back on a document. 

### ISSUE THREAD

**Issue by shashwatkathuria** [kiwix/kiwix-android#1100]
**Describe the bug**
On pressing back button on the screen while on a document, the application directs us out of the application. 

**Expected behavior**
It should instead take us to the device tab in the library just like adobe, in which on pressing back button on a document, we are directed to the page where all documents are present/library.

**Steps to reproduce the behavior:**
1. Go to Library -> Device and click on a downloaded document. 
2. Press back button of the device, usually on the bottom of screen. 
3. We are directed out of the application. 

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : OnePlus 6
- OS version : 9.0.4

**Comment by sonusourav** [comment]
Duplicate of  #1067 .

**Comment by shashwatkathuria** [comment]
Ok. Closing the issue.
