### ISSUE TITLE
Ambiguous options in search. 

### ISSUE THREAD

**Issue by shashwatkathuria** [kiwix/kiwix-android#1101]
**Describe the bug**
Almost identical options are displayed in search. The 'No Pictures' and 'No Videos' are also very misleading if one has to get the exact file. 
<img src="https://user-images.githubusercontent.com/37243661/54776282-cbf01f80-4c35-11e9-97a1-ad24bb4905b9.jpg" width="50%">
<img src="https://user-images.githubusercontent.com/37243661/54776285-cc88b600-4c35-11e9-9976-418f42cb8e18.jpg" width="50%">

**Expected behavior**
Same articles should be under one document with two or more unambiguous options like 'Only Pictures', 'Only Videos' or 'Both Videos and Pictures', etc. 

**Steps to reproduce the behavior:**
1. Search on a popular topic
2. Chances of getting same files with near exact and unclear specifications.

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : OnePlus 6
- OS version : 9.0.4

**Comment by abdulwd** [comment]
This can be revamped to look like the home screen.
