### ISSUE TITLE
Separate information tab once a document is downloaded. 

### ISSUE THREAD

**Issue by shashwatkathuria** [kiwix/kiwix-android#1108]
**Is your feature request related to a problem? Please describe.**
The documents once downloaded don't really require the same information to be displayed again and again in the Device tab under Library.

<img src="https://user-images.githubusercontent.com/37243661/54782163-38721b00-4c44-11e9-82e0-d0d1b1877b1d.jpg" width="50%">

**Describe the solution you'd like**
An option for displaying the information regarding the document can be in a specific activity which can be accessed by clicking some button which can take us to its information activity. The information tab will have Fragments like the ones shown in the below images.
<img src="https://user-images.githubusercontent.com/37243661/54782184-41fb8300-4c44-11e9-9d93-5984af1101fb.jpg" width="50%">
<img src="https://user-images.githubusercontent.com/37243661/54782190-4758cd80-4c44-11e9-9ace-3ec9fa8c1cf3.jpg" width="50%">
<img src="https://user-images.githubusercontent.com/37243661/54782201-4d4eae80-4c44-11e9-9021-60b0838dd660.jpg" width="50%">

**Additional context**
On each document list item of downloaded documents, there can be there vertical dots on the right top corner of the document list item so as to access the information realted to the document and maybe also to share the document through WhatsApp, Facebook, Twitter,etc => Another additional feature.

**Comment by abdulwd** [comment]
Do you think we have so much info about a book that we need fragments to display it?

**Comment by shashwatkathuria** [comment]
Then we can have one page regarding the information, rather than the three different pages shown above?

**Comment by abdulwd** [comment]
You should have a look at the code, all the info we get from the backend is displayed. I don't think we have more info to display.
