### ISSUE TITLE
Documents beyond device capacity should not be displayed. 

### ISSUE THREAD

**Issue by shashwatkathuria** [kiwix/kiwix-android#1109]
**Describe the bug**
Documents outside device's capacity are being displayed. Also, clicking on them serves no purpose as the error message is correctly displayed and nothing happens after clicking on them. Only the idle information is visible which serves no purpose as such. ( My device's capacity is 64GB, and the document highlighted below is of 78.1GB )

<img src="https://user-images.githubusercontent.com/37243661/54783088-7ec87980-4c46-11e9-8c81-e3ff6c1d5341.jpg" width="50%">

**Expected behavior**
The documents beyond the capacity of the device should not be displayed.

**Steps to reproduce the behavior:**
1. Go to Online tab under the Library.
2. Scrolling through the documents, some documents are there which are beyond the capacity of the device storage.

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : OnePlus 6
- OS version : 9.0.4

**Comment by abdulwd** [comment]
I don't think it is the correct before. Such items should be shown to let the user know that these books do exists so that they can be download to other devices if needed.

**Comment by shashwatkathuria** [comment]
Then there should be some indication to the user regarding this. Maybe as a small red text on the side?

**Comment by abdulwd** [comment]
A toast is displayed on clicking which serves the purpose.
