### ISSUE TITLE
Tutorial on downloading the application.

### ISSUE THREAD

**Issue by shashwatkathuria** [kiwix/kiwix-android#1110]
**Is your feature request related to a problem? Please describe.**
There is no step by step tutorial or example explanation on how to use the application, which can  help in making the user of the application aware of all its useful features as well as make the user use the application correctly. There are only two pages and one 'GET STARTED' button when the user downloads the application initially and those two pages also just give a high level idea of the purpose of the application, with the 'GET STARTED' button just directing to the library.

**Describe the solution you'd like**
Step by step pop-ups explaining on how to use the application correctly when a user enters a specific activity. Also, alongwith them, indicating with pop-ups the useful features which might not be a part of that activity but nonetheless important.

**Comment by abdulwd** [comment]
Check the material guidelines to see how it should be done correctly.

**Comment by shashwatkathuria** [comment]
Okay.
