### ISSUE TITLE
Add swipe gesture to switch tabs

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#1113]
**Is your feature request related to a problem? Please describe.**
Tab switching must be easier.

**Describe the solution you'd like**
Google Chrome offers a great way to switch tabs by horizontally swiping the toolbar. This gesture should be added.

**Additional context**
![ezgif-1-c045626485ed](https://user-images.githubusercontent.com/20206262/54854609-7f7e1000-4d19-11e9-8475-d61f69a8f0b5.gif)

**Comment by prajurock** [comment]
I want to take the issue but multi zim is supported?

**Comment by sauravchandra** [comment]
It would be a nice UI enhancement. I would like to work on it.

**Comment by sonusourav** [comment]
@abdulwd  We can use Horizontal swipe gesture to do this. Would like to work on this.

**Comment by abdulwd** [comment]
@prajurock Multi zim is not supported but we can switch between different tabs of the same zim file as done using the tabs switcher. You can work on this issue.

@sonusourav Horizontal swipe gesture is to be added only to the toolbar so that the tabs are not changed by mistake.

**Comment by sonusourav** [comment]
@abdulwd  I too meant the same, horizontal swipe gesture for the toolbar not anywhere else.

**Comment by abdulwd** [comment]
@sonusourav I have updated the issue description to make it clear.

**Comment by sauravchandra** [comment]
@abdulwd We need to inflate ActionBar with a custom view in order to detect gestures on it.
