### ISSUE TITLE
Add swipe down animation (was: Add swipe down toolbar gesture to open tabs switcher)

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#1114]
**Is your feature request related to a problem? Please describe.**
The icon for opening the tab switcher is quite small and it is used frequently. So there must be a gesture to open the tab switcher.

**Describe the solution you'd like**
Google Chrome offers a gesture to open the tab switcher which is pull down from the toolbar.

**Additional context**
![ezgif-1-8ad26a80ceb7](https://user-images.githubusercontent.com/20206262/54862483-9f392680-4d61-11e9-9563-8e6c9a8d5da2.gif)

**Comment by ShridharGoel** [comment]
I would like to work on this.

**Comment by abdulwd** [comment]
@ShridharGoel You can work on it.

**Comment by macgills** [comment]
For this to be considered fixed we would require there to be an animation for opening the tab switcher
