### ISSUE TITLE
Offline voice search option enable

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1122]
Can I add offline voice search option in download or file searching

**Comment by mhutti1** [comment]
I don't think this is a worthwhile feature, it adds a lot of complexity for very little gain.

**Comment by gptshubham595** [comment]
But it will be a goog enhancement (By the we are working on improving user experience )

**Comment by mhutti1** [comment]
Yes but it adds a lot of complexity for an offline app. I am going to close this for now.
