### ISSUE TITLE
Can we add a login and sign up form in menu for saving bookmarks in account and connnecting with firebase(OR ANY DATABASE)

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1123]
Can we connect this app to firebase and store the bookmarks to that   persons account so that if he opens that app in some other android so that he can access his saved bookmarks

**Comment by siddharth2010** [comment]
As per the Kiwix website: "Kiwix is an offline reader for online content like Wikipedia, Project Gutenberg, or TED Talks. It makes knowledge available to people with no or limited internet access."

So theres no point for adding cloud functionality in the app, as we are specifically targeting people with limited internet access.
