### ISSUE TITLE
Can we add a share option to share that particular opened at that time 

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1124]
To add a feature of sharing that screen data or the opened at that time.

**Comment by gptshubham595** [comment]
![pinned-share-app](https://user-images.githubusercontent.com/24877361/54932231-7753e980-4f40-11e9-9fda-8737ccb90983.png)

**Comment by gptshubham595** [comment]
Like if we are reading Wikipedia and inside that  we are reading some content and if we want to share that,with specific page no. ,title, website name

Ex. IMAGE and text written below Wikipedia ,TOPIC: Google,PAGE:42

**Comment by siddharth2010** [comment]
We cannot specifically share some pages, as they are bundled together with the ZIM file.

Instead of that we have have the share zim file option using which we can share the whole zim file between devices.

So i think that should suffice.

**Comment by gptshubham595** [comment]
I m also working for hotspot sharing of zim files

**Comment by mhutti1** [comment]
I don't really see what can be shared. A user can copy and paste text to share if they desire. ZIM sharing is another feature with issues dedicated to it.
