### ISSUE TITLE
While clicking on links on any page it redirects to a browser and open that page instead open that inbuilt in that app

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1125]
open the clicked links on any page while reading instead opening that in browser it should open in that app only as a browser , instead of redirecting to any other app.

like : reading wikipedia->CLICK on any hyperLink -> It opens a browser and open that link
It should be:reading wikipedia->CLICK on any hyperLink -> It opens that link inside the app only

**Comment by siddharth2010** [comment]
i think opening in the browser is the preferred way to do it. 
It also gives us extra features like saving pages as pdf, and sharing of opened and bookmarked tabs on the mobile and computer (for specific browsers).

**Comment by Raghav-intrigue** [comment]
But wouldn't that reduce the app retention rate? I agree that there should be an option to open the link in a browser for accessibility, but the current way reduces the retention time by quite a lot since the user moves to the browser just after one link.

**Comment by kelson42** [comment]
Kiwix is a ZIM file browser. Like @siddharth2010 said, this is the intend behaviour to open Web links in a Web browser.
