### ISSUE TITLE
How to resolve this show fragment manager error

### ISSUE THREAD

**Issue by gptrohit** [kiwix/kiwix-android#1127]
![1553603320057109337223](https://user-images.githubusercontent.com/48947469/54997097-f7398c80-4ff0-11e9-8623-f139e97bed5a.jpg)

**Comment by gptshubham595** [comment]
Try invalidate caches amd restart

Do check that:
You have changed build variants changed to kiwix debug

And remove .idea folder before starting

**Comment by gptrohit** [comment]
Thanks it solved
