### ISSUE TITLE
 How to resolve this error

### ISSUE THREAD

**Issue by gptrohit** [kiwix/kiwix-android#1128]
![1553614854565766679018](https://user-images.githubusercontent.com/48947469/55011293-b56a0f80-500b-11e9-8fbf-d1bdf035023f.jpg)

**Comment by gptrohit** [comment]
![1553615409897938728552](https://user-images.githubusercontent.com/48947469/55012147-f9a9df80-500c-11e9-9bb6-c524ccfaee03.jpg)

Is error is related to butterknife library as it says that

 the given artefact contains a string literal with the package reference androidx.support.v4.content that cannot be safely rewritten libraries using reflection such as annotationprocessor' needs to be updated manually to add support for Android X

**Comment by gptshubham595** [comment]
Can you give your stacktrace

**Comment by gptshubham595** [comment]
Do have a look on readme file on how to build the app and do try delete .gradle , .idea and try rebuilding it also do check Build variants to kiwix debug

**Comment by gptshubham595** [comment]
Use butterknife 10.1.0

**Comment by gptshubham595** [comment]
Thank you resolved

**Comment by kelson42** [comment]
@abdulwd Would you be able to have a look to this please? The ticket is unclear to me and it seems there is already a PR... but not sure we have a bug here at all.

**Comment by gptrohit** [comment]
@gptshubham595 ok wait trying all those

**Comment by gptrohit** [comment]
@gptshubham595 thanks it resolved

**Comment by kelson42** [comment]
@gptrohit @gptshubham595 @abdulwd What about the PR #1139?

**Comment by gptshubham595** [comment]
I just updated the versions


And saw that he was reporting error related to butterknife version  which is written 8.8.1 hopefully he would be using old version 

So, and also it worked for him i think

**Comment by gptrohit** [comment]
Yes on updating butterknife version it resolved mines thankyou @gptshubham595 

@kelson42
