### ISSUE TITLE
Improved UI ,Font style and added a light gradient texture 

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1130]
Enhancement:
should i make a PR

![adding gradient to listed files to improve UI and font as openSans used by google in most of its recent apps](https://user-images.githubusercontent.com/24877361/55024321-a3489b00-5024-11e9-9818-05ad8793704a.JPG)
![Capturead](https://user-images.githubusercontent.com/24877361/55024323-a3489b00-5024-11e9-86f7-28bcf43df839.JPG)
![ui](https://user-images.githubusercontent.com/24877361/55024324-a3e13180-5024-11e9-9911-3b158255d167.JPG)

![2](https://user-images.githubusercontent.com/24877361/55025657-6336e780-5027-11e9-99d4-a01aa2e08105.JPG)

Made Title Bold
Used Open Sans Font as it is used by google in most of its recent apps
added a light texture gradient 
added CardView Layout

**Comment by mhutti1** [comment]
This isn't in tune with material design and in my personal opinion looks a bit tacky. If you have more general suggestions I suggest making an issue calling for general discussion.

**Comment by gptshubham595** [comment]
ok Next time i will take care of it
