### ISSUE TITLE
Improved UI,Font Style, Button UI,and background and navbar colour to white

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1131]
Should i PR 
Error page :Improved Font style ,Button style ,background gradient ,and made colour of navbar to white 
![g1](https://user-images.githubusercontent.com/24877361/55024035-0d147500-5024-11e9-8ac6-d105b08d71ca.png)

**Comment by mhutti1** [comment]
As mentioned this is a bit of a dated look and isn't in tune with material design. Please follow our issue template for bugs. "Should i PR" is not an appropriate issue.

**Comment by gptshubham595** [comment]
I was trying to mark it as a enhancement

**Comment by mhutti1** [comment]
Could you please format correctly.

**Comment by gptshubham595** [comment]
wait let me send you the old/earlier screenshot
