### ISSUE TITLE
Improved KiwixWebView .java loadind of url 40% more faster

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1132]
Improved loading of data in KiwixWebView.java
Should i PR

Added this:
   `getSettings().setDomStorageEnabled(true);
    getSettings().setJavaScriptEnabled(true);
    getSettings().setBuiltInZoomControls(true);
    getSettings().setDisplayZoomControls(false);
    getSettings().setRenderPriority(WebSettings.RenderPriority.HIGH);
    getSettings().setCacheMode(WebSettings.LOAD_CACHE_ELSE_NETWORK);
    getSettings().setAppCacheEnabled(true);
    getSettings().setLayoutAlgorithm(WebSettings.LayoutAlgorithm.NARROW_COLUMNS);
    getSettings().setUseWideViewPort(true);
    getSettings().setSaveFormData(true);
    getSettings().setSavePassword(true);
    getSettings().setEnableSmoothTransition(true);
    getSettings().setRenderPriority(WebSettings.RenderPriority.HIGH);
    `

Earlier:
   `getSettings().setDomStorageEnabled(true);`

**Comment by mhutti1** [comment]
Don't ask if you should submit a PR. Make an issue with a bug/feature. Discuss it there and submit a PR with the issue with the changes. I have no idea what the code posted here might do other than broadly increase speed.
