### ISSUE TITLE
Add Peer-to-peer sharing

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#1136]
Google announced they're adding support for peer-to-peer installs and file transfers. Perhaps we can ways to take advantage of what they're providing to help our users install Kiwix, Custom Apps (such as WikiMed), and ZIM files?

Offline peer sharing of app and contents
https://android-developers.googleblog.com/2018/10/offline-p2p-installs-beta.html

Google recommends their own app [Files By Google](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files) and 2 others:
BTW the 2 file sharing apps Google mentions both seem very intrusive so I'd recommend seeking ones that focus on just doing the sharing well, without videos https://play.google.com/store/apps/details?id=com.lenovo.anyshare.gps&e=-EnableAppDetailsPageRedesign or accessing your contacts (and much more besides) https://play.google.com/store/apps/details?id=cn.xender 

Here's a recent review about the intrusive nature of the Xender app. The list of permissions required by the app is incredibly long and invasive too :(
A Google user March 14, 2019
"_Isn't life charming? Xender promises you no ads, and it delivers. Yet it takes your phone number, your identity, your contacts, photos, diaries and everything personal, that you keep away from your own girlfriend, it uploads this to about 10 different websites before you can count to 10. I put this app in an Android virtual machine & like a colleague who can't keep their mouth shut, saw everything it uploaded. then it failed to Sync to my PC_"
Xender TeamMarch 19, 2019
"Hi there, sorry for any issue, Xender can't access to your data without permission and will not do that, also server resources is expensive. Xender only read your contacts when you use the function "Phone replicate" function. :)"

**Comment by Popolechien** [comment]
Agree. I know apk sharing is another order but this seems related to #616

**Comment by mhutti1** [comment]
Certainly related. Might be useful for embedded ZIMS/ custom apps if it correctly transfers expansion files.

**Comment by Aditya-Sood** [comment]
#1276 partially solves this, specifically the part about using the P2P API for transferring ZIM files from one device to another

**Comment by kelson42** [comment]
@julianharty Are you happy with new sharing feature? What should we do next we this ticket?

**Comment by kelson42** [comment]
I'll close that ticket for now.
