### ISSUE TITLE
Creating an application built over the kiwix app that can browse the zim files hosted in another device.

### ISSUE THREAD

**Issue by sayakdutta** [kiwix/kiwix-android#1138]
This is an important feature that can improve offline internet access by large amounts.In this context I have created a proposal that emphasizes on the use of NSD APIs to achieve this connectivity.Any suggestive or helpful criticism is welcome.@mhutti1 what do you think of this proposal?
[gsoc.pdf](https://github.com/kiwix/kiwix-android/files/3021076/gsoc.pdf)

**Comment by sayakdutta** [comment]
Does anyone think that there is a better solution to solving this problem in Android without internet services?

**Comment by mhutti1** [comment]
The current plan is to use a simple web browser as a potential client with the content hosted on a dedicated app. I don't see why we couldn't have a specific client app but it seems a bit unnecessary.

**Comment by sayakdutta** [comment]
@mhutti1 why should we separately develop a hosting app for some device and web browsers for others.Don't you think that we could integrate both services into a single app so that even client devices connected over the same network could save certain wiki pages and host them.In this way we can reduce the load on the hosting device.My proposal aims on implementing that.If you think I am wrong,I am open to suggestions.

**Comment by mhutti1** [comment]
Because we wan't users without internet connection to be able to piggy back of a single user who has downloaded our app and content.

**Comment by sayakdutta** [comment]
No,I mean web browsers would require local IP address of the host which is dynamic and changes everytime connection is timed out,lost or a new connection is established.It would be tedious to find out the IP address and fix it manually everytime.

**Comment by mhutti1** [comment]
Well it can be displayed easilly in the app. It also means that the solution is "turn up and go"

**Comment by mhutti1** [comment]
Closing as this is being implemented by #259
