### ISSUE TITLE
Feature Enhancement:Onscreen Translation

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1142]
Feature enhancement for on screen translation the text 

Like most of the types are available in English so  while adding a feature on menu bar to  translate the page on desired selected language using Google Translator api

**Comment by gptshubham595** [comment]
Like this 
![Screenshot_2019-04-03-16-32-28-76](https://user-images.githubusercontent.com/24877361/55474192-2e7dee00-562e-11e9-8e91-ea53fcaabb04.png)

**Comment by gptshubham595** [comment]
![ezgif-3-acae893458f9](https://user-images.githubusercontent.com/24877361/55474360-8c123a80-562e-11e9-8498-7218b0999197.gif)

**Comment by gptshubham595** [comment]
@mhutti1  @abdulwd  @kelson42  please see this

**Comment by mhutti1** [comment]
This can already be done by using the Google translate button in the action context menu.
