### ISSUE TITLE
Feature enhancement adding bookmark button, as in new version it is not available

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1143]
New version adding bookmark button is not available
![Screenshot_2019-04-03-16-24-07-48](https://user-images.githubusercontent.com/24877361/55473749-135eae80-562d-11e9-93a9-b87faad316dd.png)
![Screenshot_2019-04-03-16-24-10-55](https://user-images.githubusercontent.com/24877361/55473771-16f23580-562d-11e9-82cc-1c1b99afdb16.png)
![Screenshot_2019-04-03-16-24-16-56](https://user-images.githubusercontent.com/24877361/55473780-1c4f8000-562d-11e9-8374-9c8a8e86bc4e.png)

**Comment by gptshubham595** [comment]
@mhutti1 @abdulwd

**Comment by mhutti1** [comment]
I think this is a duplicate of https://github.com/kiwix/kiwix-android/issues/973

**Comment by gptshubham595** [comment]
Earlier it was there but in new version of kiwix after the tabs feature update bookmark feature is not there
