### ISSUE TITLE
Figure out what constitutes a "pass" on testdroid

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#115]
Sometimes devices might become unavailable. If a device isn't available after ~15 mins then our test will time out. We need to consider if we accept the remaining devices outcome in this case or we fully fail.

**Comment by kelson42** [comment]
@mhutti1 Considering that testdroid is part of our CI I suspect we have answered that question?

**Comment by mhutti1** [comment]
Closing as it is being discussed in #110
