### ISSUE TITLE
Feature Ehancement: Convert Material Design png icons into vector assets

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1150]
Should i Work on this
Most image formats (png, jpeg, bmp, gif, webp etc) are raster which means they describe the image as a fixed grid of pixels.
Using Vector assets will have benefits like
Sharp/Vector images Resize gracefully
Small
Dynamic

**Comment by mhutti1** [comment]
What is the minimum SDK for vectors?

**Comment by SubhrajyotiSen** [comment]
Vector Drawables are supported from API 7 (Android 2.3) by using Compat libraries
https://developer.android.com/guide/topics/graphics/vector-drawable-resources

**Comment by soloturn** [comment]
@gptshubham595 yes please ...

**Comment by macgills** [comment]
It should be noted vectors are recommended for uncomplicated images and there are cases where supplying pngs ,or better yet WebPs, is the better solution https://developer.android.com/studio/write/vector-asset-studio#when

**Comment by rajput2122** [comment]
Can i work on this?

**Comment by macgills** [comment]
You are assigned to the issue, happy coding

**Comment by rajput2122** [comment]
i have done this sir .How do i open PR for this issue. I am not able to commit there is error message showing ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

**Comment by abdulwd** [comment]
Install jdk 8 and add JAVA_HOME to your environment variables. May I know which OS you're on?

**Comment by rajput2122** [comment]
I am working on window 10

**Comment by rajput2122** [comment]
i have already installed jdk 8

**Comment by rajput2122** [comment]
Can you please help me to setting this?

**Comment by abdulwd** [comment]
Have a look at this: https://stackoverflow.com/a/47902024/7792129.
