### ISSUE TITLE
FeatureEnhancement: Adding Page curl option on any page intent transition

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1151]
Should i work on this 
![ezgif-3-58c9fcc33469](https://user-images.githubusercontent.com/24877361/55685466-37472a80-5974-11e9-8906-6e8dfdcd3027.gif)

**Comment by sonusourav** [comment]
@gptshubham595  In Kiwix, there isn't any page, rather everything is displayed in webview as one single file. So, I don't think this animation could be used here.

**Comment by gptshubham595** [comment]
on intent to a specific page aniamtion

**Comment by gptshubham595** [comment]
to view transition inside webview
we can use this
`private  void animate(final WebView view){
Animation anim= AnimationUtils.loadAnimation(getBaseContext(),android.R.anim.page_turn_effect);
view.startAnimation(anim);  
}`

**Comment by sonusourav** [comment]
> to view transition inside webview
> we can use this
> `private void animate(final WebView view){ Animation anim= AnimationUtils.loadAnimation(getBaseContext(),android.R.anim.page_turn_effect); view.startAnimation(anim); }`
> 
> `and inside onPageFinished {animate(view);}`

What I mean is the whole file is like one page, and there are no pages inside a file so this animation could not be used.

**Comment by mhutti1** [comment]
As we don't have a concept of pages this would look really gimicky.
