### ISSUE TITLE
BUG:Error on Rotation of screen on new tabs feature

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1152]
on turninig screen rotation and once going back this shows unknow rotations and any tabs opened gets it rotation changed on random

**Comment by gptshubham595** [comment]
https://vimeo.com/328952168

**Comment by gptshubham595** [comment]
@mhutti1 @abdulwd @kelson42 @sonusourav

**Comment by sonusourav** [comment]
Duplicate of #948 . If you want you can work on this, however.
