### ISSUE TITLE
Enhancement of the UI of the card items (library_item.xml)

### ISSUE THREAD

**Issue by ChandanNaik999** [kiwix/kiwix-android#1154]
**Is your feature request related to a problem? Please describe.**
The ui of the card items of the resources (library_item.xml) are not well developed.

**Describe the solution you'd like**
I would like to improve the layout of the library_item

**Additional context**
This is how I designed the UI to be: 
![KiwixMobileActivity – 1](https://user-images.githubusercontent.com/31248010/55690831-23231d80-59b4-11e9-95dc-8b2a43fe2d84.png)

**Comment by ChandanNaik999** [comment]
@siddharth2010 , @abdulwd , @mhutti1 Shall I take on this project?

**Comment by mhutti1** [comment]
We are looking at solving this in a variety of ways. This ticket on its own isn't needed.
