### ISSUE TITLE
BUG:Cannot open two or more book simultaneously + ALSO on opening another book history of previous gets deleted

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1158]
We are delivering offline internet content and while doing that person who is using will definetely need more info maybe like if he is reading stuff about biology inventions then he may need wikitionary,wikipedia(say) simultaneouly
Like if a person is viewing Some Book and want to find realted stuff in wikipedia then on opening wikipedia fom downloaded content all the tabs he opened earlier goes off

**Comment by sonusourav** [comment]
@gptshubham595  Related to #892 .
Actually, this is because Kiwix does not have multizim support as of now. It is a part of big update and will be soon integrated into Kiwix as is said in earlier comments of @mhutti1 .
