### ISSUE TITLE
Execution failed for task ':kiwixlib:verifyReleaseResources'.

### ISSUE THREAD

**Issue by sherlockbeard** [kiwix/kiwix-android#1159]
Error while running gradlew file

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kiwixlib:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2InternalException: AAPT2 aapt2-3.3.2-5309881-linux Daemon #0: Daemon startup failed
  This should not happen under normal circumstances, please file an issue if it does.

**Comment by rajbohra10** [comment]
@sherlockbeard Are you getting this error for **KiwixDebug**  build variant?

**Comment by kelson42** [comment]
No feedback. I close the ticket.
