### ISSUE TITLE
App crash on Library Fragment [online tab] while refreshing and clicking List Items Simultaneously

### ISSUE THREAD

**Issue by CodetoInvent** [kiwix/kiwix-android#1163]
Fix : App crash on Library Fragment [online tab] while refreshing and clicking List Items Simultaneously

steps to reproduce 1: [with refreshing list ]
step 1: open ListFragment [ Online Tab ] where you will find the list of ZIM files
step 2: search let say "Math" then refresh and click list simultaneously app will crash

step to reproduce 2: [without refreshing the list ]
step 1:open ListFragment [ Online Tab ] where you will find the list of ZIM files
step 2:search let say "Math" when list appears add "s" to the searchview ["maths"] and suddenly press the list app will crashes 

This is the link to show how App is Crashing:
https://drive.google.com/file/d/1ktwPWDU4uTDzsi3w5D7tjSo2XlWIyQgD/view?usp=sharing

**Environment**
- Version of Kiwix Android : 2.4 build 55
- Device : samsung j7
- OS version : Android O

**Comment by CodetoInvent** [comment]
I have fixed this issue at PR #1155 . sorry about first fixing and then opening the ticket

**Comment by mhutti1** [comment]
Closing as this should be fixed by 2.5
