### ISSUE TITLE
Zim File List Item Loading Problem in online tab [ LibraryFragment ]

### ISSUE THREAD

**Issue by CodetoInvent** [kiwix/kiwix-android#1164]
Zim File List Item Loading Problem in online tab [ LibraryFragment ]

Short Explanation : we have seen that sometimes or many times online tab will not load the list item within first refresh.
Due to this we are refreshing the list again and again. It is consuming our data.
we need to load the list of books in online tab within its first refresh.

whenever we not see the list view within the first load/refresh that means it is modifying which leads to throw  ConcurrentModificationException.
I have fixed  this Refreshing/loading problem in my PR #1160 
Sorry about first fixing then opening the ticket

**Comment by iadeelzafar** [comment]
Kindly use the provided ticket template.

**Comment by mhutti1** [comment]
This should be fixed by 2.5
