### ISSUE TITLE
New external storage disappears on screen rotation

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1165]
**Describe the bug**
Create a new external storage and it disappears on screen rotation.

**Expected behavior**
State should be saved.

**Steps to reproduce the behavior:**
1.  Go to settings>Storage>External.
2. Click the '+' Button.
3. Rotate the screen.

You will notice that newly created external storage disappears

**Screenshots**
<img src="https://user-images.githubusercontent.com/36811908/56096571-6d9c2100-5f03-11e9-9d4b-eedcedf424da.gif" height="700" width="394">

**Environment**
Galaxy nexus API 24

**Comment by iadeelzafar** [comment]
@mhutti1 Another closely related bug is that If user chooses this 0 bytes storage. Same bug as shown reappears when user tries to edit it(The 0 byte external storage is not shown in the alert dialog). To resolve this, I think we should not allow the user to select a 0 byte storage.
<img src="https://user-images.githubusercontent.com/36811908/56096629-2f533180-5f04-11e9-8c66-7588172d8f90.gif" height="700" width="394">

**Comment by soloturn** [comment]
this is related to #1171 ?

**Comment by mhutti1** [comment]
I don't think so.

**Comment by kelson42** [comment]
@macgills After you have make a few fixes on this dialog. Do you think by any chance, this bug might have been fixed?

**Comment by macgills** [comment]
No I wouldn't imagine it is. Just out of curiousity, why do we allow people to specify a new external storage? the use case is escaping me

**Comment by kelson42** [comment]
@mhutti1 is the best to answer this but AFAIK this was because @mhutti1 was not convinced that this tool was able to alwasy detect the storage properly. Personnaly, I would like to avoid that feature... which makes the whole stuff too complex.

**Comment by macgills** [comment]
I would be much more in favour of getting rid of this feature and perfecting storage detection, very intense for a user to have to know their storage location

**Comment by kelson42** [comment]
@macgills I support this approach, if this can be done. @mhutti1 Your input here would be much appreciated as you have built all of this and has a longer experience of the problem.

**Comment by macgills** [comment]
By raising the minSDK to 19 (4.4, roughly 1500 users would not be able to upgrade) I am reasonably confident in a solution backed by [Context.externalFilesDirs](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDirs(java.lang.String))

**Comment by mhutti1** [comment]
I don't think this specific issue is worth fixing imo. Its purely cosmetic. WRT the minSdk I would open another issue.

**Comment by kelson42** [comment]
@mhutti1 Without new clearly open new issue, I would like to keep that ticket open? Could you please tell us more about this custom path input?

**Comment by mhutti1** [comment]
I don't think it saves state in general tbh. Its a bit of a hack.

**Comment by kelson42** [comment]
@macgills I think you can carry in by removing the feature. Less convince by increasing the minimal SDKfor now, for that.

**Comment by mhutti1** [comment]
@kelson42 I don't support removing this feature. It was added for a reason and this bug is really not very important, I wouldn't really class it is a bug at all to be honest. The feature is very bare bones for a reason, we don't want users to use it unless necessary. But as a last resort they can enter their own path and select it. Once it is selected it is used and displayed in the menu but won't appear in the selector because it was never meant to. If the user wants to use it after switching to another path they will need to enter it again.

**Comment by macgills** [comment]
…. well I didn't see this comment until just now.
I have a PR removing it there. I don't think this feature has a big value add so I would be in favour of the removal

**Comment by kelson42** [comment]
@mhutti1 @macgills What is sure is that this feature should work fine and here we suffer at least from two weaknesses like reported by @iadeelzafar. I don't know how the problem should be fixed, but either we fix the current bug or we remove the flacky part of the this external storage selector... But this is assuming the path proposed by @BBT-SeanMacGillicuddy works to a really large extend. Hopefully it wil, I'm ready to take that risk for a release.
