### ISSUE TITLE
Switching wikis in Get Content does nothing

### ISSUE THREAD

**Issue by int-ua** [kiwix/kiwix-android#1169]
**Describe the bug**
Selecting different wiki in Get Content does not change selected wiki.

**Steps to reproduce the behavior:**
1. Have at least two wikis downloaded. In my case the list is RationalWiki, 3 Wikipedias (English No Pictures, English Simple No Pictures, Ukrainian No Pictures), 2 Wiktionaries (English No Pictures, Ukrainian No Pictures).
2. Click on right menu > Get Content
3. Select another wiki.
4. The same wiki is still selected.

**Environment**
- Version of Kiwix Android : 2.4 Build 1182160
- Device : Cat S60
- OS version : 6.0.1

**Logs**
Don't see anything about logs in the app on the surface.

**Comment by kelson42** [comment]
@jetownfeve21 May you please help @ int-ua to understand what is going on?

**Comment by int-ua** [comment]
Looks like it's changed only after throbber disappears. But that takes about 30 seconds, maybe more.

**Comment by ciconi** [comment]
Same here ... problem appears only if you try to change the content file before all files are reindexed (I have ~180GB of ZIMs so I wait around 20s everytime I choose "Get content"). Would be nice if the zim-file-refresh is only done if you drag the list down.

**Comment by kelson42** [comment]
Reintroduce comment by Ciconi:

> 
Same here ... problem appears only if you try to change the content file before all files are reindexed (I have ~180GB of ZIMs so I wait around 20s everytime I choose "Get content"). Would be nice if the zim-file-refresh is only done if you drag the list down.

**Comment by kelson42** [comment]
This bug will need to be confirmed with 2.5 to be released soon.

**Comment by int-ua** [comment]
Can I help with it somehow?

**Comment by macgills** [comment]
@int-ua yes you can! If you can use version 2.5 of the app to try and replicate the problem for us that would be appreciated. If you are not a beta tester then please download the apk here https://github.com/kiwix/kiwix-android/releases/tag/2.5.1 you will want v8a or v7a if your phone is a bit older, the x86 ones will work on an emulator.
If it still exists please report back.

**Comment by int-ua** [comment]
2.5.1 Build 220501, cannot reproduce. Thank you!

**Comment by ciconi** [comment]
Checked it also, everything working perfect, thanks!
