### ISSUE TITLE
Evaluate the possibility of setting up separate Testdroid status checks

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#117]
Currently Testdroid checks are handled by Travis but it might be more beneficial to integrate them directly with GitHub. This would likely require some code running on a server somewhere though.

**Comment by kelson42** [comment]
@mhutti1 Basically not a problem. If this is a simple script, we can let it run it somewhere... If this is more, pleaes create a docker instance and I will run it.

**Comment by mhutti1** [comment]
@kelson42 Sounds good. Its fine for now but it might be something to improve in the future to slightly decrease feedback times and allow more specific feedback.

**Comment by harshvardhan-takawale** [comment]
@mhutti1 @kelson42  I am learning automated testing and would love to work on creating junit, espresso test and Travis CI. Can you tell me whether you are still interested in working on and and if yes, what all work needs to be done.

**Comment by mhutti1** [comment]
This is a large issue. We have some ideas ourselves and will start sharing our opinions on possible applications closer to the application date.

**Comment by harshvardhan-takawale** [comment]
@mhutti1  Can I start small? Like one or two espresso tests for particular features? Also is there a personal communication service for the organisation like slack or gitter, it is a bit tough to communicate through these comments.

**Comment by RajaVamsi11** [comment]
Nice idea @harshvardhan-takawale

**Comment by mhutti1** [comment]
@harshvardhan-takawale we already have some espresso tests. If you would like to add more feel free. We use IRC to talk however we are mostly volunteer developers with jobs/studies so don't expect immediate reply's. This specific issue relates to how we currently use testdroid and is quite a challenge although you should be able to work it out by reading our code.

**Comment by kelson42** [comment]
@mhutti1 @macgills Do we still need that ticket? I think all of this is sorted out meanwhile?

**Comment by mhutti1** [comment]
I think it might be nice to flesh this out more but I think test-gateway was the main fix for this.
