### ISSUE TITLE
Migrate Database from Squidb to Room/Realm/Objectbox

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1171]
**Is your feature request related to a problem? Please describe.**
Problem Squidb has not received support for at least a year and it plays very poorly with kotlin.

**Describe the solution you'd like**
A migration to Room which is a part of Android Architecture components or other solutions that more easily expose reactive data will make future work easier and capable of being fully in kotlin

**Comment by mhutti1** [comment]
This sounds sane.

**Comment by kelson42** [comment]
Looks good

**Comment by soloturn** [comment]
wow, there is a lot going on now *wonder* difficult to see any handle to help out @macgills , @kelson42 , @mhutti1 . all seems to be big chunks now, no small increments any more. you'd have a little outline or plan how the next release should go out which supports people to get an idea how they can help?

**Comment by kelson42** [comment]
@soloturn This is true, we plan to make a 2.5 release next week. Goal is to fix the bugs around the downloader by using Android downlaodManager as download solution.

**Comment by macgills** [comment]
Fixed in #1170
