### ISSUE TITLE
Do not filter out files over 4GB when storage is fat32, Grey them out instead

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1173]
**Is your feature request related to a problem? Please describe.**
On 2.5 users cannot see files over 4gb if their selected storage is formatted as fat32

**Describe the solution you'd like**
Have the files still be in the list but greyed out and unclickable

**Describe alternatives you've considered**
A dialog warning users that they will no longer be able to see 4gb files when they switch storage

**Comment by mhutti1** [comment]
@macgills This was implemented right?

**Comment by macgills** [comment]
No, not yet
