### ISSUE TITLE
Automated code coverage

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1175]
* Evaluate current status with @julianharty and @mhutti1 
* Choose a technology stack (measurement, transfers, display, ...)
* Measure code coverage for all automated tests (unit, integration, UI)
* Run it every night
* Publish (consolidate results) publicly
* Document the process (if needed) on the kiwix-android wiki

See also #865 #836

**Comment by macgills** [comment]
Merge of pull request #1176  addresses this issue, closing
