### ISSUE TITLE
Host our accepted licenses for Travis

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#118]
@kelson42 Is it possible that we can host the contents of [http://mhutti1.eu/api/licenses/](http://mhutti1.eu/api/licenses/) somewhere. Gradle can now download sdk dependencies for us if we copy these licences in at the start of each build.

**Comment by mhutti1** [comment]
The might also need to be updated from time to time.

**Comment by kelson42** [comment]
@mhutti1 This is hosted here now http://download.kiwix.org/dev/android/api/licenses/. I think we can close that ticket. For the future, I want to setup a more flexible "artefact hosting system" to let you do that on your own.

**Comment by mhutti1** [comment]
Sounds good.
