### ISSUE TITLE
Misbehaviours in the PHeT app: JavaScript error reported loading list of simulations when app starts

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#1180]
**Describe the bug**
This bug appeared when I was evaluating other strange behaviours where content doesn't display in the app. (I'll add a link to that issue once I've written it up.)

I restarted the PHeT app, it was taking a few seconds to render the main list of simulations. I was running `adb logcat` and noticed 100's of line of the following text:
`chromium: [INFO:CONSOLE(22)] "Uncaught TypeError: Cannot read property 'width' of undefined", source: content://org.kiwix.kiwixcustomphet.zim.base/-/1cbcc8ca0417644ad03a63e1396ea9d0.js (22)`

I've added an extract below from logcat.

I don't know how repeatable or consistent the problem is, or what the effects are. I'll update this issue as I do more testing on this and other devices.

**Environment**
- Version of Kiwix Android : Production 2018-09 Build: 182520
- Device : Galaxy J2 Prime, Model number SM-G532M
- OS version : Android 6.0.1
Note: this phone is one of the models which has a high rate of crashes associated with it in Android Vitals reports. I was testing the app to see if I could reproduce some of those crashes and stumbled on this behaviour in the process.
**Logs**
```
05-28 13:15:13.893  2513  2513 D kiwix   : Loaded URL: content://org.kiwix.kiwixcustomphet.zim.base/A/index.html
05-28 13:15:13.893  2513  2513 D kiwix   : Loaded URL: content://org.kiwix.kiwixcustomphet.zim.base/A/index.html
05-28 13:15:14.053   232  4858 I BufferQueueProducer: [org.kiwix.kiwixcustomphet/org.kiwix.kiwixmobile.KiwixMobileActivity](this:0xb0139c00,id:372,api:1,p:2513,c:232) queueBuffer: fps=35.56 dur=1012.27 max=233.11 min=8.82
05-28 13:15:14.053   232   232 I SurfaceFlinger: [Built-in Screen (type:0)] fps:35.846298,dur:1004.29,max:234.18,min:16.41
05-28 13:15:15.033  2513  2513 D TextView: setTypeface with style : 0
05-28 13:15:15.033  2513  2513 D TextView: setTypeface with style : 0
05-28 13:15:15.033  2513  2513 D TextView: setTypeface with style : 0
05-28 13:15:15.033  2513  2513 D TextView: setTypeface with style : 0
05-28 13:15:15.063   232   232 I SurfaceFlinger: [Built-in Screen (type:0)] fps:25.901419,dur:1003.81,max:401.62,min:16.50
05-28 13:15:15.153   232   253 I BufferQueueProducer: [org.kiwix.kiwixcustomphet/org.kiwix.kiwixmobile.KiwixMobileActivity](this:0xb0139c00,id:372,api:1,p:2513,c:232) queueBuffer: fps=23.72 dur=1095.97 max=417.03 min=9.30
05-28 13:15:15.743 15687 15694 E ReloadingLock: Finalizing LOCKED Token[ipa 2019-05-28 03:51:34.524]
05-28 13:15:16.883  2168  2208 I ReschedulableTimer: [#CMH#] ReschedulableTimer started 
05-28 13:15:17.903  2513  2513 I chromium: [INFO:CONSOLE(14)] "Error: <g> attribute transform: Expected number, "matrix(NaN,NaN,NaN,NaN,…".", source: content://org.kiwix.kiwixcustomphet.zim.base/-/1cbcc8ca0417644ad03a63e1396ea9d0.js (14)
05-28 13:15:17.943  2513  2513 I chromium: [INFO:CONSOLE(22)] "Uncaught TypeError: Cannot read property 'width' of undefined", source: content://org.kiwix.kiwixcustomphet.zim.base/-/1cbcc8ca0417644ad03a63e1396ea9d0.js (22)
05-28 13:15:18.003  2513  2513 I chromium: [INFO:CONSOLE(22)] "Uncaught TypeError: Cannot read property 'width' of undefined", source: content://org.kiwix.kiwixcustomphet.zim.base/-/1cbcc8ca0417644ad03a63e1396ea9d0.js (22)
05-28 13:15:18.023  2513  2513 I chromium: [INFO:CONSOLE(22)] "Uncaught TypeError: Cannot read property 'width' of undefined", source: content://org.kiwix.kiwixcustomphet.zim.base/-/1cbcc8ca0417644ad03a63e1396ea9d0.js (22)

```

**Comment by kelson42** [comment]
This bug needs to be re-evaluated with new Phets custom app to be released with 3.1 code base (in the next 2 weeks).

**Comment by kelson42** [comment]
@julianharty I assume now this is a problem with the javascript. Do you have the problem in a browser as well?

**Comment by kelson42** [comment]
No feedback. I close the ticket assuming this has been fixed. Please reopen if not.
