### ISSUE TITLE
Misbehaviours in the PHeT app: Contents don't always render

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#1181]
**Describe the bug**
The bug occurs in two different modes from what I can tell, either:

1. The loading splash screen remains indefinitely (20+ seconds), or
2. No content is rendered at all, generally this would mean the main area of the screen is black (not the menus, etc, they're still visible).

**Expected behavior**
Content should always render correctly.

**Steps to reproduce the behavior:**
I've yet to find a highly reliable way to trigger these issues, they tend to occur when I change various settings in the settings menu of the app. Toggling `Keep Toolbar Visible` and `Enable bottom toolbar`, then returning to the previous screen (using the arrow at the top left corner of the settings page) is when the problems tend to start.

**Screenshots**

Here's one of the ways the problem appears:
![device-2019-05-28-090221](https://user-images.githubusercontent.com/785891/58479991-65045080-8127-11e9-9c82-ccf9c2449c8e.png)

I'll add others when I encounter them again.

**Environment**
- Version of Kiwix Android : Production 2018-09 Build: 182520
- Device : Galaxy J2 Prime, Model number SM-G532M
- OS version : Android 6.0.1
Note: this phone is one of the models which has a high rate of crashes associated with it in Android Vitals reports. I was testing the app to see if I could reproduce some of those crashes and stumbled on this behaviour in the process.

**Logs**
I've not seen anything obvious in the logs for this issue yet.

**Comment by macgills** [comment]
@kelson42 I think this should be moved to 3.1, custom apps should get more attention then

**Comment by macgills** [comment]
@kelson42 I moved this ticket to 3.1, please move it back to 3.0 if you think it the better place for it

**Comment by kelson42** [comment]
@macgills @julianharty For the moment, the best we can do is IMO preparing a new custom app with latest code and see if the bug is still there.

**Comment by macgills** [comment]
agreed

**Comment by kelson42** [comment]
@julianharty I have published the a new version of the Phet app in closed alpha. https://play.google.com/apps/testing/org.kiwix.kiwixcustomphet to secure you are alpha tester. Please tell me if this problem still occur.

**Comment by kelson42** [comment]
No feedback. I close the ticket assuming this has been fixed. Please reopen if not.
