### ISSUE TITLE
Data not disabled when turning on hotspot

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1186]
**Is your feature request related to a problem? Please describe.**
Since, we need to enable wifi hotspot for other devices to connect to. For example, a teacher is enabling his/her wifi hotspot and wants to share the ZIM Files with a class of students. She wouldn't want a class full of students to use the data.

**Describe the solution you'd like**
* User should be sent to the data usage summary settings screen to disable data.
* But there should be an option for the user to skip the disabling of data. Because in some cases, the user may want to keep his data enabled because he's sharing the hotspot just with one or two devices.

**Note**:
This ticket is related to the hotspot app project. Here's the [branch](https://github.com/kiwix/kiwix-android/tree/iadeelzafar/wifi-hotspot).

**Comment by kelson42** [comment]
@iadeelzafar Why this ticket has been closed?

**Comment by iadeelzafar** [comment]
@kelson42 This has been fixed.
