### ISSUE TITLE
Make three options to deactivate sidebars, tabs and reading

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#12]
There should be a custom configuration option using our buildVariant system that can disable side bars and tabs independently. It should not be exposed to the user.

* index side bar
* tabs side bar (probably deactivate tabs)
* read aloud

This is necessary for the Phet app

**Comment by RajaVamsi11** [comment]
@kelson42  @mhutti1 I am interested in this issue.I can work on this issue.
I have only one idea of moving **read aloud** to settings fragment and give user an option to enable and disable it.
The option can be "make read aloud option  visible in menu settings"
can i continue?
You can give me an idea of doing in sidebars and tabs.

**Comment by mhutti1** [comment]
This is not what we want to do. Please read the task description.

**Comment by kelson42** [comment]
@macgills @mhutti1 I see that @jhbiggs  has started to work on that issue. Considering that the ticket is preety old, would like to confirm with you that this is still what we want to do?

**Comment by macgills** [comment]
I really can't comment on the Phet app but would urge @jhbiggs and other contributors to first look at the `good first issue` tags in the latest milestone ie 3.0

**Comment by kelson42** [comment]
@jhbiggs I think your work is necessary but probably a few things need to be clarified first for this ticket. We will do that specifically during the 3.1 milestone (in a few weeks). Sorry to see you working on things which are not 100% ready, our fault. Please let us know if you plan to work on something first, so we are all sure we don't waste time.

**Comment by jhbiggs** [comment]
No worries, I'm really just enjoying the practice.  I'll have a look at the other good first issues.

**Comment by mhutti1** [comment]
I think this was requested by @ISNIT0 for Phet? I can't fully remember though.

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by kelson42** [comment]
@gaurivn The discussion is still open if we really want to do that. I would recommend to pick an other task.

**Comment by gaurivn** [comment]
Okay, I'll try other good first issues.

**Comment by macgills** [comment]
@ISNIT0 can you remember if you requested this for phet? I'd like to close this if it is no longer needed and I probably will if it goes stale again

**Comment by kelson42** [comment]
@macgills Yes, Phet would be one of the use case.

**Comment by macgills** [comment]
As you have commented previously : 
> Considering that the ticket is preety old, would like to confirm... ...this is still what we want to do?

I was just trying to make some progress on the question of "do we want to do this" as it still seems very up in the air for me

**Comment by kelson42** [comment]
@macgills Except is this would generate a large amount of work or new problems, I would like to have it.

**Comment by macgills** [comment]
It is possible and shouldn't be too difficult. I would allow the user to keep tabs though, that could be a bit of a headache

**Comment by macgills** [comment]
@kelson42 I have added the buildconfig fields and functionality
```
    buildConfigField("Boolean", "DISABLE_SIDEBAR", "false")
    buildConfigField("Boolean", "DISABLE_READ_ALOUD", "false")
    buildConfigField("Boolean", "DISABLE_TABS", "false")
```
but as of right now they are not enabled for any custom app. Are we going to add properties to the custom app json? If this is only for phet I can in my code just say `name == "phet"`

**Comment by kelson42** [comment]
@macgills I would prefer to have options in the json and have them in the phets json as example.
