### ISSUE TITLE
enable build.gradle so kotlin files are supported

### ISSUE THREAD

**Issue by soloturn** [kiwix/kiwix-android#1201]
to allow any contributor to slowly convert kiwix over to kotlin as decided in #648 adjust build.gradle so kotlin files can be built.

maybe define the best strategy to do so. e.g. "start from app/KiwixApplication.java" and then down the dependency tree"

**Comment by kelson42** [comment]
@soloturn Considering that we have introduced Kotlin with 2.5 and are going to release it next week, I hardly believe that gradle can not deal with Kotlin in 2.5. I would just wait to see 2.5 released and merged forward with current 3.0 development to see if that is really necessary to work on that. ping @macgills

**Comment by macgills** [comment]
#1192 kotlin support is now on develop, closing.
Vis a vis migrations I have been espousing the Boyscout rule ie leave the place nicer than you found it.
The idea being that if you change a class even slightly maybe consider converting it to kotlin.
