### ISSUE TITLE
2.5 not recognizing space on external drive?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1205]
Currently testing 2.5 (build 220500) and it gives a strange reading of both my internal and  external SD card (I have a 32Gb card, 16.59 Gb of which is still free; internal has 34.8/64Gb free space). FWIW I'm running a Huawei p20 Lite with Android 8.0)

I'll try with another, fresh microSD to see if the issue remains.

![Screenshot_20190618-173737](https://user-images.githubusercontent.com/21675885/59698532-288cb780-91f0-11e9-9d84-1dc4d53ffee6.jpg)

**Comment by Popolechien** [comment]
Ok this might have to do with the fact that there are other files on the SD card - I tried with another one fresh from the box and it gives a correct(-ish) number (119Gb/126Gb).

**Comment by kelson42** [comment]
I have myself a few mixes, see this screenshot.

![screenshot (1)](https://user-images.githubusercontent.com/1029718/59976657-fbf9e680-95c7-11e9-9eba-5056b0fd0bb7.png)

@macgills One possible explanation:
* Internal is in place of external SD card
* For the too small space, that might be storage with many partitions and only the first one is detected.

**Comment by kelson42** [comment]
@Popolechien Macgills has work a bit on this piece of software for 3.0. It would be really much appreciated if the problem is still there with a nightly.

**Comment by Popolechien** [comment]
Last nightly I see is http://download.kiwix.org/nightly/2019-07-26/, in which case no, issue not solved.

**Comment by macgills** [comment]
I've opened a PR (see above) and I redid it completely and am using a new component and standardised a bunch of code and I am pretty sure it behaves exactly the same as the old code :/

So android continues its grand dance of lying straight to my face. Or it is reporting the truth and what it shows is really the amount of space we can use. 
Either way there is more kotlin code and tests so I am happy
