### ISSUE TITLE
Fails to update/wipe local file list

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1206]
I had several zim files stored on an external drive. When I switched cards the files appear as still listed, but when trying to open I get a standard error message "the selected ZIM file could not be found". 
![IMG_20190618_175745](https://user-images.githubusercontent.com/21675885/59700315-617a5b80-91f3-11e9-872d-75d955ebea0c.jpg)

Then when I try to delete the entry it exits the library and brings me back to the home page (default welcome or whatever zim was last open).

The interesting behaviour is that when I switch cards back to the old one, I can access these zims without problem. I cannot, however, delete them.
![IMG_20190618_180207](https://user-images.githubusercontent.com/21675885/59700377-7a830c80-91f3-11e9-83d8-2e804b1ff8ac.jpg)

Config is Huawei P20 Lite / Android 8.0 / kiwix-android 2.5 build 220500

**Comment by Popolechien** [comment]
Confirm that from in the interface I can delete files in my download folder but not those in the Kiwix folder (FWIW default storage in Kiwix is set to internal storage). Also when I update the local library the old zim remains listed (I can "delete" it though).

**Comment by macgills** [comment]
I think I will solve this by putting a filter on the BooksOnDisk emission of `file.exists()` and create a separate subscription that observes non existing files and deletes them from the db

**Comment by kelson42** [comment]
@macgills Great if you can fix it! This is really a long standing bug reporting many times already.

**Comment by Aditya-Sood** [comment]
@macgills I am facing a related (or probably the same) issue with `develop`, wrt to #1276 
Basically before I merged with develop (when it was still based on master); after file transfer completed, the 'Library' on the receiver device automatically detected the new zims. But this doesn't happen after merging with develop, even after swiping down to refresh the 'Library'

**Comment by macgills** [comment]
@Aditya-Sood that is odd if it doesn't work on a swipe down. The fileSearch operation still runs then. Potentially a separate issue, we will retest once I have addressed this issue

**Comment by macgills** [comment]
#1376 has hopefully fixed this, @Popolechien if you can retest this tomorrow with the nightly that would be very helpful

**Comment by Popolechien** [comment]
@macgills It shall be done.

**Comment by macgills** [comment]
Vielen danke

**Comment by Popolechien** [comment]
Tested the nightly:
Good: it does find (and open) files I download with it
Not so good: it does not seem to find files that had been previously downloaded or are located on the external SD card.

**Comment by macgills** [comment]
@Popolechien that is a symptom of #1385 can you try on an earlier android version?

**Comment by Popolechien** [comment]
Let me ask around, I may be able to get one early next week.

**Comment by macgills** [comment]
just not 9. I will probably have a fix for that issue pushed by later today and ideally merged tomorrow so don't stress yourself

**Comment by macgills** [comment]
@popolechien a beta will be published today and if you can test that then hopefully this should finally be resolved

**Comment by kelson42** [comment]
@Popolechien Could you please confirm, so we can close the ticket?

**Comment by Popolechien** [comment]
Yay, fixed \o/
Well done gents
