### ISSUE TITLE
How are zim files listed in the libraries?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1207]
It does not look to be the same in the online and local library.
Online (left): French and English are mixed, no apparent order I can make out
Local (right): posssibly alphabetical
![Screenshot](https://user-images.githubusercontent.com/21675885/59704019-74912980-91fb-11e9-83e5-081425167923.jpg)

**Comment by mhutti1** [comment]
As far as I can remember online is determined by the server and offline is alphabetical.

**Comment by Popolechien** [comment]
Thanks. We need to do some thinking / testing about that server side then.

**Comment by macgills** [comment]
Online ordering is determined by the server and selected language, I think there has been some changes to ordering on the device tab in 3.0 because now we stick in language headers? I didn't play around with it much
