### ISSUE TITLE
Ensure compliance with new google play icon specifications

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1211]
**Describe the bug**
We need to ensure we comply with this https://developer.android.com/google-play/resources/icon-design-specifications as it is currently erroring our automatic uploads. Further reading: https://github.com/Triple-T/gradle-play-publisher/issues/597

**Expected behavior**
Automatic uploads do not 500

**Steps to reproduce the behavior:**
Preform an automated release or upload icon manually

**Comment by kelson42** [comment]
@macgills How is that ticket related to #46, #852, #681 and #1150. I would appreciate if we could sort all of that simultaneously.

**Comment by macgills** [comment]
@kelson42 Not related to any of those tickets, it is the icon on google play, not our app's icon

**Comment by macgills** [comment]
I toggled a button on the google play console, apparently that was all that was needed.
