### ISSUE TITLE
Create new automated test architecture

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1212]
**Is your feature request related to a problem? Please describe.**
Test are somewhat non deterministic causing coverage variance and depend on external data.

**Describe the solution you'd like**
A full kotlin rewrite lightly inspired by [this article](https://blog.codecentric.de/en/2018/11/android-testing-part2-kotlin-dsl-for-espresso-and-uiautomator/). The important takeaways are:
+ no more idling resources, use UIAutomator methods to wait for conditions
+ PageObjects/[Robots](https://academy.realm.io/posts/kau-jake-wharton-testing-robots/) used to encapsulate view interaction
+ MockWebServer used for all network interaction

**Comment by kelson42** [comment]
This is a priority. I don't want more massive code changes without propoer automated tests (infrastructure).
