### ISSUE TITLE
Kiwix 2.4: New ZIMs downloaded, recognised but don't work; older ZIMs still do

### ISSUE THREAD

**Issue by nocheiner** [kiwix/kiwix-android#1215]
1. Downloaded wikivoyage_de_all_nopic_2019-06.zim (111 MB) and wikivoyage_de_all_novid_2019-06.zim (692 MB) with Kiwix (2.4 build 182160)
2. Both listed in "Get content"
3. When choosing one of them --> white screen while Kiwix menu is still visible and working (no chrash); when entering search tearm --> no results

Older ZIMs are still working: wikipedia_de_all_nopic_2017-08.zimxx (SD);  wikivoyage_de_all_nopic_2018-10.zim (internal) but now, wikivoyage starts with white screen (= no overview/ landinge page) although it is still works when entering a search term

Android: 7.1.1

**Comment by kelson42** [comment]
@nocheiner Thx for your report. I will check this with 2.5 (to be released soon).

**Comment by kelson42** [comment]
@nocheiner I have tested with 2.5 and it works fine for me... Lets see if you can reproduce the problem one time 2.5 will be released.

**Comment by nocheiner** [comment]
Just upgrading to 2.5 didn't make it. But after unistalling Kiwix and installing the new version it works. Thank you!
