### ISSUE TITLE
How works Android Global Crash Reporting?

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1216]
I have learned from #335 that this has been merged but I never have seen working. How does that work? Is that somewhere documented properly?

**Comment by mhutti1** [comment]
I think it is currently disabled as it didn't fully handle some types of crashes but this was some time ago so I am no so sure.

**Comment by macgills** [comment]
I believe it was until very recently disabled on all buildTypes and has just recently been enabled on develop by myself.
![image](https://user-images.githubusercontent.com/3358282/59999036-dc5ece80-9658-11e9-9320-d4d8e8377024.png)
got the commit that disabled it, it seems to me like native crashes are the only thing it can't handle.

**Comment by kelson42** [comment]
Is that worth the effort to have it, even if it handle only native crashes?

**Comment by macgills** [comment]
It is definitely worth it even though we _won't_ get native crashes, we could usurp it with a proper crash reporting system but in the meantime this is fine

**Comment by kelson42** [comment]
OK, then I just need the documentation (probably in `CONTRIBUTING.md`). Following questions should be answered:
* Where (which releases) is that activated?
* What kind of behaviour is crashed?
* Which information are gathered?
* What the value of this system?
* How and to whom are these informations sent?
* What kind of expectations should we have by sending this crash reports?

**Comment by macgills** [comment]
I don't think this is something that needs to be in `CONTRIBUTING`, it is just a feature and an optional one to send an email on a java crash.

**Comment by kelson42** [comment]
@macgills OK, then please put the doc in the wiki. What is important is not where is the documentation, but that we have a clear documentation about that.

**Comment by macgills** [comment]
https://github.com/kiwix/kiwix-android/wiki/Crash-Reporting I think this satisfies the queries? Would you like more detail @kelson42 ?

**Comment by kelson42** [comment]
@macgills It does not answer most of my questions.

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/60010434-b2fd6d00-966f-11e9-8350-0b0e317c287f.png)
If I attach this image and specify the email address will that do? 
I don't know who views this information, I don't have the login details for `android-crash-feedback@kiwix.org` I assume it goes to you. Pointing to the source file really shows everything

**Comment by kelson42** [comment]
@macgills The problem is that me neither. That is why I ask about details.

**Comment by macgills** [comment]
Then I think this is up to you @ISNIT0 ?

**Comment by ISNIT0** [comment]
Hopefully @kelson42 will have/reset the details for that mailbox (https://github.com/kiwix/kiwix-android/issues/335#issuecomment-361912988) I certainly don't anymore 😄 


P.s.
I *think* some of the logging bits caused a crash on some devices. That was implemented by @EladKeyshawn when he was in the UK. I believe it pipes `logcat` to a local file, and then attaches it to the email. Might be worth checking that out

**Comment by kelson42** [comment]
I didn't. Who is going to take care of that mailbox?

**Comment by ISNIT0** [comment]
You didn't what? You said you created the mailbox (https://github.com/kiwix/kiwix-android/issues/335#issuecomment-361912988) can you reset the password?

**Comment by kelson42** [comment]
I did not have reset the details... that are still the same as I have created it. But my question is: who will take care of that mailbox?

**Comment by macgills** [comment]
Give me the details, I have no trouble with that being a part of my responsibility, I will test the fileProvider now. @ISNIT0 was it an issue on a particular android version or just universal?

**Comment by ISNIT0** [comment]
@macgills Not sure, sorry. I really don't remember

**Comment by macgills** [comment]
@ISNIT0 no prob

**Comment by macgills** [comment]
So if the details of this account can be communicated to me then I will close this ticket now that this is working?
Do we need to clarify that I - or another developer - will triage any received error reports into bug issues if there are no existing duplicates on github

**Comment by ISNIT0** [comment]
Might be possible to setup some kind of automation (zapier etc.) to automatically create an issue

**Comment by kelson42** [comment]
@macgills @ISNIT0 I have communicated the details (password) of the mailbox to both of you perl email

**Comment by macgills** [comment]
Are we happy to close so?

**Comment by kelson42** [comment]
@macgills I have gathered all the rest information I wanted, upgraded the wiki page and I close that ticket.
