### ISSUE TITLE
Fixes for build-custom-app

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1218]
* Explain how to install ruby
* Explain how to install travis (the travis doc is big)
* Talk about "hash -r"
* Put a word about "kiwix-android-custom" that people know where to modify things
* zim_url and zim_content should be merged (in zim?)
* remove version_code fron info.json
* add httpslib2 in the deps
* add google-api-python-client in the deps
* add space before "if you found it"

**Comment by kelson42** [comment]
Putting in 3.0. I think all of this will become depracated one time the publication will be automated... but this has to be checked then

**Comment by kelson42** [comment]
@macgills Tell me when you start to define in detail the new worflow, those points are still valid imo.

**Comment by kelson42** [comment]
@macgills Here is a reminder about this ticket as you are polishing new custom app publishing process.

**Comment by macgills** [comment]
I would say none of these points are still valid?

**Comment by kelson42** [comment]
@macgills The stuff with the `version_code` and `version_name` seems to be handled already with #36. But what about merging `zim_url` and `zim_file` (they can be contradictory) and are confusing!?

**Comment by macgills** [comment]
We only need zimUrl, zimFile doesn't exist. If we need a zimFile (eg when uploading an expansion file) we download it during the build process.
We do not support embedded zims at this time. Pending the necessary update to kiwixlib we can enhance the solution
