### ISSUE TITLE
Remove Forcing Language in In-App Settings

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1222]
**Is your feature request related to a problem? Please describe.**
#207 There are some existing problems with this feature and android already has a system for changing your language that we should just respect

**Describe the solution you'd like**
Complete removal of this feature

**Describe alternatives you've considered**
For languages that don't exist in android we rebrand this feature as "unprovided languages" and attach a warning of stability to it, only allow the user to select these uncommon languages and not all of the common languages.

**Additional context**
It was also mentioned that a non device owner could not change device language, I would like this verified

**Comment by Popolechien** [comment]
> we rebrand this feature as "unprovided languages" and attach a warning of stability to it
Well if the warning is in a language that's not understood (e.g. English), might as well no warn them at all (and hope for the best).

>It was also mentioned that a non device owner could not change device language, I would like this verified
@macgills Can you please clarify?

**Comment by kelson42** [comment]
On my side I can see two argument to keep this feature:
* Android does not support the language the user wants. I don't have check recently, but a few years ago languages like Burmed (this is an example) was not supported. I think it was the same for some important language flavours (PT-BR). So if we remove it, we are not able to make a custom app in one of this not-supported language.
* Someone wants to use the app in a specific UI language without changing the device language (because this is not his own device, or because he can't, ...)

@Popolechien @julianharty @m4tx @mhutti1 Your feedback would be really welcome on this.

**Comment by macgills** [comment]
I would think that user would have to have the device already support their language for them to have it?
Is the use case they have a device they use that they barely understand most of the time?

I am not sure what the impediment is to changing the device language, is it a multi user account scenario? Are they changing the language because they think it would be fun to read only kiwix in another language?

**Comment by Popolechien** [comment]
I've seen quite a few users with devices sent from family abroad (e.g. Cubans with some family in the States or Canada get shiped an English device and have no idea how to switch to Spanish).

**Comment by macgills** [comment]
Analytics would be quite handy here to see if they can find and do use this feature.

**Comment by macgills** [comment]
@kelson42 I propose moving this ticket out of the 3.0 milestone.
Seeing as how it is offering some usability on old versions of android with poor language support it adds value. With the slow progress of raising the minSDK hopefully we won't need it in the future but for now it can stick around

**Comment by mhutti1** [comment]
I think there is value in being able to change your language as a user but I really don't know how much this is used.

**Comment by macgills** [comment]
I will close this because the language forcing should be maintained for the foreseeable future.
