### ISSUE TITLE
Bitbar should run tests on multiple devices

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1223]
**Is your feature request related to a problem? Please describe.**
Continuation of #110 . After adding the devices listed in this ticket the build became nigh unpassable

**Describe the solution you'd like**
Get rid of bitbar, use Firebase Test Lab.

**Describe alternatives you've considered**
Find through trial and error find a combination on bitbar that works

**Comment by kelson42** [comment]
@macgills I think, if we leave BitBar, we should really know exactly why.

**Comment by macgills** [comment]
That was more a thing to get the discussion rolling, bitbar is frustrating to use in my experience thus far.
I haven't used test lab but it is the recommended way of automated testing at CircleCi but it does have limitations.
We should explore bitbar more first.

**Comment by kelson42** [comment]
I think this ticket should be solved before 3.0 release.

**Comment by kelson42** [comment]
OK, all of this is quite to complex and time consuming for 3.0.

**Comment by kelson42** [comment]
BitBar can be really useful, for both CI testing on multiple devices or manual testing. But our experience so far as shown that it is pretty cumbersome to use BitBar (and maybe any other device farm) + we have already serious defficulties to get a stable CI with emulator on Github + emulator based CI delivers already most of the testing features we expect from a CI. Therefore, for the moment, we will continue with BitBar, and maybe in the future we will reconsider from scratch to use a device farm as part of the CI
