### ISSUE TITLE
Delay request to rate app

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1235]
There is some understandable level of complaint that the app would ask users to rate it even before they've had the chance to actually use it: 
https://play.google.com/apps/publish?account=9116215767541857492#ReviewDetailsPlace:p=org.kiwix.kiwixmobile&reviewid=gp:AOqpTOFynxa5ioZX8ieSt_oFHfIIOOwJ22EdjjM_1uKv88iRuUcA3EVM2BFGzN_2PwoGeQ7DQtyr1oFst5y6_Xg
Can we delay the prompt after the nth time the app is opened (with n=10 at least)?

**Comment by macgills** [comment]
https://github.com/Vorlonsoft/AndroidRate after searching not very much I found this library, there are loads of libraries but this one seem very versatile for our requirements

**Comment by jhbiggs** [comment]
I noticed in MainActivity.java that there's already a counter, currently set to 5.  I set it to 10.  I reserve the right to be obtuse here and have missed some obvious obstacle to this solution...

**Comment by mhutti1** [comment]
@rashiq Had some views on this if I can remember.

**Comment by kelson42** [comment]
@mhutti1 Yes. I have put him as reviewer of the PR. No feedback so far.
