### ISSUE TITLE
Change default branch from "master" to "develop"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1240]
The current default branch is `master` which IMO should not be anymore. It should be `develop` as we want people to work on this branch instead of `master`.

Feedback welcome (in particular if you disagree).

**Comment by mhutti1** [comment]
Yeah I think we should do this.

**Comment by macgills** [comment]
I don't foresee an issue and think it is probably the right route to go

**Comment by kelson42** [comment]
@mhutti1 @macgills Thx for your feedbacks. Just did it.
