### ISSUE TITLE
Does android dark theme inverts picture colors?

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1242]
I don't have an android version which allows that but a user complains that the dark theme invert the ZIM articles picture colors. We need to confirm that.

**Comment by siddharth2010** [comment]
@kelson42 , From what I see, the image colors are not inverted as such. However, when we are in the tab mode, the colors for the whole page are inverted. This is probably leading to the inversion in image colors.

Here is an example:

| Normal Mode        | Tab View           | 
| ------------- |:-------------:| 
| ![Screenshot_1561895624](https://user-images.githubusercontent.com/32238400/60396301-29f9a080-9b5d-11e9-80fc-eef290c65355.png)    | ![Screenshot_1561895627](https://user-images.githubusercontent.com/32238400/60396306-2f56eb00-9b5d-11e9-9f6f-9afc32d990e6.png) |

**Comment by kelson42** [comment]
@siddharth2010 Thx for having a look. This tab mode is available on `2.5`? This does not looks like mine!

**Comment by siddharth2010** [comment]
@kelson42, the tab mode is not available on the release branch (2.5). 
Here the images are looking fine on the emulator as well as on my device.

**Comment by kelson42** [comment]
@siddharth2010 Thx again for testing all of this. You confirm that you have properly tested with the **Android** dark mode in collaboration with the **Kiwix** night mode and that you confirm that in none of the combination the picture colors are inverted with Kiwix 2.5? Would be nice also if you could indicate your version of Android.

**Comment by siddharth2010** [comment]
@kelson42 , yes. I have tested the app on Android versions 8.1, and 9 emulators, And From my observations, none of the combinations of android dark mode and Kiwix Night mode has the picture colors inverted.

However, There is one specific case, when the image colors would be inverted. if the user selects the invert colors option in Android and then uses the Kiwix app.
here is that case:


| Normal Mode        | invert colors|  After invert colors option is selected | 
| ------------- |:-------------|:-------------| 
| ![Screenshot_1561907609](https://user-images.githubusercontent.com/32238400/60398609-ebbdaa80-9b77-11e9-931f-e1d4d092ed4c.png)| ![Screenshot_1561905827](https://user-images.githubusercontent.com/32238400/60398681-b6fe2300-9b78-11e9-8d46-0a729a8bb573.png) | ![Screenshot_1561907598](https://user-images.githubusercontent.com/32238400/60398612-efe9c800-9b77-11e9-8a01-63f3810b012f.png)  |

I tested it on the night mode on android P developer options as well, and the app looks fine there too:
![Screenshot_1561907964](https://user-images.githubusercontent.com/32238400/60398676-9635cd80-9b78-11e9-95b5-fb63d2c44c21.png)

Also, it works fine on my physical device (Samsung S6, Android 7.0)

**Comment by kelson42** [comment]
@siddharth2010 OK, then this is clear what happen now... That said, I'm not sure this is a bug? Looks like Android "invert colors" mode... just inverts color... So looks like a feature to me.

**Comment by siddharth2010** [comment]
exactly. That's what I think too.

**Comment by kelson42** [comment]
OK, closing the ticket. If people want a real "night mode" they can use the one of Kiwix.
