### ISSUE TITLE
Translate Play Store Kiwix descriptions

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1250]
Considering that half of our users have Spanish native speakers, this is probably worth the small effort.

**Comment by kelson42** [comment]
@Popolechien Would you be able to help here?

**Comment by Popolechien** [comment]
Yep, no problemo.

**Comment by geekRishabhjain** [comment]
Are we only including Spanish? I know French. If someday  French description is also needed, I'll do it.

**Comment by Popolechien** [comment]
@geekRishabhjain We have French, German, Turkish, Arabic and Spanish covered. Currently looking for Hindi, Urdu, Farsi, Pashto, Russian, Portuguese and Bahasa Indonesia.

**Comment by geekRishabhjain** [comment]
I can help with Hindi too.

**Comment by Popolechien** [comment]
@geekRishabhjain Thanks. Here is the text:
No internet, no problem!

Kiwix allows you to store a complete copy of hundreds of website on your phone or tablet: once it is installed, select which content you would like to download so you can still use it when your internet connexion is down. Kiwix is entirely free and has no ads.

Contents available include Wikipedia (including smaller thematic selections, e.g. Football or Maths), the Wiktionary, TED talks, etc. in 100+ languages. There are also versions without images so as to save on storage space.

Note: Kiwix is also available on regular computers (Windows, Mac, Linux) - see www.kiwix.org for more info.

**Comment by geekRishabhjain** [comment]
@Popolechien Here it is:

कोई इंटरनेट नहीं? कोई बात नहीं!

Kiwix  का इस्तेमाल करके आप अपने फोन या टैबलेट पर सैकड़ों वेबसाइट की एक पूरी कॉपी डाउनलोड कर सकते हैं : इनस्टॉल होने पर, वह कंटेंट्स चुनें जिसे आप डाउनलोड करना चाहते हैं ताकि आप इसका उपयोग तब कर सकें जब आपका इंटरनेट न हो। कीवीक्स पूरी तरह से मुफ्त है और इसमें कोई विज्ञापन नहीं है।

आप में 100+ भाषाओं में विकिपीडिया (छोटे विषय, जैसे फुटबॉल या गणित), विक्षनरी, टेड टॉक आदि को अपने मोबाइल में डाउनलोड कर सकते हैं। 
चित्रों के बिना भी इसका इस्तेमाल कर सकते हैं ताकि आपकी मोबाइल storage का किफ़ायती इस्तेमाल हो।

नोट: Kiwix बाकी कंप्यूटर (Windows , Mac,  Linux ) पर भी उपलब्ध है - अधिक जानकारी के लिए www.kiwix.org देखें।

**Comment by Popolechien** [comment]
It's now online. I don't know how to check from the user end, but thanks @geekRishabhjain

**Comment by Popolechien** [comment]
@kelson it is there already.

**Comment by kelson42** [comment]
@Popolechien Great, so I close this ticket. Thx.

**Comment by macgills** [comment]
>Urdu, Farsi, Pashto, Russian, Portuguese and Bahasa Indonesia.

@kelson42 are we making separate tickets for these remaining languages

**Comment by kelson42** [comment]
@macgills @Popolechien Yes, we need to do so, otherwise this is qutie complex to close this kind of ticket. This ticket was first about Spanish and have forgotten to take in account later comment.
