### ISSUE TITLE
FindBugs Error

### ISSUE THREAD

**Issue by nomisto** [kiwix/kiwix-android#126]
Hey,
I've imported kiwix from the git repository in Android Studio. When I want to analyze it with FindBugs i get an error

> Error:(97, 0) Gradle: A problem occurred evaluating project ':app'.
> C:\Users\Simon\.AndroidStudio2.3\system\compile-server\app\src

Does anybody know how to make this work?
If I want to emulate it with a Virtual Android device i get a warning if this helps:

> Warning:string 'custom_app_missing_content' has no default translation.

Kind regards
Simon

**Comment by kelson42** [comment]
@mhutti1 Any idea?

**Comment by mhutti1** [comment]
Yeah this is due to our translations being out of date. It doesn't cause crashes though as the string isn't used. If you care struggling to compile can you post the full gradle log.

**Comment by nomisto** [comment]
Sorry for my late reply.
Build is successful, but maybe it has something to do with the TESTDROID username not set?
Or maybe the error comes from the plugin FindBugs itself.

`Executing tasks: [:app:generateKiwixDebugSources, :app:generateKiwixDebugAndroidTestSources, :app:prepareKiwixDebugUnitTestDependencies, :app:mockableAndroidJar, :kiwixlib:generateDebugSources, :kiwixlib:generateDebugAndroidTestSources, :kiwixlib:mockableAndroidJar, :kiwixlib:prepareDebugUnitTestDependencies]

Configuration on demand is an incubating feature.
Building Kiwix
Building Custom
Incremental java compilation is an incubating feature.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
TESTDROID: username has not been set
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
TESTDROID: username has not been set
:app:preBuild UP-TO-DATE
:app:preKiwixDebugBuild UP-TO-DATE
:app:checkKiwixDebugManifest
:app:preKiwixReleaseBuild UP-TO-DATE
:app:preRaycharlesDebugBuild UP-TO-DATE
:app:preRaycharlesReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2410Library
:app:prepareComAndroidSupportAppcompatV72410Library
:app:prepareComAndroidSupportCardviewV72410Library
:app:prepareComAndroidSupportDesign2410Library
:app:prepareComAndroidSupportRecyclerviewV72410Library
:app:prepareComAndroidSupportSupportV132410Library
:app:prepareComAndroidSupportSupportV42410Library
:app:prepareComAndroidSupportSupportVectorDrawable2410Library
:app:preKiwixDebugAndroidTestBuild UP-TO-DATE
:app:preRaycharlesDebugAndroidTestBuild UP-TO-DATE
:app:prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library
:app:prepareComAndroidSupportTestRunner05Library
:app:prepareComJakewhartonButterknife801Library
:app:prepareComYahooSquidbSquidb200Library
:app:prepareEuMhutti1UtilsStorageAndroidStorageDevices050Library
:app:prepareIoReactivexRxandroid110Library
:kiwixlib:preBuild UP-TO-DATE
:kiwixlib:preReleaseBuild UP-TO-DATE
:kiwixlib:checkReleaseManifest
:kiwixlib:prepareReleaseDependencies
:kiwixlib:compileReleaseAidl
:kiwixlib:compileLint
:kiwixlib:copyReleaseLint UP-TO-DATE
:kiwixlib:mergeReleaseShaders
:kiwixlib:compileReleaseShaders
:kiwixlib:generateReleaseAssets
:kiwixlib:mergeReleaseAssets
:kiwixlib:mergeReleaseProguardFiles
:kiwixlib:packageReleaseRenderscript UP-TO-DATE
:kiwixlib:compileReleaseRenderscript
:kiwixlib:generateReleaseResValues
:kiwixlib:generateReleaseResources
:kiwixlib:packageReleaseResources
:kiwixlib:processReleaseManifest
:kiwixlib:bundleRelease UP-TO-DATE
:app:prepareKiwixDebugDependencies
:app:compileKiwixDebugAidl
:app:compileKiwixDebugRenderscript
:app:generateKiwixDebugBuildConfig
:app:generateKiwixDebugResValues
:app:generateKiwixDebugResources
:app:mergeKiwixDebugResources
:app:processKiwixDebugManifest
:app:processKiwixDebugResources
warning: string 'custom_app_missing_content' has no default translation.


:app:generateKiwixDebugSources
:app:prepareComAndroidSupportTestEspressoEspressoContrib222Library
:app:prepareComAndroidSupportTestEspressoEspressoCore222Library
:app:prepareComAndroidSupportTestEspressoEspressoIdlingResource222Library
:app:prepareComAndroidSupportTestEspressoEspressoWeb222Library
:app:prepareComAndroidSupportTestRules05Library
:app:prepareComAndroidSupportTestUiautomatorUiautomatorV18212Library
:app:prepareKiwixDebugAndroidTestDependencies
:app:compileKiwixDebugAndroidTestAidl UP-TO-DATE
:app:processKiwixDebugAndroidTestManifest UP-TO-DATE
:app:compileKiwixDebugAndroidTestRenderscript UP-TO-DATE
:app:generateKiwixDebugAndroidTestBuildConfig UP-TO-DATE
:app:generateKiwixDebugAndroidTestResValues UP-TO-DATE
:app:generateKiwixDebugAndroidTestResources UP-TO-DATE
:app:mergeKiwixDebugAndroidTestResources UP-TO-DATE
:app:processKiwixDebugAndroidTestResources UP-TO-DATE
:app:generateKiwixDebugAndroidTestSources UP-TO-DATE
:app:preKiwixDebugUnitTestBuild UP-TO-DATE
:app:prepareKiwixDebugUnitTestDependencies
:app:mockableAndroidJar UP-TO-DATE
:kiwixlib:preDebugBuild UP-TO-DATE
:kiwixlib:checkDebugManifest
:kiwixlib:prepareDebugDependencies
:kiwixlib:compileDebugAidl UP-TO-DATE
:kiwixlib:compileDebugRenderscript UP-TO-DATE
:kiwixlib:generateDebugBuildConfig UP-TO-DATE
:kiwixlib:generateDebugResValues UP-TO-DATE
:kiwixlib:generateDebugResources UP-TO-DATE
:kiwixlib:packageDebugResources UP-TO-DATE
:kiwixlib:processDebugManifest UP-TO-DATE
:kiwixlib:processDebugResources UP-TO-DATE
:kiwixlib:generateDebugSources UP-TO-DATE
:kiwixlib:preDebugAndroidTestBuild UP-TO-DATE
:kiwixlib:prepareComAndroidSupportTestEspressoEspressoCore222Library
:kiwixlib:prepareComAndroidSupportTestEspressoEspressoIdlingResource222Library
:kiwixlib:prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library
:kiwixlib:prepareComAndroidSupportTestRules05Library
:kiwixlib:prepareComAndroidSupportTestRunner05Library
:kiwixlib:prepareDebugAndroidTestDependencies
:kiwixlib:compileDebugAndroidTestAidl UP-TO-DATE
:kiwixlib:copyDebugLint UP-TO-DATE
:kiwixlib:mergeDebugShaders UP-TO-DATE
:kiwixlib:compileDebugShaders UP-TO-DATE
:kiwixlib:generateDebugAssets UP-TO-DATE
:kiwixlib:mergeDebugAssets UP-TO-DATE
:kiwixlib:mergeDebugProguardFiles UP-TO-DATE
:kiwixlib:packageDebugRenderscript UP-TO-DATE
:kiwixlib:bundleDebug UP-TO-DATE
:kiwixlib:processDebugAndroidTestManifest UP-TO-DATE
:kiwixlib:compileDebugAndroidTestRenderscript UP-TO-DATE
:kiwixlib:generateDebugAndroidTestBuildConfig UP-TO-DATE
:kiwixlib:generateDebugAndroidTestResValues UP-TO-DATE
:kiwixlib:generateDebugAndroidTestResources UP-TO-DATE
:kiwixlib:mergeDebugAndroidTestResources UP-TO-DATE
:kiwixlib:processDebugAndroidTestResources UP-TO-DATE
:kiwixlib:generateDebugAndroidTestSources UP-TO-DATE
:kiwixlib:mockableAndroidJar UP-TO-DATE
:kiwixlib:preDebugUnitTestBuild UP-TO-DATE
:kiwixlib:prepareDebugUnitTestDependencies

BUILD SUCCESSFUL

Total time: 42.785 secs`

**Comment by nomisto** [comment]
And the error appears when

> Information:Gradle: Executing tasks: [:app:assembleKiwixDebug, :kiwixlib:assembleDebug]

if this helps you.

**Comment by mhutti1** [comment]
It seems like a weird bug. It might be that you are not building all of kiwix-android and only kiwixlib. Gradle should definitely not be claiming a successful build.  So it doesn't install on your device yet still claims success or am I missing something?

**Comment by nomisto** [comment]
I had to import your application in Android Studio for University and analyze it. (Dependency analysis, Metrics, etc...). Furthermore we had to use a plugin called FindBugs, and everytime I wanted to analyze with it, it gives me the error mentioned above.
But i finally managed to get it to work. I had to adjust the gradle file a little:

line 98

`if(custom.listFiles()){
  custom.eachFile() { file ->

    def fileName = file.getName()
    if (fileName.contains("test") || fileName == "main" || fileName.contains("Test")) {
      return
    }
    map.put(fileName, file.getAbsolutePath())

  }
}`

Thanks for your help!

**Comment by kelson42** [comment]
@mhutti1 Anything to merge here to our code base?

**Comment by mhutti1** [comment]
Cool thanks, No problem, we are looking at using findbugs later ourselves. Thx for the information 👍

**Comment by mhutti1** [comment]
@kelson42 @nomisto Yeah if you want to submit a pull request it would be appreciated. Otherwise I can add it myself.

**Comment by nomisto** [comment]
@mhutti1 No problem. Nice feeling i can contribute something to you :) Add it yourself please, im pretty new to GitHub and don't want to mess something up.

**Comment by kelson42** [comment]
@nomisto Be bolt, no way to mess something in our git repository. Do like following:
1 - Create a fork of the git repository
2 - Checkout your fork on your computer
3 - Make your fix
4 - Commit and push to github
5 - Make the pull request (https://help.github.com/articles/creating-a-pull-request/)

**Comment by nomisto** [comment]
@kelson42 Ok, I'll try it.

**Comment by nomisto** [comment]
Finished, hope it worked 😄

**Comment by mhutti1** [comment]
@nomisto It looks good. Our automated build system is building now. @kelson42 Just realised something, travis  won't give testdroid an api key on commits triggered from a non contributor because it might lead to the key being exposed. This will likely cause this build to fail (although the gradle build will still succeed). What do you want to do about this long term?

**Comment by kelson42** [comment]
@mgautierfr any idea about @mhutti1 complain.

Maybe we should deactivate the testdroid (in case of external fork-based pull requests). if not solution can be found to that problem.

**Comment by kelson42** [comment]
i close that ticket. Thx again @nomisto for the valuable patch. Feel free to make new bug reports or pull requests.
