### ISSUE TITLE
Localization not supported

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1263]
I have an android phone whose default language is French. I set Kiwix to Arabic.
Resulting display is a mix of English (menu, description), French (description) and Arabic (file name, size)
![translation issue](https://user-images.githubusercontent.com/21675885/60645769-e8594600-9e39-11e9-947a-058d0d6c4adf.jpg)

**Comment by kelson42** [comment]
I should first resync the traduction, I don't have done that for ages

**Comment by kelson42** [comment]
I have just made a resync https://github.com/kiwix/kiwix-android/pull/1264... will should then have a look if we have other problems

**Comment by macgills** [comment]
We will need to do another translation push as a lot of strings have been added for LocalFileTransfer and Hotspot. I don't think there are anymore strings to be added so now is a good time to do it @kelson42

A lot of these problems are going to be pretty persistent though because the text getting rendered is just data we get from the server and unless that responds with the correct text for the language we are out of luck in that regard

**Comment by Popolechien** [comment]
@macgills Where do you get these strings from (and that I could direct translators to?) Translatewiki?

**Comment by macgills** [comment]
The project has a `strings.xml` file that contains the default English strings that we should base translations on. The process of translation is not very clear to me so @kelson42 will have to fill you in but I imagine it is Translatewiki?

**Comment by kelson42** [comment]
@macgills Can we do more here?
@Popolechien Translations are now synced often and directly between Translatewiki and our Kiwix Android repo. This should help to get better translations.

**Comment by macgills** [comment]
It would be better I think to open up issues for individual untranslated parts if something has fallen through the cracks. If for example MB is untranslated in Arabic, I would have no idea what the expectation is for that string in Arabic and it would take research to fix

**Comment by kelson42** [comment]
> It would be better I think to open up issues for individual untranslated parts if something has fallen through the cracks

@macgills Agree with you, but even them, there is nothing we can really do because:
* This is not something the dev team can handle
* There is nobody in charge to have proper translations donc by the TW translator.

We should have someone in charge to looks at TW and motivate people.
