### ISSUE TITLE
Lint Issue: Unconditional Logging

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1270]
**Is your feature request related to a problem? Please describe.**
```
Unconditional Logging Calls
 
The BuildConfig class (available in Tools 17) provides a constant, "DEBUG", which indicates whether the code is being built in release mode or in debug mode. In release mode, you typically want to strip out all the logging calls. Since the compiler will automatically remove all code which is inside a "if (false)" check, surrounding your logging calls with a check for BuildConfig.DEBUG is a good idea.  If you really intend for the logging to be present in release mode, you can suppress this warning with a @SuppressLint annotation for the intentional logging calls. 

Issue id: LogConditional
```

**Describe the solution you'd like**
We should write our own logger class(or top level kotlin functions) and disallow production logging

**Describe alternatives you've considered**
Continue ignoring this lint warning if we want to have production logs

See also #98 #252

**Comment by abdulwd** [comment]
Instead of writing our own logger class, can we use [Timber](https://github.com/JakeWharton/timber)?

**Comment by macgills** [comment]
I like wrapping it in our own functions, even if we use timber under the hood, it allows us to do things like truncating tags ourselves, swapping to a new logging library easily, writing individual logs to a file.

in total it is like 5 functions

```
logd(tag, msg){
   log(Priority.Debug, tag, msg)
}
.
.
.
log(priority, tag, msg){
 actualLogCall(verbosity, sanitisteTag(tag), sanitise(msg))
}
````

I think losing the formatArgs functionality is not so important

**Comment by abdulwd** [comment]
That's cool. We should set the class name as the default for the tag, it saves time.

**Comment by kelson42** [comment]
@macgills @abdulwd Yes, please don't write your own Logger. Each language propose one or two well established Logging framework. Please make a choice and rely on it. That said, of course, no problem to have your own Log class on the top of it to expose and handle only what you need, in the way you prefer.

**Comment by macgills** [comment]
I have done a good few experiments with this and overall it still makes sense to have a `TAG` field in your class and pass it in to the function.
`getClass.getSimpleName()` works as long as you are not obfuscating your class names 
and my too ambitious
```
log(TAG, "a log")

log(priority= Debug, tag, msg){
//log something
}

inline fun <reified T> Any.TAG = T::class.java.simpleName
```
would unfortunately capture whatever instance it was in and played terribly with lambdas

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you please update this issue? Does it still make sense?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Yes, this ticket still makes sense. We should not add logging in release mode as it is unnecessary in release mode. We need logs to debug the errors in the debug variant so we should keep the logs in our debug variant. Here are a few disadvantages of keeping logs in the release variant https://www.netguru.com/blog/3-reasons-why-you-should-always-remove-logs-from-production-mobile-app.

In release mode, users can share the crash logs through `ErrorActivity`, which includes the logcat output, not these logs outputs. Therefore, these are unnecessary in release mode, and we should remove these logs from our release mode.
