### ISSUE TITLE
Lint Issues Ignored

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1271]
**Is your feature request related to a problem? Please describe.**
For each ignored lint issue we should have a corresponding ticket in this description

+ Issue id: LogConditional #1270 
+ Issue id: MissingTranslation #1272 
+ Issue id: CheckResult #1273 
+ Issue id: DuplicateStrings #1275  
+ Issue id: SyntheticAccessor #1319  

**Describe the solution you'd like**
Clear consensus on each lint issue that we ignore

**Comment by kelson42** [comment]
@macgills Corresponding tickets have been created and two of them already implemented. I don’t believe this ticket is valuable in itself. Should we close it?

**Comment by macgills** [comment]
I think more issues have become ignored in the interim but we can probably close it
