### ISSUE TITLE
Lint Issue: MissingTranslation

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1272]
**Is your feature request related to a problem? Please describe.**
```
Incomplete translation
If an application has more than one locale, then all the strings declared in one language should also be translated in all other languages. 
If the string should not be translated, you can add the attribute translatable="false" on the <string> element, or you can define all your non-translatable strings in a resource file called donottranslate.xml. 
Or, you can ignore the issue with a tools:ignore="MissingTranslation" attribute.  
You can tell lint (and other tools) which language is the default language in your res/values/ folder by specifying tools:locale="languageCode" for the root <resources> element in your resource file. (The tools prefix refers to the namespace declaration http://schemas.android.com/tools.) 
 Issue id: MissingTranslation
```

**Describe the solution you'd like**
While this is a very useful warning to have I don't think logistically we will have full mapping anytime soon and as such it should not fail the build.
We can downgrade this to a warning and not an error I think

**Comment by kelson42** [comment]
@translatewiki @amir80 @Nikerabbit Currently, missing translations are filled with the English version. On Android, the app can do that on the fly at the runtime. As a consequence, this approach:
* Use more storage for nothing
* Fake our linter about Missing translations.

Does Translatewiki has a way to avoid doing this? An option by the export?

**Comment by macgills** [comment]
Strangely though there are still missing translations despite the English insertions.
app: 3
```
../../src/main/res/values/strings.xml:4: "file_system_does_not_support_4gb" is not translated in "kab" (Kabyle) or "nl" (Dutch)
../../src/main/res/values/strings.xml:5: "detecting_file_system" is not translated in "kab" (Kabyle) or "nl" (Dutch)
../../src/main/res/values/strings.xml:6: "cannot_open_file" is not translated in "sv" (Swedish), "lt" (Lithuanian), "es" (Spanish), "pl" (Polish)
```
core: 281
```
../../src/main/res/values/strings.xml:4: "menu_zim_manager" is not translated in "ps" (Pashto), "lt" (Lithuanian), "hr" (Croatian), "yo" (Yoruba), "ia" (Interlingua (International Auxiliary Language Association)), "mg" (Malagasy), "ie" (Interlingue; Occidental), "ur" (Urdu), "ml" (Malayalam), "mn" (Mongolian), "qu" (Quechua), "af" (Afrikaans), "uz" (Uzbek), "ms" (Malay), "mt" (Maltese), "it" (Italian), "am" (Amharic), "my" (Burmese), "et" (Estonian), "as" (Assamese), "nb" (Norwegian Bokmål), "ja" (Japanese), "az" (Azerbaijani), "rm" (Romansh), "nl" (Dutch), "ba" (Bashkir), "ji" (Yiddish), "nn" (Norwegian Nynorsk), "be" (Belarusian), "fo" (Faroese), "bm" (Bambara), "jv" (Javanese), "sa" (Sanskrit), "sh", "ka" (Georgian), "si" (Sinhala), "sk" (Slovak), "so" (Somali), "sr" (Serbian), "km" (Khmer), "su" (Sundanese), "kn" (Kannada), "or" (Oriya), "sw" (Swahili), "ta" (Tamil), "gu" (Gujarati), "ky" (Kyrgyz), "te" (Telugu), "cv" (Chuvash), "th" (Thai), "cy" (Welsh), "tl" (Tagalog)
[rest omitted]
```
custom: 4
```
../../src/main/res/values/strings.xml:4: "retry" is not translated in "ml" (Malayalam), "qq", "cs" (Czech), "tg" (Tajik)
../../src/main/res/values/strings.xml:5: "download" is not translated in "zgh" (Standard Moroccan Tamazight), "et" (Estonian), "cs" (Czech), "da" (Danish)
../../src/main/res/values/strings.xml:6: "invalid_installation" is not translated in "fi" (Finnish), "zgh" (Standard Moroccan Tamazight), "skr", "ml" (Malayalam), "qq", "sv" (Swedish), "it" (Italian), "es" (Spanish), "et" (Estonian), "cs" (Czech), "tg" (Tajik), "lb" (Luxembourgish), "da" (Danish)
../../src/main/res/values/strings.xml:7: "complete" is not translated in "fi" (Finnish), "zgh" (Standard Moroccan Tamazight), "skr", "qq", "it" (Italian), "es" (Spanish), "et" (Estonian), "da" (Danish)
```

This check doesn't make much sense in our workflow where we add a new string, PR to develop, later translation gets added from translatewiki branch.
I agree with myself from 8 months ago that this should be a warning but we should resolve these existing issues

@Abijeet if you have any insight here your input would be appreciated

**Comment by macgills** [comment]
@Abijeet I was under the impression that TW would insert English values for the strings into a languages strings.xml if the value was not there. Does this just happen for some languages? Or have I imagined this feature? I have only the vague memory of a comment on a PR.

**Comment by Nikerabbit** [comment]
We do not do that. The de facto practice is that the upstream projects to use an i18n library that will automatically fill in missing translations from fallback language(s) (usually from English, but can be more complex than that).

**Comment by macgills** [comment]
@Nikerabbit I think my confusion arose from `values-eu\strings.xml`
specifically
```
  <string name="pref_hide_toolbar_summary">u2022 On GNU/Linux and with the console: split —bytes=4000M my_big_file.zim</string>
```
which is not in Basque and is also very different from the string in English
```
  <string name="pref_hide_toolbar_summary">Keeps the toolbar from scrolling out of view when browsing content</string>
```

Android does provide this fallback system for us, if a string is not defined in `values-XX` the base string in `values` is used

**Comment by macgills** [comment]
Ensuring we have no missing translations at PR time is not feasible for the 100~ languages in the app. My PR has been updated to reflect this and I will consider the issue closed once it has been merged

**Comment by kelson42** [comment]
@macgills In case this was not clear, we can ask TW to update languages only if more than X% of strings are translated.

**Comment by macgills** [comment]
They track that here https://translatewiki.net/wiki/Special:MessageGroupStats/out-kiwix , I don't think they need us to tell them percentage coverage. Or maybe I have misunderstood your meaning

**Comment by Nikerabbit** [comment]
https://translatewiki.net/wiki/Translating:Kiwix mentions the current (default) export threshold of 25%. Language below this threshold are not updated (but neither removed, if they they previously were added while being over the threshold).

**Comment by macgills** [comment]
@kelson42 this ticket is about the lint check and it has been made a warning. If we are to request more translations or anything else this should probably be another ticket? For me the end goal of this ticket has been achieved

**Comment by macgills** [comment]
The PR is still open so I will reopen this
