### ISSUE TITLE
Lint Issue: CheckResult

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1273]
**Is your feature request related to a problem? Please describe.**
```
Ignoring results  
Some methods have no side effects, an calling them without doing something without the result is suspicious. 
 Issue id: CheckResult
```

**Describe the solution you'd like**
I think this can be a warning. A build failure doesn't need to occur because a return value is unused especially with the often useless nonsense that comes from android classes

**Comment by kelson42** [comment]
@MohitMaliDeveloper Please reactivate the linting and clean the code where this is necessary. You confirm that if linting fails then CI is red?
