### ISSUE TITLE
Lint Baseline Issues

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1274]
**Is your feature request related to a problem? Please describe.**
There are potentially 2000+ issues that we are not checking because they are obscured by our baseline file

**Describe the solution you'd like**
A series of sub tickets on this issue to address baselined issues in manageable chunks. Once the baseline file is empty we can consider this done

**Comment by abdulwd** [comment]
How do we update the baseline file? Or is it auto-updated when we fix an issue?

**Comment by macgills** [comment]
The baseline needs to be updated, ie delete it and next time you run lint it fails and creates an up to date baseline
