### ISSUE TITLE
Lint Issue: Duplicate Strings

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1275]
**Is your feature request related to a problem? Please describe.**
```
Duplicate Strings
 Duplicate strings can make applications larger unnecessarily.
 This lint check looks for duplicate strings, including differences for strings where the only difference is in capitalization. 
Title casing and all uppercase can all be adjusted in the layout or in code.  
Issue id: DuplicateStrings
```

**Describe the solution you'd like**
This should be fixed to reduce app size and lessen the burden of translation. It will require a regeneration of translations after the issue is addressed for English.

**Comment by kelson42** [comment]
Old duplicates should be fixed and linting detection should generate a hard error if this happens again.
