### ISSUE TITLE
Get your apps ready for 64 bits. What does that mean?

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1277]
After reading https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html I'm still not 100% sure what it means to us:
* If we do nothing, how this will impact our (custom apps) users?
* Does the 1 August is an important date for us?
* Do we have to do something to secure the same level of service as today?

**Comment by macgills** [comment]
**August 1, 2019** 
After this date we will have to release custom apps with 64bit architectures.

 **August 1, 2021**
After this date users with 64 bit devices will not be allowed download 32 bit apps.

A user with a 32 bit device and a 32 bit app will see no changes

**Comment by kelson42** [comment]
@macgills AFAIK all our (custom) apps support architecture `arm64-v8a` and `x86_64`. So, does that mean that this news has no impact at all for us?

**Comment by macgills** [comment]
From the email I got it seems one of our apps does not support some 64bit architecture

**Comment by kelson42** [comment]
@macgills Yes, that is why I have open the ticket. But it seems to be not specified. I suspect this is our app which is blocked. So, lets assume that. I really hope anyway that in the first half of August we can release new custom apps. Thx for the explanation.
