### ISSUE TITLE
Specify book name of the zim being deleted

### ISSUE THREAD

**Issue by Aditya-Sood** [kiwix/kiwix-android#1278]
So earlier long pressing a zim displayed a dialog to delete it
In #866, since the files also had to be selected, I replaced long pressing with selection, with an option to share or delete on the CAB. And since multiple files could be deleted, I added the book name of the zim being deleted to the dialog to avoid confusion as to which one is currently being deleted.

`develop` currently follows the previous pattern of showing a simple dialog multiple times for all the files to be deleted:
<p align="center">
  <img src="https://user-images.githubusercontent.com/15438998/60962840-de00e580-a32c-11e9-9641-31f888792932.png" width="350">
</p>

Post #1254 which readded the CAB to 'Library', we need to display the file name to clarify this

I couldn't do so by creating the custom-message `KiwixDialog` at [this line](https://github.com/kiwix/kiwix-android/blob/develop/app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/effects/DeleteFiles.kt#L22) from lack of kt know-how

**Comment by Aditya-Sood** [comment]
@macgills please have a look

**Comment by macgills** [comment]
There will need to be an update to DeleteZim and AlertDialogShower as previously all the dialogs were just showing text via ids, to support formatted Strings I will probably extend the KiwixDialog hierarchy but I must think about the best way to go about this
