### ISSUE TITLE
Move AndroidStorageDevices to KiwixAndroid

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1279]
**Is your feature request related to a problem? Please describe.**
There are currently resource leaks happening in this library that strict mode has highlighted and to make modifications to fix them would require a release of it

**Describe the solution you'd like**
Move the code internally to the project with the blessing of @mhutti1 and close the leaks

**Comment by kelson42** [comment]
@mhutti1 Worth the information for you IMO.

**Comment by mhutti1** [comment]
Sounds good.
