### ISSUE TITLE
travis won't give testdroid an api key on commits triggered from a non member

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#128]
Just realised something, travis won't give testdroid an api key on commits triggered from a non contributor because it might lead to the key being exposed. This will likely cause this build to fail (although the gradle build will still succeed). What do you want to do about this long term?

First reported here https://github.com/kiwix/kiwix-android/issues/126#issuecomment-299550664

**Comment by kelson42** [comment]
@mgautierfr any idea?

**Comment by kelson42** [comment]
@mhutti1 Hmm, you have fixed that one I believe with the test-gateway. Can we close that ticket?

**Comment by mgautierfr** [comment]
> Just realised something, travis won't give testdroid an api key on commits triggered from a non contributor because it might lead to the key being exposed. This will likely cause this build to fail (although the gradle build will still succeed).

Yes, and this is a good thing. 

> What do you want to do about this long term?

I'm not sure you ask me what to do. But the thing to do is to make the CI not depending of secret keys.

**Comment by kelson42** [comment]
@mgautierfr This problem has been resolved with https://github.com/kiwix/test-gateway
