### ISSUE TITLE
100 NullPointerException crashs reported a week

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#129]
This is what Google Play tell us, and this does not count the custom apps. This is by far the main reason of crashes of the app - TOP8 crash tracelots. Can something be done about it?

**Comment by kelson42** [comment]
@mhutti1 @rashiq @EladKeyshawn Who volunteers?

**Comment by mhutti1** [comment]
I have looked at them and I think some might be fixed. I can look into further close to 2.3 release though.

**Comment by kelson42** [comment]
@mhutti1 thx, yes maybe just before the end, checking each of this scenario might make sense.

**Comment by mhutti1** [comment]
Done some work on this in #229. We will see if it has made improvements.

**Comment by kelson42** [comment]
This report is really old. Many scenarios have been fixed meanwhile and @macgills monitors this carefully now.
