### ISSUE TITLE
Use LanguageActivity

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1292]
**Is your feature request related to a problem? Please describe.**
Due to merge problems with 2.5->3.0 LanguageActivity is no longer used but instead the older LanguageSelectDialog

**Describe the solution you'd like**
Revert to the 3.0 LanguageActivity

**Comment by kelson42** [comment]
@macgills I'm not sure to properly understand. Does that mean the language selector needs to be ported a second time to Kotlin?

**Comment by abdulwd** [comment]
@kelson42  The language selection dialog was changed to a separate activity that also includes searching the list of languages. So because of merging the old dialog is being displayed instead of the new activity.
