### ISSUE TITLE
Landing page is not displayed on Wikimedia zims

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1294]
Kiwix-Android 2.5.1 build 220501 / Huawei P20 Lite Android 8.0

I recently noticed that Kiwix does not read/show the landing page of Wikimedia zims: I am only shown a blank page . I tried other mediawiki zims (e.g. Granblue or InstallGentoo) and they mostly worked, although some (ArchWiki, WikEM) did not either. Non mediawiki (PhET, Skin of color) The bug remains after rebooting the phone, uninstalling/reinstalling Kiwix.

The zims itself may or not work: on most I can search for articles and open/read them, but on WikEM for instance I can search but opening the corresponding page will only give me a blank page.

Please see https://github.com/kiwix/kiwix-android/issues/1294#issuecomment-514963853 for a step-by-step reproduction case.

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/61465225-8fc49580-a96f-11e9-9732-9f5dee00ec2b.png)
which Archwiki? It also worked for all WikiEms I just tried. Nexus 5X 8.1.0

**Comment by Popolechien** [comment]
@macgills Archwiki 2019-04-01 novid/nopic (does not really matter). Btw I confirm that Archwiki won't display any other page either (though search does seem to work / list articles)
![Screenshot_20190718-163248](https://user-images.githubusercontent.com/21675885/61466186-c43d4f00-a979-11e9-89b4-9c16c63ab117.jpg)

**Comment by macgills** [comment]
Can I ask you to try with a [nightly?](https://download.kiwix.org/nightly/2019-07-18/)

**Comment by Popolechien** [comment]
Dammit - it did work for half a second until I tried to open another wiki and then it did not work anymore :-/

**Comment by kelson42** [comment]
I have I think saw that kind of behaviour myself, but this is sporadic and never achieved to get a fully pattern. I suspect, a trace would be really helpful here.

**Comment by macgills** [comment]
I am unsure how to proceed, Zim rendering is still a mystery to me tbh

**Comment by Popolechien** [comment]
Well the mystery deepens. I uninstalled and reinstalled once more and now rendering is fine (tried several files, incl. WikEM and Archwiki).
Should we close the ticket?

**Comment by macgills** [comment]
well my suspicion was that the WebView on your phone was wonky but that doesn't seem to be the case.
Equally it should not be kiwix-lib as that has remained the same.
How frequently do we reupload zims? Is it actually the same zim?

Otherwise it is a transient error and that is awful news

**Comment by Popolechien** [comment]
Ok, I'm reopening the issue as I get a little more reproducibility:
- Upon installing the app, I can open zim files and they display normally
- If I close the app, clear the phone's memory and then reopen the app -> the landing pages are not shown anymore. I've repeatedly uninstalled / reinstalled to the same effect and pattern.

**Comment by Popolechien** [comment]
Good news: I'm not the only one having this issue.
Bad news, I'm not the only one having this issue. From OTRS:
"Hi, I've installed yesterday Kiwix on my android 7 phone (device model Xiaomi Mi Max 2), with 4GB Ram, 64 GB Rom. The app installed ok, found 4 zims I had already downloaded on my 64gb sd card, opened them ok, browsed them ok, read 5-10 several articles without issues, everything looked fine. Today I opened the app and can't open my previous zim, I get a blank white screen. The 4 zims are still there, but the app can't find them, even when I direct it to open them via its menu. I tried uninstalling the app, installed it again, works ok the first time I run it, but the second time (after closing and reopening it) has the same issue as before, can't open the zims."

**Comment by Popolechien** [comment]
FWIW, someone wrote: "Update it as soon as you exit and close the application, after no longer able to access the external and internal memory, you must go to delete data every time." 
(ok, he's Italian, so forget the grammar)

**Comment by kelson42** [comment]
@Popolechien not sure about what that means at all... not even sure the symptom is the same as for this ticket.

**Comment by KapeSP** [comment]
Hi, everybody

I am new here and have seen this thread in Google. But I hace the dame problemas in two phone since four days, so i tel you more info.

Two phones: Samsung Galaxy 9 and Honor 6C

**Comment by kelson42** [comment]
@macgills My feedback. I can easily reproduce the problem (at least a problem which seems to match the description). Here are the steps:
* Install nightly
* download WiKem novid
* open it, everything works fine.
* Quite the app (remove it from the hibernate list of apps)
* Restart it, then you get a blanck screen, the last open ZIM file welcome page is not loaded properly.

Here is how it looks like in the log
```
07-25 11:02:00.531  8218  8218 I TextToSpeech: Connected to ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService}
07-25 11:02:00.537  5147  5160 I TTS.GoogleTTSServiceImp: For default lang en-us is name en-US-language (en-us-x-sfg-server)
07-25 11:02:00.537  8218  8317 I TextToSpeech: Set up connection to ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService}
07-25 11:02:00.547  8218  8304 I kiwix   : Attempting to create reader with: /storage/emulated/0/Kiwix/wikem_en_all_novid_2019-05.zim
07-25 11:02:00.547  8218  8304 I kiwix   : Opening ZIM file /storage/emulated/0/Kiwix/wikem_en_all_novid_2019-05.zim
07-25 11:02:00.619  8218  8315 D kiwix   : reading  A/Main_Page(mime: text/html, size: 10303) finished.
07-25 11:02:00.676  8218  8307 I OpenGLRenderer: Initialized EGL, version 1.4
07-25 11:02:00.676  8218  8307 D OpenGLRenderer: Swap behavior 1
07-25 11:02:00.718  8218  8218 D kiwix   : Loaded URL: null
07-25 11:02:00.719  8218  8218 D kiwix   : TextToSpeech was initialized successfully.
07-25 11:02:00.745  8218  8218 W wix.kiwixmobil: Accessing hidden method Landroid/text/SpannableStringInternal;->length()I (light greylist, linking)
07-25 11:02:00.835  1141  1177 I ActivityManager: Displayed org.kiwix.kiwixmobile/.main.MainActivity: +1s716ms
```

It seems that Kiwix is not able to retrieve the welcome page URL of the last ZIM (`Loaded URL: null`).

**Comment by Popolechien** [comment]
Further feedback on OTRS - I suspect it relates to this particular issue: 

>I had to stop the Background Connectivity to get Kiwix to work.
>Symptoms amd way to resolutions:
>- my four Wikipedia files were shown when I looked for my contents but the 
screen kept blank.
>Assumed that the SD card had problems and replaced it with new copies of 
the zim files.
>- after replacement of the card Kiwix showed the zim files but stated that 
it cannot open the files.
>Reinstalled Kiwix multiple times with removal of all leftover config files. 
>Did not help.
>I now assumed that Kiwix load config information remotely. After 
reinstallation I reinstalled but removed network connections Connectivity 
after download.
>Kiwix did work correctly with menu in German now. After enabling 
connectivity again blank screens were shown again and menu has changed to 
English.
>Reinstalled again with stopping the network, disallowed background 
connectivity and started the network. Now it still works.
>
>I guess you store configuration information for users remotely but this 
gets corrupted."

**Comment by kelson42** [comment]
I got also directly per email and on the sourceforge forum.

**Comment by kelson42** [comment]
@macgills @mhutti1 @siddharth2010 @rashiq @abdulwd We get meanwhile each day complains about that regression. We have to fix it in top priority and release a 2.5.2 ASAP. We can not wait additional weeks that 3.0 will be ready.

**Comment by macgills** [comment]
The content uri has no extension, this is causing an NPE in ZimContentProvider.getType(). This would have been a compile time issue in kotlin.
It is a one liner fix, opening a PR now

**Comment by kelson42** [comment]
@macgills To me, 2.5.2 has fixed the problem, but the PR and the ticket is surprinsingly still open?
