### ISSUE TITLE
Allow custom strings/translations files for custom app

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#13]
The phet app needs to rename a few menu entries

**Comment by mhutti1** [comment]
This should be possible as of now with manifest merge. If you still want it as a feature we will need more details.

**Comment by kelson42** [comment]
@mhutti1 Maybe we could provide a standard way to overwrite a menu entry in the custom app json file? I'm not familiar with the "manifest merge", is that a feature of the Android SDK?

**Comment by mhutti1** [comment]
@kelson42 Yeah its a gradle feature. With our new system you can overwrite resources simply by placing the new resource you want in the corresponding folder. So if you wanted to overwrite strings.xml you simply place a new strings.xml in phet/res/xml/strings.xml (might be slightly different). Obviously its slightly more complicated if you need to import new strings though and you have the problem of keeping both strings up to date. It might be easier to replace the menu itself with the same technique and add the strings to the standard strings file.

**Comment by kelson42** [comment]
@mhutti1 Is that an "overwrite" or a "merge"? A "merge" would be great, as we would only put the one or two strings the app wants to custom. Otherwise ("overwrite"), we need to keep the whole strings.xml up2date (with the std app strings.xml).

**Comment by mhutti1** [comment]
@kelson42 Just gave it a try and it appears to merge, prioritising custom app resources. This will work perfectly for our use case.

**Comment by kelson42** [comment]
@mhutti1 Before closing the ticket, could you please tell me exactly:
* The path/name of the XML files (for english ans translations)?
* The original location on which which should take example?

**Comment by mhutti1** [comment]
You simply add xml files in the corresponding location with the coresponding name to the custom app generation folder like so:
https://github.com/kiwix/kiwix-android/blob/master/app/src/raycharles/res/values/strings.xml

Is this clear? Its quite hard to explain.

**Comment by kelson42** [comment]
@mhutti1 thx
@ISNIT0 So this is for you :)
