### ISSUE TITLE
Kiwix cannot find an external SD partition on Acer B1-770

### ISSUE THREAD

**Issue by bobthomson100** [kiwix/kiwix-android#130]
At the request of Emmanuel Engelhart in [the Sourceforge discussion here](https://sourceforge.net/p/kiwix/discussion/604121/thread/3b517029/), I am writing to open a "ticket" to try to resolve a problem I'm having getting Kiwix to recognize a 20 GB zim file on a second ext3/ext4 partition on my external SD card of my Acer B1-770 android tablet running Android 5.01.

On the tablet, using ES File Explorer, the vfat/msdos partition is mounted at /storage/sdcard1. The ext3/ext4 partition seems to be at /data/sdext2. I say seems, because I'm not able to create a kwix folder there. When I ask ES File Explorer to add a folder named kiwix to /data/sdext2, it says "kiwix" created, but the folder doesn't appear there. When I create a folder named kiwix at /data, it gets created and I can copy a small zim file to /data/kiwix/, so the normal prohibition of using /data seems to be waived for /data but not for /data/sdext2. The tablet is rooted by the way. I suppose this might be a problem with ES File Explorer, although I don't know why it could create a folder at /data but not at /data/sdext2.

I have two distinct smaller zim files on the internal SD card at /storage/sdcard0/Kiwix (the internal SD card) and another different one at /storage/sdcard1/kiwix (the vfat/msdos partition on the external SD card). Kiwix "sees" and loads both. So the problem seems to be that Kiwix can't access the ext3/ext4 partition which seems to be at /data/sdext2.

I hope someone can help me resolve this as I'd really like to have Wikipedia on my tablet.

Bob Thomson <bthomson@web.ca>

**Comment by mhutti1** [comment]
@bobthomson100 I will look into this bug can I get some extra information first. 

1. Can you see files/folders in /data/sdext2 using ES file Explorer
2. Are you sure you can't modify the contents of this directory and its sub-directories?
3. If you can get a ZIM file on the sdcard and then click it with ES file explorer and try to open it with Kiwix, does it load correctly.

**Comment by bobthomson100** [comment]
I notice my reply to Isaac Hutt's email isn't posted here. Did it get through?

**Comment by kelson42** [comment]
@bobthomson100 nothing went through.

**Comment by bobthomson100** [comment]
OK. Here's what I "posted" via a reply to the email I received.

On 2017-05-08 06:47 PM, Isaac Hutt wrote:
>
> **_@bobthomson100 I will look into this bug can I get some extra information first._**
>
**>     _**Can you see files/folders in /data/sdext2 using ES file Explorer****_
>
No. Or at least I couldn't earlier. See below.
>
>     **_Are you sure you can't modify the contents of this directory and its sub-directories?_**
>
Yes. Or rather, I could add directories to /data. But then I couldn't add them to /data/sdext2.

However, I just tried again and managed to create /data/sdext2/kiwix. I then found a subdirectory /data/sdext2/.Trash-1000 there as well. I tried to copy a zim file into the /data/sdext2/kiwix folder and got a box showing the paste process which finished with the statement "Copy files successfully to /data/sdext2/kiwix". However, no file appeared there. I rebooted the tablet, i.e. turned the power off and then on again. Same problem - I can go to /data/sdext2/kiwix but see nothing there.
>
>     **_If you can get a ZIM file on the sdcard and then click it with ES file explorer and try to open it with Kiwix, does it load correctly._**
>
In ES file explorer I went to the ZIM file I copied to /data/kiwix and clicked on it. I got a rapidly flashing entire tablet screen which seemed to be running Kiwix (there was a [3 menu bars actually] = KIWIX text at the top left hand corner of a white rapidly flashing screen). There was a box in the middle of the flashing screen (also flashing) asking for feedback on Kiwix and at the bottom of the flashing screen there was non-flashing text that said "To access offline content we need access to your storage". I let it flash for about 5 minutes (it was a 480 mb zim file) and it didn't stop flashing. When I pressed the Android stop button at the bottom of the screen, this message "To access offline content we need access to your storage" stayed on the home Android screen in a dark background with white text. I copied the wikipedia medicine nopics zim file into a new folder at /data/test1/test2 and then clicked on it. I didn't get the flashing screen this time but the "To access offline content we need access to your storage" message appeared at the bottom of the screen. In both the /data/kiwix folder and the /data/temp1/temp2 folder, the small box on the left of the name of the zim file in ES File Explorer had a question mark in the middle of it. I assume that means ES File Explorer didn't know what to do with a zim file whereas it does seem to know for example which app to use to open a *.jpg file or to provide a menu of possible apps for say a *.zip or *.doc file.

The settings menu of Kiwix still only shows one storage source, that of the internal SD card. So no way to chose another source of zim files.

I hope that narrows down the source of the problem.

Bob

**Comment by mhutti1** [comment]
Firstly /data/kiwix is just going to be an internal storage location as it isn't mounted anywhere (we don't look here when searching for ZIM files because on most systems it would likely be access protected). Secondly there looks to be little that we can do about getting Kiwix working with the external sd card if you can't find the files in ES file explorer unfortunately. I don't know much about how Android mounts extra file systems but it is likely done at the manufacturers discretion so unless you can figure a way to mount the partition so that es file explorer can read it unfortunately there is nothing that we can do to access it either.

**Comment by kelson42** [comment]
Nothin much we can do here.
