### ISSUE TITLE
File system error when trying to download zim

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1303]
Apparently the user was downloading a file when he updated and got the below error message, but I've asked him to clarify if it happens every time from now on.
![Screenshot_20190721_092513_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/61616541-0069fb80-ac69-11e9-83a7-9d20b4434627.jpg)

**Comment by macgills** [comment]
quite the same as #1304 unfortunately, I have no more information than what was is reported to me by DownloadManager

**Comment by kelson42** [comment]
There is nothing we can do here, this is either a bug with Android (probably not) or a problem with the hardware (most probable).
