### ISSUE TITLE
Links to content inside the same ZIM file (BlackBerry=QNX+android runtime)

### ISSUE THREAD

**Issue by dapgo** [kiwix/kiwix-android#131]
Using the jelly bean android runtime, Kiwix does the following functions with success:
Displays the Home page
Search function  find and access to any entry in the ZIM file
Random article opens a random ZIM content page
Links to external webpages work fine

However when a you press over a link to local content (same ZIM) a blank page is loaded.

**Comment by kelson42** [comment]
What is that exactly for a runtime "QNX + Android"?
Sounds really strange to me?

**Comment by dapgo** [comment]
QNX is the operating system that Blackberry has been using for the last few years and they run android apps through android jelly bean runtime
[https://developer.blackberry.com/android/apisupport/android_native_support.html](https://developer.blackberry.com/android/apisupport/android_native_support.html)

**Comment by kelson42** [comment]
the problem will be complicated to fix I think as this is pretty obviously a blackberry specific issue, we do not have any device of that kind... and BB mobile bisness has been stopped (so no real reason for us to invest lots of resources on this).

**Comment by dapgo** [comment]
IMHO the solution can be something quite basic, in fact 99% of apps (not using google play services) works seamlessly. 
At least, can you tell how kiwix access to data after clicking a link?
I tried to logging the output after click the link but i cannot see any event.

**Comment by mhutti1** [comment]
@dapgo We use a content provider to navigate inside a webview, The clicking and navigation is handled by the Android runtime we just give Android content when it asks for a url. Theres a chance its asking for the wrong url. If you restart the app while on a blank page does the log indicate the url of the page that is being opened?

**Comment by kelson42** [comment]
@dapgo Does this problem still occur with last version of Kiwix?

**Comment by kelson42** [comment]
Strongly suspect this problem has been fixed, other please reopen the ticket.
