### ISSUE TITLE
Poor search feature on Android + Index files too large for Fat32

### ISSUE THREAD

**Issue by khanhhung2512** [kiwix/kiwix-android#1320]
I just performed a search on Kiwix for Android, Wikipedia database, non-indexed with keyword "eMMC" and it yielded no result. I had to search for "Multimedia Card" instead. However, on Windows, the search for "eMMC" yielded the right result, even though the database isn't indexed.

Also, even though the zim files are divided so that I can copy them to Fat32 drives/SD cards, the index files aren't. Therefore, I cannot perform a full-text-search on Kiwix for Android. I wonder if I can divide those index files myself. Will Kiwix recognize them?

**Comment by kelson42** [comment]
This is fixed in Kiwix Android 3.0.
