### ISSUE TITLE
[Bug] Android app: search is not always case insensitive [sf#943]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-android#1321]
**Reported by axel_boldt on 2016-02-24 00:56 UTC**
I'm using Android Kiwix 1.96 on Android 4.4.4, with the complete German Wikipedia zim file.

I expect the search to be case insensitive, and for the most part it is: searching for "am adler" or "Am adler" or "am Adler" or "AM ADLER" or "aM aDler" will all find the article "Am Adler". 

But if the article title has three or more words, and the second word is lower-case, then case-insensitive search does not work: searching for "frankfurt am main" or "Frankfurt Am Main" or "FRANKFURT AM MAIN" will not find the article named "Frankfurt am Main", yet searching for "frankfurt airport center" or "FRANKFURT AIRPORT CENTER" or "Frankfurt Airport center" or "fRankfurt aIrport cEnter" will all find the article named "Frankfurt Airport Center".

Also, case-insensitive search does not work right if the article starts with a lower-case letter: searching for "A posteriori" will find the article named "a posteriori", but searching for "A Posteriori" or "a Posteriori" or "A POSTERIORI" will not find it.

**Comment by kelson42** [comment]
It is now.
