### ISSUE TITLE
[Bug] Rendering on Android - main page of Russian Wikivoyage [sf#841]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-android#1322]
**Reported by abaturin on 2015-02-28 20:50 UTC**
Main page of Russian Wikivoyage looks ugly on Android. See the attached screenshot.

I'm not sure if that's a bug in Wikivoyage page markup itself, or that is a bug in Kiwix.

**Comment by kelson42** [comment]
Old bug report. To be checked again.

**Comment by kelson42** [comment]
This has been fixed.
