### ISSUE TITLE
Hotspot Ip address incorrect for Android Pie

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1325]
Hotspot ip address changes everytime it starts for android pie. P.S: I've worked around that in this [commit](https://github.com/kiwix/kiwix-android/commit/8516403d066ae852fa87320e4372e32c043e0e09).
The issue right now is i'm unable to host the server on that ip address for pie. We need to do the following things now:
**1.** Confirm if the ip address i'm getting for pie is correct using the hardware settings of the device.

_If it is correct then,_
**a.** figure out why we're unable to host the server with that ip address on pie.

_If the ip address is incorrect then,_
**b.** figure out how to get the correct ip address for pie.

**Comment by kelson42** [comment]
@iadeelzafar Regarding your code I have a few remarks:
* An IP should be stored in a proper class, not as a string.... and for sure not with `\n` at the end.
* If the device has many interfaces, this is not clear at all how you choose the one to pick. To me it should be the WIFI one, but there is nothing about that in your code.
* I really wonder about this `isSiteLocalAddress()`, in fact it seems to me we need exactly the opposite, a public address, so non local.
* The IP of the device and the HTTP server are two unrelated things. The IP is only important to communicate to people, to display in the dialog. What we need for the HTTP daemon is the network interface to bind to.
* An IP should never have a `\n` at the end... and like said before it should be store in a proper class, not as a string

**Comment by iadeelzafar** [comment]
@kelson42 So IMO what we need to do at this point is confirm the ip address using the hardware settings of the device. This will be concluded as soon as I'm able to get my hands on an Android 9 device.

**Comment by kelson42** [comment]
@iadeelzafar What is the status on this?

**Comment by iadeelzafar** [comment]
@iadeelzafar This one has been resolved in 45208f64a712fa647b82c5ef981e7a5acf235828 . I tested it on a number of Android Pie devices and we're getting the correct ip address now. I believe this can be closed.

**Comment by iadeelzafar** [comment]
**Conclusion in relevance to this ticket's description:**
We were already getting the correct ip address on Android Pie. But we were unable to host the server due to some other reason which was resolved later on. So, ip address was never the issue.
