### ISSUE TITLE
MANAGE_WRITE_SETTINGS screen won't appear

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1328]
**Problem description:**
Manage write settings screen won't appear. A wifi screen shows up instead.
A little background i,e, We need this permission to turn on wifi hotspot programmatically on devices < Oreo.

_P.S: This issue arised on the older version of our wifi-hotspot branch where we're turning on hotspot programmatically for devices version<Oreo._

**Tested device:**
Android 6.0.1
Galaxy tab S SM-T700

**Comment by iadeelzafar** [comment]
Quoting from android developer [documentation](https://developer.android.com/reference/android/provider/Settings.html#ACTION_MANAGE_WRITE_SETTINGS):

> In some cases, a matching Activity may not exist, so ensure you safeguard against this.

**Comment by iadeelzafar** [comment]
Looking at this [question](https://stackoverflow.com/questions/48422080/no-activity-found-to-handle-intent-act-android-settings-action-manage-write-se) on SO, all that we could do AFAIK is to handle the crash.
But in our case there's no crash, instead a different screen i.e. wifi screen shows up.

**Comment by iadeelzafar** [comment]
I'm looking forward to anyone's input on this, if there's any way we could figure this out. 
Btw this is how the [write settings screen](http://prntscr.com/onyh69) looks like.

**Comment by abdulwd** [comment]
You can just show a dialog to the user to open the hotspot manually.

**Comment by kelson42** [comment]
@iadeelzafar What is the status on this? What will be the exact impact? How many users will be impacted?

**Comment by iadeelzafar** [comment]
@kelson42 This is no more relevant. Since now we don't ask for **MANAGE_WRITE_SETTINGS** permission. Now we're telling the user to turn on hotspot manually on devices<Oreo.

**Comment by kelson42** [comment]
@iadeelzafar Thx for the feedback. Therefore, I'll close the ticket.
