### ISSUE TITLE
Ip address empty for android 7

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1329]
**Bug:**
Empty ip address is returned.

**Tested device:**
Android 7

**Comment by iadeelzafar** [comment]
@kelson42 can you please tell us the name of the device?

**Comment by kelson42** [comment]
It is a FairPhone

**Comment by kelson42** [comment]
@iadeelzafar What is the status on this?

**Comment by iadeelzafar** [comment]
@kelson42 I'll send you a newer APK and you can test on this device to confirm if this issue has been resolved.

**Comment by kelson42** [comment]
Any apk?

**Comment by kelson42** [comment]
I have tested a custom APK provided by @iadeelzafar and it seems to work now on my test device :)
