### ISSUE TITLE
TestDroid emails sent to Kiwix contact email address

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#133]
I just have discovered this and I strongly suspect that @Popolechien is not really interested to to get this CI notification for the Android port. It looks like this is something we can configure with Testdroid web interface. Should we disable this notification? Or it would maybe make sense that @mhutti1 still get them (in that case it looks like to be doable, as the notification email is configuration). What do you think @mhutti1?

**Comment by mhutti1** [comment]
Is it testdroid or travis sending these emails?

**Comment by kelson42** [comment]
@mhutti1 I just have forwarded one to you, but it comes from bitbar.com

**Comment by mhutti1** [comment]
Should be fixed. You can add/remove email addresses for people to receive
notifications.

**Comment by kelson42** [comment]
@mhutti1 perfect. thx.
