### ISSUE TITLE
Add progress/loading indicator for suggestions

### ISSUE THREAD

**Issue by I338** [kiwix/kiwix-android#1330]
It would be nice if there was some kind of indicator that the app is doing something while it is searching in the background.

**Comment by kelson42** [comment]
@I338 The search should really quick. I think here this is the main problem that currently it is not.

**Comment by I338** [comment]
That's a good point. I guess if the search was fast enough, it would be silly to have a loading bar.

**Comment by kelson42** [comment]
After release of 3.0 we should re-evaluate if this is necessary.

**Comment by macgills** [comment]
Can we also specify which search this is referring to?

**Comment by kelson42** [comment]
@macgills This is the suggestion system, but we will have a similar challenge one time we will implement the fulltext search.

**Comment by macgills** [comment]
this has been done
