### ISSUE TITLE
What's the point of `kiwix-android/app/gradle/wrapper` ?

### ISSUE THREAD

**Issue by licaon-kter** [kiwix/kiwix-android#1332]
This will throw off fdroidbuilder and tries to use Gradle 3.3 to build and fails, since it's too old.

Ref: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.kiwix.kiwixmobile.txt#L96

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/62607355-de71a980-b8f5-11e9-84b9-41f0f81ed0ab.png)
The what? Are you on the develop branch @licaon-kter ?
The repro environment is only frdroid builder?

**Comment by licaon-kter** [comment]
I can see it in 2.5.1: https://github.com/kiwix/kiwix-android/tree/2.5.1/app

**Comment by macgills** [comment]
Seeing as this no longer exists on develop and a 3.0 release is in the pipeline I would move to close this ticket if that is alright by you?
