### ISSUE TITLE
Why create an empty text.text and hidden .storageLocationMarker?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1333]
Question from a user on OTRS (Xiaomi Mi A2 Lite)
" I've noticed that kiwix is creating a 0 byte text.txt and the hidden file .storageLocationMarker. Is this really necessary? Is there no nicer way to check storage access?"

**Comment by kelson42** [comment]
I have already noticed that and I think @macgills was surprised about that. But this is a bug, at least the file should be removed just after its purpose is over.

**Comment by mhutti1** [comment]
I do not think there is an easier way. I guess we could delete them. The main issue was a as far as I am aware there was no way to tell whether two mount points pointed to the same file system.

**Comment by kelson42** [comment]
@mhutti1 Yes, file has to be deleted.

**Comment by kelson42** [comment]
RIIA pattern should be used here. Whatever how you get out of the scope, the temporary file should be automatically deleted.

**Comment by kelson42** [comment]
Example of implementation https://docs.juce.com/master/classTemporaryFile.html
