### ISSUE TITLE
Can't find article by its exact name (Space Shuttle retirement)

### ISSUE THREAD

**Issue by moneytoo** [kiwix/kiwix-android#134]
I use Kiwix v 2.2 on Android (Samsung Galaxy S7 / Android 6.0.1) with the latest full English wiki (wikipedia_en_all_2016-12.zim, MD5 is 6a8c2dead3219cb8eba901db15ddeca9 so it's ok).

My intention is to find the article ``Space Shuttle retirement``. There are lots of close results so the search phrase is not trivial. However searching for ``Space Shuttle re`` lists other two articles but not the one I'm looking for. More exact phrase also doesn't work. (I'm however able to get to the page when using shorter phrase such as "Space Shuttle ").

![query](https://cloud.githubusercontent.com/assets/1071643/26163191/3389eb28-3b29-11e7-850f-142ab695f635.png)

(Enabling "Fulltext Search" in Settings has no effect on this.)

I tried the desktop version (version 0.9 on Windows 10) and I get different results based on case sensitivity (I didn't check for similar issues outside the Android version).

![query-win](https://cloud.githubusercontent.com/assets/1071643/26163482/2086ae7a-3b2a-11e7-8721-aee40d93f001.png)

**Comment by kelson42** [comment]
@moneytoo Thx for your bug report. We have many problems with the search systems and are currently working on them. We will come back to you in a few weeks with new informations.

**Comment by Wikinaut** [comment]
Just re-installed Kiwix and 25 GB German Wikipedia with images but novideos

Found, that many searches are not functioning

One example is my test search for "tatort":
* only 6 results on first letter "t" ("t.A.T.u. Remixes" until "tRNA") ; and
* there are no results after having typed "ta".

Before the reinstallation, Kiwix crashed after having typed "jimi".

**Comment by Wikinaut** [comment]
Updated above:
* With "crash" I meant that certain search entries (characters) immediately killed the search and returned me to the Kiwix startpage. Currently I don't know, if this is an NPE, but could be something like that.

**Comment by kelson42** [comment]
The "crash" seems to be a bug to me and I will try to reproduce it. The rest seems quite "normal" as there is not FT index in that file. One time I will have introduced it (next version) then the problem should be fixed.

**Comment by kelson42** [comment]
Problem is still there with Kiwix Android 3.0.

**Comment by kelson42** [comment]
Still there and not specific to Android:
```
$ kiwix-search --suggestion wikipedia_en_all_nopic_2019-12.zim "Space Shuttle re"
Space Shuttle recovery convoy
Space Shuttle Rescue Mission
Space Shuttle Reaction Control System
$ kiwix-search --suggestion wikipedia_en_all_nopic_2019-12.zim "Space Shuttle ret"
Space Shuttle retirement
Retirement of the Space Shuttle
```
