### ISSUE TITLE
Multiple instances of the same Zim File visible on Home Screen

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#1342]
**Describe the bug**

Multiple instances of the same Zim File are visible on the Home Screen.

**Expected behavior**

There should only be one instance per zim file.

**Steps to reproduce the behavior:**
1. Open Kiwix
2. Click on 'Download Books'
2. Download a Zim File
3. Open the Zim File using the notification tray
4. Close all open tabs in the Kiwix app
5. Now, 4 instances of the same Zim file are visible

**Screenshots**

| -        | -          |
| :-------------: |:-------------:|
| ![Screenshot_20190810-153633](https://user-images.githubusercontent.com/32238400/62822607-37577100-bb86-11e9-8c35-792284d35819.png) | ![Screenshot_20190810-155244](https://user-images.githubusercontent.com/32238400/62822678-06c40700-bb87-11e9-8822-a6ce3ffa9bc4.png) | 

**Environment**
- Version of Kiwix Android : Latest 'develop' Branch (Version 2.5.1 Build: 10220501)
- Device : Samsung S6
- OS version : Android 7.0

**Logs**

**Comment by siddharth2010** [comment]
Another weird behaviour is that over time the zim files seem to switch icons

|    |          |         |      |
| :-------------: |:-------------:|:-------------:|:-------------:|
| ![Screenshot_20190810-165443](https://user-images.githubusercontent.com/32238400/62823293-febc9500-bb8f-11e9-8fed-d26c6dcdc3c8.png) | ![Screenshot_20190810-165429](https://user-images.githubusercontent.com/32238400/62823295-01b78580-bb90-11e9-8ff1-420e96633fa6.png) | ![Screenshot_20190810-165420](https://user-images.githubusercontent.com/32238400/62823296-067c3980-bb90-11e9-8cb3-23fe08548693.png) | ![Screenshot_20190810-165413](https://user-images.githubusercontent.com/32238400/62823298-0a0fc080-bb90-11e9-9386-061841c3bb08.png) |

**Comment by siddharth2010** [comment]
I am not quite sure whether this is specific to my device only. could someone please try to reproduce this. Thanks!

**Comment by abdulwd** [comment]
Working on this.
