### ISSUE TITLE
With 3.0, it is impossible to search in ZIM file quickly

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1344]
With 2.5 I see in the topbar:
* The magnnify glass icon I can click on
* If I click on the title of the ZIM file, I get the search input form

That is how it should continue to work IMO.

**Comment by abdulwd** [comment]
Clicking on the action bar does not open the search input.

**Comment by mhutti1** [comment]
Please open a new issue if you support this.
