### ISSUE TITLE
Git Commit fails because of GitHooks

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#1347]
**Describe the bug**

I am unable to commit to any branch because the GitHooks are failing.

**Logs**

````
Siddharths-MacBook-Pro:kiwix-android siddharth$ git add .
Siddharths-MacBook-Pro:kiwix-android siddharth$ git commit -m "Rename LoadBooks method and add instance in onResume"
Running lint...

> Configure project :app
Configuring Kiwix
Configuring kiwix
Configuring customexample

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/siddharth/Downloads/kiwix-android/app/build.gradle' line: 332

* What went wrong:
A problem occurred evaluating project ':app'.
> /Users/siddharth/.gradle/daemon/5.4.1/app/src/customexample/info.json (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

> Configure project :app
Configuring Kiwix
Configuring kiwix
Configuring customexample

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/siddharth/Downloads/kiwix-android/app/build.gradle' line: 332

* What went wrong:
A problem occurred evaluating project ':app'.
> /Users/siddharth/.gradle/daemon/5.4.1/app/src/customexample/info.json (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Static analysis found violations and attempted to autofix, please commit these autoformat changes
````

**Comment by mhutti1** [comment]
I think this is a MacOS issue. It works fine for me on linux. We should also test Windows.

**Comment by siddharth2010** [comment]
Yeah, I just checked it. its working fine on windows.

**Comment by macgills** [comment]
`/Users/siddharth/.gradle/daemon/5.4.1/app/src/customexample/info.json (No such file or directory)` this sounds like it is not the hook that is failing but just building in general?
It is possible to skip the hook by using `--no-verify` but that is not recommended

**Comment by abdulwd** [comment]
On macOS, I'm able to build and install kiwix-android and the custom app.

**Comment by siddharth2010** [comment]
The app seems to build and work perfectly fine.
Also, when I try to commit using android studio, then I am able to commit (after I uncheck "Run Git Hooks")

<img width="250" alt="Screenshot 2019-08-12 at 11 21 13 AM" src="https://user-images.githubusercontent.com/32238400/62855798-70f9ba80-bcf3-11e9-8a4a-c9a46b475c65.png">

**Comment by abdulwd** [comment]
@macgills But the hook fails.

**Comment by macgills** [comment]
here is the [script](https://github.com/kiwix/kiwix-android/blob/develop/team-props/git-hooks/pre-commit.sh) can you try running the gradle command and reporting back?

**Comment by siddharth2010** [comment]
Here is the output:
````
siddharths-mbp:kiwix-android siddharth$ ./gradlew app:ktlintKiwixDebugCheck app:lintKiwixDebug --daemon

> Configure project :app
Configuring Kiwix
Configuring kiwix
Configuring customexample

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/siddharth/Downloads/kiwix-android/app/build.gradle' line: 332

* What went wrong:
A problem occurred evaluating project ':app'.
> /Users/siddharth/.gradle/daemon/5.4.1/app/src/customexample/info.json (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
siddharths-mbp:kiwix-android siddharth$ 

````

**Comment by macgills** [comment]
`/Users/siddharth/.gradle/daemon/5.4.1/app/src/customexample/info.json` this path is immensely suspicious, where is the project on disk?

this is the code that is causing this error, it adds custom app flavors dynamically
```
// Custom apps built from a json file, zim file and icon set
    map.each { name, directory ->
      "$name" {
        println "Configuring $name"
        if (name == "kiwix") {
          return
        }
        if (file(directory + "/build.gradle").exists()) {
          apply from: directory + "/build.gradle"
        }
        def jsonFile
        if (project.hasProperty("jsonFile")) {
          // Read json file from properties e.g command line
          jsonFile = file(project.property("jsonFile"))
        } else {
          // If no file provided use the test file
          jsonFile = file(directory + "/info.json")
        }
        def parsedJson = new JsonSlurper().parseText(jsonFile.text)
        def sourceFile = file(parsedJson.zim_file)
        if (!sourceFile.exists()) {
          sourceFile = file(directory + "/" + parsedJson.zim_file)
        }
```

**Comment by siddharth2010** [comment]
yes, coming to think of it, this does seem a bit odd.

Here is the project path:
````
siddharths-mbp:kiwix-android siddharth$ pwd
/Users/siddharth/Downloads/kiwix-android
````

**Comment by macgills** [comment]
hmmm I don't think it would be the GRADLE_HOME variable.... this command should be run in the project directory and I have no good idea why it is going into the `.gradle`

**Comment by macgills** [comment]
comment out all of the `map.each { name, directory -> …. }` and check that that still works and there are no other problems

**Comment by siddharth2010** [comment]
Just a second. Actually I am using the embedded Gradle that comes with android studio.
I am trying to install the Gradle via brew and test it.

will get back in a minute

**Comment by macgills** [comment]
I mean if you use gradlew it should download the version of gradle specificed in the properties file, it is very handy and ensures everyone is using the same thing

**Comment by siddharth2010** [comment]
oh, got it. yeah. that seems about right..

I will comment out the map.each {...} lines and see that

**Comment by siddharth2010** [comment]
ok, so after commenting those lines, it gives a different error.
[Here](https://gist.github.com/siddharth2010/2b0486188b6677a7b9d568fdd9349780) is the error log.

**Comment by macgills** [comment]
Compilation is failing due to generated files, hoooo boy.
What JDK/JREs do you have installed?

**Comment by siddharth2010** [comment]
I am using the embedded android studio one. also I have JDK 8 and JDK 12 installed. However, my JAVA_HOME points to the JDK 12.

**Comment by macgills** [comment]
That is the problem. Point it at 8 I'd say. You have a [few options](https://stackoverflow.com/questions/18487406/how-do-i-tell-gradle-to-use-specific-jdk-version) but I think setting JAVA_HOME is easiest? Don't know how that will affect other dev work you perform

**Comment by siddharth2010** [comment]
Yeah!! That fixed it!
Thanks Seán!

**Comment by macgills** [comment]
Closing issue, happy days
