### ISSUE TITLE
Automatically pause download if WiFi is lost

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#135]
If a user starts a download and then WiFi is lost we should pause the download until WiFi reconnects possibly notifying the user.

**Comment by kelson42** [comment]
We have basically two options for the download:
* Wifi only
* Mobile data + Wifi

Then there is the workflow:
* Global configuration
* Ask each time of Wifi -> mobile data switch

I propose to add a configuration item to choose between the two options and if "Wifi only" is chosen (per default) AND we have an opportunity to switch (ongoing download and moving to mobile data) then invite the user (via notification) to change the behaviour. This  should work as a tip, so displayed only one time then not anymore.

@borisfba Would be great if you could have a look to this enhancement. Maybe you have ever a better approach to solve it?

**Comment by mhutti1** [comment]
#140
