### ISSUE TITLE
Search should be available from new tab menu

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#1350]
It should be possible to search from the new tab menu and the search to open in a new tab.

**Comment by geekRishabhjain** [comment]
Ya, I also found creating a new opens up completely blank. I found this not looking good. BTW, Hi, the community I am new to kiwix-android. Found this app useful and felt like contributing.

**Comment by mhutti1** [comment]
![Screenshot_1576541827](https://user-images.githubusercontent.com/2286937/70953830-a7a95e00-2062-11ea-9509-f9c00749ef27.png)

**Comment by mhutti1** [comment]
A search icon should be added to the bar to allow users to search into a new tab.

**Comment by mohamedsamehkhalil** [comment]
I would like to work on this issue

**Comment by mohamedsamehkhalil** [comment]
![Screenshot_20200226-070436_Kiwix](https://user-images.githubusercontent.com/34913464/75313873-d9ab1d80-5866-11ea-8e2c-0af6f837193b.jpg)
![Screenshot_20200226-070659_Kiwix](https://user-images.githubusercontent.com/34913464/75313863-d0ba4c00-5866-11ea-8039-22b0269bf995.jpg)
I also noticed we could reach a state were in the search icon is completely invisible
# steps to reproduce
Open a new tab then press on the tabs button then choose any tab(could be the same tab again). The chosen tab will not have a search icon

**Comment by kelson42** [comment]
@mohamedsamehkhalil I have assigned the ticket to you.

**Comment by mohamedsamehkhalil** [comment]
```
activity.intent<SearchActivity> {
        putExtra(EXTRA_ZIM_FILE, zimFileReader.zimFile.absolutePath)
      }
```
@mhutti1 The search that is currently implemented takes in a Zim file to search in. Do you expect the search from a new tab to look into all files or just one specific file ?

**Comment by kelson42** [comment]
@mohamedsamehkhalil This should work for the current ZIM open.

**Comment by mohamedsamehkhalil** [comment]
@kelson42 so just to be sure I understand the issue correctly. The screen that appears when I press on the tab switcher button and view all tabs, this is where I should add the search button, correct ?

**Comment by 4shutosh** [comment]
Yes @mohamedsamehkhalil 
We should be able to search from this screen
I think adding a search button in this bar will work fine.
![Webp net-resizeimage (1)](https://user-images.githubusercontent.com/53831987/75622779-101bcc00-5bca-11ea-81e2-e6c8c477479f.png)

**Comment by mohamedsamehkhalil** [comment]
@mhutti1 @kelson42 I finished working on a working solution for the issue but the commit hooks fail with this message when I try to commit. Any help ?
in the first file in the error I added a method to an interface that had 10 methods already
in the second file I just added 2 new methods to the class
![image](https://user-images.githubusercontent.com/34913464/75819747-d9011280-5da3-11ea-86d4-2cb9bf225984.png)

**Comment by mhutti1** [comment]
I imagine this means you have too many functions in the classes it specifies? I imagine you should move some out into a seperate class?

**Comment by mohamedsamehkhalil** [comment]
@mhutti1 I solved the detekt problem thanks to help from macgills and was able to push my solution correctly. please review my pull request #1859 and inform me of your edits or requests.
