### ISSUE TITLE
Refactor LocalFileTransfer: Use Coroutines instead of AsyncTasks

### ISSUE THREAD

**Issue by Aditya-Sood** [kiwix/kiwix-android#1351]
- [feature/LocalFileTransfer](https://github.com/kiwix/kiwix-android/tree/feature/LocalFileTransfer) currently uses async-tasks for transferring files, metadata exchange, etc.
- Aim of this ticket is to replace said async-tasks and use rx instead
- <s>I'll be working on this ticket once #1276 has been merged</s>

**Comment by kelson42** [comment]
@Aditya-Sood Which kind a problem (from a user perspective) this ticket should fix?

**Comment by macgills** [comment]
Aditya would have had to learn Rx which was mildly out of scope for the original ticket so we decided to not spend the time there but make a ticket to improve it. From a user perspective there should be zero impact. From a code perspective way nicer.

**Comment by gouri-panda** [comment]
@macgills if @Aditya-Sood  is not working can I take this issue?

**Comment by macgills** [comment]
@gouri-panda assigned

**Comment by macgills** [comment]
It may be noted that coroutines are also a much more valid option here than they were when this ticket was first made. The API stabilised a lot and they have been overwhelming embraced by the jetpack team

**Comment by gouri-panda** [comment]
@macgills I'm also favored with Coroutine.Should i make another ticket for this?

**Comment by macgills** [comment]
Nah you good, ticket was always about coroutines 👀

**Comment by gouri-panda** [comment]
@macgills How about kotlin?

**Comment by macgills** [comment]
Kotlin is non negotiable, coroutines + java is not possible

**Comment by gouri-panda** [comment]
Should I make another ticket for converting to kotlin?

**Comment by macgills** [comment]
It is discrete enough that it can just be done as part of this ticket, the activity is already in kotlin
