### ISSUE TITLE
Search order of articles involving spaces

### ISSUE THREAD

**Issue by ciconi** [kiwix/kiwix-android#1354]
**Describe the bug**
When searching for articles with one or more space characters, sorting fails:
1. Sort order is broken, articles belonging together are listed apart:
Enter: "The Wolf of " (including one space)
```
The Wolf of Debt
The Wolf of the Sila
The Wolf of Zhongshan
Age of the Wolf
(... lots of other articles containing the words in another order)
The Wolf of Wall Street (book) 
(... other articles)
The Wolf of Wall Street (2013 film)
Hour of the Wolf (disambiguation)
The Wolf of Wall Street (1929 film)
(...)
```
2. Articles are not shown
Enter: "Gone " (including one space)
"Gone with the Wind" is not shown. 
This is probably because the list is too long, to show it completely. If you enter: "Gone with", "Gone with the Wind" appears. So probably this will work after fixing problem above. 

**Expected behavior**
If the user enters a space after a word, the list should first list all articles including the words and the space in this order and then continue to list other combinations:
```
The Wolf of Debt
The Wolf of the Sila
The Wolf of Wall Street (1929 film)
The Wolf of Wall Street (2013 film)
The Wolf of Wall Street (book) 
The Wolf of Zhongshan
Age of the Wolf
```

**Steps to reproduce the behavior:**
1. Use english wikipedia
2. Click Search Symbol
3. Enter: "The Wolf of " (including one space)
4. Check the list
-->

**Screenshots**
![kiwix_sorting](https://user-images.githubusercontent.com/31411407/62858937-1022b000-bcfc-11e9-8e6f-989aa0eba650.png)

**Environment**
- Version of Kiwix Android : 2.5.1
- Device : Samsung S9
- OS version : 8.1.0

**Comment by geekRishabhjain** [comment]
I would want to work upon it. I am a student and that too new to the project, so any resources or tips will be a great help.

**Comment by kelson42** [comment]
@geekRishabhjain The whole is handled deep in a C++ library. I would not start here. But feel free to pick an issue with the tag " good first issue".

**Comment by geekRishabhjain** [comment]
@kelson42 I thought this is something as easy, just rearranging of objects types. I'll look at some issues in "good first issue". Thanks.

**Comment by kelson42** [comment]
@mgautierfr Tested with a recent ZIM file and kiwix-serve and still not working fine "the wolf of " search pattern does not return "The wolf of Wall street"... it seems that the suggestions don't prioritize if the words are put in the right order. Is that normal?

**Comment by macgills** [comment]
@kelson42 should this ticket be on this repo? Is the android client the only one experiencing this issue?

**Comment by macgills** [comment]
@kelson42 @mgautierfr Is the expectation on this ticket that the client will enforce some ordering of search results or that this ordering is to be handled in kiwixlib?
I can iterate the list, splitting the search term/result on ` ` and iterate through both calculating the number of sequential word matches and then ordering the list based on these matches.

**Comment by kelson42** [comment]
@macgills We should try to reproduce that bug wit kiwix-search binar an the move it to kiwix-tools repo. If reproducible.

**Comment by macgills** [comment]
there is a kiwix-search artifact?

**Comment by kelson42** [comment]
@macgills Command line tool in kiwix-tools

**Comment by macgills** [comment]
@kelson42 will I try to reproduce it with `kiwix-search`? I imagine I am not very well set up for it but I can invest the time

**Comment by kelson42** [comment]
@macgills I will do that if you prefer you can put that aside.

**Comment by kelson42** [comment]
Still wrong :(
```
$ kiwix-search --suggestion wikipedia_en_all_nopic_2019-12.zim "The Wolf of "
Teen Wolf 3: The Return of The Wolf
The Mouth of the Wolf
The House of the Wolfings
The Cry of the Wolf
The Year of the Wolf
The Wolf of the Sila
The Skin of the Wolf
The House of the Wolf
The Hour of the Wolf
The Mystery of the Wolf
```
