### ISSUE TITLE
Add main Kiwix banner inside the scrollable region

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#1355]
**Is your feature request related to a problem? Please describe.**
Making the banner scrollable would add extra space for displaying the zim files.

**Describe the solution you'd like**

Just add the main banner inside the scroll view (along with the recycler view).

**Comment by rajput2122** [comment]
I want to work on this issue. Can you please elaborate more?

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/63783496-08126500-c8e5-11e9-910f-40deed40d00f.png)
this is the banner with list.
![image](https://user-images.githubusercontent.com/3358282/63783562-1f515280-c8e5-11e9-95a2-05bdfc89f2dc.png)
this is after partially scrolling the list.
This ticket is about making the banner scroll too, I have my doubts if adding it to the Scrollview would work, it is more likely it would have to be added as an item in the recyclerview.
Let me verify if we want to pursue this functionality

**Comment by macgills** [comment]
@rajput2122 yes we do want to pursue this functionality! As per #798 that was decided.
I will assign the ticket to you

**Comment by rajput2122** [comment]
sir app is not building saying sdk path is not defined but i have already include sdk.Can you please guide me to build?

**Comment by macgills** [comment]
Can you show me a print screen or paste the log in here?

**Comment by rajput2122** [comment]
Sir, there is no android module appearing only project is showing
![12](https://user-images.githubusercontent.com/43101744/63944045-734b6b00-ca8e-11e9-9d2d-e40eb6510fa1.png)

**Comment by macgills** [comment]
Create a new empty project and see what problems that has. I assume clicking `sync project` and `Add Android module` have had no great affect?

**Comment by rajput2122** [comment]
All other projects are building with no issue.Even if I invalidate the cache and restarting this project the same issue appearing, again and again, .syncing this project with file system has no effect on this project. Sir is it necessary to download android ndk for this project?

**Comment by macgills** [comment]
It is not necessary. Can you clone the project to a new location and try opening that? Also what OS are you running?
I would also like to see the error messages, there must be something in `event log` or one of those windows

**Comment by siddharth2010** [comment]
> Sir, there is no android module appearing only project is showing

@rajput2122 , I had a similar problem a few days ago.
I tried cloning it a couple of times but with no success. However the problem was fixed when i did a fresh clone and then used the `import project` option instead of the 'open project' one.

![image](https://user-images.githubusercontent.com/32238400/63954881-73a13180-caa1-11e9-9b04-53c949423a2c.png)

**Comment by rajput2122** [comment]
> > Sir, there is no android module appearing only project is showing
> 
> @rajput2122 , I had a similar problem a few days ago.
> I tried cloning it a couple of times but with no success. However the problem was fixed when i did a fresh clone and then used the `import project` option instead of the `open project` one.
> 
> ![image](https://user-images.githubusercontent.com/32238400/63954881-73a13180-caa1-11e9-9b04-53c949423a2c.png)

Thanks, sir for help build is successful

**Comment by rajput2122** [comment]
After running app in my phonr after splash screen sending me to download the test content app from playstore but item not found error appear in playstore

**Comment by macgills** [comment]
The variant you should be using is `kiwixDebug`, from our readme
>We utilize different build variants (flavours) to build various different versions of our app. Ensure your build variant is kiwixDebug to build the standard app.

**Comment by rajput2122** [comment]
Sir i am not able to check it on my phone because get content or download book option is not showing anything to download even online , so there is no items in recyclerview to check the scrolling

**Comment by rajput2122** [comment]
Can you please help me sir.I want to fix this issue

**Comment by siddharth2010** [comment]
@rajput2122 , are you using the correct build variant?

**Comment by rajput2122** [comment]
i am using kiwixDebug

**Comment by rajput2122** [comment]
please help me sir?

**Comment by rajput2122** [comment]
I have done it sir but while commiting showing error that java home is not set .screenshot of issue solved
![Screenshot_20190902-033457_Kiwix](https://user-images.githubusercontent.com/43101744/64082994-c0049f80-cd35-11e9-91f5-cb81373264ed.jpg)
![Screenshot_20190902-033503_Kiwix](https://user-images.githubusercontent.com/43101744/64082995-c85cda80-cd35-11e9-9a11-4942dd7ec9fa.jpg)

**Comment by siddharth2010** [comment]
@rajput2122 , great job! You just need to install the Java JDK on your computer and set the JAVA_HOME Environment variable.
Here are the instructions to do it: https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html

**Comment by rajput2122** [comment]
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Static analysis found violations and attempted to autofix, please commit these autoformat changes
If the build failed for another reason please make sure JAVA_HOME is set to JDK8

should i have to restart the window ?

**Comment by siddharth2010** [comment]
Yeah you need to restart the terminal emulator on android studio...

Would be a good option to restart android studio itself

**Comment by rajput2122** [comment]
17:46	Commit failed with error
			0 files committed, 26 files failed to commit: Kiwix banner is now under scrollable region and All
			Running lint...
			
			> Configure project :app
			Configuring Kiwix
			Configuring customexample
			Configuring kiwix
			
			> Task :app:ktlintDebugSourceSetCheck NO-SOURCE
			> Task :app:ktlintKiwixDebugSourceSetCheck NO-SOURCE
			> Task :app:ktlintKiwixSourceSetCheck NO-SOURCE
			> Task :app:ktlintMainSourceSetCheck UP-TO-DATE
			> Task :app:ktlintKiwixDebugCheck UP-TO-DATE
			> Task :app:copyGitHooks UP-TO-DATE
			> Task :app:installGitHooks SKIPPED
			> Task :app:objectboxPrepareBuild
			> Task :app:preBuild
			> Task :app:preKiwixDebugBuild UP-TO-DATE
			> Task :app:compileKiwixDebugAidl NO-SOURCE
			> Task :app:checkKiwixDebugManifest UP-TO-DATE
			> Task :app:compileKiwixDebugRenderscript NO-SOURCE
			> Task :app:generateKiwixDebugBuildConfig UP-TO-DATE
			> Task :app:mainApkListPersistenceKiwixDebug UP-TO-DATE
			> Task :app:generateKiwixDebugResValues UP-TO-DATE
			> Task :app:generateKiwixDebugResources UP-TO-DATE
			> Task :app:createKiwixDebug... (show balloon)


while commiting this error occurs how to solve it?

**Comment by siddharth2010** [comment]
@macgills might be able to fix that.

**Comment by rajput2122** [comment]
Sir is there any public chat channel on gitter of kiwix/anroid?

**Comment by rajput2122** [comment]
I have opened a PR kindly review it @siddharth2010

**Comment by abdulwd** [comment]
@rajput2122 How did you commit even when the lint was failing?

**Comment by rajput2122** [comment]
Actually sir in lint there was error showing about srcCompact attribute for imageview . i resolved that then there was no any error in logcat and committed successfully

**Comment by rajput2122** [comment]
i also resolve issue #1150 in this pull requests as mentioned in that issue to change every .png to vector assets

**Comment by geekRishabhjain** [comment]
@siddharth2010 
> Here are the instructions to do it: https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html

The same error is also occurring in ubuntu, any references or links?
Further, I've worked on other android app projects too but JAVA_HOME error never occurred, is it something related to the version of JAVA the different projects use?

**Comment by macgills** [comment]
Have you built locally using `gradlew` before?
Before every commit we run a `hook` so that the quality of the code is verified and this requires the user to be set up to run gradle commands

**Comment by geekRishabhjain** [comment]
Actually I want to create a work in progress commit.
Whole work is complete but one line is causing bug, so.

**Comment by geekRishabhjain** [comment]
What should I really do? I want my code reviewed, I have previously mentioned it  [here](https://github.com/kiwix/kiwix-android/issues/547#issuecomment-527219321)

@kelson42 suggested me to create a PR with Work in progress head when I went to commit it, the error was shown. Seeing it first time.

**Comment by macgills** [comment]
comment out the line?

**Comment by geekRishabhjain** [comment]
I did it, committing is still showing me the same JAVA_HOME error, and gradlew is also not found.
What wrong am I doing here?

**Comment by geekRishabhjain** [comment]
`java --version` gives me 
```
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu219.04)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu219.04, mixed mode, sharing)
```

**Comment by macgills** [comment]
ignore committing for now, go to your kiwix-android folder and run `gradlew lintKiwixDebug`.

Then that is obviously wrong, your java home needs to be set to 8 and is 11
