### ISSUE TITLE
Custom app cannot find contents bug

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#1361]
**Describe the bug**

**Expected behavior**

**Steps to reproduce the behavior:**
1. Build a custom app e.g. `./gradlew installPhetDebug`
2. Start the custom app on the device. (Optionally copy across a ZIM file to the device.)
3. Wait for it to crash.

**Screenshots**

**Environment**
- Version of Kiwix Android : 2.5.x
- Device : HTC Desire 510
- OS version : 4.4.3

**Logs**
```
I/ActivityManager(  821): START u0 {cmp=org.kiwix.kiwixcustomphet/org.kiwix.kiwixmobile.main.MainActivity} from pid 29097
I/Intent  (  821): @test_code: getHtcIntentFlag: 0 obj: 1119804456
D/kiwix   (29097): Looking for '/storage/emulated/0/Android${File.separator}obb/org.kiwix.kiwixcustomphet/main.3.org.kiwix.kiwixcustomphet.obb' with size=0
D/kiwix   (29097): No file '/storage/emulated/0/Android${File.separator}obb/org.kiwix.kiwixcustomphet/main.3.org.kiwix.kiwixcustomphet.obb' found.
W/dalvikvm(29097): VFY: unable to resolve static method 3469: Landroid/text/Html;.fromHtml (Ljava/lang/String;I)Landroid/text/Spanned;
W/ActivityManager(  821): startActivity called from finishing ActivityRecord{42787878 u0 org.kiwix.kiwixcustomphet/org.kiwix.kiwixmobile.main.MainActivity t117 f}; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=org.kiwix.kiwixcustomphet/org.kiwix.kiwixmobile.main.MainActivity }

```

**Comment by macgills** [comment]
`'/storage/emulated/0/Android${File.separator}obb/` that is extremely odd it is not just rendering the fileSeparator

**Comment by macgills** [comment]
`"{File.separator}` yup, that 100% explains it FileUtils:40.
I'll fix it

**Comment by macgills** [comment]
It was the Lint auto fomat! Oh that is just evil

**Comment by julianharty** [comment]
You're racing ahead, just cos we went to lunch. I even had the fix pending :) Anyway, thanks for fixing this. I also added an extra debug log statement which I'll add since creating custom apps has been a bit of a challenge trying to learn how the custom app actually gets configured with the file size, etc.
