### ISSUE TITLE
Remove unnecessary work from Custom Apps

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#1369]
**Describe the bug**
The current codebase for custom apps is shared with the main Kiwix app. Several methods are called in custom apps that are not necessary and may cause poor performance and other bugs.

**Expected behavior**
The custom app only initialises and performs necessary work. (And reciprocally, the main app does not need to perform work (or ideally include code) that's specific to custom apps).

**Environment**
- Version of Kiwix Android : 2.5.x
- Device : N/A
- OS version : N/A

**Comment by julianharty** [comment]
Specific example: The call to `searchFiles();` in `OnCreate()` is not needed AFAIK in custom apps.

**Comment by julianharty** [comment]
Please add other examples as we discover them :)

**Comment by kelson42** [comment]
@julianharty The core of Kiwix Android is currently being reorganised to better isolate Kiwix core Android App from Kiwix Custom app specific code. If after this work is finished by @macgills (should happen sometime next week) and if you still identify a specific piece of code which suffer of the weakness you describe here, please open a ticket: one ticket per problematic piece of code.
