### ISSUE TITLE
PHeT index does not render in Kiwix Android 2.5 on some devices

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#1374]
**Describe the bug**
In the Android Log chromium reports a problem when loading index.html for the PhET ZIMs when Kiwix 2.5.x (or a custom app built using the same codebase) loads the PHeT content.

**Expected behavior**
The PhET homepage (a vertical list of images of each of the simulations) should appear in the main contents area (the WebView). The problem does not appear in the custom app available in the App Store (the 2.4 codebase). 

@mhutti1 has a suspicion the problem is related to injecting the bottom menu bar on devices with smaller screens. 

**Steps to reproduce the behavior:**
Use either the shipping version of the PhET ZIM or a more recent one, try opening it in the app.

**Screenshots**
<img width="385" alt="Screen Shot 2019-08-14 at 21 23 10" src="https://user-images.githubusercontent.com/785891/63053488-c2fc3500-bed9-11e9-9697-ce05b8e18734.png">
This is from an AVD created as a Nexus 5 running Android KitKat (4.4) from the Kiwix app built from the head of the `develop` branch.

**Environment**
- Version of Kiwix Android : 2.5.x 
- Device :  HTC Desire 510 or an AVD as above
- OS version : KitKat

PhET files include
https://download.kiwix.org/zim/phet/phet_mul_2019-06.zim
and the current app's embedded file which I can share with whoever's interested (or you can extract it once you've got the current PhET app installed).

**Logs**
Here's an extract of the message reported by chromium in both the emulator and the device's log file.

```
I/chromium( 4364): [INFO:CONSOLE(7)] "Viewport target-densitydpi is not supported.", source: content://org.kiwix.kiwixmobile.zim.base/A/index.html (7)
```

BTW there's a second message from chromium, in case it's somehow related...
```
I/chromium( 4364): [INFO:CONSOLE(1022)] "Uncaught ReferenceError: WeakMap is not defined", source: content://org.kiwix.kiwixmobile.zim.base/-/dist.js (1022)
```
If you wish I can raise a separate issue for this. I'm not aware of the impact at this stage.

See also: #1181

**Comment by julianharty** [comment]
PS: The strange colours might be related to the following message I see in the android logs for these devices:
`W/AwContents( 5645): nativeOnDraw failed; clearing to background color.`

**Comment by mhutti1** [comment]
I couldn't find any files in the ZIM file you shared with me. I can see the issue with English phet though so am debugging that.

**Comment by mhutti1** [comment]
It seems to be working fine sometimes on my Galaxy S8 but never not on my API 16 Emulator.

**Comment by mhutti1** [comment]
Last update of the Night:
2.4 can load the 2018 Phet Zim but not the 2019 Phet Zim on API 16
2.5 can't load either correctly on API 16

2019 Loads in API 28 in 2.5

This seems like very specific javascript features are being used and swapped out.

**Comment by julianharty** [comment]
Some diagnostic tests:
- LG4 running Android 6.0.1 running app version 2018-09 Build 182520 displays the main menu of PhET. The bottom bar (with the various buttons) renders acceptably and the buttons seem to work correctly.

**Comment by julianharty** [comment]
- The same LG4 with the latest build of the PhET app (2.5.2) Version 2019-06 Build: 35000004 and the most recent PhET file (from download.kiwix.org 2019-06, as above) also displays the main menu of PhET

**Comment by julianharty** [comment]
The problems may be wider, I noticed a PhET simulation did not load, and then the homepage failed to load twice before loading the third time. There are several lzma errors reported in the LG4_601_logcat_failed_to_load_BalancingAct_sim.txt logcat file. The second attachment is for the failure to load the homepage twice before it then worked.

[LG4_601_logcat_failed_to_load_homepage_twice_then_worked.txt](https://github.com/kiwix/kiwix-android/files/3505513/LG4_601_logcat_failed_to_load_homepage_twice_then_worked.txt)
[LG4_601_logcat_failed_to_load_BalancingAct_sim.txt](https://github.com/kiwix/kiwix-android/files/3505514/LG4_601_logcat_failed_to_load_BalancingAct_sim.txt)

**Comment by kelson42** [comment]
@julianharty I have published the a new version of the Phet app in closed alpha. https://play.google.com/apps/testing/org.kiwix.kiwixcustomphet to secure you are alpha tester. Please tell me if this problem still occur.

**Comment by kelson42** [comment]
No feedback. I close the ticket assuming this has been fixed. Please reopen if not.
