### ISSUE TITLE
Unable to delete old zim files after re-install

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1376]
Here is the reported use case: 

- User loses his phone. Gets a new one (Huawei 8X Max / android version 8.1.0) and re-downloads Kiwix and zim files.
- Older zim files cannot be removed
- Uninstalling / reinstalling Kiwix (2.5.2) does not change anything (see below images 1-3)

![Screenshot_20190813-223221](https://user-images.githubusercontent.com/21675885/63078599-4f3f4400-bf3c-11e9-9770-f5c5c381e594.jpg)
![Screenshot_20190813-223236](https://user-images.githubusercontent.com/21675885/63078600-4f3f4400-bf3c-11e9-89fc-338b8782b982.jpg)
![Screenshot_20190813-223357](https://user-images.githubusercontent.com/21675885/63078602-4f3f4400-bf3c-11e9-833e-ddce08ffdb54.jpg)

- Can't download new files either:
![Screenshot_20190813-223319](https://user-images.githubusercontent.com/21675885/63078601-4f3f4400-bf3c-11e9-90bd-17ae97cf0386.jpg)

**Comment by macgills** [comment]
I have opened up a PR that I believe addresses the root cause.

**Comment by Popolechien** [comment]
User reports that the issue is still there with 2.5.3. Should I reopen the issue and/or ask for more info?

**Comment by macgills** [comment]
No, the fix is for 3.0, 2.5.3 was a very minor update
