### ISSUE TITLE
White text for notes on Android 4.4

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#1379]
**Describe the bug**
The text appears to be in white on a white background on an older Android release (4.4). The text can be edited, highlighted, and edited. It can also be saved. It *is* visible in night mode on Android 4.4 devices. The issue occurs on a real device (HTC Desire 510) and in an AVD (with a Nexus 5 skin and Android 4.4 with Google APIs).

*** See also ***
In #792 there seems to be a similar issue but inverted with white on white in night mode rather than normal (day) mode.

**Expected behavior**
The text should be clearly visible and a high contrast compared to the background colour. (we should aim to meet or exceed the Accessibility guidelines for colour contrast, see https://support.google.com/accessibility/android/answer/7158390?hl=en for guidance and ways to check).

**Steps to reproduce the behavior:**
1. Install the app
2. Load a ZIM 
3. Use the Add a note menu option
4. Type away, try selecting the text, copying + pasting, etc. Save the note (or exit) otherwise you cannot go to the app's settings options...
5. In the app settings, switch to night mode (in settings) and compare the visibility of the text.

**Screenshots**
<img width="409" alt="Screen Shot 2019-08-14 at 19 06 59" src="https://user-images.githubusercontent.com/785891/63097937-9bed4400-bf69-11e9-8108-2d0d1c95a8fa.png">
<img width="409" alt="Screen Shot 2019-08-14 at 19 13 30" src="https://user-images.githubusercontent.com/785891/63097939-9c85da80-bf69-11e9-831e-3e4b87aadac3.png">
<img width="399" alt="Screen Shot 2019-08-14 at 19 37 19" src="https://user-images.githubusercontent.com/785891/63097940-9c85da80-bf69-11e9-8f89-0ed934fcb2b3.png">

**Environment**
- Version of Kiwix Android : 2.5.2 (head of develop branch)
- Device : HTC Desire 510; AVD running KitKat.
- OS version : KitKat

**Comment by julianharty** [comment]
Notes: I've tested the functionality on Android 6.0.1 and the text is visible. Additional testing on Android 5.0 and perhaps Android 5.1 may help hone in on the extent of the issue.

**Comment by macgills** [comment]
`android:textAppearance="@style/TextAppearance.MaterialComponents.Body1"`
probably aligning the style of the editext is all we need to do if our other text is the correct color.
Probably many issues like this will be solved by #1301

**Comment by mhutti1** [comment]
Yes I have seen a lot of these bugs recently.

**Comment by Aditya-Sood** [comment]
I checked this on my device (moto g5s+, oreo), seems to be working. (I had only checked on this device during development as well)
Is this a backward compatibility issue?

**Comment by macgills** [comment]
Yes, compatibility themes are all over the place and you often have to define various styles for api levels, you place a resource in `styles-v{android api number}` and it will use it on that version and below (more info [here](https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources)) but I think it is pretty unreasonable to manually test your change across 10 devices or however many SDKs we support. I think we just have to subsist on error reports like this.
The alternative in previous companies was that a qa team during the validation of a release would smoke test each version of the app, even then it was a lengthy process for 2 people to do 5 SDKs.
The other solution is a suite of automated tests that take screenshots and that also requires manual validation

**Comment by macgills** [comment]
I will close this ticket, the full overhaul of styles to support night mode will render this obsolete
