### ISSUE TITLE
Cleanup Menu

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#1383]
There are currently too many items in the menu. I propose:

1. Remove Home, find in page and new tab as their functions are available elsewhere. 
2. Move Clear all Notes to settings.
3. Rename Add Note to Notes
4. Reorder the Items in order of expected use.

**Comment by mhutti1** [comment]
Also the question of where Get Content should point to and if it should be renamed.

**Comment by kelson42** [comment]
> Also the question of where Get Content should point to and if it should be renamed.

It should be renamed in "Library"

**Comment by Aditya-Sood** [comment]
@mhutti1 I think 'Notes' will be confusing, since right now the user can view/edit only the note associated with the currently open article
Maybe we leave it as is for now? Otherwise an alternative name could be 'Article note'

**Comment by mhutti1** [comment]
I think Notes is fine.

**Comment by macgills** [comment]
If we call it notes my expectation when I click on it that I would see a list of all notes for the current zim file, clicking on these notes would open them and maybe also some buttons to share/delete a note or navigate to the article where I made the note, basically a bookmark with associated text.

**Comment by mhutti1** [comment]
@macgills I think that that is out of the scope of this issue though. Maybe we can call it Note?

**Comment by macgills** [comment]
Yeah completely out of scope.
"Note" or "Article Note" are A OK with me

**Comment by mhutti1** [comment]
This is more difficult that I thought. We need storage permissions to clear notes and we don't currently have a way of getting these from settings.

**Comment by macgills** [comment]
We really need to make a PermissionRequester class to ease the pain of requests

**Comment by Aditya-Sood** [comment]
@mhutti1 for now we could shift it to the add-note fragment itself, as an option that is always displayed in an overflow menu (so that the user is aware that it 'clear(s) all notes')

**Comment by macgills** [comment]
The app barely functions without access to storage permissions as is and a user would have had to have granted the permission to want to delete notes they had created in the first place.
I could be fine with following the example of historyClear
```
    private void clearAllHistoryDialog() {
      int warningResId;
      if (sharedPreferenceUtil.nightMode()) {
        warningResId = R.drawable.ic_warning_white;
      } else {
        warningResId = R.drawable.ic_warning_black;
      }
      new AlertDialog.Builder(getActivity(), dialogStyle())
          .setTitle(getResources().getString(R.string.clear_all_history_dialog_title))
          .setMessage(getResources().getString(R.string.clear_recent_and_tabs_history_dialog))
          .setPositiveButton(android.R.string.yes, (dialog, which) -> {
            presenter.clearHistory();
            allHistoryCleared = true;
            Toast.makeText(getActivity(),
                getResources().getString(R.string.all_history_cleared_toast), Toast.LENGTH_SHORT)
                .show();
          })
          .setNegativeButton(android.R.string.no, (dialog, which) -> {
            // do nothing
          })
          .setIcon(warningResId)
          .show();
    }
```
but throw a `ContextCompat.checkSelfPermission` in there and show a toast saying we can't delete without storage permission. Flag it for updating with a real permission requesting component in 3.1.

**Comment by macgills** [comment]
@mhutti1 have you been working on this? I assume you have but it hasn't been explicitly stated, could you assign yourself?

**Comment by mhutti1** [comment]
I haven't been looking at it actually recently. I have been a bit busy :(.

**Comment by macgills** [comment]
Fair enough, I may take it over as I assess tickets today or anyone else can take it if they manage to swoop in
