### ISSUE TITLE
Faulty snake cases in strings.xml

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1386]
**Describe the bug**
There are tons of faulty snake cases in the `strings.xml` that need to be fixed. For example:
 `<string name="error_nozimfilesfound">` 

**Expected behavior**
Should be `error_no_zim_files_found` . Similarly, all faulty snake cases should be fixed in `strings.xml`.

**Comment by jhbiggs** [comment]
I updated the strings, but somehow can't commit anything to the branch I created.  Error message shows
 * What went wrong:
Task 'ktlintKiwixDebugCheck' not found in project ':app'.
Any suggestions are welcome.

**Comment by kelson42** [comment]
@macgills Might you be able to help @jhbiggs? Does this has to do with the new git hooks?

**Comment by macgills** [comment]
It does, but if @jhbiggs branched off of any recent develop commit then `ktLint` task should be available. Worst case go to `.git/hooks` in the project and delete `pe-commit`

**Comment by kelson42** [comment]
@macgills Does all what is needed to @jhbiggs to commit properly is explained in the CONTRIBUTING.md file? It seems I don't and he doesn't understand the problem.

**Comment by macgills** [comment]
@kelson42 it shouldn't really need explaining, this only happened because jhbiggs was on a branch that did the automatic install/format that relies on a dependency and then they switched to an older branch that did not have it. Any branch off of develop will now have it.
The problem is that git hooks are not strictly in version control and must be installed, I have piggybacked on a gradle command to install it

**Comment by macgills** [comment]
@jhbiggs please revert your changes. To begin development of a new feature a branch should occur off of develop and not master. The history on the branch is very odd, please review [contributing guidelines](https://github.com/kiwix/kiwix-android/blob/develop/CONTRIBUTING.md)

**Comment by rajput2122** [comment]
Is this issue closed?

**Comment by macgills** [comment]
@rajput2122 no, jhbiggs is working on it at the moment
