### ISSUE TITLE
Use new tagging system

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-android#1407]
In order to support the [new tagging system](https://wiki.openzim.org/wiki/Tags), please make sure your reader:

* is feeding itself from the OPDS stream (using a local cache/copy or not) #1203
* is using the [centralized Categories List](https://github.com/kiwix/kiwix-tools/issues/317) #500 
* <s>is using the lastest libkiwix (not released ATM). It supports new options and includes the backward-ompatibility bits you'd need.</s> done
* <s>is using the new tags only for flavours and full-text index.</s> See task #1574

**NOTE**: This issue for planning purposes, OPDS and libkiwix **does not support** those features at the moment.

**Comment by kelson42** [comment]
Closing in favour of other dedicated tickets. See description.
