### ISSUE TITLE
Test Custom App not getting Started

### ISSUE THREAD

**Issue by geekRishabhjain** [kiwix/kiwix-android#1409]
**Describe the bug**
Test Custom App won't start. Keep on asking for Go to play store. Leak detected.

**Expected behavior**

The app should run fine when done build and run on android studio.

**Steps to reproduce the behavior:**
I got this code cloned, ran it in android studio and tried to run the app on my android phone.
Running the app instead of installing kiwix installs two apps test custom app and an app called leaks. When I try to run the test custom app it says to go to play store, play store displays not found. A notification is sent to me than from the leaks app, dumping heap, the app may crash, brrr...

**Environment**
- Device : Android Samsung J7

New to kiwix, trying to set it up in my mobile and was unable to do so.

**Comment by iadeelzafar** [comment]
Hi Rishabh, can you please confirm that you're using the correct **BUILD VARIANT**. You have to select **`kiwixDebug`**.
There's a left pane in android studio where you'll see `Build Variants`. There you can select the correct one.

**Comment by geekRishabhjain** [comment]
@iadeelzafar thanks, its working fine now.
