### ISSUE TITLE
After deleting zim files (e.g. de_11_2018), the content page is still showing the old content.

### ISSUE THREAD

**Issue by Wikinaut** [kiwix/kiwix-android#1415]
**Describe the bug**

I upgraded my wikipedia_de_novid from 2018-11 to 2019-08.
Then I deleted all(!) old 2018-11 files on my SD card.

Even after having

* stopped Kiwix App
* cleared the Kiwix app cache

the both content versions were still shown in the Content page.

Then I deinstalled and re-installed the Kiwix app. Now, the content page is showing the only correct content file.

**Environment**
- Version of Kiwix Android : 2.5.3 build 220503
- Device : HUAWEI smart 2019
- OS version : Android 9

**Logs**

**Comment by kelson42** [comment]
Might be a duplicate of #1126.

**Comment by Wikinaut** [comment]
duplicate of #1126 .
