### ISSUE TITLE
Search button not working

### ISSUE THREAD

**Issue by geekRishabhjain** [kiwix/kiwix-android#1419]
**Describe the bug**

**Expected behavior**

**Steps to reproduce the behavior:**
1. Run the latest code.
2. Click on the search icon.
3. Nothing happens

**Environment**
- Version of Kiwix Android : 2.5.1 
- Device : Samsung J7
- OS version : 9

**Comment by abdulwd** [comment]
Have you opened any zim file before searching?

**Comment by geekRishabhjain** [comment]
> Have you opened any zim file before searching?
In that case this turns into a UI problem.
I think we need to tell users that the search button is for zim files and not for online search. Users(as Me) can get deluded into believing it as latter (more intutive). We can either hide it when no zim file is previously accessed, as was the case with me, or it should be made to search online too.

**Comment by abdulwd** [comment]
Hide it.

**Comment by geekRishabhjain** [comment]
Yes, Yes I will.

**Comment by abdulwd** [comment]
Closed via #1461.
