### ISSUE TITLE
Select all files with a single click in ZimHostActivity

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1420]
**Is your feature request related to a problem? Please describe.**

There should be a way for the user to select all ZIM files with a single click in ZimHostActivity.

**Describe the solution you'd like**

A button to select all ZIM files. This will make it easier for the user to select all files with a single click that he/she wants to host on the server.

**Comment by macgills** [comment]
The default behaviour is that all books are selected automatically, I wonder if we do still want a "Select All" checkbox or somesuch view

**Comment by gouri-panda** [comment]
> The default behaviour is that all books are selected automatically, I wonder if we do still want a "Select All" checkbox or somesuch view

@macgills What if the User has more than 10 books and the user wants to host one book It will become tedious to unselect it.

**Comment by macgills** [comment]
fair, so yes this ticket is valid

**Comment by gouri-panda** [comment]
ok, then I'm taking this.

**Comment by gouri-panda** [comment]
@macgills after doing some research on this issue I think this issue is irrelevant. Why a user wants to select a subset books? Plus the design will look like a bit of odd.
Ping @kelson42 for input.

**Comment by gouri-panda** [comment]
@macgills What should we do with this PR?

**Comment by macgills** [comment]
I am happy to close as I am content with the current functionality
