### ISSUE TITLE
Add java 8 dependency in the Readme

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#1422]
We should add the instructions to install JAVA 8 and setting up the JAVA_HOME environment variable in the readme in the Build section.
This will be very helpful for new comers, who are not familiar with the commit githooks and are stuck with the commit failing..

**Comment by siddharth2010** [comment]
@macgills , do you think we should do this.
IMO this would be very helpful cause most newcomers that i know just use the JDK bootstrapped with android studio and dont have the JDK installed on their computers

**Comment by macgills** [comment]
```
#!/bin/sh

echo "Running lint..."

./gradlew app:ktlintKiwixDebugCheck app:lintKiwixDebug --daemon

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    exit 0
else
    ./gradlew app:ktlintKiwixDebugFormat --daemon
    echo 1>&2 "Static analysis found violations and attempted to autofix, please commit these autoformat changes"
    echo "If the build failed for another reason please make sure JAVA_HOME is set to JDK8"
    exit 1
fi
```

We present an error message at the appropriate time. I don't think adding an additional thing that people won't read is of massive use or - more accurately - is equally useful

**Comment by siddharth2010** [comment]
Yeah, I guess you are right..
