### ISSUE TITLE
Turning off hotspot manually doesn't updates layout

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1423]
**Describe the bug**
Turning off hotspot manually doesn't updates layout. (on devices < Oreo)

**Expected behavior**
If server was started, and user turned off hotspot manually, then the layout should be updated. And the foreground notification should be dismissed.

**Steps to reproduce the behavior:**
1. Start server in `ZimHostActivity`
2. Turn off hotspot manually
3. Go back to `ZimHostActivity`
4. Layout not updated

**Comment by macgills** [comment]
#1506 fixed here
