### ISSUE TITLE
Remove/hide books from list which are not hosted in ZimHostActivity

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1424]
**Describe the feature you'd like**
In `ZimHostActivity`, after the user pressed the start server button the books which are not hosted should either be grayed out or hidden from the list of hosted books.

**Comment by macgills** [comment]
Deleted you mean?

**Comment by iadeelzafar** [comment]
@macgills Hidden as long as the server is running. Once server is stopped, they should re-appear.

**Comment by macgills** [comment]
ZimFileSelectFragment should not allow books to be deleted while they are being hosted by the HotspotService.
I think we still want a user to be able to read them locally while they are being hosted

**Comment by abdulwd** [comment]
No no, the goal of this ticket is to let users know which ZIMs are hosted on the server. So after user presses the start server button the books which are **NOT** hosted should either be grayed out or hidden from the list of hosted books in ZimHostActivity.

**Comment by macgills** [comment]
Sorry yes, ZimHostActivity, my mind kept putting in `ZimManageActivity` for some reason.

**Comment by kelson42** [comment]
@MohitMaliDeveloper Dullicate of #2537
