### ISSUE TITLE
KiwixSettingsActivtyTests Disabled

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1428]
**Type of Test**

* [ ] Unit Test
* [x] UI Test

**Particular area and files to be tested**
KiwixSettingsActivityTest was disabled because the old tests were causing the build to hang, these tests should be rewritten in kotlin and with a PageObject

**Current Status of the tests**
Ignored

**Particular Behaviour to be tested**
Click on every preference and dialog

**Comment by kelson42** [comment]
@macgills Do you think this is a good time now to reintroduce it?

**Comment by macgills** [comment]
Yes, I will experiment on my Github actions branch

**Comment by macgills** [comment]
Tests have been reintroduced but not as a PageObject, we can probably leave this ticket and just repurpose it to `good first issue` for somebody to convert the automated test to kotlin/pageObject

**Comment by kelson42** [comment]
@macgills Good. Please open a new ticket with that specific task, without any milestone. We could then close that one.
