### ISSUE TITLE
Standardise Copyright across project using Copyright Plugin

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1429]
**Is your feature request related to a problem? Please describe.**
Copyrights are inconsistently placed, missing or have varying contents.

**Describe the solution you'd like**
Using the [plugin](https://www.jetbrains.com/help/idea/copyright.html) bundled with android studio we should commit this configuration to git and apply it to the project

**Comment by jhbiggs** [comment]
After looking again at the issue needs, I will look further into committing the configuration to git.

**Comment by jhbiggs** [comment]
Ok, would I add the following to the .git/config file?  Below is just a guess.  I haven't found much information online about committing copyright information to local git config.  

[copyright]
	text = "/** Kiwix Android\nCopyright (c) 2019 Kiwix <android.kiwix.org>\n * This program is free software: you can redistribute it and/or modify\n* it under the terms of the GNU General Public License as published by\n* the Free Software Foundation, either version 3 of the License, or\n* (at your option) any later version.\n*\n* This program is distributed in the hope that it will be useful,\n* but WITHOUT ANY WARRANTY; without even the implied warranty of\n* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n* GNU General Public License for more details.\n*\n* You should have received a copy of the GNU General Public License\n* along with this program. If not, see <http://www.gnu.org/licenses/>.\n*\n*/"
