### ISSUE TITLE
Revert build.gradle.kts to build.gradle

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1431]
**Is your feature request related to a problem? Please describe.**
Android Studio shows a warning that it does not support build.gradle.kts files

**Describe the solution you'd like**
Revert the file back to groovy

**Describe alternatives you've considered**
Wait until build.gradle is supported

**Additional context**
We can additionally move our versions/libs to a `buildSrc` folder and have that be in kotlin, theoretically this could even be autogenerated by the `buildSrcVersions` plugin

**Comment by kelson42** [comment]
@macgills Reading #947, I thought we were still using groovy!

**Comment by macgills** [comment]
We have a mix right now, the project `build.gradle` was converted to `build.gradle.kts` but the app level `build.gradle` is still in groovy

**Comment by macgills** [comment]
.kts files will be supported fully in Android Studio 4.0 (currently available in Canary channel only) so I will close this
