### ISSUE TITLE
Hotspot stops when going back to MainActivity (>=O)

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1432]
**Describe the bug**
Hotspot stops when going back to MainActivity (on devices>=O). 

First, I suspected this might be happening when `ZimHostActivity` is destroyed. But that's not the case. If you turn on hotspot and destroy the app from the background, hotspot won't stop.
I've reproduced this bug only after going back to `MainActivity`.

_P.S: This bug can be reproduced 1/4th of the times._

**Expected behavior**
Hotspot shouldn't stop

**Steps to reproduce the behavior:**
1. Go to `ZimHostActivity`, and start server.
2. Go back to `MainActivity`.
3. Look if hotspot stops automatically. 
4. If not, stop the server and repeat the process.. 

**Environment**
Tested on Android 8 & 9

**Comment by kelson42** [comment]
@iadeelzafar Thank you for reporting this, seems quite a serious problem to me.

**Comment by iadeelzafar** [comment]
@kelson42 That's right. I'm working on this as my first priority right now.

**Comment by kelson42** [comment]
@iadeelzafar Any news on this? we are approaching the end of the 3.0 milestone.

**Comment by iadeelzafar** [comment]
@kelson42 Not yet. So far I've tried different things but nothing worked. I'm approaching other discussion forums to seek help on this.

**Comment by kelson42** [comment]
@iadeelzafar @macgills @abdulwd @mhutti1 We have to fix this problem in the very few next days as this is one of the last blocker for the final release of 3.0.

**Comment by iadeelzafar** [comment]
I'm working on the fallback. Had no luck so far in getting this fixed.
