### ISSUE TITLE
No Article – just white page

### ISSUE THREAD

**Issue by rocky-III** [kiwix/kiwix-android#1434]
tested today kiwix  2.5.1 (220501) for android install from f-droid… Content from before 2018-10 does work just fine… but with newer content i got some problems…
the index of articles   is shown but if i select an article I just get a white page… I tried quid a few content sources zim files…  small and big ones… all Content after  2018-10 does not seam to work on my device. I´m on android lienageOS 16 

Waht could be the reason -  thanks for help

**Comment by kelson42** [comment]
@rocky-III Thank you for your bug report. This bug has been fixed in 2.5.3. You can download an APK from https://download.kiwix.org/release/kiwix-android/2.5.3/

**Comment by rocky-III** [comment]
Ohh YES - thnak you very much...

better update this version on f-droid soon -- thanks

**Comment by rocky-III** [comment]
Do you have also an update for wikivoyageeurope ?
https://f-droid.org/de/packages/org.kiwix.kiwixcustomwikivoyageeurope/
I find the same bug at this app

**Comment by kelson42** [comment]
@rocky-III Not for now, a new release will be done in October.

**Comment by kelson42** [comment]
@rocky-III But you can use a recent Wikivoyage ZIM file with Kiwix for Android...

**Comment by rocky-III** [comment]
thanks for your work
