### ISSUE TITLE
The horizontal screen shows abnormal white

### ISSUE THREAD

**Issue by hamkido** [kiwix/kiwix-android#1435]
**Describe the bug**
The horizontal screen shows abnormal white
*Screenshots**
![Screenshot_20190905-002830_Kiwix](https://user-images.githubusercontent.com/43724352/64273924-e5cbb780-cf74-11e9-9f49-5246cb871383.png)

**Environment**
- Version of Kiwix Android : from 2018 year version to today 2.5.3
- Device : mi8 and huawei
- OS version： lineagos and emui
android  6 7 8 9

**Comment by kelson42** [comment]
Looks to be a similar bug like reported here #226

**Comment by abdulwd** [comment]
@hamkido Can you test the develop branch?

**Comment by kelson42** [comment]
@hamkido Or with this APK https://download.kiwix.org/nightly/2019-09-04/3143-kiwix-universal-debug.apk

**Comment by hamkido** [comment]
@abdulwd I tried the nightly build, It can display normally. Thank you for your help.

**Comment by hamkido** [comment]
@kelson42 It works. Thank you.
