### ISSUE TITLE
Content seem to be empty/invisible

### ISSUE THREAD

**Issue by alexanderadam** [kiwix/kiwix-android#1440]
**Describe the bug**
I'm using Kiwix with storage set to SD card ( `/sdcard/Android/data/org.kiwix.kiwixmobile/files/Kiwix/` because the device storage is too small)

Now when I go to `Get Content` I can see the zim dumps (it's `wikipedia_de_all_maxi_novid_2019-08.zim` and `wikivoyage_de_all_novid_2019-06.zip` in case that's relevant) within the `DEVICE` tab with proper icon, size and metadata. Now when I select one of the dumps I get a white (or on the dark theme a dark) page without any content. I cannot mark text or read something but when I go on the magnifier / search button and type something, the search suggestions appear. Clicking on one of the suggestions still results in an empty page though.

**Expected behavior**
I would love to see content.

**Steps to reproduce the behavior:**
1. `Get Content`
2. Choose something
3. Nothing there :cry: 

**Screenshots**
(except from the title the other zim files look empty as well)

![Screenshot_20190905-161459_Kiwix](https://user-images.githubusercontent.com/372620/64350159-7e574b80-cff8-11e9-8bff-3f32d5ef2665.jpg)

**Environment**
- Version of Kiwix Android : `2.5.1 Build: 220501`
- Device : `Samsung S4 Tablet`
- OS version : Android 9 / One UI 1.1

**Logs**
I would provide some. Where can I get Kiwix logs? :thinking:

**Comment by macgills** [comment]
resolved in 2.5.3 which is released on the play store and [here](https://github.com/kiwix/kiwix-android/releases/tag/2.5.3) and [here](https://download.kiwix.org/release/kiwix-android/2.5.3/). Thank you for the report

**Comment by alexanderadam** [comment]
@macgills thank you for your fast response. Do you know when [`2.5.3` will land on F-Droid](https://f-droid.org/en/packages/org.kiwix.kiwixmobile/)?

**Comment by macgills** [comment]
[October it seems](https://github.com/kiwix/kiwix-android/issues/1434#issuecomment-527957550)

**Comment by alexanderadam** [comment]
Oh wow. Until now I thought those releases usually would be done automatically via GitHub tags or so?

Thank you for the info.

**Comment by macgills** [comment]
The relative size of f-droid means the tooling is not so easy. We just recently added automatic play store publication, GitHub releases and publishing to our own download.kiwix.org.
With the introduction of our more streamlined build process and semantic versioning I think this should be easier. I have not been involved in many conversations on F-droid

**Comment by alexanderadam** [comment]
I see, thank you for explaining this issue and your work in general!
