### ISSUE TITLE
Route all usages of AlertDialog to DialogShower

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1443]
**Is your feature request related to a problem? Please describe.**
To control the styling and behaviour of all dialogs right now is a pain as the implementations are spread across many classes

**Describe the solution you'd like**
Route all dialog showing through the DialogShower component

**Comment by kelson42** [comment]
@macgills Is that still a work to do?

**Comment by macgills** [comment]
Yes

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by kelson42** [comment]
@gaurivn Thx, that would be great!

**Comment by mohamedsamehkhalil** [comment]
Hello, I would like to work on this.
I grepped for usages of the the alertdialog and found the following 3 files, I would like to start working on them asap
```
core/src/main/java/org/kiwix/kiwixmobile/core/main/ConfirmationAlertDialogFragment.java
core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java
```
I have a question. `DialogShower` is in interface, did you mean `AlertDialogShower` or should I implement a new class to wrap `DialogShower` ?

**Comment by macgills** [comment]
Because of how our dagger binding is setup whenever you inject DialogShower it injects an instance of AlertDialogShower. You will not need to implement a new class for this.

If you need a quick brief on DialogShower, KiwixDialog and the kotlin features they use you can chat with me on slack.

**Comment by mohamedsamehkhalil** [comment]
Yes, I would like that, but I don't know how to join slack

**Comment by kelson42** [comment]
@mohamedsamehkhalil I have sent you an invitation
