### ISSUE TITLE
Impossible to filter by author with Gutenberg

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1464]
* Donwload https://download.kiwix.org/zim/gutenberg/gutenberg_fr_all_2018-10.zim
* Open it
* Try to filter by author (top input text box)
* nothing happen

You should have a list of authors appearing depending what you type in the search box.

Here is the online version:
http://library.kiwix.org/gutenberg_fr_all/

**Comment by macgills** [comment]
6c9794f70ff5be684b88ce34f5fe3e35a3a7df3e this is the commit, making a fix

**Comment by kelson42** [comment]
@macgills Should we close that ticket?

**Comment by macgills** [comment]
Yes, currently I am working on a release branch because I don't want anything happening on develop to affect 3.0.x
