### ISSUE TITLE
XmlHttpRequest calls not possible

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-android#1469]
**Describe the bug**

All `XmlHttpRequest` calls within ZIM files fail with a message similar to this one (in the webview console):

```
Access to XMLHttpRequest at 'content://org.kiwix.kiwixmobile.zim.base/-/data.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, https.
```

**Expected behavior**

Ajax requests should load properly.

Note: works fine with kiwix-serve and Kiwix iOS.

**Steps to reproduce the behavior:**
1. Download and load [test-ajax.zim](http://tmp.kiwix.org/test-ajax.zim)
2. display homepage while watching the console output
3. should it work, the placeholder text would change.

**Environment**
- Version of Kiwix Android : `develop` branch
- Device : TECNO F1
- OS version : 8.1.0

Demo ZIM source:

``` js
let data_url = ZIM_META_NS + 'data.json';

try {
	console.info("starting request to", data_url);
	var xhr = new XMLHttpRequest();
    xhr.open('GET', data_url);
    xhr.onload = function(request){
	    var response = request.currentTarget.response || request.target.responseText;
	    console.log(response);
	    let data = JSON.parse(response);
	    console.log(data);
	    let target = document.getElementById("target");
	    target.innerText = data["content"];
	};
    xhr.send();
} catch (e) {
	console.error("Failed to execute ajax request");
	console.error(e);
}
```

``` json
{
	"content": "hello, this is data.json's content."
}
```

**Comment by kelson42** [comment]
@rgaudin I strongly suspect this is not a regression or do we have an actual production ZIM file with this problem?

**Comment by macgills** [comment]
I'll test this now, could very easily be a 1 line fix

**Comment by kelson42** [comment]
@macgills That would be awesome... I suspect this is a limitations we suffer of since the start of the project.

**Comment by macgills** [comment]
1 line fix, creating PR

**Comment by rgaudin** [comment]
yay !

**Comment by macgills** [comment]
@kelson42 do you want this to be a part of the 3.0 release?

**Comment by kelson42** [comment]
@macgills definitly

**Comment by kelson42** [comment]
Done
