### ISSUE TITLE
Able to download the same content two times

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1471]
On a slow device, it is possible to click many time on the same online library item (before it moves to the "Downloading" tab. This shoudl not.

![screenshot](https://user-images.githubusercontent.com/1029718/64905093-64da9180-d6d3-11e9-9e84-6ec446eb5566.png)

**Comment by macgills** [comment]
```
          if (downloadDao.doesNotAlreadyExist(book)) {
            val downloadId = downloadRequester.enqueue(
              DownloadRequest(it, book)
            )
            downloadDao.insert(downloadId, book = book)
          }
```

we already check this. I guess we will have to disable the view for a period of time after the user clicks it. That is shockingly slow.
Or we can run this code inside a database transaction which might make more sense
