### ISSUE TITLE
Stabilise Tab behaviour

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1476]
**Is your feature request related to a problem? Please describe.**
The tabs work mysteriously, sometimes opening a new tab close your current tab and tabs do not persist

**Describe the solution you'd like**
Using a TabsDatabase persist what the user has opened and bring stability to the feature

**Describe alternatives you've considered**
Not clear at this point how else this could be made stable but open to suggestions

**Comment by macgills** [comment]
I now think this ticket is irrelevant until we support multizim, my confusion was when I opened a different zim it closed all the existing tabs.

**Comment by kelson42** [comment]
@MohitMaliFtechiz What should we do with this ticket? do you understand it? Do you think there is still something we should do?

**Comment by MohitMaliFtechiz** [comment]
> The tabs work mysteriously, sometimes opening a new tab close your current tab and tabs do not persist

@kelson42,  I am working for the last 3 days on the tabs issue, but I have not faced this issue yet.

> I now think this ticket is irrelevant until we support multizim, my confusion was when I opened a different zim it closed all the existing tabs.

But yes when we open a new zim then it will close the previous all tabs.
