### ISSUE TITLE
kiwix android 3.0.2 hangs when selecting settings -> storage -> internal

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#1489]
**Describe the bug**

I use kiwix android 3.0.2 from download.kiwix.org.
When clicking Settings -> Storage -> Internal for selecting external, the app hangs. I can wait or close it. Nothing else.

**Expected behavior**
I shouöld be able to select external storage.

**Environment**
- Version of Kiwix Android : 3.0.2 (direct download from kiwix.org)
- Device : Galaxy S5 (SM G900F)
- OS version :  linage_klte-userdebug 9 PQ3A. 190801.002 cc929d24cb

**Comment by macgills** [comment]
Very unfortunate. This is due to us trying to detect the filesystem of the sd card, even though we do this on a background thread it is somehow congesting the device. Is it possible to use another sd card to try and see if the issue is isolated to the card?
It is possible it will eventually work if you wait long enough but it is obviously not desired functionality

**Comment by macgills** [comment]
@JensKorte I am  bit of a loss as to why this is happening.
Is it possible for you to try and replicate the bug in any of the following scenarios:

- on a non Samsung phone
- on a non lineage OS
- on 2.5.3 release of kiwix
- with a different sd card

Otherwise I will just be taking stabs in the dark as to why this is happening

**Comment by JensKorte** [comment]
I found a difference with 2.5.3: 
* When starting for the first time after installing I can go to settings without Get content and select the Extern from storage. There is neither internal storage nor "/" to select. When clicking External again, there is no internal storage. Selecting External again works. Killing kiwix and starting over doesn't change anything. When I get content, switch to files on Device, select WP-german-maxi, then I get the full menu on storage with Internal, External and "/" (enter dir).
* When starting after installing I try to select Get content and 2.5.3 tries to download the list of media from the internet. I select WP german maxi 2019 and the media list is still downloading. When I try to select storage, the menu was opened and I wasn't able to select anything. I killed the process and started again. I am not sure if the menu language changed from german to english. Within the settings I saw "Internal" with the free space from external. Then I get the full menu and can select external without problems. I was able to reproduce it.

micro-SD card is a Samsung 200GB card with exfat, german wp maxi 2019.

kiwix-2.5.3_armeabi-v7a.apk

**Comment by macgills** [comment]
https://drive.google.com/open?id=1CvMCIEhAtsvTchMjs1ELjh286k-h1c-q A bit unorthodox but can you try with this apk? Very much an in development version but there is a possibility it will alleviate your issues. If it is successful I can pursue this solution more fully.

**Comment by JensKorte** [comment]
I didn't work for me. Now the frame around the app blinks several times and I get back to the kiwix start screen. Sometimes the app crashes. Message at the Android status line:
"3 retained instances, tap to dump head. App visible, waiting until 5 retained instances." Are there dumps I can upload?

**Comment by JensKorte** [comment]
[logcat.txt](https://github.com/kiwix/kiwix-android/files/3636104/logcat.txt)
I hope, this is it.

**Comment by macgills** [comment]
Yeah, the "retained instance" thing is a developer thing, don't need to worry about that.

Was this on a fresh install?

**Comment by macgills** [comment]
I am in the process of making a version without the retained instance stuff and also with the ability for you to email me crash reports. Will upload shortly

**Comment by macgills** [comment]
https://drive.google.com/open?id=1KW8xKAcnSSE91jzeatmUJrZs_zCgmXln

**Comment by JensKorte** [comment]
> Yeah, the "retained instance" thing is a developer thing, don't need to worry about that.
> 
> Was this on a fresh install?
I installed your Kiwix-debug version several time. I don't know, if the logcat file gets refreshed. The lineageos is not fresh, but quite up to date: 16.0-20190917-NIGHTLY-klte

**Comment by macgills** [comment]
The logcat files are generated quite poorly, I wouldn't rely on them for now, they are often quite incomplete. If you can try with that new version and if prompted email crash reports then hopefully I can make some headway. Thank you for your assistance

**Comment by JensKorte** [comment]
> The logcat files are generated quite poorly, I wouldn't rely on them for now, they are often quite incomplete. If you can try with that new version and if prompted email crash reports then hopefully I can make some headway. Thank you for your assistance

The 2. Version: After tapping on Storage - Internal the app hangs. Android asks for wait or kill? I tapped waiting once and then end. Kiwix starts with Homepage. Second time tapping Internal, Kill the app crashes back to android starter.

I haven't configured the standard mail app but use another one. Is this relevant or do I get a message about which app to use for mailing?

**Comment by macgills** [comment]
it should allow you the choice of any mail app. Hmmm let me go back to the drawing board. I don't think your problem is related to us writing that 4GB file anymore so at least that is progress

**Comment by macgills** [comment]
https://drive.google.com/open?id=1mdoOXcJs-uOVsFWpVjgk5BsaaUmgImuG New version of the app, what I think will happen :
You click on internal and will see an empty dialog for a few seconds (if I am very unlucky, a few mintes) and then you will be able to select the right storage.

**Comment by JensKorte** [comment]
> https://drive.google.com/open?id=1mdoOXcJs-uOVsFWpVjgk5BsaaUmgImuG New version of the app, what I think will happen :
> You click on internal and will see an empty dialog for a few seconds (if I am very unlucky, a few mintes) and then you will be able to select the right storage.

I was able to select the storage without problems. There was no delay.  "/" and select dir was missing.

**Comment by macgills** [comment]
"/" feature was removed. Cool, I'll move forward with this solution
