### ISSUE TITLE
Check the APK only contains essential libraries

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#149]
I discovered LibRadar last week (while I was at the ICSE 2017 conference). It processes an APK file and detects which libraries are incorporated into the app. There seem to be a couple of unexplained libraries in the APK file of Kiwix (I checked 2.0 and 2.2). Perhaps we can tweak the settings of the gradle build files to exclude non-essential libraries? 

http://radar.pkuos.org/

Details from their report are reproduced below:
APK
kiwix-2.2.apk

Libraries

Library|Package Name (In-Dataset)|Package Name (In-App)|Popularity|Match Ratio|Type|Website
--|--|--|--|--|--|--
Junit|Ljunit|Ljunit|687|<116/116>|Development Aid|<http://junit.org/junit4/>
retrofit RESTful Library|Lretrofit2|Lretrofit2|2|<88/88>|Development Aid|https://square.github.io/retrofit/
Google Core Libraries (3rd Party)|Lcom/google/thirdparty|Lcom/google/thirdparty|3332|<2/2>|Development Aid|https://github.com/google/guava
Google Core Libraries for Java 6+|Lcom/google/common|Lcom/google/common|282|<4685/4685>|Development Aid|https://github.com/google/guava
butterknife UI Framework|Lbutterknife|Lbutterknife|4756|<37/37>|GUI Component|https://github.com/JakeWharton/butterknife
OKHttp3.0|Lokhttp3|Lokhttp3|3281|<896/896>|Development Aid|https://github.com/square/okhttp
OkHttp okio Framework|Lokio|Lokio|4545|<110/110>|Development Aid|https://github.com/square/okio
RxJava Retrofit|Lrx/internal|Lrx/internal|616|<1116/1116>|Development Aid|https://github.com/square/retrofit
Android Support|Landroid/support|Landroid/support|1|<12202/12202>|Development Aid|https://developer.android.com/reference/android/package-summary.html
Android Support v13|Landroid/support/v13|Landroid/support/v13|1003|<132/132>|Development Aid|https://developer.android.com/reference/android/support/v13/app/package-summary.html
Android Support Design|Landroid/support/design|Landroid/support/design|914|<1262/1262>|Development Aid|https://developer.android.com/reference/android/support/design/package-summary.html
Android Support v4|Landroid/support/v4|Landroid/support/v4|2975|<6162/6162>|Development Aid|http://developer.android.com/reference/android/support/v4/app/package-summary.html
Android Support v7|Landroid/support/v7|Landroid/support/v7|37|<3895/3895>|Development Aid|https://developer.android.com/reference/android/support/v7/app/package-summary.html
simple framework|Lorg/simpleframework|Lorg/simpleframework|2833|<442/442>|Development Aid|http://www.simpleframework.org/
jUnit Java Unit Test|Lorg/junit|Lorg/junit|621|<683/683>|Development Aid|http://junit.org/
hamcrest|Lorg/hamcrest|Lorg/hamcrest|665|<79/79>|Development Aid|http://hamcrest.org/
Unknown|Lrx/observers|Lrx/observers|5300|||	
Unknown|Lrx/observables|Lrx/observables|5114|||	
```

**Comment by kelson42** [comment]
@julianharty Could you run this again a nightly build and let us know the one in particular which should not be included to your opinion?

**Comment by mhutti1** [comment]
I'm a bit confused about what this says. I am almost certain that we use some of these.

**Comment by julianharty** [comment]
For http://download.kiwix.org/nightly/2017-06-10/kiwix-android_arm-release-unsigned.apk here is the output, this time as JSON
@mhutti1 We use all of these AFAIK; for me the question is whether we should include all of these in the *release* build of Kiwix-Android. From my perspective we shouldn't be including JUnit, for instance, and probably not hamcrest either in the release binary. Also there's the Simple framework that appears to include an HTTP *server*, according to http://www.simpleframework.org/ . I don't know if the app actually includes an HTTP Server, if so, why? And do we want/need retrofit and retrofit2 ? 

@kelson42 in summary I'd suggest it'd be appropriate to remove the following from at least the release builds:
* jUnit (both instances)
* Hamcrest

and possibly: Simple Framework (or at least any HTTP Server)
and depending on whether we need both retrofit and retrofit2 remove whichever isn't needed.


```
[
    {
        "Library": "Junit", 
        "Match Ratio": "116/116", 
        "Package": "Ljunit", 
        "Permission": [], 
        "Popularity": 687, 
        "Standard Package": "Ljunit", 
        "Type": "Development Aid", 
        "Website": "http://junit.org/junit4/"
    }, 
    {
        "Library": "retrofit RESTful Library", 
        "Match Ratio": "88/88", 
        "Package": "Lretrofit2", 
        "Permission": [], 
        "Popularity": "2", 
        "Standard Package": "Lretrofit", 
        "Type": "Development Aid", 
        "Website": "https://square.github.io/retrofit/"
    }, 
    {
        "Library": "RxJava Retrofit", 
        "Match Ratio": "1116/1116", 
        "Package": "Lrx/internal", 
        "Permission": [], 
        "Popularity": 616, 
        "Standard Package": "Lrx/internal", 
        "Type": "Development Aid", 
        "Website": "https://github.com/square/retrofit"
    }, 
    {
        "Library": "Google Core Libraries (3rd Party)", 
        "Match Ratio": "2/2", 
        "Package": "Lcom/google/thirdparty", 
        "Permission": [], 
        "Popularity": 3332, 
        "Standard Package": "Lcom/google/thirdparty", 
        "Type": "Development Aid", 
        "Website": "https://github.com/google/guava"
    }, 
    {
        "Library": "Google Core Libraries for Java 6+", 
        "Match Ratio": "5037/5037", 
        "Package": "Lcom/google/common", 
        "Permission": [], 
        "Popularity": 73, 
        "Standard Package": "Lcom/google/common", 
        "Type": "Development Aid", 
        "Website": "https://github.com/google/guava"
    }, 
    {
        "Library": "butterknife UI Framework", 
        "Match Ratio": "37/37", 
        "Package": "Lbutterknife", 
        "Permission": [
            "android.permission.DUMP", 
            "android.permission.INTERACT_ACROSS_USERS", 
            "android.permission.INTERACT_ACROSS_USERS_FULL"
        ], 
        "Popularity": 4756, 
        "Standard Package": "Lbutterknife", 
        "Type": "GUI Component", 
        "Website": "https://github.com/JakeWharton/butterknife"
    }, 
    {
        "Library": "OKHttp3.0", 
        "Match Ratio": "920/920", 
        "Package": "Lokhttp3", 
        "Permission": [], 
        "Popularity": 652, 
        "Standard Package": "Lokhttp3", 
        "Type": "Development Aid", 
        "Website": "https://github.com/square/okhttp"
    }, 
    {
        "Library": "OkHttp okio Framework", 
        "Match Ratio": "133/133", 
        "Package": "Lokio", 
        "Permission": [], 
        "Popularity": 1895, 
        "Standard Package": "Lokio", 
        "Type": "Development Aid", 
        "Website": "https://github.com/square/okio"
    }, 
    {
        "Library": "Dagger", 
        "Match Ratio": "31/31", 
        "Package": "Ldagger", 
        "Permission": [], 
        "Popularity": 729, 
        "Standard Package": "Ldagger", 
        "Type": "Development Aid", 
        "Website": "http://square.github.io/dagger/"
    }, 
    {
        "Library": "Android Support", 
        "Match Ratio": "13954/13954", 
        "Package": "Landroid/support", 
        "Permission": [
            "android.permission.BACKUP", 
            "android.permission.BLUETOOTH_ADMIN", 
            "android.permission.DUMP", 
            "android.permission.INTERACT_ACROSS_USERS", 
            "android.permission.INTERACT_ACROSS_USERS_FULL", 
            "android.permission.INTERNET", 
            "android.permission.MANAGE_APP_TOKENS", 
            "android.permission.WAKE_LOCK", 
            "android.permission.WRITE_SECURE_SETTINGS"
        ], 
        "Popularity": "90391", 
        "Standard Package": "Landroid/support", 
        "Type": "Development Aid", 
        "Website": "https://developer.android.com/reference/android/package-summary.html"
    }, 
    {
        "Library": "Multidex", 
        "Match Ratio": "163/163", 
        "Package": "Landroid/support/multidex", 
        "Permission": [
            "android.permission.DUMP"
        ], 
        "Popularity": 90391, 
        "Standard Package": "Landroid/support/multidex", 
        "Type": "Development Aid", 
        "Website": "https://developer.android.com/studio/build/multidex.html"
    }, 
    {
        "Library": "Android Support v13", 
        "Match Ratio": "161/161", 
        "Package": "Landroid/support/v13", 
        "Permission": [
            "android.permission.DUMP", 
            "android.permission.INTERACT_ACROSS_USERS", 
            "android.permission.INTERACT_ACROSS_USERS_FULL", 
            "android.permission.INTERNET"
        ], 
        "Popularity": 1484, 
        "Standard Package": "Landroid/support/v13", 
        "Type": "Development Aid", 
        "Website": "https://developer.android.com/reference/android/support/v13/app/package-summary.html"
    }, 
    {
        "Library": "Android Support Design", 
        "Match Ratio": "1419/1419", 
        "Package": "Landroid/support/design", 
        "Permission": [
            "android.permission.DUMP", 
            "android.permission.INTERACT_ACROSS_USERS", 
            "android.permission.INTERACT_ACROSS_USERS_FULL", 
            "android.permission.INTERNET"
        ], 
        "Popularity": 1496, 
        "Standard Package": "Landroid/support/design", 
        "Type": "Development Aid", 
        "Website": "https://developer.android.com/reference/android/support/design/package-summary.html"
    }, 
    {
        "Library": "Android Support v4", 
        "Match Ratio": "6777/6777", 
        "Package": "Landroid/support/v4", 
        "Permission": [
            "android.permission.BACKUP", 
            "android.permission.BLUETOOTH_ADMIN", 
            "android.permission.DUMP", 
            "android.permission.INTERACT_ACROSS_USERS", 
            "android.permission.INTERACT_ACROSS_USERS_FULL", 
            "android.permission.INTERNET", 
            "android.permission.WAKE_LOCK", 
            "android.permission.WRITE_SECURE_SETTINGS"
        ], 
        "Popularity": 2390, 
        "Standard Package": "Landroid/support/v4", 
        "Type": "Development Aid", 
        "Website": "http://developer.android.com/reference/android/support/v4/app/package-summary.html"
    }, 
    {
        "Library": "Android Support v7", 
        "Match Ratio": "4198/4198", 
        "Package": "Landroid/support/v7", 
        "Permission": [
            "android.permission.DUMP", 
            "android.permission.INTERACT_ACROSS_USERS", 
            "android.permission.INTERACT_ACROSS_USERS_FULL", 
            "android.permission.INTERNET", 
            "android.permission.MANAGE_APP_TOKENS"
        ], 
        "Popularity": 393, 
        "Standard Package": "Landroid/support/v7", 
        "Type": "Development Aid", 
        "Website": "https://developer.android.com/reference/android/support/v7/app/package-summary.html"
    }, 
    {
        "Library": "Apache Common", 
        "Match Ratio": "1156/1156", 
        "Package": "Lorg/apache/commons", 
        "Permission": [], 
        "Popularity": 108, 
        "Standard Package": "Lorg/apache/commons", 
        "Type": "Development Aid", 
        "Website": "https://commons.apache.org/"
    }, 
    {
        "Library": "simple framework", 
        "Match Ratio": "442/442", 
        "Package": "Lorg/simpleframework", 
        "Permission": [], 
        "Popularity": 2833, 
        "Standard Package": "Lorg/simpleframework", 
        "Type": "Development Aid", 
        "Website": "http://www.simpleframework.org/"
    }, 
    {
        "Library": "jUnit Java Unit Test", 
        "Match Ratio": "683/683", 
        "Package": "Lorg/junit", 
        "Permission": [], 
        "Popularity": 621, 
        "Standard Package": "Lorg/junit", 
        "Type": "Development Aid", 
        "Website": "http://junit.org/"
    }, 
    {
        "Library": "hamcrest", 
        "Match Ratio": "79/79", 
        "Package": "Lorg/hamcrest", 
        "Permission": [], 
        "Popularity": 665, 
        "Standard Package": "Lorg/hamcrest", 
        "Type": "Development Aid", 
        "Website": "http://hamcrest.org/"
    }, 
    {
        "Library": "Unknown", 
        "Package": "Lrx/observers", 
        "Popularity": 5300, 
        "Standard Package": "Lrx/observers", 
        "Weight": 73
    }, 
    {
        "Library": "Unknown", 
        "Package": "Lrx/observables", 
        "Popularity": 5114, 
        "Standard Package": "Lrx/observables", 
        "Weight": 53
    }
]
```

**Comment by mhutti1** [comment]
@julianharty Ok that sounds sensible. We certainly need to carry out these actions as part of reducing apk size. I think we might need to test removing the duplicate libraries carefully.

**Comment by julianharty** [comment]
@mhutti1 Of course we could increase the test coverage and use those to help weed out any problems :) BTW: I'm willing to help create tests for the app. Just let me know what progress you've made with the automated tests and where you'd like some help and I'll have a go (and if we could track the tests using issues here that'll help us keep them on the radar...)

**Comment by mhutti1** [comment]
@julianharty Yeah that sounds like a good idea. I'll add a few wiki pages about our current tests/build process next weekend once uni deadlines are over and get in touch about ideas for future tests / improvements. We are tracking some test related stuff [here](https://github.com/kiwix/kiwix-android/projects/2). Our current test suite seems to be working well and is now mandatory to merge so it will be good to extend it.

**Comment by julianharty** [comment]
Note to self: let's check that we have sorted out the most appropriate set of dependencies for the various build variants. See these for more info.
https://developer.android.com/studio/build/build-variants.html 
https://developer.android.com/studio/build/dependencies.html

**Comment by abdulwd** [comment]
@julianharty @mhutti1 I'm not sure but I think we can get rid of Guava. I have found only one use of Guava in **LibraryAdapter** using only one class of the library and that is **com.google.common.collect.ImmutableList**. 

So, I replaced the **ImmutableList.copyOf** method with **Collections.unmodifiableList** and replaced **ImmutableList** with **List** and removed Guava from the dependencies. As a result, the size of APK for debug build dropped from **52.3 MB** to **51.3 MB**. I am using [3.0](https://github.com/kiwix/kiwix-android/tree/3.0) branch.

Everything was fine as far as I have tested and all tests were passing locally. May I remove this library?

**Comment by mhutti1** [comment]
Is Collections.... available on older Android versions?

**Comment by abdulwd** [comment]
@mhutti1 Yes.

**Comment by mhutti1** [comment]
Are you sure https://developer.android.com/reference/java/util/Collections#unmodifiableList(java.util.List%3C?%20extends%20T%3E) ?

**Comment by abdulwd** [comment]
@mhutti1 I see that the link says **added in API level 24** but I ran this on an emulator with API 16 and I was able to see the list of books. Ideally, the app should have crashed if the method was not found. [Collections.unmodifiableList](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#unmodifiableList(java.util.List)) was present in Java 7.
May I make a PR to test this on physical devices on Testroid?

**Comment by julianharty** [comment]
@abdulwd sounds good. We're currently using 4 devices on Testdroid, running a mix of Android 4.4, 6.0 and 7.0 which means we're testing on API level 20 and higher
https://en.wikipedia.org/wiki/Android_version_history 
I should be able to add a device running Android 4.3 (API level 16), Testdroid seem to have several. Have you also tried creating and testing on an emulator image running 4.3?

**Comment by julianharty** [comment]
I've added an Acer Iconia B1-A71 which seems to be running Android 4.3 (according to Bitbar's filters in Testdroid, they protect the settings app from being used directly). I'll run a set of tests on all 5 devices by restarting a build in Travis-CI to see if the current tests and code run cleanly on this device.

**Comment by abdulwd** [comment]
@mhutti1 It's a bug in the documentation for **Collections.unmodifiableList** and it has been reported [here](https://issuetracker.google.com/issues/37109296). IMO we should test the PR on API 14 and merge it if it passes all the tests.

**Comment by mhutti1** [comment]
Ok, I am still very cautious about this.
