### ISSUE TITLE
"Search Kiwix" does not work properly

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1493]
Steps:
* Open any article
* Select a word
* Contextual display appears
* Click on "Search Kiwix" item
* A new search is launched on the selected word

The problem is that most of the time you no suggestion at all... Although if I remove the last letter of the search pattern and retype it, then I get the proper suggestions!

**Comment by macgills** [comment]
@kelson42 I will require a more specific repro case. I went to Granblue Fantasy Wiki, selected "characters", selected "SEARCH KIWIX" and was then shown a screen of suggestions

**Comment by kelson42** [comment]
Pff... seems to work perfectly now for me too :(
