### ISSUE TITLE
SD seems to be not detected on Motorola Moto E XT1021

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#15]
Tested on BitBar and reported first here: https://play.google.com/apps/publish/?account=9116215767541857492#ReviewDetailsPlace:p=org.kiwix.kiwixmobile&reviewid=gp:AOqpTOGJzvB79Xcn_ho8bCAbUXsJzTZIpL2EIupU3wN2hIqXj6VDhf_WWZ1CPcJa-6sdbefgAMve9LSBWwpXfT0

**Comment by kelson42** [comment]
@mhutti1 Seems to need an improved of your SD card dection librayr.

**Comment by mhutti1** [comment]
Storage locations can now be manually added. I have tested and this is possible on the moto E. It should be working as we have the path added but I don't think it is worth investigating further.
