### ISSUE TITLE
Delete "custom" directory

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#150]
This is handled separatly now, isn't it?

**Comment by mhutti1** [comment]
I don't understand what this is referring to

**Comment by kelson42** [comment]
This is the directory (https://github.com/kiwix/kiwix-android/tree/master/custom) where we have the metadata for the custom apps. But now these informations are in https://github.com/kiwix/kiwix-android-custom... so it should not be necessary to have a duplicate here?

**Comment by mhutti1** [comment]
It allows for testing without downloading the extra repositories.

**Comment by kelson42** [comment]
@mhutti1 ok, this is a bit disturbing, I should probably be in some kind of "test" directory and here a git submodule should be used instead of having a duplicate. A few mockup data should also be better than bunch of real-one, or maybe renaming then.

**Comment by mhutti1** [comment]
The point of the directory being in the main repository allows developers to test custom apps easily on the main repository. I agree we should change it to a test file but no such ZIM file currently exists.

**Comment by kelson42** [comment]
@mhutti1 Ok, so let me fix https://github.com/kiwix/kiwix-android/issues/107 first.

**Comment by mhutti1** [comment]
Yeah. Once we have a test ZIM ideally considerably smaller we can use that instead.

**Comment by kelson42** [comment]
@mhutti1  #107 is done, so this one can be closed too?

**Comment by mhutti1** [comment]
@kelson42 Will just need to swap the file out/ get gradle to download dynamically.
