### ISSUE TITLE
Google Play Services needed for server 3.0.2 Beta

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#1500]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
When I want to start the server I get the error Google Play Service needed. Is Google really needed? It would be nice to check for Google Play Services after clicking "Host Books" and to show an error at the top where "Select the files you wish to host on the server" is shown.

**Describe alternatives you've considered**
An earlier warning would be nice. It would also be possible to show just an error message instead of the whole page.

**Comment by kelson42** [comment]
@JensKorte Do I understand properly? The WIFI hotspot feature is not available for users without access to the PlayStore?

**Comment by JensKorte** [comment]
If WifiHotspot and "Host Books" are the same, then yes. After tapping "Start Server" I get the message: "Kiwix won't run without Google Play services, which are not supported by your device".

I have the plain lineageos image without the Gapps addon.

**Comment by JensKorte** [comment]
Sorry PlayStore and Google Play Services are different imho.

**Comment by kelson42** [comment]
Ok. Trying to understand why that would be needed and found https://android.stackexchange.com/tags/google-play-services/info... but still don't see why it should.

**Comment by macgills** [comment]
This is due to the location request code. We can probably rewrite this.

**Comment by abdulwd** [comment]
We have to rewrite this to remove play services but then we have to turn the hotspot manually.

**Comment by macgills** [comment]
We can do a location request without bothering with google play services and in fact the more I think about it I am dubious as to why we need it in the first place. Surely the permission is the only thing we need granted to turn on the hotspot?

**Comment by abdulwd** [comment]
@iadeelzafar has more context on this.

**Comment by iadeelzafar** [comment]
@macgills @abdulwd Acc to the documentation of [startLocalOnlyHotspot](https://developer.android.com/reference/android/net/wifi/WifiManager#startLocalOnlyHotspot(android.net.wifi.WifiManager.LocalOnlyHotspotCallback,%20android.os.Handler)) only `Manifest.permission.CHANGE_WIFI_STATE` and `ACCESS_FINE_LOCATION` permissions should be required.

But even after granting these permissions, I was getting the error #1187
`java.lang.SecurityException: Location mode is not enabled.`

So, this is the workaround that helped me fix the `SecurityException`.

**Comment by macgills** [comment]
Yeah we don't need the google play services to do that I would think.
[This](https://stackoverflow.com/questions/25175522/how-to-enable-location-access-programmatically-in-android) is ringing a bell from the ble app I worked on

**Comment by JensKorte** [comment]
> We have to rewrite this to remove play services but then we have to turn the hotspot manually.

I am not sure, if I understand the whole situation. Is the rewrite of this part of play service a kind of open-source replacement for one part of the Gapps?
If yes, would it make sense to put it into an external library to make it available to other projekcts?

Does it make sense to check for the existence of Play Services and use it if available or if the user selects to?

**Comment by macgills** [comment]
This is pretty standard non specialised code. The google play services `task` just wraps around some things nicely/easily and if we _actually_ wanted to know the user location then it might be a concern but we don't, we just need the user to have turned on their location services which we can prompt them to do.

**Comment by kelson42** [comment]
@macgills I'm not sure to fully understand myself. In case this was not so clear, I really against requiring permissions for things we really don't need. Here it seems we could avoid asking about that permission. Do I understand properly? If "yes", could we do that please?

**Comment by macgills** [comment]
With the removal of the 8.0 code I think we will no longer need the permission. 8.0 code definitely needed the permission because we programmatically turned on a hotspot. I'll evaluate the situation when I take over the hotspot code

**Comment by macgills** [comment]
@iadeelzafar removed the code for requesting location, this will be fixed by #1506
