### ISSUE TITLE
Read aloud feature does not support switching ZIM files -> crash

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1509]
1 - Start read aloud on a random article
2 - Go to library and open an other ZIM file
3 - Read aloud stops
4 - Start read aloud on a random article of this new file

My Kiwix just stops working or even crash.

**Comment by macgills** [comment]
There is a dumb fix we can do to avoid the crash but depending on how we want this to work there should probably be a service that handles TextToSpeech

**Comment by macgills** [comment]
Okay so we need to collect requirements about how TTS works.
A task gets submitted to our service. A task can be paused, stopped, complete itself or be terminated by requesting a new task.
Tasks are "Read Current Selection" & "Read Current Page"?
A task continues until explicitly stopped by user interaction? We will need a notification if this is the case to support it being used while our app is in background. 
If the TTS task should stop as soon as a user navigates away from the open zim file then we probably don't want a service

**Comment by kelson42** [comment]
The read aloud should continue in the backround (like any audio playing app) as long as the article/selection is not read to the end or the feature stopped explicitly in Kiwix or another article/selection to be read started. I think also that the user should probably be able to continue to do whatever he wants with kiwix.

**Comment by macgills** [comment]
@kelson42 it seems this functionality is supported without us making any changes and this bug has been fixed.
I would propose deferring this ticket to a latter milestone in the interest of wrapping up 3.1

**Comment by macgills** [comment]
@kelson42 what is to be done here, there is no crash. I don't think a maintenance release is the place to be rearchitecting TextToSpeech

**Comment by kelson42** [comment]
Works more or less... but we have a few weird behaviours there. We probably need to clarify tabs/multizim first.
