### ISSUE TITLE
Fails to display landing page

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1511]
Kiwix Android 3.0.3 / Android 9
I've tried to download a couple of the Top 50k (French, Chinese, Norsk Bokmal): when opening these the tiled landing page appears for a split second before the screen appears dark. I can stil check articles, so it really is a display issue.
Interestingly, the display issue does not seem to happen with a couple of selections (e.g. [Football, french](http://download.kiwix.org/zim/wikipedia/wikipedia_fr_football_novid_2019-06.zim) and [Chemistry, French, mini](http://download.kiwix.org/zim/wikipedia/wikipedia_fr_chemistry_nodet_2019-06.zim) both from last June). Could the bug be a thing from the later MWoffliner releases?

**Comment by kelson42** [comment]
If it fails on library.kiwix.org, yes this is a problem with the ZIM.

**Comment by kelson42** [comment]
I can not reproduce the problem with my Pixel on Android 9

![screenshot](https://user-images.githubusercontent.com/1029718/65509631-2dd65e00-ded3-11e9-96d9-a8d5b0f023d2.png)

**Comment by Popolechien** [comment]
Dammit, I can't reproduce it anymore either. Looks like the fix consists of turning the phone off and then back on again : [I should have known better](https://www.youtube.com/watch?v=5UT8RkSmN4k)!

Closing ticket.
