### ISSUE TITLE
Crash Report 3.0.3: AndroidInjection.Inject

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1515]
**Describe the bug**
```
Caused by: java.lang.RuntimeException: 

 
  at dagger.android.AndroidInjection.inject (AndroidInjection.java:49)

 
  at org.kiwix.kiwixmobile.base.BaseActivity.injection (BaseActivity.java:48)

 
  at org.kiwix.kiwixmobile.base.BaseActivity.onCreate (BaseActivity.java:42)

 
  at org.kiwix.kiwixmobile.splash.SplashActivity.onCreate (SplashActivity.java:33)
```
This is a very strange one
```
 public static void inject(Activity activity) {
    checkNotNull(activity, "activity");
    Application application = activity.getApplication();
    if (!(application instanceof HasActivityInjector)) {
      throw new RuntimeException(
          String.format(
              "%s does not implement %s",
              application.getClass().getCanonicalName(),
              HasActivityInjector.class.getCanonicalName()));
    }
```
The only reason I can see for this dagger code to fail is if `activity.getApplication()` returns null which is a head scratcher in and of itself. I would propose scouring `dagger-android` from the application and using plain `dagger` injection. Not a small task and the crash rate is fairly low.

**Expected behavior**
No Crash

**Environment**
- Version of Kiwix Android : 3.0.3
- Device : Samsung Galaxy A5(2017) (a5y17lte), 
- OS version : Android 8.0

**Comment by kelson42** [comment]
Will be fixed because #1581 has been implemented.
