### ISSUE TITLE
Make socket address better visible, clickable and shareable

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#1542]
**Is your feature request related to a problem? Please describe.**
I didn't recognize the message with IP:Port at first. Maybe it could be better visible.
The version is [3.0.4 from download.k.o](https://download.kiwix.org/release/kiwix-android/3.0.4/3312-kiwix-universal-release.apk)

**Describe the solution you'd like**

After starting the server the message "Enter this ip address into your browser to access the server http://a.b.c.d:8080" appears.

Maybe the URL could be better visible. Either it could be printed bold or it could be even a clickable URL which opens in a new program.

**Comment by kelson42** [comment]
I have splitted your ticket in two with #1553 to bring more clarity.

**Comment by kelson42** [comment]
@JensKorte I agree with you.
@iadeelzafar Would you be able to put these connections details in a more visible manner at the top of the screen? Maybe in a color box? I also think the URL should be clickable.

**Comment by iadeelzafar** [comment]
@kelson42 So, I looked into this and #1553 

We have two objectives here

**1- Making the "server started message" better visible and clickable.**

**2- Making the URL shareable:**
We have 2 options.
a- via adding a share button:
This will copy the message on the server device and open an intent to send it via other apps(i.e. messenger apps, etc)

b- OR via adding a QR scanner:
I don't think this is a super useful approach considering a lot of users will have to scan the QR from a single device.

**Comment by JensKorte** [comment]
I never had someone else in my wifi network using my kiwix, I am using it on my own. What is the planned usage for kiwix-server in android?  
 (a) a (small) group is travelling on a boat/train/plane and some people need the IP
 (b) a mobile phone will be the server in the african outback?

To
(a) group: A useful way could be to show the OR code on the mobile phone.  
(b) server replacement: 1. The QR code should be printed on a paper or 2. the software locked mobile phone is tied to a table and everyone can go there, tap a button and the lock screen shows the QR-code(s)

Every solution could be solved by providing the data to other (helper) apps and the core source code from kiwix would be smaller. Also it would be the Unix way.

**Comment by iadeelzafar** [comment]
@JensKorte Gotcha! I think QR is also something that we can look into once the basics are implemented.

**Comment by iadeelzafar** [comment]
Here's something that we can do as a first step:

1- The URL is better visible and clickable.
2- Using the share button, we can share the URL via relevant apps for handling this intent

<img src = "https://user-images.githubusercontent.com/36811908/71327749-28b69880-252e-11ea-90d6-3a632de69192.jpg" height="643" width="302">

**Comment by JensKorte** [comment]
> Enter this ip address into your browser to access the server

How about:  
"Click/tap the URL below or enter it into your browser to access the server"

**Comment by macgills** [comment]
I'd prefer if clicking the link presented a [bottom sheet](https://material.io/components/sheets-bottom/) with our options eg "show qr/share via app/copy text/open in browser" though I am not sold on all these options. we could probably use nfc to share links as it is nicer to just tap phones especially given the proximity necessary

**Comment by JensKorte** [comment]
The URL in the screenshot above looks good. In 3.2.1 from download.k.o this is lacking.

**Comment by suterma** [comment]
Just as a reference, here is how it currently looks on my Fairphone3, version 3.4.4, without any of the above improvements yet included. It's unnecessarily hard to spot.
![Screenshot_20210722-102421](https://user-images.githubusercontent.com/11473920/126632998-eebebbfd-b54f-4675-ba01-6bc0f7a5a327.jpeg)

**Comment by s-ayush2903** [comment]
@suterma You can try the apk generated from the linked PR(we publish APK related to each PR as CI artifacts at GitHub) and let us know your feedback : )
Let me know if you find any problem in getting the APK

**Comment by JensKorte** [comment]
>  Let me know if you find any problem in getting the APK

I don't find it, can you help me, please?

**Comment by s-ayush2903** [comment]
For _now_, you can directly go to [this](https://github.com/kiwix/kiwix-android/pull/2679/checks?check_run_id=3152899616) link to obtain the APK(via taking _little_ help from picture attached), also keep in mind that the APK from this url will become obsolete if I push any further commits/work on the linked PR, so in that case follow the given instructions in sequence given below(this general workflow for getting artifacts is _more_ advised, as it is dynamic), so make sure that you
* have opened the correct PR(the `1` red colored circle in the picture, the number enclosed in red box near this circle is the PR number)
* are standing on the **Checks** section of that PR(the Red colored circle with number `2` on it)
* have selected the **Build** Job there (the Red colored circle with number `3` on it)
* Then go to the **Artifacts** dropdown and select **kiwix-android**(the Red colored circles with number `4` & `5` on it)

Following these steps will give you a zip file which on extraction will show you many _APKs_, you can try any of them

-----

|Image as a Reference for the instructions provided above|
|--|
|![image](https://user-images.githubusercontent.com/56556919/126892660-d5d49cc3-8c5d-4442-befe-847af08c5c44.png)|

**Comment by JensKorte** [comment]
The link works, but the renderer is not nice.

![Screenshot_20210725-105738_Kiwix](https://user-images.githubusercontent.com/2682123/126893599-4e6a1531-ee9a-4f63-b111-3c5ac64051f1.png)

**Comment by s-ayush2903** [comment]
Thanks a lot for testing it out. I just thought of `en` while writing the fix and other languages were really not in my mind. Will push the fix :)

**Comment by s-ayush2903** [comment]
Now it should work flawlessly in all scenarios, I've generalized the method for finding the url in the text

|An example|
|--|
|<img src="https://files.gitter.im/5e46e1d4d73408ce4fd9acef/v7yT/fix.jpeg" height=500>|

**Comment by JensKorte** [comment]
Link looks good and Link and "Share to" works for me. Can the link be even bigger or bright? At least it is better visible then before.
