### ISSUE TITLE
Remove email addresses from Credits

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1544]
The Settings page lists Kiwix contributors and includes their email addresses, which can lead to unsollicited (and rarely actionable) email, particularly for former contributors.

If people want to comment they should generally use the Android store, or the webform on our website.

So the proposal is to remove contributors email addresses and, to be clear, **not** replace it with a generic address: as indicated, that feedback is rarely (if ever) actionable.

Over the course of 2019 we've received so far more than 2'900 emails, 2'200 coming from android users. A fair number (1'600) were in Arabic or Spanish, and about 1'400 were actually empty (ie people had no idea what they were doing). Each and every one of them nevertheless had to be dealt with, which over the course of a year adds up to 60 hours (YTD) for very little return we could not have otherwise (<20 donations; I suspect #929 has had more impact).

**Comment by kelson42** [comment]
Looks good to me.
