### ISSUE TITLE
download.kiwix.org released APK name/directory is not proper

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1546]
* We should not have a `3.0.4` subdirectory because we have only one file in it
* The file should be called `kiwix-x.y.z.apk` and not `3312-kiwix-universal-release.apk`

**Comment by kelson42** [comment]
@macgills I have moved the files, so don't be surprised if you don't find the old/badly named apk files.

**Comment by macgills** [comment]
the `3312` is so we have a build number association to an apk. If we are intent on only hosting "fat" apks then I can do the rename.
Is this only for these hosted files or should the names of apks generated at build time be changed?

**Comment by kelson42** [comment]
@mac I have tried again with Chrome & Firefox with my older and my newer devices... and last nigthlies just install properly :) No clue what happened at that time.

**Comment by kelson42** [comment]
I made an error here by closing the ticket, the naming is still wrong.

**Comment by kelson42** [comment]
> the `3312` is so we have a build number association to an apk. If we are intent on only hosting "fat" apks then I can do the rename.
> Is this only for these hosted files or should the names of apks generated at build time be changed?

This is only for the release ones.

**Comment by macgills** [comment]
@kelson42 I don't think this has a place in a maintenance milestone, I'll be completely redoing this in a GitHub action on 3.2 anyway

**Comment by kelson42** [comment]
ok
