### ISSUE TITLE
Go back home should be easier

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#155]
Recommendations:
Make it so there is only one tap to get back to the main menu. If users are looking for several different items in a row, they will most likely want to go back to the main menu frequently to begin their navigation for the next item starting with the table of contents. 

Perhaps if what is behind the hamburger menu currently is not needed, a wikimed, or other logo could be used as a button to tap to get to the home page. 

Pressing the logo of the website is a well worn mental model for going to a home page.

**Comment by mhutti1** [comment]
Resolved by the bottom bar.
