### ISSUE TITLE
I cant't read the full definitions in the Galician Wikipedia for Kiwix

### ISSUE THREAD

**Issue by henriquehenrique** [kiwix/kiwix-android#1551]
Hello!

I need help with an issue. I have Kiwix installed for two years, now the latest version for mobile phones, I have an Android Phone with Android 4.2.2. 
I use Wikipedia in English, Spanish and Galician. In the Galician version, with the latest Wikipedia, I can't see the full text of the definitions.
This is the version I have (2019-04):
http://download.kiwix.org/zim/wikipedia_gl_all_novid.zim
For instance, when I open the definition for "Galicia" in the Spanish version I can see the full text, but when I open "Galicia" in the Galician version I only can read the first part of the text (before the title Etimoloxía). However, the previous version of the Galician Wikipedia worked fine. I tried touching the word Etimoloxía and the next titles (Símbolos de Galicia, Historia...) to open these parts of the text, but it doesn't work. Could you help me with that issue? 
I suppose the problem could be only in the latest Galician Wikipedia version for Kiwix, but I don't know how to solve it.
Thank you in advance :-)

Henrique

**Comment by kelson42** [comment]
@henriquehenrique Thank you for your report. I need to confirm the problem, but it looks like to me you are confusing the mini version (first section only) with the nopic.

**Comment by kelson42** [comment]
Have tried with the newly generated http://download.kiwix.org/zim/wikipedia_gl_all_maxi.zim and it seems to work fine.
