### ISSUE TITLE
Hotspot URL should be shareable (as a QR code?)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1553]
The URL could also be shown as a qr-code so other people could scan the qr-code and start surfing. Am I right that network connections can be shown as qr-code? Maybe there could be a 2. qr-code for connecting to the local hotspot.
Is it possible to support people who want to post/send the URL, network connection and/or qr-code(s) by messenger? Either it could be copied to clipboard or there could even open an android dialog "To which application do you want to send this data to?"

Since the server is also usable from the local device (mobile phone, tablet...) without starting a hotspot there could be more details about this.
In the dialog "Did you start the hotspot?" there could be a button "No, I want to access it from local device only". Then in the server ip dialog there could be shown http://127.0.0.1:8080 (without qr-code ;) )

This is a follower of #1542

**Comment by suterma** [comment]
I really second this. I also had a hard time finding the note about the IP address. To display it as a QR code is technically simple, just encode the text of the url (eg "http://123.234.454.566:8080") into the QR code. Most QR code readers would automatically open the URL after scanning, or at least offer the option to do so after acknowledgement.

**Comment by kelson42** [comment]
@suterma I agree, Maybe @s-ayush2903 can implement this as well in #2679. Would be really great IMO!

**Comment by s-ayush2903** [comment]
Ah, it _is_ much involved. I believe it'll be better if we can handle this as a follow up in near future and for the time being, think on how we can improve the basic initial implementation.

Also, I think we'll need some design mockup here to think/decide on how to present the QR Code to the user before planning to implement the fix.

**Comment by cdhiraj40** [comment]
hey @kelson42, we can pretty much generate the QR code by using [ZXing](https://github.com/zxing/zxing) library. if this feature can still be added I can show some mockup design on this. maybe fix it?
about sharing the QR code I am not sure if we can do that.
but we can sure share the link(which is already there)
