### ISSUE TITLE
Rename "Host Books" with "WiFi Hotspot" in menu

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1554]
I'm not convinced about the naming of the feature. I think "WiFi Hotspot" is better.

**Comment by kelson42** [comment]
@Popolechien @rgaudin @macgills @mhutti1 What is your opinion? Maybe you have an other proposal?

**Comment by Popolechien** [comment]
I would use an action word that is easy to understand/nontechnical. “Activate hotspot", "Share as hotspot", or simply "Broadcast".

**Comment by kelson42** [comment]
@Popolechien What is behind the menu item is not hotpost activation. It can be hotspot deactivation, or other hotspot related operation ... pretty much like for the "Library".

**Comment by Popolechien** [comment]
@kelson42 I think the wording is most important for new users: once they've tried it they'll know what it does. But we need something that is understandable at first glance (incl. from a screenshot for the store).

**Comment by macgills** [comment]
"Book Sharing"? Conflicts a bit with Local Transfer. "Hotspot Sharing"?

**Comment by iadeelzafar** [comment]
If this was a Bluetooth feature, we'd use **Bluetooth Books**.
Similarly, how about **Hotspot Books**
OR
Something like **Books Server**

**Comment by mhutti1** [comment]
I personally prefer broadcast, but hotspot works as well.

**Comment by kelson42** [comment]
@Popolechien "wifi hotspot" is clearer than just "hotspot" and Im against to put everywhere a verb, this is inefficient IMO.

**Comment by iadeelzafar** [comment]
How about "Broadcast Books"?

**Comment by kelson42** [comment]
What we do is not a broadcast solution.... and this won't be understood by people because broadcast = tv, radio for most of them.

**Comment by iadeelzafar** [comment]
@kelson42  The options i see

1 Wifi Hotspot 
2 Hotspot Books
3 Wifi Hotspot Books

*P.S: I personally like no. 2*

**Comment by yashk2000** [comment]
@kelson42 @macgills can I take up this issue? I think renaming to option to `WiFi Hotstop` or `Hotspot Sharing` is good enough.

**Comment by macgills** [comment]
@yashk2000 if you can prioritise anything in the 3.2 milestone (preferably with `good first issue` tag) that would be ideal. Otherwise this ticket is still awaiting a firm decision

**Comment by kelson42** [comment]
> @kelson42 I think the wording is most important for new users: once they've tried it they'll know what it does. But we need something that is understandable at first glance (incl. from a screenshot for the store).

A few months have passed and I think one other fundamental problem is that if "Stop read aloud" works out because it just stops the TTS, it can not work that way for the the Hotspot, as we need to provide a way as well to the user to configure the hotspot while running.

I still believe that just "WiFi Hotspot" is the best compromise.

**Comment by Popolechien** [comment]
> I still believe that just "WiFi Hotspot" is the best compromise.

I wish we could afford some user testing but for the time being it's still the much clearer option so let's roll with it.

**Comment by karthik-anand** [comment]
Hi. If this issue hasn't been solved yet, can I be assigned to it?

**Comment by kelson42** [comment]
@karthik-anand Yes, "WiFi Hotspot".

**Comment by kelson42** [comment]
@s-ayush2903 As we are approaching the release time, would you be able to quickly fix that one please/
