### ISSUE TITLE
Kiwix Hostpot page should only list books which are served one time hotpost started

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1555]
Currently it lists all books which is IMO a non-sense.

**Comment by kelson42** [comment]
@iadeelzafar not at all

**Comment by abdulwd** [comment]
I think we should gray out the books which aren't being served instead of removing them from the list. This will keep the user informed that those books aren't being served.

**Comment by iadeelzafar** [comment]
@kelson42 i think this can be closed as a duplicate  of #1424
