### ISSUE TITLE
Remember books which are served by Kiwix Hotspot

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1557]
This will avoid to reconfigure everytime.

**Comment by iadeelzafar** [comment]
@kelson42 is this possible duplicate of #1555 ?

**Comment by iadeelzafar** [comment]
@kelson42 I don't get this one. Can you please provide more context..

**Comment by kelson42** [comment]
Beetween two app restarts, the app chosen to be hosted, should be the same, without having to choose again.

**Comment by macgills** [comment]
I still don't understand this feature request. The book selection on the screen should be persisted? Always? Only while the screen is the topmost activity?

**Comment by iadeelzafar** [comment]
From what I understand, Same ZIMs should be hosted everytime unless the user clicks on an Edit button and makes changes to the list of books to be hosted? @kelson42 ?

**Comment by kelson42** [comment]
@macgills yes, the selection should be persisted until user decides differently. It is extremly boring to have at each app relaunch to reselect the books I want to put in the hotspot.
