### ISSUE TITLE
With Android 9, impossible to start hotspot directly from Kiwix

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1558]
We discussed that many time and I was under the impression that with Android 9+ it would be able to start the WiFi hotspot from Kiwix without any additional configuration. It seems it is not :( Any reason?

**Comment by iadeelzafar** [comment]
@kelson42 because we couldn't fix #1432

**Comment by kelson42** [comment]
@iadeelzafar Thank you for the reminder, on a longer term, we will have to find a solution. The workflow is really too complex IMO.

**Comment by kelson42** [comment]
@MohitMaliDeveloper Do you have a device with Android9? Is this still a valid ticket?

**Comment by MohitMaliFtechiz** [comment]
Hi @kelson42 ,
Yes, I have android 9 device. I have tried on android 9 and it's working fine.
