### ISSUE TITLE
Overlapping menus

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#156]
It is possible to open both the dot menu (on top right) and the line menu (on top left) at the same time. On small screens, they overlap. Make it impossible to open both menus at the same time. This is confusing and confuses the focus of the person using the app. Switching one on should switch the other one off.  This will conserve screen space and improve user UX.

**Comment by Albert221** [comment]
It is worth noting, that firstly clicking dot menu and then hamburger (or basically anywhere outside of dot menu) will hide that menu, so the only case we want to handle is when hamburger menu is shown and then  dot menu clicked.
