### ISSUE TITLE
Error toast by starting kiwix

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1564]
The error is only briefly visible, but it says: error loading url....   base/null. This happen just after a fresh reinstall.

**Comment by kelson42** [comment]
@siddharth2010 Might be one for you?

**Comment by weatherman1776** [comment]
I get the same error toast on start.
Error: Loading article (url: content://org.kiwix.kiwixmobile.zim.base/null) failed. 
Library is blank, won't load zim files.

**Comment by kelson42** [comment]
@weatherman1776 I my case this is just a misleading error message. All the rest works fine.

**Comment by devilmonk** [comment]
Is this issue resolved? Or is anyone working on it?

**Comment by kelson42** [comment]
@devilmonk yes and yes (see PR).
