### ISSUE TITLE
Local library refresh fails to detect a new Zim file in Downloads directory

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1565]
I just have downloaded a new Zim file with firefox on my Pixel2 with Android10. The download has been Ok and the file is in the Downloads directory. Unfortunately, the local library tab, even after forcing a refresh does not list it as part of available Zim files.

**Comment by macgills** [comment]
I downloaded a zim from chrome, did a swipe to refresh and it was found. Android10 emulator.

**Comment by kelson42** [comment]
The pb is again with mawsouaa_ar_all_2019-09.zim. I have tried with an other Zim file it has been detected properly... But mawsouaa_ar_all_2019-09.zim is still missing. Either there is a problem with this specific Zim file or the code is not robust.

**Comment by macgills** [comment]
can you post the link here so I can click on it from the emulator?

**Comment by macgills** [comment]
`mawsouaa_ar_all_2019-09.zim` was detected after I downloaded it from https://ftp.acc.umu.se/mirror/kiwix.org/zim/other/mawsouaa_ar_all_2019-09.zim

Cannot reproduce. I will have access to a Pixel3a running 10 outside of office hours and I can make some attempts then on these assorted 10 issues I can not repro. Unless another developer has a device they can repro on

**Comment by kelson42** [comment]
Need to further investigate...

**Comment by kelson42** [comment]
@macgills Tested again with last nightly... and works fine.
