### ISSUE TITLE
Bookmarks not readable in nightmode

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#1573]
**Describe the bug**
If I switch to night mode the bookmarks are white text on white background. Is the background left in day mode and the text is switched to night mode?

**Expected behavior**
The text should be white and the background should be black or grey like the layout of the settings menu in night mode.

**Steps to reproduce the behavior:**
1. make sure you have a bookmark
2. switch to night mode or use auto night mode and slip under the covers.
3. try to read the bookmark list

**Environment**
- Version of Kiwix Android : 
3.0.4 Build: 230004 release and nightly from 2019-10-27 [3423-universal-debug.apk](https://download.kiwix.org/nightly/2019-10-27/3423-universal-debug.apk)
- Device : Samsung Galaxy S5 SM-G900F i9300
- OS version : lineage_klte-userdebug 9 PQ3A. 190801.002 750bd77430

**Comment by kelson42** [comment]
@JensKorte Thank you for your bug report. We have various bugs related to the night/dark mode. The reason behind is a weak global mgmt of this feature, in particular in relation to the Android OS own Dark mode. We are aware of the problem, and the whole problematic will be treated within the milestone 3.1 (so the one currently in development).
