### ISSUE TITLE
Red border are annoying.

### ISSUE THREAD

**Issue by geekRishabhjain** [kiwix/kiwix-android#1576]
I don't know if only I feel it, but the red borders that appear when you click anything are very annoying.
If they are intentional, then there should be some button in settings to turn them off. For me they are annoying.

**Describe the bug**
The red border that appears whenever you click anything.

**What should it be**
Either they should be shut off, or there should be some option in settings to turn them off.

**Comment by kelson42** [comment]
@geekRishabhjain Which version of the app are you using? Self-compiled?

**Comment by geekRishabhjain** [comment]
Yes. It is:
```
Version
3.0.4 Build: 5230004
```

**Comment by kelson42** [comment]
@geekRishabhjain We don't have this on Google Play versions of the app. I'm quite sure this is either related to a dev versin or due to the Android developer mode. @macgills Could you confirm please?

**Comment by macgills** [comment]
This is only on develop and a gentle reminder to developers that they are violating strict mode, logs can be checked for what rule is being violated. Not an issue.

**Comment by geekRishabhjain** [comment]
@macgills I am sorry if I did something wrong. Can I know what is strict mode? And What log I have to check? I am really sorry if I was did something wrong.

**Comment by macgills** [comment]
You did nothing wrong, the app just does a lot of wrong stuff, most of it inconsequential.
See CoreApp where this gets installed
```
  private StrictMode.ThreadPolicy buildThreadPolicy(StrictMode.ThreadPolicy.Builder builder) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
      builder.detectResourceMismatches();
    }
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      builder.detectUnbufferedIo();
    }
    return builder.detectCustomSlowCalls()
      .detectDiskReads()
      .detectDiskWrites()
      .detectNetwork()
      .penaltyFlashScreen()
      .penaltyLog()
      .build();
  }
```

StrictMode can also be enabled in Developer Settings for all apps.

Open logcat in Android Studio and you will see there is a corresponding "StrictMode Violation" for every flash

**Comment by geekRishabhjain** [comment]
@macgills I thought that we have some "strict mode" in our project. Thanks BTW.
