### ISSUE TITLE
Remove dagger-android

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1581]
**Is your feature request related to a problem? Please describe.**
dagger-android adds complication and is no longer being supported as google have decided it is not fit for purpose as announced [last week](https://youtu.be/o-ins1nvbDg?t=539)

**Describe the solution you'd like**
Replace all usages

**Describe alternatives you've considered**
Just continue with the deprecated library

**Comment by kelson42** [comment]
@macgills What are the replacement candidates?

**Comment by macgills** [comment]
Plain old Dagger, `dagger-android` is a module that tried to remove boilerplate but came with its own issues

**Comment by jhbiggs** [comment]
I'm ready to work on this one if you'd like.

**Comment by kelson42** [comment]
@jhbiggs Thank you
@macgills Do you think this is something doable for @jhbiggs? Do you have important advices to share here?

**Comment by macgills** [comment]
Dagger is inherently quite complicated, I am happy for jhbiggs to do it and will offer guidance but I don't know their familiarity with the core concepts.

**Comment by kelson42** [comment]
@jhbiggs I allow myself to write that probably #1173 would be more adapted to you.

**Comment by jhbiggs** [comment]
Ok, good to know. I was hunting for a meat-and-potatoes issue. I’ll have a look.  

I’m currently about 1/2 through #1581.  Thought I was almost done but noticed the SearchActivity has deep roots in Dagger-Android in app and not core. I have Core working without dagger-Android now except for the SearchActivity.

**Comment by jhbiggs** [comment]
So I pushed a 1581 branch, I'm hopeful that you @macgills could please have a look and let me know if I'm totally off base.  I didn't run git hooks because there is plenty of work left to do and the commit would fail.  I hope that's ok.

**Comment by macgills** [comment]
@jhbiggs that is okay, I'll have a look, I am just working my way through notifications right now but you can always open a PR in draft (and tag me) to get my feedback

**Comment by macgills** [comment]
fixed in #1700

**Comment by kelson42** [comment]
@jhbiggs @macgills Well done
