### ISSUE TITLE
Remove CHANGE_NETWORK_STATE useless permission

### ISSUE THREAD

**Issue by 4tip** [kiwix/kiwix-android#1582]
**Describe the solution you'd like**

Could you please make the Kiwix app more privacy friendly and delete the following permissions?:
- approximate location (network-based)
- change network connectivity

They seem, to me, unnessecary for the app to work, anyway, especially the first one.

I'd be happy if you consider this and answer me.

Best regards

**Comment by kelson42** [comment]
@4tip I strongly suspect these permissions are really needed.. but could someone confirms why exactly?

**Comment by macgills** [comment]
I would believe the location would relate to our book sharing options, ie hotspot & WifiP2P. My hypothesis is scanning for nearby wifi devices could leak the users location so we have to request the coarse location permission even though we are not trying to get the users location.
I can run a quick experiment and report back with my findings

**Comment by macgills** [comment]
`CHANGE_NETWORK_STATE` can probably be removed I would say

**Comment by 4tip** [comment]
> 
> 
> `CHANGE_NETWORK_STATE` can probably be removed I would say

Could you remove it directly and release a new Kiwix version called 3.1.0 or 4.0.0 today?

**Comment by kelson42** [comment]
OK, so let's remove `CHANGE_NETWORK_STATE` in 3.1.

**Comment by jhbiggs** [comment]
In core/src/main manifest Android Studio gave me an error on android:exported="true", recommending with a red light bulb to change to false.  So I did.  Other than that there was just the one deletion of the CHANGE_NETWORK_STATE permission.

**Comment by 4tip** [comment]
> 
> 
> In core/src/main manifest Android Studio gave me an error on android:exported="true", recommending with a red light bulb to change to false. So I did. Other than that there was just the one deletion of the CHANGE_NETWORK_STATE permission.

The CHANGE_NETWORK_STATE permission is not needed, so you may delete it.

**Comment by 4tip** [comment]
Please release a new version of Kiwix called 3.1 as soon as you have deleted the permission (even if you have no other updates to the app or bugfixes to include).
