### ISSUE TITLE
possible cause of slow search

### ISSUE THREAD

**Issue by I338** [kiwix/kiwix-android#1585]
I don't know if the cause for the slow search in kiwix is known, but I noticed that it scales rapidly with the number of search results found. If I paste a highly specific search term that only has one article related to it, the search loads almost immediately, but if there are many results, it can take upwards of a minute.

**Comment by kelson42** [comment]
@I338 There is nothing much we can do here with this ticket. If you experienced a bug, a slow search experience... Please the open a bug with all the details.
