### ISSUE TITLE
wikipedia_en_all_nopic_2019-10.zim does not appear listed on Android list of contents

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1586]
Looking at the available content in the library, I realize that the latest nopic version is not listed. Nor, as a matter of fact, if the Maxi one (wikipedia_en_all_maxi_2018-10.zim)

Am on Android 3.0.5

**Comment by macgills** [comment]
There is a possibility that it is filtered out temporarily while we try to detect the filesystem of your preferred storage, assuming this is over 2GB

**Comment by Popolechien** [comment]
Yeah, but I've got plenty of space and, _fun fact_, I get the exact same issue (no Wikipedia all_maxi, no all_nopic; I do get Top_maxi though) with other languages (French, Dutch, Arabic, Spanish). Waited for about 5 minutes with multiple refreshes, to no avail.

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/68662942-b49fd280-0535-11ea-944f-11a6ddc40c99.png)
The trick here is to just stay on the library screen an awfully long time. FileSystem detection varies in quality depending on the sd card as we try to write a 2GB file, some filesystems support doing this instantaneously, others require you allocate each byte

**Comment by macgills** [comment]
change storage of off sd card and you should see all files, if you have more than 2GB on your phone

**Comment by Popolechien** [comment]
Ok, this fixed the issue insofar as the files have now appeared, but this is odd as I had 17Gb listed as available on internal storage and one of the missing wikis was 4.4Gb.

**Comment by macgills** [comment]
Local files have different rules to the online list. there is a ticket to gray out items we think cannot be downloaded instead of hiding them
