### ISSUE TITLE
Problem with table visualisation (Wikimed / arabic)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#16]
The table appears cut (see image) and it is not possible to move around to see what's missing (in this example the Arabic article for Tropin). 
![screenshot_20170307-230220](https://cloud.githubusercontent.com/assets/21675885/23700491/3935ff20-03f3-11e7-94bd-20c1b5475abc.png)

**Comment by kelson42** [comment]
@Popolechien I strongly suspect that the situation is better now that we use the mobile view.

**Comment by Popolechien** [comment]
Well I just downloaded WikimedAr and mobile view does not seem enabled. 
File version indicates 2016-07 Build 3 :-/

**Comment by kelson42** [comment]
You should test with this file https://download.kiwix.org/zim/wikipedia/wikipedia_ar_medicine_2018-01.zim

**Comment by Popolechien** [comment]
yup works fine now. Let's just update the app then. Thanks.
