### ISSUE TITLE
Move Tabs in Download Content view to bottom bars

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-android#160]
In the download view:
![](https://i.imgur.com/7zxS8d8m.png) 

Convert the tabs to bottom navigation: https://material.io/guidelines/components/bottom-navigation.html

**Comment by dhirajj75** [comment]
@rashiq  You want to say that you want the three tabs  Device Online Downloading above the navigation. Am I right?

**Comment by dhirajj75** [comment]
can I work on this?

**Comment by brijeshshah13** [comment]
@dhirajj75 I think this is quite a big issue because just moving the tabs to bottom bars using `BottomNavigationView` won't make much of a difference. The whole UI for the download management should be improved and thus can be a part of the GSoC application. @mhutti1 What are your views?

**Comment by mhutti1** [comment]
Yeah I am going to close this for now as it is part of a larger issue that will get resolved separately.

**Comment by dhirajj75** [comment]
Yeah. I have seen this project on GSoC'18 project ideas aiming to change the whole user experience!
