### ISSUE TITLE
Move ZimHostActivity to app module

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1600]
**Is your feature request related to a problem? Please describe.**
Custom apps should not be allowed to host books

**Describe the solution you'd like**
Move zimHosting to app module

**Comment by kelson42** [comment]
@macgills What is exactly the current problem of having this feature in the custom app?

**Comment by macgills** [comment]
They could only host one file and the feature would have to be altered to support obb files.

**Comment by kelson42** [comment]
@macgills What exactly the problem with the obb, really surprised it does not work ou of the box?

**Comment by macgills** [comment]
Because they are not zim files. We do not add them the same way. Zim files get added to a database when we download/detect them and that database is what powers many screens that allow for viewing zim files.
It is certainly possible to implement but it doesn't seem to me like a feature we want in custom apps as a custom app is simply a browser for one book, in my current understanding

**Comment by kelson42** [comment]
Even if we have only one book, I would prefer to have the wifi hotspot working for it. This is not a priority.

Considering that the obb is only a zim file with another file extension, I don't believe/understand we use the libkiwix differently. I guess the current incompatibility comes from Java/Kotlin code, but here again it is not fully clear why this use case is different from loading a random ZIM file.

Therefore, I believe that the fix could happen by rethinking a few things in the Java/Kotkin code and the feature should as a consequence stay in core.

I would recommend to mask only the feature for now in custom apps and open a ticket to properly analyse/implement the feature for custom apps as as well.

@macgills Does that make sense to you?

**Comment by macgills** [comment]
We would have to entirely rework the UI, it would look less than stellar with only one book and no way to add more from its current name "Host Books", the selections ui, all dead space

**Comment by kelson42** [comment]
@macgills Thx for confirming this is only a UI Java/Kotlin issue. And "yes" there is only one book in the library. I'm not sure to fully understand the problem here. This UI needs anyway to be improved (a few tickets are already open), so this is probably one of the things to improve. Please just open the ticket to reintroduce the feature, if you remove it for now in custom apps. How you deal with the temporary solution, does not really matter to me, just hiding the menu item seems easier to me, but if you are not afraid to re-introduce the feature to core later, no problem to me :)

**Comment by macgills** [comment]
Well it raises a lot of questions for the user.
"Why can I deselect the book"
"why does the ui talk about multiple books"
etc

The screen would be clearer with an icon of the custom app and a button "start hosting" or something equally simplistic.

I had done 99% of the work by your first comment so I have opened a PR that moves it to app.

If we want a different UI for custom then in the future I will have to move a few classes back.

If we want to reuse the same UI I will have to move the entire thing back, more or less.
