### ISSUE TITLE
Reintroduce Hotspot feature in custom apps

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1602]
It has been removed because of #1600

**Comment by Kshitij0910** [comment]
Hello! May I know what exactly has to be done in order to solve this issue and how to proceed as well?

**Comment by Rishavgupta12345** [comment]
Hello! May I know what exactly has to be done in order to solve this issue and how to proceed as well?

**Comment by kelson42** [comment]
@MohitMaliFtechiz How much work would that be?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 It does not need so much work, as @gouri-panda said **"_We have to revert some changes i.e move some functionality to core and change some things according to Kiwix app and custom apps. Also UI for one book(custom apps) and multiple books._"** It might take a few hours to get the functionality back in custom apps, but after implementing we will need to modify/create our test cases to properly test the UI/functionality.

**Comment by kelson42** [comment]
@MohitMaliFtechiz OK, somlets do it now
