### ISSUE TITLE
Travis CI Issues

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1609]
**Describe the bug**
All pull requests have a non completing check from travis CI, also builds cannot be rerun by clicking `re-run checks`

**Expected behavior**
Builds should be able to be re-run and PRs should not have a non completing check

**Steps to reproduce the behavior:**
1. Open a PR

**Comment by kelson42** [comment]
I confirm... will try to have a look

**Comment by kelson42** [comment]
@macgills I might have fixed that pb by tweaking travis-ci perms in settings>branches. Could you please confirm it works now?

**Comment by macgills** [comment]
The non completing check is gone, I don't know if we can re-run builds

**Comment by kelson42** [comment]
This has been fixed
