### ISSUE TITLE
Stop using translation for BottomToolbar and programtically set HideBottomViewOnScrollBehavior based on preference

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1611]
**Describe the bug**
Add enough books so that you would have to scroll the screen, scroll the screen as far as possible, see final list item only showing half of its content

**Expected behavior**
All content can be scrolled into view

**Screenshots**
![image](https://user-images.githubusercontent.com/3358282/70065212-9da74a00-15e2-11ea-92fb-44f36e430aad.png)

**Environment**
- Version of Kiwix Android : develop
- Device : Nexus 5x
- OS version : 8.1.0

**Comment by macgills** [comment]
We should remove the nested scrollview and only use recyclerview

**Comment by devilmonk** [comment]
I want to work on it if someone tells me: what part of code what changes I have to make.

**Comment by kelson42** [comment]
@devilmonk Great :)

**Comment by macgills** [comment]
@devilmonk CoreWebViewClient:133 `inflateHomeView` is what is adding this view, it calls a callback which attaches the adapter/data to the recyclerview, MainActivity:1663 `setHomePage`

**Comment by devilmonk** [comment]
@macgills Thanks

**Comment by macgills** [comment]
The initial solution proposed would not work, I have updated the title to reflect that

**Comment by kelson42** [comment]
@devilmonk Are you actually working on that ticket?

**Comment by macgills** [comment]
The complexity of the task has risen somewhat, the view hierarchy needs updating to support a Coordinatorlayout to handle the scrolling behaviour and `activity_main` is non trivial.

The complexity comes from the implementation of our current scrolling behaviour being a custom implementation via 2 subclasses `ToolbarScrollingKiwixWebView` and `ToolbarStaticKiwixWebView` instead of being behaviour driven by androidx classes.
`ToolbarScrolling` hides top & bottom on scroll down, shows on scroll up.
`ToolbarStatic` keeps the top & bottom onscreen at all times.

I personally don't see much reason in having these 2 separate behaviours, my expectation of scrolling reading content in an app is when I scroll down the controls (top & bottom) should hide to give the content maximum space and that these controls should reappear on scroll up. I would believe this to be standard browser behaviour? I can't find it in chrome

The ticket number in the commits for this feature do not match up to the github issues, they are from 2017, so I can't see the original intent.

**Comment by macgills** [comment]
@kelson42 are you happy to remove the feature of "static" toolbars?

**Comment by kelson42** [comment]
@macgills Good to me.

**Comment by macgills** [comment]
@kelson42 I am hitting something of a roadblock. I think the time needed to fix this properly is quite large and would incur a significant rewrite of CoreMainActivity and is probably out of scope for this milestone

**Comment by kelson42** [comment]
OK, I descope it.

**Comment by Frans-Lukas** [comment]
Going through old tickets, can this be closed @macgills ?

**Comment by macgills** [comment]
yup!
