### ISSUE TITLE
"Delete notes" alert buttons are not displayed properly

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1614]
This kind of dialog should be standard.

![Screenshot_20191205-124556](https://user-images.githubusercontent.com/1029718/70232866-a708f180-175d-11ea-96ee-c0aa93880407.png)

**Comment by macgills** [comment]
If this isn't working then all the dialogs should not be working, can you verify with "clear history" for example?

**Comment by macgills** [comment]
Also an android OS version would be helpful here as I suspect it is that

**Comment by kelson42** [comment]
"Clear history" works fine. Android 10, Google Pixel2

**Comment by kelson42** [comment]
@macgills I got that with the last "wikimed" alpha version.

**Comment by macgills** [comment]
on a 10 emulator with latest develop the buttons appear for me, I would say that this is no longer an issue post our theme update for the night mode. Closing

**Comment by kelson42** [comment]
@macgills I confirm it looks better now that we compile against `develop` branch.
