### ISSUE TITLE
Error displayed behind authorization request

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1618]
A full black or white background should be preferred.

![Screenshot_20191206-143057](https://user-images.githubusercontent.com/1029718/70326670-5f559900-1835-11ea-93ca-ae7363327bbb.png)

**Comment by macgills** [comment]
What are the repro steps? What device? What OS? This is a custom app? This is a custom app with an obb or download fallback?

**Comment by kelson42** [comment]
1 - install wikimed custom app (the new one)
2 - launch it
3 - you get the screenshot I have posted with the error
