### ISSUE TITLE
Replace the spinner with a SwipeRefreshLayout in the Download Activity

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-android#162]
Add a [SwipeRefreshLayout](https://developer.android.com/training/swipe/add-swipe-interface.html) to replace the Spinner in both the online library and the local library of the Get Content section of kiwix. This will improve our adherence to the google UI style.
![](https://i.imgur.com/HveJiTZm.png)

**Comment by mhutti1** [comment]
This should be done for both the device and online fragments.

**Comment by divadsn** [comment]
As I'm working on that task, I am thinking about removing the "progress bar" thing, as it looks weird to have both things displayed.

**Comment by mhutti1** [comment]
@divadsn Yeah lets remove the current progress bar as part of this.

**Comment by divadsn** [comment]
Ok, great! I also removed some unused menu items, those changes are already on my repo. Will do some testing and make a PR after I removed the progress bar.
