### ISSUE TITLE
"Read aloud" seems completly broken with `develop` branch

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1620]
Testing with the Wikimed custom app, I never get a sound. For the rest the feature seems to work.

**Comment by macgills** [comment]
Seems it is zim file dependent, investigating further

**Comment by macgills** [comment]
checked the logs and onError is being hit
```
        tts.setOnUtteranceProgressListener(new UtteranceProgressListener() {
          @Override
          public void onStart(String s) {

          }

          @Override
          public void onDone(String s) {
            int line = currentPiece.intValue();

            if (line >= pieces.size() && !paused) {
              stop();
              return;
            }

            tts.speak(pieces.get(line), TextToSpeech.QUEUE_ADD, params);
            currentPiece.getAndIncrement();
          }

          @Override
          public void onError(String s) {
            Log.e(TAG_KIWIX, "TextToSpeech Error: " + s);
            //TODO: Surface to user
          }
        });
      }
    }
```

the error is absolutely useless though as it is just an id we passed in to the system earlier. We can implement the TODO but I am not seeing an easy way forwards with this, TTS seems [incredibly flaky](https://stackoverflow.com/questions/55080063/android-texttospeech-behaves-irregular)

**Comment by kelson42** [comment]
@macgills Do you mean you can not get it working at all?

**Comment by macgills** [comment]
It works right now on `Granblue Fantasy Wiki` for example, I have little experience with TTS but from a quick browse of the code I can't see a glaring error. It bears more investigation but I am giving a heads up that this might be a real tricky one

**Comment by kelson42** [comment]
@macgills OK, I would start from my bug report - with Wikimed. If you test something different, then that does not make the investigation easier.

**Comment by macgills** [comment]
Testing includes verification, verifying it works in some scenarios is a huge insight because it narrows the field of possible problems from "seems completely broken" down to "broken for some zims".

It being a custom app has no bearing on the functionality

**Comment by kelson42** [comment]
@macgills It is just an advice. As long as we don't understand from which part of the software the problem comes from, I would start from the problem itself instead of guessing things (for example, that it won't work with any ZIM file). If you are sure the custom app does not play any role, then at least play with the same ZIM file. But again, this is only an advice, I just does not want to open a new discusion about an other ZIM file.

**Comment by macgills** [comment]
I verified it worked in the main app with the same file so seeing as the problem is not the content, it is in fact the custom app. I believe it to be associated with the language enforcing

**Comment by kelson42** [comment]
@macgills Yes, a bit of info I remember which might help. The TTS system needs at some point to be initialized with a language (a voice need to be chosen). This language should come from the ZIM file itself... but the meta data coming from the ZIM file might not be exactly in the format taken by the TTS system, so a transformation might be needed.
