### ISSUE TITLE
Night mode does not always apply properly on pictures

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1625]
Dark mode does no apply properly on pictures just after:
- App's restart (after been properly removed from memory) in night mode
- After switching on the night mode and exiting settings

see for example:
![Screenshot_20191208-171713](https://user-images.githubusercontent.com/1029718/70392326-3d981580-19df-11ea-9048-2f67d2754fb7.png)

Further page loadings are OK

**Comment by macgills** [comment]
I don't see the problem with this image?

**Comment by kelson42** [comment]
This bug report is buggy indeed! But there is a problem of this order. This is how it looks like just after having changed from dark -> light in the settings. See screenshot.
