### ISSUE TITLE
Categories/Tags in Download Books don't make sense (to me)

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#1632]
**Describe the bug**
I downloaded 3.1.0 from the homepage and want to select a ZIM file. All my files get the tags Pic, Vid, Text Only, and Short Text Only.  I don't understand how the tags are meant. I prefer the big german version with Pics. This version has no Vids. Why do Pics and Vids have the same color?
PS: I clicked on Download Books and then selected the local device.

**Expected behavior**
The tags should fit to the files or maybe marked with a "?" if kiwix can't decide it. If the tag doesn't fit, additionally the text should be stroke.

**Steps to reproduce the behavior:**
1. new installation from download.kiwix.org
2. Select local ZIM file 
´
**Environment**
- Version of Kiwix Android : 3.1.0 from download.k.o
- Device : Samsung Galaxy S5
- OS version :  recent lineageos

edit: see also #1636

**Comment by kelson42** [comment]
@JensKorte I guess what happen here is that you have old Zim files which don't have the new tags. Per default, they have all tags.
@macgills "short text" and "text" should not be active together. If not specified, "short text" should've inactive.

**Comment by JensKorte** [comment]
@kelson42 I have old files, like WP en 2018-10-24 78GB. But the WP de 2019-08-07 34GB is quite fresh.

**Comment by kelson42** [comment]
@JensKorte Files older than october don't have the proper tags... there will be unfortunately a transition period.

**Comment by JensKorte** [comment]
@kelson42 Can the e.g. WP de from 2019-08-07 modified with only few work? Like changing/adding headers?

**Comment by macgills** [comment]
Hmm curious, I put in code to hide the tags for books with improper tag data, it is clearly not working.

I will address this today but 3.1.1 release to beta may be next week as we look to resolve another issue

**Comment by macgills** [comment]
A very dumb error by myself `==` instead of `=`. Tags will now be hidden. Probably time to install detekt on the project, I am surprised our checks didn't catch this.

On the design of tags:
![image](https://user-images.githubusercontent.com/3358282/70609716-2e40e400-1bfa-11ea-8141-8cec34f0b763.png)

All tags are always present, the tags are activated/deactivated by the presence/absence of tag data for the content.
The supported tags as of right now are `pictures=yes|no` `videos=yes|no` `details=yes|no` and we infer from there whether to activate a tag

**Comment by macgills** [comment]
@JensKorte I have created a PR which will close this issue.

If you wish to open a new feature request to discuss the design of tags ie should be hidden if not present, should have different colors, strikethrough text for deactivated tags. I think that issue should be place for that discussion

**Comment by kelson42** [comment]
@JensKorte no
