### ISSUE TITLE
App becomes unresponsive in the library

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1634]
... if I click on the icon in the top right corner of this screenshot. I have no clue what should happen.
![Screenshot_20191211-065049](https://user-images.githubusercontent.com/1029718/70595170-f7130880-1be2-11ea-8287-795f82b8eed7.png)

**Comment by macgills** [comment]
This is my fault for removing a permission, I tested this but must not have uninstalled inbetween testing so the permission, though no longer requested in the manifest, was already granted? That is my theory anyway
