### ISSUE TITLE
If the ZIM file tag (Vid,Pic) doesn't fit, additionally the text should be stroke.

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#1636]
**Is your feature request related to a problem? Please describe.**
#1632 
I was confused about the colors with non tagged files. If the text would be stroked the color usage would be clear, even if there happens a bug.

**Describe the solution you'd like**
e.g.: ~Vids~

**Comment by kelson42** [comment]
This is a typical 3.2 decision

**Comment by macgills** [comment]
@kelson42 I think this is up to you. I am not too swayed on any option be it strikethrough, simply hiding or more prominent coloring/transparency

**Comment by kelson42** [comment]
I'm not in favour of strickin anything, but maybe we should not display the tags which are not "active".
