### ISSUE TITLE
Improve global state of WebViews

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-android#164]
Right now we keep a strong reference to all WebViews which can leak memory. Create a container that is wrapped in a WeakReference and provides all WebViews through dependency injection via dagger.

All the WebViews right now are tracked in the KiwixMobileActivity:

    private List<KiwixWebView> mWebViews = new ArrayList<>();

**Comment by kelson42** [comment]
@macgills @mhutti1 Still a valid ticket?

**Comment by macgills** [comment]
this shouldn't cause a memory leak. Without a LeakCanary report I am inclined to just close it
