### ISSUE TITLE
Corrupt application dialog appears after installing app.

### ISSUE THREAD

**Issue by ShivamPrajapati-dev** [kiwix/kiwix-android#1643]
**Describe the bug**

When I clone the repository and then install it into my phone with android 9.0, the application fails to install with a 'corrupt application dialog opened'. And it suggests downloading the app from play store.

**Screenshots**

![Screenshot_2019-12-15-15-49-38-49_c4696a07e91bd7d7377775a7de880950](https://user-images.githubusercontent.com/53396008/70861415-9291d980-1f53-11ea-8420-8b8b44e7f056.png)

**Environment**
- Version of Kiwix Android : 
- Device : Realme u1
- OS version : Android 9.0

**Comment by kelson42** [comment]
@ShivamPrajapati-dev Thank you for reporting this bug. We are really interested to investigate it. Do you use the beta version of this app https://play.google.com/apps/testing/org.kiwix.kiwixcustomwikimed ?

**Comment by kelson42** [comment]
Same as #888?

**Comment by ShivamPrajapati-dev** [comment]
> @ShivamPrajapati-dev Thank you for reporting this bug. We are really interested to investigate it. Do you use the beta version of this app https://play.google.com/apps/testing/org.kiwix.kiwixcustomwikimed ?

No, I am just using the cloned version from Github.

**Comment by kelson42** [comment]
@ShivamPrajapati-dev Ok, sorry I misread your report. You will get an answer to your request on Monday.

**Comment by macgills** [comment]
This is the custom app. If you want to use kiwix please follow the instructions on the readme

```
Kiwix-Android is a multi-module project, in 99% of scenarios you will want to build the app module in the debug configuration. If you are interested in our custom apps they have their own repo kiwix-android-custom that goes into further detail
```

Seeing as we don't actually use this string anymore I would also guess you are on `master` branch and not `develop`? It should be gone on both actually so outdated anyway

**Comment by kelson42** [comment]
@macgills Thank you. Closing the ticket as question is answered.

**Comment by ShivamPrajapati-dev** [comment]
If I want to contribute then, how can I test the application?

**Comment by ShivamPrajapati-dev** [comment]
@macgills

**Comment by macgills** [comment]
make sure you are using the latest version of develop.
>build the app module in the debug configuration

![image](https://user-images.githubusercontent.com/3358282/71071048-cd725800-2173-11ea-92a9-c708cc774a06.png)

**Comment by ShivamPrajapati-dev** [comment]
I had done those things, but that 'corrupt application' dialog appears again and again. Because of that, the app is unable to open. @macgills

**Comment by ShivamPrajapati-dev** [comment]
Yeah thanks, @macgills, it worked.
