### ISSUE TITLE
Open search results in a new tab

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#1648]
We should add a feature to allow users to open searches in a new tab on long click.

**Comment by kelson42** [comment]
Sounds a good idea. Is that a standard/recommended gesture?

**Comment by mhutti1** [comment]
I would assume a long click.

**Comment by macgills** [comment]
In chrome it does nothing unless the item is a history item in which case it prompts me to remove it

**Comment by mhutti1** [comment]
Hmm, I do think its useful functionality though.

**Comment by macgills** [comment]
A button would be more explicit I think, long clicks are hidden superuser features for the most part.
But then would we need to differentiate between open/open in tab? Probably if it just an icon to the right that is enough visual information to show it as a separate action from just clicking on the list item, we just need a good "new tab" icon then

**Comment by mhutti1** [comment]
Yes that sounds sensible.

**Comment by jhbiggs** [comment]
May I work on this while I wait for feedback on dagger-android removal?

**Comment by kelson42** [comment]
@jhbiggs Any feedback on this ticket?

**Comment by jhbiggs** [comment]
Hi @Kelson, I have been working but it has been slow. I’m fine to give this issue up if you need a quicker completion. 

>

**Comment by kelson42** [comment]
@jhbiggs Great, no this is not super urgent.

**Comment by jhbiggs** [comment]
/unassign
Hi, sorry everybody, I just can't commit time to this assignment.

**Comment by kelson42** [comment]
@jhbiggs No problem, hope to see you back soon!

**Comment by briancherin** [comment]
I've spent some time working on this and will make a pull request soon. It'd be great if I could be assigned to this issue.

**Comment by kelson42** [comment]
@briancherin Thank you for your work. We will try to review your PR soon.
