### ISSUE TITLE
SVG images donot render properly in night mode

### ISSUE THREAD

**Issue by zzndb** [kiwix/kiwix-android#1649]
**Describe the bug**

SVG images donot render properly in night mode, such as a just black text svg image you just can see black space in night mode.(see image below

**Expected behavior**

Maybe should invert SVG image color in night mode.

**Steps to reproduce the behavior:**

Just switch to night mode read some page use just black SVG image.

**Screenshots**

![Screenshot_20191217102507](https://user-images.githubusercontent.com/20870493/70960957-7a3cce80-20bb-11ea-85dc-394c6018cae6.jpg)
![Screenshot_20191217102416](https://user-images.githubusercontent.com/20870493/70960967-80cb4600-20bb-11ea-8713-2876a716aab0.jpg)

**Environment**
- Version of Kiwix Android : 3.1.2
- Device : Redmi K20 Pro
- OS version : 10

**Comment by kelson42** [comment]
@zzndb Thank you for your bug report, could you please tell us which content and which article your screenshots are from?

**Comment by zzndb** [comment]
> @zzndb Thank you for your bug report, could you please tell us which content and which article your screenshots are from?

the image from English Wikipedia `AVL tree` entry `Balance factor` section with landscape screen.

**Comment by kelson42** [comment]
@zzndb This picture is (in the ZIM) a PNG (see http://library.kiwix.org/wikipedia_en_all_maxi/I/m/AVL-tree-wBalance_K.svg.png). This is a bug in the scraper (not in Kiwix Android). Here is the duplicate ticket on MWoffliner side https://github.com/openzim/mwoffliner/issues/1026

**Comment by zzndb** [comment]
> @zzndb This picture is (in the ZIM) a PNG (see http://library.kiwix.org/wikipedia_en_all_maxi/I/m/AVL-tree-wBalance_K.svg.png). This is a bug in the scraper (not in Kiwix Android). Here is the duplicate ticket on MWoffliner side [openzim/mwoffliner#1026](https://github.com/openzim/mwoffliner/issues/1026)

I know this file is a png file 
![Screenshot_20191217150318](https://user-images.githubusercontent.com/20870493/70972723-fb598d00-20de-11ea-9baf-fb267587cdef.jpg)
I can see it from the right corner. 

BUT

I mean these SVG files (there are all SVG files which can confirm from kiwix save media or online wiki page

![图片](https://user-images.githubusercontent.com/20870493/70972955-95b9d080-20df-11ea-82c8-16162bca4b40.png)

**Comment by macgills** [comment]
@kelson42 We do not invert the colors on svg tags currently, this can be fixed if the content is in a `svg` tag

**Comment by macgills** [comment]
Read the linked issue, nothing to be done on the android side for the general case. We preserve the original colors of images in night mode - otherwise they would look like negatives for most of the content - and it just so happens that the design of this site is not night mode friendly as their images (here images of black text) cannot contrast on a dark background.

There is the slight possibility of advancing our CSS injection,
```
<span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle \int _{a}^{b}f(x)\,dx}">
  <semantics>...</semantics>
</math></span><img src="../I/m/ac02adeed584466d53dee65f3228ad66939eb58b.svg" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -2.338ex; width:11.139ex; height:6.343ex;"></span>
```

we can target spans with the class `mwe-math-element` with inversion and that would allow us to solve this scenario but this would be a Wikipedia exclusive fix I'd imagine

**Comment by macgills** [comment]
Achievable like so
```
        span.mwe-math-element > img {
          -webkit-filter: invert(0); 
          filter: invert(0); 
        }
```
![image](https://user-images.githubusercontent.com/3358282/70996697-3c47a680-20cb-11ea-893c-595053ec0542.png)

Note I was using Mathematics by Wikipedia, at this time cannot guarantee the same span class is used in Wikipedia maxi but I would imagine it is

**Comment by zzndb** [comment]
@macgills maybe not elegant, but provide a switch to let user choose maybe can take into consideration.

**Comment by kelson42** [comment]
OK, we have the problem with SVG with transparent background as well. Still openzim/mwoffliner#1026.

**Comment by macgills** [comment]
@zzndb unfortunately we will not support this fix in the android app but thank you for the report

**Comment by endolith** [comment]
So what is the solution for the reader?  We just cannot use night mode on articles that contain math?  :(

**Comment by endolith** [comment]
Normal mode works:


![Screenshot_20211207-165400_Kiwix](https://user-images.githubusercontent.com/58611/145139421-79c76b96-1ebc-4461-bf69-dc0bab44ec9b.jpg)

Night mode is unreadable:


![Screenshot_20211207-165432_Kiwix](https://user-images.githubusercontent.com/58611/145139420-9d3c785d-3208-448b-ba52-af58c5d5241b.jpg)

**Comment by Mitia99** [comment]
Hope that it can be considered as priority cause after 4 years, I noticed that it is not yet fixed.
![AddText_07-23-09.24.42_edit_3220058479716.jpg](https://github.com/kiwix/kiwix-android/assets/56766778/931e9e7c-d58f-476a-ba10-a982856bd462)
