### ISSUE TITLE
Improve bottom bar

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-android#165]
Add a collapsable bottom bar to the article view like in the wikipedia app. 
This bar should have a shortcut to the already existing actions: save as a bookmark, read aloud, find in page and  show side bar.

![](https://i.imgur.com/JxNd3ou.png)

**Comment by mhutti1** [comment]
Initial implementation on the bottombar branch.

**Comment by mhutti1** [comment]
This is implemented now so I think we can release it as an optional feature in 2.3 and then look to enable it by default in 3.0

**Comment by mhutti1** [comment]
We should look at adding more buttons/changing out buttons and look to make this default in 3.0

**Comment by mhutti1** [comment]
Resolved by #763
