### ISSUE TITLE
Library "Text Only" seems to be wrong

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1650]
for this book entry:

```
<book id="61114eff-427d-7b9c-cefe-5feac777bc10" title="Mathématiques par Wikipédia" name="wikipedia_fr_mathematics" tags="wikipedia;_category:wikipedia;_videos:no;_details:no;_ftindex:yes;_pictures:yes" description="Une sélection de Wikipédia articles sur les mathématiques" language="fra" creator="Wikipedia" publisher="Kiwix" faviconMimeType="image/png" favicon="..." date="2019-11-27" url="http://download.kiwix.org/zim/wikipedia/wikipedia_fr_mathematics_mini_2019-11.zim.meta4" articleCount="3671" mediaCount="4553" size="101205"/>
```

It has `_details:no` (which is different from `_details` unset which is like `_details:yes`). In that case, "Short text" should be highlighted. It is not.

It should be also "Short text", not "Short text only".

I would also put "Text Only" at the end (and "Short text" before).

**Describe the bug**

**Expected behavior**

**Steps to reproduce the behavior:**
1. 

**Screenshots**

**Environment**
- Version of Kiwix Android : 
- Device : 
- OS version : 

**Logs**

**Comment by macgills** [comment]
```
    tag_picture.selectBy(pictureTagIsSet)
    tag_video.selectBy(videoTagIsSet)
    tag_text_only.selectBy(!pictureTagIsSet && !videoTagIsSet && detailsTagIsSet)
    tag_short_text_only.selectBy(!pictureTagIsSet && !videoTagIsSet && !detailsTagIsSet)
```
what is the tag state of this book?

There is an error where I have been interpreting `_details:` as `_details:no` 
I wasn't aware the value could be empty for the private tags

**Comment by macgills** [comment]
https://github.com/kiwix/kiwix-android/issues/1574#issuecomment-560429974 I describe the behaviour implemented here but I am guessing what you want is
```
    tag_text_only.selectBy(!pictureTagIsSet && !videoTagIsSet)
    tag_short_text_only.selectBy(!detailsTagIsSet)
```

**Comment by kelson42** [comment]
```
tag_picture.selectBy(!pictureTagIsDef || pictureTagIsSet)
tag_video.selectBy(!videoTagisDef || videoTagIsSet)
tag_short_text.selectBy(detailsTagisDef && !detailsTagIsSet || !detailsTagisDef && false)
tag_text_only.selectBy(pictureTagIsDef && videoTagisDef && !pictureTagIsSet && !videoTagIsSet)
```

Displayed in this order.
