### ISSUE TITLE
People start to complain that everything is tiny on 20' screens

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1661]
* Do we have a reproduction case with a screenshot?
* We need to know if the problem comes from the content or the UI, or both?
* Is that related to the size of the pixel depth of the screen?

**Comment by macgills** [comment]
Is this chromebooks?

**Comment by kelson42** [comment]
@macgills I don't know... do Chromebooks use Android (I don't think so)?

**Comment by macgills** [comment]
They can use android apps. What tablet is 20 inches? Is it a small tv?

**Comment by kelson42** [comment]
I'll close the ticket for now, as we don't have neither a clear reprocase nor a way to get more information. Nothing more can be done for the moment.
