### ISSUE TITLE
Add a cache to avoid checking filesystem too often (might be slow)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1664]
**Is your feature request related to a problem? Please describe.**
Currently filesystem detection can take upwards of 1min and cause problems for users #1662 . This is because we write a file 4GB in size and see if it throws an exception or not.

**Describe the solution you'd like**
Add a cache so when we get a definitive result of whether a storage location can or cannot write 4GB files we never check it again.

**Comment by kelson42** [comment]
@macgills How would you secure that your recheck when needed (new smart card? same smart card but with different filesystem?)

**Comment by macgills** [comment]
No way of knowing, if the cache is scoped to the application it would live and die with the app meaning it would get rechecked from time to time

**Comment by kelson42** [comment]
@macgills What triggers the current check? How often does it run?

Letting this running only one time per Kiwix run seems a good idea in 99% of the case, but without being able to verify in the SD card has not been hot unplugged/plugged... we might generate quite weird crash scenarios IMO.

**Comment by macgills** [comment]
Everytime some enters the Library(FAT32 checker gets created) or if they change their preferred storage from the library(FAT32Checker observes changes to preferred storage) or if the sd card had less than 4GB of space and a deletion or move cause there to be >4GB free space. I could make it a singleton which effectively makes it an app instance cache, that would be a 1 line change.
The only "weird" behaviour we would get is we would try to download a file and fail.

#1663 is the preferred solution, running a minute long process invisible to the user is not desired at all ever.

**Comment by Jaifroid** [comment]
Sorry if this is obvious, but why not write a small text file in the app's directory on the SD card that gives the outcome of the test, and check for the existence of this file before re-running the test? Seems wasteful and potentially damaging to an SD card if 4GB is written to it every time the user enters the Library. Maybe I've misunderstood.

**Comment by macgills** [comment]
@Jaifroid thank you for the suggestion, had not considered it. Hopefully with the merging of #1663 this won't be necessary but improving the fallback filewriting filesystem checker with your suggestion should probably be a way forward if we experience any more user complaints around this issue

**Comment by kelson42** [comment]
@macgills I propose to close this ticket for the moment. Considering that the new check is really quick, we should not need a cache.

**Comment by macgills** [comment]
@kelson42 I think closing it may be going too far, the new solution works on the devices I have tested, I cannot have 100% certainty it will work on all devices.
Also we would be writing the file into our private storage on the sd card and the file would be the result of a test so just a `.txt` with `CanWrite4GbFile` in it which would be largely inoffensive

**Comment by kelson42** [comment]
@macgills With #2282, we se that in a lot of cases, it is impossible ot know from the mount point if fs supports big files. Therefore, somehow like foreseen by you, this ticket is relevant and IMO pretty important considering the current burden of writting this big test file each time to test if fs is OK. I believe what @Jaifroid propose is the best we can do: we should write in the directory itself where we write the ZIM files. But please write a hidden files, otherwise we will get questions/worries from users.
