### ISSUE TITLE
Search is slow and laggy

### ISSUE THREAD

**Issue by DoS007** [kiwix/kiwix-android#1676]
(I searched issues, i tried 3.1.2 latest pre-release.)

**Describe the bug**
I use maxi-wiki in german and english. I noticed that searching, e.g. on german maxi-wiki is slow and often laggs behind.

I noticed, that 3.1.2 is less laggy than current play store version - but still.

**Expected behavior**
It should be fast.

**Steps to reproduce the behavior:**
1. Load german maxi wiki.
2. Type in "Meditation"
3. You will see how long it takes

**Maybe: Underlying Problem**
A long time (10 sec or even more? - on 3.1.2) after typing i have a white screen. I think the problem is, that the search for "M" takes very long and after it is successful it searches for the next word. So a solution would be to periodically check while searching for "M" if the word has changed and then abort the search for "M" and start with the new one (or at least after e.g. 4 seconds) - searching for longer words is probably faster (searching for "Meditation" is probably faster than search for "M"). 

I don't know how kiwix is programmed, if the first search is important because its result is used for further searching by filtering the first results, then maybe abort searches after timeout at least for one or two character searches. "Med" will be probably much faster already.

**Environment**
- Version of Kiwix Android : 3.1.2
- Device : Samsung Galaxy Note 8 (has 6gb ram and should have fast enough soc)
- OS version : 9

_And btw. i want to thank you for the other two already fixed bugs: Download now works well on Android 9 and external sd (maxi wiki eng is 78 gb :), did work nice directly on sd). And math code now compiles fine on every page i visited._

**Comment by kelson42** [comment]
@DoS007 Thank you for your bug report. Which version (date) of the Wikipedia in German do you use?

FYI Kiwix for Andorid 3.1.2 is not officially available for everybody in the Google Play Store.

**Comment by DoS007** [comment]
hi @kelson42 ,
yeah, i tested newest android version and after that i tested the newest pre-release from here on github.

Wikipedia 2019-08-07 34.5  2.3 M articles (maxi-offline).

Happy new year to you all :).

**Comment by macgills** [comment]
This problem is due to us using `Filter.filter`
```
Starts an asynchronous filtering operation. Calling this method
cancels all previous non-executed filtering requests and posts a new
 filtering request that will be executed later.
```
Which sounds like any in progress filtering operations must be completed before a new one can begin as @DoS007 has intuited.

I've had an axe to grind against this filter for a while anyhow as it is not filtering anything but acting as a totally new dataSource. A rewrite to a viewModel/kotlin/recyclerview/Rx solution would be my preferred course of action but we could also easily slap an Rx bandaid(switchMap/debounce) on and reap the benefits

**Comment by kelson42** [comment]
@macgills This bug is really critical. It is fundamental that the search works fine. Really happy you think you understand the problem and have a solution in mind. Please do the best you can for that ticket.

**Comment by mgautierfr** [comment]
I don't know how you do the filtering but, from the documentation you've copied, it seems that you start a new filtering, it cancel previous ones.
So only one filtering (the last one) is executed at a time.

**Comment by macgills** [comment]
`cancels all previous non-executed` my read on that is it is not cancelling the in progress request ie the extremely lengthy search for `M`. The user then types `Me` that request gets queued, user types `Med` that gets queued  and `Me` gets cancelled. Anyway this screen should be architected to adhere to unidirectional data flow

**Comment by macgills** [comment]
I have verified this behaviour by putting a thread.sleep inside the filtering thread. Ongoing requests do not get cancelled so we can expect some speedup from the proposed solution.

The discrepancy between search speed for English vs German is odd though, I am in the process of verifying. I have English maxi and the speed is nigh instantaneous

**Comment by kelson42** [comment]
@macgills Great! The suggestions should come almost instantaneously in worse case and instantaneously otherwise. If not and you feel stuck, please let me know here.
