### ISSUE TITLE
Crash when using the "Search Kiwix" context menu (Dupe of #1656?)

### ISSUE THREAD

**Issue by zhuowei** [kiwix/kiwix-android#1681]
**Describe the bug**

Since the update to Kiwix 3.1.2, the "Search Kiwix" option in the text selection menu no longer works.

(I haven't tested the development version yet; I'll try that later)

**Steps to reproduce the behavior:**
1. Select some text in another app (eg. Google Chrome)
2. Select "Search Kiwix"
3. tap on one of the search results

Expected: the search result opens
Actual: Kiwix force-closes.

**Environment**
- Version of Kiwix Android : 3.1.2
- Device : Google Pixel 3 XL
- OS version : Android 10

**Logs**

The cause seems to be a NullPointerException:

```
12-25 23:24:21.073  7622  7622 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kiwix.kiwixmobile.core.main.MainMenu.showWebViewOptions(boolean)' on a null object reference
12-25 23:24:21.073  7622  7622 E AndroidRuntime: 	at org.kiwix.kiwixmobile.core.main.CoreMainActivity.hideTabSwitcher(CoreMainActivity.java:11)
```

The full stack trace can be found in this Gist:

https://gist.github.com/zhuowei/5138978b9ced34fefdbbc07d8fb02601

Based on the stack trace, I think this is a duplicate of #1656, which is already fixed, but that issue doesn't show how the crash is triggered, so I'm not sure if it's exactly the same bug.

**Comment by kelson42** [comment]
@zhuowei Thx for your bug report, we will do our best to come back soon to you.

**Comment by macgills** [comment]
Closing as duplicate, 3.1.3 will be released shortly
