### ISSUE TITLE
Even when closed one book search icon even appears and even searches the prev doc

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1683]
Even on closing after reading book search icon appears and one can search on previously opened doc
and even click find on-page.
Steps to reproduce:
0)You're in the home page with **no search icon**
1)Open any book 
2)Close that from recent
3)Now You came on the home page again.
4)But still, it has a Search icon where you can search prev open doc.

![ezgif-5-03fc060a8e5d](https://user-images.githubusercontent.com/24877361/71659316-2abdfa00-2d6d-11ea-9890-a7c53bf88f27.gif)

**Comment by iadeelzafar** [comment]
Hi @gptshubham595 ,

Thanks for opening the ticket. But I find it quite difficult to understand. Can you please structure the ticket information in the default Kiwix issue template? That'll make it easier for us to review and reproduce the bug.

**Comment by gptshubham595** [comment]
Hi @iadeelzafar I felt same while writing so I preferred to create the video gif for the explanation.
Even Though I am changing it a bit

**Comment by sonusourav** [comment]
@kelson42 I guess this issue is resolved because I am not able to reproduce it.
