### ISSUE TITLE
Crash scenario with Wikimed

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1684]
"i hav a problem- when i long press any word from web browser it allows me to choose wikimed and when i click then it goes to wikimed and there is available of that word in wikimed and when i press on that word it CRASHES and keep crashing even i cleared cache. FIX IT asap."

https://play.google.com/apps/publish?account=9116215767541857492#ReviewDetailsPlace:p=org.kiwix.kiwixcustomwikimed&reviewid=gp:AOqpTOFCztd_Fd8MqK3u29qocNhsGY3EQxGmxkB5NTtzRxYYFSSNy2rf9lcZNfob8CS6btS8aUqyGx-WytqWKg

**Comment by kelson42** [comment]
I can not reproduce this problem, I don't have this ability to jump from the web browser to Wikimed ap. Do you?

**Comment by macgills** [comment]
closing as duplicate of #1656
