### ISSUE TITLE
REFACTOR: move constants to a separate package

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-android#169]
We have a lot of constants: log tags, preference keys, activity result keys and whatnot. In some places these constants are hardcoded. 

1. Remove all hard coded strings and replace them with a constant
2. Group constants that are of the same kind (all Preference Keys for example) and move them to a separate class (create a new package called constants for that).

For example:

`zimFile = getIntent().getStringExtra("zim_file");`

Replace the hardcoded "zim_file" with a constant. Some already have a constant, and some are duplicated throughout multiple files.

**Comment by kelson42** [comment]
@mhutti1 @rashiq Wonder if this ticket is still valid after 3 years?

**Comment by mhutti1** [comment]
We have moved a lot of them. I guess there is always more possible work.

**Comment by kelson42** [comment]
@mhutti1 Do we have any method to detect them?

**Comment by mhutti1** [comment]
I think the linter detects some types.

**Comment by macgills** [comment]
`magic number` & `hardcoded text` are the inspections/issues that would help us, overall constants need to be handled better and placed in appropriate files

**Comment by kelson42** [comment]
I don’t really think this ticket is helpful anymore. Closing it.
