### ISSUE TITLE
Tabs previews in Tab Switcher doesn't change.

### ISSUE THREAD

**Issue by ajuancer** [kiwix/kiwix-android#1691]
**Tabs previews in Tab switcher when dark theme is active doesn't change.**
When we're in the Tab Switcher of the app, and the app is working with the dark theme, the preview for each opened tab continues being the normal one. The background is white and hyperlinks are in blue. The only change is shown if the article preview contains an image, in that case, the image will have inverted colors.

**Expected behavior.**
There should be a continuity with the theme. If the dark theme is active, previews also should be in that theme.

**Steps to reproduce the behavior:**
1. Activate Dark theme is your phone. This can be done in the developer settings or through the Kiwix's own settings.
2. Open the app
3. Open the TabSwitcher

**Environment**
- Version of Kiwix Android : 2020-01 Build: 6200070
- OS version : Android 9, API 28

![example](https://user-images.githubusercontent.com/39202665/71922694-ba0f4700-318b-11ea-97f4-65db5d01c2e2.png)

**Comment by macgills** [comment]
We will be overhauling the rendering in #1411 so I think this would be best addressed then instead of fixing now and reimplementing then.

Thank you for the report

**Comment by kelson42** [comment]
Closing, because basically a duplicate.
