### ISSUE TITLE
Manual release on FDroid

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1698]

**Comment by macgills** [comment]
I have asked for a manual release [here](https://gitlab.com/fdroid/fdroiddata/issues/1823#note_272568829)

**Comment by kelson42** [comment]
Yes, it seems this is as easy as updating https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.kiwix.kiwixmobile.yml

**Comment by macgills** [comment]
The merge request has been accepted, I will close this ticket once I have verified kiwix 3.1.3 is up on fdroid

**Comment by kelson42** [comment]
@macgills I wonder about that line (should not be `3.1.3`?
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.kiwix.kiwixmobile.yml#L175

**Comment by macgills** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/6232 merged, awaiting publication

**Comment by kelson42** [comment]
@macgills It seems we need here to propose an option to avoid signing the app.

**Comment by kelson42** [comment]
New PR https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6261

**Comment by macgills** [comment]
Released

**Comment by kelson42** [comment]
@macgills I don't see the new Kiwix version on my Fdroid!

**Comment by kelson42** [comment]
I see it now
