### ISSUE TITLE
Missing webview scrollbar

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#17]
I've had the request on OTRS so I'm just asking: has the elevator bar been removed after the 2.2 release? Is it a bug or a feature?

**Comment by Popolechien** [comment]
Since the guy insisted on Twitter: here's a screenshot from his Lenovo Vibe K5, where he is apparently scrolling but no elevator bar appears (otherwise everything is normal).
![c6fj2d-vaaencc8](https://cloud.githubusercontent.com/assets/21675885/23759508/4af70588-04ed-11e7-9c40-04bf0e742981.jpg)

**Comment by kelson42** [comment]
@mhutti1 Any idea was is meant here. I do not understand was goes wrong.

**Comment by Popolechien** [comment]
@kelson42 See red arrow for what is missing ![screenshot_2017-03-07-14-56-42](https://cloud.githubusercontent.com/assets/21675885/23785839/f62aead8-0569-11e7-9027-c436b84ce562.png)

**Comment by mhutti1** [comment]
This is a bug, we changed around or layouts and it likely changed something here. The scroll bar is actually there but it is the same colour as the background so is invisible. (You can see it if you scroll left as far as possible and down at the same time)
