### ISSUE TITLE
MEMORY LEAKS: Remove all static member updates from Activities

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-android#170]
We're doing some bad things in some Activities. For example in our SettingsActivity we're updating a static member of the KiwixMobileActivity.

Make members like these non-static:
  
```
public static boolean nightMode;

public static boolean refresh;

public static boolean wifiOnly;

```

Instead of statically updating them you could start the SettingsActivity with startActivityForResult() and then update the field through setting a Result in the SettingsActivity.

**Comment by kelson42** [comment]
Sounds pretty important to get that sorted out indeed!

**Comment by kelson42** [comment]
@macgills What is the status on this?

**Comment by macgills** [comment]
```
  public static boolean isFullscreenOpened;
  public static boolean refresh;
  public static boolean wifiOnly;
  public static boolean nightMode;
```
Still there but these wouldn't cause a memory leak. Still very bad practice though

**Comment by kelson42** [comment]
@macgills OK, then we should try to change that, not a big deal I guess.

**Comment by rashiq** [comment]
I believe there used to be a static fragment that was accessed from the main activity. I'm guessing that that one got removed. 

So yeah, these static booleans shouldn't leak memory, so we can close this for now.
