### ISSUE TITLE
Don't apply typography changes to all languages

### ISSUE THREAD

**Issue by amire80** [kiwix/kiwix-android#1711]
**Describe the bug**
In a commit such as 581b127184259ae999bd3501d95bb908aaffa1e5 typographic corrections were applied to localization files. For example, in values-iw/strings.xml, `"` was changed to `“”`. These changes are later automatically copied to translatewiki.

**Expected behavior**
The intention, to use non-trivial high-quality typography, is good. However, different languages have different needs. For Hebrew, for example, using these quotation marks is incorrect.

As a localizer for Hebrew, I cannot see any necessary automatic typographic changes at the moment, and they should be disabled for this language.

I'd go further and suggest not doing it for any languages, unless they ask for it.

**Steps to reproduce the behavior:**
1. Translate something in translatewiki using `...`, `"`, or other characters that are automatically replaced by typography update software.
2. Wait until the typography update software runs.

**Comment by macgills** [comment]
`the typography update software runs` that is a manual process run by me, granted android studio does most of it for me. I don't think this will matter for Hebrew if the correct character is used, the [gershayim Unicode](https://www.fileformat.info/info/unicode/char/05f4/index.htm) is different from the simple English quotation mark and will not be detected or replaced automatically. If Hebrew translations contain English quotation marks they should be updated with the Hebrew equivalent if at all possible.

**Comment by amire80** [comment]
I have a degree in Hebrew language, I have more than ten years of experience of localizing into Hebrew, and I am one of the people who designed the standard Hebrew keyboard layout, so I know what's correct and I can use the correct characters myself when I work in translatewiki and elsewhere, so I don't need automated or semi-automated processes to do this for me. And if this software was at least adapted for the language and actually changed quotes to gershayim and to Hebrew-style quotes —which are not the same thing— in the right places, we'd have a different conversation, but it changes plain quotes to English-style quotes, and this is just wrong. It also changes three full stops to the ellipsis character. All of it is unnecessary, incorrect, and creates extra bot edits in translatewiki. Please don't do it for Hebrew, and consider not doing it for other languages, too. Different languages have different needs.

**Comment by macgills** [comment]
I have no doubts about your expertise in the Hebrew language.
To talk in specifics you mean these strings?
```
  <string name="cannot_open_file">Failed to open file\nPlease try looking for this file in the Device Tab of your Library</string>
```
```
  <string name="cannot_open_file">פתיחת הקובץ נכשלה\nנא לנסות לחפש את הקובץ הזה בלשונית \“מכשיר\” בספרייה שלך</string>
```

These are the automated checks that get run and report errors
![image](https://user-images.githubusercontent.com/3358282/72979492-595d4c80-3dd0-11ea-800d-0a6beb63ae77.png)
![image](https://user-images.githubusercontent.com/3358282/72979534-72fe9400-3dd0-11ea-9365-7aae2752edb6.png)
![image](https://user-images.githubusercontent.com/3358282/72979605-9e817e80-3dd0-11ea-90b0-b444ff00ebb3.png)

Can you explain to me the purpose of the straight quote usage in our hebrew text?

All of our english text does (or should) have curvy quotes and I would have thought the languages analog should be used at translation time and looking at the [unicode](https://en.wikipedia.org/wiki/Hebrew_(Unicode_block)) I thought this was the gershayim.

Translation is a thorny beast so I want to know the full details before making a decision that affects the visual quality of our text

**Comment by amire80** [comment]
Curvy quotes are indeed good for English text.

The very best thing for Hebrew quotations is to use low-9 double quote in the beginning and high-9 double quote in the end of a quotation. However, it is rare in modern texts because it was not available on keyboards until Windows 8 and badly supported in Microsoft Office for many years, so in collaborative projects, like free software projects translation, the plain quote is used for quotation.

The gershayim character is distinct. It is supposed to be used in abbreviations and not in quotations.

I use gershayim as well as the high and low quotes in my personal writing and in writing and translation projects where everyone agrees on using them. They are also used in some other publications. In wider, collaborative projects, like Wikipedia and translatewiki, where participation of newbies is frequent and welcome, it's not feasible to demand this, at least for now, because the necessary characters became available in common operating systems only since 2012, and Windows 7 is still very common. It cannot be enforced by software either, because it's too difficult to distinguish abbreviations and quotations automatically. Strange as it may sound, both gershayim and quotation marks can appear between letters in the middle of the word and it's impossible to guess the right character with simple parsing, without also understanding the word.

Luckily, I'm pretty good at enforcing it manually. The punctuation conventions I use for Kiwix translations are the same as for MediaWiki and Wikipedia, so the Kiwix users get a consistent experience.

**Comment by macgills** [comment]
For this case specifically I am still mildly confused. I assume \“מכשיר\” is `Device` which in the original english does not have quotation marks. Is it a characteristic of Hebrew that the extra emphasis is necessary or is there extra information provided by this symbol?

Regardless of this scenario if we want to ignore a lint rule for a language there are many ways of easily doing it but I don't know much on the translatewiki side of the production of files.
We can ignore an issue for an entire file
```
<resources xmlns:tools="http://schemas.android.com/tools"
  tools:ignore="TypographyQuotes">
  <string name="example">"straight quotes are great"</string>
</resources>
```
We can ignore on a specific string
```
<resources xmlns:tools="http://schemas.android.com/tools">
  <string name="example" tools:ignore="TypographyQuotes">"straight quotes are great"</string>
  <string name="error" tools:ignore="TypographyQuotes">"not great here"</string>
</resources>
```
Or I can ignore for the entire project in our build file.
`ignore` accepts a comma separated list of issue ids or the `all` keyword.

I would currently believe our current typographical checks are a good choice for all of the latin alphabet languages though I could happily be proven wrong.

**Comment by amire80** [comment]
In English, "Device" is emphasized by being capitalized: "Please try looking for this file in the Device Tab of your Library". (I'm not sure the word "Tab" should be capitalized, by the way.) The capital letter makes it stand out, so quotes are not needed.

Hebrew doesn't have capital letters, and without them it's not clear that this is a title of a tab in the user interface.

Please ignore this rule for the whole file, and the ellipsis rule, too.

I don't know how well does it work for other languages that use the Latin alphabet. It uses incorrect quotes style in Hebrew, so I'm not sure that it works correctly in other languages, each of which has a different style. If it uses correct quotes style for German, French, Hungarian, Polish, etc., and the translators are happy about it, then so be it. I'm not sure that it's correct for Portuguese, for example.

**Comment by macgills** [comment]
I think the only occurrence of straight quotes in the English strings is
```
  <string name="wifi_only_msg">If you choose "Yes" you won\'t be warned in future. However, you can always change this in Settings</string>
```
which is quite surprisingly not curvy-ed, I will probably fix that now.
The automatic fix only affected pt, pt-rBR, and sl as regards this string, if you can tag any translators responsible for these languages here to put my mind at ease it would be appreciated. If that is an easy task for yourself, otherwise I can chase it.
The rest of the 36 translations of wifi_only_msg were unaffected

**Comment by macgills** [comment]
@amire80 PR opened
