### ISSUE TITLE
Robuster online library loading

### ISSUE THREAD

**Issue by mohamed-sameh-khalil** [kiwix/kiwix-android#1713]
**Describe the bug**
Library always shows no items available after loading for 5 minutes in the online tab.
I think this issue might be related to the closed issue #1164 

**Expected behavior**
It should display books that i can download

**Steps to reproduce the behavior:**
I don't know if this a global problem, but this is what I did
1. download the application from google play store
2. open app and click on download books
3. after 5 mins and around 30 MBs of data usage the library shows no item available
4. I used a vpn set to france but the problem was still there

**Screenshots**
![image](https://user-images.githubusercontent.com/34913464/73118166-41650480-3f59-11ea-809b-cec3af3e958a.png)

**Environment**
- Version of Kiwix Android : 3.1.3
- Device : Samsung Galaxy s7 edge, Samsung Galaxy A70
- OS version : 8.0.0, 9.0.0

**Comment by macgills** [comment]
@mohamedsamehkhalil are you exclusively using a vpn? If your reported location is very dissimilar  to your actual location that could cause delays. Our current retry mechanism is that we try downloading the list of books(9mb or so) and if it hasn't completed after 1 minute abandon that request and try again. In the next release we will be migrating to a library system that fetches much smaller focused chunks at a time so hopefully this pain point will be resolved for you then

**Comment by mohamedsamehkhalil** [comment]
@macgills I used both vpn and a direct connection and both did not work. However, I tried it again today using mobile data which was slightly faster than my original connection and it worked. so I think it was probably a connection problem. I will test my original connection again tomorrow just to be sure it's a connection problem.
And if I may suggest, using some sort of cache to save the list of books would help as well

**Comment by kelson42** [comment]
@macgills 30MB in 5mb makes a really slow bandwidth. I had myself extremely high difficulties to get the catalog displayed with a 1Mb/s bandwidth. To me this problem should be fixed by using the OPDS stream.

**Comment by macgills** [comment]
I say we revisit this after the OPDS stream is implemented. If @mohamedsamehkhalil is still experiencing trouble we can explore some caching using `cache-control` headers for an easy win

**Comment by kelson42** [comment]
@macgills Yes, and there is also an other problem we really need to fix https://github.com/kiwix/maintenance/issues/113

**Comment by kelson42** [comment]
@mohamed-sameh-khalil Are you still impacted with latest version?
@macgills What should we do here? Not sure we can do more, except monving to OPDS.

**Comment by mohamed-sameh-khalil** [comment]
@kelson42 No, I am no longer facing this problem. I suspect it was happening because of low bandwidth on my side at the time.
