### ISSUE TITLE
Zoom Control does not make the Zoom level visually enabled instantly.

### ISSUE THREAD

**Issue by 4shutosh** [kiwix/kiwix-android#1715]
**Describe the bug**
Under the Zoom options in settings the Zoom controls switch enables the custom zoom level slider option but it does not get view of a enabled option, it gets view of enabled option after we reopen the settings page. Although the slider works perfectly fine.

**Expected behavior**

Every time we enable the Zoom controls swithc the zoom level should turn on(should lighten / turn as a usable option)

**Steps to reproduce the behavior:**
1. Download the kiwix app from play store
2. Go to settings
3. Scroll down to Zoom
4. Enable the Zoom Control switch
5. Check the error

**Screenshots**
![zoom_issue1](https://user-images.githubusercontent.com/53831987/73141363-40db8380-40a9-11ea-85f4-a4a2b589ca3a.gif)

**Environment**
- Version of Kiwix Android : 3.1.3
- Device : Pixel 4
- OS version : Android 10

**Comment by 4shutosh** [comment]
Hi! I would like to work on this.

**Comment by kelson42** [comment]
@4shutosh thank you. Your are welcome but gives a few hours please to confirm the problem.

**Comment by macgills** [comment]
I confirm the issue, @4shutosh you are welcome to work on it

**Comment by 4shutosh** [comment]
Hey!
I just added this code which solves this issue.
![zoom_issue_solution](https://user-images.githubusercontent.com/53831987/73294095-23cebe00-422b-11ea-8634-9d60b2f0de7d.gif)

**Comment by 4shutosh** [comment]
Hey! @kelson42 @macgills 
Please review !
