### ISSUE TITLE
Adding/Removing bookmarks is prety much buggy

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1717]
0 - My bookmark list is empty.
1 - Open a content and bookmark the welcome page, I get:
![image](https://user-images.githubusercontent.com/1029718/73257582-509bba80-41c4-11ea-8edc-203ad6af5e13.png)
2 - Like you can see, the bottom bar bookmark icon has not been updated [PROBLEM 1]

3 - Then a try to bookmark it again and I get:
![image](https://user-images.githubusercontent.com/1029718/73257742-98badd00-41c4-11ea-9d75-c5b9f3a54894.png)
4 - Like you can see, this time the bottom bar icon has been updated properly... But this should work for the first time

5 - And now I have it twice in the library (should never happen).
![image](https://user-images.githubusercontent.com/1029718/73257844-c99b1200-41c4-11ea-8ca2-c10a470458da.png)

**Comment by macgills** [comment]
This will require some Rx knowledge as the `CoreMainActivity` should observe the bookmarks database and not have to perform requests for data updates

**Comment by kelson42** [comment]
@macgills Not super suprised about your comment. I will remove the "good first issue" tag ans assign it to you as this makes the whole bookmarking difficult to use.

**Comment by kelson42** [comment]
@macgills I can not bookmark anything anymore, seems to still have a problem to me.
