### ISSUE TITLE
REFACTOR: Extract Menu logic to a separate class

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-android#173]
[Lightcycle](https://github.com/soundcloud/lightcycle) is a great library that makes it possible to chunk of logic from the Activity to a contained class that gets all the Android lifecycle callbacks. Extract all the Menu logic (onOptionsItemSelected, initAllMenuItems, onPrepareOptionsMenu, onCreateOptionsMenu etc.) into one of those lightcycles. You will need to add the library to the project first, but that's very easy with gradle.

**Comment by kelson42** [comment]
@mhutti1 Do we have a consensus on this way of doing? That brings a new dependency!
@rashiq Any chance you help on implementing this?

**Comment by kelson42** [comment]
@mhutti1 @rashiq Wonder if this ticket is still valid after 3 years?

**Comment by abdulwd** [comment]
Still, we have not extracted the menu logic to a separate class. So yes.

**Comment by macgills** [comment]
Refactoring would be good, adding a new library is not needed I would say

**Comment by kelson42** [comment]
@macgills This is not something you have done recently? Considering that the menu is different for Kiwiax and Custom apps, this would have maybe make sense?

**Comment by macgills** [comment]
It is probably something I will do on the road to custom apps.
