### ISSUE TITLE
Android OS language changes are ignored

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1738]
Steps:
1 - Android configured in English
2 - Install Kiwix and start it
3 - Kiwix is properly running with English locale
4 - Change Android language to French
5 - Stop and restart Kiwix

I get:
Kiwix is still with English locale

I want:
Kiwix with French locale, Twitter has changed.

**Comment by macgills** [comment]
I would say this is somewhat impossible outside of the scenario where no language has been set in the app settings

If the user has chosen a language in our settings we should probably respect that above a different locale in System Settings otherwise it would never take effect.

There was my proposal to remove the in app language selection and respect the System setting only but we said no because sometimes the android phone wouldn't have more esoteric languages in its settings

**Comment by kelson42** [comment]
> I would say this is somewhat impossible outside of the scenario where no language has been set in the app settings

This is exactly what happen here, I never have open the settings.

**Comment by kelson42** [comment]
I think it should be a bit more sophisticated as it is. For the moment, it looks like that Kiwix just sticks to a language even if the user has never explicitly chosen one. It should behave that way only if it has, otherwise it should take the one of the OS... and of course this does not apply for custom apps.

**Comment by kelson42** [comment]
A way to do that would be to have a first choice (the chosen per default) which would be "Language of Android".

**Comment by macgills** [comment]
I am not disputing the bug, I am just saying it gets tricky outside of that 1 scenario.

Out options are
1. Formalise the "no language" set option, only force locale when we have an option
1. Make the default language returned the current language
1. Remove in app language setting

After a small investigation
```
    @JvmStatic
    fun handleLocaleChange(
      context: Context,
      sharedPreferenceUtil: SharedPreferenceUtil
    ) {
      val language = sharedPreferenceUtil.getPrefLanguage("")
      if (language.isEmpty()) {
        return
      }
      handleLocaleChange(context, language)
    }
```
that variable passed to `getPrefLanguage` is the default return for no value.

All I can say right now is I need to investigate more

**Comment by kelson42** [comment]
I think I want (1), I don't want (3) and I don't really understand (2).

**Comment by macgills** [comment]
I'll work on this next and then we can re-evaluate 1737 if it doesn't get fixed as a by-product

**Comment by macgills** [comment]
@kelson42 I think this was a false positive, what you are actually experiencing is incomplete translations.
Go the library and the title of the tabs should change

**Comment by macgills** [comment]
actually scratch that, just encountered the bug of it going to english, occurred when I entered the setting screen, investigating further

**Comment by macgills** [comment]
```
languagePref.setDefaultValue(selectedLang);
languagePref.setValue(selectedLang);
```
The offending article, bypasses our SharedPrefUtil so my breakpoints weren't triggering, very annoying.
So yeah option 1 it is, I will add a "Device Default" and change the settings option to `Force Language`
