### ISSUE TITLE
REFACTOR: Legacy method manageExternalLaunchAndRestoringViewState()

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-android#174]
Nobody ever dared to touch that method and it's just very ugly.

**Comment by kelson42** [comment]
@mhutti1 @rashiq Wonder if this ticket is still valid after 3 years?

**Comment by mhutti1** [comment]
It looks better, I imagine it could still do with some refactoring. Maybe not worth its own issue though.
