### ISSUE TITLE
Investigate if reintroducing Density Split apks is worthwhile

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1744]
**Is your feature request related to a problem? Please describe.**
For devices <21 vector assets get turned into pngs for all densities, to reduce the size of these apks we can create an apk per density

**Describe the solution you'd like**
If the size reduction is noticeable we should add density split apks

**Describe alternatives you've considered**
keep our existing apks

**Additional context**
There is the possibility of this affecting our CD solutions

**Comment by kelson42** [comment]
@macgills I propose to abandon that idea because:
* less and less of such devices
* not a real added value as most of the apk size is binary code
* Quite complex
* Our apk is relatively small anyway

**Comment by macgills** [comment]
I am happy to abandon it
