### ISSUE TITLE
Rewrite KiwixSettingsActivityTest in Kotlin with a PageObject/Robot

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1745]
**Type of Test**

* [ ] Unit Test
* [x] UI Test

**Particular area and files to be tested**
The tests already exist but should be rewritten to conform to the new style

**Current Status of the tests**
current tests reside in `app/src/androidTest`

**Comment by s-ayush2903** [comment]
Can you please throw light at _Write test to conform new style_

**Comment by s-ayush2903** [comment]
Okay, so i just read about the `Robot` mentioned in the title and comprehended that it is something that makes use of Builder Pattern(kinda abstraction and implementation type but not like interfaces, like clean Architecture?) and found its usage in the `IntroActivityTest`. Please add anything that i missed or misinterpreted.

PS: I would like to work on this issue

**Comment by macgills** [comment]
A PageObject/Robot is just an object that wraps around the details of a screen/view to simplify driving a test. This way if a view changes (a new id or what have you) then our tests are not affected, only our robots
