### ISSUE TITLE
Difficult to read low contrast text with low brightness on phone

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#1748]
**Describe the bug**

In dark mode.
When viewing the text of zim tags in the library and the text of buttons in dialogs the text is very low contrast and is difficult to see when the brightness of the phone is low. 

**Expected behavior**

The contrast of all text should be high so that it is easy to read. Even in dark mode. 

**Steps to reproduce the behavior:**
1. Enter library
2. Look at the tags on the device or online zim files.
3. Go to the online tab in the library.
4. Start downloading a file.
5. Click the stop button. This dialogs buttons text is low contrast. 

**Screenshots**

Pictures instead of screenshots as screenshots does not show brightness level.

![83636464_265134524465502_6806432113617797120_n](https://user-images.githubusercontent.com/22193232/73557723-ff085f80-4451-11ea-9b62-0622ea8830d7.jpg)
![84397513_184695102589811_2439227462018662400_n](https://user-images.githubusercontent.com/22193232/73557725-ff085f80-4451-11ea-901d-05a8df6da840.jpg)

**Comment by 4shutosh** [comment]
Hello! @Frans-Lukas 
You correctly pointed out that the stop downlaod button in dark mode is sometimes hard to see.
Although the contrast of all the text cannot be increased further I guess as the background is already black and the text color is white.
For the text you may try the `High-contrast text` feature under the `Accessibility` in Android Settings
Also please specify the version of app (environement) you are using, I suggest you trying the same in latest version available at Google Play Store.

**Comment by kelson42** [comment]
@macgills Feedback welcome. The tags are really not visible on these pictures. Even if on my Google Pixel2 the contrast level is acceptable. I think something should be done here, probably by increasing at least the lightness of the font.

**Comment by Frans-Lukas** [comment]
> You correctly pointed out that the stop downlaod button in dark mode is sometimes hard to see.
> Although the contrast of all the text cannot be increased further I guess as the background is already black and the text color is white.

@4shutosh I meant the dialog buttons seen in picture 2. ('No' and 'Yes' of the dialaog. Blueish in color) as well as the tags that are gray in color from picture 1. Here is the version info:

- Version of Kiwix Android : 3.1.3 Build: 6230103
- Device : Oneplus 5

**Comment by 4shutosh** [comment]
> > You correctly pointed out that the stop downlaod button in dark mode is sometimes hard to see.
> > Although the contrast of all the text cannot be increased further I guess as the background is already black and the text color is white.
> 
> @4shutosh I meant the dialog buttons seen in picture 2. ('No' and 'Yes' of the dialaog. Blueish in color) as well as the tags that are gray in color from picture 1. Here is the version info:
> 
> * Version of Kiwix Android : 3.1.3 Build: 6230103
> * Device : Oneplus 5

:grinning: : I was really unable to see them !
The colors should be arranged accordingly for better visibility.
Do you want to work on this issue?
Otherwise I am interested in working on this one.

**Comment by Frans-Lukas** [comment]
Hehe, yeah it is difficult to see! Go ahead and fix it as I can't do much this weekend.

**Comment by macgills** [comment]
Under `values-night/color.xml` we can change the tone of our primaryColor `@color/blue800` and that would affect the night mode blue color.
The disabled text color would probably require a selector be written for the color to supply a different alpha in selected.

If there is someone with experience in graphic design who could make a style guide based on the material design priniciples, that would be immensely helpful to the project
