### ISSUE TITLE
Use Androidx.webkit 1.2.0 Force Dark for webview dark mode

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1749]
**Is your feature request related to a problem? Please describe.**
Our current implementation means we have to invert the paint colors for the view, which is slightly error prone and requires maintenance.

**Describe the solution you'd like**
Use the force dark method supplied by androidx

**Additional context**
The ForceDark Feature may not be supported by all Webviews so we have to check availability at runtime, if we were to use this feature we would have to either maintain our existing paint inversion feature or show a message to the user that their webview does not support dark mode

**Comment by kelson42** [comment]
@macgills I thought you tested it and it was not providing a similar UX than what we have currently?

**Comment by macgills** [comment]
@kelson42 it produced a different UX, arguably better and will probably have more maintenance than our solution seeing as how it will be a part of the androidx family

**Comment by kelson42** [comment]
@macgills Ok, I would like to discuss that in detail before implementation.

**Comment by kelson42** [comment]
@macgills I don’t really think that we can have one dark mode strategy which will fit to all kind of contents. My feeling is that the ultimate solution is that the content decides this... and using the Android native solution is for that reason not optimal.

**Comment by macgills** [comment]
I think there will be an aesthetic benefit to many of our users. To me the cost is the added complexity in having 2 solutions, 1 as a fallback

**Comment by kelson42** [comment]
Closing, not the strategy I want to follow, even if I agree with all points of @macgills.
