### ISSUE TITLE
crash using youscribe_audiobooks

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-android#1756]
**Describe the bug**
Using the [youscribe-audiobooks](http://download.kiwix.org/zim/other/youscribe_fr_audiobooks_2020-01.zim) ZIM, kiwix crashes on clicking the play button.

**Expected behavior**
Clicking the play button should reveal the videojs widget and start playing the audio.

**Steps to reproduce the behavior:**
1. Download and open the ZIM file (link above)
2. Click on any audio icon. Should open a popup.
3. Click on the _play icon_ in the black rectangle.

Beware that the crash happens when clicking the play button and not the _télécharger_ (download) link above, which opens a native player and works fine on my device.

**Environment**
- Version of Kiwix Android : master
- Device : TECNO F1
- OS version : Android Go 8.1

**Comment by rgaudin** [comment]
Important information is that the player is the very same player as for youtube ZIMs. Main difference is that it is applied to `<audio />` elements instead of `<video />` ones.

**Comment by macgills** [comment]
Could not reproduce. @rgaudin is it possible for you to provide me with logs?

I am intenesely suspicous of Android Go.

**Comment by rgaudin** [comment]
Will try but it's difficult. The device is crap and when connected (debug mode), the screen is not/incorrectly responsive.
What happens on your system when clicking that button?

**Comment by macgills** [comment]
Audio starts playing. 
![image](https://user-images.githubusercontent.com/3358282/73929050-0ef9c680-48cc-11ea-896c-8a0e08df0038.png)


Some audio links have greyed out play icons
![image](https://user-images.githubusercontent.com/3358282/73929019-fc7f8d00-48cb-11ea-85ea-8187b0439cbb.png)

**Comment by rgaudin** [comment]
OK, here's a log file

Actually, it crashs even before clicking the play button. When I open a modal dialog, after a few seconds, the app crashes.

Here are the steps for this particular log:

1. launch kiwix (master)
2. open youscribe ZIM
3. click on the first icon
4. wait a bit
5. kiwix disapears
6. using the alt-tab feature to restore kiwix which is in the library

[youscribe_crash.log](https://github.com/kiwix/kiwix-android/files/4166360/youscribe_crash.log)

**Comment by macgills** [comment]
there isn't really a crash there unfortunately. I have no ability to reproduce this on my end, I can go buy a Go device (maybe), the emulator alternative is to use a sys image of 19 on a tiny amount of RAM.

The log contains some ANR warnings but that is probably to be expected on such low specs

**Comment by rgaudin** [comment]
OK ; is this “behavior” regular though ? What's happening? Is the Kiwix app *restarted* ?

Is there anything I could try on my end? there's an aggressive “RAM cleaner” on the device. I'll try to disable it if possible (was bundled) and see if that changes anything.

**Comment by macgills** [comment]
Well your logs have a curious `gone` statement. How are you extracting logs?

I don't have much idea of what the app is doing, if there is a crash there should be a dialog `Kiwix has stopped working`, if the app is overworked on the main thread it should say `Kiwix has stopped responding`. Without an exception there is nothing I can do. I do have a 6.0 budget device but it is not running Go, granted it might be better if it was, it can barely handle having a home screen

**Comment by kelson42** [comment]
@rgaudin What is your exact device? Might be not a bad move to have @macgills able to run Kiwix of such a device or similar super low end hardware (on a device farm, or even buy one).

**Comment by rgaudin** [comment]
The device is a **TECNO F1**. I have no link to share as the manufacturer as no page for it online and most specs catalogs are wrong mentioning 512MB RAM while mine has 1GB.

Retail price is under $60 here.

```
DevCheck Report

Tecno
F1

Feb 11, 2020 9:31
Uptime: 3d 20h 26m 41s
Deep sleep: 3d 18h 29m 15s (97%)

HARDWARE
Mediatek 
Hardware: MT6580M
Cores: 4
null
Process: 28 nm
Frequencies: 604 MHz - 1300 MHz
Governor: interactive

GRAPHICS
Vendor: ARM
GPU: Mali-400 MP
OpenGL: OpenGL ES 2.0 58bf738
Resolution: 854 x 480
Screen density: 240.11053 ppi
Screen size: 4.08 in / 104 mm

RAM
RAM size: 1.0 GB
Type: LPDDR2 533 MHz
Bandwidth: 4.3 GB/s
Channels: 32-bit single channel

OTHER HARDWARE
Bluetooth support: Yes
Bluetooth LE support: Yes
USB host support: No
Infrared transmitter: No
NFC support: No

DEVICE
Model: TECNO F1
Codename: TECNO-F1-PRO
Manufacturer: Tecno
Serial Number: 4802922172041201

SYSTEM
Android Version: 8.1.0 (Oreo)
Build: F1-VP510EFG-GO-191205V16
Security patch: December 5, 2019
Architecture: armv7l (32-bit)
Instruction sets: armeabi-v7a armeabi
Kernel: 3.18.79

BATTERY
Technology: Li-ion
Health: Good
Capacity (reported by system): 2050 mAh

NETWORK
MAC address: 70:9F:A9:35:04:58
5GHz band support: No
Phone type: GSM

CAMERA
Resolution: 4.9 MP (2560x1920)
Focal length: 3.5 mm
35mm equivalent focal length: 27.6 mm
Sensor size: 4.46x3.19 mm
Crop factor: 7.9x
Field of view: 65.0°
Pixel size: 1.66 μm
RAW mode: Supported
Front camera: 1.9 MP (1600x1200)
```

**Comment by rgaudin** [comment]
Did some additional testing and sharing some findings for documentation purpose…

The first thing to state is that I tried accessing the ZIM served by kiwix-serve on a different computer, using Chrome and it worked perfectly. No browser crash, audio plays as expected.

Important to note that when _downloading_ audio files, the chrome player is launched (as android supports ogg) but I received a RAM-related error message on a very large file. See screenshot

![Screenshot_20200213-085158](https://user-images.githubusercontent.com/57929/74420603-9eaaf200-4e43-11ea-804c-e9517da6f090.png)

I then tested in Kiwix using the remote debugging and found a number of issues:

![Screen Shot 2020-02-13 at 09 05 03](https://user-images.githubusercontent.com/57929/74418230-f9424f00-4e3f-11ea-8cae-34cc46fb27a5.png)

```
Fetch API cannot load content://org.kiwix.kiwixmobile.zim.base/I/vendors/ogvjs/ogv-demuxer-ogg-wasm.wasm?version=1.6.1-20190618150123-e65cc4a. URL scheme "content" is not supported.
```

I wonder why we arqe getting this as we're using the same code as for youtube ZIMs and those are working. Have you done anything special regarding the `<video />` tag when fixing support for youtube? As mentioned above, we're now tapping into the `<audio />` tag.

Also, and maybe more important, it's working for you guys. Could any of you try to look at the remote console to check whether you're getting this error message as well? Maybe the `async` fails on all devices` and the `sync` fails on this one due to lack of RAM.

```
wasm streaming compile failed: TypeError: Failed to fetch
falling back to ArrayBuffer instantiation
```

First line is direct result of previous error I guess and second results from not serving WASM files with correct content-type.

So I regenerated the ZIM file using new zimwriterfs which sets the proper MIME type for wasm files and indeed, the error messages are gone.

I do get a new one instead:

```
Uncaught TypeError: Cannot read property 'byteLength' of null
    at ArrayBufferBackend.onXHRLoad (ogv.js:41)
    at XMLHttpRequest.<anonymous> (ogv.js:1)
```

I will mark this issue as stale as I don't think much can be done without a repro-case. I'll bring the device to the hackathon. I'm also about to open a different one regarding the _disabled state_ of some audio.

**Comment by rgaudin** [comment]
Sorry for all the noise around this but trying to document the other issue, I got the _crash_ also on the emulator (Pixel3a, API29).

Though it could be RAM related, so a created another virtual device with 3GB  ram on API 26 but it crashes on opening the ZIM file…

```
kill (OOM or update) wasn't handed by all associated webviews, killing application.
```

Attaching the full log.
[emulator_crash.log](https://github.com/kiwix/kiwix-android/files/4198366/emulator_crash.log)

**Comment by macgills** [comment]
You have to be sure to be using google_apis emulators to get a someway decent version of the browser on the emulator. Emulators being fresh instances will have the worst browser and lead to bizarre issues.

I'll do an investigation on the audio soon.

**Comment by macgills** [comment]
I have been trying to reproduce the crash with emulators with no success.

@kelson42 I would say this should be descoped from this milestone and I will work on it at the hackathon as suggested.

**Comment by kelson42** [comment]
@macgills I don't really know for now how to deal with the problem. Postponing.

**Comment by kelson42** [comment]
New kiwixlib has been published https://bintray.com/kiwix/kiwix/kiwixlib/

**Comment by kelson42** [comment]
New kiwix-lib is now available https://bintray.com/kiwix/kiwix/kiwixlib/9.1.1

**Comment by kelson42** [comment]
For me works fine now with 3.3.0

**Comment by rgaudin** [comment]
> For me works fine now with 3.3.0

Well you were never affected by this issue so it’s not very useful:)

Will try to test with the device on Saturday (it’s been reassigned)

**Comment by kelson42** [comment]
@rgaudin It is true that I was not able to get a crash. But, I was not able to play most of the audio of this same ZIM... which I assume was an other symptom of a same root cause. Now I can. Actually I can even play all the chapters of one audiobok together... which is fun.

**Comment by rgaudin** [comment]
OK, I could eventually test with 3.3.0. It works as expected !!!
I could test with 3.2.1 (store) and with that works, it plays correctly but durations are messed-up.

Congrats on fixing this.
