### ISSUE TITLE
Convert all AsyncTasks to run with RxJava Schedulers

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-android#176]
There are examples of RxJava networking in the DownloadService class. We want to get rid of AsyncTasks (like the SaveNetworkLanguages in LibraryAdapter) and replace it with a similar construct.

**Comment by mhutti1** [comment]
This could be tackled incrementally and converting one such async task might be an interesting introduction for new comers to the project.

**Comment by srv-twry** [comment]
@mhutti1 Which async task would you like to convert first ? I'll do it :smile:

**Comment by mhutti1** [comment]
@srv-twry its up to you I would pick a simple one though if you havn't used RxJava before as it can take some time to get get used to the flow.

**Comment by srv-twry** [comment]
@mhutti1 I have some experience working with RxJava2 on a few other open source projects in which i contribute.
I'll choose a simple one though to start.

**Comment by srv-twry** [comment]
@mhutti1 I couldn't find any other AsyncTask in the project. Can you please check once you get time and confirm it ? We can close this issue then after #369 is merged.

**Comment by mhutti1** [comment]
Wow it does look like there was only one. We must have converted the others during general bug fixes and feature implementations.

**Comment by rashiq** [comment]
Though we could convert this [into](https://github.com/kiwix/kiwix-android/blob/108af1096b9316f9dd00ecee912aff4c5cfc4942/app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileSearch.java#L62-L73) an observable

**Comment by srv-twry** [comment]
@rashiq Yes, i will send in the PR shortly.

**Comment by kelson42** [comment]
Download & File scan has been rewritten. I'll close that ticket. If someone one to improve a particular piece, I propose to create a specific ticket and related PR.
