### ISSUE TITLE
About Page for the app.

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1762]
**Is your feature request related to a problem? Please describe.**

Currently, the application doesn't have a dedicated about page telling about it's details. 

**Describe the solution you'd like**

Making an about section for the app and adding the option to open it to the main menu or settings of the app.

**Additional context**

I would like to make a dedicated about section for app which contains different sections in separate card views. 
The sections include:
- An brief description of what the app is.
- A link to the GitHub issues section where users can directly report any issues they face
- App version and details
- Licenses

Having an about section is a criterion followed by most android apps and I think there should be one here too.

**Comment by yashk2000** [comment]
@kelson42 @macgills what are your views on this?
I was just going through the app and realized that this is missing while it is present in many other applications.

**Comment by macgills** [comment]
In Settings we have the app version and clicking on `Credits` shows the licenses of the application.
`Help` shows info about the app.

I wouldn't classify this as a priority for anytime soon.

The most desirable feature here to me is `Report an issue` which could extend from our `Send Feedback` & `Error Reporting` facilities

**Comment by kelson42** [comment]
We have one. I would prefer a ticket specifically proposing to improvedor fix one part of it.

**Comment by yashk2000** [comment]
> In Settings we have the app version and clicking on `Credits` shows the licenses of the application.
> `Help` shows info about the app.
> 
> I wouldn't classify this as a priority for anytime soon.
> 
> The most desirable feature here to me is `Report an issue` which could extend from our `Send Feedback` & `Error Reporting` facilities

@macgills should I make a report issue option below the Send Feedback option which directs them to the issues page over here.

**Comment by macgills** [comment]
I would leave that to the discretion of @kelson42 

My idea is perhaps more of a "diagnostic" that could aid us in troubleshooting with users who are experiencing issues, much like how our Error Reporting(see ErrorActivity) works in that a user can toggle data to send us data like what is in the Databases. My personal interest is in the result of the `mount` command which we use to detect the filesystem.

There are at least 2 tickets in that proposal but these are all nice to haves and would get scheduled for a later milestone if we decide they do add enough value to a user
