### ISSUE TITLE
Kiwix does not find the ZIM files on SD-Card since Jan. Update

### ISSUE THREAD

**Issue by heimo0** [kiwix/kiwix-android#1775]
The problem here is that the user has ZIM files on its external SD card and can not see them in its local library.

**Environment**
- Version of Kiwix Android : Jan 2020
- Device : Samsung S8
- OS version : 10

**Comment by kelson42** [comment]
@macgills This is a user who first contacted us via the Play Store comments. He is an "old" user of Kiwix and for some reasons, since January release (so version 3.1) he has no access anymore to his file on the external SD card.

**Comment by mhutti1** [comment]
I have had a look and I can still access them on an s8 running OS 9 though. Pretty sure 10 isn't out on the s8?

**Comment by kelson42** [comment]
@mhutti1 @heimo0 I confirm that for this user Google Play Console reports Android 9. That said, we have many different models of S8. Lets wait to @macgills to see if he has a few specific questions for @heimo0.

**Comment by heimo0** [comment]
hallo 

 

I think problem is independent from OS Android.

 

I tried it also with my old LG G4 and Android V7. 

Last year Kiwix run here with ZIM already on SD-card, but now not yet....

 

yours.

 

Gruß 

Hermann

 

 

------------------------------------------------------------------
Hermann Moseler            Tel.:   089-44848-40-0



Von: Kelson [mailto:notifications@github.com] 
Gesendet: Sonntag, 16. Februar 2020 14:22
An: kiwix/kiwix-android
Cc: heimo0; Mention
Betreff: Re: [kiwix/kiwix-android] Kiwix does not find the ZIM files on SD-Card since Jan. Update (#1775)

 

@mhutti1 <https://github.com/mhutti1>  @heimo0 <https://github.com/heimo0>  I confirm that for this user Google Play Console reports Android 9. That said, we have many different models of S8. Lets wait to @macgills <https://github.com/macgills>  to see if he has a few specific questions for @heimo0 <https://github.com/heimo0> .

**Comment by macgills** [comment]
@heimo0 do you know from which version you updated?

I would recommend you leave your phone open on the Library screen for a couple of minutes as we had a poorly performing feature that has been improved for the next release but that you could be suffering from. After a few minutes it should a) stop greying out files over 4GB b) Scan your directories properly and populate the Device tab

**Comment by heimo0** [comment]
hallo ....

 

                                   do you know from which version you updated?

 

no, because I did it not manually, but it took place automatically by the OS-System.....

 

 

----------------

 

So I tested open on the Library screen for hours, bad result, apps was always closed, when I looked ..on it....

 

Please link me the previous version APk, so I can use the old version, until you fix the bug...

 

 

 

------------------------------------------------------------------
Hermann Moseler            Tel.:   089-44848-40-0
München                           Fax:   089-44848-48 

Von: Seán Mac Gillicuddy [mailto:notifications@github.com] 
Gesendet: Dienstag, 18. Februar 2020 11:56
An: kiwix/kiwix-android
Cc: heimo0; Mention
Betreff: Re: [kiwix/kiwix-android] Kiwix does not find the ZIM files on SD-Card since Jan. Update (#1775)

 

@heimo0 <https://github.com/heimo0>  do you know from which version you updated?

I would recommend you leave your phone open on the Library screen for a couple of minutes as we had a poorly performing feature that has been improved for the next release but that you could be suffering from. After a few minutes it should a) stop greying out files over 4GB b) Scan your directories properly and populate the Device tab

**Comment by heimo0** [comment]
hallo ...

 

                        5 minutes should be the worst scenario

 

I would only say with my message, that I observed the Library screen for long time, nothing happens after 5, 10, 15, 30 or more minutes, until sometime later the app closed by itself.....

 

-------------------

 

                        Do you have your sd card set as your preferred storage for downloading zims?

 

Of course, because ZIM files in the internal storage are found, but it does not help me.

I tested it with a small Zim-file and it works, but the GERMAN WIKI has 33 GByte, and there is no place for it inside the Phone...

 

-----------------------------------------------

                        If you are willing I can send you a development version of the app that may help us fix this problem in the future.

 

I think, it a good idea, perhaps better to install an older version...

I like to try it...

 

 

yours

Gruß 

Hermann

 

 

------------------------------------------------------------------
Hermann Moseler            Tel.:   089-44848-40-0



 

Von: Seán Mac Gillicuddy [mailto:notifications@github.com] 
Gesendet: Mittwoch, 19. Februar 2020 16:24
An: kiwix/kiwix-android
Cc: heimo0; Mention
Betreff: Re: [kiwix/kiwix-android] Kiwix does not find the ZIM files on SD-Card since Jan. Update (#1775)

 

@heimo0 <https://github.com/heimo0>  any of our previous versions can be downloaded from the releases page on github <https://github.com/kiwix/kiwix-android/releases>  or from download.kiwix.org <https://download.kiwix.org/release/kiwix-android/> 

So I tested open on the Library screen for hours, bad result, apps was always closed, when I looked ..on it....

I am afraid I don't quite understand what you are saying here? 5 minutes should be the worst scenario. Do you have your sd card set as your preferred storage for downloading zims?

If you are willing I can send you a development version of the app that may help us fix this problem in the future.

**Comment by macgills** [comment]
>I think, it a good idea, perhaps better to install an older version...
I like to try it...

I am still a bit unclear here. Are you going to install a previous version or are you happy to help us with our investigation by installing a development version of the apk?

**Comment by kelson42** [comment]
I think at this stage, we will release 3.2 in the Play Store and @heimo0 will tell us if he still has a problem.

**Comment by macgills** [comment]
The only addition I can think of is we could scan the directories returned by MountInfo? I would need to run some tests on it

**Comment by kelson42** [comment]
@macgills You mean testing code or prod code?

**Comment by macgills** [comment]
Prod code to try and find readable mounts on the users filesystem. That is the only next step I can think to take that we aren't already taking

**Comment by kelson42** [comment]
Ok to think about that, but lets get confirmation that 3.2 does not work first.

**Comment by heimo0** [comment]
Reminder:

 

-----------------------------------------------

                        If you are willing I can send you a development version of the app that may help us fix this problem in the future.

 

I think, it a good idea, perhaps better to install an older version...

I like to try it...

 

Perhaps something will help.

 

Some apps ask especional to receive acces to SD-Karte, and user have to allow it.

Kiwix never ask for it...

 

 

yours

Gruß 

Hermann

 

 

 

------------------------------------------------------------------
Hermann Moseler            Tel.:   089-44848-40-0
München                           Fax:   089-44848-48 

Von: hermann moseler [mailto:hmoseler@gmx.de] 
Gesendet: Mittwoch, 19. Februar 2020 17:30
An: 'kiwix/kiwix-android'; 'kiwix/kiwix-android'
Cc: 'Mention'
Betreff: AW: [kiwix/kiwix-android] Kiwix does not find the ZIM files on SD-Card since Jan. Update (#1775)

 

hallo ...

 

                        5 minutes should be the worst scenario

 

I would only say with my message, that I observed the Library screen for long time, nothing happens after 5, 10, 15, 30 or more minutes, until sometime later the app closed by itself.....

 

-------------------

 

                        Do you have your sd card set as your preferred storage for downloading zims?

 

Of course, because ZIM files in the internal storage are found, but it does not help me.

I tested it with a small Zim-file and it works, but the GERMAN WIKI has 33 GByte, and there is no place for it inside the Phone...

 

-----------------------------------------------

                        If you are willing I can send you a development version of the app that may help us fix this problem in the future.

 

I think, it a good idea, perhaps better to install an older version...

I like to try it...

 

 

yours

Gruß 

Hermann

 

 

------------------------------------------------------------------
Hermann Moseler            Tel.:   089-44848-40-0

 

Von: Seán Mac Gillicuddy [mailto:notifications@github.com] 
Gesendet: Mittwoch, 19. Februar 2020 16:24
An: kiwix/kiwix-android
Cc: heimo0; Mention
Betreff: Re: [kiwix/kiwix-android] Kiwix does not find the ZIM files on SD-Card since Jan. Update (#1775)

 

@heimo0 <https://github.com/heimo0>  any of our previous versions can be downloaded from the releases page on github <https://github.com/kiwix/kiwix-android/releases>  or from download.kiwix.org <https://download.kiwix.org/release/kiwix-android/> 

So I tested open on the Library screen for hours, bad result, apps was always closed, when I looked ..on it....

I am afraid I don't quite understand what you are saying here? 5 minutes should be the worst scenario. Do you have your sd card set as your preferred storage for downloading zims?

If you are willing I can send you a development version of the app that may help us fix this problem in the future.

**Comment by heimo0** [comment]
i asked for Download link...

Am 26. Februar 2020 15:24:35 MEZ schrieb Kelson <notifications@github.com>:
>Ok to think about that, but lets get confirmation that 3.2 does not
>work first.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kiwix/kiwix-android/issues/1775#issuecomment-591451736

Gruß

Hermann Moseler

**Comment by macgills** [comment]
@heimo0 as per my comment [here](https://github.com/kiwix/kiwix-android/issues/1775#issuecomment-589073543) I am having difficulty understanding you. If you can comment on github as opposed to replying via email it might help.

What download link are you looking for?
3.2 has been released on the play store so it may have automatically updated or you will need to manually update.
Or is it a development version of the app to help diagnose your sd card problem?

**Comment by heimo0** [comment]
I understood in one of your mails that I should test a development version for you....

Was´nt it?

 

----------

 

                        If you can comment on github as opposed to replying via email it might help.

It is to difficult for me...

 

yours.

hermann

 

------------------------------------------------------------------
Hermann Moseler            Tel.:   089-44848-40-0
München                           Fax:   089-44848-48 

Von: Seán Mac Gillicuddy [mailto:notifications@github.com] 
Gesendet: Mittwoch, 11. März 2020 17:05
An: kiwix/kiwix-android
Cc: heimo0; Mention
Betreff: Re: [kiwix/kiwix-android] Kiwix does not find the ZIM files on SD-Card since Jan. Update (#1775)

 

@heimo0 <https://github.com/heimo0>  as per my comment here <https://github.com/kiwix/kiwix-android/issues/1775#issuecomment-589073543>  I am having difficulty understanding you. If you can comment on github as opposed to replying via email it might help.

What download link are you looking for?
3.2 has been released on the play store so it may have automatically updated or you will need to manually update.
Or is it a development version of the app to help diagnose your sd card problem?

**Comment by macgills** [comment]
Yes, unfortunately I have less time than when I made that offer, I am afraid I will have to ask for you to wait longer unless another contributor can come in and save the day

**Comment by mhutti1** [comment]
I'm not really sure what's going on here?

**Comment by heimo0** [comment]
same to me.....

I am waiting for a Link for a "test" version of Kiwix, but nothing answers...

Only answer, I should do something, I do not understand on a HUB page?

Whatever it is??


I am not a profi, but only normal user...

 

 

yours...

hermann

 

------------------------------------------------------------------
Hermann Moseler            Tel.:   089-44848-40-0
München                           Fax:   089-44848-48 

Von: Isaac Hutt [mailto:notifications@github.com] 
Gesendet: Dienstag, 24. März 2020 22:44
An: kiwix/kiwix-android
Cc: heimo0; Mention
Betreff: Re: [kiwix/kiwix-android] Kiwix does not find the ZIM files on SD-Card since Jan. Update (#1775)

 

I'm not really sure what's going on here?

**Comment by macgills** [comment]
@mhutti1 heimoo can't see files on the sd card since the update, the version he was on remains a mystery.

I was going to make a development version with a button he could press that would email some specific logs to see what is happening on his device if he was willing but because of the language barrier I couldn't ascertain if I had his consent.

It now seems clear that heimoo is definitely willing to test but I don't have the time right now. I will be back fulltime next week but I don't know if I will get around to this.

@heimo0 I was asking you to comment on this issue https://github.com/kiwix/kiwix-android/issues/1775 where I am typing. Replying from email instead of typing here is hiding a lot of what you are saying and making it difficult.
For now there is nothing for you to do, it is up to us.

**Comment by heimo0** [comment]
Hallo ....

I will Try a version form  
"downloaded from the releases page on github or from download.kiwix.org"
But don´t know, which of the version are right for me.
It is Samsung S8 with Android V.9
Make it help to test a pre or beta version?

**Comment by macgills** [comment]
Releases page: https://github.com/kiwix/kiwix-android/releases
Downloads page: https://download.kiwix.org/release/kiwix-android/

There are many versions so I don't know which one will work for you because I don't know which one you upgraded from.

I cannot make a test version because I do not have the time. A new release of kiwix will happen in a month and maybe your problem will have been fixed then?

Our beta releases usually happen a week before the releases, you can sign up for those on the google play store

**Comment by kelson42** [comment]
@heimo0 New release 3.3.0 has been released in beta in Play Store. Should be tested to update the ticket.

**Comment by heimo0** [comment]
How do i update to it?


Am 24. April 2020 09:38:57 MESZ schrieb Kelson <notifications@github.com>:
>@heimo0 New release 3.3.0 has been released in beta in Play Store.
>Should be tested to update the ticket.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kiwix/kiwix-android/issues/1775#issuecomment-618856302

Gruß

Hermann Moseler

**Comment by macgills** [comment]
@heimo0 if you go to our store listing https://play.google.com/store/apps/details?id=org.kiwix.kiwixmobile on your phone you should be able to sign up to be a beta user if you scroll down the screen a bit.

**Comment by heimo0** [comment]
installed the beta, but bug continues, no zim in inside memory nor on SD-card will be recognized.
So I dowloaded a small online ZIM = Ubuntu, it is stored, but when opening the file, the app freeze.
Have to kill it to get out and off it..
Tried it several times, allways the same...

**Comment by macgills** [comment]
There have been a few bugs fixed since the beta and we have introduced a new diagnostic report system so you will be able to send us an email of details from the app to help diagnose your problem.

Thank you for your patience, I have to ask for a bit more. Hopefully we will have a new beta by the end of today

**Comment by heimo0** [comment]
How dow i generate the Diagnostik Report?


Am 1. Mai 2020 09:44:24 MESZ schrieb "Seán Mac Gillicuddy" <notifications@github.com>:
>There have been a few bugs fixed since the beta and we have introduced
>a new diagnostic report system so you will be able to send us an email
>of details from the app to help diagnose your problem.
>
>Thank you for your patience, I have to ask for a bit more. Hopefully we
>will have a new beta by the end of today
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kiwix/kiwix-android/issues/1775#issuecomment-622286940

Gruß

Hermann Moseler

**Comment by macgills** [comment]
On the new version, which you can download tomorrow (probably), it is in the help screen.
You access the help screen here
![image](https://user-images.githubusercontent.com/3358282/80797307-6b9e1200-8b99-11ea-82d3-964b5f89227d.png)
and then there is a `Send Diagnostic Report` button

**Comment by macgills** [comment]
@heimo0 thank you for the report and patience, I believe I have a fix for this issue

**Comment by heimo0** [comment]
when will this version be available?

**Comment by macgills** [comment]
@heimo0 could you check if your problem is resolved by testing with this apk https://download.kiwix.org/nightly/2020-05-11/dev-universal-debug.apk

I will need to evaluate when we next do a release, ideally we do not do releases too close together to avoid annoying our users with too many downloads.
