### ISSUE TITLE
External storage not selectable in nightly

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#1778]
**Describe the bug**
 
I installed the nightly <https://download.kiwix.org/nightly/2020-02-16/dev-universal-debug.apk> and when selecting storage I just get internal storage listed. The external/sd-card storage is missing. Using 3.1.3 from F-Droid shows me Internal and External.

**Expected behavior**
Both should be listed.

**Steps to reproduce the behavior:**

Have a look at the preferences/select storage.

**Environment**
- Version of Kiwix Android :  nightly 2020-02-16
- Device : Galaxy S5
- OS version : lineageOS lineage_klte-userdebug 9 (2020-02-08)

**Comment by JensKorte** [comment]
Imho this bug is NOT related to #1775 since I get the zim files from SD-card after ten seconds.

**Comment by macgills** [comment]
I confirm the issue was with migration to Recyclerview, the layouts previously used for ListView had a `match_parent` attribute meaning the first item expanded to fill the entire space. Fix incoming

**Comment by kelson42** [comment]
@JensKorte Good catch!
