### ISSUE TITLE
Clicking "find in page" crashes app

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1781]
Steps to reproduce:

* Open app
* Click on magnifier
* Click on Find in page (without entering any search term)

The app first freezes and then crashes.

Android 9.0
Huawei P20 Lite
Kiwix 3.1.3 build 6230103

**Comment by macgills** [comment]
this was already fixed in #1771 , if you can verify this behaviour with a nightly I'll reopen
