### ISSUE TITLE
Upgrade kiwixlib

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1786]
**Is your feature request related to a problem? Please describe.**
Video/audio files won't play because the reported offset from kiwixlib is returned as an int.

**Describe the solution you'd like**
Upgrade to latest kiwixlib to benefit from the correct typing of this field

**Comment by kelson42** [comment]
@mgautierfr We need urgently libkiwix 9.0.1 to release Kiwix Android 3.2
