### ISSUE TITLE
Create script to move string resources across modules

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1788]
**Is your feature request related to a problem? Please describe.**
To support our translations we lint  the core module as a dependent of the app module. This has a side effect of linting all of the dependencies of app and creates false positives in our lint reports that have to be baselined

**Describe the solution you'd like**
A script that takes 3 inputs, `source module`, `destination module` `string key` and uses them to move a specific string and all its translation to the `destination module` so our translations are preserved on translatewiki

**Describe alternatives you've considered**
Continue with how it is, downside is we will never get rid of the baseline

**Comment by Frans-Lukas** [comment]
I'd like to work on this!

**Comment by kelson42** [comment]
@Frans-Lukas You are welcome :)

**Comment by Frans-Lukas** [comment]
@macgills @kelson42 Am I interpreting this correctly? 

The user gives `source module` and `destination module` as well as `string key`. 

The source and destination modules can for example be `app` and `core`. The script will then look for a `source module`/src/main/res/ directory after of which it will iterate all `values*` directories from there. For each iteration it will copy the `string key` line from the strings.xml file. (Ex. ` <string name="detecting_file_system">Detecting if file system can create 4GB files</string>` for the key `string_key = 'detecting_file_system'`.) 

It will then paste the `string key` line into the corresponding values* directory in `destination module`/src/main/res/values*. 

One ambiguity is whether it should cut the line from the source directory or copy it? I.e. if the line should be removed from `source module`/src/main/res/values*/string.xml or not.

**Comment by kelson42** [comment]
@macgills I think this script should be in Python. You confirm?

**Comment by macgills** [comment]
Yes this is correct, it will find a string by key and cut it out of all the values-* files it occurs in and add it to (or create) the corresponding strings file.

I think in reality what will happen is that strings will only be moved from `core` -> `app` but it is easy to give us the flexibility.

Personally if I was going to write this I would try and do it with [kotlin scripting](https://kotlinlang.org/docs/tutorials/command-line.html) but that would mostly be to satisfy my curiosity of how capable it is . Nobody should feel an obligation to do that, bash/python whatever is convenient and easy

**Comment by kelson42** [comment]
> Personally if I was going to write this I would try and do it with [kotlin scripting](https://kotlinlang.org/docs/tutorials/command-line.html) but that would mostly be to satisfy my curiosity of how capable it is . Nobody should feel an obligation to do that, bash/python whatever is convenient and easy

I strongly support Kotlin, as this is the language of the app. Any other solution would require additional deps to be installed and I don't like this really much.

**Comment by Frans-Lukas** [comment]
Alright, I want to learn kotlin scripting as well, so that will be good. Do we have a directory for scripts in the repository or should the script be placed in the root dir? I noticed there are a couple of scripts in the root dir. (update-play-store.py and upload-apk.py)

**Comment by macgills** [comment]
Please create a `scripts` directory on the root of the project and move all those scripts in. I have been meaning to delete half off them as they are defunct

**Comment by Frans-Lukas** [comment]
Great! Will do.

**Comment by kelson42** [comment]
@macgills @Frans-Lukas Probably good to put it directly in `contrib` directly?!

**Comment by macgills** [comment]
Ah yes, I forgot that was there

**Comment by macgills** [comment]
@Frans-Lukas I was doing some quick reading on kotlin scripting and [this article](https://www.danielebonaldo.com/kotlin-script/) mentioned the packaging of a script as a standalone binary using `kscript`, I wasn't a big fan of adding `kscript` just to add dependencies but to me there is value in users of this script not having to install `kotlinc`. Consider this a bonus extra on this ticket, totally optional

**Comment by Frans-Lukas** [comment]
@macgills kscript looks great. I'll look into it.
