### ISSUE TITLE
Arrows next to questions not visible in dark mode

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1792]
**Describe the bug**
On switching to dark mode, the arrows next to the questions in the help section are not visible. 

**Expected behavior**
The arrows should be visible in dark mode too.

**Steps to reproduce the behavior:**
1. Switch to dark mode.
2. Go to the help section from the menu.
3. The arrows next to the questions will not be visible. 

**Screenshots**

![screencap](https://user-images.githubusercontent.com/41234408/75089892-657d2b00-5583-11ea-936e-cfc317c2dd8a.png)

**Environment**
- Version of Kiwix Android : 3.1.3
- Device : Redmi K20
- OS version : Android 9

**Comment by yashk2000** [comment]
@kelson42 @macgills I propose making the color of those arrow icons the same as the color of the feedback icon so that it is uniform throughout the help section and will be visible in the light as well as dark mode.
Should I proceed with this?

**Comment by kelson42** [comment]
I really wonder why this does not work out of the box here! It should be grey like the text to me.

**Comment by 4shutosh** [comment]
I would like to work on this.

**Comment by yashk2000** [comment]
> I really wonder why this does not work out of the box here! It should be grey like the text to me.

I also tried to figure that out. In the text view, we are using style to set the parameters unlike that in the arrow. Maybe that's causing the discrepancy. 

What option should we proceed with?
Making the color always blue or changing it according to the mode of the app?

**Comment by yashk2000** [comment]
> I would like to work on this.

Sorry, I opened the issue with the intention to work on it.

**Comment by yashk2000** [comment]
@kelson42 is this fine?

![screencap](https://user-images.githubusercontent.com/41234408/75090431-ca874f80-5588-11ea-9d52-9b335d4e38e8.png)
