### ISSUE TITLE
Improve README instructions about project import

### ISSUE THREAD

**Issue by KushagraK123** [kiwix/kiwix-android#1794]
While building kiwix-android, build fails with message Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.

**Comment by kelson42** [comment]
@abdulwd Maybe you can help @KushagraK123, from the CONTRIBUTING file, it is not clear if a specific version of Gradle is expected... or maybe we have an other problem here?

**Comment by deborahlow97** [comment]
Hey, have you tried the solution mentioned [here](https://stackoverflow.com/questions/56607089/new-gradle-sync-is-not-supported-due-to-containing-kotlin-modules-using-an-unsup)? It seems like a similar issue.

**Comment by Frans-Lukas** [comment]
I had the same error message when first importing the project. I can not reproduce this error though.

What I did to solve this was to import the core module alone in android studio, and not the entire project. That is: in android studio. File->new->import project. Select kiwix-android/core

**Comment by abdulwd** [comment]
@KushagraK123 I think what you're seeing is a warning: `Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0`. I also get this line in build logs but the build succeeds. Can you confirm this so we can close this ticket?

Otherwise, if you would like to fix this warning you can change the title of this PR.

**Comment by macgills** [comment]
Per the readme
>To build this repository alone for development purposes you can simply import the project into Android Studio and the hard work will be done for you. 

This means you can't `open` the project, you must `import` it
![image](https://user-images.githubusercontent.com/3358282/75141005-f1a86300-56e7-11ea-99f5-bfd5b077a214.png)
We could probably bold/underline/italicise/quote that part to emphasise that.

I would delete whatever you have on disk, open android studio to an unrelated/empty project, clone kiwix and then import it.

As @abdulwd said this is a warning that occurs on every build. If you want to upgrade gradle to latest version I am all for it, there will be speed increases and we will be able to upgrade some of our tooling and potentially support incremental builds. Tiny amounts of our gradle scripts would need to be rewritten

**Comment by kelson42** [comment]
@macgills Yes, I think this is important to be a bit more explicit here in the documentation.

**Comment by yashk2000** [comment]
@macgills should we update the gradle to the latest version? I would be willing to make all the related changes if it's fine. I'll also make the change in the readme so that it's easier for the user to see that the project has to be imported.

**Comment by macgills** [comment]
@yashk2000 please make a ticket to upgrade gradle and another ticket to update readme. We will close this ticket when @KushagraK123 's problem is fixed

**Comment by yashk2000** [comment]
@macgills doing it.

**Comment by yashk2000** [comment]
@kelson42 according to the above discussion, I created #1804 and #1803. So should I proceed with them?

**Comment by kelson42** [comment]
@yashk2000 Carry on pleaee

**Comment by kelson42** [comment]
se

**Comment by KushagraK123** [comment]
Importing the project fixed the issue.

**Comment by yashk2000** [comment]
@KushagraK123 great!
I'll update the readme so that part is better conveyed to people who build the app in future.
