### ISSUE TITLE
Wiktionary translations can't be shown

### ISSUE THREAD

**Issue by danielzgtg** [kiwix/kiwix-android#1796]
**Describe the bug**

The translations in Wiktionary cannot be viewed anymore on the latest ZIMs. They start collapsed and do not expand when tapped. This applies to translations, conjugations, and collapsible tables in general.

This happens with:
- `wiktionary_en_all_maxi_2020-01.zim`
- `wiktionary_en_all_nopic_2019-12.zim`
- `wiktionary_en_all_novid_2018-06.zim`

This does not happen with and things worked fine with `wiktionary_en_all_nopic_2017-08.zim`

**Expected behavior**

To be able to see the translations.

**Steps to reproduce the behavior:**

1. Tap on "Library" in the overflow menu
2. Open `wiktionary_en_all_maxi_2020-01.zim`
3. Open the definition for "wiki"

**Screenshots**

Actual behavior:

![Screenshot_20200222-191642](https://user-images.githubusercontent.com/25646384/75102845-7f892e80-55c0-11ea-9108-f4f05e4f8571.jpg)

Example of expected behavior in older ZIM:

![Screenshot_20200222-191715](https://user-images.githubusercontent.com/25646384/75102846-81eb8880-55c0-11ea-948b-4de2354b5911.jpg)

**Environment**
- Version of Kiwix Android : 3.1.3
- Device : OnePlus 7 Pro
- OS version : OxygenOS Open Beta 9

**Comment by kelson42** [comment]
@danielzgtg Thank you for your bug report, this is a bug in the content itself, moving the issue to the right repository.
