### ISSUE TITLE
Proposal: Allow users to refresh the books list on the home screen

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#1797]
**Is your feature request related to a problem? Please describe.**

There should be a way to refresh the list of books on the home screen. Consider this sequence of events:
1. You start downloading a certain book which takes a few minutes
2. You come back to home screen while the download is in progress
3. The book is successfully downloaded
4. The list of books shown doesn't have the newly downloaded book.

There is no way to refresh the list of books now. The only option is to head back to any other random activity and then come back to the Home activity again so that it triggers a reload of the list of books.

**Describe the solution you'd like**

Either a swipe to refresh layout or simply a refresh button on the title bar should be enough.

**Additional context**

I am willing to implement this if this seems like a reasonable thing to do

**Comment by kelson42** [comment]
Home screen and local library should merge at some point. I would leave that aside for the moment as this is milestone 3.3 main topic.

**Comment by mhutti1** [comment]
I would close this as I think the functionality shouldn't be needed and is going to be replaced.
