### ISSUE TITLE
Confirm from users before deleting the history/bookmarks

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#1798]
**Is your feature request related to a problem? Please describe.**

While using the application randomly, I stumbled upon the history tab. I accidentally clicked on the delete icon and it deleted my history. There was no confirmation requested by the application.

**Describe the solution you'd like**

I think there should be a confirmation dialog asking the user to confirm the deletion. 

**Additional context**

I am willing to implement this in case it's a reasonable thing to do.

**Comment by kelson42** [comment]
Not sure if that is really a good idea. Would need other opinions on that.

**Comment by srv-twry** [comment]
After a little more research, I believe that an option to undo the action would be much better in comparison to a confirmation dialog. Obviously, that depends on if the action is invertible or not. I haven't taken a look at the source code, so can't comment on that.

Nice discussion here: https://ux.stackexchange.com/questions/71960/deletion-confirm-or-undo-which-is-the-better-option-and-why

**Comment by macgills** [comment]
"Confirm before deleting" is more inline with kiwix behaviour. This behaviour would have to be added to bookmarks also, for consistency

**Comment by kelson42** [comment]
@srv-twry Then you can carry on with the fix I believe :)

**Comment by macgills** [comment]
@KushagraK123 @4shutosh given the relative size of this change it won't take to long for it to be redone so I will be closing your PRs and giving this ticket to @srv-twry as this ticket acknowledged them as the assignee (though neglected to actually mark it, I'll do that now) so I think it is only fair, thanks for the submissions.

**Comment by danielzgtg** [comment]
For history, there is already a button on the settings page. That one does ask for confirmation. How about we remove the delete icon from the history page as it's duplicate functionality?

**Comment by macgills** [comment]
This feature allows for more fine grained control as the user can delete the history/bookmarks for just 1 zim or delete specific entries. I don't particularly think there is great value in managing your history to such an extent but history and bookmarks are such similar features we should aim to achieve feature parity so as not to confuse users
