### ISSUE TITLE
Add slack invite link to readme

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#1799]
**Is your feature request related to a problem? Please describe.**

Add slack invite link to the readme.

**Describe the solution you'd like**

Just change the text to: `Slack: #android channel (get an invite)` under communications linked with https://join.slack.com/t/kiwixoffline/shared_invite/enQtOTUyMTg4NzMxMTM4LTU0MzYyZDliYjdmMDYzYWMzNDA0MDc4MWE5OGM0ODFhYjAxNWIxMjVjZTU4MTkyODJlZWFkMmQ2YTZkYTUzZDY
A slack badge can also be added to the readme.

**Describe alternatives you've considered**

**Additional context**

**Comment by dlow97** [comment]
I‘d like to do this issue!

**Comment by deborahlow97** [comment]
I’d like to do this issue!

**Comment by kelson42** [comment]
@deborahlow97 carry on.
