### ISSUE TITLE
Update gradle version.

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1804]
**Describe the feature**

Gradle version should be updated to the latest version available and all requisite changes should be made to the scripts. 

**Additional Context**

I would like to work on this.

**Comment by kelson42** [comment]
@yashk2000 Why? What does that imply for other developers?

**Comment by yashk2000** [comment]
@kelson42 this was discussed on #1794 where @macgills told to open a ticket for this. 

> If you want to upgrade gradle to latest version I am all for it, there will be speed increases and we will be able to upgrade some of our tooling and potentially support incremental builds. Tiny amounts of our gradle scripts would need to be rewritten

**Comment by macgills** [comment]
@kelson42 Upgrading gradle is a necessary step we will have to take eventually, the ecosystem moves and we have to move with it, we are lagging a bit behind right now

**Comment by kelson42** [comment]
@yashk2000 carry on

**Comment by yashk2000** [comment]
@macgills newer versions of some dependencies being used are also available. Should I create an issue for updating those too?
