### ISSUE TITLE
Accidental deleting all of our bookmarks

### ISSUE THREAD

**Issue by 4shutosh** [kiwix/kiwix-android#1807]
**Problem Description**
While selecting **`View Bookmarks From all Books`** the icon for deleting all the bookmarks is prone to being touched, which further deletes all the bookmarks without a choice.

![Webp net-resizeimage (5)](https://user-images.githubusercontent.com/53831987/75184149-eeee5200-5769-11ea-9048-82a44a188a62.jpg)

**Describe the solution you'd like**
A warning message should be displayed before deleting the bookmarks.
Losing all our precious bookmarks can be saved using this

**Comment by kelson42** [comment]
Duplicate of #1798
