### ISSUE TITLE
Text in tags aren't centered

### ISSUE THREAD

**Issue by deborahlow97** [kiwix/kiwix-android#1812]
**Describe the bug**
UI Bug: where text in tags aren't centered - it doesn't look appealing to users.

**Current Behavior:**

![image](https://user-images.githubusercontent.com/22865538/75231483-7d0d1b80-57f0-11ea-8371-6f41c1cc7fcc.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/22865538/75231781-07ee1600-57f1-11ea-946d-74eede613c6c.png)

**Others**
I would like to work on this starter issue if it gets acknowledged!

**Comment by macgills** [comment]
Sounds good, go for it
