### ISSUE TITLE
Make clear all notes dialog similar to clear history dialog

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1815]
**Is your feature request related to a problem? Please describe.**
The dialogs of clear history and clear all notes in the setting section of the app vary a lot even though both of them involve clearing data important to the user. Hence the dialogs should also look similar.

**Describe the solution you'd like**
The clear history dialog looks good as it provides the appearance of an alert with an exclamation mark so that the user clearly knows what he is doing. The appearance of the clear all notes option dialog is a bit plain on the other. I plan to make the same UI for both, following the style of the clear history dialog.

**Additional context**

![screencap](https://user-images.githubusercontent.com/41234408/75259063-6e812d00-580d-11ea-974f-05a037abffce.png)

![screencap](https://user-images.githubusercontent.com/41234408/75259091-7a6cef00-580d-11ea-8eae-924802fadbaa.png)

If this is a valid issue, I would like to work on it.

**Comment by macgills** [comment]
I would wait until #1443 is completed as that will have an api to easily support this.

This dialog might look goofy with an icon as it just has a `message`, no title and You run the risk of repeating yourself if you have a title and a message. I am unconvinced it is a value add right now but I could be proven wrong.

**Comment by rohanprasadofficial** [comment]
@kelson42  @macgills  Can i work on this ?

**Comment by yashk2000** [comment]
@rohanprasadofficial this issue is currently on hold. If we need it to be solved, we'll do it once #1443 is completed.

**Comment by rohanprasadofficial** [comment]
@yashk2000  thanks for the clarification

**Comment by yashk2000** [comment]
@kelson42 #1443 has been merged. I will fix this issue now. 
In order to prevent the message from being repeated, in the title and message, I will just give the title along with an icon. 
This will provide the message, and at the same time, it will look like an alert too in order to make the user properly aware of what they're doing.
