### ISSUE TITLE
Input methods are broken in search

### ISSUE THREAD

**Issue by danielzgtg** [kiwix/kiwix-android#1818]
**Describe the bug**

When searching for an article, kiwix-android messes with the text box in a way that breaks many forms of input.

**Expected behavior**

To be able to enter text properly in the text box, just like in version 3.1.3.

**Steps to reproduce the behavior:**

1. Tap on the search icon in the app bar
2. Do one of the following:
a. Type fast with an English keyboard. Notice that some letters are lost.
b. Use Japanese handwriting input. Notice that you can only enter one stroke before the character disappears.
c. Use Chinese handwriting input. Notice the same problem as with Chinese
d. Type with Japanese flick input. Notice that the word being typed in deselected. Entry of neither dakuten, handakuten, nor Kanji work.
e. Type with Japanese QWERTY input. Notice the same problem as with flick input. No Japanese at all can be typed, only fullwidth Latin.

This is a nuisance for English, Chinese, and other languages that don't use selection.

This bug completely prevents any Japanese from being typed.

**Screenshots**

Japanese flick input being broken in kiwix-android article search:

![Screenshot_20200225-173225](https://user-images.githubusercontent.com/25646384/75293837-0a526f00-57f5-11ea-8067-c631539cb6c6.jpg)

Japanese flick input working in the system launcher search (it worked similarly in kiwix-android 3.1.3):

![Screenshot_20200225-173232](https://user-images.githubusercontent.com/25646384/75293840-0cb4c900-57f5-11ea-9987-6ae453dc1e3b.jpg)

**Environment**
- Version of Kiwix Android : 3.2.0
- Device : OnePlus 7 Pro
- OS version : OxygenOS Beta 9

This was working fine with version 3.1.3.

**Comment by kelson42** [comment]
@danielzgtg Which version of Kiwix?

**Comment by macgills** [comment]
Ah this is a bug from us rendering the text as part of the state, we can stop doing this and the bug will disappear

**Comment by macgills** [comment]
Or actually it could just be the debounce on the viewState in SearchViewModel, that can be safely removed now I would believe

**Comment by kelson42** [comment]
@macgills A bit worried by that bug even if I can not fully get it or estimate how bad would be the impact. What is your guess about the user impact?

**Comment by macgills** [comment]
Well very bad for Japanese users, search is unusable. We can halt 3.2.0's release (currently at 25%) and prep 3.2.1?

**Comment by kelson42** [comment]
@macgills Japanese users, or Japanese, Arabic, Chinese, ...? Yes a 3.2.1 seems to make sense to me here.

**Comment by macgills** [comment]
I will create a hotfix. If @danielzgtg is willing to test it I would be appreciative as I don't trust my ability to verify I am entering japanese/arabic/chinese handwriting correctly

**Comment by danielzgtg** [comment]
Sure

Additionally, you don't need to type any other languages. Just handwrite the English lowercase letter "i" in search. That is also broken and is broken in the same way as other input methods.

**Comment by macgills** [comment]
Okay, no need for you to test, the fix is working. Thank you for the report @danielzgtg , very helpful
