### ISSUE TITLE
Night Mode UI is not properly translated/translaable

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1824]
See the screenshot

![image](https://user-images.githubusercontent.com/1029718/75390256-3f8bb980-58e8-11ea-9483-ac671a8db58c.png)

It looks like "On", "Off", "Auto" are hardcoded string?

**Comment by dipu989** [comment]
@kelson42 I would like to resolve this!

**Comment by macgills** [comment]
```
  <string-array name="pref_night_modes_entries">
    <item>On</item>
    <item>Off</item>
    <item>Auto</item>
  </string-array>
```

It hasn't been translated by TW, I can't remember if they handle `string-array`s well

**Comment by dipu989** [comment]
@macgills We want the "On", "Off" and "Auto" in their respective language once selected, not in English every time! Is this what we want to resolve in this ticket?

**Comment by macgills** [comment]
We want to add Arabic translations for the strings. Our translations are handled by Translatewiki, a lot of the process is automated so my concern was it was not picking up the `string-array` declaration.

We can fix this with a little layer of indirection if that is the case eg:
```
<string-array name="pref_night_modes_entries">
    <item>@string/on</item>
     .
     .
     .
  </string-array>
```

**Comment by macgills** [comment]
@yash982000 you may need to comment here before I can assign you

**Comment by yashk2000** [comment]
@macgills can I take up this issue?

**Comment by macgills** [comment]
@yashk2000 assigned. Please look to the previous PR for existing comments
