### ISSUE TITLE
Last Opened Zim file Tab gets closed if we open a new zim in another Tab.

### ISSUE THREAD

**Issue by 4shutosh** [kiwix/kiwix-android#1834]
**Describe the bug**
Previously Opened Tab gets closed automatically when we try to open a **different** zim file in another tab.
 

**Expected behavior**
Both the zim files should be open in their respective tabs

**Steps to reproduce the behavior:**
1. Open a zim file
2. Open a new tab from Tabs manager
3. Open another zim file (from Home Screen or Library)
4. See error (Previously opened zim file tab is disappeared)

**Screenshots**
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/53831987/75569867-f3717e00-5a7b-11ea-88be-1dbb84ef19fb.gif)

**Environment**
- Device : Pixel 4
- OS version : Android 10

If the Issue is valid, I would like to work on this.

**Comment by 4shutosh** [comment]
This Issue is not produced is we open the same zim file in another Tab
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/53831987/75571171-ab078f80-5a7e-11ea-9950-e19c1d226d37.gif)

**Comment by 4shutosh** [comment]
I would like to kindly ask @kelson42 @macgills to check this issue.

**Comment by kelson42** [comment]
This is a feature not a bug. For now we don’t handle multizims.

**Comment by yash1ts** [comment]
@kelson42 @macgills  I think the app should show Some information when we open other zim file, like an alert "Only one file can be opened at a time. This will close all other tabs.". Because it feels like a bug every time you open a new file.
