### ISSUE TITLE
Convert WifiDirectManager to Kotlin

### ISSUE THREAD

**Issue by rohanprasadofficial** [kiwix/kiwix-android#1835]
This includes the conversion of code of WifiDirectManager to Kotlin. It is an enhancement. 

I will be converting the WifiDirectManager.java to WifiDirectManager.kt

After completion WifiDirectManager.kt will support all related task that were supported by WifiDirectManager.java

**Comment by rohanprasadofficial** [comment]
@macgills @kelson42  i am working on this , can you assign it to me.

**Comment by yash1ts** [comment]
@macgills I would like to work on this.

**Comment by yash1ts** [comment]
@macgills app:detekt fails complaining TooManyFunctions 28/11. How can I reduce the number of functions there are a lot of them?

**Comment by macgills** [comment]
we can consider this a legacy problem as you are converting an existing class. Run `gradlew detektBaseline` and this will add the existing issues to an ignore list.

This is the exception when you should do this, most of the time you should fix the issues detekt tells you about

**Comment by yash1ts** [comment]
Ok

**Comment by yash1ts** [comment]
Now l am getting lintDebug error saying requires checkpermission ACCESS_FINE_LOCATION. LocalFileTransferActivity checks for ACCESS_COARSE_LOCATION. Should I change that to fine location or do I need to ignore this error too?

**Comment by macgills** [comment]
It is easier if I can see it, if you need feedback push your changes and open a draft PR.

You can bypass the commit hook by using ` --no-verify` if using git for commandline or there is an option if you commit through AS
