### ISSUE TITLE
Convert intro module to Kotlin

### ISSUE THREAD

**Issue by AjayThakur12** [kiwix/kiwix-android#1836]
Converting entire Intro module into Kotlin which is currently in java.

**Comment by AjayThakur12** [comment]
@macgills  @kelson42  i started working on it please assign it to me

**Comment by AjayThakur12** [comment]
![gs1](https://user-images.githubusercontent.com/29337604/75630189-63177280-5c0e-11ea-9ed3-34dcf36c682f.PNG)

facing this issue while committing tried to solving using stackoverflow and Googled it but not able to solve

**Comment by srv-twry** [comment]
@AjayThakur12 None of these looks like an error. All of them are deprecation warnings as far as I understand. The app should still work.

**Comment by AjayThakur12** [comment]
@srv-twry thank you for your feedback. I future i follow same

**Comment by macgills** [comment]
Closing this, conversion should be class based, not module
