### ISSUE TITLE
Convert local_file_transfer module to kotlin

### ISSUE THREAD

**Issue by KushagraK123** [kiwix/kiwix-android#1838]
Converting local_file_transfer module to kotlin from java

**Comment by KushagraK123** [comment]
I am working on this issue please assign it to me.

**Comment by NullByte08** [comment]
Can I work on this issue? @kelson42

**Comment by kelson42** [comment]
@KushagraK123 You are still working on it?

**Comment by KushagraK123** [comment]
No

**Comment by macgills** [comment]
I am closing this ticket, nobody should be taking a module, @NullByte08 check the rules of #1826
