### ISSUE TITLE
Change the flow of starting a server to host books

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1841]
Currently, when a user clicks on `Start Server`, a dialog is shown instructing the user to turn on their wifi hotspot. While this is fine for a user when using the app for the first time, but once a user knows that the hotspot has to on before starting the server, this dialog starts feeling like a hindrance.

**Describe alternatives you've considered**
I suggest that when a user clicks on start server, instead of showing the dialog, we straight away proceed as if the user has already turned on the hotspot. In case the hotspot isn't on, then we can show the dialog instructing the user to turn on the hotspot. This way people who already know how to use this feature won't have any problems and new users will also get to know that the hotspot has to be turned on. 

**Additional context**

If this issue is genuine, I would like to work on it.

**Comment by yashk2000** [comment]
@macgills @kelson42 what are your opinions on this?

**Comment by yashk2000** [comment]
@kelson42 @mhutti1 @abdulwd @macgills could you please provide your views on this?

**Comment by mhutti1** [comment]
@yashk2000 do you have a concrete way of knowing if the hotspot is on?

**Comment by yashk2000** [comment]
We will proceed as if the hotspot is on. 
Right now, a dialog is shown. It has two options: Proceed and turn on the hotspot. 
A user can press proceed even if the hotspot isn't now. In this case(when hotspot isn't on), an overridden method, `onServerFailedToStart` is called. In this function, currently, a toast is shown showing that the server failed to start. 

So instead we will let this function handle the case when the hotspot isn't on and show a dialog telling user that he needs to turn on the hotspot along with the option to go to settings. 

I think this should be done as right now the dialog is shown every time even if the hotspot is on and this becomes a bit of a hindrance for experienced users. This solution will allow new as well as experienced users to have ease of access.

**Comment by yashk2000** [comment]
@mhutti1 We will proceed as if the hotspot is on.
Right now, a dialog is shown. It has two options: Proceed and turn on the hotspot.
A user can press proceed even if the hotspot isn't now. In this case(when hotspot isn't on), an overridden method, onServerFailedToStart is called. In this function, currently, a toast is shown showing that the server failed to start.

So instead we will let this function handle the case when the hotspot isn't on and show a dialog telling user that he needs to turn on the hotspot along with the option to go to settings.

I think this should be done as right now the dialog is shown every time even if the hotspot is on and this becomes a bit of a hindrance for experienced users. This solution will allow new as well as experienced users to have ease of access.

**Comment by mhutti1** [comment]
Ok that sounds like a good idea to me.

**Comment by macgills** [comment]
Comment from #2075 
>@abdulwd @macgills given that the user needs to be told to either turn on the hotspot or keep devices on the same wifi network, I think this dialog will be necessary.
So should #1841 be closed?

So our options are
1. Always show a dialog saying connect to wifi or hotspot
1. Only show a dialog if connected to neither(?)

Or are there more? can we identify the scenario of wifi vs hotspot? show a warning when you are not the hotspot "For people to view your hosted content they must be connected to the same wifi as you"

I have no firm opinion but I think this issue can continue as it seems we may need to do more discovery on this feature and the possibilities

**Comment by yashk2000** [comment]
@macgills we can show the dialog when neither is connected. If either wifi or hotspot is enabled, we'll allow the user to create a server. 

We can also check whether wifi is enabled or hotspot is enabled. So in the case just wifi is on, we can show an additional warning, saying this instead of the dialog. 

I believe the second option will be better as it will cover all the test cases. Please let me know what you think. I'll implement it that way once #2075 in merged.

**Comment by macgills** [comment]
> So in the case just wifi is on, we can show an additional warning, saying this instead of the dialog.

This sounds good to me in conjunction with

> Only show a dialog if connected to neither
