### ISSUE TITLE
Intro UI image overlay with text in landscape mode

### ISSUE THREAD

**Issue by AjayThakur12** [kiwix/kiwix-android#1842]
**Describe the bug**
When we install app Intro Activity appears. UI of intro activity not properly aligned in landscape mode

**Expected behavior**
UI of intro activity properly aligned in landscape mode

**Steps to reproduce the behavior:**
1. Install app
2. When intro activity comes change to landscape mode

**Screenshots**
![__1](https://user-images.githubusercontent.com/29337604/75702659-e18e1600-5cdb-11ea-990f-75a260efbe4f.jpeg)

![__2](https://user-images.githubusercontent.com/29337604/75702681-e81c8d80-5cdb-11ea-9715-5677c228f307.jpeg)

**Environment**
- Device : redmi note 4
- OS version : Android 8

**Want to work on it**
-Yes

**Comment by AjayThakur12** [comment]
@kelson42  should stop landscape mode during Intro activity

**Comment by mhutti1** [comment]
I think the correct approach would be to fix the bug rather than disable landscape mode for the start.
