### ISSUE TITLE
Persist Searchview Expanded state in LibraryFragment on Configuration Change

### ISSUE THREAD

**Issue by AjayThakur12** [kiwix/kiwix-android#1848]
**Describe the bug**
When we search for some activity in Library Activity and then switch to landscape mode then searched text not remain same
**Expected behavior**
Searched text not remain same

**Steps to reproduce the behavior:**
1. Click on Download Books
2. Search in Library Activity
3. Switch to landscape mode 
4. Searched test not remain same

**Screenshots**
Portrait mode  --

![ok2](https://user-images.githubusercontent.com/29337604/75810432-9560d580-5db0-11ea-9ad9-2ca14d4b7d0c.jpeg)

**Landscape mode --**
![ok1](https://user-images.githubusercontent.com/29337604/75810439-998cf300-5db0-11ea-89cd-27a5c95379f4.jpeg)

**Environment**
- Device : Redmi Note 4
- OS version : Android 8

**Additional Information**
We can use shared preferences to save text when activity re-created on switching to landscape mode.

**Working On this**
->Yes

**Comment by yashk2000** [comment]
@AjayThakur12 why do we need to use shared preferences to save the text?
Can't we use onSavedInstanceState?

**Comment by srv-twry** [comment]
> Can't we use onSaveInstanceState?

This is a better idea.

Although in my opinion, the best way would be to create a `ViewModel`. They're lifetime aware. https://developer.android.com/topic/libraries/architecture/viewmodel

**Comment by macgills** [comment]
There is a viewmodel but they only last configuration changes, viewmodels also have a saved state for persisting items in so that should also be used if we want the activity to be recreated well.

The problem here is probably the ui state doesn't get recreated well, notice how the list is actually filtered by an invisible search term

**Comment by NullByte08** [comment]
@abdulwd Can you assign this to me ?

**Comment by MohitMaliFtechiz** [comment]
hi , 

this issue is not reproduce able in latest 3.6.0.

**Comment by kelson42** [comment]
@AjayThakur12 This bug seems to have been fixed already in one of the latest versions. Thank you anyway for reporting.
