### ISSUE TITLE
Search history should keep track of more than 5 items

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1850]
IMO we could save up to 100 items.

**Comment by kelson42** [comment]
@deborahlow97 That might be one for you?

**Comment by deborahlow97** [comment]
> @deborahlow97 That might be one for you?

Sure! 😀

**Comment by deborahlow97** [comment]
@kelson42 Just out of curiosity, is there a reason for showing 100 items 🤔?

**Comment by kelson42** [comment]
@deborahlow97 No, 5 is just too few.
