### ISSUE TITLE
Kiwix Bug Report: Download stuck on pending

### ISSUE THREAD

**Issue by an0nym767** [kiwix/kiwix-android#1854]
If I try to download something from inside the Kiwix reader (on mobile) it just gets stuck on pending and stays there forever, even with fast wifi. During that there is no download running and also no major data transmission, it just seems like it does nothing. That happens everytime I try to download something.

I open the app, tap on "Download Book" then tap on "online" type something into the search bar ("Wikipedia" in this particular case, but it happens with every book), then I scroll down, tap on the book (Wikipedia, english, 77 gigs) and it just shows this small downloading bar which is empty and shows "pending" forever. Trying to cancel the procedure does not do anything at all either. 

I changed in my settings,that everything gets downloaded onto my micro sd which has about 400gigs and is near empty, so storage should not be a problem, also my device is not rooted, and the micro sd card is not modified in any way.

I would appreciate your help :)

**Comment by kelson42** [comment]
@an0nym767 Thank you for your bug report.What is the version of Kiwix? What is your version of Android?

**Comment by an0nym767** [comment]
Oh yeah, I forgot to mention, my phone (Huawei P smart) is running on Android 9.1.0.163 and the Kiwix Version is the newest one in the Play Store (3.2.1)

**Comment by kelson42** [comment]
@an0nym767 Would you be able to provide the android log during 60 minutes after the download begin?

**Comment by kelson42** [comment]
@mhutti1 @abdulwd Woukd you please help here why Kiwix is buggy for @an0nym767?

**Comment by an0nym767** [comment]
Is there a way to access the log without a pc/laptop?

**Comment by kelson42** [comment]
@an0nym767 I always do it through the PC, but I guess there is app to do so.

**Comment by an0nym767** [comment]
Aand I forgot to mention that it is still on pending after reopening the app, so I will just let it run for 60mins and then send the log. Is there any private information contained inside the log? If yes, how do I get rid of it? And could I directly send you the log in some kinda private message? If yes, how?

**Comment by kelson42** [comment]
@an0nym767 I recommend to close all other apps (or just restart the device). Then we shoukd not have private things in it. You can send the logs at kelson -at- kiwix.org per email.

**Comment by an0nym767** [comment]
Sent it, I hope I made no mistake, I am pretty unexperienced when it comes to such things

**Comment by an0nym767** [comment]
So what do I do noe

**Comment by an0nym767** [comment]
I've tried it on another android device now, my tablet, and am currently downloading it onto the micro sd card, so when I take the micro sd out of my tablet after the download finished and put it into my phone, will I be able to read the Wikipedia on my sd, which was downloaded from Kiwix on my tablet, on my phone through the Kiwix reader? Both versions of kiwix on both devices are the same. Also I've tried to download a few other books on my tablet for testing purposes and the bigger the file was, the longer it was on "pending" before being on "Process" and actually downloading, so I think that when downloading 77gigs you gotta let it sit a few hours on pending, before it actually starts the download.

**Comment by kelson42** [comment]
@an0nym767 Would you please just try to wait these few hours to confirm this theory?

**Comment by an0nym767** [comment]
Ok, no problem

Kelson <notifications@github.com> schrieb am Do., 5. März 2020, 06:48:

**Comment by an0nym767** [comment]
Ok, now things get kinda weird: My 78 gigs download on my tablet worked perfectly, while my Download on my phone is still stuck on pending, which isn't really a surprise because I took the sd card outta the phone, but yesterday I tried to download something else, just for testing, a really small file, into my internal storage, and it's still stuck on pending, now comes the weird part, when I try to download a file now, even if it's really small (tried it with a 12mb file) it says there is no free storage and then says that the free storage space is 0 Bytes, while I have far enough storage for a 12mb file
![Screenshot_20200306_173225_org kiwix kiwixmobile](https://user-images.githubusercontent.com/61789896/76102592-835d7d80-5fd0-11ea-8035-459d215af888.jpg)

**Comment by ha-kg** [comment]
I have a similar problem. I cannot download
Wikipedia_de_all_maxi_2020_01 Zim.
Download stopped and is shown in the Library as pending. I want to
cancel the pending download it will not be cancelled. Even after several
uninstall and install of Kiwix (Includig Restart of the Smartphone) I see in the Library "pending"
I copied the file from the smartphone to the SD-card in the same folder
were is Wikivoyage.zim.
And I can open the Wikipedia_de_all_maxi_2020_01 Zim through the files
explorer.
But it will not be included in the library and the download
status remains "pending".

As a solution for the first time I linked the file to the Homepage, were I can open it directly

Hartmut

**Comment by mhutti1** [comment]
I'm really not sure whats going wrong here and don't think I would be able to work it out without a log.

**Comment by ha-kg** [comment]
Please find enclosed the log file as well as a screenshot
Hartmut
![Screenshot_20200310-142939_Kiwix](https://user-images.githubusercontent.com/25171599/76318424-f96a2900-62dd-11ea-851c-b9da77df5d73.jpg)
[logcat.txt](https://github.com/kiwix/kiwix-android/files/4312738/logcat.txt)

**Comment by an0nym767** [comment]
If you have access to a tablet, I would recommend trying it on a tablet, because I had the exact same problem, it just stayed on pending all the time on my phone, but it worked on my tablet (started downloading about half an hour of being on "pending"). I dont know if this is a problem related to android,because my phone is running on android 9 and my tablet on android 7. Maybe just letting it sit on pending for an hour helps, because even on my tablet, as I mentioned, it didnt go to "In Progress" directly but only after staying on pending beetween half an hour and an hour, depending on the file size.

**Comment by ha-kg** [comment]
The problem exists on Tablet and Smartphone, Samsung S7 with Android 8.0 and a Samsung Tab A with Android 8.1. Both not rooted

**Comment by macgills** [comment]
I'd say that it is trying to read the storage of the removed sd card and returning 0, a separate bug. Have you tried explicitly setting your preferred storage to internal?

The main problem here is the behaviour of our downloading library, it has to preallocate space before it starts downloading and on sd cards this can be painfully slow. This option can be changed (ie write as you download) but I think it might result in worse performance and people too easily consuming their free space as a user could theoretically start 2 giant downloads that exceed their space when combined and then the downloads would be fighting each other.

**Comment by macgills** [comment]
Okay so there are a few issues here

1. Allocating space for a large file can take a significant amount of time on some sd cards
1. We do not communicate to the user well that we are allocating space and it could take a while
1. We don't automatically switch the preferred storage if a user removes the sd card that was set as the preferred storage
1. We don't stop a download that is in the allocating phase

Aside from the first one I would assess the rest are bugs to be fixed, @kelson42 I would move to close this issue and create 3 issues based on 2-4

**Comment by kelson42** [comment]
@an0nym767 Thank you again for your bug report. We will try to implement as much of possible of the three tickets which are consecutive to your report. Please subscribe to them if you want to be kept informed.
