### ISSUE TITLE
Flickering text when expanding info from 'help' menu.

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#1855]
**Describe the bug**

When expanding "What does kiwix do?" and "Where is the content?" the text flickers by going up and down fast. (See vid. below)

**Expected behavior**

The expanded text/view should not flicker.

**Steps to reproduce the behavior:**
1. Open kiwix app.
2. Click three dots in upper right corner.
3. Click the help option.
4. Expand "What does kiwix do?" or "Where is the content?" a couple of times. The expanded views should flicker. 

**Screenshots**

[Video with higher framerate, as the issue is not visible in 10fps](https://photos.app.goo.gl/2n2CafAUJoNT4iQ77)

**Environment**
- Version of Kiwix Android : 3.2.1 Build: 6230201
- Device : OnePlus 5
- OS version : 9.0.10 OxygenOS

**Comment by sonusourav** [comment]
This can be solved simply by increasing the animation time.
@Frans-Lukas Are you working on this issue?

**Comment by Frans-Lukas** [comment]
No I was not working on it. Thanks for fixing it!
