### ISSUE TITLE
Loading icon does not disappear if there is no internet connection

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#1856]
**Describe the bug**

When in flightmode or without internet and going from the start screen/library to the 'Download books'/online view the loading icon will never disappear. 

**Expected behavior**

If there is no internet connection the loading icon should not appear at all. Just the text saying that there is no internet connection. 

**Steps to reproduce the behavior:**
1. Enter flight mode or disable your internet connection.
2. Open kiwix.
3. Click on Download Books
4. The loading icon will keep rotating with a message of 'No network connection.' until a connection is found and the zim metadata has been downloaded. 

**Screenshots**

![88138277_2939901259387784_7018593817183911936_n](https://user-images.githubusercontent.com/22193232/75892792-35ab0e80-5e32-11ea-8b1d-37517f6aeef6.jpg)

![88189311_994388140975906_7586015643309178880_n](https://user-images.githubusercontent.com/22193232/75893028-891d5c80-5e32-11ea-89ea-9c929ea78f31.jpg)

**Environment**
- Version of Kiwix Android : 3.2.1 Build: 6230201
- Device : OnePlus 5
- OS version : 9.0.10 OxygenOS

**Comment by kelson42** [comment]
Agree

**Comment by waahm7** [comment]
@kelson42 I would love to do this. Can you please assign this to me?
