### ISSUE TITLE
Add unit tests for NewBookDao

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#1864]
### Problem
Unit tests are missing for `NewBookDao`

### Solution
Add unit tests for `NewBookDao`

### Additional Context
Parent issue: #1827 

### Working on it?
Yes

**Comment by srv-twry** [comment]
This can be assigned to others.

**Comment by ashutosh1919** [comment]
@srv-twry , i want to work on this issue. Please assign it to me
