### ISSUE TITLE
Search result selection is not haptic

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#1866]
Steps:
* Load a ZIM file
* Make a search and select any result

What I get:
* The item select is not visually higlighted before the content is loaded. The article is properly loaded.

I want:
* To see clearly, by a highlight operation, which item i have chossen, before the content is loaded... like in any list.

**Comment by dipu989** [comment]
@kelson42 Would like to work on this! Please assign.

**Comment by Frans-Lukas** [comment]
I'm assuming you are not working on this as well @dipu989. I'd like to work on this if that is the case.

**Comment by Frans-Lukas** [comment]
@kelson42 I am not sure what you mean by this. Currently, when I select an item, it is 'highlighted' by being tinted gray for half a second after of which the page loads. Can you give an example of a list item being more clearly highlighted in some other app or show an image?

**Comment by macgills** [comment]
There was a PR that added this effect very recently if I am not mistaken

**Comment by Frans-Lukas** [comment]
@macgills ok, so this is probably resolved then?

**Comment by macgills** [comment]
If you can post a screenshot here and validate it with @kelson42 then we can happily close it

**Comment by macgills** [comment]
@kelson42 this looks fine to me, closing
