### ISSUE TITLE
App stops when trying to navigate between tabs after a tab is closed

### ISSUE THREAD

**Issue by dipu989** [kiwix/kiwix-android#1868]
**Describe the bug**

The app stops when user tries to navigate between different tabs after closing a tab. 

**Expected behavior**

App should not close unexpectedly

**Steps to reproduce the behavior:**
1. Open 2 or more tabs.
2. Close any one of the tabs.
3. Click on the tabs display point.
![IMG_20200308_121451](https://user-images.githubusercontent.com/31280303/76157970-79ee2580-6136-11ea-8465-5571989dc9d2.jpg)
4. App crashes.

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : realme X
- OS version : Android 9

**Comment by kelson42** [comment]
That sounds really bad... but I can not reproduce it.

**Comment by dipu989** [comment]
Attaching a screenshot - 
![Screenshot from 2020-03-08 15-55-22](https://user-images.githubusercontent.com/31280303/76161030-68684600-6155-11ea-8491-6321793922f1.png)

**Comment by kelson42** [comment]
@dipu989 You want to fix it?

**Comment by dipu989** [comment]
Sure, Working on #1866 right now! Would fix this after completing the previous one.

**Comment by Frans-Lukas** [comment]
@dipu989 Are you still working on this?

**Comment by macgills** [comment]
I haven't heard from @dipu989 in a while on any of the other PRs they have open so assigning this to @Frans-Lukas

**Comment by Frans-Lukas** [comment]
@macgills Thanks!
