### ISSUE TITLE
Night Mode disappears for a split second 

### ISSUE THREAD

**Issue by Scarlet0103** [kiwix/kiwix-android#1869]
**Describe the bug**

Whenever I open a downloaded file, for a split second the night mode disappears. 

**Expected behavior**

Night mode should not disappear.

**Steps to reproduce the behavior:**
1. Open the app and click download books
2. On the online download one of the file
3. click on the donloaded file on the home page
4. The file is opened while showing described bug.

**Screenshots**

![ezgif-3-2b3c4c47c457](https://user-images.githubusercontent.com/59963912/76170087-b5273d80-61a4-11ea-88c0-5481840c4f92.gif)

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Redmi Note 4
- OS version : Android 7.0

**Logs**

**Comment by Frans-Lukas** [comment]
Are you working on this? @Scarlet0103 Otherwise I'd like to work on it.

**Comment by macgills** [comment]
@Frans-Lukas you are assigned. @Scarlet0103 I hope you weren't working on it
