### ISSUE TITLE
View source

### ISSUE THREAD

**Issue by danielzgtg** [kiwix/kiwix-android#1871]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to view either the HTML source of the articles. This would be especially useful while waiting for visual bugs like openzim/mwoffliner#1033 to get fixed, or while debugging them.

**Describe the solution you'd like**

To add a "view source" button in the overflow menu. The button would display the source just like Chrome or Firefox for Android.

**Describe alternatives you've considered**

- Wikitext would be more useful, but I don't think it's possible with ZIM.
- Plugging into a computer to view source is not convenient.

**Comment by kelson42** [comment]
I’m against this, we should not build feature to debug. In partuculat that one because the HTML is exactly the one in the ZIM and we have tools to know how thw ZIM content looks like.

**Comment by macgills** [comment]
If you have a debuggable version of the app you can inspect our webpages with chrome dev tools via a computer, if your device is connected. More info [here](https://developers.google.com/web/tools/chrome-devtools/remote-debugging) @danielzgtg
