### ISSUE TITLE
Number of tabs opened does not change instantly on undoing

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1872]
**Describe the bug**
Even after undoing the closing of a tab, the number change (increase) in the tab switcher is not reflected. 

**Expected behavior**
The change in the number of tabs ( i.e. increase and decrease ) should be displayed at the same instance of that of undoing. However, currently, it is changing when you open some other tab.

**Steps to reproduce the behavior:**
1. Open multiple tabs.
2. Close a tab and select any tab before the undo option disappears.
3. Click undo.
4. Now, click on the tab switcher. The number displayed in the tab switcher and no. of tabs opened is different.

**Screenshots**
![undo_gif](https://user-images.githubusercontent.com/34706326/76206677-7afc8100-6222-11ea-83fa-f670dc211614.gif)

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Redmi 4
- OS version :  Android Nougat

**Logs**

**Comment by 4shutosh** [comment]
Hey! @sonusourav 
You correctly pointed out the issue.
Are you willing to work on this issue?
This can be solved by calling ` tabsAdapter.notifyDataSetChanged();` 
under the `snackbar.setAction()` for Undo after the `tabsAdapter.notifyItemInserted(index);` 
in the `CoreMainActivity.closeTab`

**Comment by sonusourav** [comment]
Hey @4shutosh , I am working on the issue.

**Comment by 4shutosh** [comment]
Proceed with it! @sonusourav
