### ISSUE TITLE
Unusual behaviour on pressing back button

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1881]
**Describe the bug**

In some Zim files, on pressing back button lands on the home screen while in some others it exits the app. I can't guess the pattern in which case first happens and in which case second happens.

**Expected behavior**

In all cases, it should be the same. Either the app should exit or home screen should appear.

P.S.: It would be better if home screen appears.

**Steps to reproduce the behavior:**
Case is random so not necessary it would work on following the steps.

1. Open zim files and press back button and observe.

**Screenshots**

[Link](https://imgur.com/htuwe4G)

**Environment**
- Version of Kiwix Android : Kiwix 3.2.1
- Device : Redmi 4
- OS version : Nougat

**Comment by macgills** [comment]
It should exit the app to keep the behaviour we have had unless @kelson42 wants to chime in and say it should return to the home screen to select a zim.

What is probably happening is 2 instances of MainActivity are created somehow, this should be easy to detect.

**Comment by Frans-Lukas** [comment]
What is the intended way of navigating back to the zim browser from an opened zim file? The only consistent way I have used is to close all tabs.

**Comment by macgills** [comment]
Open a new tab from the + in tabswitcher, this presents the list for you to choose a new book or the same book. Choosing a new book will close all the tabs that were open of another book

**Comment by Frans-Lukas** [comment]
@macgills Okay! I did not know about the + button, thanks.

**Comment by kelson42** [comment]
@macgills @Frans-Lukas In any case, the behaviour should be consistent. IMO should come back to home screen and then exit if back called an other time.

**Comment by Frans-Lukas** [comment]
@kelson42 I agree when comparing with how a browser handles back navigation as well as Googles recommendation:

 "Every app you build has a fixed start destination. This is the first screen the user sees when they launch your app from the launcher. 
...
This is also the last screen they see before exiting the app. [using back navigation]" 
 https://developer.android.com/guide/navigation/navigation-principles

**Comment by sonusourav** [comment]
So, should I proceed with bringing the user to home screen instead of directly escaping?

**Comment by macgills** [comment]
Lets go home screen (aka list of books under the kiwix banner) then, I never really knew why it worked how it did anyway.
