### ISSUE TITLE
Margin in webview layout should be removed

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#1883]
**Describe the bug**

When browsing a zim file there is a margin left and right to the content. This means less horizontal content can be shown, and in some cases the user has to scroll to see all the horizontal content. If comparing to any other browser, the web content does not have a margin.

**Expected behavior**

There should be no margin of the content of a zim file. The margin should be decided by the styling of each individual zim file. I.e. HTML margins.

**Steps to reproduce the behavior:**
1. Open a zim file.
2. Scroll left and right back and forth to see the white border/margin to the left and to the right. 

**Screenshots**

![ezgif-1-fa529f21fc54](https://user-images.githubusercontent.com/22193232/76414273-43631580-6397-11ea-97af-f15c60e947cf.gif)

**Environment**
- Version of Kiwix Android : 3.2.1 Build: 6230201

**I'd like to work on this if we agree that this is an issue.**

**Comment by kelson42** [comment]
I dont’t think you can fix that in this repo.

**Comment by Frans-Lukas** [comment]
@kelson42 Ah ok! Was looking for where the margin was specified but couldn't find it. Is it defined per zim file basis?
