### ISSUE TITLE
AUTO in night mode not working

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1884]
**Describe the bug**

The auto option in Night mode is not working.

**Expected behavior**

The theme should change based on the local time when AUTO option is selected one.

**Steps to reproduce the behavior:**
1. Go to night mode option in Settings.
2. Change to AUTO mode and observe.

**Screenshots**

![night](https://user-images.githubusercontent.com/34706326/76429361-f1d97b80-63d4-11ea-9837-730196dad5b8.jpeg)

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Redmi 4
- OS version : Nougat

**Comment by macgills** [comment]
Not on your version of android. Auto changes by `Battery Saver` like the device does if it supports it.

Feature has been implemented to spec https://developer.android.com/guide/topics/ui/look-and-feel/darktheme closing
