### ISSUE TITLE
Remove all "Surface to user" TODOs

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1887]
**Describe the solution you'd like**

Currently, there are a few TODOs which require some data to be shown to the user. These TODOs are present in:

- KiwixDatabase.java, line 192
- KiwixDatabase.java, line 195
- CoreMainActivity.java, line 1447
- KiwixTextToSpeeach.java, line 90
- ZimContentProvider.java, line 94
- KiwixTextToSpeech.java, line 311

A suitable message shall be shown to a user in form of a toast or a snackbar message. 

**Additional context**

I would like to work on this issue.

**Comment by kelson42** [comment]
@macgills You confirm this ticket should be implemented?

**Comment by macgills** [comment]
KiwixDatabse is deprecated so nothing should be done there. I'd also ignore ZimContentProvider, mostly because I will be removing it

The others are all fair game, I say work on it
