### ISSUE TITLE
Converting toasts to snackbars.

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1888]
In a lot of places in the application, we are using toasts. Unless we need a message to be displayed even after an activity is destroyed, we should use snackbars. 

Benefits of snackbars over toasts:
- More customizable than a toast
- In certain places, due to inappropriate permissions, a toast is shown. Here instead, a snack bar with an action can be shown. This will enhance the UX of the application immensely. 
- Can be swiped off the screen
- Look better than toasts, hence make for a good UI along with good UX. 

Only in places where a message needs to be displayed even when the activity is destroyed, or in the background, we should continue using toasts. For example, when the server in host books is stopped using the notification, the user might not even be in the app and might be on the phone home screen. In a case like this, a toast should be shown. 

**Additional context**

If this is an appropriate issue, I would like to work on it.

**Comment by kelson42** [comment]
@mhutti1 @abdulwd @macgills Any opinion on this proposal?

**Comment by abdulwd** [comment]
@yashk2000 Can you list the places where do you want to use snackbars? I'm not in favor of using them too frequently as they block the bottom screen.

**Comment by yashk2000** [comment]
@abdulwd I intend to replace toasts in the following places:

- KiwixMainActivity: The toasts showing "file not found" or "unable to open file"
- Toasts for clearing history, bookmarks, and notes
- Toasts for showing no internet: I intend to show a snackbar instead with the action to open network settings

**Comment by macgills** [comment]
Toasts should never block the bottom of the screen or no worse than a toast anyway, if there is interactable UI it should slide up like fabs do when a snackbar is shown.

These all seem like sensible locations to me.
