### ISSUE TITLE
TOC menu entries are wrong with new Wikipedia ZIM (with mobie layout)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#189]
Instead of each menu entry, "..." is displayed. Try with http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_2017-06.zim

**Comment by kelson42** [comment]
@mhutti1 If you could have a look to this quickly, that would be really helpful as this is a blocker to the release of the new version of the Wikimed app.

**Comment by kelson42** [comment]
@borisfba ping :)

**Comment by kelson42** [comment]
@borisfba @rashiq @mhutti1 @EladKeyshawn Could someone have a look to this? This is pretty urgent.

**Comment by mhutti1** [comment]
@kelson42 I will look at now. That is a big zim file.

**Comment by kelson42** [comment]
@mhutti1 Thx, you can work with http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_novid_2017-07.zim which is slightly smaller.

**Comment by kelson42** [comment]
@mhutti1 thx for that important fix.
