### ISSUE TITLE
Use Custom Chrome Tabs for opening external links

### ISSUE THREAD

**Issue by yash1ts** [kiwix/kiwix-android#1901]
**Is your feature request related to a problem? Please describe.**
When user clicks on an external link he is taken to browser. For example clicking "support Kiwix" and links present in books.

**Describe the solution you'd like**
It would be great if the link opens in the app, instead of depending on external browser.
We can use custom chrome tabs for this.

**Comment by kelson42** [comment]
I don’t want to change the Kiwix app in a Web browser.

**Comment by macgills** [comment]
@kelson42 this would just allow us to sort of theme the browser that opens when users open a link from Kiwix, just to clarify that point

**Comment by kelson42** [comment]
>  this would just allow us to sort of theme the browser

@macgills What does that mean? Why we would need that? Does that mean opening external Web pages in Kiwix?

**Comment by macgills** [comment]
https://developer.chrome.com/multidevice/android/customtabs You can see their example here. Sometimes a zim file has an external link eg a stackexchange question that links to another website.

Right now we just launch the browser without much fanfare. I am largely indifferent to the feature.

**Comment by kelson42** [comment]
I don’t like the whole principle of this for Kiwix or any other app (like Twitter for example). I don’t really understand the added value but I suspect the increase of complexity it can bring.
