### ISSUE TITLE
Toast and snackbar shown together when downloading a large zim with insufficient memory

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1918]
**Describe the bug**
A toast and a snackbar are both shown when user tries to download a large zim and there's not enough storage. 

**Expected behavior**
Either a toast or a snackbar should be shown. Here, showing just a toast is not an option since the snackbar has an action. So showing just a snackbar with the required message is enough. 

**Steps to reproduce the behavior:**
1. Go to online section of the library
2. Try downloading a zim that will not fit in the internal storage of the phone
3. A toast, as well as a snackbar, is displayed

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Redmi K20 
- OS version : Android 10

**Screenshot**

![screencap](https://user-images.githubusercontent.com/41234408/77066277-db50a700-6a08-11ea-9160-907337fd7a54.png)

**Additional Context**
I would like to work on this issue.

**Comment by macgills** [comment]
We would also need to condense this information into the snack as if we just show the snack it is confusing
