### ISSUE TITLE
kiwix-build fails to build kiwix-android

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-android#192]
Since 3 days, daily builds made by `kiwix-build` fails.  (https://travis-ci.org/kiwix/kiwix-build/builds)

Between build 482 (https://travis-ci.org/kiwix/kiwix-build/builds/248569545) and build 483 (https://travis-ci.org/kiwix/kiwix-build/builds/248969369), nothing has changed in `kiwix-build`, `kiwix-lib` and `libzim`.
The only recent changes are on `kiwix-android` sides.

**Comment by mhutti1** [comment]
I though I might have fixed it last night I think some JNI imports got removed.

**Comment by mgautierfr** [comment]
Ok, I will wait the next daily build and close this issue if everything is ok.

**Comment by mhutti1** [comment]
Yeah. Sounds good. I can't test locally though as it fails to build. Is there a specific set of commands to build android?

**Comment by kelson42** [comment]
What is annoying is that travis-ci does not complain about it https://travis-ci.org/kiwix/kiwix-android

**Comment by mgautierfr** [comment]
> Is there a specific set of commands to build android?

I'm not sure to understand your question. But..

If you want to know how to build `kiwix-android` using `kiwix-build` :
```kiwix-build.py --target-platform android_arm kiwix-android```

If you want to know which commands are launched by `kiwix-build` to build `kiwix-android`, it is mainly copy of directory to have everything at the right place and launch of `graddle`.
(See "configure" step https://github.com/kiwix/kiwix-build/blob/master/dependencies.py#L354-L362
and "compile" step https://github.com/kiwix/kiwix-build/blob/master/dependency_utils.py#L358-L363)

**Comment by mgautierfr** [comment]
> What is annoying is that travis-ci does not complain about it

What is more annoying is that PR #159, #171, #172, #175, #179, #180, #185 and #186 have been merge whit a failed travis build.

**Comment by mhutti1** [comment]
That command fails for me. I will try again tonight. Those prs were made from remote forks and so fail by default. (they now pass).  We checked they compiled in Travis and tested locally.

**Comment by mhutti1** [comment]
Ok. This should be fixed. There were 2 errors causing it to fail.

1. The JNI was altered and as it isn't compiled in kiwix-android fell through the cracks
2. A hard coded string was added that for some reason passed the kiwix-android build but failed the kiwix-build build. I will open a new ticket for this.

**Comment by kelson42** [comment]
@mhutti1 thx!
