### ISSUE TITLE
Improper Text and no Icon in Alert Dialogue of History & Bookmarks

### ISSUE THREAD

**Issue by 4shutosh** [kiwix/kiwix-android#1927]
**Describe the bug**
The text "Delete History?" or "Delete Bookmark?" is quite grammatically wrong and should be improved

**Expected behavior**
Text: "Are you sure you want to delete History?" & "Are you sure you want to delete Bookmark?"
along with warning icon

**Steps to reproduce the behavior:**
1. Open History/bookmark
2. Delete one or more History/Bookmark

**Screenshots**
![Screenshot_20200320-172705~2](https://user-images.githubusercontent.com/53831987/77161670-3b5e5080-6ad0-11ea-9433-c2022c1139af.png)
![Screenshot_20200320-172714~2](https://user-images.githubusercontent.com/53831987/77161681-41543180-6ad0-11ea-9383-845b57897807.png)

**Environment**
- Version of Kiwix Android : latest develop
- Device : Pixel 4
- OS version : Android 10

**Comment by kelson42** [comment]
@mhutti1 @macgills Could you please confirm the "bug"?

**Comment by macgills** [comment]
I think the dialogs are fine as is https://material.io/components/dialogs/#alert-dialog the icons are unnecessary but our button text could use updating to "delete/cancel"

**Comment by 4shutosh** [comment]
> I think the dialogs are fine as is https://material.io/components/dialogs/#alert-dialog the icons are unnecessary but our button text could use updating to "delete/cancel"

Okay I'll change them

**Comment by 4shutosh** [comment]
@macgills We are still using warning icon in  options like `ClearAllNotes`, `ClearAllHistory` and `ExternalLinkPopup`. Do I also remove them?
And the texts are should be improved as well of the same.

**Comment by macgills** [comment]
The icons feel like a relic of pre material design, I think it would be best to get rid of them in favour of minimalism.

Improving the text is also good by me

**Comment by 4shutosh** [comment]
@macgills I've executed the changes in PR #1929 
Please review them.
