### ISSUE TITLE
Home Screen Widget for app

### ISSUE THREAD

**Issue by akkywadhwa** [kiwix/kiwix-android#1937]
**Is your feature request related to a problem? Please describe.**

Reading anything requires a user to open the app. The bookmarks/favourites seem to be underutilised as of now. 

**Describe the solution you'd like**

A home screen widget can be made which will make this lot easier. Please refer the sample screenshot below.
![image](https://user-images.githubusercontent.com/666752/77228298-60c08c80-6bac-11ea-8265-0d7682ac29b0.png)
A similar widget can be made to display the following :
- Bookmarks
- Downloads

**Comment by kelson42** [comment]
I don't ready see the added value/use case of this feature.

**Comment by macgills** [comment]
I hate widgets with a passion. That is mostly the API being horrible but still most widgets kind of suck and the user has to long press and add them themselves so the only ones that ever get used are the default ones that come with the phone. Plus we already have a widget and it doesn't work great.

**Comment by akkywadhwa** [comment]
Oh! I didn't take a look at the previous widget before. If widgets don't work great for us then maybe we can chuck this issue.
