### ISSUE TITLE
Allowing user to switch to mobile view 

### ISSUE THREAD

**Issue by akkywadhwa** [kiwix/kiwix-android#1938]
Most of the downloaded content libraries require the user to scroll right to see complete content. Check the screenshot below for reference.
![Screenshot_20200321-195237_Kiwix](https://user-images.githubusercontent.com/666752/77228566-4ab3cb80-6bae-11ea-84a6-835aaa250e8c.jpg)
This hampers the user experience. There must be an OPTIONAL feature to make this display mobile-friendly.

**Describe the solution you'd like**

Add a feature to make the display mobile-friendly.

**Comment by kelson42** [comment]
@akkywadhwa Could you explain please how you would do that on the Kiwix Android side?

**Comment by macgills** [comment]
Users can zoom out to see the content

or this is an option

![image](https://user-images.githubusercontent.com/3358282/78233065-1bb22980-74cd-11ea-9f3a-bdd4edf6960d.png)

We currently have that slider for "Zoom Preference" in our Settings which I don't see much point for? It would probably look nicer if the page just loaded into the width

**Comment by macgills** [comment]
@kelson42 there is something to be done on the android side, we could instruct the webview to load pages into the width of the webview as the linked PR may in facet do.

>We currently have that slider for "Zoom Preference" in our Settings which I don't see much point for?

Do you know the point of this setting? I don't and if we could remove it we cold go with a sensible default setting for the webview's zoom behaviour

**Comment by kelson42** [comment]
@macgills I think I will trust you on that one. I'm not sure myself that the zoom feature is necessary (anymore?). The point is that you devs need to be carefull to not try to fix HTML problems on the reader side. I think that could wrap-up my point :)
