### ISSUE TITLE
Add option to open a new tab to the menu

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1940]
**Is your feature request related to a problem? Please describe.**

Currently, the only way to open a new tab is to open the tabs section and click on the plus button. 

**Describe the solution you'd like**

Add an option in the menu to open a new tab. Using this, the user will not have to open the tabs section every time they want to open a new tab hence improving the UX of the app. 

**Additional context**

I would like to work on this issue.

**Comment by macgills** [comment]
You can also long click a link to open a new tab. I think we might have had "New Tab" in the menu before and that menu just has too much in it so we cut it out. Unconvinced we need this right now.
