### ISSUE TITLE
Bug in open link in new tab dialog

### ISSUE THREAD

**Issue by yash1ts** [kiwix/kiwix-android#1941]
**Describe the bug**
Message in open link in new tab is written twice.

**Expected behavior**
Message should be written only once.

**Steps to reproduce the behavior:**
1. Open any Zim file.
2. Long click on a highlighted work.
3. Dialog box appears with "Open link in new tab option" written twice.

**Screenshots**
![Screenshot_2020-03-21-20-56-06-096_org kiwix kiwixmobile](https://user-images.githubusercontent.com/45488341/77230048-84d59b00-6bb7-11ea-8e0e-8217e9265315.jpg)

**Comment by macgills** [comment]
@yash1ts do you want to work on this issue?

**Comment by yash1ts** [comment]
Yes, I will work on it.

**Comment by ashutosh1919** [comment]
@yash1ts , Can you please consider this PR since I have raised it? I am sorry, I started working on the PR before you commented yesterday 11 hours ago. That's why I couldn't see your comment.

**Comment by yash1ts** [comment]
@ashutosh1919 you should comment on the issue before starting to work. But since you already did the work, i think its fine.

**Comment by ashutosh1919** [comment]
> @ashutosh1919 you should comment on the issue before starting to work. But since you already did the work, i think its fine.

Sorry @yash1ts . And thanks for accepting PR. Please review the PR. Your approval is also needed since the issue was originally assigned to you.
