### ISSUE TITLE
Confirm delete dialog shown multiple number of time when deleting more than one zim

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1946]
**Is your feature request related to a problem? Please describe.**

Currently, when a user selects more than one zim to be deleted, a dialog is shown for every zim to be deleted. While this might be fine for 1-2 zims being deleted, but when a user will be deleting a large number of zims, this dialog will become a bit cumbersome. The user will have to press delete for every zim to be deleted.

**Describe the solution you'd like**

When more than one zim is being deleted, just show one dialog asking for confirmation from the user for deleting all the detected zims.

**Additional context**

I would like to work on this.

**Comment by 4shutosh** [comment]
I think asking confirmation for each zimFile is necesarry, because the app works offline and if the user does not have internet access it will be a hard time to download the zim file again (which usually is big in size).
It might be cumbersome for the users who have easy internet acces all the time but we target the people who don't have internet access all the time.

**Comment by yashk2000** [comment]
We will be showing a general dialog asking for confirmation before deleting. 
But imagine you're deleting even just 5 files. It will be too much for the user to click delete 5 different times. 
For confirmation, the user is first selecting the files by himself, then clicking the delete icon(aware that a trash button means deletion) and then a dialog will also be shown. 

Even apps such as photo applications don't ask for a confirmation while deleting multiple phots for each photo.

**Comment by yashk2000** [comment]
@macgills should I proceed with this?

**Comment by macgills** [comment]
It would be cool if we showed a custom dialog that you can scroll with all the titles of the zims you are about to delete. Individually deleting is slow and tedious

**Comment by yashk2000** [comment]
@macgills is a dialog like the screenshot below fine:

![screencap](https://user-images.githubusercontent.com/41234408/78664384-89a58900-78f1-11ea-84cd-c92850a8da66.png)

**Comment by macgills** [comment]
@yashk2000 show me what it looks like with so many entries that it has to scroll.

I don't think the numbering is necessary.

**Comment by yashk2000** [comment]
@macgills on it. I won't be able to download enough zims for this purpose though. I'll just make a custom list with my own words and put it in this dialog.

**Comment by yashk2000** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41234408/78696086-9095c100-791c-11ea-9d64-4305f653b8b8.gif)

**Comment by yashk2000** [comment]
@macgills it looks like the above gif.

**Comment by macgills** [comment]
Works great for me
