### ISSUE TITLE
Notes of deleted zims are not deleted from memory

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1947]
**Is your feature request related to a problem? Please describe.**

When a zim is deleted, the notes that were made for that zim are not removed from the memory. Since a user deleted the zim, the user will not have any use for the notes made in that zim too. Hence when a zim is deleted the notes folder for that zim should also be deleted from the memory. 

**Describe the solution you'd like**

When deleting a zim, delete the notes folder of that zim from memory. 

**Additional context**

I would like to work on this.

**Comment by 4shutosh** [comment]
Notes are not supposed to be deleted.
User might need to access the notes he/she has written while reading the information from the ZimFIle, but want to delete the ZimFile for any reason (less storage,etc).

**Comment by yashk2000** [comment]
Yes, you're right :+1:
