### ISSUE TITLE
Accessing all notes inside App 

### ISSUE THREAD

**Issue by 4shutosh** [kiwix/kiwix-android#1948]
**Is your feature request related to a problem? Please describe.**
There is no option to access notes inside the app once a zimfile is deleted.
Also the user is required to navigate to the specific page(where the note is made) to access it which is not so convinient.

**Describe the solution you'd like**
A new feature should be created to acces all the notes in one place from any of zimfile (deleted or stil present). As a user, there might be a good chance that the user wants to access the notes even after the zimfile is deleted.

**Additional context**
I would like to work on this issue.

**Comment by yashk2000** [comment]
@4shutosh I already started working on a similar feature. 
As I mentioned on this issue. 
https://github.com/kiwix/kiwix-android/issues/1916

**Comment by 4shutosh** [comment]
As mentioned there, a new issue was required for this feature/impementation discussion. So this issue can be used for the same.
I see a PR merged by you for that issue. 
So I request ticket for this part.

As far as it goes for the feature implementation, I'll be happy for the feature whoever executes it.

**Comment by yashk2000** [comment]
My apologies, for forgetting to create an issue. 
Thanks for creating one :)

Since you also had the same idea, maybe we could work on this issue together and co-author the pr.

**Comment by gouri-panda** [comment]
@macgills I would like to work on this issue.

**Comment by 4shutosh** [comment]
@gouri-panda Can I please work on this issue? I once started on this but got left. Hope you understand. 
Thanks for reminding.

**Comment by gouri-panda** [comment]
Sure, go ahead @4shutosh!

**Comment by gouri-panda** [comment]
@4shutosh How is your progress?

**Comment by 4shutosh** [comment]
Hey, @gouri-panda sorry for the delay. I am stuck on an error seeking help from sean. I've done a no verify commit on a branch [here](https://github.com/4shutosh/kiwix-android/tree/all_notes_page). Will update you soon. 

It will be great if you too take a look and help me with the errors.

**Comment by gouri-panda** [comment]
@4shutosh Thanks for updating. You can make a pull request in the draft and then we can help you with that.
