### ISSUE TITLE
Bottom and top bars opens when clicking an external link in full screen mode.

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#1949]
**Describe the bug**

When clicking on an and going to an external link in full screen mode, the bottom navigation drawer opens as well as the app bar. The app bar remains invisible however (it still takes up space). 

**Expected behavior**

The navigation drawer and app bar should be hidden in full screen mode at all times unless otherwise stated by the settings. 

**Steps to reproduce the behavior:**
1. Open a zim file.
2. Enable full screen mode.
3. Click on any external link.
4. Go to the links location with your browser.
5. Go back to the Kiwix application.
6. The full screen mode should still be active but with the bottom navigation drawer and app bar now visible. 

**Screenshots**

https://imgur.com/a/p0QLMD0

I'd like to work on this.

**Comment by 4shutosh** [comment]
@Frans-Lukas You've correctly pointed out the issue.

In CoreMainActivity.closeFullScreen.1043 replacing `updateBottomToolbarVisibility()` to     `bottomToolbar.setVisibility(View.VISIBLE);`
and adding one more condition `!isInFullScreenMode()` in CoreMainActivity.updateBottomToolbarVisibility.1280 will fix this.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/53831987/77328866-2806eb80-6d43-11ea-87bc-7a99524d3db2.gif)

**Comment by yashk2000** [comment]
@4shutosh wouldn't it be better if you didn't give out the solution to the issue? People might want to work on it by themselves first.

You wanting to help is really awesome, but I'd recommend that you wait for a person to ask first. 
I personally wouldn't directly like to see the solution to an issue this way and I believe anyone contributing to open source would agree as they do it to increase their knowledge and not just get direct answers to problems they are working on.

**Comment by 4shutosh** [comment]
Apologies @Frans-Lukas. Got your point @yashk2000. Won't happen again.

**Comment by Frans-Lukas** [comment]
@4shutosh No worries! ^^
