### ISSUE TITLE
Lint passed in kiwix-android but failed in kiwix-build

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#195]
![screenshot from 2017-07-03 21-57-52](https://user-images.githubusercontent.com/2286937/27807737-c0fbfca4-603a-11e7-8cf0-df136e97054d.png)

#184 Passed kiwix-android tests but failed the lint check on kiwix-build

**Comment by kelson42** [comment]
Why that does not block the CI?

**Comment by kelson42** [comment]
@mhutti1 @macgills Not sure what we should do with that ticket. I strongly suspect this is totally outdated and we can close it.

**Comment by macgills** [comment]
well kiwix-build should have nothing to do with kiwix-android now so I would say close it

**Comment by kelson42** [comment]
Is my feeling. Closing the ticket.
