### ISSUE TITLE
Updating View Binding to use Kotlin Extensions

### ISSUE THREAD

**Issue by akkywadhwa** [kiwix/kiwix-android#1962]
**Is your feature request related to a problem? Please describe.**

As per the kotlin documentation, it is advised to use Kotlin Extension View Binding.

**Describe the solution you'd like**

Butterknife can be replaced with Kotlin Android Extension for ViewBinding.

**Describe alternatives you've considered**

- Using ViewBinding

**Additional context**

References:
- [StackOverflow](https://stackoverflow.com/questions/46482018/kotlin-android-view-binding-findviewbyid-vs-butterknife-vs-kotlin-android-exten)
- [Kotlin View Binding](https://kotlinlang.org/docs/tutorials/android-plugin.html#view-binding)

PS: While converting to Kotlin, I can use Kotlin Android Extensions instead of ButterKnife.

**Comment by macgills** [comment]
@akkywadhwa this is the expected style of our kotlin classes, I will request it on any kotlin PR.

Annoyingly kotlin extensions don't work across modules, you can read more [here](https://youtrack.jetbrains.com/issue/KT-22430).

I'll close this
