### ISSUE TITLE
Last book in all lists (Library, home page) is only half visible

### ISSUE THREAD

**Issue by mohamedsamehkhalil** [kiwix/kiwix-android#1965]
**Describe the bug**
The bottom part of the last book is always not visible. I believe this is due to the switch to card view in #1924 to fix #1874

**Expected behavior**
All books should be fully visible

**Steps to reproduce the behavior:**
1. open home page or library
2. have enough books to require scrolling
3. When scrolling to the last book it is only half visible

**Screenshots**
No matter how much I scroll the Wikipedia book (the last book in the list) will not be fully visible
![Screenshot_20200325-150320_Kiwix](https://user-images.githubusercontent.com/34913464/77542315-aaf88500-6eae-11ea-8308-75e7d1fa81e6.jpg)

**Environment**
- Version of Kiwix Android : 3.2.1 (Latest build from develop)
- Device : S7 edge
- OS version : 8.0.0

I would like to work on this issue

**Comment by yashk2000** [comment]
Duplicate of #1611.

**Comment by mohamedsamehkhalil** [comment]
Yes you are right, thanks closing now
