### ISSUE TITLE
Showing warning before closing all tabs on opening new book

### ISSUE THREAD

**Issue by yash1ts** [kiwix/kiwix-android#1967]
**Is your feature request related to a problem? Please describe.**
On opening some other book all the tabs are closed and a new tab opens with that book's content.
This gives a feeling of bug, its not correct behavior. The user loses all the opened tabs.

**Describe the solution you'd like**
On opening a new book, a warning should be shown like "Do you want to open this book, this will close all the other tabs?".

**Additional context**
Steps to produce the problem
1. Open a book on some tabs.
2. Open a new tab and select any other book which is not open right now.
3. This closes all tabs, even if the user doesn't intend to.

**Comment by 4shutosh** [comment]
@yash1ts We don't support multizim as of now( we cannot open two different files simultaneously in two/more tabs) 

We can open same file in different tabs to read/compare  articles .

**Comment by yash1ts** [comment]
Yes, I am not saying about opening multizim files. I am just saying we should show a warning before closing all tabs.

**Comment by 4shutosh** [comment]
The only way to close all tabs is from tab switcher ( bottom blue cross icon ) which I think is quite obvious suggesting the action that it will close all tabs.

Also the user is used to it, cause there is no warning while closing background apps (Android system), closing all tabs from Chrome,etc.

IMO this feature will be irksome and is not required.

**Comment by yash1ts** [comment]
@4shutosh I didn't mean that. Opening any other zim file closes all tabs.

**Comment by macgills** [comment]
The current behaviour is annoying and unexpected but also showing a message everytime would be pretty annoying too.

Unfortunately I think are users are used to this "quirk" and we can ignore it until MultiZim is a reality

**Comment by yash1ts** [comment]
@macgills the alert box can have an option like "Don't show this again". In this way, the user will not lose all tabs if he accidentally opens any other book and can opt-out from warning if he wants.

**Comment by macgills** [comment]
Implementing the don't show again is the part that makes me want to do this the least.

I will be closing this as I don't want to introduce this as a temporary fix. We should be making strides towards multizim soon with the removal of the ContentProvider.

**Comment by yash1ts** [comment]
Ok
