### ISSUE TITLE
Android 4.4 users for WikimedAR app complains that not open after download it 

### ISSUE THREAD

**Issue by alanajjar** [kiwix/kiwix-android#1968]
Hello, 
(Here I pass what I noticed from WikimedAR app reviews.)

I noticed that (Android 4.4) often complains that after download the app is not opened with them, as we received two complains (today and yesterday), and I took a look on previous comments, and I found a lot said the same since 2019.

I replied on all of them, that if they can explain more, as the app should work on Android version 4.0.3 and up.

**Comment by kelson42** [comment]
@macgills Would you be able to look to the Play Store console please and try to identify a pattern?

**Comment by macgills** [comment]
There is no crash report to support this. I could try and repro with an emulator? If anyone has a 4.4 device that would be better

**Comment by kelson42** [comment]
@macgills Yes please do
@alanajjar We don't have any crash report in the Play Console. I guess we will have to close this ticket if we can not achieve to reproduce the problen.

**Comment by alanajjar** [comment]
@kelson42 yup feel free, I'm only passing what I found on comments.
Thanks for help

**Comment by macgills** [comment]
I can't install any app from the play store with a 4.4 emulator so I don't have much of a way to test this, unfortunately will have to close
