### ISSUE TITLE
Remove AnimatedProgressBar

### ISSUE THREAD

**Issue by akkywadhwa** [kiwix/kiwix-android#1987]
**Is your feature request related to a problem? Please describe.**

AnimatedProgressBar could easily be replaced with just a ProgressBar

**Describe the solution you'd like**

Delete AnimatedProgressBar and adapt our current code to use a ProgressBar

**Comment by rutvik-panchal** [comment]
@kelson42 @macgills Can i work on this issue?

**Comment by macgills** [comment]
please and thank you

**Comment by kelson42** [comment]
@macgills @akkywadhwa The problem is this ticket is that this is not clear why we have to do anything? What is wrong with the current animated bar?

**Comment by macgills** [comment]
My comment on the closed [PR](https://github.com/kiwix/kiwix-android/pull/1988#issuecomment-606548368)

>This class is ridiculous it inflates a layout that contains a progress bar and then custom draws its own progress line anyway? I didn't even really know it existed. I don't want this in kotlin, I want it deleted.
