### ISSUE TITLE
Version number does not appear in settings

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#199]
While it is normally indicated in the previous release of Wikimed (2016-10), it is absent from the alpha I just tested.
![crop](https://user-images.githubusercontent.com/21675885/28273815-95b59b24-6b0f-11e7-8514-cfa583dccfc9.jpg)

**Comment by mgautierfr** [comment]
@mhutti1, I've build the alpha version specifying the version_code (with `-p version_code=xxxxxx`)

From this https://github.com/kiwix/kiwix-android/blob/master/app/build.gradle#L237-L243, the versionName and versionCode should be xxxxx.

And the version is displayed here : https://github.com/kiwix/kiwix-android/blob/master/app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java#L261-L268

Am I missing something ?

I agree that the version would not be the right one but we should at least display something.

**Comment by kelson42** [comment]
That is strange, by me I see the version number, but this is the version of Kiwix, not of the custom app (so 2.2).

**Comment by mhutti1** [comment]
Mine says:
2.3 Build 54. Is this right?

**Comment by kelson42** [comment]
@mhutti1 no, it should be 2017-07 (not sure about the build number).

**Comment by mhutti1** [comment]
@kelson42 Well thats the issue. Its displaying org.kiwix.kiwixmobile (vanilla kiwix) information. And blank if that is not installed.

**Comment by mhutti1** [comment]
This should be fixed but I would test.

**Comment by mgautierfr** [comment]
New wikimed alpha should include the fix.

**Comment by Popolechien** [comment]
Yup (2017-07 Build: 1171990). Thanks.
