### ISSUE TITLE
Update preferred storage if it was removed by the user

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1997]
**Describe the bug**

If the user removes their sd card after setting the sd card as their preferred storage then we continue using this as the preferred storage and report available size as 0
**Expected behavior**

The app should fallback to using internal storage if removable doesn't exist

There is a question if we should switch to internal permanently ie save internal as preferred if current preferred does not exist, or simply use internal until the preferred is found again or the user chooses the internal as preferred

first reported #1854

**Comment by kelson42** [comment]
I'm not really in favour of super-smart behavior behind de scene. I think a warning should be printed if the storage is not available anymoire and invite the user (with a button "go to settings") to change it. Doing more seems a bit too smart to my taste.

**Comment by macgills** [comment]
superseded by #2002
