### ISSUE TITLE
Stop a download that is in the allocating phase

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1998]
**Describe the bug**

Clicking stop on a large download that is still in the "allocating" phase does not stop the download and seems to have no effect

**Expected behavior**

When the stop button is pressed the download should be removed from the list and stop all activity

First reported #1854

**Comment by kelson42** [comment]
@macgills That sounds quite important to do to me.

**Comment by macgills** [comment]
superseded by #2002
