### ISSUE TITLE
Unit Test: DarkModeViewPainter

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1999]
**Type of Test**

* [X] Unit Test
* [x] UI Test

**Particular area and files to be tested**

- DarkModeViewPainter

**Current Status of the tests**
<!-- Are there any tests included for this particular area, which need improvement, or has this are never been tested at all?
No tests

**Comment by kelson42** [comment]
@yashk2000 Do you plan to implement that ticket yourself?

**Comment by yashk2000** [comment]
@kelson42 sorry for the delay. 
Anyone can work on this issue.

**Comment by satvik2131** [comment]
is this still need to be done @kelson42 ?

**Comment by Nol22815** [comment]
if the issue is still open and nobody is working on it i'd like to do so :)
