### ISSUE TITLE
Content download progress bar is not updated if not downloading

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#20]
_From @kelson42 on February 14, 2017 6:50_

Which has for consequence that if you restart Kiwix with an ongoing download, the progress bar is empty at the beginning - as long as you do not download new data (even if you have already downloaded 50% for example).

_Copied from original issue: kiwix/kiwix#461_

**Comment by kelson42** [comment]
_From @EladKeyshawn on February 15, 2017 20:26_

@kelson42 I cannot reproduce the problem, for me after app restart the progress bar is up to date.

**Comment by kelson42** [comment]
_From @mhutti1 on February 15, 2017 21:32_

I can reproduce fine. I will fix it for the release of 2.3.

**Comment by kelson42** [comment]
@mhutti1 What is the status on this?

**Comment by mhutti1** [comment]
I think it is fixed now.
