### ISSUE TITLE
Wikimed landing page needs to be replaced

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#200]
The new link for the english Wikimed landing page is:

https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Medicine/Open_Textbook_of_Medicine2

**Comment by Popolechien** [comment]
Got feedback from Doc James, he wants to make another couple of changes.

**Comment by mgautierfr** [comment]
@kelson42 Is the landing page specified when generating the zim file ?

**Comment by kelson42** [comment]
@mgautierfr yes, just need to make a switch. This is trivial.

**Comment by Popolechien** [comment]
Ok page is ready, you can implement at the next release.

**Comment by kelson42** [comment]
This is implemented, next version, in August, will implement the new welcome page.
