### ISSUE TITLE
Buttons overlap in Zoom control dialog

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#2005]
**Describe the bug**

The buttons overlap in the dialog box of Zoom control in settings

**Expected behavior**

**Steps to reproduce the behavior:**
1. Go to settings.
2. Toggle on Zoom control if it is off
3. Click on Zoom level

**Screenshots**

![zoonm_ui](https://user-images.githubusercontent.com/34706326/78457739-06eeb500-76ca-11ea-8210-4702bfa04a89.jpeg)

**Environment**
- Version of Kiwix Android : Kiwix 3.2.1
- Device : Redmi 4
- OS version : Nougat

**Comment by mohamedsamehkhalil** [comment]
Hello, I would like to work on this

**Comment by macgills** [comment]
This dialog has been deleted so I am afraid this can no longer be worked on
