### ISSUE TITLE
Toast and Storage Selector Option overlaps.

### ISSUE THREAD

**Issue by hamza-maqsood** [kiwix/kiwix-android#2010]
**Describe the bug**
When you try to download a file and enough storage isn't available, app shows a toast message and a storage device selector options behind it, as they both overlap, it's hard to read and respond.
Also the tags are overlaping and text too, in the list item, screenshot is attached.

**Expected behavior**
The toast message and the Storage Options popup should not overlap but clearly visible.
The storage options can be shown with a snackbar instead.

**Steps to reproduce the behavior:**
1. Try downloading a file with not enough storage available.

**Screenshots**
![Screenshot_2020-04-08-23-09-25](https://user-images.githubusercontent.com/62572687/78821555-1edc7680-79f3-11ea-8313-6fae435d6007.png)

**Environment**
- Version of Kiwix Android : 3.2.1
- Device :  LG G5
- OS version : 8.0

**I want to fix this.

**Comment by macgills** [comment]
This has been fixed recently I am pretty sure. Are you testing on latest master?

**Comment by hamza-maqsood** [comment]
Yes it's fixed now. I re-cloned the develop branch and tested the app.

**Comment by macgills** [comment]
Great, we can close this.
