### ISSUE TITLE
Add unit tests for NewBookmarksDao

### ISSUE THREAD

**Issue by akkywadhwa** [kiwix/kiwix-android#2012]
**Type of Test**

* [x] Unit Test
* [ ] UI Test

**Particular area and files to be tested**

NewBookmarksDao.kt

**Current Status of the tests**

Coverage is at 33.13%

**Particular Behaviour to be tested**

Functions: getBookmarks, getCurrentZimBookmarksUrl, bookmarkUrlsForCurrentBook, saveBookmark, deleteBookmarks, deleteBookmarks, migrationInsert

**Comment by kelson42** [comment]
@akkywadhwa Any news here or have you give up?
