### ISSUE TITLE
Kiwix won't use my SD card

### ISSUE THREAD

**Issue by DavidKutu** [kiwix/kiwix-android#2018]
**Describe the bug**
I have a 16 GB SD card on my device, yet Kiwix won't download a 10 GB version of Wikipedia. I am using External Storage on settings.

**Expected behavior**
I should be able to download and store stuff on my external storage.

**Steps to reproduce the behavior:**
1. Go to settings, on storage select external
2. Press Download books
3. Search for Wikipedia
4. 10 GB option appears grayed out

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : HUAWEI P9 lite
- OS version : Android 7.0

**Comment by kelson42** [comment]
@DavidKutu Thank you for your bug report. Which version of Kiwix to you use (visible in Settings, at the bottom)? Which filesystem do you use on your SD card? Are you been able to write a file bigger than 4GB at all on this SD card/filesystem?

**Comment by DavidKutu** [comment]
It was FAT32. I reformatted it to exFAT but that didn't help.

**Comment by kelson42** [comment]
@DavidKutu So you don't see your Ext SD card in the settings? You see only the "internal" storage?

**Comment by macgills** [comment]
Hi @DavidKutu can you long click on the greyed out item? A message should display and if I am correct it will say something like "trying to detect storage". If you wait awhile on this screen then we may successfuly detect the filesystem as compatible with files over 4GB. The process can take minutes unfortunately

**Comment by DavidKutu** [comment]
@kelson42 The Ext SD does appear in settings. And it is selected.

@macgills The message does appear, but then nothing happens. How long should it take?

**Comment by macgills** [comment]
@DavidKutu I only ever observed 5 minutes at the worst I think? try long clicking at the end of 5 minutes, it has different messages for when it is in progress or failed to assess the filesystem (ie couldn't write a 4GB file)

**Comment by macgills** [comment]
@DavidKutu did waiting have a positive result?

**Comment by DavidKutu** [comment]
No, after 5 minutes I gave up.

**Comment by macgills** [comment]
@DavidKutu we have a new feature where a diagnostic report can be sent from the Help screen. This feature is available in our Beta release and is slowly being released to production over the coming days.

If you send a diagnostic report I am hopeful I can help

**Comment by kelson42** [comment]
@DavidKutu Would you be able to give a try with the latest nightly? https://download.kiwix.org/nightly/
