### ISSUE TITLE
Error resolving host name when downloading content

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2022]
Not sure it has any actionable value -not even sure this is the right repo as the error might be somewhere else- but we received this from a Russia-based android folk:

![Screenshot_20200410-151458_Kiwix](https://user-images.githubusercontent.com/21675885/79070515-d1a02380-7cd6-11ea-8b57-393800d389c0.jpg)

**Comment by kelson42** [comment]
@macgills I think there is nothing much we can do here, the user infrastructure is just broken.

**Comment by kelson42** [comment]
@Popolechien Please ask users to open tickets here, there is most of the time nothing much we can do otherwise.

**Comment by Popolechien** [comment]
@kelson Well the guy wrote in Russian, I only opened the ticket as an FYI because he sent a screenshot. Feel free to close these tickets as they come.

**Comment by kelson42** [comment]
@Popolechien Yes... the fundamental problem is that for a ticket in which the problem is not obvious (from the symption or the rootcause), the value is the exchange between the dev and the user... and here there is no exchange possible unfortunatly :(

**Comment by Popolechien** [comment]
Since this is more of an FYI I am more than happy to simply flag it via Slack. Let me know if that would be best.

**Comment by macgills** [comment]
I would doubt there is anything to do app side
