### ISSUE TITLE
Two strings are not localized correctly

### ISSUE THREAD

**Issue by asereze** [kiwix/kiwix-android#2024]
There are two strings, in the "Online" tab of the Library, that keep remaining in my system's language (Italian), no matter what language I choose in Kiwix's settings: "Selected languages:" and "Other languages". It only happens on that page, in the one where I can select the languages they are correctly localized.

- Version of Kiwix Android : 3.2.1 
- Device : Xiaomi Redmi Note 4X
- OS version : LineageOS16.0 (Android 9)

![photo_2020-04-21_00-09-03](https://user-images.githubusercontent.com/11271324/79804493-71f3e900-8364-11ea-965b-2cb8eeb93f8e.jpg)

![photo_2020-04-21_00-06-38](https://user-images.githubusercontent.com/11271324/79804255-00b43600-8364-11ea-963e-b222f960689c.jpg)

**Comment by kelson42** [comment]
@macgills Any idea? We had an old bug really similar which has been closed because of lack of reprocase.

**Comment by macgills** [comment]
We are using the application context to get the string in the ZimManageViewModel, which is what produces the data to be rendered in LibraryFragment, this should be easily fixable
