### ISSUE TITLE
Create Send Diagnostic Report screen

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2045]
**Is your feature request related to a problem? Please describe.**
Some people still have trouble with their sd cards file system detection and other device specific issues #1775 #2018 that are impossible to resolve without further information

**Describe the solution you'd like**
Add a "Send Diagnostic Report" button to Help screen.
Potentially reuse ErrorActivity and also enhance it to give us the output of the mount command and `externalDirs` as well as the app version
This will send an email with the necessary information to the same address used for email crash reports

**Comment by kelson42** [comment]
This feature seems quite urgent indeed. I think I would prefer a string that the user could copy and do whatever he wants with it.

**Comment by macgills** [comment]
Well right now the error screen puts all the info into an email that a user is free to edit

**Comment by macgills** [comment]
I can probably get this into the 3.3 milestone, the remaining tickets are mostly fine, I think I have the necessary availability

**Comment by kelson42** [comment]
> I can probably get this into the 3.3 milestone, the remaining tickets are mostly fine, I think I have the necessary availability

I'm definitly with you on this. Thx for the quick move.
