### ISSUE TITLE
Convert Bookmark package to kotlin

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#2051]
**Is your feature request related to a problem? Please describe.**
The bookmark package is still in Java

**Describe the solution you'd like**

Convert it in kotlin

**Additional context**

Parent issue #1826

**Comment by macgills** [comment]
Please do not convert packages, singular classes preferred

**Comment by sonusourav** [comment]
Hey @macgills ,
Please consider this time. Next time I will this into consideration.

P.S.: Some other files which were showing error are also changed.

**Comment by macgills** [comment]
I think it would be for the best if you opened individual tickets, there are confusing changes and video playing & svg loading is broken by this PR currently
