### ISSUE TITLE
Kiwix hotspot starts without mobile hotspot being turned on

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#2071]
**Describe the bug**

Even if the hotspot of the device isn't on, and then the start server button is clicked, the Kiwix Hotspot starts. If I enter the provided URL in another device, the ZIMS appear in the browser of the other device too.
Earlier if Start Server was clicked without turning on the device hotspot, a toast used to be shown saying that the server couldn't be started.

From what I noticed, this is only happening when a device is already connected to some wifi network.
Then the Kiwix Server starts. And in order to use the address generated by the Kiwix Server in this case, the other device on which we want to view the ZIMS should also be connected to the same wifi network.

**Steps to reproduce the behavior:**
1. Go to host books.
2. Ensure that the device is connected to a wifi network 
3. Press on the start server button with at least one book selected.
4. When the dialog comes, click on the option saying that mobile hotspot is already on
5. The Kiwix Server starts

**Environment**
- Version of Kiwix Android : 3.3.1
- Device : Redmi K20
- OS version : Android 10

**Comment by abdulwd** [comment]
I'm aware of this. This is the intended behavior but isn't documented anywhere. Last year when Adeel was working on this we thought it would be a use case for hosting ZIMs on the same network with no internet.

**Comment by yashk2000** [comment]
So should we update the dialog and the onboarding to include this information too?

**Comment by abdulwd** [comment]
Yes please and update the docstrings in the related file(s).

**Comment by yashk2000** [comment]
Ok, I'll do that.
