### ISSUE TITLE
Looks like there is a typo on android UI

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2074]
I was looking at translatewiki and I see the first string is _Kiwi_ rather than Kiwi**x**. Isn't this a typo? Does it get fixed here or there?
String: https://translatewiki.net/wiki/Kiwix:Android.ui.kiwi/fr

**Comment by Popolechien** [comment]
Just to be clear - the typo isn't in the French translation, which I could fix, but in the English source.

**Comment by macgills** [comment]
I think that string is not visible to the user, we should remove it though

**Comment by kelson42** [comment]
@macgills It is in `app/src/main/res/layout/item_intro_1.xml`

**Comment by macgills** [comment]
as a contentDesciption if I remember correctly, not typically visible

**Comment by kelson42** [comment]
@macgills What is this string about? Do we have a typo or is that just the right thing written there? Or is the string OK but just useless?

**Comment by danielzgtg** [comment]
> as a contentDesciption if I remember correctly, not typically visible

It's never visible but it's very audible. It should be read by screen readers, but I've never used one.

**Comment by macgills** [comment]
We should remove the string, it is low priority so I probably won't get to it in the immediate future but anyone else is welcome to
