### ISSUE TITLE
"Problem loading widget"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2076]
This is what happen for me when I try to apply the widget to my "desktop". I get a white widget with inside the message "Proablem loadind widget". Seem quite important to fix IMO, we already have got at least one complain about it.

**Comment by rashiq** [comment]
Can't reproduce with latest master, do you maybe have something related to that in the logcat?

**Comment by macgills** [comment]
I assume this is android 10?

**Comment by kelson42** [comment]
> I assume this is android 10?

@macgills Yes, and now the error has vanished and I can see the searbox properly and us it!!!

**Comment by macgills** [comment]
… well then... problem solved?

**Comment by kelson42** [comment]
Hmmm, closing for now.
