### ISSUE TITLE
[wikimed alpha] Credits is not available.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-android#208]
In the settings menu, it is not possible to get the "view/page" associated to `credits` button.

![credits](https://user-images.githubusercontent.com/86161/28324326-59f85a78-6bdb-11e7-94d6-6ddc98ab431b.png)

**Comment by kelson42** [comment]
File is there ./app/src/main/res/raw/credits.html... so I suspect the link is "simply" wrong... @mhutti1 ?

**Comment by kelson42** [comment]
Thx @mhutti1, I close the ticket and will reopen it if we still have the problem with the next nightly.
