### ISSUE TITLE
Convert History module to kotlin

### ISSUE THREAD

**Issue by jonggeunpark** [kiwix/kiwix-android#2081]
**Is your feature request related to a problem? Please describe.**

History module in Java

**Describe the solution you'd like**

Convert History module in Kotlin

**Additional context**

Parent issue #1826

**Comment by macgills** [comment]
No modules, individual files only please

**Comment by jonggeunpark** [comment]
What I meant is converting the file HistroyModule.java
Can't I do this?

**Comment by macgills** [comment]
Ah that is fine, my mistake

**Comment by jonggeunpark** [comment]
thanks
