### ISSUE TITLE
Convert HistoryActivity to kotlin

### ISSUE THREAD

**Issue by jonggeunpark** [kiwix/kiwix-android#2092]
**Is your feature request related to a problem? Please describe.**

HistoryActivity is in Java

**Describe the solution you'd like**

Convert HistoryActivity to Kotlin

**Additional context**

Parent issue #1826

**Comment by macgills** [comment]
This may not be the best idea, #1990 is well underway and is a total rewrite of HistoryActivity

**Comment by jonggeunpark** [comment]
I just checked. Would it be better to close the issue?
