### ISSUE TITLE
Icon tooltip font color is wrong

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#21]
_From @kelson42 on February 11, 2017 19:6_

by clicking on the icon a tooltip appears explaining the purpose of the button. the font is in black. Considering the background of the tooltip is black or grey (depending the android version) I think it would be better to make white (or grey light).

_Copied from original issue: kiwix/kiwix#459_

**Comment by kelson42** [comment]
_From @EladKeyshawn on February 11, 2017 19:11_

I also experienced this but I thought it's specifically happening on my
Huawei.on  what device did you get this?

**Comment by kelson42** [comment]
@EladKeyshawn on my both Samsung Galaxy tabs?

**Comment by mhutti1** [comment]
@kelson42 Did we get a reproduction case for this because I can't find one.

**Comment by kelson42** [comment]
Old bug report without repro-case. I close the ticket.
