### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2100]
I've had a few reports from users over the past 24 hours so I'll just copy paste the moste elaborate one (in English) here:

"kiwix was working yesterday (19/may/2020) then after an android update on my galaxy s9+ it just opens and immediately closes again. Ive tried unisyalling, reintalling through playstore, ive tried with the apk from you website. It just wont work now."

I understand this is fairly useless as feedback but it's unusual to get so many reports in such a short span, thus sharing it as FYI. @macgills feel free to close once you read it.

**Comment by macgills** [comment]
There is potential it could be

```
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: 

 
  at android.webkit.WebViewFactory.getWebViewContextAndSetProvider (WebViewFactory.java:278)
```

Which could mean the WebView (whose implementation we rely on) was updating? But that is only affecting 1 model `Core- X3 (HS8917QC) `

I really can't say from this data and after checking any potential issue that I have on the crash dashboard I can't connect this report to any of them

**Comment by macgills** [comment]
Closing as unactionable but noted.
