### ISSUE TITLE
Zoom controls disappeared in v3.3.1

### ISSUE THREAD

**Issue by tigran123** [kiwix/kiwix-android#2110]
I have upgraded Kiwix Android application to v3.3.1 yesterday and now none of the articles are readable, because the default text size is too small and the zoom controls disappeared from the Settings. Fortunately, apkpure hosts the previous versions, so I downgraded Kiwix to v3.2.1 and everything is perfect now.

**Expected behaviour**

Zoom controls should be present in the Settings menu, as in the previous versions.

**Steps to reproduce the behaviour:**
1. Try to read any article in WikiPedia and fail, because the text size is too small (if you read 2000 pages a day, you will soon notice the difference). Go to Settings and find that the Zoom control option is gone. Trying to "zoom in" by pinching the screen is not an option, obviously, because the text does not reflow, so parts of the page end up to the right of the screen and are invisible. And one cannot be expected to read gigabytes of data by scrolling all the time horizontally.

**Environment**
- Version of Kiwix Android : v3.3.1
- Device : Samsung Galaxy Tab S4
- OS version : Android 9

**Comment by kelson42** [comment]
It is true we have removed this setting in 3.3.

I don't find the exact ticket and don't remember all the reasons behind that decision but I was supportive because I believe the main problem was that the content itself did not have the right size, but otherwise it should be OK.

The fact is that @tigran123 is not the only one complaining about that loss. Actually, this is probably main pain point users complain about with 3.3.3.

@macgills Would you be able to wrap-up the pros/cons please? I would like to secure the app takes the right path on this.

**Comment by tigran123** [comment]
Well, I haven't seen a WikiPedia page which has a concept of "content with fixed size". This is not a printed book or a facsimile of such, where each page is atomic. In electronic texts (such as html or fb2) the information is stored as characters and so the software is free to render them at any size. The main thing here is to be able to reflow the text to fill the screen optimally. If there is no easy way to reflow it automatically (upon pinch-zooming in), then the manual "zoom controls" remain a necessity for the serious reader. I spend a lot of time in Kiwix when doing physics or mathematics research and find this feature absolutely essential, even critical.

Ideally, it would be nice to reflow the text automatically. I vaguely remember that some very old version of Kiwix (or maybe some other WikiPedia offline reader) had this function --- or was it Android's builtin "webview" that provided this functionality?

**Comment by kelson42** [comment]
@tigran123 Really first versions of Kiwix for Android had automatic text reflow in my remembering as well. But we just use here the feature provided by the Android component and this feature has been removed by Google. Let see now the detail of the reasons behind the removal of our zoom setting.

**Comment by macgills** [comment]
We removed the zoom bar because it seemed like an extraneous feature and there was a bug report about the default zoom values if I remember correctly.

https://github.com/kiwix/kiwix-android/pull/2004 simple to undo

There may be a best of both worlds solution but it will require some experimentation.

@tigran123 can you please tell me the specific zim file and an example article for me to reproduce the issue?

**Comment by kelson42** [comment]
@macgills Thank you for the feedback. I think this feature is worth this experimentation/effort.

**Comment by tigran123** [comment]
Yes, sure, I use the latest 79GB English WikiPedia zim file with MD5 checksum of d3578c4248b6f4ff6f0f917687acd6c1

Here is the URL to it:

[http://download.kiwix.org/zim/wikipedia_en_all_maxi.zim](http://download.kiwix.org/zim/wikipedia_en_all_maxi.zim)

Btw, on your website there are lots of small zim files for WikiPedia which are very recent, but the complete one is still dated 2018-10.

**Comment by tigran123** [comment]
I do not understand how the absolutely critical feature like this could be considered extraneous. Obviously, this is critical not just for me, but for everyone who is reading the text rather than just looking at the pictures. Removing the freedom to set the text size encourages to "go with the flow" of the modern pseudo-educational establishments (schools, universities etc) which encourage superficial pseudo-learning and foster illusion of comprehension. But, my dear brothers, we, the Open Source Community, are literally the last hope of mankind, the last tiny thread upon which this world's fate hangs. Surely we must always go AGAINST the flow and maintain the spirit of freedom and free access to all knowledge, against all odds. I hope all of you appreciate that I say these words purely out of love and respect and deep appreciation of the work you are doing.

**Comment by macgills** [comment]
@tigran123 have you experienced this issue on a smaller zim file by any chance? Downloading 79GB will take extra time

**Comment by tigran123** [comment]
@macgills You will experience this problem on any article with any WikiPedia zim file, large or small.

**Comment by macgills** [comment]
@tigran123 just so I can confirm:

This is a wikipedia article right now at our default text size

![image](https://user-images.githubusercontent.com/3358282/84150912-767e7900-aa5a-11ea-8aac-3c7863e1c113.png)

This is the same article after changing the accessibility settings in my phone system settings

![image](https://user-images.githubusercontent.com/3358282/84151110-c5c4a980-aa5a-11ea-8c50-6d32e4203256.png)

Is this support of the native accessibility features acceptable as a solution to this issue?

**Comment by tigran123** [comment]
@macgills Sean, how can I say if this is "acceptable" or not? You showed one enormous picture of what could well be a screenshot of some tiny mobile device with a screen of some unknown size. So, no, this (or any other) picture is not an acceptable solution, of course. The only acceptable solution is the restoration of the user's ability to control text size. Have you restored this functionality yet?

**Comment by tigran123** [comment]
Ah, I have just re-read your message and noticed the text in between two pictures. So, the answer is "No, it is not acceptable" but for a completely different reason: one should NOT need to change the global system settings because that would affect all other applications. You should restore the Kiwix-specific functionality --- that is the ONLY acceptable solution. I thought this is obvious.

**Comment by macgills** [comment]
Yes, I reread the initial ticket and realised the size of your device.

After experimenting with Chrome's confusing accessibility settings that only seem to take affect in "Desktop Mode" I think I have a better idea for a new feature

**Comment by tigran123** [comment]
The size of my main device is 10" (tablet), but I also have 6" device (mobile) and I expect it to work there as well, just like it did work perfectly, until this feature was removed in the recent upgrade.

**Comment by macgills** [comment]
![text_size](https://user-images.githubusercontent.com/3358282/84259693-c3bd2200-ab10-11ea-9469-6d6c93cd73c0.gif)

This is the new functionality, not quite the old zoom but I hope an adequate solution, will open a PR shortly.

**Comment by tigran123** [comment]
Good, thank you. As long as it works with serious articles with pictures and formulae, i.e. things like [https://en.wikipedia.org/wiki/Wigner_quasiprobability_distribution](https://en.wikipedia.org/wiki/Wigner_quasiprobability_distribution) and not just text-only, I am very happy. Thank you again!
