### ISSUE TITLE
Merging Library activity with homepage view

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2112]
**Is your feature request related to a problem? Please describe.**

Currently, the removal and sharing of a Zim file is handled in a separate activity than from the view where a Zim file is opened from. This leads to a confusing user flow for any action that is done on a book. E.x. User wants to delete a book and then move to another, the user has to open the 'Download Books' activity, switch to the Device tab and then open a book. This is confusing because we have two views that look like they can perform the same actions but have different purposes. E.g. one view for opening books and one activity for handling books.  

**Describe the solution you'd like**

I suggest we merge these two views into one activity where books are managed and opened. This activity will behave exactly like the library activity with the change of it being the default/starting activity of the Kiwix application. This will also remove the tab mode from the downloads activity which should allow more books to be viewed at once. See [this figma](https://www.figma.com/file/EkpKMn5rchpHcZg2qdgHFv/Kiwix?node-id=0%3A1) for what merging the library views might look like.

A problem with this is that the book 'web-page' view is opened whenever a user wants to open a new book via the '+' icon in the tab handler. 
![image](https://user-images.githubusercontent.com/22193232/82814663-db9d7080-9e97-11ea-81bc-56497eb06e78.png)
Instead of this button opening the library view I suggest we open a dialog instead. This dialog will both explain what the action is doing (closing all opened tabs when a book is selected, and display the currently available books.)
![image](https://user-images.githubusercontent.com/22193232/82814825-346d0900-9e98-11ea-9dfc-7169a7c3a326.png)

**Describe alternatives you've considered**

None so far but I want to hear suggestions and other feedback on my suggestion.

**Additional context**

This is part of my summer of code proposal and is something I will work on in the coming weeks. I will also perform a user study to see if the current setup is as confusing as I have argued that it is.

**Comment by rutvik-panchal** [comment]
I think the add button to open a tab should be kept, that could help a user to read and switch between two different articles/page from the same file easily.
Speaking about alternatives we can show bookmarks or perhaps an add-on feature of favorite books for displaying a shortlist of books on the main activity or the list of few pages from bookmarks.

**Comment by Frans-Lukas** [comment]
I am not saying we should remove the 'add' button, but to change how a new book is opened.  

Do you mean sorting the available books based on them being 'bookmarked' or 'favorites'?

**Comment by rutvik-panchal** [comment]
Oh, I actually thought you gonna remove the add button or the tabs options with books after looking at the Figma designs. Yes, I think sorting the books on the basis of favorites can improve the user experience.

**Comment by Frans-Lukas** [comment]
I see, I'll have to make that more clear... For books being sorted based on being bookmarked or favorites: I think it should be put as a separate issue as it is an extension of the zim browser activity and not related to fixing duplicate activities.

**Comment by Frans-Lukas** [comment]
I spoke to @macgills about this issue being closely related to an existing issue related to navigation discussed last summer. #1245. They talked about implementing a bottom navigation drawer (as well as?) a navigation drawer. 

By implementing better navigation and merging the `view displaying "the list of books when you have no book open"` and the `local library` activity we will potentially fix navigation issues and reduce the number of views in the app. 

The suggested bottom navigation bar should contain the following destinations (at a minimum):
1. `Library` : Similar to the current `local library` activity that is currently accessed by: Main activity -> Download books -> Switch to Device tab
2. `Download` : An activity for downloading new books. Exact copy of the current downloads activity.
3. `Reader` : The current reader activity without the library view as it has been merged with the `Library` destination. 

The `Reader` activity should display "No book open" (and a button to navigate to library should be clearly visible), if no book is open when the user navigates to this view. 

I will make a mock of what this could look like asap. 

@mhutti1 @kelson42 You had some feedback about #1245. What are your thoughts about this suggestion a year later?

**Comment by 4shutosh** [comment]
Bottom navigation would work great for simplifying the navigation.
I would like to suggest a usecase for Bottom Navigation including the following 4 destinations:
* **Home**: with recent opened zims list (same as the current landing page).
* **Library** : with two tabs- one to download zim files(ONLINE) and another the offline saved one(DEVICE).
* **Reader**: The individual reader activity as you suggested.
* **Settings**: Including the Settings activity will also be handy.

![reader](https://user-images.githubusercontent.com/53831987/83845326-410a2080-a726-11ea-84f7-a27acc866805.png)



This will cover the core features of the app and will make the navigation smipler.

**Comment by Frans-Lukas** [comment]
Good that you also agree that bottom navigation could be needed. 

What is the purpose of the `home` destination compared to the `library` destination? What can the `home` destination do, that the `library` destination can not? My conclusion is that the `home` destination should be replaced by the "offline saved one(DEVICE)" tab of the `Library` destination. That is, that we should merge `home` with `local library`. 

I also disagree with having `settings` as a destination on the navigation bar simply because I haven't seen any other app include a settings activity in a bottom navigation bar. As discussed in #1245 a navigation drawer can be added to include less common destinations such as settings. 

I am currently making some mock-ups of how this could be handled, and I am starting to think that having the `reader` as a destination is a bad idea as well...

**Comment by Frans-Lukas** [comment]
[Here is the mock-up](https://www.figma.com/file/7MEYHVBYlr5BSbqd0i8CdC/Kiwix-Copy?node-id=0%3A1). My current preference is that the bottom navigation should have the following three destinations:

1. `Library` - Books available offline.
2. `Download` - Books available online.
3. `History` - The history of viewed book pages. Click an entry to go to the clicked page.

See the mock-up for arguments for and against both alternatives but to summarize:
If the reader activity is its own destination on the bottom navigation bar, we have to change the book navigation bottom bar in some way. I am not happy with the changes I came up with and as such I think having the reader be accessible from two other destinations should suffice. That is, to get to the reader either a book has to be opened from `library`, or a history item is to be clicked from the `history` destination. 

I am of course happy to hear other suggestions or solutions as well. 
![image](https://user-images.githubusercontent.com/22193232/83852703-7c035880-a714-11ea-9ac3-c97275d63140.png)
![image](https://user-images.githubusercontent.com/22193232/83852726-87ef1a80-a714-11ea-981a-53165650f1ad.png)

**Comment by 4shutosh** [comment]
> What is the purpose of the `home` destination compared to the `library` destination? What can the `home` destination do, that the `library` destination can not? My conclusion is that the `home` destination should be replaced by the "offline saved one(DEVICE)" tab of the `Library` destination. That is, that we should merge `home` with `local library`.

As a landing page for an app will be a good idea, with a limited list of recently opened zim files which will help users to jump back to the file where they left off. What if the user has a large number of zim files saved, it will be quite tedious to go back to where he left. Also, there is no search feature in `ZimManageActivity`
Also, it gives an extra screen to work with some announcements (new features, etc). 

> I also disagree with having `settings` as a destination on the navigation bar simply because I haven't seen any other app include a settings activity in a bottom navigation bar. As discussed in #1245 a navigation drawer can be added to include less common destinations such as settings.

Settings can be useful in some situations (zoom controls, light mode) android system navigation is accessible from the bottom (either of 3 button/2 button/gestures) , and the “Bottom” Navigation goes the same so to make the UI more presentable and leaned towards bottom usage we may include frequently used features.
Also, the Navigation Drawer can be included as well but IMO is redundant.

> 1. `Library` - Books available offline.
> 2. `Download` - Books available online.

Giving an extra bottom navigation destination is not required I guess as it goes pretty well now ( the two tabs Offline and Online ). As a user who does not have internet for quite a few times the bottom download destination will be futile. 


> 3. `History` - The history of viewed book pages. Click an entry to go to the clicked page.

History should be included only in the reader page as an overflow menu (as it goes now) along with bookmarks and other menu options. Good to see that you plan to show the tab switcher only if we are on the reader screen.

While handling the book navigation bar what if we hide the bottom navigation bar with an icon/button in the book navigation bar, instead of the FAB. So if a user wants to hide the navigation bar it is possible, if the user does not one of the navigation bars (or) both the navigation bars will hide automatically when we scroll down through the book(or just click the book content layout). So the problem of large bottom bars is no more a problem if the user starts reading.

Nice Mockups there @Frans-Lukas, all the good possibilities are to be considered, and then the best should be implemented.

**Comment by Frans-Lukas** [comment]
I think you bring good points. There are definitely some tough choices regarding navigation to make. My opinion still stands for merging the "start-screen" and the local library screen as well as keeping the three destinations mentioned above in the navigation bar. 

`Library`, `Download`, `History`. 

It will be interesting to hear more opinions and hopefully we can come to a great conclusion that will make navigation simple and intuitive. @macgills  @mhutti1 @kelson42

**Comment by macgills** [comment]
I think the `reader` section is tough to lose, one of the primary benefits of this is that you can quickly switch from reading a zim to opening a new zim within 2 clicks at all times.

History I feel like it can not be in the sections, the "reader" is very much a browser so I like to keep it as chrome-like as possible and there are tickets to make the toolbar of that screen look more like a traditional browser address bar

**Comment by Frans-Lukas** [comment]
Ok, what are your thoughts on the bottom navigation bar in the reader? That is, how should it work together with the new bottom navigation bar? 

I gave some suggestions but feel like none of them are as intuitive as I would have liked.

**Comment by macgills** [comment]
It is very bulky but we can hide it when scrolling down and show it again while scrolling up

**Comment by 4shutosh** [comment]
Hey @Frans-Lukas just wanted to get an update what are the final bottom navigation bar destinations you are working on? 
I believe it should be the **Library**, **Downloads**, **Reader**.
(History being included inside the reader)
Is **Setting** also included in the bottom bar or is it present on every screens overflow menu like the current system? 
What about the **Home** Screen / Landing Page?

**Comment by Frans-Lukas** [comment]
Hey @4shutosh , My current plan is to do `Library`, `Downloads`, `Reader`. The plan is also to make most if not all activities into fragments and to use the [navigation component](https://developer.android.com/guide/navigation/navigation-getting-started) to handle navigation. This will allow for very easy changes in e.x. destinations of the bottom navigation bar. 

`Setting` will remain in the overflow menus as of now. 

The `home` screen/ landing page is also to be merged with `library`. However, I have still only heard your and @macgills opinions, so I am of course open to further discussion. And as mentioned, with the navigation component it will be very easy to change/add/remove destinations.
