### ISSUE TITLE
Opening library downloads data

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#2113]
**Describe the bug**

If I open the library there is data downloaded.

**Expected behavior**
When the library is opened no data should be downloaded. If I click on the tab Online then data should be downloaded. Maybe there should be even a question like "Download list now?", "Use old list with date from xx-xx-xxxx?"

**Environment**
- Version of Kiwix Android : 3.2.1.Build 230201
- Device : Samsung Galaxy S5
- OS version : LineageOS 16.0-20200419-NIGHTLY-klte

**Comment by kelson42** [comment]
I think we should have a new setting "Online catalog synchronisation":
* None
* Manually
* Automaticall

Per default it should unset and if someone go the library and this is unset then it could choose which of these 3 options he wants to have.

**Comment by kelson42** [comment]
@JensKorte @automactic I don't think this request will make sense at all if we use OPDS?

**Comment by macgills** [comment]
OPDS should solve this.

**Comment by kelson42** [comment]
The first time the user is asked if he wants to download the library as well (see #2575). I don't think it makes sense to keep longer this ticket open.
