### ISSUE TITLE
Scroll bar in the online list

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#2114]
**Is your feature request related to a problem? Please describe.**
When scrolling through the list of available zim files I don't see how long the list is. It would be nice if there is a scroll bar on the left or right side to see how far I have come or if it make sense to use  another search term.

**Describe the solution you'd like**
Just a normal scroll bar to the left or right. If the files are ordered by alphabet, language or date then it would be nice if I could see the position like "K" or "2020-04-30" somewhere.

**Comment by markZuckerberg2** [comment]
Can I work on this?

**Comment by kelson42** [comment]
I'm not convinced we should really implement this honestly. @mhutti1 @abdulwd @s-ayush2903 @gouri-panda Any opinion?

**Comment by abdulwd** [comment]
There should be some way to use the native scrollbar that shouldn't be too difficult to implement.

**Comment by mhutti1** [comment]
I agree, it would be nice.
