### ISSUE TITLE
sd card is not recognized

### ISSUE THREAD

**Issue by MichaelBruestle** [kiwix/kiwix-android#2121]
I installed kiwix 3.3.1  on a samsung s8 (android 9) but kiwi doesn't recognizes the (external) sd card. In the android settings the access to the external memory is enabled. I later deinstalled 3.3.1 and tried 3.2.0 - but it's the same. SD card is a samsung 128GB Evo (exFat formatted with > 70GB free space).
Do you have any ideas what to do?

**Comment by macgills** [comment]
@MichaelBruestle could you send a diagnostic report from the help section of the app? I may be able to diagnose the problem

**Comment by macgills** [comment]
@MichaelBruestle have you sent a diagnostic report? We are hoping to do a bugfix release by months end and I'd like to resolve your issue if I can. Please do uniquely identify yourself in the diagnostic report email if it is not obvious from your email address that it is you.

**Comment by MichaelBruestle** [comment]
@macgills thank you for your reply. I finally realized that the sd card was not working properly any longer - although other programs still could access the card. So I bought a new one and reinstalled kiwix. All the zim-files are now being detected and all is working fine.
