### ISSUE TITLE
Handle relative links between ZIM files (as is possible with Kiwix-serve)

### ISSUE THREAD

**Issue by desconectando** [kiwix/kiwix-android#2123]
I'd like to be able to link from an article in one zim file to an article in another zim file.  This is possible with kiwix-serve using:
```html
<a href="../../other_zim_filename/A/target_article_url">click me</a>
```
However, this does not work in kiwix-android.

I'd like to use this capability in some custom zim files that I'm building with non-wikimedia data.  However, I can imagine that this functionality might also be useful in more traditional wikimedia derived zim files since links between them, such as between wikipedia and wiktionary, are common.

While using links of the form shown above would be ideal (for compatibility with kiwix-serve), an alternative link/href format would be acceptable since this could be handled with different zim files provided depending on the user's platform (android vs. kiwix-serve).

**Comment by kelson42** [comment]
@desconectando Sorry for the late feedback on this. I agree this does not work, and as long as we don’t have standard ZIM scheme protocoll over all apps it won’t. Such ZIM scheme is not going to arrive soon.

On the top of this, there is a fondamental problem that we have a ZIM file which basically would work only properly in cooperation with an other one. Such kind of dependence mgmt does not exist either and there is no concrete plans to implement it.

Therefore I believe, I can honestly close this ticket as WONTFIX.
