### ISSUE TITLE
Hash ignored when linking to other article

### ISSUE THREAD

**Issue by desconectando** [kiwix/kiwix-android#2126]
When one article contains a link to another with a hash string pointing to the id of an element in the target article, that hash string is dropped. For example:
````html
<a href="target_url#target_element">Click Me</a>
````
This correctly opens target_url, but it does not scroll to the element with id="target_element".  Similarly, location.hash (checked by js in target_article) returns an empty string instead of "#target_element" as expected.

Links as shown above work correctly in kiwix-serve and kiwix-desktop, as expected based on the description of Local Anchors in the Zim file format specification at http://wiki.openzim.org/wiki/ZIM_file_format#Local_Anchors

Links to hash values within the same article work correctly.  This problem only occurs when the hash is included in a link to a different article within the zim file.

**Comment by macgills** [comment]
@kelson42 do you have any insight on how this is achieved on other clients? This seems a bit finicky to me as we would have to store if there was a `target_element` in a load call (we currently strip these out to access the resource to load) and then have a way of accessing the stored element on a completed load in the webview to then trigger auto scrolling by invoking javascript or perhaps reloading the url with the `target_element`

**Comment by macgills** [comment]
@desconectando If you can give an explicit example zim file (ideally small file size) with steps so I can recreate the issue easily then that would be a great help

**Comment by desconectando** [comment]
Attached is a small example zim file that demonstrates the use of target hash values in links.  Github wouldn't let me attach a bare zim file, so I put it into a zip archive.

Each article in this file contains links to paragraphs both within the same article and paragraphs within the other article.  Using kiwix-serve.exe and Kiwix desktop for windows, all of these links behave as expected.  However, within Kiwix android (latest version available from Google Play Store as of 7/13/2020), the links within the same article behave as expected but the links to specific target paragraphs within the other article open the other article at the top of the page rather than scrolling to the specified paragraph as expected.

[hashExample.zim.zip](https://github.com/kiwix/kiwix-android/files/4914780/hashExample.zim.zip)

**Comment by macgills** [comment]
Thank you very much.
Do you know if this was functioning in a previous version of kiwix-android? Or has it always not supported `#` links?

**Comment by macgills** [comment]
mercifully easy to implement. This fix will be released in the next version of Kiwix Android. Thank you for the help @desconectando
