### ISSUE TITLE
I copied a new Zim file and the app never worked again

### ISSUE THREAD

**Issue by eguinosa** [kiwix/kiwix-android#2127]
**Describe the bug**
The app crashes right after I open it, it doesn't matter if I have a .zim file on the phone or not. The only way to stop the bug is to denied the storage permissions to the app. How did this happen?

The app used to work perfectly fine for me, I've been using a .zim file of the English Wiktionary for a couple of months, then I decided to copy a new .zim file, this one a French Wiktionary; while I was copying the new .zim file to the phone, the copy was interrupted for some reason (perhaps because I moved the cable) and after this, the app stopped  working. I tried everything to make the app work again, delete al .zim files, uninstall the app and reinstalling it, everything, but the app kept crashing seconds after I opened it, the only thing that allowed me to open the app without crashing it, wash to denied  the storage access  to the app, which also makes it unusable.

**Expected behavior**
I expect the app to not crash each time I open it, and be able to work and load a zim file properly.

**Steps to reproduce the behavior:**
1. Try to copy a zim file to the phone an interrupt the copy.
2. After this the app no longer works, no matter what you do.

**Environment**
- Version of Kiwix Android : 3.3.1 Build: 6230301
- Device : Samsung Galaxy S20 Plus - SM-G986UI
- OS version : Android 10 - One UI 2

** Diagnostic Report  (from the app)**
Curent Zim File:
null

All Zim Files in DB:

Current Locale:
en_US

Device Details:
Device:[y2q]
Model:[SM-G986U1]
Manufacturer:[samsung]
Time:[1589453885000]
Android Version:[10]
App Version:[3.3.1 6230301]

Mount Points
MountInfo(device=/dev/block/dm-4, mountPoint=/, fileSystem=ext4)
MountInfo(device=tmpfs, mountPoint=/dev, fileSystem=tmpfs)
MountInfo(device=devpts, mountPoint=/dev/pts, fileSystem=devpts)
MountInfo(device=none, mountPoint=/dev/memcg, fileSystem=cgroup)
MountInfo(device=none, mountPoint=/dev/blkio, fileSystem=cgroup)
MountInfo(device=none, mountPoint=/dev/cg2_bpf, fileSystem=cgroup2)
MountInfo(device=none, mountPoint=/dev/cpuctl, fileSystem=cgroup)
MountInfo(device=none, mountPoint=/dev/cpuset, fileSystem=cgroup)
MountInfo(device=none, mountPoint=/dev/stune, fileSystem=cgroup)
MountInfo(device=none, mountPoint=/dev/freezer, fileSystem=cgroup)
MountInfo(device=adb, mountPoint=/dev/usb-ffs/adb, fileSystem=functionfs)
MountInfo(device=proc, mountPoint=/proc, fileSystem=proc)
MountInfo(device=sysfs, mountPoint=/sys, fileSystem=sysfs)
MountInfo(device=selinuxfs, mountPoint=/sys/fs/selinux, fileSystem=selinuxfs)
MountInfo(device=debugfs, mountPoint=/sys/kernel/debug, fileSystem=debugfs)
MountInfo(device=tracefs, mountPoint=/sys/kernel/debug/tracing, fileSystem=tracefs)
MountInfo(device=bpf, mountPoint=/sys/fs/bpf, fileSystem=bpf)
MountInfo(device=pstore, mountPoint=/sys/fs/pstore, fileSystem=pstore)
MountInfo(device=tmpfs, mountPoint=/mnt, fileSystem=tmpfs)
MountInfo(device=tmpfs, mountPoint=/mnt/secure, fileSystem=tmpfs)
MountInfo(device=tmpfs, mountPoint=/mnt/secure/asec, fileSystem=tmpfs)
MountInfo(device=/dev/block/bootdevice/by-name/persist, mountPoint=/mnt/vendor/persist, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/efs, mountPoint=/mnt/vendor/efs, fileSystem=ext4)
MountInfo(device=/data/knox/secure_fs/enc_media, mountPoint=/mnt/shell/enc_emulated, fileSystem=sdcardfs)
MountInfo(device=/data/media, mountPoint=/mnt/runtime/default/emulated, fileSystem=sdcardfs)
MountInfo(device=/data/media, mountPoint=/mnt/runtime/read/emulated, fileSystem=sdcardfs)
MountInfo(device=/data/media, mountPoint=/mnt/runtime/write/emulated, fileSystem=sdcardfs)
MountInfo(device=/data/media, mountPoint=/mnt/runtime/full/emulated, fileSystem=sdcardfs)
MountInfo(device=tmpfs, mountPoint=/apex, fileSystem=tmpfs)
MountInfo(device=/dev/block/dm-10, mountPoint=/apex/com.android.tzdata@292500000, fileSystem=ext4)
MountInfo(device=/dev/block/dm-10, mountPoint=/apex/com.android.tzdata, fileSystem=ext4)
MountInfo(device=/dev/block/dm-11, mountPoint=/apex/com.android.media@292000300, fileSystem=ext4)
MountInfo(device=/dev/block/dm-11, mountPoint=/apex/com.android.media, fileSystem=ext4)
MountInfo(device=/dev/block/dm-12, mountPoint=/apex/com.android.media.swcodec@292200000, fileSystem=ext4)
MountInfo(device=/dev/block/dm-12, mountPoint=/apex/com.android.media.swcodec, fileSystem=ext4)
MountInfo(device=/dev/block/loop5, mountPoint=/apex/com.android.apex.cts.shim@1, fileSystem=ext4)
MountInfo(device=/dev/block/loop5, mountPoint=/apex/com.android.apex.cts.shim, fileSystem=ext4)
MountInfo(device=/dev/block/loop6, mountPoint=/apex/com.android.conscrypt@290000000, fileSystem=ext4)
MountInfo(device=/dev/block/loop6, mountPoint=/apex/com.android.conscrypt, fileSystem=ext4)
MountInfo(device=/dev/block/loop7, mountPoint=/apex/com.android.resolv@290000000, fileSystem=ext4)
MountInfo(device=/dev/block/loop7, mountPoint=/apex/com.android.resolv, fileSystem=ext4)
MountInfo(device=/dev/block/loop8, mountPoint=/apex/com.android.runtime@1, fileSystem=ext4)
MountInfo(device=/dev/block/loop8, mountPoint=/apex/com.android.runtime, fileSystem=ext4)
MountInfo(device=/dev/block/platform/soc/1d84000.ufshc/by-name/metadata, mountPoint=/metadata, fileSystem=ext4)
MountInfo(device=/dev/block/dm-5, mountPoint=/product, fileSystem=ext4)
MountInfo(device=/dev/block/dm-6, mountPoint=/vendor, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/apnhlos, mountPoint=/vendor/firmware_mnt, fileSystem=vfat)
MountInfo(device=/dev/block/bootdevice/by-name/modem, mountPoint=/vendor/firmware-modem, fileSystem=vfat)
MountInfo(device=/dev/block/bootdevice/by-name/dsp, mountPoint=/vendor/dsp, fileSystem=ext4)
MountInfo(device=/dev/block/dm-7, mountPoint=/odm, fileSystem=ext4)
MountInfo(device=/dev/block/dm-8, mountPoint=/prism, fileSystem=ext4)
MountInfo(device=/dev/block/dm-9, mountPoint=/optics, fileSystem=ext4)
MountInfo(device=none, mountPoint=/acct, fileSystem=cgroup)
MountInfo(device=none, mountPoint=/config, fileSystem=configfs)
MountInfo(device=/dev/block/bootdevice/by-name/cache, mountPoint=/cache, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/sec_efs, mountPoint=/efs, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/carrier, mountPoint=/carrier, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/dqmdbg, mountPoint=/dqmdbg, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/spu, mountPoint=/spu, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/keydata, mountPoint=/keydata, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/keyrefuge, mountPoint=/keyrefuge, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/omr, mountPoint=/omr, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/userdata, mountPoint=/data, fileSystem=f2fs)
MountInfo(device=tmpfs, mountPoint=/storage, fileSystem=tmpfs)
MountInfo(device=/data/media, mountPoint=/storage/emulated, fileSystem=sdcardfs)
MountInfo(device=tmpfs, mountPoint=/storage/self, fileSystem=tmpfs)

External Directories
/storage/emulated/0/Android/data/org.kiwix.kiwixmobile/files

**Comment by macgills** [comment]
I will check our crash reports and see if anything lines up with your issue and report back here

**Comment by macgills** [comment]
I can't see anything particularly obvious but here is what it sounds like to me.

When we get storage permission we scan so we can show you a list of zim files on your device, there have been issues with this scanning when it encounters a file that is not complete. We have to open the file to read the necessary metadata to present information to the user and that fails for incomplete files. Our own downloader informs our filescanner so we avoid this very scenario during our own downloads.

My theory is that somewhere on your device there is still a partial zim file and deleting it could help you, finding it may be difficult as it could be anywhere but it explains the problem recurring through installs.

We have a ticket open that hopefully in the future this crash will be impossible but the current situation cannot be helped right now I think

**Comment by kelson42** [comment]
> We have a ticket open that hopefully in the future this crash will be impossible but the current situation cannot be helped right now I think

@macgills Would you please link the two tickets? so we can keep track with @eguinosa of the progress on this?

**Comment by macgills** [comment]
@kelson42 here is the [kiwixlib issue](https://github.com/kiwix/kiwix-lib/issues/361)

**Comment by mgautierfr** [comment]
> My theory is that somewhere on your device there is still a partial zim file and deleting it could help you, finding it may be difficult as it could be anywhere but it explains the problem recurring through installs.

Well, it seems this is the case :

>  while I was copying the new .zim file to the phone, the copy was interrupted for some reason (perhaps because I moved the cable) and after this, the app stopped working.

However, @eguinosa said that he has removed all zim files and the crash is still there.

**Comment by macgills** [comment]
My theory is dependent on the possibility they have not realised that there is a zimfile somewhere in the entire filesystem, true. It remains most plausible to me.

**Comment by kllp** [comment]
Same issue. I tried two different zim files around 38GB and 12GB big.
I copied them and checked the md5sum using the adb shell.
The files are correct and they work with kiwix desktop.
However they crash all kiwix android versions I tested. When I delete them the app works.

**Comment by macgills** [comment]
@eguinosa have you had any luck in resolving this? version 3.3.3 of kiwix is releasing now and will be fully available on Friday

**Comment by kelson42** [comment]
@eguinosa Hi, we would need your feedback to be able to continue with this ticket. See last question?

**Comment by kelson42** [comment]
No feedback. Closing.
