### ISSUE TITLE
Convert BookDataSource to Kotlin

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#2136]
Parent issue #1826 

Convert BookDataSource to Kotlin

**Comment by macgills** [comment]
I wouldn't recommend this class, the `@TableModelSpec` classes are from our deprecated databases

**Comment by yashk2000** [comment]
@macgills ok. I didn't know that. 
Do we need to make any other change related to this class since it's deprecated?

**Comment by macgills** [comment]
Well at some point we are going to delete them, it has nearly been a year since they were deprecated I think?

I think a lot of our userbase hasn't updated from 2.4 yet and once we delete these classes then they won't be able to migrate their data on an upgrade.

I'd say there is nothing to do here

**Comment by yashk2000** [comment]
@macgills ok. Thanks for the information :)
I'll work on some other issue then :rocket:
