### ISSUE TITLE
HomePage Toolbar is not visible on Back Button Pressed from Book

### ISSUE THREAD

**Issue by rutvik-panchal** [kiwix/kiwix-android#2137]
**Current Behaviour:**

Let us consider the following cases - 
1) While reading a book, the toolbar is visible and the user has to go back to the Home Page.
On back button press toolbar is visible.

![wtoolbar](https://user-images.githubusercontent.com/39809059/84481264-762cea80-acb3-11ea-98fc-3f4f967ffa1b.gif)

2) While reading a book, the toolbar is not visible and the user has to go back to the Home Page,
**On back button press toolbar is not visible.**

![toolbar](https://user-images.githubusercontent.com/39809059/84481180-58f81c00-acb3-11ea-852f-1d6ce511d8a9.gif)

**Expected Behaviour:**

Toolbar should always be displayed on the home page, it breaks the navigation.

**Comment by macgills** [comment]
We have a project underway to revamp navigation that should make this irrelevant.

The report is appreciated but I think if we were to implement this we would quickly remove it again so I will close this
