### ISSUE TITLE
Remove explicit NDK version once AGP 4.1 is in stable

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2151]
**Is your feature request related to a problem? Please describe.**
Right now we set an ndkVersion in AllProjectConfigurer, nightly.yml and coverage.yml that need to be aligned with the NDKs available on Github Actions runners. With version 4.1 of the Android  Gradle Plugin we can go back to not specifying it and it will be automatically downloaded on request.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Still a valid ticket? Can we easily fix it?

**Comment by MohitMaliFtechiz** [comment]
Hi @kelson42 ,
Yes it's a valid ticket. We are using two different NDK versions in our project.
* In ```coverage.yml``` and ```AllProjectConfigurer``` we are using NDK version ```21.4.7075529```.
* In ```nightly.yml``` we are using NDK version ```22.0.7026061```.

In our project we are using AGP(Android Gradle plugin) ```7.1.0``` which already have default NDK version ```21.4.7075529```.

![Screenshot from 2022-12-30 12-48-33](https://user-images.githubusercontent.com/34593983/210044691-b404f5dd-03ef-4105-a979-3378e8ea6c20.png)

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you easily implement the ticket?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 , Yes

**Comment by kelson42** [comment]
@MohitMaliFtechiz Formthe future, we should really try to avoid this kind of situation. Obviuosly.
