### ISSUE TITLE
Failing to load content

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2164]
**Steps to reproduce the behavior:**
1. Download Europa Universalis IV
1. Open the zim
1. Click on "Beginner's Guide"
1. Click on "Europa Universalis IV"
1. Click on "Beginner's Guide"
1. Page does not load

In Step 2 the url in the webview is `PREFIX//A/Europa_Universalis_4_Wiki` this is correct and loads as expected
In Step 3 the url in the webview is `PREFIX/A/Beginner's_guide` this loads as expected
In Step 4 the url in the webview is `PREFIX/wiki/Europa_Universalis_IV` this is incorrect and should have an `A/` prefix, this causes an empty load which results in us returning to the main page
In Step 5 the url in the webview is `PREFIX/Beginner's_guide` which is incorrect and does nothing

**Comment by kelson42** [comment]
yes, the ZIM file is bad I beleive.

**Comment by macgills** [comment]
Closing
