### ISSUE TITLE
[Feature request]Global search

### ISSUE THREAD

**Issue by Mitia99** [kiwix/kiwix-android#2167]
Feature request:Global search(same word but result of all the sources)
![Screenshot_20200628_113256](https://user-images.githubusercontent.com/56766778/85942714-b1761d00-b933-11ea-87ba-38a156d896fd.jpg)

**Comment by macgills** [comment]
I believe this was an experimental feature "MultiZim search"
Found the [ticket](https://github.com/kiwix/kiwix-android/issues/54), closing. Thank you for the request.
