### ISSUE TITLE
It would be nice that large books could be downloaded directly on the device

### ISSUE THREAD

**Issue by stumpelrilz** [kiwix/kiwix-android#2169]
Current situation:
To download books (zim-files) that are larger 4GB I have to download it on the PC, split it and transfer it to the (android-)smartphone, because android(-7) uses a filesystem for SD-Cards that cannot use more than 4GB per file.

Wish:
It would be nice to download and split large zims directly on the phone.

**Comment by kelson42** [comment]
ZIM files could/should not be splitted anymore. If it works, this is only by chance. We have plans to reintroduce a smart split, but no real agenda for now, see https://github.com/kiwix/kiwix-tools/issues/287.

**Comment by florian29** [comment]
> because android(-7) uses a filesystem for SD-Cards that cannot use more than 4GB per file.

you should format the SD-Card with exFAT, than Android can handle very large files, I can confirm you that it works even with Android 4

**Comment by macgills** [comment]
As there is no action to take on the android side, I will be closing this ticket. Hopefully you have some luck formatting your sdcard with exfat @stumpelrilz
