### ISSUE TITLE
Make publishing new kiwix-libs to jcenter easier

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#217]
Either implement a manual process or automated one.

**Comment by kelson42** [comment]
@mhutti1 What would exactly be needed to be uploaded? Could you make do the first and document the process?

**Comment by mhutti1** [comment]
@kelson42 It is already uploaded. The process involves building kiwixlib for each architecture, collating the libs directories, copying them to a template android module directory and then incrementing three numbers in a script and then running a gradle command. The template module only contains a handful of files but we should proberberly upload it somewhere.

**Comment by kelson42** [comment]
@mhutti1 
OK. If you want someone else than you to do that work, we could probably work to somehow automate this... but this need to  be documented first somewhere.

**Comment by mhutti1** [comment]
@kelson42 Yeah i'll sort it all out.

**Comment by macgills** [comment]
superseded by #489 closing
