### ISSUE TITLE
Issue Opening Bouquineux 

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2174]
**Describe the bug**
Ca fait 2 fois que je télecharge Bouquinieux et que je n'arrive pas à acceder aux livres. Le télechargement s'effectue en totalité sans problème,  mais qd je cherhe à ouvrir bouquineux, ce sont des lignes de code qui s'affichent et impossible de faire autre chose.
J'essaie de vous envoyer une page ecran dans le mail suivant.

**Screenshots**

![2020_06_28_17 58 02](https://user-images.githubusercontent.com/3358282/86018026-b236ae00-ba1c-11ea-9cf1-e4ede871f4d6.jpg)

**Environment**
- Version of Kiwix Android : 3.3.1

**Comment by kelson42** [comment]
I can reproduce the problem.

**Comment by kelson42** [comment]
We are preparing a new ZIM.

**Comment by kelson42** [comment]
@macgills The only thing which can fail here is the the mime-type delivered by the ZIM is `text/html; charset=utf-8`. Probably Kiwix Android can not handle properly the extended mime-type attribute. Can you please try to skip it just before giving the information to the web-renderer?

**Comment by macgills** [comment]
should be straightforward, just `substringBefore(";")` I imagine

**Comment by thebiz98** [comment]
@macgills Could you please describe the bug in English? Also, this would be my first time contributing to open source, so any suggestions? I have already read the Contribution guide

**Comment by kelson42** [comment]
@thebiz98 This file https://download.kiwix.org/zim/other/bouquineux_fr_all_2013-07.zim does not rendere properly, wee see the HTML code as text in place of having it rendered.

**Comment by MohitMaliFtechiz** [comment]
https://github.com/kiwix/kiwix-android/issues/2814

**Comment by MohitMaliFtechiz** [comment]
https://github.com/kiwix/kiwix-android/issues/2814
