### ISSUE TITLE
ZimFileReaders not being disposed

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2175]
**Describe the bug**
When a FileReader is allocated it takes up a portion of native memory which must be explicitly freed or the memory could grow uncontrollably

**Expected behavior**
The app continues to run smoothly regardless of the amount of FileReaders created

**Comment by kelson42** [comment]
@macgills Seems important to have in the 3.3.2

**Comment by macgills** [comment]
@kelson42 yeah, the problem surfaced as part of the new navigation so I might merge this to develop somewhat quickly to unblock that
