### ISSUE TITLE
Remove home/library webview from reader fragment in new navigation.

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2179]
**Is your feature request related to a problem? Please describe.**

As the new navigation system provides easier access to the library we want to remove the library view from the webview. It should instead be replaced with text and a button directing the user to the library destination.

**Describe the solution you'd like**

A couple of things needs to change for the home view to disappear, the ones I can count now are:
1. Pressing the 'close all tabs' button from the tab view should close all tabs and show an empty view with the redirection text and button. 
2. Pressing the new tab button ('+'-icon from the tab view) should open a new tab with the home page of the currently opened zim file. 
3. Closing all tabs should show the empty view with redirection text and button (similar to 1.).

Please include other ways of reaching the current home page/clearing all tabs if you can think of any. 

**Additional context**

Part of the new navigation feature branch @feature/navigation

**Comment by macgills** [comment]
You can press back on the current reader fragment which will eventually show the "home" page after it shows the main page of the zim. This should probably just exit the app?

**Comment by Frans-Lukas** [comment]
I am thinking it should exit the book to the "No book open" page first, then exit the app.

**Comment by macgills** [comment]
Try playing around with a browser on android and try and replicate the behaviour they have
