### ISSUE TITLE
Is fully zoomed out display a Kiwix or a phone / android issue?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2180]
I'd suspect it's a Xiaomi thing, but asking anyway. 
A user sent this, saying this is their current display on a Xiaomi Redmi note 8 pro

![Screenshot_2020-07-01-08-08-15-650_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/86214708-c5ac5b00-bb7b-11ea-99c0-f843dd014068.jpg)

**Comment by macgills** [comment]
We have added a new feature in 3.2.2 to allow controlling the text zoom

**Comment by Popolechien** [comment]
Wut? Where do you manage that?

**Comment by macgills** [comment]
Once the latest release is out if a user goes to settings there is a slider they can drag. It is different from our previous feature of setting the initial scale of a webview which was removed. 

*3.3.2 earlier comment had a typo

**Comment by Popolechien** [comment]
> *3.3.2 earlier comment had a typo

Here we go. Thanks.
