### ISSUE TITLE
Use LeakCanary Plumber when it is less experimental

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2182]
**Is your feature request related to a problem? Please describe.**
LeakCanary has released a library to "fix" well known leaks in Android itself
```
com.squareup.leakcanary:plumber-android
```
but it is a recent release marked as experimental

**Comment by kelson42** [comment]
I’m not in favour of autofix. Memory leaks are now detected automatically in the CI and that seems good enough to me.
