### ISSUE TITLE
Kiwix 3.3.2 beta crashes on opening on Android 4.4.4

### ISSUE THREAD

**Issue by florian29** [kiwix/kiwix-android#2188]
Impossible to open the latest beta 3.3.2. App crashes on opening. Android 4.4.4, Samsung S4 mini, also tested with Bluestacks App Player for Android 4.4.4. Clearing the data base and the cache won't solve the problem.
The version 3.3.1 only crashes if there are newer ZIM files from June 2020 present on the SD card. If there are only older ZIM files, the 3.3.1 doesn't crash and let's you open the older ZIM files. The 3.3.2 crashes including without the presence of newer ZIM files.

**Comment by kelson42** [comment]
@florian29 Thank you for having opened a new ticket.

**Comment by florian29** [comment]
> Would you be able to reduce it to one which makes the app crashing? I guess if you have no ZIM at all the app will start properly.

I tried to open the app with no ZIM at all on the Bluestacks player and it crashes immediately. On my phone I renamed all the ZIM files to *.1 instead of *.zim, so that the Kiwix app wouldn't recognize that files anymore (that was what I did with the newer ZIM files which caused the 3.3.1 version to crash, after renaming them I could open the Kiwix 3.3.1) but it doesn't make any difference, the 3.3.2 version can't be opened.

**Comment by florian29** [comment]
I tested it now with a Samsung Tablet with Android 5.0.2 and it works. The Kiwix 3.3.2 app opens in a normal way. But I can't open it with Android 4.4.4 (see above). When trying to open it crashes immediately and shows this message (my phone is in spanish):
![Screenshot_2020-07-03-21-37-39](https://user-images.githubusercontent.com/43439672/86494569-f7891180-bd75-11ea-93c0-d42e4ab53522.png)

The file logcat.txt in the Kiwix directory in the internal storage only has two lines:

--------- beginning of /dev/log/main
--------- beginning of /dev/log/system 

Can I do something more to locate the problem? The Kiwix 3.3.1 app opened without problems. I'm sure there must be a way to solve this. Thank you in advance!

**Comment by kelson42** [comment]
@macgills I confirm the problem on 4.2.2.

**Comment by macgills** [comment]
I will check the console for a crash report, failing that launch an emulator

**Comment by florian29** [comment]
I confirm that the version 3.3.3 works with Android 4.4.4. Thank you!
