### ISSUE TITLE
[Wikimed beta] Application corrupt. 

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-android#219]
Play store update automatically my wikimed application.
But trying to launch it, I've got a message saying it is corrupt : 
```Your application is corrupted.
This might happen when you remove files on the SD Card.
You need to uninstall then reinstall the App from the Play Store'```

From the "application menu" the wikimed version is "2017-08".
From the play console, this correspond to bêta application (172130 => 2/08/2017).

My previous version was the last alpha version (probably the one I've published).

**Comment by mhutti1** [comment]
Google Play calls the expansion file main.172130.org.kiwix.kiwixcustomwiki for all versions. This is only the correct name for one of the architectures though. Either we need to upload multiple, proberbly not a good idea or reconfigure all versions to use the 1.... version.  https://github.com/kiwix/kiwix-android/blob/master/app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.java#L86

**Comment by mgautierfr** [comment]
> Google Play calls the expansion file main.172130.org.kiwix.kiwixcustomwiki for all versions

This is normal. All apk use the same expansion file.
This is setup in `build_custom_app.py` at upload here (https://github.com/kiwix/kiwix-build/blob/master/build_custom_app.py#L401-L408). And confirm in google play console, each apk is using `main.172130.org.kiwix.kiwixcustomwikimed.obb
` expansion file.

This was already the case in the previous alpha version.

**Comment by mhutti1** [comment]
I can reproduce on my end. I have check the file system and the new file is there and correctly named. There must be an issue with either permissions, location size or name. I will try to work out which this evening.

**Comment by kelson42** [comment]
I think this was my fault

**Comment by mgautierfr** [comment]
Is it fixed? 
Have you published a new version?

**Comment by kelson42** [comment]
@mgautierfr Yes
