### ISSUE TITLE
chore: Convert SharedPreferenceUtil.java to Kotlin Class

### ISSUE THREAD

**Issue by s-ayush2903** [kiwix/kiwix-android#2200]
Currently, SharedPreferenceUtil.java is written in java, it should be instead in Kotlin.
For more info.:
Refer #1826

**Comment by s-ayush2903** [comment]
I would like to work on this issue.

**Comment by s-ayush2903** [comment]
@macgills Anything left here?

**Comment by macgills** [comment]
I tagged you on a PR, tldr this broke the online library, we will redo it and be more careful

**Comment by kelson42** [comment]
@s-ayush2903 Do you plan to fix the regression?

**Comment by s-ayush2903** [comment]
Yeah definitely, i'll move it to top in my list
