### ISSUE TITLE
Can't open videos

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2202]
**Describe the bug**
When clicking a video, the video is not started. Tested on `master`, `develop` and `feature/navigation`. As well as the published app, but it has a different issue where instead of not opening the video the page gets blank when the video is clicked. 

**Expected behavior**
When a video is clicked, it should open. (I don't know what the expected behavior for videos are as I have not tried opening a video before and it is not working on any branch I've tried, or for the published app). However, I have only tried with three ted talk files, perhaps the ted talk files are corrupt/bad? 

![bild](https://user-images.githubusercontent.com/22193232/87291637-e66f9b80-c4ff-11ea-9d5d-fc7bed6e8924.png)

**Steps to reproduce the behavior:**
1. Download a file with a video in it.
2. Open the file and locate the video.
3. Click the video and see that nothing happens. 

**Screenshots**
![untitled](https://user-images.githubusercontent.com/22193232/87292101-98a76300-c500-11ea-8809-c6531e45eebb.gif)

**Logs**
No crash or error just logcat. https://pastebin.com/RzvSnQ0u

**Comment by macgills** [comment]
Le Mali Pour Les Nuls is playing the video but there is an issue with fullscreen video, I'll investigate a TED file now

**Comment by macgills** [comment]
With TED - Fighting Imposter Syndrome it seems like the links are broken

```
2020-07-13 11:16:51.841 D/ZimFileReader: getting mimetype for zim://content/I/favicon.png = image/png
2020-07-13 11:16:51.844 D/ZimFileReader: reading  I/favicon.png(mime: image/png, size: 701) finished.
2020-07-13 11:16:51.875 D/ZimFileReader: getting mimetype for zim://content/ = text/html
2020-07-13 11:16:51.875 D/kiwix: Loaded URL: zim://content/
2020-07-13 11:16:51.877 D/ZimFileReader: reading  (mime: text/html, size: 6176) finished.
2020-07-13 11:16:52.163 D/kiwix: Loaded URL: zim://content/
2020-07-13 11:16:52.164 D/kiwix: Loaded URL: zim://content/
```

what we try to load is the empty url which obviously does nothing. 

@kelson42 I will inspect the html but at this point I think there was an issue at zim creation

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/87293979-fdf85580-c4fa-11ea-9799-f0e848bba23e.png)

Hmmm link seems fine.

The problem is when we get the redirect for this article it returns the empty `zim://content/`

**Comment by macgills** [comment]
Our options are fix the zim/kiwixlib? Or we report the empty string as not being a valid redirect result

**Comment by macgills** [comment]
opened a separate ticket for the fullscreen video bug  #2203

**Comment by kelson42** [comment]
@rgaudin Would you be able to give a feedback on this please?

**Comment by kelson42** [comment]
> Le Mali Pour Les Nuls is playing the video but there is an issue with fullscreen video, I'll investigate a TED file now

Looks like a serious regression to me. I can confirm the bug with the Mali ZIM file.

**Comment by kelson42** [comment]
@macgills @Frans-Lukas Which file are we exactly talking about?

**Comment by Frans-Lukas** [comment]
@kelson42 None of the ones shown in this image works:


![bild](https://user-images.githubusercontent.com/22193232/87298336-52570180-c50a-11ea-9f88-f60f80726fcc.png)


- The lights and sounds of the universe
- The race for your attention
- Why it's (sometimes) good to be bored

**Comment by kelson42** [comment]
@Frans-Lukas It is always important to focus on a concrete thing which fails, otherwise we might follow diffierent tracks. This is why I ask which file exactly.

**Comment by Frans-Lukas** [comment]
Is this file naming ok? ted_en_playlist-581_2020-07.zim

**Comment by rgaudin** [comment]
All images and videos works for me using kiwix-desktop. Just stating the fact that this seems android-specific at the moment.

**Comment by macgills** [comment]
@rgaudin is kiwix desktop using v9.2.3 of kiwixlib or are you mapping blank redirects to original urls?

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/87393937-da8ae480-c5a6-11ea-9db0-ed6bd1c505d7.png)
my rejecting blank redirects I can load the video

**Comment by rgaudin** [comment]
> @rgaudin is kiwix desktop using v9.2.3 of kiwixlib or are you mapping blank redirects to original urls?

Actually I meant kiwix for macOS which was just released. I don't know the kiwix-lib version in use (statically linked) but what I know is that we have no redirect in this ZIM (except -/favicon I guess).
It's built with zimwriterfs and doesn't use the redirect option.

So there might be another issue making it appear as blank redirects…

**Comment by macgills** [comment]
In kiwix-android when we are loading a url we must detect if there is a redirect (I remember this being a problem when we tried to load a random article on a lot of zims) and we do so by saying `isRedirect =originalUrl != getRedirectUrl(originalUrl)`

If a url was not a redirect then the jniCall would return the original.

@mgautierfr do you know if there have been any changes to the behaviour of `jniKiwixReader.checkUrl` ?

**Comment by macgills** [comment]
After discussions with kelson it seems the error is not removing text after `?` when passing to `checkUrl`, fix incoming

**Comment by kelson42** [comment]
@MohitMaliDeveloper Any news here? Are we OK now with TW (all the tickets have been closed)? Can we merge (still without modifying manually the PR)? If "not" please open corresponding bug tickets.
