### ISSUE TITLE
Fullscreen Video does not display

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2203]
**Describe the bug**
Only a white screen is shown with no video or controls

**Expected behavior**

**Steps to reproduce the behavior:**
1. Open Mali les Pour les Nuls
1. click fullscreen on a video

**Comment by kelson42** [comment]
Looks like a serious regression to me. I can confirm the bug with the Mali ZIM file.

**Comment by macgills** [comment]
regression introduced in 0ebbdf5bf8e8c51df56e56e256ad41f35475c655 

Why the conversion to fragment caused this is a head scratcher, will dig deeper.

**Comment by macgills** [comment]
Null view is passed for `root`, fix incoming

**Comment by macgills** [comment]
Correction, the view of a fragment was being passed as root view instead of the view at the correct layer of the heirarchy.
