### ISSUE TITLE
Perform contrast audit on all screens to check accessibility. 

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2212]
**Is your feature request related to a problem? Please describe.**
"..a contrast audit is well overdue, ...but some bits of dark mode look a mite gloomy and the switches in bookmarks/history can look hard to distinguish." -Macgills 

I agree as well, also for the book tags in dark mode. 

**Describe the solution you'd like**
Run the [accessibility scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor) on (all?) activities/views. In dark mode, and light mode. This ticket also includes the fixes of potential contrast errors.

**Comment by Frans-Lukas** [comment]
# Dark Theme
Results when running the accessibility tool on some activities. I left out some views that did not seem relevant, like the contrast of a button on an opened zim page being slightly below the recommended value. 

**"Support Kiwix" options menu:**
<img src="https://user-images.githubusercontent.com/22193232/87542490-510d0c80-c6a3-11ea-9415-f34b7a92b938.jpg" alt="drawing" height="200"/>

**Bookmarks switch:**
<img src="https://user-images.githubusercontent.com/22193232/87542492-51a5a300-c6a3-11ea-9a5e-751d7bce9286.jpg" alt="drawing" height="200"/>

**Bookmarks container:**
<img src="https://user-images.githubusercontent.com/22193232/87542496-523e3980-c6a3-11ea-97c4-d16001f7d23c.jpg" alt="drawing" height="200"/>

**Book tag:**
<img src="https://user-images.githubusercontent.com/22193232/87542497-523e3980-c6a3-11ea-8437-24444c3c46d4.jpg" alt="drawing" height="200"/>

**Book label:**
<img src="https://user-images.githubusercontent.com/22193232/87542499-52d6d000-c6a3-11ea-81e9-ac993b5517b5.jpg" alt="drawing" height="200"/>

**Library close search button:**
<img src="https://user-images.githubusercontent.com/22193232/87542500-52d6d000-c6a3-11ea-8cfc-6fe19edadcca.jpg" alt="drawing" height="200"/>

**Book tag extended:**
<img src="https://user-images.githubusercontent.com/22193232/87542502-52d6d000-c6a3-11ea-9b68-7ed2a0108736.jpg" alt="drawing" height="200"/>

**Close "send to nearby device activity":**
<img src="https://user-images.githubusercontent.com/22193232/87542504-536f6680-c6a3-11ea-8b2f-183fd1e97ccb.jpg" alt="drawing" height="200"/>

**History switch:**
<img src="https://user-images.githubusercontent.com/22193232/87542505-536f6680-c6a3-11ea-9e51-c22c7a278ed1.jpg" alt="drawing" height="200"/>

**"Help" options menu destination:**
<img src="https://user-images.githubusercontent.com/22193232/87542509-536f6680-c6a3-11ea-91ac-b0eb58004b69.jpg" alt="drawing" height="200"/>

**Settings:**
<img src="https://user-images.githubusercontent.com/22193232/87542510-5407fd00-c6a3-11ea-9c3d-f04be047d81f.jpg" alt="drawing" height="200"/>

**Comment by Frans-Lukas** [comment]
# Light Theme
Some contrast issues exists in the light theme as well.

**Book tag:**
<img src="https://user-images.githubusercontent.com/22193232/87546444-dc899c00-c6a9-11ea-8bd7-01ed36bbf817.jpg" alt="drawing" height="200"/>

**Header date text:**
<img src="https://user-images.githubusercontent.com/22193232/87546446-dd223280-c6a9-11ea-8f58-6303d1e020f5.jpg" alt="drawing" height="200"/>

**Number of articles text:**
<img src="https://user-images.githubusercontent.com/22193232/87546448-dd223280-c6a9-11ea-9904-61092c13aca5.jpg" alt="drawing" height="200"/>

**More of the same text:**
<img src="https://user-images.githubusercontent.com/22193232/87546449-ddbac900-c6a9-11ea-9845-9b32c2dc37d2.jpg" alt="drawing" height="200"/>

**Comment by macgills** [comment]
We should also update the design guidelines with how to assess contrast perhaps?

**Comment by Frans-Lukas** [comment]
With https://contrast-ratio.com , https://material.io/design/color/the-color-system.html#tools-for-picking-colors etc?

**Comment by macgills** [comment]
Yeah, it could be handy to point people towards

**Comment by macgills** [comment]
and the accessibility scanner

**Comment by Frans-Lukas** [comment]
Agreed!

**Comment by Frans-Lukas** [comment]
![image](https://user-images.githubusercontent.com/22193232/87652772-eb795880-c754-11ea-83ed-e5b004ae5e30.png)

**Comment by macgills** [comment]
We want it so that in the on state the right most point of the switch is aligned with the right most point of the trash icon, if possible. Also a smidge more padding between the text and the switch, just so when it is off they aren't so close but not so much that when on it looks too far away

**Comment by Frans-Lukas** [comment]
The full range of the switch is larger than the width of the thrashcan. 

![image](https://user-images.githubusercontent.com/22193232/87655075-0e593c00-c758-11ea-8cd7-8b694e6fc58c.png)
![image](https://user-images.githubusercontent.com/22193232/87655105-187b3a80-c758-11ea-8331-60bed193ef6a.png)

**Comment by Frans-Lukas** [comment]
New text color on tags and description for increased contrast. 

![image](https://user-images.githubusercontent.com/22193232/87655268-50827d80-c758-11ea-9f8a-b76d15616018.png)

**Comment by Frans-Lukas** [comment]
New primary color for dark theme. (The blue one used on the button text.)

![image](https://user-images.githubusercontent.com/22193232/87655577-bcfd7c80-c758-11ea-9944-c91328423516.png)

**Comment by macgills** [comment]
Re, the switch: yes it does have an awkaward width but right now in the on position it makes your eyes do this

![image](https://user-images.githubusercontent.com/3358282/87655572-583e2400-c750-11ea-870e-1926c0f79150.png)

and I want a clean vertical

**Comment by Frans-Lukas** [comment]
![image](https://user-images.githubusercontent.com/22193232/87655731-e8806700-c758-11ea-9812-0e59bc37cb4d.png)

So this one is better, maybe a bit more to the right? It can either be centered or odd looking when off.

**Comment by macgills** [comment]
Odd looking when off is fine, violating a screen's margin is a worse visual offence. The eye can go inward it can't bulge out

**Comment by Frans-Lukas** [comment]
**10dp right padding:**
![image](https://user-images.githubusercontent.com/22193232/87782019-08d02480-c832-11ea-8cf8-a621e934a918.png)

**Comment by Frans-Lukas** [comment]
I'd like to change this to a darker green and red, or make it blue to have good contrast. What do you think? 

<img src="https://user-images.githubusercontent.com/22193232/88036439-d715d100-cb43-11ea-9f67-0930c54c7784.png" alt="drawing" height="600"/>

**Comment by macgills** [comment]
I think darker green/red is fine, this button occupies the same space so we want an instantaneous visual distinction that it is in a separate state so it being in blue will not help with that, reading text on a button is not something people really do a lot

**Comment by Frans-Lukas** [comment]
Ok, cool!

**Comment by Frans-Lukas** [comment]
# Discussion on changes

### Tab View
1. Missing label for tabs.
2. Close tab button is too small.
<img src="https://user-images.githubusercontent.com/22193232/88040232-e21f3000-cb48-11ea-8df0-52c45b0d974a.png" alt="drawing" height="600"/>


### Host book view
t's complaining about duplicate labels or missing labels on the background of the cards. 
<img src="https://user-images.githubusercontent.com/22193232/88040236-e2b7c680-cb48-11ea-82f1-a2f85dff1db0.jpg" alt="drawing" height="600"/>
<img src="https://user-images.githubusercontent.com/22193232/88040238-e2b7c680-cb48-11ea-8702-1a6b4ad0b364.jpg" alt="drawing" height="600"/>

### History/Bookmarks
1. The view all history switch is 48dp now. 
2. It's complaining abut duplicate labels and image contrasts which is fine I think. (We can't do anything about the image contrast).
<img src="https://user-images.githubusercontent.com/22193232/88040239-e2b7c680-cb48-11ea-9689-c3c6084e6fb8.jpg" alt="drawing" height="600"/>

### Help activity
This is also complaining about duplicate item descriptions and touch target sizes, both of which should be fine.
<img src="https://user-images.githubusercontent.com/22193232/88040241-e3505d00-cb48-11ea-9db1-0776b3302760.jpg" alt="drawing" height="600"/>

### Settings
1. Missing label on the zoom slider. It has a description that should be readable by a screen reader?
<img src="https://user-images.githubusercontent.com/22193232/88040245-e3e8f380-cb48-11ea-98a8-c697df92fecc.jpg" alt="drawing" height="600"/>

### Tab closed snackbar
1. The snackbar uses an odd color? It's a shade of white with black text and stands out a lot in dark mode. Any suggestions on if this should change? I made the button color darker to increase contrast. 
<img src="https://user-images.githubusercontent.com/22193232/88040247-e3e8f380-cb48-11ea-9fae-67d1a396eeed.jpg" alt="drawing" height="600"/>
