### ISSUE TITLE
Question: download zim from local server

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-android#2214]
I have the impression that in the past it was possible to enter the url from which zims should be downloaded, but I can't find that in version 3.3.1.

**Comment by kelson42** [comment]
@tim-moody I don't believe we had this feature at any point.

**Comment by tim-moody** [comment]
@kelson42 

> You can download the ZIM file yourself from anywhere

Do you mean outside of kiwix.apk? 

>or use the integrated downloader.

What do you mean by 'integrated downloader'? How does kiwix.apk find the zim in the phone?

**Comment by kelson42** [comment]
The title and your comment talks about ZIM files. I talk about ZIM files, not about the Kiwix-Android APK.But if you want to know where to download the Kiwix-Android APK, they are all available here https://download.kiwix.org/release/kiwix-android/.

**Comment by tim-moody** [comment]
I want the already downloaded and installed Kiwix-Android APK app to download ZIM files from a local server.

**Comment by kelson42** [comment]
This is not part and has not been part of the feature portfolio of Kiwix-Android AFAIK.

**Comment by tim-moody** [comment]
Got it now.
