### ISSUE TITLE
Impossible to read warc2zim generated ZIM files

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2222]
We are working on warc2zim, a tool able to create ZIM file from a WARC file. These ZIM files integrates a JS player relying on service-worker. You can find an example of file here:
http://tmp.kiwix.org/warc2zim.zim

I don't have achieved to read such a ZIM file. Maybe this is due to the custom protocol scheme zim://

**Comment by kelson42** [comment]
@macgills Would be great if you could confirm the technical nature of the problem here.

**Comment by macgills** [comment]
Not particularly sure what is happening as I see no obvious problem in loading anything.

We load the html
```
<html>
    <head>
    <style>
    body {
      width: 100%
      height: 100%;
      overflow-y: hidden;
      margin: 0px;
      padding: 0px;
    }
    </style>
    <script src="./replay/ui.js"></script>
    </head>
    <body>
    <replay-web-page
     source="../netpreserve-twitter.warc"
     replayBase="./replay/"
     deepLink="true"
     embed="replayonly"
     url="https://twitter.com/netpreserve"></replay-web-page>
    </body>
    </html>
```

and we load the js
```
 /*! ui.js is part of ReplayWeb.page (https://replayweb.page) Copyright (C) 2020, Webrecorder Software. Licensed under the Affero General Public License v3. */
    !function(e,t){for(var i in t)e[i]=t[i]}(self,function(e){var t={};function i(a){if(t[a])return t[a].exports;var o=t[a]={i:a,l:!1,exports:{}};return e[a].call(o.exports,o,o.exports,i),o.l=!0,o.exports}return i.m=e,i.c=t,i.d=function(e,t,a){i.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:a})},i.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},i.t=function(e,t){if(1&t&&(e=i(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var a=Object.create(null);if(i.r(a),Object.defineProperty(a,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)i.d(a,o,function(t){return e[t]}.bind(null,o));return a},i.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(t,"a",t),t},i.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},i.p="/",i(i.s=222)}({100:function(e,t){e.exports='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M448 360V24c0-13.3-10.7-24-24-24H96C43 0 0 43 0 96v320c0 53 43 96 96 96h328c13.3 0 24-10.7 24-24v-16c0-7.5-3.5-14.3-8.9-18.7-4.2-15.4-4.2-59.3 0-74.7 5.4-4.3 8.9-11.1 8.9-18.6zM128 134c0-3.3 2.7-6 6-6h212c3.3 0 6 2.7 6 6v20c0 3.3-2.7 6-6 6H134c-3.3 0-6-2.7-6-6v-20zm0 64c0-3.3 2.7-6 6-6h212c3.3 0 6 2.7 6 6v20c0 3.3-2.7 6-6 6H134c-3.3 0-6-2.7-6-6v-20zm253.4 250H96c-17.7 0-32-14.3-32-32 0-17.6 14.4-32 32-32h285.4c-1.9 17.1-1.9 46.9 0 64z"></path></svg>'},101:function(e,t){e.exports='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M464 32H48C21.49 32 0 53.49 0 80v352c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V80c0-26.51-21.49-48-48-48zm-6 400H54a6 6 0 0 1-6-6V86a6 6 0 0 1 6-6h404a6 6 0 0 1 6 6v340a6 6 0 0 1-6 6zm-42-92v24c0 6.627-5.373 12-12 12H204c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h200c6.627 0 12 5.373 12 12zm0-96v24c0 6.627-5.373 12-12 12H204c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h200c6.627 0 12 5.373 12 12zm0-96v24c0 6.627-5.373 12-12 12H204c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h200c6.627 0 12 5.373 12 12zm-252 12c0 19.882-16.118 36-36 36s-36-16.118-36-36 16.118-36 36-36 36 16.118 36 36zm0 96c0 19.882-16.118 36-36 36s-36-16.118-36-36 16.118-36 36-36 36 16.118 36 36zm0 96c0 19.882-16.118 36-36 36s-36-16.118-36-36 16.118-36 36-36 36 16.118 36 36z"></path></svg>'},102:function(e,t){e.exports='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M149.9 349.1l-.2-.2-32.8-28.9 32.8-28.9c3.6-3.2 4-8.8.8-12.4l-.2-.2-17.4-18.6c-3.4-3.6-9-3.7-12.4-.4l-57.7 54.1c-3.7 3.5-3.7 9.4 0 12.8l57.7 54.1c1.6 1.5 3.8 2.4 6 2.4 2.4 0 4.8-1 6.4-2.8l17.4-18.6c3.3-3.5 3.1-9.1-.4-12.4zm220-251.2L286 14C277 5 264.8-.1 252.1-.1H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h288c26.5 0 48-21.5 48-48V131.9c0-12.7-5.1-25-14.1-34zM256 51.9l76.1 76.1H256zM336 464H48V48h160v104c0 13.3 10.7 24 24 24h104zM209.6 214c-4.7-1.4-9.5 1.3-10.9 6L144 408.1c-1.4 4.7 1.3 9.6 6 10.9l24.4 7.1c4.7 1.4 9.6-1.4 10.9-6L240 231.9c1.4-4.7-1.3-9.6-6-10.9zm24.5 76.9l.2.2 32.8 28.9-32.8 28.9c-3.6 3.2-4 8.8-.8 12.4l.2.2 17.4 18.6c3.3 3.5 8.9 3.7 12.4.4l57.7-54.1c3.7-3.5 3.7-9.4 0-12.8l-57.7-54.1c-3.5-3.3-9.1-3.2-12.4.4l-17.4 18.6c-3.3 3.5-3.1 9.1.4 12.4z"></path></svg>'},103:function(e,t){e.exports='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M371.7 238l-176-107c-15.8-8.8-35.7 2.5-35.7 21v208c0 18.4 19.8 29.8 35.7 21l176-101c16.4-9.1 16.4-32.8 0-42zM504 256C504 119 393 8 256 8S8 119 8 256s111 248 248 248 248-111 248-248zm-448 0c0-110.5 89.5-200 200-200s200 89.5 200 200-89.5 200-200 200S56 366.5 56 256z"></path></svg>'},104:function(e,t,i){const a=i(124),o=i(126),r=i(63),n=i(64),s=i(65),l=i(66),{merge:c,checkSanitizeDeprecation:d,escape:h}=i(23),{getDefaults:f,changeDefaults:b,defaults:u}=i(22);function p(e,t,i){if(null==e)
```

Do we have a working version on the web that can be loaded with an Android browser?

**Comment by rgaudin** [comment]
@macgills here's a simpler example http://tmp.kiwix.org/basicsw.zim

`index.html`

```html

<html>
<head>
</head>
<body>
<div id="status">
Status:
</div>
<script>

async function register() {
  var div = document.querySelector("#status");

  if (!navigator.serviceWorker) {
    div.innerText = "No SW Support";
    return;
  }

  try {
    await navigator.serviceWorker.register("sw.js", {"scope": "./"});
  } catch (e) {
    div.innerText = "Error: " + e;
    return;
  }

  await navigator.serviceWorker.ready;

  const resp = await fetch("./replay/url");

  if (resp.status == 404) {
    setTimeout(async () => {
      const resp = await fetch("./replay/url");
      div.innerText = await resp.text();
    }, 1000);
  } else {
    div.innerText = await resp.text();
  }
}

register();
</script> 
</body>
</html>
```

`sw.js`

```js

self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
  console.log("Activate!");
});

self.addEventListener('fetch', (event) => {

  const opts = {};
  if (event.request.cache === 'only-if-cached' && event.request.mode !== 'same-origin') {
    opts.cache = 'default';
  }

  if (event.request.url.endsWith("/replay/url")) {
    event.respondWith(new Response("this is a response from the service worker"));
  } else {
    event.respondWith(fetch(event.request, opts));
  }
});
```

**Comment by macgills** [comment]
Renders "No SW support"

From this [question with no answer](https://stackoverflow.com/questions/61478376/how-to-use-service-workers-in-android-webview)
>I went through Android's WebKit, there it was specified that for service worker support in WebView we need to use ServiceWorkerClient and ServiceWorkerController, but it is not clear, that, how exactly to use them with the WebView.

Looks like I have some googling to do

**Comment by kelson42** [comment]
@macgills You might have (at least) to add some kind of authorisation to add to the widet.

**Comment by macgills** [comment]
`ServiceWorkerClient Added in API level 24` ahhh but there is an androidx version, trying that out. It sounds a bit unpleasant as you register 1 ServiceWorkerClient for the entire application
`

**Comment by macgills** [comment]
Seems like this will only be available to a subset of users and perhaps depending on the features we want a further subser?

![image](https://user-images.githubusercontent.com/3358282/88028328-69ac7500-cb30-11ea-9aa8-511c17f2e366.png)

**Comment by macgills** [comment]
I am still getting nothing from that zim

```
      ServiceWorkerControllerCompat.getInstance()
        .setServiceWorkerClient(object : ServiceWorkerClientCompat() {
          override fun shouldInterceptRequest(request: WebResourceRequest): WebResourceResponse? {
            return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
              zimReaderContainer.load(request.url.toString())
            } else {
              null
            }
          }
        })
```

`shouldInterceptRequest` does not get called

@rgaudin  Is this because your html does not include the `sw.js`? Not aware where this `navigator.serviceWorker` comes from, a language level feature?

**Comment by rgaudin** [comment]
I don't know :/ Do you want me to give you a ZIM with the sw.js code embedded?

**Comment by macgills** [comment]
That might help

**Comment by rgaudin** [comment]
hum, the fact that you get *No SW support* implies `navigator.serviceWorker` is not there so I don't think that would help.

**Comment by macgills** [comment]
where is `navigator.serviceWorker` coming from though? Very JS ignorant

**Comment by rgaudin** [comment]
From the browser, https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

**Comment by macgills** [comment]
Following on from the links [here](https://stackoverflow.com/questions/45773104/webview-with-service-worker-what-are-serviceworkercontroller-and-serviceworkerw) is `if ('serviceWorker' in navigator)` any bit different from `if (!navigator.serviceWorker)`?

**Comment by rgaudin** [comment]
Nah, that's equivalent in this case

**Comment by macgills** [comment]
Not sure how to progress this ticket

>Do we have a working version on the web that can be loaded with an Android browser?

Maybe cycle around to this to see if it works in that scenario? I would think it must? If it doesn't then there may be a larger issue

**Comment by rgaudin** [comment]
OK, preparing you this

**Comment by macgills** [comment]
Thanks a lot.

**Comment by rgaudin** [comment]
https://tmp.kiwix.org/sw/

This is the exact same content as is in the ZIM. Please note that service workers only works through HTTPS or on localhost.

**Comment by rgaudin** [comment]
Just to be clear, in this case, not working means no `navigator.serviceWorker`.

**Comment by macgills** [comment]
`This is a response from a service worker` Yup that is all fine.

I'll try more experiments tomorrow

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/88375822-30743f00-cd94-11ea-8ddb-a6ed60b3b012.png)

The problem is our custom scheme for loading! We prefix URLs with "zim://content/" as a way to uniquely identify zim content from other web content. the above screenshot is when I changed the scheme to "https://"

![image](https://user-images.githubusercontent.com/3358282/88376235-e3449d00-cd94-11ea-898b-053279f15fef.png)
However it isn't a magic bullet.

**Comment by rgaudin** [comment]
OK, well that's already a very useful information. Did you do anything else but the scheme change?

**Comment by macgills** [comment]
I changed the scheme and then set the ServiceWorker... stuff 

```
if (WebViewFeature.isFeatureSupported(WebViewFeature.SERVICE_WORKER_BASIC_USAGE)) {
      ServiceWorkerControllerCompat.getInstance()
        .setServiceWorkerClient(object : ServiceWorkerClientCompat() {
          override fun shouldInterceptRequest(request: WebResourceRequest): WebResourceResponse? {
            Log.e("SERVICE_WORKER", "load")
            return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
              zimReaderContainer.load(request.url.toString())
            } else {
              null
            }
          }
        })
    }
```

Maybe I need a more refined load than how we typically load content?

**Comment by kelson42** [comment]
> Maybe I need a more refined load than how we typically load content?

@macgills So far I'm concerned and for the moment, the custom protocol (scheme) is the proper way, but we believe many of our ports are impacted by https://bugs.chromium.org/p/chromium/issues/detail?id=522370 (at least). Therefore, our guess is that we have a "global" issue. We just try to have a good understanding on each platform before elaborating a global strategy for kiwix/overview#43.

**Comment by ikreymer** [comment]
I think using a custom scheme of `http` or `https` is probably the best solution.. This is how I solved this in electron also.
It's not necessary to run a full server, but just change the scheme to be `http` or `https` instead of `zim` or `kiwix`.
Curious, what was the exact url used in the test, was it `https://<zim file>/path`?

(The AbortController error is good to know as well.. maybe that's not available in this webview and should be fixable)

**Comment by macgills** [comment]
in my test because I wasn't concerned about anything fully functioning I just used `https://content/[internal_zim_path]`

For a robust solution that will work with multiple open zim files it may be necessary to encode the filePath or zimId into the url being loaded but that is just something for me to keep in the back of my mind

**Comment by kelson42** [comment]
@macgills @ikreymer This is probably a silly question but basically doing exactly the same but renaming `zim://` protocol to `http://` just does the job? If "yes" then it looks like a way to workaround the problem (yes this is a bit hacky, but would work), isn't it? If "yes". how would we make the difference between legitimate external HTTP URLs and internal URLs?

**Comment by macgills** [comment]
@kelson42 we would need a unique prefix after the scheme in the url ie `https://this_absolutely_must_be_a_zim/A/Index.html`

which is hard to guarantee once we adopt a scheme like `http`, probably most advisable to have it under an address Kiwix owns and we can reserve?

Then when a person clicks a url we intercept that and just do some string comparisons to figure out if it is external or not

**Comment by macgills** [comment]
`zim:` just seemed like a nice semantic that accurately described "this content is loaded using a different protocol" but it seems like a change must be necessary.

**Comment by kelson42** [comment]
@macgills we own kiwix.app which serves nothing.

**Comment by rgaudin** [comment]
I confirm this works for me. Thanks @macgills !
Requires some small changes inside the ZIM though https://github.com/openzim/warc2zim/issues/45
