### ISSUE TITLE
Added "How to update zim files?" to Kiwix, Wikipedia offline app

### ISSUE THREAD

**Issue by alanajjar** [kiwix/kiwix-android#2223]
Hello,

After reviewing a lot of Arabic comments on [Kiwix Wikipedia offline app,](https://play.google.com/store/apps/details?id=org.kiwix.kiwixmobile) I found that there's huge misunderstanding, that users thinks if they update kiwix app, then ZIM files will be updated! also a lot of others not know how to update zim files, and they rating kiwix app by 1 star due to this point.

So hope please, if you can add "How to update zim files?" to help section on the app.

Thanks on advance

**Comment by ruhci28** [comment]
Hii, @kelson42 can I work on this issue

**Comment by kelson42** [comment]
@ruhci28 Yes.

**Comment by macgills** [comment]
What is our proposed text?

```
How to Update Zim Files 

To update a zim file delete your existing zim and download the latest file
```

I don't see that being very popular.

We would also want to consider the custom apps in this as it is possible for us to deliver them new zim files in an update, which they might expect depending on the size of the update

**Comment by macgills** [comment]
@kelson42 do we have any clarity here?

**Comment by kelson42** [comment]
I propose this:

How to Update a content ?

To update a content (zim file) you need to download the full latest version of this very same content. You can do that via the Kiwix library download manager.

**Comment by kelson42** [comment]
@alanajjar Does that sound good to you or do you have something different in mind.

**Comment by alanajjar** [comment]
Thanks.
Should we add "delete your existing zim"? 

```
How to Update a content ?

To update a content (zim file) you need to "delete your existing zim" then download the full latest version of this very same content. You can do that via the Kiwix library download manager.
```

**Comment by kelson42** [comment]
I don't think we need to delete the older version of the ZIM file, this is just that afterward, we get a kind of duplicate. I believe Kiwix should invite to delette the older version one time the new is downloaded.

**Comment by alanajjar** [comment]
> I don't think we need to delete the older version of the ZIM file, this is just that afterward, we get a kind of duplicate. I believe Kiwix should invite to delette the older version one time the new is downloaded.

Great! so we can use your proposal. And I'll translate it to Arabic as soon as I can.
