### ISSUE TITLE
Cannot install Kiwix APK if it not coming from the Playstore and downloaded with non-Chrome browsers

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2225]
I'm on Huawei P20 Lite / Android 9.0 and downloading [the Kiwix 3.3.4 apk](https://mirror.download.kiwix.org/release/kiwix-android/kiwix-3.3.4.apk) from our repo gives me the following message when I try to open/install it: `For your security, your phone is not allowed to install unknown apps from this source`. 

On both Firefox Focus 8.5.1  and DuckDuckGo 5.59.2 I am then taken to the browser's settings page where I can allow app installs (not just this one but all of them). 

On the plus side, Chrome simply asks `Do you want to install this application? It does not require any special access`

**Comment by macgills** [comment]
I don't think there is anything we can do here, maybe inform users to use chrome?
Or download on their computer and install using adb? That is for power users only.

**Comment by kelson42** [comment]
@macgills I kind of agree with you. IMO we should put a README to download.kiwix.org/release/kiwix-android/. This could be then linked from wherever this is needed.

**Comment by macgills** [comment]
@Popolechien if you allow app installs from your browser does it then work? It is a failure of the feature set of these browsers it sounds like, though there are also OS level protections against installing apps from unknown sources

**Comment by Popolechien** [comment]
Yep it works no problem once I change browser settings.

**Comment by abdulwd** [comment]
Is this good to close?

**Comment by Popolechien** [comment]
@abdulwd yep!

**Comment by kelson42** [comment]
@abdulwd Yes, there is nothing much we can do here. We have a ticket to better check mimetypes here https://github.com/kiwix/maintenance/issues/73.
