### ISSUE TITLE
Full screen icon does not show transparency

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2234]
**Describe the bug**

The full screen button `activity_main_fullscreen_button` sets an alpha value of 0.6. However, the button is not transparent. 
**Expected behavior**

The button should have 60%~ transparency. 

**Steps to reproduce the behavior:**
1. Open full screen mode.
2. See that the full screen icon is either black or white (dark mode), without transparency. 

**Screenshots**

![Screenshot_1595925259](https://user-images.githubusercontent.com/22193232/88640392-30d74780-d0be-11ea-81ff-a00cd44d06ae.png)

**Comment by s-ayush2903** [comment]
I would like to work on this issue

**Comment by Frans-Lukas** [comment]
Great!

**Comment by kelson42** [comment]
@s-ayush2903 @Frans-Lukas Can we close that one?

**Comment by s-ayush2903** [comment]
@kelson42 Can you please enlighten about this milestone stuff. Are the issues/PRs added to the milestone are supposed to be completed before a specific deadline?

**Comment by kelson42** [comment]
@s-ayush2903 Yes this is the idea. But here we have too much stuff in milestone 3.4.

**Comment by s-ayush2903** [comment]
Thanks for the info :)
