### ISSUE TITLE
Move to single activity architecture

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2235]
**Is your feature request related to a problem? Please describe.**

The single activity architecture is officially recommended by google and brings many benefits, such as faster UI transitions, easier shared data and a simplified lifecycle. 

**Describe the solution you'd like**

All activities except for KiwixMainActivity and CustomMainActivity should be converted to fragments and use the navigation component for navigation.

**Comment by kelson42** [comment]
@Frans-Lukas @macgills Do we have created all sub-tickets? Does that make sense to keep that one open?

**Comment by macgills** [comment]
I think there is still 1 activity without a ticket, CustomDownload

**Comment by kelson42** [comment]
@Frans-Lukas @macgills Is that something we have any chance to complete for 3.4 and needs to be done within 3.4?

**Comment by macgills** [comment]
It is not necessary but would make things more cohesive, we are nearly there but understandably it is moving slower now that GSOC is complete.

**Comment by kelson42** [comment]
@macgills Thank you for the feedback. It seems that we will have anyway to postpone the prod rollout of 3.4 anyway of a few weeks. I'm really glad and thankfull that @Frans-Lukas runs this effort to the end. Please consider a plan B if you believe this is going to take more than 2 or 3 additional weeks.

**Comment by macgills** [comment]
I don't forsee this taking 2-3 weeks, the tickets to consider this done are in Review currently and then we can merge the `one-activity` branch

**Comment by Frans-Lukas** [comment]
Agreed!

**Comment by kelson42** [comment]
BRAVO!!!!
