### ISSUE TITLE
Closing and opening the custom app resets book

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2246]
**Describe the bug**

When having opened a set amount of tabs on different pages and restarting the app, the default tab with the default page is the only open tab. That is, the zim file is 'reset'. 

**Expected behavior**

The expected behavior is the same as for the main App, when restarting the app, all tabs, their scroll position and page should be restored. 

**Steps to reproduce the behavior:**
### In custom:
1. Make sure 'don't keep activities' is true.
1. Open a page in a tab.
2. Go to a page in the current tab.
3. Go to the android home screen (minimize Custom)
4. Open custom again. 
5. Notice that only one tab with the home page is open .

**Screenshots**

# Custom:
<img src="https://user-images.githubusercontent.com/22193232/89163915-a9cf1700-d576-11ea-8c85-73aaac63cbd8.gif" alt="drawing" height="400"/>

# Kiwix:
<img src="https://user-images.githubusercontent.com/22193232/89164015-ce2af380-d576-11ea-9225-403bf44e18fb.gif" alt="drawing" height="400"/>

**Comment by NullByte08** [comment]
Hi, this will be my first issue that I am going to tackle in this repository. Can I work on this?

**Comment by Frans-Lukas** [comment]
Hey and welcome @NullByte08 , I think this issue will be solved by the #2295 pull request. 

I can recommend #2292 if you are up for a similar issue. Otherwise, converting java files to Kotlin are always appreciated and good first issues as they don't require much knowledge about the code base. See #1826.

**Comment by NullByte08** [comment]
Ok, thanks. I will check them out.

**Comment by gouri-panda** [comment]
@Frans-Lukas this issue should be closed by #2288
