### ISSUE TITLE
External device mgmt is not robust and gives contradictory information

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2256]
Otherwise how to explain such incoherent screenshot:

![image](https://user-images.githubusercontent.com/1029718/89306365-0f52fe80-d670-11ea-936e-a843dfbb4b7e.png)

Please write this part in a way things are cristal clear.

**Comment by kelson42** [comment]
After reformating the SD card, I have achieve to get again the same situation, here is the diagnostic:
```
--------- beginning of main
08-04 16:26:24.507 16681 16681 D kiwix   : onPause Save current zim file to preferences: null
08-04 16:26:31.587 16681 16681 I kiwix   : Intent data: null
08-04 16:26:33.257 16681 16681 D kiwix   : onPause Save current zim file to preferences: null
08-04 16:38:12.757 16681 18543 E kiwix   : Attempting to create reader with: /storage/5203-DB74/Android/data/org.kiwix.kiwixmobile/files/Kiwix/wikem_en_all_nopic_2020-07.zim
08-04 16:38:31.577 16681 16681 D kiwix   : onPause Save current zim file to preferences: null
08-04 16:39:18.382 16681 16681 I kiwix   : Intent data: null
08-04 16:39:21.687 16681 16681 D kiwix   : onPause Save current zim file to preferences: null
--------- beginning of system
08-04 16:39:21.927 16681 18543 E kiwix   : Attempting to create reader with: /storage/5203-DB74/Android/data/org.kiwix.kiwixmobile/files/Kiwix/wikem_en_all_nopic_2020-07.zim
08-04 16:43:35.442 19346 19346 D kiwix   : Initializing TextToSpeech
08-04 16:43:35.527 19346 19346 D kiwix   : actionnull
08-04 16:43:35.542 19346 19346 D kiwix   : Kiwix normal start, no zimFile loaded last time  -> display home page
08-04 16:43:36.097 19346 19346 D kiwix   : Loaded URL: file:///android_asset/home.html
08-04 16:43:36.097 19346 19346 D kiwix   : Loaded URL: file:///android_asset/home.html
08-04 16:43:36.097 19346 19346 D kiwix   : invalidUrl = false
08-04 16:43:36.457 19346 19346 D kiwix   : TextToSpeech was initialized successfully.
08-04 16:43:37.877 19346 19346 D kiwix   : onPause Save current zim file to preferences: null
08-04 16:43:55.342 19346 19346 D kiwix   : onPause Save current zim file to preferences: null
08-04 16:44:11.362 19346 19346 I kiwix   : Intent data: null
08-04 16:44:16.702 19346 19346 D kiwix   : onPause Save current zim file to preferences: null
08-04 16:44:24.107 19346 19346 I kiwix   : Intent data: null
08-04 16:44:27.882 19346 19346 D kiwix   : onPause Save current zim file to preferences: null
```

**Comment by macgills** [comment]
Logs are not the Diagnostic report, the content of the email is the diagnostic report

**Comment by kelson42** [comment]
@macgills This is what has been saved to the Google Drive from the Kiwix "Diagnostic Report". Do we have another bug here?

**Comment by macgills** [comment]
The diagnostic report is meant to be sent as an email so we attach data only meant for that context, I don't think we can limit the intent to exclusively email clients because we are also attaching a file

**Comment by kelson42** [comment]
@macgills This is another bug, tracked here https://github.com/kiwix/kiwix-android/issues/2258

**Comment by s-ayush2903** [comment]
> After reformating the SD card, I have achieved to get again the same situation, here is the diagnostic:
> 
> ```
> --------- beginning of main
> 08-04 16:26:24.507 16681 16681 D kiwix   : onPause Save current zim file to preferences: null
> 08-04 16:26:31.587 16681 16681 I kiwix   : Intent data: null
> 08-04 16:26:33.257 16681 16681 D kiwix   : onPause Save current zim file to preferences: null
> 08-04 16:38:12.757 16681 18543 E kiwix   : Attempting to create reader with: /storage/5203-DB74/Android/data/org.kiwix.kiwixmobile/files/Kiwix/wikem_en_all_nopic_2020-07.zim
> 08-04 16:38:31.577 16681 16681 D kiwix   : onPause Save current zim file to preferences: null
> 08-04 16:39:18.382 16681 16681 I kiwix   : Intent data: null
> 08-04 16:39:21.687 16681 16681 D kiwix   : onPause Save current zim file to preferences: null
> --------- beginning of system
> 08-04 16:39:21.927 16681 18543 E kiwix   : Attempting to create reader with: /storage/5203-DB74/Android/data/org.kiwix.kiwixmobile/files/Kiwix/wikem_en_all_nopic_2020-07.zim
> 08-04 16:43:35.442 19346 19346 D kiwix   : Initializing TextToSpeech
> 08-04 16:43:35.527 19346 19346 D kiwix   : actionnull
> 08-04 16:43:35.542 19346 19346 D kiwix   : Kiwix normal start, no zimFile loaded last time  -> display home page
> 08-04 16:43:36.097 19346 19346 D kiwix   : Loaded URL: file:///android_asset/home.html
> 08-04 16:43:36.097 19346 19346 D kiwix   : Loaded URL: file:///android_asset/home.html
> 08-04 16:43:36.097 19346 19346 D kiwix   : invalidUrl = false
> 08-04 16:43:36.457 19346 19346 D kiwix   : TextToSpeech was initialized successfully.
> 08-04 16:43:37.877 19346 19346 D kiwix   : onPause Save current zim file to preferences: null
> 08-04 16:43:55.342 19346 19346 D kiwix   : onPause Save current zim file to preferences: null
> 08-04 16:44:11.362 19346 19346 I kiwix   : Intent data: null
> 08-04 16:44:16.702 19346 19346 D kiwix   : onPause Save current zim file to preferences: null
> 08-04 16:44:24.107 19346 19346 I kiwix   : Intent data: null
> 08-04 16:44:27.882 19346 19346 D kiwix   : onPause Save current zim file to preferences: null
> ```

Here what situation are you trying to reach? The one depicted in the screenshot attached in the description? And what contradiction you are finding here, everything looks fine to me. Can you please throw some more light on the issue being faced by you to me, it would be very kind of you. 
Thanks

**Comment by s-ayush2903** [comment]
@kelson42 Can you please the address/consider the trailing comment

**Comment by macgills** [comment]
The internal/external labels should be consistent. We should use the same logic in the PrefsFragment
