### ISSUE TITLE
Fix scrolling toolbar in windowed mode

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#226]
There is a small white bar at the top of the app when it is the window at the bottom of dual app mode and in scrolling toolbar mode.

**Comment by RohanBh** [comment]
@mhutti1 can I work on this?

**Comment by kelson42** [comment]
@mhutti1 Could you tell us if the bug is still there with 3.0 please?

**Comment by mhutti1** [comment]
I think this might be an issue with all apps on my phone. I don't think it is kiwix specific.
