### ISSUE TITLE
Stop supporting Android version < 5.0 (Lollipop)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2260]
These older versions of Android won't be able to read new Zimit ZIM files relying on ServiceWorkers.

On the top of this, these Android OSes are more than 6 years old and require more and more effort to developers to keep them working fine.

My personal experience is that many of these devices are - from a hardware perspective - so limited that this is really difficult to provide a good UX with with recent versions of Kiwix Android.

Google play reports that stopping supporting these older versiona of Android would impact around 4.000 users which would still be able to download Kiwix Android 3.3.4 but not get any updated/newer version of Kiwix Android.

I plan to keep this ticket open to comment for 1-2 weeks to gather feedbacks. Then a decision would be made for future 3.4 version.

**Comment by Popolechien** [comment]
Do we have any way to push an alert or warning on (target) people's screens?

**Comment by abdulwd** [comment]
It would not be easy to push notifications to them as that would require to push another update to them. Moreover, they won't update their devices just because we're showing them a notification. The older devices will still have the older version of Kiwix.
I think we can drop support for them as we won't have many new app installations on older devices.

**Comment by macgills** [comment]
As abdul says it requires us releasing a new version and in that having special code that says something like "On first open of this new version show a News Screen/Notification" and that would inform them that they will no longer receive updates. I don't think it is particularly necessary either.

**Comment by kelson42** [comment]
I would be in favour of implementing this ASAP then. @abdulwd Is that something you would like to do?

**Comment by abdulwd** [comment]
I can do it but as Sean suggested it's not necessary. If we have some concrete reason we can go ahead with it.

**Comment by rgaudin** [comment]
Same, as a user I'd be annoyed to download an update that would just tell me I won't get any new update. Never seen this kind of behavior

**Comment by kelson42** [comment]
@abdulwd All the reasons are given in the ticket. Not talking of makinf a dummy release for old Androids.

**Comment by abdulwd** [comment]
Ohh my bad. 😅 
I'll update the min SDK version to Android Lollipop.

**Comment by kelson42** [comment]
@abdulwd Thx, try to clean anything which can be cleaned. Looks like we have a few places where old stuff are supported which should not be needed anymore.

**Comment by abdulwd** [comment]
Yeah. I'm checking that but the linter is not raising any warning for unnecessary version checks.

**Comment by abdulwd** [comment]
I found that the linter is not being run on the `core` module. Either we can remove `app:` from [here](https://github.com/kiwix/kiwix-android/blob/ba16a5f208e120d7cf1f51b6e9ffc027676c7e67/team-props/git-hooks/pre-commit.sh#L5) or we can add `core:lintDebug` to it.
I think we also need to add
```kotlin
  lintOptions {
    isCheckDependencies = true
  }
```
to [core/build.gradle.kts](https://github.com/kiwix/kiwix-android/blob/develop/core/build.gradle.kts).

I'm not sure of the latter. @macgills Do we have to make any other changes?

**Comment by abdulwd** [comment]
@macgills Should we remove `AppCompatActivity`, `app:srcCompat`, etc too?

**Comment by macgills** [comment]
we are linting core,

```
lintOptions {
    isCheckDependencies = true
  }
```

is in `app` `build.gradle.kts` because app has core as a dependency, not the other way around.

We shouldn't remove AppCompatActivity, that is vital for the support of a lot of the libraries.
`srcCompat` might be nice to get rid of then we can get rid of that warning about vector drawables.
I would change nothing but the minSDK number. And then probably some now obsolete version checks that should cut some code down to be more acceptable, I would expect these to be reported by lint and be automatic quality gates? Maybe it is an inspection though

**Comment by abdulwd** [comment]
There's something wrong with it. You can check the linked PR the pre-commit hook isn't failing when there are any lint errors in the core module.

**Comment by macgills** [comment]
Every translatewiki PR fails lint checks in the core module, can you post a concrete example on the PR?

**Comment by abdulwd** [comment]
@macgills IMO the inspections should fail the pre-commit hook for the examples given by Frans https://github.com/kiwix/kiwix-android/pull/2284#pullrequestreview-468216059.

**Comment by macgills** [comment]
`inspections` != 'lint', I am investigating but I might run out of time today.

It might just be that the files are in kotlin and the lint rule doesn't work fully in kotlin

**Comment by abdulwd** [comment]
Ahh, my bad. I always associate android inspections with lint.
