### ISSUE TITLE
convert VideoEnabledWebChromeClient.java to kotlin class

### ISSUE THREAD

**Issue by bharath2547** [kiwix/kiwix-android#2261]
currently VideoEnabledWebChromeClient class in core/com.cprcrack.videowebview is written in java.
it should be instead in kotlin.
For more info.:
Refer #1826

**Comment by bharath2547** [comment]
i would like to work on this issuse

**Comment by macgills** [comment]
You have been assigned, looking forward to your contribution

**Comment by bharath2547** [comment]
#2275

**Comment by bharath2547** [comment]
#2275

**Comment by bharath2547** [comment]
#2275

**Comment by bharath2547** [comment]
#2275

**Comment by bharath2547** [comment]
#2275

**Comment by bharath2547** [comment]
#2261
