### ISSUE TITLE
Investigate war2c zim issues

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2262]
**Describe the bug**
https://dh-preserve.sfo2.cdn.digitaloceanspaces.com/webarchives/zim/lesfondamentaux.zim is not working with new ServiceWorker code

**Expected behavior**
zim file should load

**Comment by macgills** [comment]
@kelson42 Is there a file that is not 9GB that is not working?

**Comment by kelson42** [comment]
@rgaudin Can you plublish your smaller latest ZIM test file on tmp.kiwix.org please?

**Comment by rgaudin** [comment]
It's an inside-ZIM issue https://github.com/openzim/warc2zim/issues/45
You can test with my working [zim file](http://tmp.kiwix.org/myisago.zim)
