### ISSUE TITLE
Back to top FAB should be above the top bottom toolbar in feature/navigation

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2263]
**Is your feature request related to a problem? Please describe.**

Currently, the back to top fab is displaying on top of (see screenshot) the bottom toolbar, This looks weird. 

**Describe the solution you'd like**

The back to top button should be (16dp?) above the bottom toolbar.

**Describe alternatives you've considered**

Steps to reproduce:
1. Make sure back to top is enabled in settings -> Back to Top toggle
2. Open a book.
3. Scroll down
4. Scroll up so that the bottom reader nav bar is visible. 
5. Notice that the back to top FAB is overlaying the bottom bar. 
![Screenshot_1596718727](https://user-images.githubusercontent.com/22193232/89534753-b8773180-d7f5-11ea-81ac-91c57ac786d1.png)

**Additional context**

This problem only occurs in the feature/navigation branch.

**Comment by s-ayush2903** [comment]
I would like to work on this issue.
