### ISSUE TITLE
Kiwix crashes constantly after downloading (EN) Wikipedia

### ISSUE THREAD

**Issue by 07416** [kiwix/kiwix-android#2264]
**Describe the bug**

Kiwix crashes constantly after downloading the full English Wikipedia.
**Expected behavior**

I should be able to browse the Wikipedia archive.
**Steps to reproduce the behavior:**
N/A

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Oneplus One
- OS version : LineageOS 16 (Android 9)

**Logs**

logcat output for "kiwix": 
[logcat_08-07-2020_10-14-21.txt](https://github.com/kiwix/kiwix-android/files/5039893/logcat_08-07-2020_10-14-21.txt)

**Comment by macgills** [comment]
Can you update your version of kiwix to latest?

**Comment by 07416** [comment]
> Can you update your version of kiwix to latest?

Yes, I'll update to 3.3.2  (it will take some time to back up the 10GB archive as the APK signature is different, sorry).

Why the F-Droid build is from last February?

**Comment by 07416** [comment]
Mind telling where the ZIM files are stored? I appear to be browsing the "short version" of Wikipedia now, but have no crashing issues anymore. The path is in `/storage/emulated/0/Android/data/org.kiwix.kiwixmobile/files/`, but where exactly?

**Comment by macgills** [comment]
Good to hear your issue was resolved. We haven't got any response from F-Droid when we opened a merge Request to update kiwix, it is currently a manual process. There are a couple of barriers for us setting up automatic publishing to fdroid so it is inherently a slower process
