### ISSUE TITLE
Convert CoreSplashActivity to fragment

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2270]
**Is your feature request related to a problem? Please describe.**
#2235 

Edit: CoreSplash should just be deleted and intro activity should be made into a fragment and the splash code should be moved to CoreMain. #2272 will complete this.

**Comment by NullByte08** [comment]
Hi, Can I work on this?

**Comment by Frans-Lukas** [comment]
Fixed by #2273.
