### ISSUE TITLE
Convert IntroActivity to fragment

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2272]
**Is your feature request related to a problem? Please describe.**
#2235

**Comment by prayutsu** [comment]
I would like to work on this issue.

**Comment by Frans-Lukas** [comment]
@prayutsu sorry, this ticket is already work in progress. Try looking for issues with "good first issue" tags, or converting classes to kotlin from Java if you are unsure of where to start.

**Comment by prayutsu** [comment]
okay, thanks!
