### ISSUE TITLE
Is the offline Wikipedia complete?

### ISSUE THREAD

**Issue by 07416** [kiwix/kiwix-android#2274]
I've now downloaded the full 10.2GB Wikipedia archive (2020-07-03) on my device, but it appears that only the article opening paragraphs can be viewed. Is this a bug on my side or the intended scope of the project? If the latter, I request updating the "book" description.

**Comment by 07416** [comment]
>A New Full English Wikipedia Dump is on Kiwix (June 2020) 88.54GB - https://www.reddit.com/r/DataHoarder/comments/hn9l3f/a_new_full_english_wikipedia_dump_is_on_kiwix/

Doesn't seem so — I wonder if the data can be compressed any further.

**Comment by kelson42** [comment]
This is normal, you have downloaded the mini version (first paragraph only), should be visible in the tags. You probably want the maxi flavour.
