### ISSUE TITLE
Convert localfiletransfer activity to fragment

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2280]
**Is your feature request related to a problem? Please describe.**

#2235

**Comment by kelson42** [comment]
@Frans-Lukas @macgills This PR is old, a blocker for 3.4, not reviewed. What is the status? Why this is not moving on?

**Comment by Frans-Lukas** [comment]
I was waiting for #2249, and see that it is completed now. I'll probably have to redo most of the ticket and I'll try to take a look this weekend. If I do, it should be review-ready by Monday.
