### ISSUE TITLE
Samsung exfat driver "sdfat" forbids to write big files

### ISSUE THREAD

**Issue by heimo0** [kiwix/kiwix-android#2282]
Samsung S8 mit And. V.9.xx
Zim files größer als 4.xx GB sind ausgegraut und daher nicht downloadbar.
Es ist aber ausreichend Platz auf der Speicherkarte vorhanden.

**Comment by kelson42** [comment]
@heimo0 Thank you for your bug report. Unfortunately, This is impossible to handle many different problems within one ticket. please split this ticket so we have one simple problem at a time?

**Comment by heimo0** [comment]
hallo ..

 

this are not different Problems.

 

IT IS ONLY one and the same problem, which I tested on 2 smartphones......

 

yours.

 

 

------------------------------------------------------------------
Hermann Moseler            Tel.:   089-44848-40-0
München                           Fax:   089-44848-48 

Von: Kelson [mailto:notifications@github.com] 
Gesendet: Donnerstag, 13. August 2020 18:56
An: kiwix/kiwix-android
Cc: heimo0; Mention
Betreff: Re: [kiwix/kiwix-android] wie kann ich die deutsche Wiki mit 37 GB auf S8 downladen. (#2282)

 

@heimo0 <https://github.com/heimo0>  Thank you for your bug report. Unfortunately, This is impossible to handle many different problems within one ticket. please split this ticket so we have one simple problem at a time?

**Comment by kelson42** [comment]
@heimo0 I have kept only one problem by modifyingthe ticket.

**Comment by kelson42** [comment]
@heimo0 This is greyed because the online content will not be writeable on your external SD card. This is not because the free space is not sufficient. This is because the filesystem does not support files bigger than 4GB. Typically the case with fat32. Use exfat instead and you will be able to download big files.

**Comment by heimo0** [comment]
hallo  ....

 

EXT. SD Card is formated with EXFAT32.

 

I can copy the 37 GByte file 

wikipedia_de_all_maxi_2020-07.zim

 

from PC in the files Directory of Kiwix.

 

BUT the Reader will not recognice any file copied from PC, but only the downloaded direct inside the READER.

 

What to do....

Until Dez.2019 this works fine, but other the Jan.2020 update never again...

 

yours

 

 

 

------------------------------------------------------------------
Hermann Moseler            Tel.:   089-44848-40-0



Von: Kelson [mailto:notifications@github.com] 
Gesendet: Donnerstag, 13. August 2020 19:20
An: kiwix/kiwix-android
Cc: heimo0; Mention
Betreff: Re: [kiwix/kiwix-android] Big zim files are greyed (#2282)

 

@heimo0 <https://github.com/heimo0>  This is greyed because the online content will not be writeable on your external SD card. This is not because the free space is not sufficient. This is because the filesystem does not support files bigger than 4GB. Typically the case with fat32. Use exfat instead and you will be able to download big files.

**Comment by kelson42** [comment]
@heimo0 Whould you be able plase to send the diagnose report per email?
@macgills would you be able please to check the diagnose report so we unterstand why his sd card is not detected as exfat?

**Comment by heimo0** [comment]
hallo  ...

 

             <https://github.com/heimo0> @heimo0 Whould you be able plase to send the diagnose report per email?

 

I did it already today and someone confirmed to receive it...

 

But, if you tell me how. I repeat it as often as necessary...

 

-------------------

 

 

                        would you be able please to check the diagnose report so we unterstand why his sd card is not detected as exfat?

 

 

of course....

if you tell me how. I repeat it as often as necessary...

 

yours..

 

 

------------------------------------------------------------------
Hermann Moseler            Tel.:   089-44848-40-0
München                           Fax:   089-44848-48 

Von: Kelson [mailto:notifications@github.com] 
Gesendet: Donnerstag, 13. August 2020 20:52
An: kiwix/kiwix-android
Cc: heimo0; Mention
Betreff: Re: [kiwix/kiwix-android] Big zim files are greyed (#2282)

 

@heimo0 <https://github.com/heimo0>  Whould you be able plase to send the diagnose report per email?
@macgills <https://github.com/macgills>  would you be able please to check the diagnose report so we unterstand why his sd card is not detected as exfat?

**Comment by heimo0** [comment]
is it possible to continue a broken Download, instead to restart it always new....
So 37 GByte will never end to be downloaded....

**Comment by macgills** [comment]
`MountInfo(device=/dev/block/vold/public:179,1, mountPoint=/mnt/media_rw/5399-48E9, fileSystem=sdfat)`

Your SD card is reporting it is `sdfat` which I had interpreted as "does not support 4GB files" which I believe to be the correct interpretation

`private val DOES_NOT_SUPPORT_4GB_FILE_SYSTEMS = listOf("fat32", "vfat", "sdfat")`

If you can try formatting the card again as exfat? Otherwise we could do an update to remove `sdfat` as a blacklisted filesystem and instead let it do the file writing fallback check

**Comment by kelson42** [comment]
If I trust this article https://www.phoronix.com/scan.php?page=news_item&px=exFAT-sdFAT-Alt-Driver "sdfat" is the name od the traditional Samsung implementation of exfat driver (until recently strong MS property). Therefore, Sdfat should perfectly support big files and should not I believe be part of the black list. What was the reason to put it in?

**Comment by kelson42** [comment]
@macgills Might be that this is simple impossible to know from this is we have fat32 or exfat, see https://github.com/greiman/SdFat-beta

**Comment by kelson42** [comment]
@macgills This confirs my guess https://android.stackexchange.com/questions/209347/how-do-i-find-what-type-of-file-system-is-of-an-attached-usb-or-sd-card. It is impossible to knowwith fa driver sdfat from Samsung ifthe fs behind is fat16, fat32 or exfat... and therefore able to handle big files... or not.

**Comment by macgills** [comment]
So I will remove sdfat from the blacklist, it will fallback to writing the file

**Comment by kelson42** [comment]
@macgills What will happen if we have the sdfat/fat32 combination?

**Comment by macgills** [comment]
It will fail to write the file, get marked as "unable to write 4gb files"

**Comment by kelson42** [comment]
@macgills Great. Sorry to bother you a bit wit this but I ned a small refreshment about how it works:
* when will that fail? It will download 4gb and the fail?
* or do we have a test (we had this in the past)?
* remember me where the file marker will be put if it fails? In the same directory where we download the ZIM files?

**Comment by macgills** [comment]
We check the file system on launch of the library.
First we read the mount information to determine the file system.
If that returns Inconclusive we attempt to write a 4GB file.
If it succeeds we return a "Can Support 4GB"
If it fails we return a "Cannot Write 4GB"
After either outcome we delete the 4gb file.
There is no file marker, I believe there is a ticket for that.

**Comment by kelson42** [comment]
@macgills Thx, yes I believe we should move one with https://github.com/kiwix/kiwix-android/issues/1664.

**Comment by kelson42** [comment]
@heimo0 So, it looks like your problem will be sorted out soon. A fix should be part of next beta to be published next week. I’m glad you made this bug report. Please open new tickets for your other problems, and keep in mind: one bug at a time.

**Comment by heimo0** [comment]
Kiwix now recognizes the last new downloaded ZIM files, but app starts about 10 to 15 minutes....
I discovered it by chance...


Am 14. August 2020 13:47:26 MESZ schrieb Kelson <notifications@github.com>:
>@heimo0 So, it looks like your problem will be sorted out soon. A fix
>should be part of next beta to be published next week. I’m glad you
>made this bug report. Please open new tickets for your other problems,
>and keep in mind: one bug at a time.>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/kiwix/kiwix-android/issues/2282#issuecomment-674036132

Gruß

Hermann Moseler

**Comment by heimo0** [comment]
Thanks now it works again, like last year.
Yours


Am 14. August 2020 13:47:26 MESZ schrieb Kelson <notifications@github.com>:
>@heimo0 So, it looks like your problem will be sorted out soon. A fix
>should be part of next beta to be published next week. I’m glad you
>made this bug report. Please open new tickets for your other problems,
>and keep in mind: one bug at a time.>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/kiwix/kiwix-android/issues/2282#issuecomment-674036132

Gruß

Hermann Moseler
