### ISSUE TITLE
CustomApp Crashes on launch (when dev is merged with feature/nav)

### ISSUE THREAD

**Issue by s-ayush2903** [kiwix/kiwix-android#2285]
The described issue is observed when `develop` is merged with the changes proposed from `feature/navigation`
_CustomApp_
The custom app seems to be jammed completely.
* It crashes on its first install(please reinstall the app after the uninstallation as previous settings may not lead it to crash) with a border of red lines over the screen showing that there was an attempt made to launch the app and it disappears after the crash occurs leaving user with the permission request for Media access.
* After this when app is next launched(not on reinstallation) it says: (umm..., let me attach the exact visuals) [Here they are :link: ](https://drive.google.com/file/d/18aXlGGoN76Ox2EsJWbT9B-pBnkWobVDf/view?usp=sharing)
* Repeating the process causes no changes but crashes

**Comment by Frans-Lukas** [comment]
I merged develop to feature/nav which seems to have created a conflict... Otherwise it looks good!

**Comment by s-ayush2903** [comment]
Okay fine, thanks for the update, I'll be looking into it soon
