### ISSUE TITLE
Change operating systems navigation bar to use kiwix themes color instead of system default. 

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2287]
# Additional context
**This is a great first issue as it is very straight forward, so I'd like it if someone who has never contributed to Kiwix implemented this.** 

<br/>
<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**

Currently the bottom navigation bar of the android OS uses the operating systems default color. This can look odd when using our application. I suggest we override the bottom navigation bar color to black, for a more unified interface.

**Describe the solution you'd like**
Change the operating systems navigation bar color.
![Capture](https://user-images.githubusercontent.com/22193232/90372418-ae182b80-e070-11ea-88d7-6487b3e2bda7.PNG)

**Comment by Frans-Lukas** [comment]
@prayutsu ?

**Comment by prayutsu** [comment]
I would like to work on it

**Comment by Frans-Lukas** [comment]
Great! Assigning you.

**Comment by prayutsu** [comment]
Thank you!

**Comment by prayutsu** [comment]
@Frans-Lukas Do I need to create a new branch for this?

**Comment by Frans-Lukas** [comment]
Yes! See the naming convention in [CONTRIBUTING.md](https://github.com/kiwix/kiwix-android/blob/develop/CONTRIBUTING.md) and commit style in [COMMITSTYLE.md](https://github.com/kiwix/kiwix-android/blob/develop/docs/commitstyle.md). Basically branches should be named feature/<username>/<issuenumber>-<issue-name> and commits should follow #<issue-number> <commit-message>.

**Comment by macgills** [comment]
@kelson42 I will move the discussion of the validity of this ticket off of the PR and to here.

It is pretty common to match thesystem UI to the colors of your app, status bars and navigation bars. Otherwise you can have jarring color clashes. I think this ticket is quite valid
