### ISSUE TITLE
Restoring multiple tabs does not work in feature/navigation custom.

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2288]
**Describe the bug**

When restarting the custom app, only the most recently opened tab is restored.

**Expected behavior**

All tabs with their y-scroll positions should be restored on app restart. 

**Steps to reproduce the behavior:**
1. Open multiple tabs.
2. Restart the custom app.
3. See that only one tab is restored.

**Comment by s-ayush2903** [comment]
@Frans-Lukas I feel that there needs to be focus to be put on _CustomApp_ as well, last night when it automatically downloaded the zim file, it did open and i read it for a while but when i exit the app and launched it again, it crashed! and the crashes were persisting and repetitive. So i've been trying to reproduce it and fix it eventually. But unfortunately, there are frequent power cuts happening here. I'll be working on it!

**Comment by Frans-Lukas** [comment]
Hmm, that's worrying. Good that you are working on finding the cause.
