### ISSUE TITLE
ZimHostFragment/Activity is not requesting ACCESS_COARSE_LOCATION on Android 10

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2292]
**Describe the bug**

ZimHostFragment/Activity requires the coarse location permission to access wifi information. This permission is never requested on zim host starting. 

**Expected behavior**

I think the permission should be requested if the user is connected to wifi (`wifiManager.isWifiEnabled`) and the user clicks the "Start Server" button in `ZimHost*`. Similarly to how the permission is requested if the user searches for devices in the LocalFileTransferActivity.  

**Steps to reproduce the behavior:**
1. Make sure the location permission for Kiwix is denied.
2. Open `ZimHost`. 
3. Make sure you are connected to wifi.
4. Click "Start Server".
5. Notice that a dialog opens requesting the user to enable wifi, or hotspot instead of requesting permissions.

**Screenshots**

![image](https://user-images.githubusercontent.com/22193232/90498576-cbb8c400-e148-11ea-98a1-5a095925967d.png)
![image (1)](https://user-images.githubusercontent.com/22193232/90498579-cc515a80-e148-11ea-99f1-01f159508516.png)
![118095866_329523881511613_7800025852129703092_n](https://user-images.githubusercontent.com/22193232/90498602-d2dfd200-e148-11ea-852c-bff3d42abab7.jpg)

**Comment by macgills** [comment]
As a note: I cannot replicate this issue. Issue discovered on the zimHost to fragment ticket. Currently on `oneActivity` branch.

@Frans-Lukas can you verify this behaviour on develop, when you have the time

**Comment by Frans-Lukas** [comment]
Same issue on `develop`-branch.

**Comment by macgills** [comment]
Excellent issue identified

**Comment by NullByte08** [comment]
@Frans-Lukas Hi, Can I work on this?

**Comment by Frans-Lukas** [comment]
Yes! Assigning you.

**Comment by gouri-panda** [comment]
@macgills Should I add 3.4 milestones here?

**Comment by gouri-panda** [comment]
It seems @NullByte08 is offline for this project for a while.so I am taking this issue.
