### ISSUE TITLE
Can we do supertargeted popups?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2294]
It appears that we've had three downloads this year from Antarctica-based devices: could it be possible to embed a functionality that would test a user's IP address, and if it matches a given region (e.g. Antarctica), pop up a "please contact us" window (similar to the "please rate us" we already have)?

I'm not asking we do it, but only if that would be possible and how big of an effort that would be?

**Comment by macgills** [comment]
There are webservices that allow a lookup based on IP if we wanted to avoid using location APIs. I think they have rate limits per day so we would probably only want to do it infrequently?  I'd need to investigate these services more

A more robust solution would be push notifications which would be a much larger integration but leave us in a place where we could target more specifically. I think it would destroy Fdroid publishing as that isn't open source

**Comment by kelson42** [comment]
Regarding, I’m pretty against implementing this feature request because:
* The ratio between work and impact is hight
* The ratio between how many users wiuld be impacted by the test and the few for which is woukd be really usable
* Create a string dependence to an online service
