### ISSUE TITLE
Upgrade to Kotlin 1.4.0

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2299]
**Is your feature request related to a problem? Please describe.**
A new version of kotlin has been released with new language features, improved speed and a new type inference engine.

**Describe the solution you'd like**
An upgrade to kotlin 1.4.0 with a migration run to fix any potential issues

**Additional context**
We may also want to move to AS/AGP 4.1 which currently has a RC in the beta channel, the speed boosts to auto complete are only present on 4.1 or later

**Comment by kelson42** [comment]
@macgills I’m not sure about how much work is needed, but would be indeed good to do.

**Comment by macgills** [comment]
not very much work I would think

**Comment by macgills** [comment]
We have a separate ticket to upgrade AGP so I am hijacking this ticket to bump our libraries
