### ISSUE TITLE
Missing wrap in library

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2300]
Version 3.3.4 build 6230304

Picture speaks for a thousand words so here we go
![Screenshot_20200819_172613_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/90655142-7c09f380-e241-11ea-9693-b23ee2271299.jpg)

**Comment by macgills** [comment]
kind of finicky this aside from the title of books which is an easy fix.
I guess we can set a maximum width on the filename eg "computer maxi" and elipsizing it when it is too long?

A multiline author will break the symmetry so perhaps elipsize that too?

**Comment by kelson42** [comment]
None of the entries here should be multiline.... but the descriptions can be a full sentence.

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/90766075-e32bb480-e2e2-11ea-8519-df7e7bc901ee.png)
for reference

The author "Youtube Channel KhanAcademy Francophone" is too long and we have to deal with that. is it multiline or is it ellipses?

similarly the File Name is longer than the entire list item

**Comment by macgills** [comment]
@kelson42 have you reached a decision on how long text in these fields should render?

**Comment by kelson42** [comment]
@macgills We should fade out/ellipsis if too long. Ultimatively, we need a view to be able to show ZIM details properly.

**Comment by macgills** [comment]
okay, I will be changing the text pairs below description to divide the space between them and elipsize.

There is that ticket for showing a zims detail view  where all this information would be legible

**Comment by macgills** [comment]
still surprisingly irritating to implement. Can we kill the bottom line ie Publisher/File Name? I am not sure these are too relevant  what with Publisher being Kiwix most of the time and the file name being pretty much the title again

**Comment by macgills** [comment]
@kelson42 do you have any input on this?

**Comment by macgills** [comment]
@kelson42 I will proceed with removing the bottom line of Publisher/FileName, if you have no objection

**Comment by kelson42** [comment]
@macgills Sorry for my lack of feedback here, this went without triggering my attention. Good you just went forward!
