### ISSUE TITLE
Broken rate dialog in 3.4

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2301]
![Screenshot_20200820-102032](https://user-images.githubusercontent.com/1029718/90740464-385dcb00-e2cf-11ea-99c4-92760073aa8c.png)

**Comment by Frans-Lukas** [comment]
Stems from `AlertDialogShower.kt`:
```
dialog.message?.let { setMessage(activity.getString(it, *bodyArguments(dialog))) }

private fun bodyArguments(dialog: KiwixDialog) =
    if (dialog is HasBodyFormatArgs) dialog.args.toTypedArray()
    else emptyArray()
```
But don't know why? One fix is to concatenate the strings beforehand, and creating a constructor that uses a string instead of int for the message, but that feels like it doesn't fix the real issue. @macgills ?

**Comment by macgills** [comment]
The Dialog is just wrong, it shouldn't pass ints as the args, the body template accepts strings

**Comment by Frans-Lukas** [comment]
Ah, like this 

```
if (dialog is HasBodyFormatArgs) dialog.args.map { activity.getString(it as Int) }
      .toTypedArray()
```
?

**Comment by macgills** [comment]
Not there, that code is fine, a string template can and should accept numbers sometimes

```
 data class ShowRate(override val args: List<Any>, val customIcon: Int?) : KiwixDialog(
    R.string.rate_dialog_title,
    R.string.triple_arg_format_string,
    R.string.rate_dialog_positive,
    R.string.no_thanks,
    icon = customIcon,
    neutralMessage = R.string.rate_dialog_neutral
  ),
    HasBodyFormatArgs {
    constructor(icon: Int?) : this(
      listOf(R.string.rate_dialog_msg_1, R.string.app_name, R.string.rate_dialog_msg_2),
      icon
    )
  }
```
this listOf should have getString called

**Comment by Frans-Lukas** [comment]
Activity/context is not reachable from KiwixDialog.kt

**Comment by macgills** [comment]
maybe just passed in as strings but they are intrinsic to this dialog so maybe just pass in the activity to the secondary constructor

**Comment by macgills** [comment]
Context is reachable everywhere via CoreApp but you should always use the closest context because it might have had something applied to it

**Comment by Frans-Lukas** [comment]
while we are at it, should the visitcounter increase on any top level destination (on KiwixMainActivity start). Because currently the dialog is only opened in the reader destination.

**Comment by macgills** [comment]
Start of activity makes sense, I believe it tries to track "app opens", it is a bit messy that logic
