### ISSUE TITLE
Newly opened pages starts slightly scrolled. 

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2304]
**Describe the bug**

When entering any page of any book, the page is scrolled down by (about) the height of the toolbar. 

**Expected behavior**

When opening a new page, its scroll position should be zero. 

**Steps to reproduce the behavior:**
1. Open any book and any new page. 
2. Notice that the scroll position is not zero. 

**Screenshots**

![Screenshot_1597912717](https://user-images.githubusercontent.com/22193232/90747845-b4f1a900-e2d1-11ea-9d0b-99052ccd0e8b.png)

**Comment by macgills** [comment]
I think this is a custom apps bug, is it not resolved by the tab restoration?

**Comment by Frans-Lukas** [comment]
No, it's in both `app` and `custom` and is the same for all files and pages.

**Comment by kelson42** [comment]
@Frans-Lukas If you could fix it that would be great considering that we are in a race to finish on time the 3.4 milestone.

**Comment by Frans-Lukas** [comment]
Will do!
