### ISSUE TITLE
Convert DocumentParser to kotlin

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2307]
**Is your feature request related to a problem? Please describe.**

DocumentParser is in Java

**Describe the solution you'd like**

Convert it in Kotlin

**Additional context**

Parent issue #1826

**Comment by macgills** [comment]
Hmmm I think someone else was going to do this

**Comment by macgills** [comment]
@bharath2547 do you want to do this conversion or are you happy for @gouri-panda to take it?

**Comment by bharath2547** [comment]
@macgills  i will take this.

**Comment by bharath2547** [comment]
@macgills  i am working on it
