### ISSUE TITLE
On re-opening of history/bookmarks after having opened a page from either of them, the back button requires a double click to work.

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2308]
**Describe the bug**

The first click does nothing, and the second click works as expected. 

**Expected behavior**

The back button should always work on the first click.

**Steps to reproduce the behavior:**
1. Open history.
2. Select a page.
3. Re-open history.
4. Click back and notice that nothing happens.
5. Click back again, and see that it works as expected. 

**Screenshots**
This is what happens after step 2 from above, the first click is subtle: 

![untitled](https://user-images.githubusercontent.com/22193232/90752395-9e4e5080-e2d7-11ea-8d25-792646eba2aa.gif)

**Comment by macgills** [comment]
@Frans-Lukas I can't repro this, could you give it a shot to make sure I amn't being a dunce

**Comment by Frans-Lukas** [comment]
Oh, forgot about this one! Will check.

**Comment by Frans-Lukas** [comment]
1. Open History.
2. Click an item.
3. Open history again.
4. Press the back icon in the action bar.
5. Notice that you have to press back again (in the top action bar).

Fixed by popping the backstack in the `OpenPage` SideEffect.
