### ISSUE TITLE
Convert SearchActivity to fragment

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2319]
**Is your feature request related to a problem? Please describe.**

#2235

**Comment by kelson42** [comment]
@Frans-Lukas @macgills This PR is old, a blocker for 3.4, not reviewed. What is the status? Why this is not moving on?

**Comment by Frans-Lukas** [comment]
There were some questions regarding navigation results with the nav component. I'll fix the instrumentation tests today (probably) and then we can take another look at the nav results, if necessary.
