### ISSUE TITLE
Only need to run lint before push.

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2327]
Now lint is running every commit. It will be much easier to run lint if it runs only before the push.

**Comment by macgills** [comment]
@Frans-Lukas commits are not necessarily on the repo though. I can't speak to others style of writing but I would nearly always commit and push at the same time so logistically this makes zero difference to me.

If a person has a bunch of local commits, tries to push and then it fails they can happily rebase and rework their local history before making it the history of the repo.

@gouri-panda it might help if you tell us about your workflow.

**Comment by gouri-panda** [comment]
When I work on an issue. I generally commit small meaningful changes, after the issue is solved i push to my repo.

**Comment by macgills** [comment]
I am happy for this ticket to be accepted, it will have to delete the commit hook as part of the install task. The install task is located in `git-hooks.gradle`, This isn't a priority for me right now so I won't get to it for a while but happy for someone else to pick it up

**Comment by gouri-panda** [comment]
@macgills This issue will be resolved after #2360. Should we close this issue?

**Comment by macgills** [comment]
This changes the behaviour, the documentation does not make this irrelevant

**Comment by kelson42** [comment]
@gouri-panda After 3 years, I finnaly fully read this issue and the comments. I fully agree with @Frans-Lukas. The multiples commits of a PR are not try an errors, they are a way to split an enhancement in multiple logicial small parts. Each part should be linted for quality reasons.

**Comment by gouri-panda** [comment]
@kelson42 Yup! Couldn’t agree more. At that time I didn't know the value of each commits with lint checks. It's a trade-off between time & efficiency. But in a long run, we can see significant benefits from it!
