### ISSUE TITLE
FileReader injected in other classes rather calling normally.

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2331]

**Comment by macgills** [comment]
It has 1 usage, I would be more in favour of this being an extension function on context `readAssetAsText` or somesuch. Downside is that is is used in java so usage will just look like a conventional static method

**Comment by tdopires** [comment]
I would like to work on this... Which direction should I go? 

The extension function idea from @macgills seems nice, we could add `@file:JvmName("FileReader")` to the file, so it's not weird to use it with the `Kt` suffix in Java code...

**Comment by tdopires** [comment]
I've opened a PR for this. 
If the extension function idea doesn't suit the codestyle of the project, just let me know.

**Comment by gouri-panda** [comment]
I'm taking this up since @tdopires isn't available.

**Comment by gouri-panda** [comment]
@macgills I am waiting for #2460 to complete. It will be easier to finish. Is that ok?

**Comment by macgills** [comment]
works for me

**Comment by kelson42** [comment]
@gouri-panda Do you plan to work on this issue?

**Comment by gouri-panda** [comment]
@kelson42  sure! Due to some health problems I wasn't able to do this.

**Comment by kelson42** [comment]
@gouri-panda Hope you are doing better now. Just let us know if you plan to leave it.

**Comment by gouri-panda** [comment]
No worries, I will finish this infact I'm already started working on this ;).
