### ISSUE TITLE
The progressbar in the reader fragments is not being hidden on hideTabSwitcher (in dark mode). 

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2333]
**Describe the bug**

After closing the tab switcher, the progress bar remains visible after finishing loading. 

**Expected behavior**

The progress bar should be hidden after loading is finished. 

**Steps to reproduce the behavior:**
1. Make sure dark mode is enabled.
2. Open reader fragment.
3. Open tab switcher.
4. Close tab switcher by selecting or creating a tab. 
5. Notice that the progress bar remains visible.

**Screenshots**

![Screenshot_1598360763](https://user-images.githubusercontent.com/22193232/91177769-80705980-e6e4-11ea-8686-87927011e62b.png)

**Comment by gouri-panda** [comment]
Can i take this issue?
