### ISSUE TITLE
Convert CustomDownload to fragment 

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2335]
**Is your feature request related to a problem? Please describe.**

#2235

**Comment by Frans-Lukas** [comment]
@s-ayush2903

**Comment by s-ayush2903** [comment]
I would love to work on this as soon as my currently open PR(#2328) gets perfect. Or if time permits, I'll comment it here before the perfection of the aforementioned PR!

**Comment by kelson42** [comment]
@s-ayush2903 Please go ahead

**Comment by kelson42** [comment]
@s-ayush2903 What is the status here?

**Comment by s-ayush2903** [comment]
Ah, I was planning to restore the deleted branch in order to reopen the closed PR
