### ISSUE TITLE
Merge LibraryFragment with OnlineLibraryFragment

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2339]
**Is your feature request related to a problem? Please describe.**

`LibraryFragment` is only inherited by one class: `OnlineLibraryFragment`. By merging these two classes we reduce duplicated code and number of files.

**Comment by Masked-Carrot** [comment]
Hello, 
Can I work on this issue?

**Comment by Frans-Lukas** [comment]
That would be great. Assigning you.

**Comment by s-ayush2903** [comment]
As the corresponding PullRequest is closed, may i take it up?
