### ISSUE TITLE
Fix memory leaks in feature/one-activity

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2341]
**Describe the bug**

Fragments require more care for memory leaks (as their references remain longer?). Because all activities have been converted to fragments, many more memory leaks are present.

**Comment by Frans-Lukas** [comment]
Two leaks found this far,

ZimHostFragment:
1. Open "Host Book" from navigation drawer.
2. Minimize kiwix.
`HotSpotService.zimHostCallbacks` causes leak.


PrefsFragment: 
1. Open "Settings" from navigation drawer.
2. Minimize kiwix.
`KiwixPrefsFragment.mContainer` causes leak.

**Comment by kelson42** [comment]
@Frans-Lukas What is the status of this issue? Does the referenced commot has fixed the issues?

**Comment by Frans-Lukas** [comment]
@kelson42 waiting for all fragments to be merged with one-activity.

**Comment by Frans-Lukas** [comment]
We can merge the current fixes now, or wait for more leaks to be fixed in unmerged fragments.

**Comment by kelson42** [comment]
@Frans-Lukas So fixed but not merged? Or probably fixed but needs confirmation?

**Comment by Frans-Lukas** [comment]
Fixed but not merged (the commented leaks).

**Comment by Frans-Lukas** [comment]
I can make a draft pull request as well.

**Comment by Frans-Lukas** [comment]
@kelson42 The leaks are mostly very easy to find and fix as well. So as soon as we have all the fragments merged I'll be able to fix the introduced leaks in a day or two.
