### ISSUE TITLE
Response to range request is a 200, but should be 206 and include content-range header.

### ISSUE THREAD

**Issue by ikreymer** [kiwix/kiwix-android#2347]
**Describe the bug**

It appears that Range requests with (`Range: bytes=start-end`) are handled - the content-length is off the range, not the entire file, but the response is a 200, not a `206 Partial Content`. 
The `Content-Range` header also appears to be missing.

This issue was discovered in testing warc2zim, reported here: https://github.com/openzim/warc2zim/issues/55#issuecomment-683372056

**Expected behavior**

The response to range requests should be a `206 Partial Content` when a range is handled correctly.
Otherwise, the requester does not know if ranges are supported or not.

This came up with the new service-worker based replay in warc2zim, where the service worker is expecting a 206 response 
when playing videos.

**Steps to reproduce the behavior:**
Make a range request to `https://kiwix.app` with range header set.

**Screenshots**
<img width="834" alt="Screen Shot 2020-08-29 at 8 25 31 PM" src="https://user-images.githubusercontent.com/1015759/91650804-1e438b80-ea39-11ea-9cf5-119bd9410035.png">

**Environment**
- Version of Kiwix Android : 3.4.0
- Device : Galaxy S9 in Genymotion Emulator
- OS version : 8.0

**Logs**

**Comment by kelson42** [comment]
@ikreymer I’m not the developer, but I don’t understand what are the reproduction steps.

**Comment by macgills** [comment]
@ikreymer can you give me some more info on the precise header sent and what a response should look like?

Right now the loading is quite simplistic

```
          override fun shouldInterceptRequest(request: WebResourceRequest): WebResourceResponse? =
            zimReaderContainer.load(request.url.toString())
        })
```

I can modify our response to include headers but it feels kind of wrong to me? Recreating a full web server inside the application sounds like too much complexity and this ticket opens that rabbit hole.

Are Range request something we can avoid? 

Otherwise this 1 case should be relatively easy to add, assuming that range requests are limited to specific types of content

**Comment by rgaudin** [comment]
Until @ikreymer responds, here are my thoughs:

* don't think we can avoid such requests
* those can be easily spotted from the `request.getRequestHeaders()` as it contains a `Range` header.
* we could “just” set status_code to `206` in case of such request (maybe not if the range is larger than the content – then it's not partial ?)

**Comment by ikreymer** [comment]
Yes, these requests are necessary for playing video. It may be sufficient to just set the response to a 206 status if `Range` header is set, or at least to test. It seemed like the range was already being handled somewhere, but maybe not (can't find where it would be doing that).

Looks like this is the part in the test suite for libkiwix and how it handles ranges, ideally the support here would be comparable:
https://github.com/kiwix/kiwix-lib/blob/5f8c0998291d0778887373355bb6b1c5a345ed2c/test/server.cpp#L431

**Comment by kelson42** [comment]
The libkiwix handles range requests on an item, but this has nothing to do with HTTP. This handling is done at the Kiwix for Android level which plays the role of interfacing the libkiwix with HtmlRenderer widget.

**Comment by macgills** [comment]
Can I get a link to a zim file to test against?

**Comment by rgaudin** [comment]
https://dh-preserve.sfo2.cdn.digitaloceanspaces.com/webarchives/zim/lesfondamentaux.zim

Do you need a smaller one and can you deal with this one?

**Comment by ikreymer** [comment]
> Can I get a link to a zim file to test against?

Here's a smaller .zim I created for testing:
[Uploading test_2020-08.zim…]()  (rename to .zim)
Click on the middle video here to load a page with the video
<img width="1110" alt="Screen Shot 2020-09-11 at 8 45 39 AM" src="https://user-images.githubusercontent.com/1015759/92946310-55d40f80-f40b-11ea-943d-21456bf8a236.png">


> The libkiwix handles range requests on an item, but this has nothing to do with HTTP. This handling is done at the Kiwix for Android level which plays the role of interfacing the libkiwix with HtmlRenderer widget.

Yes, My point was that this works exactly the same way, as far as browser is concerned, it is just a version of Chrome making http requests (which are handled in a special way by the server). Range request support is needed for the same reasons that its needed in kiwix-serve.

**Comment by rgaudin** [comment]
I think @kelson42 was referring to the fact that libkiwix does two things:

- it handles range requests for data access. This is working already on our youtube ZIMs which are composed of single large webm or mp4 files.
- it also bundles an HTTP server that kiwix-serve uses but the android doesn't. And the test you pointed at concerns this HTTP server code that is not used on readers.

I believe the webview transparently sets the OK code and we shall tweak that on range requests (that we should detect, as I suggested above).

**Comment by ikreymer** [comment]
> it handles range requests for data access. This is working already on our youtube ZIMs which are composed of single large webm or mp4 files.

I checked another ZIM that has videos, it looks like it also responds with 200 to a byte range request. I think the webview is able to cope with it, but I noticed that I was not able to seek in the video (only start from the beginning), probably due to lack of 206 response. Adding proper range request support will probably improve playback of these videos too.

**Comment by rgaudin** [comment]
hum, as shown [here](https://github.com/openzim/youtube/wiki/Compatibility) we have no problem seeking on kiwix-serve videos (#91 is webm-apple specific and we actually found a workaround today).

Can you share ZIM url and confirm on what you test so I can reproduce your seeking issue?

**Comment by ikreymer** [comment]
> hum, as shown [here](https://github.com/openzim/youtube/wiki/Compatibility) we have no problem seeking on kiwix-serve videos (#91 is webm-apple specific and we actually found a workaround today).
> 
> Can you share ZIM url and confirm on what you test so I can reproduce your seeking issue?

Ah, sorry, I meant on kiwix-android, not on kiwix-serve. The 200 instead of 206 issue applies to all videos on android, not just those from warc2zim.

I tried this ZIM (the smallest one there): http://download.kiwix.org/zim/videos/scienceinthebath_en_assorted-nonsense_2020-08.zim with the Genymotion emulator.

**Comment by rgaudin** [comment]
@ikreymer thank you for this, I could reproduce: it's impossible to seek on any video in kiwix-android at the moment.
I am pretty sure it's a regression but haven't tried to confirm by testing with older version of the app.
I can confirm that the same ZIM is seekabe on the device's chrome if served via kiwix-serve so, as you suggest, it looks that this is related to that 206 status code missing.

@macgills let us know how we can help with this. Use the latest shared ZIM, it's only 24M.

**Comment by macgills** [comment]
AAAAGH as I feared, the introduction of serviceWorker support broke our ability to seek. Deeply confusing, don't know the specific root cause, maybe range support will fix this?

I guess it might be the scheme... previously we were `zim://content/` now we are `https://kiwix.app/` so we have to respect headers on all loads, that introduces some additional concerns

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/93323434-89000f80-f80c-11ea-8d39-7ab427c88247.png)

```
      if (requestHeaders.keys.contains("Range")) {
        setStatusCodeAndReasonPhrase(HttpURLConnection.HTTP_PARTIAL, "range request")
      }
```

![image](https://user-images.githubusercontent.com/3358282/93323514-a2a15700-f80c-11ea-9627-e0b985b4d683.png)


So yeah no clue

**Comment by macgills** [comment]
@rgaudin @ikreymer any further suggestions? It doesn't seem like scrubbing incurs any additional request for specific ranges.

Am I supposed to return some specific headers to indicate content length/range? I am not well versed in backend work as I typically write clients

**Comment by ikreymer** [comment]
Looking at the code, it doesn't seem like range requests were ever supported, even without service workers?
I think the support will need to be implemented manually (I tried to see if there was anything that would do so automatically or some sort of wrapper library but couldn't find anything).

Eg:
https://github.com/kiwix/kiwix-android/blob/master/core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreWebViewClient.java#L146
It's always just reading the full url `zimReaderContainer.load(url);`

I think you'll probably want to pass in the `Range` header from the request, using the `public WebResourceResponse shouldInterceptRequest (WebView view, WebResourceRequest request)` and then in the ZimFileReader, eg:
https://github.com/kiwix/kiwix-android/blob/master/core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt#L116
you would need to support seeking into the ZIM file response and returning the requested length, rather than the whole file.

It is odd, as it appeared the range request was working but just 206 was not being set, but maybe that's not true..
It certainly seems like it would need to be done manually from what I could find.

The WebViewClient *is* basically an HTTP server that allows custom HTTP responses to HTTP requests, so I think that's what would need to be done.

The libkiwix/kiwix-serve seems to have a bunch of custom code for dealing with range requests, and unless I'm missing something, it seems like same [type of handling](https://github.com/kiwix/kiwix-lib/blob/eb7a8beb77600cfe4f4b3e6eb74d288eab0a5cde/src/server/response.cpp#L393) would also be needed on other platforms.

Again, I only looked at this briefly, and this codebase is new to me, so apologies if I am missing something..

**Comment by kelson42** [comment]
@mhutti1 had implemented the solution to read only byte ranges for videos, years ago. It has to be there and this is mandatory.

**Comment by macgills** [comment]
it is the change of schemes that is screwing with us ie `zim://` -> `https://`, previously we just provided a resource as an inputstream inside a WebResponse that fully supports arbitrary seeking, it is not like we were reading the full webm/mp4 file into memory.

What is the appropriate Response to
![image](https://user-images.githubusercontent.com/3358282/93575374-77944000-f991-11ea-8e21-e7afcf9ced85.png)
?

Isn't it just asking for everything?

A brief bit of history on us returning WebResponses:
Originally this loading code did not return a WebResponse, it was located inside a ContentProvider and by simply adrressing with the scheme `content://`+our appid it redirected all requests to that component and all it demanded was an inputStream in response to a URI.

I modified it to make the relationship between the loading code and the webview more explicit.

**Comment by macgills** [comment]
@rgaudin  example branch pushed here

**Comment by rgaudin** [comment]
OK I eventually got it *working* but it's not straightforward:

- The Webview and/or the InputStream reads `Range` request headers and seeks appropriately into the data stream
- It doesn't set any `Content-Range` response headers though
- It does set the `Content-Length` one, adjusted to the seek position

So basically, what we need to do is:
- Set 206 status code on partial responses (important)
- set 200 status code on non-partial response to Range requests like `0-` (important)
- Build and set the `Content-Range` response header
- Add the `Accept-Ranges` headers (not required for video.js though but good practice)
- Content-Range must be `<startOffset>-<LastByte>/<fullSize>` (important) A single byte error here results in hell.
- Had to retrieve size from the inputstream instead of the `zimFileReader.fileSize` 🤷‍♂️

@macgills, I am pushing a commit on your test branch with those changes. This is informational. I don't known 💩 about kotlin so it's terrible and had to bypass the commit hook. Also, it's incomplete in range extractions (as I only needed `x-` since that's what video.js used).

I am sharing [a 15MB ZIM](http://tmp.kiwix.org/single-webm_2020-09.zim) file that's easy to test and includes not-minified video.js.

**Comment by rgaudin** [comment]
FYI, I tested it (@macgills's PR) with both *regular* videos (youtube scraper) and warc2zim ones (lesfondamentaux) and it works for both scenarios. btw @ikreymer you never completed the upload of the small version of lesfondamentaux 🙃
