### ISSUE TITLE
"Start Server" in ZimHostActivity does not have its color overriden.

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2349]
**Describe the bug**

The color of the start server button should be green, and the stop server button should be red. Currently, it is a shade of `denim_blue`.
**Expected behavior**

When the button has the text "Start Server" its color should be `startServerGreen`. 
When the button has the text "Stop Server" its color should be `stopServerRed`. 
**Steps to reproduce the behavior:**
1. Open ZimHostActivity by clicking the drawer -> Host Books. 

**Screenshots**
![Screenshot_1598790376](https://user-images.githubusercontent.com/22193232/91658957-cbb3af00-eacc-11ea-9445-ae2e017674eb.png)
![Screenshot_1598790372](https://user-images.githubusercontent.com/22193232/91658960-cce4dc00-eacc-11ea-971e-4c3a6ff64d7b.png)

**Comment by gouri-panda** [comment]
@Frans-Lukas can I take the issue?
