### ISSUE TITLE
tests: Revamp & Refine the Instrumentation Test for KiwixMainActivity

### ISSUE THREAD

**Issue by s-ayush2903** [kiwix/kiwix-android#2359]
**Type of Test**

* [ ] Unit Test
* [x] UI Test

**Particular area and files to be tested**
KiwixMainActivity

**Current Status of the tests**
Currently this test follows old norms and lacks some navigation tests

**Particular Behaviour to be tested**
It should exhaustively test the navigation originating from itself and follow the new norms as far as possible, mentioned as per #1212

**Comment by s-ayush2903** [comment]
PS: I would like to work on it.

**Comment by s-ayush2903** [comment]
@macgills Is this a valid to work with?

**Comment by macgills** [comment]
If you want to convert it then go ahead

**Comment by s-ayush2903** [comment]
I don't work like _what i want_ , i want to contribute in such a way that i learn the things that i don't know and to the issues which are in hight priority of module or what the module demands

**Comment by macgills** [comment]
Priority issues are in the milestone, those are important for 3.4 releasing. Increasing the quality of the automated tests is not a bad idea. I do want there to only be good examples of tests in the project.

Keeping contributors engaged in the project is fantastic and if that involves enhanced tests I am happy for it to happen. Our remaining java files are dwindling (thank god) but that presents a minor hiccough for our onboarding process for new contributors
