### ISSUE TITLE
Cant open Zim files on Android

### ISSUE THREAD

**Issue by okkebal** [kiwix/kiwix-android#236]
I have about 10 Zim files on my phone, tree of them with big indexes. Fulltext search works in these. When I go to 'get content' and try to open one of my local files it usually does not work. If Kiwix opened up with Dutch Wikipedia and I choose say wiktionary I still get Dutch Wikipedia. Restarting the app does nothing. I can select a different Zim only by using ES filemanager and directly opening a Zim file through that

**Comment by kelson42** [comment]
@okkebal Thank you for your bug report. Would you like to join the kiwix-testing google user group? We are currently testing 2.3 and would like to know if you still have the problem there.

The Kiwix-testing Google user group:
https://plus.google.com/communities/106410746144853739922

And then activate the testing for the app:
https://play.google.com/apps/testing/org.kiwix.kiwixmobile

**Comment by okkebal** [comment]
I'd love to join, but I'm not going to do anything in the "Play store" I use Yalp. Sorry

I did try a nightly from download.kiwix.org and the problem is still there... Is there a 2.3 nightly there too? It looks like its 2.2 still..

**Comment by kelson42** [comment]
@okkebal With the 2.3 version which works for you (64 bits) do you still have the pb?

**Comment by okkebal** [comment]
Just tried it, no improvement. I could upload a screenrecording if that helps.

**Comment by mhutti1** [comment]
@okkebal Yeaha screenrecording and log would be helpful.

**Comment by kelson42** [comment]
This bug report is quite "incredible". Screenrecording and corresponding Android log would be (like usual) really helpful to understand what is going one.

**Comment by okkebal** [comment]
Screenrecording 1:
[2018_02_15_13_44_15.zip](https://github.com/kiwix/kiwix-android/files/1727710/2018_02_15_13_44_15.zip)

This is feb 14 build of Kiwix-Android

I have 'wikiwoordenboek' open. And try to select a different file: does not work

Screenrecoring 2:
I select a file and a different file opens!

[2018_02_15_14_02_23.zip](https://github.com/kiwix/kiwix-android/files/1727730/2018_02_15_14_02_23.zip)

**Comment by okkebal** [comment]
[log.txt](https://github.com/kiwix/kiwix-android/files/1727758/log.txt)

I really do not know what I am doing in creating these log files. Hope it worked. Same problem only now doing adb logcat

**Comment by mhutti1** [comment]
@okkebal Thanks for the video that could be really helpfull. Can you let the loading circle finish loading and then see if this issue still occurs? (it might take some time).

**Comment by okkebal** [comment]
You talk about the loading circle in the 'get content' screen. 

This thing takes forever (oke about 60 sec) and appears every time I click 'get content'.

I've tried waiting before selecting a file. That does not work.

When I close kiwix, and open it again the file I selected previously is opened!

1: i get wikiwoordenboek
2: get content ->select Phet
3: still see wikiwoordenboek
4: kill kiwix
5: open kiwix
6: phet appears
7: get content
8: select medical wiki
9: wikiwoordenboek opens...
10: kill kiwix
11: open kiwix
12: medial wiki opens....

**Comment by arpank10** [comment]
Can you guide me as to where the error can possibly be? I found that the setZimFile() method in contentProvider is working correctly and setting the file to the corresponding file we are trying to open.So when we kill kiwix and reopen it, the previously set file is opening correctly.

**Comment by mhutti1** [comment]
@arpank10 As you can see this issue has been open for some time. This is because we don't have any idea ourselves.

**Comment by arpank10** [comment]
So far what I found - 
The uri parameter passed in the openFile method in zimContentProvider class is of the previous one. Somehow it doesn't get updated. Hence the same file opens. While it gets updated after reopening. 
@mhutti1 Do you have any idea when the openFile() method is called?

**Comment by mhutti1** [comment]
@arpank10 There are many tools in Android Studio that will do all this for you along with a simple repository search. Use them wisely.

**Comment by arpank10** [comment]
Actually it is not called anywhere in the repository.I should have mentioned it in the previous comment.I checked it with both find usages and search. It must been called by some method of the content provider class, anyways I will look into it.

**Comment by mhutti1** [comment]
If you right click and goto super you can see its a stub method in ContentProvider.class this normally means that it is called by a system component in this case automatically by the WebView
