### ISSUE TITLE
Document Git Hooks and create a troubleshooting guide

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2360]
**Is your feature request related to a problem? Please describe.**
The git hooks are a pain point for new contributors.

**Describe the solution you'd like**
Explain detekt, ktlint and committing with `--no-verify` and link this page from the git hook failure message

**Comment by s-ayush2903** [comment]
So this Issue does not need any Pull Request, just documenting here about the aforementioned and putting the url of this issue in `pre-commit.sh` will do the required, is it like that or something else?

**Comment by macgills** [comment]
It will probably entail a PR to add a markdown file but yes that is the file to be edited with the link

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please create a dedicated section in the CONTRIBUTING file
