### ISSUE TITLE
File transfer does not work

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2363]
**Describe the bug**
When initiating transfer of files the transfer finishes abruptly from the sender device, subsequent attempts to transfer lead to a crash
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter clientAddress
        at org.kiwix.kiwixmobile.localFileTransfer.WifiDirectManager.setClientAddress(Unknown Source:6)
        at org.kiwix.kiwixmobile.localFileTransfer.PeerGroupHandshakeAsyncTask.onPostExecute(PeerGroupHandshakeAsyncTask.java:164)
        at org.kiwix.kiwixmobile.localFileTransfer.PeerGroupHandshakeAsyncTask.onPostExecute(PeerGroupHandshakeAsyncTask.java:48)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
```

**Expected behavior**
No crash and the ability to share files over wifi

**Steps to reproduce the behavior:**
1. launch receiver activity on receiver device
2. Long click on a book from the sender device
3. click the share icon 
4. click send to nearby device
5. on both devices click the search icon until both devices are visible to each other
6. Click on the name of the receiver device from the sender
7. observe failure to send device

**Screenshots**

**Environment**
- Version of Kiwix Android : develop
- Device : Nexus5x & Samsung Galaxy s7
- OS version : 8.1 & 7.0

**Comment by gouri-panda** [comment]
@macgills I want to give a shot on this ticket?

**Comment by macgills** [comment]
You are assigned, 2 physical devices will probably be necessary to test this feature

**Comment by gouri-panda** [comment]
@macgills I can't reproduce the issue anymore. Previously how I reproduce the issue 
* after file transfer completion
*  close the activity and foreground the app 
* resume the app
* open the file receiver activity in receivers device 

thus how I reproduced the issue. Now I can't if you give me some more hint about how to produce the issue then that will be great. Thanks!

**Comment by gouri-panda** [comment]
@kelson42 This issue is resolved. Should we remove from pinned issues?
