### ISSUE TITLE
SearchFragment doesn't hide keyboard on finish

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2378]
**Describe the bug**
Open the search fragment, press the back arrow in the toolbar, see the keyboard is still open in a context where you can't input text.

**Expected behavior**
The only scenario where the keyboard should remain open after leaving search is when launching FindInPage

**Screenshots**

**Environment**
- Version of Kiwix Android : one-activity branch

**Comment by kelson42** [comment]
Looks like a regression?

**Comment by macgills** [comment]
A mistake I should have caught at review time, I had too many instances of android studio running so I inadvertently tested the wrong version. I merged it, realised my mistake and after testing thought a full reversion was overkill, it is on a branch separate from dev anyhow

**Comment by Frans-Lukas** [comment]
I'll fix!
