### ISSUE TITLE
How easily can we query Kiwix-android from another app

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2381]
Bear with me, here is the use case and the question comes after that.
There's a whatsapp service that works like a bot: there's a menu, and depending on what you send as text you can get a reply from the bot (e.g. text, or documents or links). 
![Capture-d’écran-2020-09-03-à-17 07 10](https://user-images.githubusercontent.com/21675885/93615162-55231680-f9d3-11ea-9c7d-d4c5ffc2aa01.png)

The idea would be for a hybrid service whereby users have kiwix with a zim file on it (say, a youtube playlist or even wikipedia), and depending on their action with the whatsapp bot would get a link which, instead of directing them to youtube or even sending them the Wikipedia article, would direct them to that same video on the zim file that is locally hosted.

How hard would this be to do? I know it's already possible to highlight some text and query Kiwix, but I don't know how different that would be if we want to open videos or documents within a zim.

**Comment by macgills** [comment]
There are 2 options App links and Deep links.

The link would need to contain the following information:

unique identified of a zim, probably zimId
the path of the article to open

Potential problems are that we can't know if a zimFile is actually downloaded and we would be routing all of these links to our app once we make this change

**Comment by Popolechien** [comment]
okie dokie. I'll close the ticket for now, it would be nice to have at some point but clearly not a low-hanging fruit.

**Comment by macgills** [comment]
Hmm though I suppose this is not "querying Kiwix" more just launching specifically to kiwix. If we wanted to query  kiwix from another app we would use a ContentProvider, this would require tight integration with another app though, more suited to a family of apps from the same publisher
