### ISSUE TITLE
Online Library is just loading and loading 

### ISSUE THREAD

**Issue by abhijeetsinghcode** [kiwix/kiwix-android#2385]
On navigating Download Books >Online 
Online Library is not opening and it is  just loading and loading  . I have tried for max - 20 min. 
I have decent internet connection .
 I have also restarted my device, uninstalled app and installed it.
I have also checked with settings - Download content via Wifi.

I have tried with Wifi and mobile data/wifi/mobile data
![Screenshot_20200920-203156](https://user-images.githubusercontent.com/58856747/93714997-0e285300-fb84-11ea-993a-d04d69d70053.png)

Sometimes  - No network  Connection 
![Screenshot_20200920-203202](https://user-images.githubusercontent.com/58856747/93715001-11bbda00-fb84-11ea-949d-2a297c5a0eff.png)

Device - Redmi Go
Android ver - 8.1.0

**Comment by gouri-panda** [comment]
I'm also encountering this problem too. @abhijeetsinghcode do you want to work on this issue?

**Comment by abhijeetsinghcode** [comment]
> I'm also encountering this problem too. @abhijeetsinghcode do you want to work on this issue?

Yes , I will love to work on this  but I am currently learning Android ,So I don't have good knowledge to how to tackle the problem.

**Comment by abhijeetsinghcode** [comment]
I have tried to open the Online page in morning . It is working but it take time to load the results .

**Comment by kelson42** [comment]
I think it would be good to send at that point the diagnostic per email.

**Comment by macgills** [comment]
Could it have been the stability of our mirrors? Do we have any healthcheck apis for them @kelson42 ?

**Comment by s-ayush2903** [comment]
* I don't consider this as an issue, the ISP that is depicted in the screesnshot has poor connection in the prime time(as i'm from the same country and use the same same ISP(Jio)) so it cannot load the library, whereas when the same is tried late/mid night it works smoothly.
* If we see logs when it shows loading then they say a 200 OK response from the backend and fetching in progress. 
* For weaker connections like this we should set some timeout limit(imo)

**Comment by abhijeetsinghcode** [comment]
> * I don't consider this as an issue, the ISP that is depicted in the screesnshot has poor connection in the prime time(as i'm from the same country and use the same ISP(Jio)) so it cannot load the library, whereas when the same is tried late/mid night it works smoothly.
> * If we see logs when it shows loading then they say a 200 OK response from the backend and fetching in progress.
> * For weaker connections like this we should set some timeout limit(imo)
Before I checked Kiwiz app,I watched YouTube video in 420p for 20min then I opened the app and tested it.

**Comment by gouri-panda** [comment]
> > * I don't consider this as an issue, the ISP that is depicted in the screesnshot has poor connection in the prime time(as i'm from the same country and use the same ISP(Jio)) so it cannot load the library, whereas when the same is tried late/mid night it works smoothly.
> > * If we see logs when it shows loading then they say a 200 OK response from the backend and fetching in progress.
> > * For weaker connections like this we should set some timeout limit(imo)
> 
> 
> Before I checked Kiwiz app,I watched YouTube video in 420p for 20min then I opened the app and tested it.

@abhijeetsinghcode It seems like it's a server related issue. Perheps @macgills can help with this issue.

**Comment by macgills** [comment]
I have no visibility on any servers and I cannot reproduce it, if I could reproduce it then I could get somewhere.

@kelson42 may be able to give some info on our mirrors.

@abhijeetsinghcode if this problem is still persisting add some debug logs to

ZimManageViewModel.updateLibraryItems

particularly the parameters of the `combineLatest`

```
Flowable.combineLatest(
    booksFromDao,
    downloads,
    languages.filter { it.isNotEmpty() },
    library,
    Flowable.merge(
      Flowable.just(""),
      requestFiltering
        .doOnNext { libraryListIsRefreshing.postValue(true) }
        .debounce(500, MILLISECONDS)
        .observeOn(Schedulers.io())
    ),
    fat32Checker.fileSystemStates,
```

eg `booksFromDao.doOnNext{ Log.e("booksFromDao", "$it")}`

All of these inputs need to emit at least 1 value for the list UI to start updating

**Comment by abhijeetsinghcode** [comment]
Sir, I have  tried many times .
What I found is that sometimes it work sometime not .
Video 
https://drive.google.com/file/d/1-W9TGv9tqRM8pzvRZE7J9Ro8AB5CtjzK/view?usp=drivesdk

**Comment by kelson42** [comment]
@macgills It is impossible forme to know wich mirror has bee picked, but this shoul bevisble in the logs, maybe even the diagnostic.

**Comment by kelson42** [comment]
To me the problem here is the lack of proper error mgmt in such a case.

**Comment by macgills** [comment]
> Sir, I have tried many times .
> What I found is that sometimes it work sometime not .
> Video
> https://drive.google.com/file/d/1-W9TGv9tqRM8pzvRZE7J9Ro8AB5CtjzK/view?usp=drivesdk

This is going to tell me very little about what is happening, other than the fact that it is happening. If you are willing to dive into the code and look through the logs I might be able to do something but the diagnostic report won't help here. Network logs only exist in a basic form on debug variants of the application. Prod apps have nothing network related.

**Comment by s-ayush2903** [comment]
The code changes needed for proper logging in the networking module were explained in great detail by @macgills in the #android in slack, a few weeks back. Those logs provided me more than sufficient information that led me to infer that it was merely a poor internet connection only.

**Comment by abhijeetsinghcode** [comment]
> > Sir, I have tried many times .
> > What I found is that sometimes it work sometime not .
> > Video
> > https://drive.google.com/file/d/1-W9TGv9tqRM8pzvRZE7J9Ro8AB5CtjzK/view?usp=drivesdk
> 
> This is going to tell me very little about what is happening, other than the fact that it is happening. If you are willing to dive into the code and look through the logs I might be able to do something but the diagnostic report won't help here. Network logs only exist in a basic form on debug variants of the application. Prod apps have nothing network related.


Sir ,This is all log infomation of my device 

All log information when app is open and loading of Online Library
1. https://drive.google.com/file/d/115hIZh40gCz_2kwAmdct7Geo8Gg1etaD/view?usp=sharing

2.https://drive.google.com/file/d/11Bj-HpB4PCAr7fR5IXvWdW16I2TRN8RO/view?usp=sharing
phone :- Samsung
Android ver :- 8.1.0

**Comment by macgills** [comment]
You will have to make modifications yourself to enable logging of the relevant portions of the app and install the app locally to get relevant logs, unfortunately those logs tell me nothing.

That is option a), option b) is wait quite some time until i have enough availability to investigate/make a debug version for you to investigate with

**Comment by abhijeetsinghcode** [comment]
Okay,Sir

**Comment by gouri-panda** [comment]
>I don't consider this as an issue, the ISP that is depicted in the screesnshot has poor connection in the prime time(as i'm from the same country and use the same ISP(Jio)) so it cannot load the library, whereas when the same is tried late/mid night it works smoothly.
@s-ayush2903 Nowadays I am not encountering this problem very often. Sometimes the download fragment has loaded and sometimes it doesn't but before that, it only loads in the mid/late night.

**Comment by macgills** [comment]
Have encountered this issue
```
I: --> GET http://mirror.download.kiwix.org/library/library_zim.xml http/1.1
I: Host: mirror.download.kiwix.org
I: Connection: Keep-Alive
I: Accept-Encoding: gzip
I: User-Agent: okhttp/4.9.0
I: --> END GET
I: <-- 200 OK http://mirror.download.kiwix.org/library/library_zim.xml (25ms)
I: Server: uhttpd/1.0.0
I: Date: Fri, 02 Jan 1970 07:36:53 GMT
I: X-Frame-Options: SAMEORIGIN
I: Cache-Control: no-cache,no-store
I: Pragma: no-cache
I: Expires: 0
I: Content-Type: text/html; charset="UTF-8"
I: Connection: close
I: <html>
I: <head>
I: </head>
I: <script> top.location.href="http://www.mywifiext.com";</script>
I: <body>
I: </body>
I: </html>
I: <-- END HTTP (109-byte body)
```

I was not receiving the list and had inadvertently connected to my wifi extender that was complaining it wasn't connected and returning the above garbage html. The non strict nature of the serialiser was permitting a malformed object through and causing a failure when we tried to offer an item. Enforcing the strictness allowed the retries to perform and fail gracefully, dismissing the loading icon

**Comment by gouri-panda** [comment]
@macgills  I'm still encountering this problem.

**Comment by macgills** [comment]
go to `NetworkModule`
change
```
      .addNetworkInterceptor(HttpLoggingInterceptor().apply {
        level = if (BuildConfig.DEBUG) BASIC else NONE
      })
```
`BASIC` to `BODY`, post your logs. It will take 5 minutes for it to totally fail if the root cause is slow connection
