### ISSUE TITLE
Invite user to delete old versions of the same content

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2391]
Currently most files have a `name_yyyy-mm` naming convention, but if I have wikipedia_en_all_mini_2020-08 and want to update it I end up with two nearly identical files (and twice as much space used up). I still need to manually delete the "old version.". Kiwix should be able to recognize updates and delete/overwrite as needed.

**Comment by epicadk** [comment]
Can I work on this?

**Comment by kelson42** [comment]
We need to agree first about what to do. This can be done based on the ZIM `name` metadata (so not the filename). But I disagree that we should automatically delete it, but we could provide an invite.

**Comment by Popolechien** [comment]
@kelson42 honest question: why not delete it automatically? What's the use case?

**Comment by kelson42** [comment]
@Popolechien If content is downloaded at user initiative, it should be deleted at user initiative. I strongly oppose to do that automatically. It is a principle.

**Comment by Popolechien** [comment]
@kelson42 yeah I wasn't very clear with the scenario I had in mind but obviously it should ask for confirmation, as it does in most cases. 
What I meant to say is that the default outcome of a new download should not be having two files sitting side by side without the user being notified that the second download can replace the older one (and confirm with a single click).

**Comment by epicadk** [comment]
Can I work on this?

**Comment by ManasviPatidar** [comment]
@kelson42 I would like to work on this issue.
But to start my work I need to know how to recreate/test this. To be more precise how do I get new and old versions of the same file on demand so that I can update it.

**Comment by Popolechien** [comment]
@ManasviPatidar The easiest way is to head over at download.kiwix.org/zim : it keeps the two last versions of a zim file (so at this stage probably xxxx-2020-12.zim and xxxx-2021-01.zim)

**Comment by kelson42** [comment]
@ManasviPatidar At https://download.kiwix.org/zim, you have always two revisions of a content (different months). I think the dialog to invite to delete an older content should happen at the time a new content is put in the library. Basically, if a new content "replace" an old content.
@mgautierfr I believe the primitive to identify the "duplicate" should be anyway in the kiwix-lib. Would you be able to enlight us on this?

**Comment by kelson42** [comment]
Basically a duplicate of #57
