### ISSUE TITLE
Search Kiwix is just redirecting to kiwix app but not searching the result

### ISSUE THREAD

**Issue by Abhijeetcodev** [kiwix/kiwix-android#2398]
When I select a text and long press it  on Chrome , I got option to choose my search So when ever I choose  Search Kiwix 
It redirect me to Kiwix app but it just load after that there is no result of my search.

video -> Kiwix app
https://drive.google.com/file/d/10M1Q5jGS7pwMujc4ZVDskSVDVpnD89k4/view?usp=sharing

video-> Kiwix app (Beta)
https://drive.google.com/file/d/10GpM6HY-bRWouFdmWslN6lUcYXpqGn6j/view?usp=sharing

**Comment by kelson42** [comment]
@macgills Do we have a regression here?

**Comment by macgills** [comment]
We already have an open ticket https://github.com/kiwix/kiwix-android/issues/2372 but I believe this issue has been longstanding regardless

**Comment by erayd** [comment]
It's also not possible to press the back button to return to whatever app the search was triggered from.

**Comment by gouri-panda** [comment]
I just wanna add a note here If the Kiwix app doesn't exist in the background then the issue exists otherwise it's not.

**Comment by gouri-panda** [comment]
@kelson42 Can I try this?

**Comment by kelson42** [comment]
@gouri-panda Yes, please would be great!

**Comment by kelson42** [comment]
@gouri-panda Any news on this ticket, this is actually a quite annoying bug (the full search widget feature broken) and my guess relatively easy to fix?
