### ISSUE TITLE
Rounded search bar widget

### ISSUE THREAD

**Issue by Mitia99** [kiwix/kiwix-android#2399]
**Is your feature request related to a problem? Please describe.**
The Widget UI is a bit old  

**Describe the solution you'd like**
 Rounded corner for the search bar widget

**Comment by kelson42** [comment]
Feedback would be welcome to know if there is a consensus about this enhancement proposal.

**Comment by macgills** [comment]
The Widget probably needs a lot more done to it.

Overall I'd like clarity on the usecase of it, the search looks like a textfield but you can't enter text into it.
The point is quick access into search/favourites/voice search? This is better served by adding shortcuts to our app launcher

![image](https://user-images.githubusercontent.com/3358282/94244157-5cd14680-ff10-11ea-9ccb-7072a9303b09.png)

A good widget should be a portal of information/content not just links into the app

**Comment by kelson42** [comment]
Agree with @macgills, we probably need here a global proposal for this widget before doing anything.

**Comment by Mitia99** [comment]
Actualy I don't have any proposal apart from the rounded corners.Let's see other's proposals.

**Comment by macgills** [comment]
The I guess my proposal is as follows:

Replace Widget with [shortcuts](https://developer.android.com/guide/topics/ui/shortcuts)

It limits us to 4 actions even though we can specify 5
>Although you can publish up to five shortcuts (static and dynamic shortcuts combined) at a time for your app, most launchers can only display four.

I think we can get rid of `Get Content` with the new navigation making it far more accessible. Leaks is only present on debug so I would ignore that. That leaves us with `New Tab`, `Search`, `Favourites`, `Voice Search`.
I might even get rid of voice search for `History` as that feels more right to me if we are showing favourites as well

**Comment by shivamparihar12** [comment]
hello, I just wanna know that can I work on this issue?

**Comment by kelson42** [comment]
@shivamparihar12 I don't think this task is ready for now to be implemented.

**Comment by shivamparihar12** [comment]
@kelson42 thanks for letting me know that.

**Comment by kelson42** [comment]
@MohitMaliFtechiz @gouri-panda I'm not in favour of just fixing this small thing. Here we need to revamp this is I understand properly. To me either we close the ticket or someone propose a propoer/global plan regarding this widget.

**Comment by gouri-panda** [comment]
@kelson42 @MohitMaliFtechiz I think I agree with the seàn's propose. But I don't like the idea to remove the `History` in favour of `Voice Search`.

**Comment by kelson42** [comment]
Closing, ticket is too unclear. A real and complete proposal for the widget has to be made.
