### ISSUE TITLE
Convert TableDrawerAdapter to kotlin

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2401]
Is your feature request related to a problem? Please describe.

TableDrawerAdapter is in Java

Describe the solution you'd like

Convert it in Kotlin

Additional context

Parent issue #1826

**Comment by Rajnish23** [comment]
I would like to work on this issue. Should I go ahead?

**Comment by gouri-panda** [comment]
@Rajnish23 you are assigned!
