### ISSUE TITLE
Convert TabsAdapter to kotlin

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2402]
Is your feature request related to a problem? Please describe.

TabsAdapter is in Java

Describe the solution you'd like

Convert it in Kotlin

Additional context

Parent issue #1826

**Comment by ritik17499** [comment]
Can i work on this?

**Comment by gouri-panda** [comment]
@ritik17499 sorry,I am working on this issue. If you want you can work on #2401 .

**Comment by abdulwd** [comment]
Discussed with @gouri-panda, I'm picking this. @ritik17499 If you need my help in assigning a ticket to you let me know.
