### ISSUE TITLE
Cannot play video (audio ok)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2404]
On 3.4.0 build 6230400 (Huawei P20 lite / android 9) playing videos yields correct audio but the image is either fixed and jumpy or black screen (if it loads at all). Also notice the false color bit.

![Screenshot_20200928_101759_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/94407717-154af480-0174-11eb-9561-1b140a10d458.jpg)

I've tried with 
http://download.kiwix.org/zim/videos/scienceinthebath_en_assorted-nonsense_2020-08.zim
http://download.kiwix.org/zim/ted/ted_en_playlist-11-must-see-ted-talks_2020-09.zim
http://download.kiwix.org/zim/ted/ted_en_playlist-how-navigate-questionable-information_2020-09.zim
http://download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2020-07.zim
Don't know if this is related to #2202

**Comment by Popolechien** [comment]
Ah wait is this some duplicate of #2347 ?

**Comment by macgills** [comment]
I would believe so. You are using the beta I take it?

**Comment by Popolechien** [comment]
Probably, yes, as I am on the beta list and haven't switched back to anything.

**Comment by Popolechien** [comment]
well then closing as duplicate.
