### ISSUE TITLE
Navigation view not hidden for fullscreen video

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2407]
**Describe the bug**
Play a video, press fullscreen with navigation view visible, see navigation view

**Screenshots**
![image](https://user-images.githubusercontent.com/3358282/94424230-ca37de00-0181-11eb-9b13-233ced77dcc6.png)

**Environment**
- Version of Kiwix Android : https://github.com/kiwix/kiwix-android/pull/2406

**Comment by gouri-panda** [comment]
I'll take this issue.
