### ISSUE TITLE
Custom app flags zim file as invalid 2 weeks or so after install

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2408]
User (Samsung Galaxy A20 / android 10) reports installing Wikimed and, every couple of weeks, needs to uninstall and re-install the app following this error message. Until this happens the app is fully useable.

![Screenshot_20200928-125214_One UI Home](https://user-images.githubusercontent.com/21675885/94435463-72a66c00-019b-11eb-9127-58e2135a9265.jpg)

**Comment by kelson42** [comment]
IMO he or something is just deleting the ZIM file.

**Comment by macgills** [comment]
```
  private fun obbFiles() = scanDirs(ContextCompat.getObbDirs(context), "obb")

  private fun zimFiles() =
    scanDirs(ContextCompat.getExternalFilesDirs(context, null), "zim")

  private fun scanDirs(dirs: Array<out File?>?, extensionToMatch: String): List<File> =
    dirs?.filterNotNull()?.fold(listOf()) { acc, dir ->
      acc + dir.walk().filter { it.extension.startsWith(extensionToMatch) }.toList()
    } ?: emptyList()
```

I do not understand how this code could be malfunctioning. The user deleting their obb file seems most likely?

Google does do some magic with obb files sometimes with regards updates but that doesn't seem consistent with this report

**Comment by kelson42** [comment]
@BBT-SeanMacGillicuddy Would that be possible maybe to get more details in the message? Maybe if we know it has worked one time, to just write that the file `/.../..obb` has disappeared!

**Comment by macgills** [comment]
I would have to store the results of what the previous "file validation" was, it wouldn't just be a case of adding logs.

**Comment by Popolechien** [comment]
Ok, user wrote back saying he was deleting files that he didn't know were needed o_0
Case closed.
