### ISSUE TITLE
Toolbar in Reader is scrollable

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2411]
**Describe the bug**
When trying to use the swipe gestures to change tab/open the tab switcher I was unable to and was able to swipe it off the screen

**Expected behavior**

The toolbar should not be capable of being swiped up and the swipe gestures should work

**Screenshots**

![image](https://user-images.githubusercontent.com/3358282/94650476-b493f700-02ee-11eb-9aff-65f24a72f241.png)

**Environment**
- Version of Kiwix Android : develop

**Comment by kelson42** [comment]
@Frans-Lukas @macgills Would that be wise to release 3.4 with this bug?

**Comment by macgills** [comment]
We can postpone fixing it, the gestures are quite a hidden feature and it is only because I know about them that I even attempted it.

It doesn't crash or anything and a quick navigation will restore the toolbar. Low priority but unfortunate. I could  see it being in a 3.4.2 or something

**Comment by Frans-Lukas** [comment]
I'll take a look this weekend.
