### ISSUE TITLE
Wiki of Ice and Fire Major bug

### ISSUE THREAD

**Issue by Destroyer5150** [kiwix/kiwix-android#2419]
![Screenshot_20201004-051219_Kiwix](https://user-images.githubusercontent.com/59759269/95015224-a6045300-0600-11eb-8f47-b6db92f3711b.jpg)
As you can see, most of the content can not be seen. It's been this way for about a year. The little bit that you can see on the right, can be moved and scrolled through but only in that small area of the screen. I use a galaxy S9 SD845 android version 8.0. The only zim that does work properly is from 2018 because like an idiot, I've always treated them as updates and deleted the old. Thank you

**Comment by macgills** [comment]
In landscape is the situation improved at all?

@kelson42 seems like it could be an issue at creation/scraping time?

**Comment by Destroyer5150** [comment]
![Screenshot_20201005-155509_Kiwix](https://user-images.githubusercontent.com/59759269/95140218-2cb15100-0723-11eb-8299-92384ac37739.jpg)
Somewhat. Still offset to the right but I can zoom in to fill the screen. If there's a way to edit something in the zim, tell my what tool to use and how and I can try. I'm limited to my phone and a wine VM (Exagear) no pc, but it could be fun to try lol

**Comment by s-ayush2903** [comment]
Woah! looks astonishingly different at my end, pictures too ain't being rendered in my device. I'm android 10
|Landscape mode|
|--|
|![IceAndFire](https://user-images.githubusercontent.com/56556919/95142372-2b1e7200-0791-11eb-8b2d-50f229519a76.jpg)|

|Portrait Mode|
|---|
|![vertical](https://user-images.githubusercontent.com/56556919/95142485-6faa0d80-0791-11eb-8839-4056b444220a.jpg)|

**Comment by Destroyer5150** [comment]
@s-ayush2903
That's the text only zim. Text only looks exactly like yours on my end. I have both. With pics and text only. If I remember correctly, the bug is not only restricted to these zims. I don't remember the others I've tried since I've did a little cleaning up on my device.

**Comment by macgills** [comment]
@kelson42 can we check this file on other products? I haven't eliminated the possibility it is an android issue but would like to. Memory is just acting a bit fuzzy on how to do so.

**Comment by Destroyer5150** [comment]
I grabbed a few small zims to test and this is what Im getting.
![Screenshot_20201006-040829_Kiwix](https://user-images.githubusercontent.com/59759269/95194119-c14e9a00-0789-11eb-927b-3f314ba61903.jpg)
![Screenshot_20201006-040819_Kiwix](https://user-images.githubusercontent.com/59759269/95194137-c6abe480-0789-11eb-994b-0113a3e2af97.jpg)
Most zims are far too large for phone storage. So I'm limited on testing. I would find the space for a Dark Souls wiki 😁

**Comment by kelson42** [comment]
@Destroyer5150 Which zim file is that?
