### ISSUE TITLE
Can no longer open history items correctly. 

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2428]
**Describe the bug**

When opening a history item, a "Webpage not available" page is displayed in the reader fragment.

**Expected behavior**

The history item page and its book should be opened in the reader fragment.

**Steps to reproduce the behavior:**
The only book I have on my device is the `Test` book.
1. Open the history fragment.
2. Click on "Sven-Åke Johansson" or try some other history item if you do not have the `Test` book.
3. Notice the page doesn't load or displays "Webpage not available." 
4. If this bug does not occur, try opening another history item, some items work, some does not. 

**Screenshots**

![121282639_1265405147151179_2883778882544141144_n](https://user-images.githubusercontent.com/22193232/95675902-d036b180-0bba-11eb-8922-d41be94aa492.jpg)

**Environment**
- Version of Kiwix Android :  latest dev branch

**Comment by macgills** [comment]
Not an issue. The problem here is that your history was stored as the new `https` scheme but I have since reverted that because service workers need much more work before they are production ready
