### ISSUE TITLE
KiwixMainActivity leak caused by WifiP2pManager.

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#2435]
**Describe the bug**

I was using my phone when leak canary displayed a leak from Kiwix, I had not opened kiwix for at least an hour which makes this hard to reproduce. See screenshot for actual leak canary report.

**Expected behavior**

Memory leaks should not occur.

**Steps to reproduce the behavior:**
1. This happened with Kiwix minimized, otherwise I do not know how to reproduce this. Maybe the leak canary report can give hints as to how to reproduce it?

**Screenshots**

![121611811_352838869299993_6830386693306009073_n](https://user-images.githubusercontent.com/22193232/95830007-50822180-0d37-11eb-9d39-db0b4eaecd2a.jpg)

**Comment by kelson42** [comment]
@Frans-Lukas @mhutti1 Can we live a few months with this memory leak? Is that easy to fix?

**Comment by macgills** [comment]
seeing as it is the WifiP2P a user would have to actually use the feature to cause the leak which I think has been quite unlikely though I do not have analytics to support this hypothesis

**Comment by Frans-Lukas** [comment]
Very nice, go ahead!

**Comment by gouri-panda** [comment]
@Frans-Lukas I can't reproduce this issue. @macgills @Frans-Lukas Can you give me some suggestions on how to reproduce this issue?

**Comment by Frans-Lukas** [comment]
@gouri-panda I do not know how to reproduce, all I can tell you is that kiwix was minimized and  had been for maybe an hour? This might be a difficult ticket to prove as finished.

**Comment by macgills** [comment]
I would try performing a file transfer and pressing back until the application exits. I am beginning the release now so sadly this won't make it for 3.4.1 but 3.4.2 is right around the corner

**Comment by gouri-panda** [comment]
**Steps to reproduce this issue**

* Open FileTransefer Fragment
* Change WIFI discovery network (If you are connected to wifi then remove this network)
* go back until the app is in the foreground

**Comment by gouri-panda** [comment]
**Scenario 2**
* Open Library Fragment
* Tap the share button on the upper right corner
* Search the wifi
* Go back until you reach the home screen
