### ISSUE TITLE
Upgrade to AS/AGP 4.1

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2437]
**Is your feature request related to a problem? Please describe.**

Android Studio 4.1 has been released, we should update our tooling to take advantage of the latest features

**Describe the solution you'd like**

Update Android Studio and the gradle plugin

**Comment by kelson42** [comment]
@BBT-SeanMacGillicuddy Do we really need that for 3.4?

**Comment by macgills** [comment]
no, only a nice to have that I thought would be easy and quickly wasn't

**Comment by MohitMaliFtechiz** [comment]
hi,

this already updated on 3.6.0.
