### ISSUE TITLE
Adding layout attribute for each fragment in kiwix_nav_graph.xml

### ISSUE THREAD

**Issue by Dalakoti07** [kiwix/kiwix-android#2439]
Having a UI description helps in understanding the nav-graph flow better. I want to add layout attribute ti each fragment in kiwix_nav_graph.xml

At present we have nav-graph something like :
![image](https://user-images.githubusercontent.com/38468299/96004915-920aed80-0e59-11eb-8660-d1a2636115d4.png)

It can be made something like:
![layout_after_changes](https://user-images.githubusercontent.com/38468299/96005338-f75ede80-0e59-11eb-81a6-09b9887d9897.png)

Can I work on it?
More over we can recursively put recyclerview-item layout attribute in each fragment's recyclervoew for more UI improvements.

**Comment by macgills** [comment]
Sounds great, better previews and `tools` attributes help everyone
