### ISSUE TITLE
Suggested enhancement: Use Cached Library file when...

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#244]
Currently, the app downloaded the library catalogue file each time the user selects the Online tab. It might be worth implement support where the app uses a cached copy when...

- The network is slow, problematic, or unavailable
- The file was downloaded recently (in the same user session). The file changes infrequently.

Downloading the library file often may be a waste of the user's time and precious network connection.

Design ideas:
- We'd probably want to inform the user when we're using a cached copy.
- Could we add a cache age in the file?
- Downloads can still be requested by users, they'd happen when the WiFi network is available (and ideally working well)
- We'd probably want to inform the user if&when the app perceives problems with the network connection.
- We could add a download anyway option if users want to check they've got the latest version of the file.

Implementation ideas:
- Could we store the library file with the ZIM files on the SD card (etc.)?
- How would we read the cached copy and update the GUI in `LibraryPresenter.java`

**Comment by kelson42** [comment]
We are going to provide the online catalog through an OPDS API. As a consequence, I'm not sure this ticket is really valid.

**Comment by julianharty** [comment]
Tell me more...
will that be downloaded over a network connection? when? what happens if the network isn't available, etc? how will the catalogue be updated on/to the device?

**Comment by kelson42** [comment]
@julianharty kiwix-lib will happen in September. Details will be discussed in collab with @automactic and @mhutti1 at that time.

**Comment by kelson42** [comment]
OPDS mgmt in kiwix-lib is ongoing and will be over in ~ 2 weeks. It is planned to update the JNI in collaboration with Isaac during next hackathon. I'll close the ticket as WONTFIX.
