### ISSUE TITLE
Shimmer Effect in Download Screen Needed

### ISSUE THREAD

**Issue by s-ayush2903** [kiwix/kiwix-android#2441]
**Is your feature request related to a problem? Please describe.**
Most of the times, (due to the slower internet connection) user tend to lose the patience and hence terminates the application just because of staring at the entirely blank screen with a spinner rotating at the top, so shimmer layout can look nicer from a UX perspective and may increase the user stability.

**Describe the solution you'd like**
Implementation of Shimmering in download screen

**Describe alternatives you've considered**
Nothing else is what I have in my mind(other than shimmer layout)

**Additional context**
|Blank Download Screen (when connection is just initialized)|
|--|
|![blankLayout](https://user-images.githubusercontent.com/56556919/96043014-f2b31e00-0e8b-11eb-83e9-0699fab88b8b.jpeg)|

**Comment by s-ayush2903** [comment]
I will be taking this up

**Comment by macgills** [comment]
we need to agree to it first and personally I am not for it.

OPDS is a longstanding evolution of our endpoint that should dramatically reduce load times and I'd rather we attempt to focus on that rather than this

**Comment by s-ayush2903** [comment]
Fine then, I'll close it
