### ISSUE TITLE
Advanced library search : Option to display only selected label(Vid,Pic,Text...)

### ISSUE THREAD

**Issue by Mitia99** [kiwix/kiwix-android#2446]
**Describe the solution you'd like**
Option to only display "pic zim,vid zim,text only zim..."when doing a content search

**Additional context**
![AddText_10-16-06.03.33.jpg](https://user-images.githubusercontent.com/56766778/96276448-b0005b80-0fdb-11eb-975b-53e7414d53b5.jpg)

**Comment by macgills** [comment]
I would consider this a dupe of #1077 , thank you for the report, closing
