### ISSUE TITLE
Allow read aloud to continue while app is in background

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2448]
**Describe the bug**
Evidently a regression introduced in 3.4.1. Users want to be able to listen to articles without having kiwix visibly open. I imagine we just put an unregister call in OnDestroy instead of onPause

**Expected behavior**
Read aloud to continue

**Steps to reproduce the behavior:**
1. Click Read Aloud
1. Background the app

**Environment**
- Version of Kiwix Android : 3.4.1

**Comment by s-ayush2903** [comment]
I would like to take it up!

**Comment by gouri-panda** [comment]
@macgills It would be better if we add preference for this so that user can choose that  they want play audio in the background or not.

**Comment by gouri-panda** [comment]
@macgills you're right Users will want that. What I meant was what if they want to change this behavior under different circumstances. I am thinking about this.
<img width="321" alt="Screenshot 2020-10-21 at 2 31 29 PM" src="https://user-images.githubusercontent.com/43576162/96697930-1ef9fd80-13aa-11eb-988d-94c7ea05fb71.png">
.

**Comment by macgills** [comment]
I don't want that. the user can just stop the audio if they want to stop the audio. I want features that run with reasonable defaults, not multi faceted things that are hard to maintain
