### ISSUE TITLE
Could not click any link in the TED content

### ISSUE THREAD

**Issue by EvansJahja** [kiwix/kiwix-android#2459]
From my Android device, I expect to be able to view offline version of the TED contents. However, clicking any of the image link just make the page scrolls to the top without opening the link.

I expect to be able to click the links in the TED contents and view the videos.

Steps to reproduce:
1. Download any of the TED content. Here I use "How to live many lives"
2. Inside the content, see that there are multiple thumbnail & title. Let's click the second one "How I became 100 artists"
3. Notice how the page jumps to the top of the page instead of showing the content

- Version of Kiwix Android : 3.3.1
- Device : Samsung S10+
- OS version : Android 10

Note:

Kiwix has a feature to "Host Books", and I can open the hosted content from my laptop, connecting to my phone via web browser.
I can see the homepage of the TED contents and I can click on the links, play the videos with no issue.

Note:

Clicking on "Random Article" would take me to the content page with video and I can watch the video with no issue. Therefore the issue lies going from Homepage -> Link -> Content page

**Comment by macgills** [comment]
This could be an issue where our redirect evaluating code is returning empty for some links, causing an initial page load. I am trying to remember some discussion on the topic, will need to investigate to get specific repro steps before pinging people. Thank you for the report

**Comment by gouri-panda** [comment]
@macgills I can't reproduce this issue. Perhaps you can tell me how to find this issue?

**Comment by kelson42** [comment]
@EvansJahja We are currently release 3.4.1, would be great to test with it. Please let us know the result as soon as you have updated.

**Comment by EvansJahja** [comment]
Fixed in newer version

**Comment by kelson42** [comment]
@EvansJahja Thx you for reporting back.
