### ISSUE TITLE
Modern splash screen

### ISSUE THREAD

**Issue by Mitia99** [kiwix/kiwix-android#2462]
**Is your feature request related to a problem? Please describe.**
I think that it it will be great to have a more modern splash screen cause the actually one is a bit old and big

**Describe the solution you'd like**
![New splash screen.png](https://user-images.githubusercontent.com/56766778/97406432-4866dc00-190a-11eb-92ba-c566a1c228a2.png)

**Comment by yashraj-iitr** [comment]
If the issue is still up for grab then I would love to work on this issue.

**Comment by Mitia99** [comment]
I noticed that there is no more splash screen in ver 3.4.2 so i'll close this issue.
