### ISSUE TITLE
KiwixPrefsFragment is leaking

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2469]
**Describe the bug**
KiwixPrefsFrament is leaking if we open Settings.

**Expected behavior**
There shouldn't be this leak on KiwixPresFragment.

**Steps to reproduce the behavior:**
1. Open Application
2. Go to the Settings
3. Go back to home Fragment

**Screenshots**
<img width="359" alt="Screenshot 2020-11-02 at 4 32 12 PM" src="https://user-images.githubusercontent.com/43576162/97860928-f7e7e800-1d28-11eb-9c0c-d50a1753a2e8.png">

**Environment**
- Version of Kiwix Android : develop
- Device: Google Pixel
- OS version: 10

**Comment by kelson42** [comment]
@gouri-panda Thank you for for reporting/working on this issue. Memory leaks is really something we should make an effort to fix them.

**Comment by gouri-panda** [comment]
@kelson42 thank you!
