### ISSUE TITLE
Interface translation problem

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#247]
When downloading content there is now a time indicator that says "x minutes left". For some reason the French interface translates it as "left-hand" (I did not see the issue in es/de/it/zh).

![screenshot gutenberg](https://user-images.githubusercontent.com/21675885/29610000-2e362cdc-87f9-11e7-99b4-679843d62574.png)

**Comment by tbertels** [comment]
[Kelson fixed this on August 2017](https://translatewiki.net/w/i.php?title=Kiwix:Android.ui.time_left/fr&action=history) so this can be closed.

**Comment by kelson42** [comment]
@tbertels yes, thx, the problem is a lack of documentation on translatewiki... did not have had the time to documented that properly

**Comment by kelson42** [comment]
Finally just updated the doc https://translatewiki.net/wiki/Kiwix:Android.ui.time_left/qqq
