### ISSUE TITLE
Convert OnSwipeTouchListener to kotlin

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2474]
**Is your feature request related to a problem? Please describe.**
Convert CoreReaderFragment to Kotlin.
Splits from #1826

**Comment by s-ayush2903** [comment]
Most probably a duplicate.
Mentions #2400 
Mentions #2451

**Comment by gouri-panda** [comment]
Sorry, I thought it was another class. Thank you @s-ayush2903 .
