### ISSUE TITLE
History and Bookmark are not showing the correct title

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2475]
**Describe the bug**
On History and Bookmark the title is Kiwix

**Expected behavior**
The screens should be appropriately titled

**Comment by gouri-panda** [comment]
@macgills I can't reproduce this issue. Can you tell me how to find this bug?

**Comment by s-ayush2903** [comment]
Open the Bookmarks screen from sideNav and look at the toolbar, that'd suffice.

**Comment by gouri-panda** [comment]
D'oh, I thought about web page titles. Thanks!

**Comment by gouri-panda** [comment]
@kelson42 Should we hotfix this now or wait for newcomers?

**Comment by macgills** [comment]
It isn't urgent? It would be nice to fix though. New contributors are also difficult to predict, though we are coming to a period of colleges closing for the season which could lead to an uptick? Depends what yourselves want to work on and if ye have enough on your plate at the minute

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Can I work on this issue, I am new to open-source and looking forward for opportunities to contribute

**Comment by gouri-panda** [comment]
@AmeyaPhadnis-2019H1030012G sure! please go ahead. Let us know your progress!

**Comment by kelson42** [comment]
This is definitly a regression, should be easy to fix by looking at older revision.

**Comment by gouri-panda** [comment]
@AmeyaPhadnis-2019H1030012G How is your progress?

**Comment by macgills** [comment]
the fix is quite simple, I had a look to the file and misuse of a scope function means an variable outside the scope is not being used where it should be on account of it  being shadowed by a property in scope.

**Comment by gouri-panda** [comment]
since there is no feedback from @AmeyaPhadnis-2019H1030012G . I am taking this.
