### ISSUE TITLE
Investigate nightly  issue on API 27

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2488]
**Describe the bug**
The nightly instrumentation tests have been failing consistently on API 27
```
--------- beginning of crash
11-11 00:21:38.544  3640  3640 E AndroidRuntime: FATAL EXCEPTION: main
11-11 00:21:38.544  3640  3640 E AndroidRuntime: Process: org.kiwix.kiwixmobile, PID: 3640
11-11 00:21:38.544  3640  3640 E AndroidRuntime: kotlin.TypeCastException: null cannot be cast to non-null type android.net.wifi.p2p.WifiP2pManager
11-11 00:21:38.544  3640  3640 E AndroidRuntime: 	at org.kiwix.kiwixmobile.localFileTransfer.WifiDirectManager.startWifiDirectManager(WifiDirectManager.kt:108)
11-11 00:21:38.544  3640  3640 E AndroidRuntime: 	at org.kiwix.kiwixmobile.localFileTransfer.LocalFileTransferFragment.onViewCreated(LocalFileTransferFragment.kt:124)
```

**Expected behavior**
test should stop crashing

**Comment by s-ayush2903** [comment]
Feels like this is causing the crash
|Maybe error prone|
|--|
|![danger](https://user-images.githubusercontent.com/56556919/99014757-5e66d480-2579-11eb-99aa-049da0066291.png)|

Writing it in null-safe format may fix the issue.

**Comment by gouri-panda** [comment]
>manager =activity.getSystemService(Context.WIFI_P2P_SERVICE) as WifiP2pManager

@s-ayush2903 I think crash is happening here. Here manager gets null.

**Comment by s-ayush2903** [comment]
Ah the stupid me. Thanks for helping though.
