### ISSUE TITLE
UI language change of Kiwix for Android UI should apply to HTML render widget language

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#25]
_From @kelson42 on January 17, 2017 18:47_

Like this we should be able, if the ZIM file is correctly configured, to adapt the content, depending of UI language. This is  in particular needed for the Phets custom app.

_Copied from original issue: kiwix/kiwix#444_

**Comment by kelson42** [comment]
@mhutti1 Does that make sense to you?

**Comment by kelson42** [comment]
_From @mhutti1 on January 17, 2017 18:49_

@kelson42 How would the alternative languages be stored in the ZIM file?

**Comment by kelson42** [comment]
@mhutti1 All languages are stored (maybe partly with json files, ...) in the ZIM, javascript (in the ZIM HTML content) would do the rest.

**Comment by kelson42** [comment]
_From @mhutti1 on January 17, 2017 22:36_

@kelson42 So we can call javascript functions or use different urls. Ideally if we use java-script though text shouldn't be displayed until the app tells it which language to use to avoid flickering,

**Comment by mhutti1** [comment]
I'm closing this. If specific implementations are required make a new ticket with the details.

**Comment by kelson42** [comment]
@mhutti1 Sorry I have to reopen this ticket. We need basically a way, using the javascript in the ZIM file, to know the Kiwix UI language. Does such a way exists? If yes can we use "navigator.language" https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language ?

**Comment by mhutti1** [comment]
Use ``navigator.userAgent``
