### ISSUE TITLE
NestedCoordinatorLayout is leaking

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2501]
**Describe the bug**
NestedCoorinatorLayout is leaking

**Expected behavior**
Memory leak shouldn't happen

**Steps to reproduce the behavior:**
* Open Library Fragment
* Tap the share button on the upper right corner
* Search the wifi
* Go back until you reach the home screen

**Screenshots**
<img width="313" alt="Screenshot 2020-11-17 at 4 47 24 PM" src="https://user-images.githubusercontent.com/43576162/99383891-94e37d00-28f4-11eb-86fd-413af9557be4.png">

**Environment**
- Version of Kiwix Android : 3.4
- Device : realme ,pixel
- OS version : 10

**Comment by s-ayush2903** [comment]
@gouri-panda What do you think if we have a parent issue for memory leaks as well from where we can further reference all the memory leak issues? I mean quite similar to that of what we have for converting Java files to kotlin, doing so will help keeping track of leaks fixed. Thoughts?

**Comment by macgills** [comment]
I am fine with an issue per leak, the kotlin conversion task was just a way of allowing autonomous work by new contributors.

**Comment by gouri-panda** [comment]
yes, that's a fantastic idea! I leave it to @macgills @kelson42

**Comment by s-ayush2903** [comment]
Okay, I meant a big issue and creating minor issues like "this part is leaking" and referencing the major issue in the smaller ones, just an idea, nothing else

**Comment by macgills** [comment]
We don't want an eternal task ever, ideally we eventually get this repo down to 0 open issues. We should only go multi ticket when we are decomposing a very large yet finite task and even then tags are probably a better mechanism to achieve this. When a leak is detected we should create a ticket to fix that leak and I don't particularly see the benefit of having a history of our leaks fixed referenceable via a ticket. Like we don't have a "fix bugs" ticket. Hopefully this gives an insight into general ticket philosophy at kiwix

**Comment by s-ayush2903** [comment]
Now this makes it as clear as today's sky.

**Comment by gouri-panda** [comment]
@macgills I can't reproduce this and #2502 in the recent develop branch. should we close this?

**Comment by macgills** [comment]
Close 'em
