### ISSUE TITLE
Kiwix app doesn't launch

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2509]
**Describe the bug**
I was using the application. After some time it didn't launch even after clearing the cache.

**Expected behavior**
The application should be launch.

**Steps to reproduce the behavior:**
Don't know

**Environment**
- Version of Kiwix Android : develop
- Device : realme
- OS version : 10

**Logs**
I hope [this](https://drive.google.com/file/d/150EfFo_j3-SIhYlJROtUhK75vaqEiATl/view) will help.

**Comment by macgills** [comment]
This sounds like a development issue not an app issue, you should be able to see a clear cause in logcat

**Comment by gouri-panda** [comment]
@macgills unfortuantely I wasn't debugging this time. I am not sure what was causing that issue.I'm still confused about this issue. It's up to you now for closing this issue ;)

**Comment by macgills** [comment]
If it is throwing an exception at startup this crash would be visible if you just connected to a computer and had android studio running, debugging is not necessary. I will close this as it is at the moment unactionable, if you discover a bug and have a trace we can reopen/rewrite this ticket or just make a new one
