### ISSUE TITLE
Pressing back from Bookmarks/History always goes to Library

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2514]
**Describe the bug**
When navigating back from bookmarks/history you don't arrive at Reader/Downloads if you navigated from there

**Expected behavior**
Pressing back should return you to where you were previously

**Steps to reproduce the behavior:**
1. Click Reader
1. Navigate to Bookmarks
1. Press back
1. See you are on Library

**Comment by s-ayush2903** [comment]
I would like to work on this issue
