### ISSUE TITLE
Messages displayed should be consistent

### ISSUE THREAD

**Issue by rutvik-panchal** [kiwix/kiwix-android#2515]
**Describe the bug**

The message's displayed on open books and no files in downloads is not consistent.

**Expected behavior**

The message's displayed should be consistent in terms of their placement, typography and spacing.

**Steps to reproduce the behavior:**

Close and delete all the books

**Screenshots**

<img width="50%" src= "https://user-images.githubusercontent.com/39809059/99834092-0a677b80-2b89-11eb-83c0-5b3f176bcd39.jpg">

**Environment**
- Version of Kiwix Android : 3.4.1
- Device : Vivo V17
- OS version : Android 10

**Logs**

NA

**Comment by rutvik-panchal** [comment]
@macgills I would like to work on this issue.

**Comment by macgills** [comment]
You are assigned, looking forward to a PR
