### ISSUE TITLE
Target Android 11 before November 2021

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2516]
**Is your feature request related to a problem? Please describe.**
To continue to update kiwix we will have to target Android 11 and consequently SAF. https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html

**Comment by kelson42** [comment]
@gouri-panda I don't remember in details our discussion on this. Would you be able please to put an update comment here about what has been done and what could/should be done?

**Comment by gouri-panda** [comment]
@kelson42 Google Play will require new apps to use the Android App Bundle publishing format. This brings the benefits of smaller apps and simpler releases to more users and developers.
* Publish with the Android App Bundle format.
* Target API level 30 (Android 11) or above

**Comment by kelson42** [comment]
@gouri-panda How much work is needed for each item and what are the (bad) consequences to expect (for the bundle in particular)? Does that impact the release process for Kiwix Android? For the custom apps?

**Comment by gouri-panda** [comment]
>How much work is needed for each item

Well, I covered most of the work in that following PR. If Issac or Abdul are free to review, then they can give feedback
> what are the (bad) consequences to expect (for the bundle in particular)?

This is my first experience with Bundle. So I don't think I can give my opinion. But in my experience, the play store just won't update to the latest version. 
> Does that impact the release process for Kiwix Android?

Here is the official timeline 

<img width="740" alt="Screen Shot 2021-06-17 at 21 42 19" src="https://user-images.githubusercontent.com/43576162/122434833-4ced0d00-cf4c-11eb-9ba6-3de5e735486a.png">

>For the custom apps?

We just change the ci of `kiwix-android-custom` that we will do here(`kiwix-android`).

**Comment by kelson42** [comment]
> > How much work is needed for each item
> 
> Well, I covered most of the work in that following PR. If Issac or Abdul are free to review, then they can give feedback

Which PR are we talking about, no PR is linked here to this ticket!
 
> > what are the (bad) consequences to expect (for the bundle in particular)?
> 
> This is my first experience with Bundle. So I don't think I can give my opinion. But in my experience, the play store just won't update to the latest version.
> 
> > Does that impact the release process for Kiwix Android?
> 
> Here is the official timeline
> 
> <img alt="Screen Shot 2021-06-17 at 21 42 19" width="740" src="https://user-images.githubusercontent.com/43576162/122434833-4ced0d00-cf4c-11eb-9ba6-3de5e735486a.png">
> 
> > For the custom apps?
> 
> We just change the ci of `kiwix-android-custom` that we will do here(`kiwix-android`).

OK, so lets try to do that quickly then. Thx!

**Comment by gouri-panda** [comment]
>Which PR are we talking about, no PR is linked here to this ticket!

#2660 
>OK, so lets try to do that quickly then. Thx!

👍
