### ISSUE TITLE
ServiceWorker does not support opening epubs/pdfs in external apps

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2518]
**Describe the bug**
Our service worker client needs to share the capability to open epubs/pdfs that already exists in our WebViewClient

**Expected behavior**
Click a pdf/epub link in bouquineux and have it open in an external application

**Comment by s-ayush2903** [comment]
I would like to work on this issue, but is the issue concerned about the SW zims only, means we can implement the fix and test on any other SW zim like [this](https://download.kiwix.org/zim/stack_exchange/3dprinting.stackexchange.com_en_all_2020-04.zim), right? or correct me if I'm wrong at any point

**Comment by macgills** [comment]
3d printing isn't a service worker zim, `boquineau` which I might not be spelling correctly is 1.

**Comment by macgills** [comment]
The current epub/pdf handling isn't quite working but we at least get a toast saying "can't open this in an application"

This could prove quite challenging to extract common functionality, just as a warning

**Comment by s-ayush2903** [comment]
Okay, so without downloading how can we verify if one is a sw zim?

**Comment by macgills** [comment]
We cannot, it is extrinsic knowledg4e
