### ISSUE TITLE
Logging (quantity and quality)

### ISSUE THREAD

**Issue by ISNIT0** [kiwix/kiwix-android#252]
Having read:
https://www.javacodegeeks.com/2011/01/10-tips-proper-application-logging.html

@julianharty and I have been discussing what makes logging good/bad. This is based on:

- Quality of the message (appropriate tag/type, contents, contextual information, ease of understanding)
- Quantity/Location of Logs (near troublesome code, spread across the project)

I've generated a report about our logging at present:
[Kiwix.pdf](https://github.com/kiwix/kiwix-android/files/1251940/Kiwix.pdf)

Log Tag Naming Convention?
What do people think about "kiwix-{className}" or "kiwix-{fileName}"

**Comment by julianharty** [comment]
Added logging of the OkHttp requests and responses https://github.com/kiwix/kiwix-android/commit/86f0da12c633400a87d40899b38bc7d7576d8271

**Comment by kelson42** [comment]
@mhutti1 @macgills Do you have an idea how we could deal with that ticket?

**Comment by macgills** [comment]
As part of #1270 I was looking to make a centralised logging class so we can have greater control over app logging and can comply with the conditional logging easily

**Comment by kelson42** [comment]
Pretty much a duplicate of #1270. A ticket with such a formulation is as well pretty hard to implement.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Very old ticket I just have assigned tomyou. Not sure about this pertinence. What can you propose?

**Comment by kelson42** [comment]
OK, so basicaly no clear actionable. Closing.
