### ISSUE TITLE
Kiwix uses mobile data without asking

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2520]
Steps:
* Mobile only with data / no WIFI
* Install Kiiwx
* Go to library download tab

You get
* You see the content of the catalogue available for download

You should get:
* A dialog inviting to deactivate "Download content only via Wifi"

Remark:
I believe there is/was something unclear around catalogue/content. The feature "Download content only via WiFi" seems to work fine for downloading ZIM files. But the catalogue itself makes 20MB and is (I guessed) refreshed automatically time to time (every few days). As a consequence the data consumption is to high to be acceptable without informing the user.

Solution?
I propose to handle the catalogue download like the content (at least as long as we don't use the OPDS feed).

**Comment by macgills** [comment]
The current logic behind requesting the library is
"When our request stream emits and our internet connection stream emits CONNECTED then perform a library GET" Note: after both of these streams emit then an emission of either will cause a fetch.

The "request stream" starts with a request loaded in the chamber so upon creation of our ViewModel (if we are connnected to the internet) a fetch occurs. This ViewModel is created once per app instance, upon arrival to one of our top level destination screens ie, if you can see the bottom navigation bar.
Users can push a fresh request onto the request stream by swiping to refresh.

If you want to add cache control to this request then that may be a separate ticket.  May entail separating out our okHTTP clients as we don't want to try and cache downloads... not that they'd fit in the cache anyway... maybe some would. Perhaps we even integrate with Workmanager to schedule a job to update the library when the device is plugged in and connected to wifi.

The intention here is to reuse the dialog
```
Allow downloading content via mobile network?
If you choose “Yes” you won\'t be warned in future. However, you can always change this in Settings
```
?
The choice from this dialog extends to downloading zims too? ie `The feature "Download content only via WiFi"` is a monolith with no granularity?

**Comment by macgills** [comment]
My only concern over the dialog is that since the request is performed in the background right now the user will be prompted upon the launch of the top level destinations without them having performed an action so it may seem disconnected with their flow, like we are posing a more general question they don't have context for

**Comment by kelson42** [comment]
@macgills Why not asking at the first start? And make the background loading conditional?

**Comment by macgills** [comment]
> the user will be prompted upon the launch of the top level destinations without them having performed an action

This mostly, it is disconnected from the user doing anything explicitly. I was just highlighting the mild concern, if we are fine with it just popping up then it can be implemented

**Comment by kelson42** [comment]
@macgills Good to me, maybe the workding need to be revamped to better match the new workflow. Thx.
