### ISSUE TITLE
Improper display of wikitables

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2522]
Not entirely sure if this is a mwoffliner or android issue, but here we go:  
https://library.kiwix.org/wikiversity_en_all_maxi_2020-10 looks fine on Kiwix-serve, but there is a serious display issue on the android landing page (and presumably elsewhere):
![wikiversity](https://user-images.githubusercontent.com/21675885/100068349-b1713f00-2e37-11eb-8b41-9f90e178504e.jpg)
![image](https://user-images.githubusercontent.com/21675885/100069045-918e4b00-2e38-11eb-9d9d-07e7eacc1d3f.png)

**Comment by kelson42** [comment]
I believe this is a problem with mwoffliner
