### ISSUE TITLE
Wikimed AR app start interface not work well 

### ISSUE THREAD

**Issue by alanajjar** [kiwix/kiwix-android#2534]
Hello,

When start Wikimed AR app this interface appear for few seconds  

Wikimed AR app
![Screenshot_2020-12-02-17-14-24](https://user-images.githubusercontent.com/20701355/100894014-ad42c280-34c4-11eb-8c32-22fac74f6191.png)

Wikimed EN app
![Screenshot_2020-12-02-17-26-30](https://user-images.githubusercontent.com/20701355/100893947-9603d500-34c4-11eb-9127-aa9a8572bd81.png)

**Comment by kelson42** [comment]
It is importan to notice that Wikimed EN has been build on 3.4.1 base and Wikimed AR on 3.4.2.

**Comment by kelson42** [comment]
In my case with my Pixel2 (android 10) the Splash logo is small (too small) so not stretched.

**Comment by alanajjar** [comment]
> In my case with my Pixel2 (android 10) the Splash logo is small (too small) so not stretched.
Above screenshot based on Android 5.1 on HTC desire 728

**Comment by kelson42** [comment]
@s-ayush2903 @gouri-panda Hi, does one of you would volunteer to quickly fix this one? This is really an ugly first user experience for custom app users... and it sounds to be a silly bug.

**Comment by gouri-panda** [comment]
@kelson42 sure!
