### ISSUE TITLE
History and Notes tabs still untranslated on Wikimed AR app 

### ISSUE THREAD

**Issue by alanajjar** [kiwix/kiwix-android#2535]
Hello,

History and Notes tabs on settings still untranslated on Wikimed AR app.

History already translated here https://translatewiki.net/wiki/Kiwix:Android.ui.history/ar 
But I can't find "Notes" Kiwix Android on translatewiki.net
https://translatewiki.net/w/i.php?title=Special:Translate&group=kiwix-android-strings&language=ar&filter=translated&optional=1&action=translate 

![Screenshot_2020-12-02-17-15-19](https://user-images.githubusercontent.com/20701355/100894766-82a53980-34c5-11eb-9c1c-aaf90e79edca.png)

**Comment by kelson42** [comment]
This is a problem (lag) of sync. with Translatewiki or are these strings not translatable?

**Comment by macgills** [comment]
These strings are hardcoded in the preferences file, simple update needed

**Comment by s-ayush2903** [comment]
Sounds to be a quick fix, should I push the changes needed?

**Comment by macgills** [comment]
please do
