### ISSUE TITLE
Tab restoration for multiple tabs not working

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2540]
**Describe the bug**
Open 2 tabs on Reader, switch top level destination and switch back. 1 tab loads correctly but if you switch to the other it is stuck on the uninitialiser page. Potentially all that needs to be done is init the Uninitialiser interface on this tab but I think this will just load the main page so the unitialiser will need to store the target url and navigate to it after uninitialising of service workers complete

**Comment by kelson42** [comment]
@macgills This is a regression from 3.4.1?

**Comment by macgills** [comment]
I would have to doublecheck but I would think so

**Comment by macgills** [comment]
This is an issue on 3.4.1 too

**Comment by macgills** [comment]
closing as dupe of ##2545 same underlying cause
