### ISSUE TITLE
New Tabs & recreation is loading home page on other tabs

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2545]
**Describe the bug**
Original report:

>now I see that also when I create new tabs or minimize, it takes any other tab and takes it to the “Welcome” page. It also takes away their thumbnails.

**Expected behavior**
A tab should maintain its url 

**Environment**
- Version of Kiwix Android : 3.4.1

**Comment by macgills** [comment]
I attempted a solution using `restoreState` `saveState` so we can maintain the WebBackForwardList across Reader instances but this didn't bear fruit for me. It will however be necessary if we want to allow users to mainatain a tab's navigation stack. The alternative is a database and we entirely ignore the Webview's opinion on whether it can go back or not

**Comment by macgills** [comment]
NB: the currently linked PR does not restore the history of a tab, it just loads the most recent url of a tab, ie pressing back will close reader regardless of how deeply nested the url was in the tab history pre-restoration

**Comment by s-ayush2903** [comment]
Mentions #2581(to keep in light not to hamper/modify the _article position_ restoring algorithm) and 

>  the currently linked PR does not restore the history of a tab,

is tracked in #2582.

Closing, as the issue has been fixed by the linked PR(merged) and a good to have feature is now being tracked in the ticket aforementioned(i.e., #2582 )
