### ISSUE TITLE
Back Press from Find In Page goes to library

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2546]
**Describe the bug**
Original report:

>when we have opened several articles using the same tab, and we touch “search on the page”, after the search if we touch “back arrow” (bottom button of android), kiwix does not take us to the previous articles but to the tab “Library”; It is very uncomfortable.

**Expected behavior**
A back press should take you to the screen you were previously on.

**Environment**
- Version of Kiwix Android : 3.4.1

**Comment by macgills** [comment]
I am not entirely sure on the nature of this bug but have taken an educated guess? This could be about navigation after clicking a link during "find in page" or the user expects a back press to navigate to the previous entry of find in page? May have to investigate how chrome handles find in page  if we are to make that behaviour change.

**Comment by macgills** [comment]
Ah, I've got it. Tab restoration (which is what happens when we navigate to Reader from Search) does not preserve the history of the webview

**Comment by gouri-panda** [comment]
Can I take this issue?

**Comment by kelson42** [comment]
@gouri Yes, would be great.

**Comment by kelson42** [comment]
@gouri-panda Have you been able to reproduce the issue? Is that the same rootcuase as #2582?

**Comment by gouri-panda** [comment]
@kelson42 Yes I'm able to reproduce this issue. If we search a word then open a link it goes to another page but if we go back then it returns to the library fragment, the navigation state doesn't restored. 
> Is that the same rootcuase as #2582?
I'll dig deep that issue also to find out what's happening.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz I can't reproduce the issue either. So far nobody complains about this.

**Comment by kelson42** [comment]
Should we close ot?
