### ISSUE TITLE
Improve content search usability in library

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#255]
Kiwix for Android provides the list of contents available for download in the "Library". The library provides a simple but important search box on the top. This search box allows the user to search for content selections from an online library. This search engine gives results based on library details.

So far so good. Currently the feature can behave strangely with the language filtering feature (available in the top right corner). This language filtering only displays the content in a configurable list of language. The counter-intuitive part is that:
* If you do not search anything, the list displays all contents in the preselected language(s)
* But if you make a search, then it searches in all contents in all languages

This makes searches pretty difficult if you have common words because of the large amount of results. Try to search "Wikimed" in a specific language for example... Not easy.

We need therefore to change a bit the way how the search feature behaves.

The solution we have in mind is to still display all contents (matching the search pattern) but to put them in two groups:
* First "in your language(s)" would list the contents in the configured languages
* Then "in all languages" would display all the other contents

**Comment by mhutti1** [comment]
Fixed by https://github.com/kiwix/kiwix-android/pull/307
