### ISSUE TITLE
Zimit-generated zim files partly fail to open

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2561]
Steps to reproduce: 

1. generate zim file via https://youzim.it
2. Download onto android
3. Open.

I would say it takes a solid 7-10 seconds to open on kiwix-android 3.4.3 (Huawei p20 lite, Android 9). Generally speaking I find that opening files on 3.4.3 is significantly longer than before.

**Comment by kelson42** [comment]
Before means with 3.4.1 I guess.

**Comment by kelson42** [comment]
@Popolechien any feedback?

**Comment by Popolechien** [comment]
@kelson Yup though it is not systematic - testing on Kiwix-android 3.7.1 I can open [bibnum](https://library.kiwix.org/viewer#bibnum_fr_all_2021-12/A/journals.openedition.org/bibnum/), but not [athena](https://library.kiwix.org/viewer#athena_fr_all_2023-05/A/athena.unige.ch/athena/) nor [CoopMaths](https://library.kiwix.org/viewer#coopmaths_2023-04/A/coopmaths.fr/)

**Comment by kelson42** [comment]
@Popolechien OK but you understand your comment does to match what your reported first! First you reported "it is (always) slow to open a zimit file" and now you write "it does work (fine?) but only for part of them (zimit files), the other don't work at all!". I understand properly?

**Comment by Popolechien** [comment]
@kelson42 Yes I understand. If anything I'd say this has become worse. I cannot reproduce the initial step in the ticket as we cannot download files from youzim.it anymore onto android (until 3.8 at least), so that's the closest we can get.

Happy to rename the ticket if you think it's more appropriate.

**Comment by MohitMaliFtechiz** [comment]
@kelson42, @Popolechien I confirm with 3.7.1 we are unable to read [athena](https://library.kiwix.org/viewer#athena_fr_all_2023-05/A/athena.unige.ch/athena/) , [CoopMaths](https://library.kiwix.org/viewer#coopmaths_2023-04/A/coopmaths.fr/). Yesterday we merged #3216 so I have tested with the develop branch and we are able to read these files, but I have seen a strange behavior sometimes it is unable to read these zim files when we frequently switch to `Zimit` zim files e.g. if currently CoopMaths is opened and I open Athena and again open the Coopmaths then this error happened. This error is only happening with Zimit files.

@kelson42 I am debugging this error and will place a fix for it.


https://github.com/kiwix/kiwix-android/assets/34593983/7c0df3eb-3df0-4f87-9a38-474331605628
