### ISSUE TITLE
Some Wikipedia zim files can't be downloaded (3.4.3)

### ISSUE THREAD

**Issue by asereze** [kiwix/kiwix-android#2563]
**Describe the bug**
If I go to the "Download" section and I click on some Wikipedia file (with images or without them) nothing happens. The download doesn't start. I don't get that same problem with other downloadable files (TED talks, Project Gutenberg archives, MathOverflow and so on). It seems like it only happens with offline Wikipedia versions ans selections of articles from Wikipedia (ex. the Bollywood one). 

Not all versions of Wikipedia are affected, for some reason. I can download the **Mirandese**, the **Javanese**, **Volapük**, **Macedonian**, **Nepalese**, **Portuguese**, **Khmer**, **Sranan Tongo** and **Urdu** files without issues, and there are probably more that are working fine (I didn't check them all). But, for example, I can't download the **Sardinian**, **Estonian**, **Venetian**, **Napoletano**, **Irish**, **Belarusian**, **Azerbaijani**, **Dutch**, **Low German**, **Hindi** or **Lithuanian** ones.

**Environment**
- Version of Kiwix Android : 3.4.3
- Device : Xiaomi Redmi Note 4X
- OS version : LineageOS 16.0 (Android 9)

**Comment by kelson42** [comment]
We have currently problems with the platform. Therefore it happens sporadically that contents are not downloadable. Would you be able please to check again?

**Comment by kelson42** [comment]
@asereze I believe most of the platform problem has been fixed meanwhile. Would you be able please to test again and tell us if you are still impacted?

**Comment by kelson42** [comment]
Please reopen ticket if the download still fails.

**Comment by asereze** [comment]
> @asereze I believe most of the platform problem has been fixed meanwhile. Would you be able please to test again and tell us if you are still impacted?
Yes, it works now! Thank you!
