### ISSUE TITLE
Can't find "in-page terms in collapsed index"

### ISSUE THREAD

**Issue by Mitia99** [kiwix/kiwix-android#2565]
**Describe the bug**
The issue is that I can't find in-page terms in collapsed index.

**Expected behavior**
Display in-page search results even if they are in collapsed index

**Steps to reproduce the behavior:**
1.Download Encyclopédie médicale Wikimed (french library)
2.Search "Liste d'abréviations en médecine"
3. Search a random word in collapsed index:e.g from screenshot is "adénine"
4. Can't find the term
-->

**Screenshots**
![IMG_20201226_130243.png](https://user-images.githubusercontent.com/56766778/103149536-92cdd300-476a-11eb-8370-4592d468e61f.png)

**Environment**
- Version of Kiwix Android : 3.4.3
- Device : Huawei P30 ELE-L09
- OS version : Android 10

**Comment by gouri-panda** [comment]
Duplicate #863
