### ISSUE TITLE
Layout problem in Diagnostic Report

### ISSUE THREAD

**Issue by franklinbill** [kiwix/kiwix-android#2566]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the Diagnostic Report page, the button and the following text overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is 3.4.1, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
<img width="470" alt="bug-kiwixmodile-2" src="https://user-images.githubusercontent.com/18572115/103194449-b0419f00-491a-11eb-9dfa-8cc9e61e3a2d.png">

**Expected behavior**

I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.

**Steps to reproduce the behavior:**
1.  use the largest font and display
2. click Diagnostic Report page
3. see error

**Screenshots**

<img width="470" alt="bug-kiwixmodile-2" src="https://user-images.githubusercontent.com/18572115/103194603-1e866180-491b-11eb-8c56-b2e0f9e52683.png">

**Environment**
- Version of Kiwix Android : 3.4.1
- Device : Google nexus 6,
- OS version : Android 8.0

**Logs**

**Comment by shabar-shab** [comment]
@macgills can I work on this

**Comment by franklinbill** [comment]
Thank you very much！

**Comment by jhbiggs** [comment]
Hi @kelson42, may I work on this one?

**Comment by kelson42** [comment]
@jhbiggs Yes, and welcome back.

**Comment by jhbiggs** [comment]
Thank you!
