### ISSUE TITLE
In SearchFragment When we click search(enter)  button in keyboard it should search the words

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2573]
**Is your feature request related to a problem? Please describe.*
 If we type a word then click keyboard's search(enter) button then it just hides the keyboard. It's not a good user experience.
**Describe the solution you'd like**
It should be better if we add `findInPage` functionality after clicking the search button.

**Comment by gouri-panda** [comment]
@kelson42 @mhutti1 Any thoughts?

**Comment by kelson42** [comment]
> It should be better if we add `findInPage` functionality after clicking the search button.

I don't think this is better. There is no way to just remove the "magnify glass" button? The only way out should be:
* Click on "Find in Page"
* Click on one of the suggestions

There should not be other way out, right?

**Comment by gouri-panda** [comment]
@kelson42 What I meant was It should be better if we also add functionality of find in page in magnify search button of keyboard.

**Comment by kelson42** [comment]
@gouri-panda I got that, but I'm against because this is super not intuitive and confusing for the user. It looks like the current behaviour is the proper one. This is the same on iOS. Nobody has ever complained about that.

**Comment by kelson42** [comment]
One time fulltext search will be implemented, see #1324, then this button should maybe lead to it.
