### ISSUE TITLE
Can't download files larger than 4GB on my Nvidia Shield Tablet.

### ISSUE THREAD

**Issue by CorallusCaninus** [kiwix/kiwix-android#2594]
When I try to download any file larger than 4 GB in the download section, a notice pops up telling me that the filesystem doesn't support files larger than 4 GB. I have formatted the sdcard with exFAT and another time with NTFS, but I am unable to download the files.
The kiwix version that I use is the latest one available on Google Play Store Version 3.4.3.
Do you have any solutions?

Thanks in advance.

**Comment by kelson42** [comment]
In the help, you have a diagnostic tool which generates a a `.txt` file. Would you be able to copy the content of that file here?

**Comment by CorallusCaninus** [comment]
Hi kelson42,

here is my log file. Is there any website where I can download the wikipedia version that I can't download via the download manager in kiwix, in the case I want to download the file on my pc and transfer them to the tablet?
[logcat.txt](https://github.com/kiwix/kiwix-android/files/6056738/logcat.txt)

**Comment by s-ayush2903** [comment]
>  Is there any website where I can download the wikipedia version that I can't download via the download manager in kiwix

@CorallusCaninus [download.kiwix.org/zim](https://download.kiwix.org/zim), it's not so responsive so, you'll have to dig deep into the website and find the file that you're interested in.

**Comment by kelson42** [comment]
@MohitMaliFtechiz What’s up with this ticket?

**Comment by gouri-panda** [comment]
@kelson42 Looking at the Log file, the error happened because of unable to find mime type. We recently fix that bug in #2809 . Hopefully it can fix that.

**Comment by MohitMaliFtechiz** [comment]
hi ,
The maximum possible size for a file on a FAT32 volume is 4 GB minus 1 byte or 4,294,967,295 bytes, SD memory in your phone is formatted as FAT32 so you limited to have files smaller than 4GB in your phone. 

here are some useful link
https://forum.xda-developers.com/t/bypassing-4gb-filesize-limit-of-micro-sd-card.3799843/#:~:text=By%20default%2C%20if%20you%20format,file%20size%20limit%20of%204GB.

https://android.stackexchange.com/questions/41015/download-bigger-than-4-gb-file-on-android-4-0-4

**Comment by kelson42** [comment]
@MohitMaliFtechiz I guess your analysis is based on the logcat?

**Comment by kelson42** [comment]
@MohitMaliFtechiz @gouri-panda  It seems to me the case is explained and there is nothing more we can do right?

**Comment by MohitMaliFtechiz** [comment]
Yes @kelson42 ,

We can do anything since its fat32 behaviour that can't download more then 4 gb file.

**Comment by CorallusCaninus** [comment]
Hi, the SD card is formatted using NTFS. The problem has been solved for me using the latest version of Kiwix.
