### ISSUE TITLE
Back Press doesn't work in SearchFragement

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2601]
**Describe the bug**
The back button doesn't work(stuck) while Searching

**Expected behavior**
It should go where it comes from.

**Steps to reproduce the behavior:**
1. Open the Kiwix app
2. Select a word
3. Press Search Kiwix
4. Press Back Button

**Environment**
- Version of Kiwix Android: 3.4.3
- Device: Realme
- OS version: 10

**Comment by gouri-panda** [comment]
Also, the search doesn't work either.

**Comment by kelson42** [comment]
@gouri-panda I guess you plan to fix this?

**Comment by gouri-panda** [comment]
Sure!

**Comment by yyprince334** [comment]
I want to contribute on it.

**Comment by gouri-panda** [comment]
Hi @yyprince334! This ticket's PR is on the way! You can search the issue i.e not assigned or inactive for a while ;)
