### ISSUE TITLE
Clicking the search result doesn't go anywhere

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2603]
**Describe the bug**
If we search through the search field and click the search result then the search result doesn't open the link

**Expected behavior**
 Search Text should appear in the SearchEditText
**Steps to reproduce the behavior:**
1. Open the Kiwix app
2. Select a word
3. Press Search Kiwix
4. Type a text to search
5. Click the link

**Environment**
- Version of Kiwix Android: 3.4.3
- Device: Realme
- OS version: 10

**Comment by kelson42** [comment]
Seems to be almost the same of what I reported #2580. I hardly understand how such a bug can appear and land in master unoticed!

**Comment by gouri-panda** [comment]
@kelson It works fine if we search normally but if we search through `Search kiwix` then this problem happens. plus #2580 and this problem's behavior aren't the same. I'll dig deep into this.
