### ISSUE TITLE
Moving kiwix-android off from JCenter

### ISSUE THREAD

**Issue by 4shutosh** [kiwix/kiwix-android#2609]
**Jfrog to Shut down JCenter and Bintray** see this [article](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

For anyone who is unfamiliar with JCenter, it is a public repository hosted at Bintray that is free to use for open source library publishers. It is the largest repository in the world for Java and Android OSS libraries, packages, and components.

JCenter is turning down over the next 12 months. Here is the timeline for the shutdown process.
![image](https://user-images.githubusercontent.com/53831987/111284661-570a2180-8666-11eb-8d74-e375d92cb2ff.png)

As of now following are the **packages in our app** that would be affected due to JCenter
- androidx.tonyodev.fetch2okhttp:xfetch2okhttp:3.1.6
- com.yahoo.squidb:squidb:2.0.0
- com.yahoo.squidb:squidb-annotations:2.0.0
- com.pacioianu.david:ink-page-indicator:1.3.0
- io.objectbox:objectbox-java:2.8.1
- io.objectbox:objectbox-kotlin:2.8.1
- io.objectbox:objectbox-android:2.8.1
- org.kiwix.kiwixlib:kiwixlib:9.4.1

**What are we required to do?**
1. Track the above-mentioned packages, when moved to other hosts, will be mostly on mavenCentral and remove the modules to fetch from JCenter, once it will be available from mavenCental.
2. Updating Gradle to use the new repositories in place of JCenter.
3. Investigating all missing dependencies to find alternate repositories
4. Ensuring the app builds successfully without JCenter after all the migration.

**Comment by gouri-panda** [comment]
Duplicate #2591

**Comment by 4shutosh** [comment]
My bad @gouri-panda. The issue can be further closed if required.

**Comment by s-ayush2903** [comment]
Closing
