### ISSUE TITLE
Clicking an Image will Open a different screen

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2615]
**Is your feature request related to a problem? Please describe.**
Since images are important in Kiwix. It would be better if we create a new different full-screen image for images when clicking them. 

**Describe the solution you'd like**
Create a new Screen
**Additional context**
**Describe alternatives you've considered**
Yes, we have an alternative method. The users can zoom for images.
**Additional context**
We can add new or existed additional functionality of images there.

**Comment by Pawanupadhyay10** [comment]
hello, gouri can you assign this issue to me so that I can start and please guide me to start working.

**Comment by kelson42** [comment]
@gouri-panda what is the value of a fullscreen image if the upimage resolution is not higher than what is in the thumbnail?

**Comment by gouri-panda** [comment]
@kelson42 Good Point. Maybe we can give a full-screen image of those images we are downloading?

**Comment by kelson42** [comment]
@gouri-panda All of this is a decision on the scraper side IMO, nothing to do with Kiwix Android. I would recommed to close this ticket.
