### ISSUE TITLE
Add `Nightly` Status Badge in Readme

### ISSUE THREAD

**Issue by s-ayush2903** [kiwix/kiwix-android#2636]
**Is your feature request related to a problem? Please describe.**
Nightly fails multiple times for a long period of time and goes unnoticed for weeks and months, and we always get to know about it very late. I've fixed 'em numerous times but it is always too late and many changes get merged in to the stream by the time we get to know about it.

**Describe the solution you'd like**
Add a status badge in readme so that nightly status can be seen easily without much effort(s). 

**Describe alternatives you've considered**
None

**Additional context**
#2488 #2492 #2585 #2633

**Comment by kelson42** [comment]
Yes, is a good idea.

**Comment by s-ayush2903** [comment]
I'm Sorry, but I cannot take beginner friendly issues. https://github.com/kiwix/kiwix-android/issues/2068#issuecomment-721884345

**Comment by kelson42** [comment]
@s-ayush2903 you should be able, what does not work exactly?

**Comment by cdhiraj40** [comment]
@kelson42 I would like to work on this :)
