### ISSUE TITLE
Library still lists old zim files

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#264]
The library shows an outdated zim file from December on top of the list. This maybe a naming issue as the newer one is named "No Videos"

![screenshot_2017-09-27-08-11-31](https://user-images.githubusercontent.com/21675885/30898404-876ff602-a35b-11e7-9bd2-52e3ec843eb3.png)

**Comment by kelson42** [comment]
This is the problem with the library.xml itself as we do not provide anymore (for now) files with everything inside (meant in the past without videos and now with videos) for many wiki. I should probably provide a hack to avoid that. That said, it would be good to change www.kiwix.org to have the link pointing to the _novid_ versions of the files.

**Comment by Popolechien** [comment]
do you have a generic link so I don't need to update everytime we get a new zim? The website currently points at http://download.kiwix.org/zim/wikipedia_en_all.zim

Should I use http://download.kiwix.org/portable/wikipedia_en_all_novid.zim instead?

**Comment by kelson42** [comment]
@Popolechien I do not have a generic link, but I just have modified the script to "forget" about old zim files if there is a "all_novid" version. That shoudl fix this bug.
