### ISSUE TITLE
One panel for all the library filters

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2640]
For the online and the offline library. Should be super accessible (with a swipe?). The free text search should be put there beside the language and category searches.

**Comment by cdhiraj40** [comment]
hey @kelson42 I had the thought of adding a filter in the download screen (for now sorting on the basis of download size), but maybe I can try out this first or after adding to download as per you
Can you provide me with some more info about the issue? Thanks

**Comment by kelson42** [comment]
@cdhiraj40 Honestly, I have no precise idea about how it looks like, but we should try to have an even simpler library. But I would recommend to continue with "good first issue" tickets instead of tackling this complex one.

**Comment by cdhiraj40** [comment]
> @cdhiraj40 Honestly, I have no precise idea about how it looks like, but we should try to have an even simpler library. But I would recommend to continue with "good first issue" tickets instead of tackling this complex one.

sure I will keep trying for  ``good first issues`` and then maybe someday will help the organization in this, thanks :)

**Comment by kelson42** [comment]
For the moment we should mostly implement a category filter, see #500. For the rest I’m sure of nothing. Not in favour of implementing a lot of filters anyway. Closing this as not specific enough.
