### ISSUE TITLE
Reader should open on reader tab by default instead of library tab

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2641]
Based on a user comment and a lot of common sense: whenever Kiwix is opened the default setting should be to open on the reader tab (ie last zim being browser) rather than the library tab. If the last zim that was browser has since been deleted, then we can default to reader.

**Comment by kelson42** [comment]
Actually this depends on #398 and a settings shoudl be made: "remember open tabs when existing"

**Comment by Popolechien** [comment]
@kelson42 close enough. thanks.
