### ISSUE TITLE
Problems with MANAGE_EXTERNAL_STORAGE to come?

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2646]
Do the necessary to avoid problems with https://support.google.com/googleplay/android-developer/answer/10467955

**Comment by 4shutosh** [comment]
I don't think that's an issue for us, our targetSdk is 29 (Android 10) and we are also using `requestLegacyExternalStorage` flag.

Also, we don't have the `MANAGE_EXTERNAL_STORAGE` permission in our project.

We do use the READ_EXTERNAL_STORAGE but that's okay.
> Also, this policy does not impact the usage of the READ_EXTERNAL_STORAGE permission. 

So we are good.

**Comment by kelson42** [comment]
@gouri-panda any opinion, does this problem has been fixed recently (i see the warning in the play store).

**Comment by gouri-panda** [comment]
>I don't think that's an issue for us, our targetSdk is 29 (Android 10) and we are also using requestLegacyExternalStorage flag.
Also, we don't have the MANAGE_EXTERNAL_STORAGE permission in our project.

I agree with @4shutosh .
>does this problem has been fixed recently

Not that I know of.

According to [Google play notice](https://developer.android.com/training/data-storage/manage-all-files#all-files-access-google-play) this permission only when your app cannot effectively make use of the more privacy-friendly APIs, such as Storage Access Framework or the Media Store API. Additionally, the app's usage of the permission must fall within permitted uses and must be directly tied to the core functionality of the app.
One of the core functionality of the Kiwix app does Search (On Device) i.e core purpose is to search through files and folders across the device’s external storage which is eligible permission for Android 11 (API level 30) or higher.
