### ISSUE TITLE
Wikivoyage doesn't work following a factory reset

### ISSUE THREAD

**Issue by Eyarkoni** [kiwix/kiwix-android#2652]
I had to factory reset my smartphone,after which all apps including Wikivoyage were re-installed automatically by Android. 
When I tried to launch the app, I got an error message "invalid install. Please download Zim". Uninstall & reinstall did not resolve this issue. 

I'm using Xiaomi redme note 7.
MIUI 12.0.1
Android 10
Wikivoyage version 2019-12

Thanks.

**Describe the bug**

**Expected behavior**

**Steps to reproduce the behavior:**
1. 

**Screenshots**

**Environment**
- Version of Kiwix Android : 
- Device : 
- OS version : 

**Logs**

**Describe the bug**

**Expected behavior**

**Steps to reproduce the behavior:**
1. 

**Screenshots**

**Environment**
- Version of Kiwix Android : 
- Device : 
- OS version : 

**Logs**

**Comment by kelson42** [comment]
@mhutti1 I don't know what you think about this bug, but this sounds pretty mysterious. To me, as soon as libkiwix 10.0.0 is released (with the ZIM file constructor with filehandler), we should implemented https://github.com/kiwix/kiwix-android/issues/56 and it should probably fix this kind of scenario.

**Comment by mhutti1** [comment]
I would imagine what has happened here is the filesystem lost track of where it is keeping the expansion files with the content. Not much we can do about this unfortunately.

**Comment by kelson42** [comment]
@mhutti1 But, why a reinstall does not fix the pb?

**Comment by Eyarkoni** [comment]
actually, I noticed not all Kiwix files were deleted during the reinstall.
I deleted them manually, but even that didn't help.


*Eran Yarkoni *
***@***.***
Phone: +972-54-750-3041
Skype: eyarkoni
WeChat: EranYarkoni
http://il.linkedin.com/in/yarkoni

ᐧ

**Comment by kelson42** [comment]
@Eyarkoni Which file was not deleted after uninstallation?

**Comment by Eyarkoni** [comment]
Not sure what were the files, I only know that I have found several folders
having *kiwix* in their name which I found while doing a deep search in the
Android storage space.


*Eran Yarkoni *
***@***.***
Phone: +972-54-750-3041
Skype: eyarkoni
WeChat: EranYarkoni
http://il.linkedin.com/in/yarkoni

ᐧ

**Comment by mhutti1** [comment]
Could be a cache somewhere. The play store ultimately manages all of this. Not sure if we can do anything. Global cache clear / factory reset would probably fix but not much else we can do.

**Comment by kelson42** [comment]
Unfortunately nothing we can really do to help here.
