### ISSUE TITLE
English Wikipedia 2021-03: Articles (links) in Articles not clickable

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2656]
I am using Kiwix Android 3.4.3 on a Galaxy Tab S7 Plus. I noticed that in many articles some links to other articles are not clickable. I am using the latest English Wikipedia 2021-03 build. 

Example:
https://en.wikipedia.org/wiki/Outline_of_history#Ages_of_history

Here is a screenshot:
![Screenshot_20210518-141554_Kiwix](https://user-images.githubusercontent.com/84388790/118650698-07221500-b7e5-11eb-8fd0-608ccde56e77.jpg)

As you can see, "Dark Age", "Late Modern Age" and "Modern Age" are not clickable, i.e. you have to search for them manually, which does not always mean that you will find them, as they (sometimes) have a completely different title than indicated.

Unfortunately, this is not the only article that is affected. I have come across many other articles that have the same bug, even in 2021-03 German Wikipedia.

**Comment by Inbefortus** [comment]
Has anyone had the same experience? And why is this not getting any attention? So far I have come across countless articles with the same behavior as described above. This destroys some of the usability of the article, especially when the "See also" selection is broken, as almost all of the corresponding links are not clickable.

**Comment by kelson42** [comment]
Such behaviours happens when the article is missing. We should verify case by case.

**Comment by Inbefortus** [comment]
> Such behaviours happens when the article is missing. We should verify case by case.

The good thing is that these articles actually exist, just "not" in the article. You can still easily find most of the articles by searching for them under their giving name, but there are also articles under a different name, which makes it almost literally impossible to take a look. I have always compared to the original English Wikipedia when I realized that a link is not clickable.

In my experience, everything is fine in terms of the presence of the articles themselves, but some important related articles (links) are not usable to get a better understanding of the article you are reading, as they are not clickable.

At first I thought this had something to do with the Android app, but it turns out I was wrong as I have the same behavior on Windows 10. 

I think this has something to do with the ZIM file itself?

**Comment by kelson42** [comment]
They are not clickable because there is no link. Why there is no link is a question to answer by the scraper team. Moving the ticket.
