### ISSUE TITLE
Not existing article in English Wikipedia

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2663]
The article https://en.wikipedia.org/wiki/Benidorm_(British_TV_series) does not exist in the current English Wikipedia 2021-03 build, so unfortunately cannot be read. 

I tried searching under the name of the article, but this is all you get:

![Screenshot_20210601-130718_Kiwix](https://user-images.githubusercontent.com/71934042/120314007-0c9a5780-c2db-11eb-8d91-08db40c45cf9.jpg)

If you click on "Benidorm (TV series)" you are redirected to:

![20210601_131919](https://user-images.githubusercontent.com/71934042/120315013-2b4d1e00-c2dc-11eb-8bd9-61b87cad930d.jpg)

**Comment by Popolechien** [comment]
@Inbefortus But then isn't this an issue with the Wikipedia ZIM file rather than Android?
