### ISSUE TITLE
Missing images in custom Wikipedia zim

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2664]
When generating a test zim file from https://farm.openzim.org/recipes/wikipedia_en_for_schools the corresponding zim file seems to have missed an image.
I ran the recipe twice, and the same image (https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_for_Schools/Welcome/Mathematics#/media/File:Fisher_iris_versicolor_sepalwidth.png) is always missing:
![Capture d’écran 2021-06-08 à 14 55 48](https://user-images.githubusercontent.com/21675885/121188743-af1d8200-c869-11eb-9a22-62fbf9170499.png)

Same issue appears on [Kiwix-JS](../../kiwix-js/issues/730), but not on Kiwix-Serve

**Comment by kelson42** [comment]
@Popolechien The problem is in the ZIM, sorry about that.

**Comment by Popolechien** [comment]
Ah, apparently a ZIM issue in the end. https://github.com/openzim/mwoffliner/issues/1477
