### ISSUE TITLE
Missing image in English and German Wikipedia

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2665]
I'm using Kiwix 3.4.3. ZIM is 2021-03 English and German Wikipedia.

Thanks to the random article feature, I came across https://en.wikipedia.org/wiki/William_L._Jorgensen

It looks like the only image in this article is missing (or just not displayed correctly?).

In Kiwix (English Wikipedia)

![Screenshot_20210611-092619_Kiwix.jpg](https://user-images.githubusercontent.com/71934042/121661381-70274080-caa4-11eb-988c-02b4ae8c1ac8.jpg)

In Kiwix (German Wikipedia)

![Screenshot_20210611-092640_Kiwix.jpg](https://user-images.githubusercontent.com/71934042/121661405-73bac780-caa4-11eb-817b-27c04fd33a5a.jpg)

Original German Wikipedia
![Screenshot_20210611-103610_Samsung Internet.jpg](https://user-images.githubusercontent.com/71934042/121661431-7ae1d580-caa4-11eb-9737-18a6f5939265.jpg)

Original English Wikipedia
![Screenshot_20210611-103620_Samsung Internet.jpg](https://user-images.githubusercontent.com/71934042/121661449-7e755c80-caa4-11eb-9b55-cc72b1453e36.jpg)

**Comment by kelson42** [comment]
file seems to be missing in ZIM file, see http://library.kiwix.org/wikipedia_en_all_maxi/A/William_L._Jorgensen
