### ISSUE TITLE
Red dot is not visible on the map

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2673]
Kiwix Version: 3.4.4
ZIM: 2021-03 German Wikipedia

The red dot illustrating the geographical location is not visible. 2021-03 English Wikipedia is not concerned.

Either article that has something to do with a city is implicated.

Kiwix:

![Screenshot_20210704-202607_Kiwix](https://user-images.githubusercontent.com/71934042/124396467-077d5d80-dd0a-11eb-9461-feb6b1f781a7.jpg)

Original German Wikipedia:

![Screenshot_20210704-202627_Samsung Internet](https://user-images.githubusercontent.com/71934042/124396482-1cf28780-dd0a-11eb-9cb6-5f7c752aab11.jpg)

Kiwix:

![Screenshot_20210704-202656_Kiwix](https://user-images.githubusercontent.com/71934042/124396493-3a275600-dd0a-11eb-9032-652ab9814eff.jpg)

Original German Wikipedia:

![Screenshot_20210704-202723_Samsung Internet](https://user-images.githubusercontent.com/71934042/124396503-4b706280-dd0a-11eb-8c35-0ab60eb27f54.jpg)

Kiwix (2021-03 English Wikipedia):

![Screenshot_20210704-202849_Kiwix](https://user-images.githubusercontent.com/71934042/124396525-6d69e500-dd0a-11eb-8380-201428c48078.jpg)

![Screenshot_20210704-202918_Kiwix](https://user-images.githubusercontent.com/71934042/124396528-6e027b80-dd0a-11eb-8fb8-595ee1aee6ee.jpg)

**Comment by Inbefortus** [comment]
> This is not an issue with the application. It seems the image/content is outdated and needs to be updated.

@4shutosh This is not the case with Kiwix JS PWA, it works in both desktop and mobile style. So I think it has something to do with the app itself.

Kiwix JS PWA:

![Screenshot_20210903-112345_Samsung Internet](https://user-images.githubusercontent.com/71934042/131983740-93f456c6-3b1a-444b-aaa6-55f23cb31812.jpg)
![Screenshot_20210903-112359_Samsung Internet](https://user-images.githubusercontent.com/71934042/131983744-e04a86e5-2833-4c31-a05f-756e507d5a9e.jpg)

Kiwix Android:

![Screenshot_20210903-112424_Kiwix](https://user-images.githubusercontent.com/71934042/131983830-fdd83408-ea9d-4d62-b3fa-7f38fa0edaae.jpg)

**Comment by gouri-panda** [comment]
@Inbefortus Can you give us the zim file name and the android version you are using? Thanks!

**Comment by Inbefortus** [comment]
@gouri-panda wikipedia_de_all_maxi_2021-03.zim and wikipedia_de_all_maxi_2021-08.zim

Kiwix Android 3.4.4

**Comment by kelson42** [comment]
Kamino closed and cloned this issue to [openzim/mwoffliner](https://github.com/openzim/mwoffliner/issues/1952)
