### ISSUE TITLE
Adding a Wikimedia desktop style setting to Kiwix Android to debunk templates

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2674]
Adding the 'Wikimedia desktop style' to the Android Kiwix app as a setting would warrant us mobile android users to navigate through templates. At the moment you are forced to use the 'Wikimedia mobile style' (which is logical), but at a high price.

See https://github.com/openzim/mwoffliner/issues/1474#issuecomment-874006472

**Comment by kelson42** [comment]
Kiwix Android is content agnostic. Everything related to content is in the ZIM file.
