### ISSUE TITLE
Access own kiwix server through my own local IP.

### ISSUE THREAD

**Issue by diashima** [kiwix/kiwix-android#2675]
Hello. My company has our own mobile operator, that can connect directly to the server of my office through 4G (like local network). 
Is there any way to host kiwix server and then connect to our own IP trough kiwix-android app?

**Comment by kelson42** [comment]
I guess you don't need kiwix-android, just host kiwix-serve on a server and have it listen to internet HTTP requests.

**Comment by kelson42** [comment]
I guess you mean a REST API. Answer is yes a bit, and we are strongly developing. Documentation is not full so far. What do you want to do?

**Comment by diashima** [comment]
> I guess you mean a REST API. Answer is yes a bit, and we are strongly developing. Documentation is not full so far. What do you want to do?

I want to create mobile application (android/kotlin), where users will have ability to connect(search, preview) to wiki dump, that is post on server via local connection.

**Comment by kelson42** [comment]
You should be able to do that with kiwix-serve. The is no formal fulltext search API so far, but an opensearch API will be implemented in the next months https://github.com/kiwix/kiwix-tools/issues/52. You can make a title search (see how the kiwix-serve title suggestion box works).
