### ISSUE TITLE
Saved zim files do not show when reinstalling app

### ISSUE THREAD

**Issue by jl2359** [kiwix/kiwix-android#2676]
Downloads only run when the app opens, but are cancelled when exiting the app or leaving the phone idle, leaving 1 hour downloads to take several days, and usually failing before being fully downloaded. After some zim files being stuck in "Waiting"-mode and/or downloads constantly failing, I uninstalled and reinstalled the Kiwix android app version 3.4.1, the latest from F-Droid, on Fairphone 3 running /e/ os Android version 10. The previously downloaded zim files are not visible in the Kiwix library (they are however still on the phones' storage). The steps to reproduce this behaviour are just 1. open app 2. try to download files.  The expected behaviour is of course that the files are successfully downloaded and visible.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Sorry, but I had to add this ticket in the project.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

By introducing the ```MediaStore Api``` and saving on public folder should also fixed this issue too.

**Comment by MohitMaliFtechiz** [comment]
Hi ,
after merging the following pull request 
https://github.com/kiwix/kiwix-android/pull/2800

we will able to read saved zim files and it will prompt on reinstalling the app. this feature will be fully working on android 11 and above while below android 11 only internal save  work while external is app specific.
