### ISSUE TITLE
Storing Zim/Book files inside the seperate Kiwix Directory

### ISSUE THREAD

**Issue by 4shutosh** [kiwix/kiwix-android#2690]
**Describe the bug**

Why are we not storing all the zim files aka the "books" on the external storage inside the Kiwix directory just as the notes?
- As per current implementation if the user uninstalls the app all the downloaded books are also removed which is defying the primary motive of our app. (Basically users lose all the time and data used to download the files: primary user target is with less internet access)
- One more use case is overruled because of this behavior: If the user wants to transfer the zim files from one device to another, there's no way to do so (also the majority of users are not so tech-savvy to access the app-specific files and move them manually, Moreover from Android 11 onwards, no app can access the app directories it will require Special Permissions)

**Expected behavior**

- Uninstalling the app should not remove the zim files.
- Reinstall the app and all the books/files should re-appear in the library. 
- Another way of doing that maybe providing the users a method to the ZIM files from the app (giving a button "open from device" something like that, which lets users open the zim file from their storage)

**Comment by kelson42** [comment]
@4shutosh You can save to the external SD card, if you choose it in the settings.

**Comment by 4shutosh** [comment]
But the point being the default behaviour removes the books on uninstall, is that ideal?

**Comment by kelson42** [comment]
AFAIK they are removed only if they are in the default app directory (default behaviour) and there is nothing we can do about that. AFAIK, the ZIM files are not deleted if they are stored somewhere else. The ticket should be rewritten like a standard bug with a concrete example which is buggy.

**Comment by gouri-panda** [comment]
>As per current implementation if the user uninstalls the app all the downloaded books are also removed which is defying the primary motive of our app. (Basically users lose all the time and data used to download the files: primary user target is with less internet access)

I agree with this idea. Generally, our users store a lot of data so we should store zim files like a normal media App after uninstallation.
>AFAIK they are removed only if they are in the default app directory (default behaviour) and there is nothing we can do about that (Android standard uninstallation).

Yes, we can do that.

>One more use case is overruled because of this behavior: If the user wants to transfer the zim files from one device to another, there's no way to do so (also the majority of users are not so tech-savvy to access the app-specific files and move them manually, 

We have this functionality inside our app to share ZIM files.

**Comment by cdhiraj40** [comment]
@gouri-panda @kelson42 @4shutosh Maybe we can create a folder 'kiwix' under the downloads folder?
I think then data won't be removed and maybe we can check in that specific folder again for the data whenever a new install is done.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you describe here please what you plan do to? I'm not sure there is anything to do honestly.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

I am currently switch back to ```MediaStore Api``` to move app specific folder to public directory so it can shareable to other app , also once we uninstall the app the data remain stored in memory. For internal storage i have figured it out to store and retrieve from public folder with external storage its not allow me to create folder apart from app specific so i am currently figured it out.
