### ISSUE TITLE
Add `MANAGE_EXTERNAL_STORAGE` permission

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2694]
**Is your feature request related to a problem? Please describe.**
In android 11 we have to add `MANAGE_EXTERNAL_STORAGE`  in order to access other zim files that are present other than our app(outside the app).

**Describe the solution you'd like**
Add this permission

**Additional context**
Previously we discussed: [here](https://github.com/kiwix/kiwix-android/pull/2660#issuecomment-846469934) [here](https://github.com/kiwix/kiwix-android/pull/2660#issuecomment-846536630) [here](https://github.com/kiwix/kiwix-android/pull/2660#issuecomment-846610476) [here](https://github.com/kiwix/kiwix-android/issues/2646)
However, in the Play Store, we will need to justify the reason for requesting that permission.
CC @kelson42

**Comment by kelson42** [comment]
@gouri-panda Something important about this, it is important this feature does not impact the custom app. In custom apps, this permission is not needed, so either this is fully transparent for the end-user, or we need to someone avoid to request it for custom apps.

**Comment by gouri-panda** [comment]
@kelson42 Our `kiwix-android` and `custom app` have two manifest files. So we don't need this permission in our custom app.
