### ISSUE TITLE
Upgrading Object-Box Dependency to support ConflictStrategy

### ISSUE THREAD

**Issue by 4shutosh** [kiwix/kiwix-android#2696]
**Is your feature request related to a problem? Please describe.**

PageFragment implementations require ConflictStrategy to work better for storing unique objects.

**Describe the solution you'd like**

Dependency update required for object-box reference [here](https://github.com/objectbox/objectbox-java/issues/509)

**Comment by kelson42** [comment]
We are deprecating Objectbox, somthis improvement does not make sense anymore IMO. @mhutti1 @gouri-panda Please reopen if you disagree.
