### ISSUE TITLE
Current android downloads do show an empty progress bar (sometimes)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#27]
_From @kelson42 on January 8, 2017 23:42_

If Kiwix restarts and there is no internet, the oinging download show en empty progress bar. The bar should show how many is already downloaded (anyway if the downloading process currently runs or not).

_Copied from original issue: kiwix/kiwix#431_

**Comment by mhutti1** [comment]
Caused by the same problem as #20
