### ISSUE TITLE
Option to display more content on a large screen

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2701]
It would be appropriate for us tablet users if there was an option to display more content on a large screen. The layout is rather adapted for mobile users and should therefore also be optimized for a tablet.

In Kiwix it looks like this:

![Screenshot_20210904-191325_Kiwix](https://user-images.githubusercontent.com/71934042/132103748-663d2da7-d37f-4acc-bab6-e2bb66a0e340.jpg)

Best would be like this (Kiwix JS PWA):

![Screenshot_20210904-191318_Samsung Internet](https://user-images.githubusercontent.com/71934042/132103731-9b52c565-0099-4399-a952-9bd289296e7f.jpg)

**Comment by pratik2315** [comment]
Hey @Inbefortus, Is this issue still open to work, can I work on this?
Thanks.

**Comment by Inbefortus** [comment]
@pratik2315 Of course!

**Comment by kelson42** [comment]
This is a content question, moving to `openzim/mwoffliner`

**Comment by kelson42** [comment]
Kamino closed and cloned this issue to [openzim/mwoffliner](https://github.com/openzim/mwoffliner/issues/1993)
