### ISSUE TITLE
Improper display of gallery mode 

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2714]
Not entirely sure if this is an android or mwoffliner issue, but the display problem only appear here so...

The article [Electroencephalography](https://en.wikipedia.org/wiki/Electroencephalography) has a gallery of images with rather long descriptions. It appears normally on Kiwix-serve (see [here](https://en.wikipedia.org/wiki/Electroencephalography)):
![Capture d’écran 2021-10-04 à 16 33 16](https://user-images.githubusercontent.com/21675885/135870420-816c9486-ebfd-4cb6-9168-bcaa0453a33a.png)

**On Kiwix-android,** however, the display is misaligned:

![Screenshot_20211001-171021_Medical Wikipedia](https://user-images.githubusercontent.com/21675885/135870513-674b8aee-44ad-4b0a-bac1-f7affce11be0.jpg)
![Screenshot_20211001-171031_Medical Wikipedia](https://user-images.githubusercontent.com/21675885/135870640-020b4123-16d6-4dd9-a0e7-2f81ae5be275.jpg)

**Comment by kelson42** [comment]
Will have a look, but highly probably a problem with MWoffliner.
