### ISSUE TITLE
Hide Keyboard when Scrolling in OnlineLibraryFragment/PagerFragment

### ISSUE THREAD

**Issue by cdhiraj40** [kiwix/kiwix-android#2717]
**Is your feature request related to a problem? Please describe.**
In  OnlineLibraryFragment  & PagerFragment  while scrolling the keyboard just stays there and takes so much space of the page
which in my opinion isn't a great experience, its better if we scroll and the keyboard goes away :)

**Describe the solution you'd like**
I will addOnScrollListener to the recycler view so everytime we scroll the keyboard gets hidden

**Describe alternatives you've considered**
if we use a touch listener, then the keyboard hiding code is called multiple times each second while scrolling, which is not efficient.

**Additional context**
Before my approach 

https://user-images.githubusercontent.com/75211982/137470164-0d79d9d4-6856-4956-88b2-d8fcdc72a653.mp4

After my approach 

https://user-images.githubusercontent.com/75211982/137470182-efae0cbd-4e29-42df-bff1-d60632b8363f.mp4

**Comment by gouri-panda** [comment]
Yeah, I like the idea. It's great UX. The basic fundamental is  If the edit-text field doesn't focus anymore. Let the keyboard hide. @kelson42 What do you think?

**Comment by cdhiraj40** [comment]
> Sounds a good improvement, just hope this deos not have any bad sode effects. Definitly worth a try.

also, one more thing should searchView/editText lose focus(remove cursor) when scrolled?

**Comment by gouri-panda** [comment]
Leave it for now. Although I find it odd we don't lose focus if we click enter.

**Comment by cdhiraj40** [comment]
@kelson42 @gouri-panda after getting familiar with the codebase and the app
 I see at many places that while scrolling the keyboard just stays there.
 should I create a new issue and add this functionality to those places?

**Comment by gouri-panda** [comment]
@cdhiraj40 Is this related to #2756 ?

**Comment by cdhiraj40** [comment]
> @cdhiraj40 Is this related to #2756 ?

no no, this is different here the functionality should be close keyboard on the scroll
pending changes-> searching in reader page, searching about languages,

**Comment by gouri-panda** [comment]
>no no, this is different here the functionality should be close keyboard on the scroll
pending changes-> searching in reader page, searching about languages,

So it's not related to the above PR's issue. You wanna do the same functionality with the above places. Right?

**Comment by cdhiraj40** [comment]
> > no no, this is different here the functionality should be close keyboard on the scroll
> > pending changes-> searching in reader page, searching about languages,
> 
> So it's not related to the above PR's issue. You wanna do the same functionality with the above places. Right?

yes!

**Comment by anamansari062** [comment]
hey @cdhiraj40, this seems interesting to me. if you don't mind I would like to create an issue to work on this and learn something new.

**Comment by anamansari062** [comment]
> @kelson42 @gouri-panda after getting familiar with the codebase and the app I see at many places that while scrolling through screens, the keyboard just stays there. should I create a new issue and add this functionality to those places?

hey @cdhiraj40, this seems interesting to me. if you don't mind I would like to create an issue to work on this and learn something new :)

**Comment by cdhiraj40** [comment]
> > @kelson42 @gouri-panda after getting familiar with the codebase and the app I see at many places that while scrolling through screens, the keyboard just stays there. should I create a new issue and add this functionality to those places?
> 
> hey @cdhiraj40, this seems interesting to me. if you don't mind I would like to create an issue to work on this and learn something new :)
> 

sure go ahead!
just dont forget to add at all places :)
you can check [this]( https://github.com/kiwix/kiwix-android/issues/2717#issuecomment-988316266) to see where its pending.
