### ISSUE TITLE
Adapting the app to support Background optimizations

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#272]
Android 7.x and Android 8 include various changes intended to optimize how apps behave when running the background. These include changes to network traffic, background services, etc. Users can apply most of the restrictions even if the app does not target these releases! so users can choose to affect and constrain the behaviour of Kiwix-Android anyway. So I think it'd be good for us to revise the app at some point to support the newer versions on Android.

Here are the main links I've found to these topics so far:

* https://developer.android.com/topic/performance/background-optimization.html
* https://developer.android.com/topic/performance/background-optimization.html#sched-jobs (for using the network on unmetered connections)
* https://developer.android.com/about/versions/oreo/background.html (Further changes and restrictions added in Oreo (Android 8.0)

**Comment by abdulwd** [comment]
@theLimitBreaker You may work on this issue. Can you please share how will you resolve this issue i.e. what changes you plan to make?

**Comment by theLimitBreaker** [comment]
@abdulwd  So far I was able to see DownloadService as Background Process. For apps Above 5.0 we can use Job Scheduler. If network is unavailbale then Job Scheduler can retry on its own and work in background. For Android  Above 8.0 normal Service throws exception when in Background.

**Comment by abdulwd** [comment]
@mhutti1 As `DownloadService` is only used to download the ZIM files I think we can rely on this library https://github.com/lingochamp/okdownload for downloading the ZIM files instead of improving our custom solution. It has high test coverage and is being maintained actively.

**Comment by theLimitBreaker** [comment]
Correct me if wrong . But OkDownload is library for download files . Would it Handle Background exceptions thrown by Android Platform above 8.0 
Would it Handle Background executions . I think for that we have to use WorkManager or JobScheduler Only . 
🤔

**Comment by abdulwd** [comment]
I'm not sure about. If WorkManager/JobScheduler is our only option we can use it. You may start working on this issue once @mhutti1 provides his feedback.

**Comment by kelson42** [comment]
@mhutti1 @julianharty @macgills What to do with this ticket? Is that still pertinent?

**Comment by macgills** [comment]
No, we don't really do any "background" work anymore. We use foreground services with notifications if performing a long running task
