### ISSUE TITLE
Double Character Input with Unihertz Titan Pocket

### ISSUE THREAD

**Issue by suptheapp** [kiwix/kiwix-android#2725]
With the brand new Unihertz Titan Pocket's physical keyboard (Android 11) there is a bug where double characters show up in Kiwix when using the physical keyboard --- one press of the key results in two identical characters being pressed.  There may be a buffer issue in the text input field because many rapid presses can result in an odd number of characters being entered.  Using the on-screen keyboard works fine, and using the "Find in page" text input field works fine with the physical keyboard.

This ticket was requested on https://www.reddit.com/r/unihertztitanpocket/comments/qfaw08/double_character_issue_on_a_few_apps/

Here is a screen capture video:

https://user-images.githubusercontent.com/16461802/138737339-7e53ce47-146c-46f9-ab8d-7e2219fa4b98.mp4

**Comment by kelson42** [comment]
@gouri-panda To me it looks similar to #2657 fixed in 3.4.5. A duplicate?

**Comment by gouri-panda** [comment]
@kelson42  I don't think it's related to our app.

**Comment by kelson42** [comment]
@suptheapp Any feedback? otherwise we will to close this ticket.

**Comment by kelson42** [comment]
No feedback, closing ticket.
