### ISSUE TITLE
Pass Test for Android 30

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2729]
Error:
 >qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:network' service: Invalid argument

Since we weren't checking the device after 6.0(marshmallow) we are seeing now in android API 30(android 10)  emulator devices. This error could be seen on Android Emulator/Device Version >= 6.0. It occurs probably when our app tries to send/receive requests/responses to a remote API that is not secure (HTTP).

**Comment by gouri-panda** [comment]
@Fs00 We have that. I guess in the emulator something weird goes on.

**Comment by kelson42** [comment]
> In order to connect via insecure HTTP, recent Android versions (Nougat and newer if I recall) require you to add `android:usesCleartextTraffic="true"` attribute to the `<application>` tag in the manifest.
> Hope it helps.

@MohitMaliFtechiz Have you seen this comment? Is this activated properly?

**Comment by kelson42** [comment]
Problem handled within #2804

**Comment by gouri-panda** [comment]
> > In order to connect via insecure HTTP, recent Android versions (Nougat and newer if I recall) require you to add `android:usesCleartextTraffic="true"` attribute to the `<application>` tag in the manifest.
> > Hope it helps.
> 
> @MohitMaliFtechiz Have you seen this comment? Is this activated properly?

@kelson42 We have already tried that. It doesn't work.

**Comment by kelson42** [comment]
@gouri-panda To bypass download.kiwix.org redirections and secure we keep using https. I have recommended yesterday to @MohitMaliFtechiz tondirectly use https://mirror.download.kiwix.org/library/library_zim.xml.

**Comment by gouri-panda** [comment]
@kelson42 I hope it works. I tested with the above `android:usesCleartextTraffic="true` , it overrides the https protocol for all url, but nothing really happened.

My second try would be customizing our network preference by overriding the url which you given.

**Comment by gouri-panda** [comment]
Maybe we are looking wrong part of the solution because Google added this protocol in Android 26. In Android 29 it works fine(previously tested)  but in Android 30 it doesn't.
