### ISSUE TITLE
convert RecentSearchDao.java to Kotlin

### ISSUE THREAD

**Issue by cdhiraj40** [kiwix/kiwix-android#2737]
Parent issue: #1826

What changes you will do:
will convert Java file to Kotlin

I couldn't find an issue regarding this, do tell me if there is I will close this

**Comment by rishujam** [comment]
Hey is this issue completed because I can't see any file named RecentSearchDao

**Comment by cdhiraj40** [comment]
> Hey is this issue completed because I can't see any file named RecentSearchDao

not completed but the PR has been made :)

**Comment by rishujam** [comment]
why can't I see the file ? (I am newbie ignore if its a silly question).

**Comment by cdhiraj40** [comment]
> why can't I see the file ? (I am newbie ignore if its a silly question).

its totally fine :)
if you are asking about ``RecentSearchDao.java``
then it can be found under core folder whole path to file is -> core/data/local/dao/RecentSearchDao.java

**Comment by rishujam** [comment]
![Screenshot 2021-12-03 233003](https://user-images.githubusercontent.com/74773876/144650611-8449a8a1-8828-422d-827f-e3abcaddce3c.png)
I got it in test package

**Comment by rishujam** [comment]
Ok so I was searching in the app package actually I am new so working only in app package in android view. Wanted to ask one more silly question why we make so many different package outside the app package like can't we put them inside app package?

**Comment by cdhiraj40** [comment]
> Ok so I was searching in the app package actually I am new so working only in app package in android view. Wanted to ask one more silly question why we make so many different package outside the app package like can't we put them inside app package?
> 
> Also if you don't mind I have bunch of such questions as a beginner.  You can reply in discussion section if this section is only for particular issue and delete it.

sure would definitely like to help you :) 
you can ask me on slack if you didn't join yet you can join from here ->

**Comment by rishujam** [comment]
> > Ok so I was searching in the app package actually I am new so working only in app package in android view. Wanted to ask one more silly question why we make so many different package outside the app package like can't we put them inside app package?
> > Also if you don't mind I have bunch of such questions as a beginner.  You can reply in discussion section if this section is only for particular issue and delete it.
> 
> sure would definitely like to help you :) you can ask me on slack if you didn't join yet you can join from here -> [kiwix-slack](https://kiwixoffline.slack.com/)


Getting this error "doesn’t have an account on this workspace"

**Comment by rishujam** [comment]
Do I need to get email ending with kiwix.org ?

**Comment by gouri-panda** [comment]
>Do I need to get email ending with kiwix.org ? where do I get that.

@rishujam Normal Gmail domain works fine.

**Comment by rishujam** [comment]
![Screenshot 2021-12-05 003114](https://user-images.githubusercontent.com/74773876/144721450-c05d720a-faf7-4d96-8cdd-306bd06bd269.png)
@gouri-panda

**Comment by cdhiraj40** [comment]
@gouri-panda @kelson42  I think the slack link has expired @anamansari062 was facing the same issue I had to send her to invite via mail
additional info: https://github.com/elementary/website/issues/2255
https://slack.com/intl/en-in/help/articles/360049769934-Accept-an-invitation-to-join-another-companys-channel

**Comment by cdhiraj40** [comment]
@rishujam for now you can join the slack channel by  this [link](https://join.slack.com/t/kiwixoffline/shared_invite/zt-c5fgl342-VDYtm7fwY6w0BAeBqYxIGg)
and also now that we are using discussions, you can directly ask questions there, no need to ask any questions here if the question is not related to the issue itself :)
