### ISSUE TITLE
Ask for confirmation before exiting the app

### ISSUE THREAD

**Issue by anamansari062** [kiwix/kiwix-android#2744]
**Is your feature request related to a problem? Please describe.**
If we are pressing back button, the app closes without confirmation.

**Describe the solution you'd like**
The app should ask confirmation like "Are you sure you want to exit?" when back button is clicked.

**Comment by kelson42** [comment]
Seems to be a duplicate of #2606.

**Comment by cdhiraj40** [comment]
> Seems to be a duplicate of #2606.

I don't think this is a duplicate of #2606 this seems like a new feature request, unlike the other one

**Comment by kelson42** [comment]
I not in favour of confirmation of this kind anyway.

**Comment by gouri-panda** [comment]
We don't do any heavy tasks or save input tasks from users. So it's unnecessary.
