### ISSUE TITLE
Meaning of "top nopic" in the list of ZIM databases for Kiwix

### ISSUE THREAD

**Issue by yagamikira88** [kiwix/kiwix-android#2746]
What's the meaning of the word "top nopic" for offline database below for use on Kiwix?

https://wiki.kiwix.org/wiki/Content_in_all_languages

I understand the meaning of maxi, mini, and nopic, but there's no info on the meaning of "top", and how many articles the "top" have?

**Comment by kelson42** [comment]
top: only 50.000 most important/good quality articles
nopic: no pictures.
