### ISSUE TITLE
Add an option to share app

### ISSUE THREAD

**Issue by cdhiraj40** [kiwix/kiwix-android#2748]
**Is your feature request related to a problem? Please describe.**
Adding the option of the share app will allow users of this app to share it easily with others.

**Comment by 4shutosh** [comment]
Giving an option on the drawer needs to be a feature of high priority and which is used frequently.

I don't think that will be the best option here.

**Comment by cdhiraj40** [comment]
> Giving an option on the drawer needs to be a feature of high priority and which is used frequently.
> 
> I don't think that will be the best option here.

maybe adding in settings?

**Comment by helloitsgaurav** [comment]
ya it would be nice if we add it above the information section in the settings of the app
![image](https://user-images.githubusercontent.com/81961014/144573097-d82f1c3f-0be5-4162-a193-c9cd9cd1c157.png)

**Comment by kelson42** [comment]
AFAIK there is no standard way to share an app, right?

**Comment by helloitsgaurav** [comment]
though we can share the link to play store / app store  page of the app

**Comment by cdhiraj40** [comment]
> AFAIK there is no standard way to share an app, right?

yes, I also don't have any knowledge of sharing direct app, and sometimes the app doesn't get installed because of google play's policy(manually have to turn off the play protect)
But usually a google play store link is shared via any messaging app, Gmail, drive etc

**Comment by cdhiraj40** [comment]
> though we can share the link to play store / app store page of the app it would be better if we can share the apk of app without any use of internet

I'm not sure if we can share apps without the internet (other than an in-built messaging app where we get our OTPs)

**Comment by 4shutosh** [comment]
We do not work with any zim URLs, or deep links. 

So sharing the app here is only regarded as sharing the app download link from the play store. 

@kelson42 If we want to continue with this feature implementation, please help with a UI option to share the app download link.

**Comment by kelson42** [comment]
I'm not sure the idea is a good idea at all, why not just letting users type "Kiwix" in their prefered app store to find the app?

**Comment by cdhiraj40** [comment]
@kelson42 I think it's not about that user, it's about like If I am using kiwix and I'm liking it I can just share the link of the app from the app itself to my friends, colleagues and then they can download it and use it too. That's what I had in mind as I have seen in other apps too, thanks :)

**Comment by kelson42** [comment]
So like https://github.com/kiwix/kiwix-android/issues/379 ?

**Comment by cdhiraj40** [comment]
> So like #379 ?

ah yes

**Comment by rishujam** [comment]
Yes, I think adding share button in the three dots on top right corner will be convenient for user. Should I try adding it ?

**Comment by cdhiraj40** [comment]
> Yes, I think adding share button in the three dots on top right corner will be convenient for user. Should I try adding it ?

I actually wanted to work on it but we are having a discussion so not sure if this will be implemented as it has already been once rejected

**Comment by kelson42** [comment]
I confirm I'm against this feature request because it brings not enough added value. As such, I will close the ticket.
