### ISSUE TITLE
Keyboard doesnt hide when clicked on menu buttons of download screen and choose language 

### ISSUE THREAD

**Issue by cdhiraj40** [kiwix/kiwix-android#2756]
**Describe the bug**

The keyboard doesn't hide even when the editText is not focused
1) when clicked on ``choose a language `` from the download screen keyboard doesn't close and stays open in the select language screen
vice versa 
from the select languages screen when clicked on the ``tick``  icon keyboard doesn't close

**Expected behavior**
the keyboard should hide once editText has no focus
**Steps to reproduce the behavior:**
1. go to the download screen, click on search, see the keyboard open
2. now click on 
![image](https://user-images.githubusercontent.com/75211982/144815874-b07a678e-701a-4015-bc14-01b9d21c47c2.png)
and see the keyboard still open on a different screen
1. go to select languages screen and click on search see the keyboard open
4. now click on tick and see the keyboard open on the download screen
-->

sorry if I couldn't explain properly
see this screen recording this might help in understanding

**Screenshots**

https://user-images.githubusercontent.com/75211982/144816520-36d0d53b-6c51-4dc1-bad8-dfc25f6ea329.mp4

**Environment**
- Version of Kiwix Android: 3.4.5
- Device: realme 6/ emulator
- OS version: android10/11

I would like to work on this issue :)

**Comment by cdhiraj40** [comment]
any thoughts @gouri-panda @kelson42 ?
are you able to reproduce it too?

**Comment by gouri-panda** [comment]
@cdhiraj40 In #2717 We hide the keyboard as we scroll through the list and above here we change the fragment(window). so that's why the keyboard doesn't close in this circumstance.
>I would like to work on this issue :)

Go ahead! Before that can you propose how to deal with this situation above like this. We should close the keyboard in a generic way.

**Comment by cdhiraj40** [comment]
>Go ahead! Before that can you propose how to deal with this situation above like this. We should close the keyboard in a generic way.
I think this will be easy just hide the keyboard when you are going to different windows like
hide keyboard when clicked on menus

**Comment by gouri-panda** [comment]
Yes, We can do that but is there any better way to handle these kinds of situations?

**Comment by cdhiraj40** [comment]
> Yes, We can do that but is there any better way to handle these kinds of situations?

maybe ``android:windowSoftInputMode="stateHidden"`` may help
this will hide the keyboard whenever a new activity opens, not sure about the latency between opened keyboard and its closing time

**Comment by gouri-panda** [comment]
Yes, we can do this for now. But what if start adding multiple windows? Although We can add a simple method in this scenario.

**Comment by cdhiraj40** [comment]
> Yes, we can do this for now. But what if start adding multiple windows? Although We can add a simple method in this scenario.

as per me, a simple method will be better for now and maybe in the future too, I have seen this functionality via methods only so I cant say much about other solutions
but sure I will research and update you :)

**Comment by cdhiraj40** [comment]
@gouri-panda sorry but I was not able to find a proper solution for this, I guess a method will be good to resolve this if you approve I can start working and make a PR

**Comment by gouri-panda** [comment]
@cdhiraj40 Go ahead!
