### ISSUE TITLE
Kiwix android fails to display images on farsi wikipedia (2021-11)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2757]
On the latest (3.4.5) release, a user reported that they cannot see some images on https://download.kiwix.org/zim/wikipedia/wikipedia_fa_all_maxi_2021-11.zim

![Capture _2021-12-04-22-58-06](https://user-images.githubusercontent.com/21675885/145368127-ed370a6a-0786-49fe-bdff-59e4af4898a7.png)

The image [appears correctly on kiwix-serve](https://library.kiwix.org/wikipedia_fa_all_maxi/A/%D8%A7%D8%B5%D9%81%D9%87%D8%A7%D9%86), so clearly the issue is not zim-side.

**Comment by kelson42** [comment]
Interesting...

**Comment by Popolechien** [comment]
Nevermind I think it is a zim issue, I checked on Desktop and it would not work either, then double-checking on Kiwix-serve it does not work either.
I'll try on the previous zim version https://download.kiwix.org/zim/wikipedia/wikipedia_fa_all_maxi_2021-10.zim but I think we can close this ticket.
