### ISSUE TITLE
Kiwix is still on 3.4.1 on F-Droid 

### ISSUE THREAD

**Issue by defini-tiv** [kiwix/kiwix-android#2766]
Ist that on purpose?

**Comment by kelson42** [comment]
We don't have taken the time to deal with that.

**Comment by jgoerzen** [comment]
Could the f-droid like be removed from the website then?

**Comment by petrarca-arezzo** [comment]
I just want to support the wish to see kiwix being available (and mostly up-to-date) on the free F-Droid. Some people don't have Google on their Android and rely on F-Droid.
