### ISSUE TITLE
Random article function not working in wikiHow ZIMs

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2767]
Example ZIM: wikiHow English 2021-10

It's always leading to the same article.

![Screen_Recording_20211221-125555_Kiwix_1](https://user-images.githubusercontent.com/71934042/146928590-02fb00fd-38e2-445a-8686-7751e86c252f.gif)

In wikiHow Turkish (wikihow_tr_maxi_2021-10.zim) nothing happens:

![Screen_Recording_20211221-132310_Kiwix_1](https://user-images.githubusercontent.com/71934042/146930016-3876dfc2-4647-4506-aacf-e3972bd61289.gif)

**Comment by kelson42** [comment]
I strongly suspect we will have to migrate to libkiwix10 for that.

**Comment by MohitMaliFtechiz** [comment]
@Inbefortus, @kelson42, This issue will be fixed after we merged https://github.com/kiwix/kiwix-android/pull/3217.


https://github.com/kiwix/kiwix-android/assets/34593983/999f4a28-d575-4c65-87a5-ae8369cd412b
