### ISSUE TITLE
Implement video playing/streaming properly

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#277]
Currently the whole video is copied to the device mass storage before being played. Instead this should be streamed directly from the lib zim/kiwix.

**Comment by kelson42** [comment]
@mgautierfr Do you confirm lib kiwix/zim git master is ready for that?

**Comment by kelson42** [comment]
@mhutti1 libbzim/libkiwix git master HEAD has now the feature to retrieve only a part of an "article".

**Comment by mhutti1** [comment]
@kelson42 Improving video is harder than I thought :( I can load in bits of video now but playing them causes issues. If I cache them in files then I can play the first file but the second is corrupt likely cause it doesn't contain the correct headers. Do you have any insight on this?

**Comment by mhutti1** [comment]
So the solution we have decided on is to pass an offset to the videos location from the JNI and use that to get a file descriptor that can then be passed from our content provider to the video player.

**Comment by mgautierfr** [comment]
Why ?

Have you any insight why this solution is better than the other ?
Any links ?

Are you using android [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) ?
If this is the case, why not use create a [MediaDataSource](https://developer.android.com/reference/android/media/MediaDataSource.html) and use it as a source with [setDataSource](https://developer.android.com/reference/android/media/MediaPlayer.html#setDataSource(android.media.MediaDataSource)) ?

It could be the responsibility of the JNI (and kiwix-lib) to create this MediaDataSource.

**Comment by mhutti1** [comment]
MediaDataSource requires android 6.0+ it would also mean fiddling with the
webview to replace it's video player which is difficult. I looked at
exoplayer which might work for pre 6.0 but I could not get it working.

**Comment by mgautierfr** [comment]
Hum..
It seems you are using ContentProvider and override the `openFile` method (https://github.com/kiwix/kiwix-android/blob/03f27f6580c769f8f02adde36ec9018058c8b34f/app/src/main/java/org/kiwix/kiwixmobile/ZimContentProvider.java#L365-L377).

I can see that if the file is not a video, you are creating a pipe and use a thread to write to it.
But if this is a video, you are writing the whole content into a temporary file. Why not use a pipe all the time ? If the `TransferThread` could use the new `getContentPart` to fill the pipe.

You write in the pipe until the pipe is full (or while there is content if the webView read the content fast enough). As the write function block if the pipe is full, you will not copy the whole video in memory.
This is conditioned to the size of the internal pipe buffer, but I doubt it will be higher than few MB.

**Comment by mhutti1** [comment]
Because it doesn't allow seeking and it's too big and breaks the pipe.

**Comment by mgautierfr** [comment]
It's not that I don't want to implement a new API method to help you.
But I'm thinking that having a method giving you at which offset of which zim part is the content will probably not help you, as you are splitting the zim file, so a video could be in two zim parts.
(Assuming you can create a `ParcelFileDescriptor` from a file and a offset)

**Comment by kelson42** [comment]
@mgautierfr I thought it was clear that will lost the ability to split ZIM file at random position!

**Comment by mgautierfr** [comment]
We haven't lost the ability to split ZIM file at random position. It is just that if you split zim at random position, you may lost some libzim optimization to avoid copy if a cluster is split on two file parts.
But libzim is still able to handle randomly split zim.

The may "real" problem come from third party library/code who can't handle content split on several files. This include xapian (and, I fear about that, the future kiwix-android with this change.)

---

Coming back to our problem.. How will you handle the case of video being split on several zim parts ?
Will you stop to split zim files (and so stop supporting fat32 fs) ?

**Comment by kelson42** [comment]
@mhutti1 We will continue to split files, but stop to split files randomly (in the middle of clusters). Which also means that we will have "impossible cases" if you want to create chunks which are smaller than the biggest cluster. That is what zimsplit is about (.. and yes I should test it).

**Comment by kelson42** [comment]
@mhutti1 Is that ticket implemented?

**Comment by mhutti1** [comment]
@kelson42  I asked for your opinion on whether its ready to merge? https://github.com/kiwix/kiwix-android/pull/321

**Comment by kelson42** [comment]
@mhutti1 @mgautierfr Well done! Congrats to both of you :) And thx again to @rashiq who had implemented the workaround a few years ago.
