### ISSUE TITLE
Showing a dialog when clicked on close server

### ISSUE THREAD

**Issue by cdhiraj40** [kiwix/kiwix-android#2770]
Checklist for requesting a feature:
- [x] Check the issue tracker. The feature you are requesting may have already been requested.
- [x] Check if the feature does not exist on the latest developer's version.

**Is your feature request related to a problem? Please describe.**
when closing the server it directly closes it and it may have happened by mistake. As it closes the server immediately the reading sessions in other devices, Having a dialog asking for close may help in fixing that. 

**Describe the solution you'd like**
when clicked on stop server, a dialogue should show to ask to close the server.
something like this:

![Screenshot_2021-12-23-15-00-46-23_924282dd390cc14aae1af1e29436bb16.jpg](https://user-images.githubusercontent.com/75211982/147221085-15fa00f8-be7f-4bc5-ad33-511480a4c3d2.jpg)

I would like to work on this :)

**Comment by Rishavgupta12345** [comment]
can i work on this issue

**Comment by gouri-panda** [comment]
@Rishavgupta12345  it's not discussed yet. @cdhiraj40  I don't think it's necessary. User can simply reconnecting the service by clicking one button(Start Server) and the other side of the device or user won't even notice if they are static. @kelson42  What do you think?

**Comment by cdhiraj40** [comment]
> @Rishavgupta12345  it's not discussed yet. @cdhiraj40  I don't think it's necessary. User can simply reconnecting the service by clicking one button(Start Server) and the other side of the device or user won't even notice if they are static. @kelson42  What do you think?

if it works like that then i agree on this being unnecessary but i will still check once and verify you again.

**Comment by kelson42** [comment]
I confirm, such a dialog seems unecessary.
