### ISSUE TITLE
android 11 can not find my zim

### ISSUE THREAD

**Issue by heerNo1** [kiwix/kiwix-android#2771]
**Describe the bug**
I download zim,move to kiwix folder,but app can not find this zim.This zim can use in windows 10, so this zim is ok.I also download zim from this app , it can be read at first , then I moved it to another folder then move this zim download from app back to kiwix folder(0/android/data/org.kiwix.kiwixmobile/files/kiwix/) , this app can not find it , this is very weird.

**Expected behavior**

**Steps to reproduce the behavior:**
1. 

**Screenshots**

**Environment**
- Version of Kiwix Android : V3.4.5
- Device : RedMi K40pro+
- OS version : android 11 miui 12.5.8

**Logs**

**Comment by gouri-panda** [comment]
@heerNo1 Can you test this on our nightly [Apk](https://download.kiwix.org/nightly/2021-12-24/dev-universal-debug.apk)?

**Comment by heerNo1** [comment]
我已收到，会尽快回复！

**Comment by heerNo1** [comment]
Thanks,that works.In this debug app, it can request the permission of all files access , when I allowed it , it can read the zim I put in 0/kiwik folder
thank you guys again , it helps a lot !  ｡◕‿◕｡
