### ISSUE TITLE
WikiHow zim files are definitely not using the correct logos / icons

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2772]
From wikihow created by [Popolechien](https://github.com/Popolechien): openzim/wikihow#104  

![Screenshot wikiHow](https://user-images.githubusercontent.com/21675885/143431429-ad04ce42-6859-4fdf-ab00-0b270533edf3.png)

**Comment by kelson42** [comment]
Shouldn't it be in wikihow repo ?

**Comment by kelson42** [comment]
Sorry you'll have to move it again

**Comment by kelson42** [comment]
Could we fix it by forcing the wikiHow logo into the recipe?

**Comment by kelson42** [comment]
But it looks like a reader/catalog issue actually as those icons are not random from the ZIM but from other ZIMs

**Comment by kelson42** [comment]
It's probably because wikihow ZIMs uses new Illustration and no favicon

**Comment by kelson42** [comment]
So I'd say it's a reader issue

**Comment by kelson42** [comment]
Which ZIM file is that? Do we know if this is a problem in the `library.xml` or in Kiwix-Android?

**Comment by kelson42** [comment]
@Popolechien thx.

**Comment by kelson42** [comment]
Not sure how much of a reader issue that is: I'm looking at library.kiwix.org (kiwix-serve) and the WikiHow zim files show no icon at all.
![Capture d’écran 2021-11-25 à 12 19 56](https://user-images.githubusercontent.com/21675885/143432383-9bfb1a4a-7ae9-4691-aa15-fdf655734c6e.png)

**Comment by kelson42** [comment]
@kelson42 Not sure we can move the issue across projects (from openzim/wikihow to kiwix/kiwix-android)

**Comment by kelson42** [comment]
I will move the ticket to kiwix/kiwix-android

**Comment by kelson42** [comment]
> @rgaudin yes, even 3 times now and my question stay unanswered. I need the exact filename to make my assessment.

I don't know what else to say. Those ZIM have `Illustration_48x48` and thus no `-/favicon` entry. The library XML doesn't exposes those icons so there is no `favicon` property in those nodes.

kiwix-serve 3.1.2-5 understands there is no icon and thus displays no icon. We're aware of this ; it was discussed back in August. kiwix-android apparently isn't expecting this situation and is probably displaying an icon from the next/previous available node. 

Possible immediate fix: change the tool that generates the library.xml so it sets the favicon property from Illustration if there's no `-/favicon`.

FYI, libzim7 (at least pylibzim) doesn't allow specifying a namespace so we can't add a `-/favicon` entry to those ZIM, should we want to.

**Comment by kelson42** [comment]
@kelson42 There has only been one run so the files and file names are those in https://download.kiwix.org/zim/wikihow/

wikihow_pt_maxi_2021-10.zim
wikihow_nl_maxi_2021-10.zim
wikihow_es_maxi_2021-10.zim 
wikihow_ko_maxi_2021-10.zim

Interestingly, here is another screenshot of the same series taken at a different time - the icons have changed compared to my earlier screenshot:
![Screenshot_20211125-223320](https://user-images.githubusercontent.com/21675885/143501745-4561fe2e-a4dc-4f09-b2b3-d53310c5380e.png)

**Comment by kelson42** [comment]
@rgaudin yes, even 3 times now and my question stay unanswered. I need the exact filename to make my assessment.

**Comment by kelson42** [comment]
For some reason this ticket does not move... but it should. Config looks good.

**Comment by kelson42** [comment]
> Could we fix it by forcing the wikiHow logo into the recipe?

No. The scraper already gets the proper icon and sets it properly. It's a *new ZIM*, using the new `Illustration_` metadata for the Icon. The problem is that the reader, which uses previous version is not aware of this. You'll notice that _old_ kiwix-serve doesn't displays it either while the current one (on dev-library) does.

**Comment by kelson42** [comment]
> Which ZIM file is that? Do we know if this is a problem in the `library.xml` or in Kiwix-Android?

have you read my comments ?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

This issue seems rectify by using lib 10.1.1 for WikiHow , i am attaching the current screenshot but **if favicon is not available then its pick's up the icon of next or previous list item.** 
|wikiHow Search |Download screen|
|-----|--------|
|![Screenshot_2022-09-23-12-43-09-694_org kiwix kiwixmobile](https://user-images.githubusercontent.com/34593983/191913198-a181da65-9d1d-4e9a-8d4d-b73ff9fa69fd.jpg)|![Screenshot_2022-09-23-12-43-31-308_org kiwix kiwixmobile](https://user-images.githubusercontent.com/34593983/191913208-eaa2262b-d024-40b8-a857-ee327c00d396.jpg)     |

**Comment by kelson42** [comment]
@MohitMaliFtechiz Good news. I think a PR is need to fix the following points:
* If no illustration availabl, display default logo https://fileproinfo.com/file-type/zim#
* Stop displaying wrong logo (of precent file).
* I have seen the bug in the bookmark view yesterday, so check there as well.
