### ISSUE TITLE
How to use big zim on sdcards?

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-android#2785]
It's not exactly a bug. I want to use wikisource on an sdcard, it's 12Giga big. Impossible to copy it on the sd.
Any idea?

**Comment by kelson42** [comment]
@LAfricain what is exactly the problem with copying 12GB on the SD card?

**Comment by LAfricain** [comment]
Fat32 doesn't accept big files. I tried to split it but it's not working (I don't know why).

**Comment by kelson42** [comment]
There no recommended solution to use big ZIM files with fat32. ExFAT or any modern (and supported) filesystem shoukd be used.

**Comment by LAfricain** [comment]
Is exfat supported by android?

**Comment by kelson42** [comment]
It depends of the carrier. Samsung always does and now that exfat driver has been freed by MS, theoritically all new Android could support it.

**Comment by LAfricain** [comment]
It's working with exfat, that you!
