### ISSUE TITLE
Most downloads work, but "Low-Tech Magazine" downloads and disappears

### ISSUE THREAD

**Issue by jgoerzen** [kiwix/kiwix-android#2786]
Most downloads are working fine; the file downloads and then is visible in the library.

However, for "Low-tech Magazine", the file downloads, I get the usual "complete" confirmation, and then is NOT visible in the library.  The Android Settings -> Apps confirms that it is using storage space, but it can't be opened, or deleted, or seen in any way.  If I try to download it again, the download completes virtually instantly this time.

The same behavior can be easily replicated after clearing storage.

This is a Pixel 4a running the latest Android.

Thanks!

**Comment by gouri-panda** [comment]
@jgoerzen Which version app are you  using? Is it latest version of ours?

**Comment by jgoerzen** [comment]
It's 3.4.4 from the Play store.  (The version on f-droid seemed to be outdated.)

**Comment by jgoerzen** [comment]
I also tried the 3.4.5 apk from GitHub and it behaves the same. Just that one ZIM exhibits the issue
-- 
Sent from a mobile device. Please excuse my brevity.

Feb 27, 2022 1:08:50 AM gouri-panda ***@***.***>:

**Comment by jgoerzen** [comment]
FYI - I just tried http://download.kiwix.org/nightly/2022-03-05/ apk and although it fixes some other storage-related issues, it doesn't fix this.  I believe this is a "bug", not a "question" and is hopefully easily reproducible.  Thanks!

**Comment by kelson42** [comment]
We need to confirm here to have a repro. case.

**Comment by jgoerzen** [comment]
Sorry if I'm not quite understanding that comment - are you having trouble reproducing it?  Anything I can do to help?

**Comment by kelson42** [comment]
@jgoerzen Sorry for the late feedback but I can not reproduce this problem. Have you tried with the latest released version 3.5.0 https://download.kiwix.org/release/kiwix-android/

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 and @jgoerzen ,

I am also not able to replicate the problem.

**Comment by jgoerzen** [comment]
Looks to be solved now for me!  Thanks!
