### ISSUE TITLE
ZIM files copied into Kiwix storage dir never get listed in the app

### ISSUE THREAD

**Issue by KolyaKorruptis** [kiwix/kiwix-android#2787]
Also mentioned here: #2676

Due to Kiwix instable download mechanic, (which I won't get into here), I eventually downloaded my ZIM files on desktop and then moved them to my phone, into the same dir where other ZIM files already exist and newly downloaded ones appear. 
But ZIM files added this way never show up in the app. I tried restarting the app and the phone. 
Placing the ZIM files into external or internal storage makes no difference.

Expected behavior would be that ZIM files added to Kiwix storage get listed in the app.

- Version of Kiwix Android :  current official and current beta
- Device : Samsung Galaxy S10+ 
- OS version :  Android 12

**Comment by gouri-panda** [comment]
@KolyaKorruptis  Can you try 3.4.5 version of our app? I hope it solves your problem!

**Comment by KolyaKorruptis** [comment]
Just installed 3.4.5 from the releases here. Same problem persists. Only ZIM files downloaded via the Kiwix app are listed. Other ZIM files that sit right next to them do not show up. Again tried restarting the app and the phone to no avail.

**Comment by KolyaKorruptis** [comment]
**Log file**
[logs1645981751321.txt](https://github.com/kiwix/kiwix-android/files/8149072/logs1645981751321.txt)

**Screenshot**
![Screenshot_20220227-181229_Total Commander](https://user-images.githubusercontent.com/4076947/155892326-29a2c636-97f6-47c8-aff2-f77f6473907c.jpg)

**Comment by gouri-panda** [comment]
@KolyaKorruptis  I'm wondering did you somehow revoke the storage permission? If, so you have to give the app all files storage permission.

**Comment by KolyaKorruptis** [comment]
Kiwix 3.4.5 Build: 7230405 has the permission: **Files and Media** which I guess is the one you're referring to. I confirmed this in Android's app info. I could not find storage permission in the settings.

**Comment by gouri-panda** [comment]
@KolyaKorruptis here ![Screenshot_2022-02-27-23-19-17-93_924282dd390cc14aae1af1e29436bb16.jpg](https://user-images.githubusercontent.com/43576162/155893626-7ecf30e4-a0d4-46ff-896f-b51726864416.jpg)

**Comment by KolyaKorruptis** [comment]
Yeah, I don't have that.![Screenshot_20220227-185218_Kiwix.jpg](https://user-images.githubusercontent.com/4076947/155893732-c876c012-096f-4fc0-9236-3fdffeea3481.jpg)

**Comment by KolyaKorruptis** [comment]
Are you on the same version @gouri-panda?

**Comment by gouri-panda** [comment]
I have same APK version as yours. If it doesn't hurt , Can you reinstall the APK? We will investigate further why the permission preference doesn't show in your case? Thanks!

**Comment by KolyaKorruptis** [comment]
I uninstalled Kiwix, re-downloaded the universal release 3.4.5, installed it. Upon starting the app I got a system request whether to allow the permission for Files and Media. Just like the first I installed Kiwix, I approved that permission.

Now there is still no setting in Kiwix for Permissions as seen in @gouri-panda's screenshot. Also still only ZIM files that I downloaded via Kiwix itself are listed in the app. Other ZIM files are ignored. 

In order to make sure that this isn't a problem with the ZIM files I'm trying to add I backed up a ZIM that I had downloaded via Kiwix and that was listed in the app. Then I deleted that book from the Kiwix app. And then I moved the backup file to its original folder. Kiwix does not recognize it.

**Comment by KolyaKorruptis** [comment]
[logs1645996746343.txt](https://github.com/kiwix/kiwix-android/files/8149463/logs1645996746343.txt)

**Comment by bahbarnett** [comment]
Same problem, S22 + Android 12.

NOTE: A thought.  I don't know of another app quite like this, which maintains a database and must have files added to that database to be usable.

EG, I have book readers which just show a list of files, and I can click to open them.  I have OOo docs which I can just open from a file picker as well.

I know you guys want to present a nice interface, but at the same time, all that's required here is:

- scan the local dir
- if something is in the local, but not the database, add it to the database
- done

Storage permissions, or not, are not an issue here.  After all, people are able to download (through the app) these files, and then see them.  So it cannot have anything to do with a lack of access to the download directory.

So my thought here is ... what is the swirly 'wait' icon doing, for 5+ seconds, if not scanning the local directory for new files?  And this used to work, so it makes me think the change or issue here is minor.

I would suggest a rollback to the last known working version, or some such, until this > 2 year old issue is resolved.

**Comment by bahbarnett** [comment]
I found a copy of 3.4.4 on another phone, copied it over, and not only did it see files in the kiwix dirm but it also found other files on my SD card.  So 3.4.5 is broken for me, 3.4.4 works, on S22 + Android 12.

**Comment by KolyaKorruptis** [comment]
For what it's worth I can confirm the weirdly long display of the loading spinner. 

Also since my SDCard which was formatted as FAT couldn't hold the huge ZIM files (FAT has a 4GB file size limit) I re-formatted the card on the phone. Android didn't say which file system it used, but I was able to copy the ZIM files onto it after. 

Something else changed with this format: Now no app can access the complete SDCard anymore. When I'm giving an app access to the card Android only allows me to set access for a sub-directory - "for security reasons" as it says.

Earlier versions of Kiwix can be found in the releases of this repo: https://github.com/kiwix/kiwix-android/releases
