### ISSUE TITLE
Difference between Wikipedia en medicine and medicine maxi zim libraries

### ISSUE THREAD

**Issue by sobaee** [kiwix/kiwix-android#2790]
Hello dear developers

I need to know the difference between 2 wikipedia english medicine zim libraries founded beside each other

There is a very big difference in size

Is it worth to download the 7 gb file?

See this picture:
![Screenshot_20220326002229](https://user-images.githubusercontent.com/65910585/160202974-f4c3fb2c-4def-477f-b633-86f5eb0bd361.jpg)

**Comment by kelson42** [comment]
The biggest one can have audio/video content
