### ISSUE TITLE
Where are bookmarks stored?

### ISSUE THREAD

**Issue by H-P-W** [kiwix/kiwix-android#2794]
Forgive the lack of formatting.
I bricked my device but was able to backup the basic filesystem including a Kiwix folder, but I can't find any reference to the bookmarks. I had hundreds that I wish I could recover. Is there any way to access my bookmarks? Could I transfer any of the folders to a new android device and have the bookmarks show up?

Appreciate any guidance you have.

H

**Comment by kelson42** [comment]
@gouri-panda Can ypu help pkease here?

**Comment by gouri-panda** [comment]
@H-P-W Thank you for the report. Can you reproduce this issue? If so, please give us step by step procedure on how to produce this issue, or If you can send a Log file of the application that can help us to reproduce this issue. Thanks!

**Comment by kelson42** [comment]
@gouri-panda Where do we save the bookmarks? In the Kiwix dedicated internal storage? If "yes", usually where is the path on the internal storage?

**Comment by gouri-panda** [comment]
@kelson42 We recently stores this on our application's external directory.

**Comment by kelson42** [comment]
Thx!
