### ISSUE TITLE
 Unable to save notes in android 10 and above 

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#2797]
**Describe the bug**

 Unable to save notes in android 10 and above 

**Expected behavior**

Note Should be saved in data folder without any error.

**Steps to reproduce the behavior:**

1. After downloading ZIM file 
2. Click on Note
3. When trying to save note in Android 10 and above, Toast message displayed ” Note saved ” as showing in screenshot below but note not saved.
In Logcat Showing error mention below.

That means it’s unable to create folder in android 10 and above.

**Screenshots**
| ![Screenshot_2022-04-04-13-58-35-164_org kiwix kiwixmobile](https://user-images.githubusercontent.com/34593983/161515046-f53b0a91-d835-43f5-9d45-15540fb42552.jpg)| ![Screenshot_2022-04-04-13-58-40-660_org kiwix kiwixmobile](https://user-images.githubusercontent.com/34593983/161515057-62fd030c-2fee-4a6a-9855-d251aff9ae27.jpg) | 
| --- | :-- | 

**Environment**
- Deivce : Redmi Note 9 Pro
- OS version : Android
- Kiwix version:- 3.4.6

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz It's actually saved. If you close the dialog and then reopen it you can see your saved note.

**Comment by MohitMaliFtechiz** [comment]
Hi @gouri-panda ,

Here is my finding so far 
a) on playstore build its working.
b) on develop branch its toast a wrong message as note saved but actually its fall on condition folder not exist. please refer to
code line .

https://github.com/kiwix/kiwix-android/blob/c18fc0749fb8f3cc3f688e103a9b35b5b68797c5/core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt#L304
https://github.com/kiwix/kiwix-android/blob/c18fc0749fb8f3cc3f688e103a9b35b5b68797c5/core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt#L305
c) I close the dialog and tested again its still showing on my device.

**Comment by MohitMaliFtechiz** [comment]
Hi @gouri-panda ,

Here is my finding so far 
a) on playstore build its working.
b) on develop branch its toast a wrong message as note saved but actually its fall on condition folder not exist. please refer to
code line .

https://github.com/kiwix/kiwix-android/blob/c18fc0749fb8f3cc3f688e103a9b35b5b68797c5/core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt#L304
https://github.com/kiwix/kiwix-android/blob/c18fc0749fb8f3cc3f688e103a9b35b5b68797c5/core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt#L305
c) I close the dialog and tested again its still showing on my device.

**Comment by gouri-panda** [comment]
Hi @MohitMaliFtechiz ! Thanks for the update. On my device, it's still  working. but if you think it's possible in certain scenario then please go head raise a PR :)
