### ISSUE TITLE
Allow cross-app search using share function

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#28]
_From @Popolechien on January 4, 2017 11:39_

From the OTRS queue: 
"It would be very helpful if users could longpress to highlight a word in another app (e.g. an eBook reader) and use the Share function to send the word to Kiwix for searching its meaning. Other apps are
already doing this... for example, the offline dictionary app English  Dictionary - Offline by Livio (
https://play.google.com/store/apps/details?id=livio.pack.lang.en_US ) includes as one of its features:

"Compatible with Moon+ Reader, FBReader and other applications via share button"

Moon+ Reader and FBReader are the 2 most popular eBook Reader apps for Android with tens of millions of installs each."

_Copied from original issue: kiwix/kiwix#427_

**Comment by kelson42** [comment]
_From @mhutti1 on January 4, 2017 18:1_

@Popolechien We should now have this functionality on android 6.0+ simply by highlighting text and pressing more. It seems like a good idea if we can also implement this solution for use on older android versions though.

**Comment by kelson42** [comment]
_From @Popolechien on January 5, 2017 15:6_

Cool, thanks. I guess you can close the ticket then :-)
(for some reason I can't)

**Comment by macgills** [comment]
Sounds like this should have been closed? @kelson42 reopen if I have misunderstood
