### ISSUE TITLE
Java 8 support is changing in Android SDK's, we need to adapt :)

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#280]
While investigating a build failure I also noticed the following warnings. 

Google decided to retire their use of Jack (which provided support for Java 8 features) earlier this year. We - like several other Android projects - will need to adapt our build configuration.  e.g. https://developer.android.com/studio/write/java8-support.html  

I've taken a quick look at the build.gradle scripts for the app (which specifies Java 8) and kiwixlib which doesn't mention Java 8 or `DeSugar`ing. Ideas? 
```
Configuring Kiwix
Configuring customexample
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /usr/local/android-sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
```

**Comment by mhutti1** [comment]
I thought the reason that they retired Jack was that it was made obsolete by its benefits being made default. I'm not sure why they are warning us it is disabled though.

**Comment by kelson42** [comment]
@mhutti1 @julianharty 
This seems to be a common error which does not appear with newer version of build tools. See
https://stackoverflow.com/questions/45020207/errorjack-is-required-to-support-java-8-language-features-either-enable-jack-o/45054748

As far as I can see, the warning does not appear anymore. See
https://travis-ci.org/kiwix/kiwix-android

I propose therefore to close that ticket.

**Comment by brijeshshah13** [comment]
@mhutti1 As the support for Java 8 has been included in the `app` level `build.gradle`, this issue can be closed.

**Comment by mhutti1** [comment]
Agreed lets close it then.
