### ISSUE TITLE
Search inside custom zim file is not getting you to the page you want

### ISSUE THREAD

**Issue by LTVA1** [kiwix/kiwix-android#2812]
**Describe the bug**
I made a zim file with zimwriterfs on Windows 10. When I open the kiwix desktop app and navigate to my zim file (1.9 gb) and try to use search, it gives me the correct results, but when I use Android app and click on one of them, the app just reloads the current page and does not move to the page I need.

**Expected behavior**
Obviously, I expected the search to work and the app go to the page.

**Steps to reproduce the behavior:**
1. Create .zim file with the command ```docker run --mount type=bind,source=C:/Users/%User%/Desktop/site,target=/home/docker/zimwriterfs/data openzim/zim-tools zimwriterfs -w index.html -I icon.png -l rus -t "Фонд SCP" -d "Русскоязычный сайт коллективного литературного творчества" -c "SCP Foundation" -p "LTVA" //home/docker/zimwriterfs/data/test //home/docker/zimwriterfs/data/scp-wiki-ru-05-2022-maxi.zim -x -i``` using Docker desktop on Windows 10. Make sure you included some visible icon and have some pages with external links (e.g. ```http://some.site.foo/bar```) in your root html folder.
2. Check if zim file works correctly and search works and allows you to move to the desired page in kiwix desktop app.
3. Use nightly build 28.04.2022 to open the zim file you previously put into root directory of your smartphone internal storage. You should experience the same search malfunction.

**Environment**
- Version of Kiwix Android : nightly build 28.04.2022.
- Device : xiaomi mi note 8 pro
- OS version : Android 11, MIUI 12

**Comment by LTVA1** [comment]
P.S. I tried to manually move one of the zim files downloaded by kiwix (iirc some Wikipedia articles selection) into root folder and kiwix successfully searches and allows you to navigate to different pages of this file via search.

**Comment by kelson42** [comment]
@LTVA1 Looking again to this ticket. I hardly understand how you made a ZIM file under Windows, considering that `zimwriterfs` is not distributed for Windows!

Here two things are missing to reproduce the bug:
* The ZIM file itself
* The exact procedure of searching (what do you type and where, what do you get exactly and what you expect

Would you be able please to provide this?

**Comment by MohitMaliFtechiz** [comment]
hi @LTVA1 ,

I tried generate zim file but it was given lots of error by  running above command so its better if you provide me the zim file so i can further investigate this issue.

**Comment by kelson42** [comment]
No feedback, closing.
