### ISSUE TITLE
Mime type of .js for archlinux zim file needs to fix.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#2813]
**Describe the bug**
Mime type for Node.js files is ```text/html``` but needs to update as ```application/javascript```

File link :- 
https://download.kiwix.org/zim/other/archlinux_en_all_nopic_2022-03.zim
For "big" wikipedia ZIM seems all other pages are broken also (backbone.js, ember.js, vue.js).

**Expected behavior**
Mime type must be ```application/javascript```

**Environment**
- Version of Kiwix Android : 3.4.4
- Device : Samsung s9
- OS version :  android 10

**Comment by kelson42** [comment]
Should be moved to openzim/mwoffliner.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Do you talk about this article? http://library.kiwix.org/archlinux_en_all_nopic_2022-04/A/Node.js ? The mimetype text/html is correct then.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Do you talk about this article? http://library.kiwix.org/archlinux_en_all_nopic_2022-04/A/Node.js ? The mimetype text/html is correct then.

Yes we are talking about that article in android js file mime type is ```application/javascript```.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

I think i don't have access to move this issue to openzim/mwoffliner , transfer issue does not pop me up any repo.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I will move it.

**Comment by kelson42** [comment]
@MohitMaliFtechiz The ZIM file is correct, mime-type in the ZIM is `text/html`, see:
```
$ zimdump list --details --url=Node.js archlinux_en_all_maxi_2022-04.zim 
path: A/Node.js
	title:           Node.js
	idx:             8727
	type:            item
	mime-type:       text/html
	item size:    11718
```

**Comment by kelson42** [comment]
@gouri-panda @MohitMaliFtechiz Might that be that we have the JNI doing some kind of magic with the mimetype? Is the mime-type wrong just out of the JNI? Or made wrong later?

**Comment by gouri-panda** [comment]
@kelson42 We will check that 👍
