### ISSUE TITLE
MIME type for Bouquineux file is wrong needs to fix.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#2814]
**Describe the bug**
MIME type for Bouquineux is returning as ```text/html;``` but needs to correct as ```text/html``` without semicolon. 

File Link :-  https://download.kiwix.org/zim/other/bouquineux_fr_all_2013-07.zim

**Expected behaviour**
file must return ```text/html``` without semicolon.

**Comment by rgaudin** [comment]
@MohitMaliFtechiz this doesn't look like a kiwix-android issue. Bouquineux was created using [warc2zim](https://github.com/openzim/warc2zim/) so it's probably more appropriate there.

Now on the issue itself, you should provide the URL (or path) of the Entry with which you're having difficulties.

I believe there are no entries with `text/html;` MIME types but `text/html;raw=true` is to be expected. It's done on purpose. Can you explain why this is problematic to you?

**Comment by kelson42** [comment]
@MohitMaliFtechiz Mime-type with semi-colon is correct, see specification https://en.wikipedia.org/wiki/Media_type. We really uses this. You have somehow to handle it is kiwix-android.

**Comment by kelson42** [comment]
@rgaudin This bouquineux ZIM file was not created wit Warc2zim... but 10 years ago with zimwriterfs.

**Comment by rgaudin** [comment]
Ah I didn't look at the date in the URL. Interestingly both uses extended MIME attributes 😉

**Comment by MohitMaliFtechiz** [comment]
hi @rgaudin @kelson42  ,
this issue was occurred  earlier where we made custom fix in android to handle particular this condition https://github.com/kiwix/kiwix-android/issues/2174.I have just removed the condition where this problem is explicitly. @kelson42 if that needs to handle at android end then we have to place filter like we were doing earlier we just cannot take directly mime type from zim file because that may breaks the rendering.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Why not just removing what is after the semi colon?

**Comment by MohitMaliFtechiz** [comment]
ok @kelson42  we can do that.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Once fixed, please check a file like http://download.kiwix.org/zim/zimit/musictheory.net_en_all_2021-12.zim continues to displayed properly.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Once fixed, please check a file like http://download.kiwix.org/zim/zimit/musictheory.net_en_all_2021-12.zim continues to displayed properly.

ok sure
