### ISSUE TITLE
Error 495 happens when trying to download (Wikimed)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#282]
Am just escalating to an issue as I had several similar reports over the past 72 hours.

**Comment by kelson42** [comment]
@Popolechien You mean the download of the Android Wikimed app through the Google Play app?

**Comment by Popolechien** [comment]
Correct. Normally I don't think the problem is on our side, but just in case to get confirmation next time it's reported to us.

**Comment by kelson42** [comment]
Yes, this is the "typical" google play app download problem. Nothing we can really do about it. At least, we do nothing wrong.
