### ISSUE TITLE
Jcenter dependency: androidx.tonyodev.fetch2

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#2826]
**Describe the bug**
We are using https://github.com/tonyofrancis/Fetch for downloading the file in our app. Its dependent on Jcenter.

I found that this library is being already moved to jitpack repo.

## https://github.com/tonyofrancis/Fetch/issues/586#issuecomment-954225519

Part of #2816

**Comment by MohitMaliFtechiz** [comment]
Hi @kelson42 , I also found that this library is not maintained from past 2 year we must also started finding alternative for this library. for now we can use jitpack.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Considering the Jcenter deprecation, maybe people talk about Jitpack as an alternative. But what is Jitpack? How is that different from Jcenter or Maeven? Considering Fetch library, who has moved to Jitpack? The author of the plugin or someone else? Can we trust the code there?

In general with Fetch, it seems there is another problem: the code seems unmaintained! Is that reasonable to continue to use it even for only a year?

**Comment by MohitMaliFtechiz** [comment]
https://github.com/kiwix/kiwix-android/issues/2816

**Comment by kelson42** [comment]
@MohitMaliFtechiz OK, so if not too complicated, agree to use Jitpack in place JCenter for this lib. Then we could discuss its deprecation.
