### ISSUE TITLE
Jcenter dependency: io.objectbox:objectbox

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#2828]
### Describe the bug
We are using ```io.objectbox:objectbox```  for database operations. Version we are using 2.8.1 is available on jcenter while higher version are available on maven central. 

Maven Central have 3.1.3 as latest version. I am updating to this version.
https://mvnrepository.com/artifact/io.objectbox/objectbox-android

Part of #2816

**Comment by MohitMaliFtechiz** [comment]
Hi ,
I tired with version 3.1.3 lots of issue , we need to refactor code to support latest version for now i am upgrading to version 2.9.1 which is working fine.

**Comment by MohitMaliFtechiz** [comment]
Hi ,
I tired with version 3.1.3 lots of issue , we need to refactor code to support latest version for now i am upgrading to version 2.9.1 which is working fine.

**Comment by kelson42** [comment]
@gouri-panda Probably, but for the moment the priority is mostly to get rid of jcenter.
