### ISSUE TITLE
Jcenter dependency:com.yahoo.squidb:squidb

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#2830]
**Describe the bug**
We are using com.yahoo.squidb:squidb for database operations. Must move to maven central.

Part of https://github.com/kiwix/kiwix-android/issues/2816

**Comment by kelson42** [comment]
This ticket is interesting https://github.com/google/j2objc/issues/325. Would it be complicated to use instead native `android.database.sqlite` ?

**Comment by gouri-panda** [comment]
We can use Room. It's Android's recommendation way to create Database. Why do we need cross platform API?

**Comment by kelson42** [comment]
@gouri-panda The only point which is important to me is that the stroage format does not change.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 and @gouri-panda , I have check Room database replacement it will involve lots of refactoring of code. I think we should work on refactoring in another milestone since many libraries needs to updated or replaced which are not maintained.

For now i think we can use jitpack for this library https://jitpack.io/p/yahoo/squidb
