### ISSUE TITLE
Jcenter dependency: com.pacioianu.david:ink-page-indicator

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#2831]
**Describe the bug**
This library is only used for page indicator on intro fragment so i think best is to customised code without using this library since its only used for intro screen. 

This library is also not maintained or available in maven or jitpack.

part of #2816

**Comment by kelson42** [comment]
What is « page indicator »? I don’t really understand the feature here. Can we not simply avoid to use it?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

The page indicator only did a animation on navigation between intro pages. We can avoid it if you want well i am almost done with the change to parse it into our code.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thx for the clarification. Lets keep it, it is not in a critical part of the app.
