### ISSUE TITLE
Large Downloads Are Halted 3.4.5 (7230405)

### ISSUE THREAD

**Issue by NaegelC** [kiwix/kiwix-android#2845]
**Describe the bug**

Downloading large files like the 88.7 GB wikipedia_en_all_maxi_2022-05.zim has repeatedly failed/halted due to "UNKNOWN_HOST".

**Expected behavior**

The download should continue as normal.

**Steps to reproduce the behavior:**
1. Start a fresh session of Kiwix.
2. Go to the Download tab.
3. Use the search function and enter "wikipedia".
4. Tap on the the 88.7 GB file to begin the download.
5. Press the power button to allow the screen to sleep.
6. Check in periodically until the download has failed due to UNKNOWN_HOST.

**Environment**
- Version of Kiwix Android : 3.4.5 Build 7230405
- Device : Samsung A50
- OS version : Android 11

**Logs**

[logs1653249667183.txt](https://github.com/kiwix/kiwix-android/files/8750183/logs1653249667183.txt)

Additional notes:

I am able to download smaller .zim files, and the SD card has hundreds of GBs in available space.

I did not test the latest developer's version, as I'm not sure where I would find that. I tried http://download.kiwix.org/nightly/2022-05-22/, but the only .apk listed is a debug tool. 

I used developer options to force the screen to stay awake, but still ran into the same problems. 

My internet is mostly reliable, and the phone automatically switches to data during any downtime.

I'm only having this problem because the .zim file I downloaded on my PC and placed into my micro SD card isn't being detected by the app, so I'm forced to download it via the app.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

This is due to network fluctuation , so basically its network issue we can increase Read and Write timeout and autoRetryMaxAttempts. Let me know if that helps.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

Current  autoRetryMaxAttempts = 10 and  Read and Write timeout is default as 20 sec

**Comment by kelson42** [comment]
@MohitMaliFtechiz So after 200s failing, there is an error? Even if there is no network at all?

**Comment by MohitMaliFtechiz** [comment]
yes @kelson42 , there was error as ```UNKNOWN HOST```

**Comment by kelson42** [comment]
@MohitMaliFtechiz If there is no network at all, it just not zry to download. I'm sure Android providrs an API to know that.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

Yes there is check for no network and yes we can add this strategy to retry and prompt message to user.
