### ISSUE TITLE
Not possible to jump to sections in Table of Contents containing single quote

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2849]
- Kiwix 3.4.5
- Article: List of creepypastas
- [wikipedia_en_all_maxi_2022-05.zim](https://de.wikipedia.org/wiki/Der_Patriot_(Tageszeitung))
- Log: 
[logs1653416153136.txt](https://github.com/kiwix/kiwix-android/files/8765420/logs1653416153136.txt)

Selecting `Hi I'm Mary Mary` does nothing, as it contains a single quote.

![20220524_203942](https://user-images.githubusercontent.com/71934042/170108677-197b0af7-d0ff-4c7b-b641-1134c488bddb.gif)

**Comment by kelson42** [comment]
@MohitMaliFtechiz Reassigning to you, seems straight forward to me... probably a kind of escaping problem.
