### ISSUE TITLE
Unable to open local zim file

### ISSUE THREAD

**Issue by NielsGx** [kiwix/kiwix-android#2852]
I dom't get where I should put my zim files for the app to detect them.

I tried in android/data/kiwix folder/Kiwix, like where are the zim files downloaded trough the gui, but doesn't work.

Your readme doesn't even explain this.

A bit weird for an app that is made for offline usage.
Also it's a handmade zim file with zimit, so it isn't on the download thing, obviously

thanks

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you please help?

**Comment by MohitMaliFtechiz** [comment]
hi @NielsGx ,

Thank you for reaching out at kiwix, can you let us know which kiwix version you are using ? so i can better assist you with your problem ?

**Comment by NielsGx** [comment]
hi, it's version 3.4.5 from the android play store.

Basically I tried to put it in storage/emulated/0/Android/data/org.kiwix.kiwixmobile/files/Kiwix/myfile.zim

the file had spaces, maybe it's an issue

also I tried to open the .zim with Kiwix, through Solid Explorer. I do open with > all > Kiwix
and the app opens and on the library page the load logo is spinning but no new entry with my zim file, even if I wait like 10mins (the file is only 50mb, used --limit 50 in zimit)

the file doesn't seem corrupted, as I can open it if I download "Off the grid" through the gui then replace it's file (100r-off-the-grid_2022-03.zim) with my own and open it through the app

Thanks a lot for your help and quick reply

**Comment by NielsGx** [comment]
Actually if I force close the app then try to open the .zim through solid explorer, kiwix starts then directly crash.

**Comment by MohitMaliFtechiz** [comment]
hi @NielsGx ,

can you please try 3.5.0 [kiwix apk](https://download.kiwix.org/release/kiwix-android/kiwix-3.5.0.apk).

Thanks and Regards
Mohit Mali

**Comment by kelson42** [comment]
@NielsGx Any feedback?

**Comment by kelson42** [comment]
No feedback, I have to close this ticket.
