### ISSUE TITLE
`Field` s instance doesn't create properly in database testing

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2872]
In new version  tried ```Query.select()``` but i was getting error , I have also tried with query with parameter but that was also not working so i changed it to any()

_Originally posted by @MohitMaliFtechiz in https://github.com/kiwix/kiwix-android/pull/2838#discussion_r896790525_

**Comment by kelson42** [comment]
@gouri-panda What is the new version you talk aboit exactly? What are the reproduction steps? Is that a regression?

**Comment by gouri-panda** [comment]
@kelson42 The description was come from [this](https://github.com/kiwix/kiwix-android/pull/2838#discussion_r896790525) In #2838 we increment the squidb library version that's why . We haven't merged yet that PR, so it's not regression yet. I think it's a future bug .
cc @MohitMaliFtechiz

**Comment by kelson42** [comment]
ok, then we should close this ticket and comment/fix the appropriate PR.
