### ISSUE TITLE
Upgrade to Kotlin 1.7.0

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2873]
**Is your feature request related to a problem? Please describe.**
A new version of kotlin has been released with stabilizes language features and brings performance improvements for the JVM.

**Describe the solution you'd like**
An upgrade to kotlin 1.7.0 with a migration run to fix any potential issues and improve the performance.

**Comment by kelson42** [comment]
How much woek is needed her? What are the benwfits?

**Comment by gouri-panda** [comment]
Not so much, i would think!

**Comment by kelson42** [comment]
OK, putting in the next release.
