### ISSUE TITLE
The app gives me an error message whenever I try to open pdf files inside zim ones (Kiwix 3.5.0)

### ISSUE THREAD

**Issue by asereze** [kiwix/kiwix-android#2882]
**Describe the bug**
I've downloaded and tried many zim files from the app, but some of them, the ones with PDFs inside, give me error messages. Every time I click on one of them (for example, the pic is from the "Post Disaster Resource Library") the app tells me that I don't have an app installed for that kind of data, while I do.

**Expected behavior**
I expected to be able to open the different sections of the zim file.

**Steps to reproduce the behavior:**
1. Download 'Post Disaster Resource Library'
2. Click on it in the Library
3. Click on any section

**Screenshots**
![photo_2022-06-26_12-50-52](https://user-images.githubusercontent.com/11271324/175810720-fe195d0a-db7e-497f-85a1-ba9895396f6c.jpg)

**Environment**
- Version of Kiwix Android : 3.5.0
- Device : Xiaomi Redmi Note 9 pro
- OS version : LineageOS 18.1 (Android 11)

**Comment by kelson42** [comment]
@asereze Thank you for your bug report. A few days ago, in the development branch, many bugs related to PDF handling have been fixed. Woukd you be able to give a try with latest nightly? http://download.kiwix.org/nightly/2022-06-26/dev-universal-debug.apk

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please have a look to this ticket. Maybe you already have fixed it.

**Comment by asereze** [comment]
> @asereze Thank you for your bug report. A few days ago, in the development branch, many bugs related to PDF handling have been fixed. Woukd you be able to give a try with latest nightly? http://download.kiwix.org/nightly/2022-06-26/dev-universal-debug.apk

Yes, I tried it right now and with that version it works!

**Comment by kelson42** [comment]
@asereze Good to hear, then this bug will be fixed in next release, hopefuly to be released in July.
