### ISSUE TITLE
Back button after opening a search result closes the app

### ISSUE THREAD

**Issue by opk12** [kiwix/kiwix-android#2886]
**Describe the bug**
Pressing Back closes the app, if you have opened an article from the search result list.

**Expected behavior**
It should bring you back to the search result list.

**Steps to reproduce the behavior:**
- Open article A.
- Follow a wikilink to B.
- Press Back. It brings to A, as expected.
- Click the magnifying glass.
- Press Back. It brings to A, as expected.
- Click the magnifying glass, search for an article and open it.
- Press Back. The app closes. Instead, the app should go back to the search result list.

**Environment**
- Version of Kiwix Android : Both 3.5.0 and 3.4.1 from F-droid
- OS version : Android 10, Android 7.1.1

**Comment by kelson42** [comment]
@opk12  I confirm the behaviour. But to me it should not go back to the search result list, but to the article A!
@MohitMaliFtechiz Could you please fix this bug? For an unknow reason, it seems that loading an article from the search, just empty the navigation history, which should not be the case.
