### ISSUE TITLE
Introduce file/directory picker instead of file scanning

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-android#2890]
Currently, the Kiwix Android app uses a file scanner to detect ZIM archives in the Android file system and on external microSD cards. However, this is problematic for a number of reasons:

* It is the main reason the [app is being rejected](https://github.com/kiwix/kiwix-android/issues/2819#issuecomment-1142067233) by the Play Store;
* The file scanning process incorporates a big file test which [damages flash memory](https://github.com/kiwix/kiwix-android/issues/2889);
* Privacy-conscious users are wary of granting such wide permissions to any app - and there are [alternative APIs](https://developer.android.com/training/data-storage/use-cases#handle-non-media-files) that respect privacy;
* It [simply doesn't work](https://github.com/kiwix/kiwix-android/issues/2787) for many users, probably due to differences in implementation of file access in different Android implementations and versions.

All of this is unnecessarily complicated. Instead of trying to locate ZIM archives automatically, trust the user to know where they have stored their files, and let the user pick the directory containing their archives (and let them pick a new one whenever they wish). This directory can be used for storing downloaded ZIMs too. This would, IMHO, be **much more** user friendly than the currently opaque file scanning over which the user has no control. The file/directory picker permission is standard, and does not require special permission from Google. It returns control to the user...

**Comment by kelson42** [comment]
@Jaifroid There is a filepicker already in 3.5.0.

**Comment by Jaifroid** [comment]
@kelson42 I don't have this version (due to the Play Store issue). In the Play Store version of the app, will it replace the file scanner, and allow users to access archives in the directory of their choice, with persistent permission? If so, then this issue would be fixed in the next Play Store version, when released.

**Comment by kelson42** [comment]
We build a customised version for the PlayStore. This is the version 3.6.0. This version does not allow to read any ZIM file but only a dedicated app directory (but only the version in PLayStore, other versions work like before). This directory can be placed on the SD card. There is nothing more we can do because of Google. @MohitMaliFtechiz you confirm please?

I strongly recommend in the future to download Kiwix from F-Droid https://f-droid.org/. The version there does not suffer of these linitations.

**Comment by Jaifroid** [comment]
@kelson42 OK, that's good to know. Regarding using Play Store vs F-Droid versions, I think it's important to have some Kiwix insiders testing and using regularly the Play Store version, because realistically it will be the dominant version (much though I don't like Google's quasi-monopoly...).

Maintaining the File Scanner in a separate version of the app on F-Droid could still raise privacy concerns for some users (the ostensible reason Google restricts use of this API).

**Comment by MohitMaliFtechiz** [comment]
> We build a customised version for the PlayStore. This is the version 3.6.0. This version does not allow to read any ZIM file on the fs but only from a dedicated app directory (but only the version in PLayStore, other versions work like before). This directory can be placed on the SD card. There is nothing more we can do because of Google. @MohitMaliFtechiz you confirm please?
> 
> I strongly recommend in the future to download Kiwix from F-Droid https://f-droid.org/. The version there does not suffer of these limitations.

Yes I confirm, on Play-Store version we will not have file picker while F-Droid version will have this functionality.

**Comment by Jaifroid** [comment]
> Yes I confirm, on Play-Store version we will not have file picker while F-Droid version will have this functionality.

I don't understand what stops you using a directory picker for the Play Store version. There is no restriction on using the ACTION_OPEN_DOCUMENT_TREE intent (other than not being able to open the Root directory or the Download directory). See https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory which has code samples. As the guide says:

> This user-controlled access allows users to choose exactly what content they're comfortable sharing with your app.

**Comment by MohitMaliFtechiz** [comment]
> > Yes I confirm, on Play-Store version we will not have file picker while F-Droid version will have this functionality.
> 
> I don't understand what stops you using a directory picker for the Play Store version. There is no restriction on using the ACTION_OPEN_DOCUMENT_TREE intent (other than not being able to open the Root directory or the Download directory). See https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory which has code samples. As the guide says:
> 
> > Because the user is involved in selecting the files or directories that your app can access, this mechanism doesn't require any [system permissions](https://developer.android.com/guide/topics/permissions/overview), and user control and privacy is enhanced. Additionally, these files, which are stored outside of an app-specific directory and outside of the media store, remain on the device after your app is uninstalled.

hi @Jaifroid , On android 11 and above cannot use it on root, download, and other app-specific folders so what is used since all Zim file will auto-populate on the app-specific folder. I tried it it's not allowed to read files while giving ``` MANAGE_EXTERNAL_PERMISSION``` it will enable reading all but this permission is being denied on play store to upload the build.

```
On Android 11 (API level 30) and higher, you cannot use the ACTION_OPEN_DOCUMENT_TREE intent action to request access to the following directories:

The root directory of the internal storage volume.
The root directory of each SD card volume that the device manufacturer considers to be reliable, regardless of whether the card is emulated or removable. A reliable volume is one that an app can successfully access most of the time.
The Download directory.
Furthermore, on Android 11 (API level 30) and higher, you cannot use the ACTION_OPEN_DOCUMENT_TREE intent action to request that the user select individual files from the following directories:

The Android/data/ directory and all subdirectories.
The Android/obb/ directory and all subdirectories
``

**Comment by Jaifroid** [comment]
@MohitMaliFtechiz The Android 11 guide linked above clearly states that you don't need that permission (MANGE_EXTERNAL_PERMISSION) to use the ACTION_OPEN_DOCUMENT_TREE file picker. You don't need any system permissions at all. Yes, you can't open the root directory, but user will be told that if they attempt to open root or attempt to open Downloads. Other than that, user is free to pick directory of their own choosing. As the guide says, "user control and privacy are enhanced" this way.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz The Android 11 guide linked above clearly states that you don't need that permission (MANGE_EXTERNAL_PERMISSION) to use the ACTION_OPEN_DOCUMENT_TREE directory picker. You don't need any system permissions at all. Yes, you can't open the root directory, but user will be told that if they attempt to open root or attempt to open Downloads. Other than that, user is free to pick directory of their own choosing. As the guide says, "user control and privacy are enhanced" this way.

ok I will take a look once again.

**Comment by Jaifroid** [comment]
> Basically in android 11 ,framework is restricted to access file which is not created by the app on External Storage. you can only granted access of a file which is non root , non download _**and which is created by the app itself**_.

@MohitMaliFtechiz The last bit above ("and which is created by the app itself") is not part of the restriction when using the Storage Access Framework API. The relevant part of your graphic shows this (see circled below). The user doesn't need access to root and doesn't need access to the Downloads folder. What the user needs is access to a folder of their own choosing where they'd like to store ZIM archives, and this is perfectly possible using the system file picker **without** MANAGE_EXTERNAL_PERMISSION (in fact it **must not** be declared).

![image](https://user-images.githubusercontent.com/4304337/177989010-f936cd5f-dc04-4bc5-872b-f1b5d58a93a1.png)

The guide makes this clear:

> these files, which are stored outside of an app-specific directory and outside of the media store, remain on the device after your app is uninstalled.

This is completely different from app-specific storage.

**Comment by MohitMaliFtechiz** [comment]
hi @Jaifroid ,

Yes I agreed to your point that files will not lost when we uninstall the app but only those files which are downloaded from app , we can ask user to select folder which will use to download the zim files but if users just copied any zim file from external system like PC or any other app to that folder it will not work while with app specific if user can copied to its directory from any external source like copied from PC  etc it will work. 

Please confirm the scenario so i can implement it.

**Comment by Jaifroid** [comment]
@MohitMaliFtechiz I don't think your interpretation is quite right here. The user can download ZIM files in their browser and add them to the selected directory, or transfer them from PC into that directory. As the graphic says, these are files "contributed by other apps", e.g. by a Web browser or file explorer application. They are files that are **_not_** in an app-specific directory. Of course the user cannot pick those files from the Download folder, so they have to move the files into their ZIM folder using file management.

This is similar to the way the file picker in the Web browser works (on Android). You can try it by picking a ZIM stored in an arbitrary location in https://pwa.kiwix.org (on Chrome or Samsung browser on Android). Permission is not persisted, however, in the browser.

There must be something wrong in the way this is set up in your test. The guide clearly states:

> File management and media-creation apps typically manage groups of files in a directory hierarchy. To provide this capability in your app, use the [ACTION_OPEN_DOCUMENT_TREE](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE) intent action, which allows the user to grant access to an entire directory tree, with some exceptions starting in Android 11 (API level 30). **Your app can then access any file in the selected directory and any of its sub-directories.**
> 
> When using ACTION_OPEN_DOCUMENT_TREE, your app gains access only to the files in the directory that the user selects. You don't have access to other apps' files that reside outside this user-selected directory. This user-controlled access allows users to choose exactly what content they're comfortable sharing with your app.

**Comment by Jaifroid** [comment]
NB Make sure you're not trying to access files from:

* The Android/data/ directory and all subdirectories.
* The Android/obb/ directory and all subdirectories.

The API doesn't give access to those locations, as it says in the guide.

**Comment by MohitMaliFtechiz** [comment]
> 
On my current scenario , I have create zim file inside Document folder by our app and also copied one zim file from computer , after implementing the ```Storage Access Framework``` , I was able to fetch the file which my app created but the one copied is failing ok I am looking at it further

**Comment by MohitMaliFtechiz** [comment]
hi @Jaifroid ,

Just to update you I developed a two small application , app1 which is writing a file ```a.txt``` under ```Download/Kiwix``` and app2 which is writing a file ```b.txt``` under  ```Download/Kiwix``` . I am sharing my finding on below point

a) app1 can access ```a.txt``` but failed to read ```b.txt``` even its on shared storage.
b) Simlarly app2 can access ```b.txt``` but failed to read ```a.txt```.
c) I download the file from browser and placed inside ```Download/Kiwix``` then none app1 and app2 can access that copied file.
d) Interestingly if I cleared the storage and cache of app1 after creating the file ```a.txt``` then app1 also not able to read even ```a.txt``` so i think its all about ownership of file and Storage Access Framework will return the files which individual app want's to shared and they need to make Doucment Provider within the app so that other app can access those files.

I am still looking at it since many pdf application reads files after downloading it how they achieve it I am still wondering may be they have ```MANAGE_EXTERNAL_PERSMISSION``` or we are missing something.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Is that not trivial to verify which permissions are needed by a random app?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

if we figured it out is there is way other then ```MANAGE_EXTERNAL_PERMISSION``` which these apps is using then we can have file picker working on play store build.

**Comment by Jaifroid** [comment]
@MohitMaliFtechiz Are you sure your apps are using the DIRECTORY picker rather than the FILE picker? That behaviour, where an app has access only to one file in a directory, sounds very much like only one file was picked. If you are using a directory picker, AND you are not requesting MANAGE_EXTERNAL_PERMISSION, AND you are picking a folder external to the app's data directory, then the behaviour is not as described by the Android 11 documentation. I wish I had some Android dev experience to help troubleshoot. As you can tell, I think it is really important for Kiwix that a solution should be found that doesn't require users to install from other stores.

**Comment by julianharty** [comment]
@MohitMaliFtechiz you mentioned you've created two small Android applications in https://github.com/kiwix/kiwix-android/issues/2890#issuecomment-1179546262 If you're able to share your code for your small test apps please can you do so e.g. in a GitHub repo? And perhaps you could also include the APK files for each of these small apps which might help @Jaifroid and anyone else use these apps easily on their Android device. We can then experiment with these small apps to find a viable solution which we can then integrate into the core Kiwix app.

**Comment by julianharty** [comment]
@MohitMaliFtechiz a quick question, have you tried https://github.com/braver-tool/Android11FilePicker in combination with your two small apps? for instance, can it access the files your apps create?

**Comment by MohitMaliFtechiz** [comment]
hi @Jaifroid and @julianharty , 

I think after going through the https://github.com/braver-tool/Android11FilePicker , i understand how other apps read other file apps data on android 11 and above.
let me explain you on following points.
a) So basically what this kind of https://github.com/braver-tool/Android11FilePicker does is they just copy the file into their cache and create a ```temp file ``` so after creating temp file ownership of that file belongs to that requested app so they able to read it.
b) You can check the file picker code https://github.com/braver-tool/Android11FilePicker/blob/main/picker/src/main/java/com/braver/tool/picker/BraverDocPathUtils.kt#L17.

``` companion object {
        @SuppressLint("Range")
        fun getSourceDocPath(
            context: Context,
            uridata: Uri
        ): String? {
            var displayname = ""
            var size = 0
            val contentResolver = context.contentResolver
            if (contentResolver.equals(null)) {
                return null
            }
            contentResolver.query(
                uridata, null, null, null, null, null
            )?.use {
                if (it.moveToFirst()) {
                    displayname = it.getString(it.getColumnIndex(OpenableColumns.DISPLAY_NAME))
                    size = it.getColumnIndex(OpenableColumns.SIZE)
                }
            }
            //val filepath = context.applicationInfo.dataDir + File.separator + userID + "_" + System.currentTimeMillis() + displayname
            val filepath =
                context.filesDir.absolutePath + File.separator + "_" + System.currentTimeMillis() + displayname
            val splitName = filepath.substring(filepath.lastIndexOf('/') + 1)
            val file = File(filepath)
            try {
                val inputStream = contentResolver.openInputStream(uridata) ?: return null
                val outputStream = FileOutputStream(file)
                val bufferbyte = ByteArray(1024)
                var len: Int
                while (inputStream.read(bufferbyte)
                        .also { len = it } > 0
                ) outputStream.write(bufferbyte, 0, len)
                outputStream.close()
                inputStream.close()
            } catch (e: Exception) {
                return ""
            }
            Log.d("##file.name", "-------->" + file.name)
            Log.d("##file.uridata", "-------->$uridata")
            Log.d("##file.splitName", "-------->$splitName")
            Log.d("##file.size", "-------->$size")
            Log.d("##file.absolutePath", "-------->" + file.absolutePath)
            return file.path
        }```

c) So if we going to implement the above file picker then we need to create temp file every time someone select the zim and our zim file is of size in ```GB``` so to me its not optimise solutions.

I have placed the apk and source code of reading directly via System file picker and reading and copying file and then opened it. 
https://github.com/MohitMaliFtechiz/android-11-file-picker-demo

**Comment by julianharty** [comment]
@MohitMaliFtechiz Thank you for investigating that project https://github.com/kiwix/kiwix-android/issues/2890#issuecomment-1183202716 I agree with you and with @kelson42 their approach is not viable for the Kiwix Android app. 

Please could you share your source for your mini apps you mentioned earlier? I'd still appreciate being able to see what's happening based on your experiements.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Thank you for investigating that project https://github.com/kiwix/kiwix-android/issues/2890#issuecomment-1183202716 I agree with you and with @kelson42 their approach is not viable for the Kiwix Android app. 
> 
> Please could you share your source for your mini apps you mentioned earlier? I'd still appreciate being able to see what's happening based on your experiments. 

Hi @julianharty ,

Link was already there on my finding let me send you again https://github.com/MohitMaliFtechiz/android-11-file-picker-demo

**Comment by julianharty** [comment]
> > @MohitMaliFtechiz Thank you for investigating that project [#2890 (comment)](https://github.com/kiwix/kiwix-android/issues/2890#issuecomment-1183202716) I agree with you and with @kelson42 their approach is not viable for the Kiwix Android app.
> > Please could you share your source for your mini apps you mentioned earlier? I'd still appreciate being able to see what's happening based on your experiments.
> 
> Hi @julianharty ,
> 
> Link was already there on my finding let me send you again https://github.com/MohitMaliFtechiz/android-11-file-picker-demo

My bad... when I read the name of the project I got the impression it was your clone of the https://github.com/braver-tool/Android11FilePicker project... Thank you :)

**Comment by Jaifroid** [comment]
@MohitMaliFtechiz I notice that the Android File Picker you are looking at depends on the READ_EXTERNAL_STORAGE permission, whereas the API we're discussing requires no austen permissions at all, because the user provides permission explicitly through a directory picker. Could you confirm whether your test code reads a directory and enumerates is contents, or whether the code picks a specific file only?

**Comment by MohitMaliFtechiz** [comment]
Hi @Jaifroid ,

In Demo we are granting access to Directory via file picker not specifically for file.

**Comment by Jaifroid** [comment]
If the ACTION_OPEN_DOCUMENT_TREE API is set up correctly, the user should be asked to pick a directory, not a file within it. According to the [API documentation](https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory), once the directory is picked "your app can then access any file in the selected directory and any of its sub-directories".

It would be worth testing this in the demo app by picking a directory of ZIM archives that have been transferred from PC on a test device, and then enumerating and displaying in a message box the contents (e.g. file names) of the directory after the user has picked the directory. Remember that the enumeration would need to happen inside the [onActivityResult](https://developer.android.com/reference/android/app/Activity#onActivityResult(int,%20int,%20android.content.Intent)) code block.

**Comment by Jaifroid** [comment]
Thank you for trying. It's a real shame it's not working out. Maybe some sample code that makes this possible will emerge over time as devs wrestle with these APIs. I have noticed some Android apps explicitly asking me for permission to access existing files in folders, and I say yes, and they get access. But I don't know if they've managed to persuade Google to accept their use of the restricted APIs or whether they are using the picker API / Intent.
