### ISSUE TITLE
CI job to detect Kotlin version 1.7.0 is used in project.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#2892]
**Describe the bug**
We have to make sure in CI that we are using kotlin version 1.7.0 in our project to build , if fail abort the build process.

**Comment by kelson42** [comment]
@MohitMaliFtechiz
* Check our Kotlin code fit this configured Kotlin version
* Report appropriatly in the CI if not matching

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

I have check the klint its being set to the latest version since we are using square which is auto installed for code style https://github.com/square/java-code-styles/blob/6cdf2144265bcc436b1f3845a6dd425410797bba/configs/codestyles/SquareAndroid.xml#L241 and this is set to kotlin official and we are using kotlin 1.7.0 so if the code is not formatted with kotlin 1.7.0 then k-lint will fail and we already have CI for klint. That why lots of code formatting required by https://github.com/kiwix/kiwix-android/pull/2884 .
