### ISSUE TITLE
Search: ability to press Enter to skip the search

### ISSUE THREAD

**Issue by opk12** [kiwix/kiwix-android#2896]
**Is your feature request related to a problem? Please describe.**
When you know the exact word of interest, the search is unnecessary. You must wait a couple seconds to search, move the finger from the keyboard to the top of the screen, tap the search result.

This is not a "bug", but I use Wiktionary as a language learning aid at home (make a lot of queries while reading) and abroad (quickly look up an occasional word from a sign) so if a shorter interaction is possible, it would be convenient.

**Describe the solution you'd like**

- Type `abc`
- The search starts
- Enter is pressed before the search completes
- If the article `abc` does not exist: no change (searching continues normally)
- If the article `abc` exists: the search is interrupted

**Comment by kelson42** [comment]
@gouri-panda @MohitMaliFtechiz Does that sounds a good idea?

**Comment by gouri-panda** [comment]
@kelson42 Yes

**Comment by opk12** [comment]
To inform the user that the search can be interrupted, a message could appear above the rotating spinner, or in a toast message, or as a tip in the Settings...

    💡 Tip: Press Enter to stop searching and try to match the exact article title

**Comment by kelson42** [comment]
This is badically the same problem as https://github.com/kiwix/libkiwix/issues/748 wirh kiwix-serve

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can we try to implement this now? Seems pretty easy.
