### ISSUE TITLE
The SD card is not used, although I can see and select it in the options.

### ISSUE THREAD

**Issue by yustAnotherUser** [kiwix/kiwix-android#2916]
As I said in the title I cannot use the SD card as storage.
It will detect the sd card and it will let me choose a directory there but it won't use it. It still says internal after choosing the directory. Tried several times to change to path it doesn't care. Didn't have this problem with any other apps so I'm pretty lost here. Any tips?!

**Environment**
- Version of Kiwix Android : 3.5.0
- Device : Realme 3 Pro
- OS version : Android 11
-

**Comment by yustAnotherUser** [comment]
Nevermind. A reinstall of the whole app fixed the problem. Now it won't let me select a directory anymore but at least it uses the SD card now. Probably it had some issues with it's changed directory structure as mentioned in an older post with the same problem - before it was in the root a folder called kiwix. Now after a reinstall and selecting the SD card it uses the dir SD/Android/data/org.kiwix.kiwixmobile/files/Kiwix but files transfered there are not recognized by the app.

**Comment by MohitMaliFtechiz** [comment]
hi @yustAnotherUser ,

You need ```MANAGE_EXTERNAL_PERMISSION``` make sure its being given. and let me know if you still find out issue.

Thanks and Regards
Mohit Mali

**Comment by MohitMaliFtechiz** [comment]
hi @yustAnotherUser ,

any update on this ?
