### ISSUE TITLE
Lego message: Android.ui.rate dialog msg 1/2

### ISSUE THREAD

**Issue by amire80** [kiwix/kiwix-android#2919]
**Describe the bug**

The message that invites the user to rate the app is broken into two messages, which is called "lego" in translatewiki jargon. The name "Kiwix" is inserted automatically in the middle between two messages, but this is really not great. This causes misunderstanding and incorrect translations.

**Expected behavior**

It's much better to have one message, and simply let the translators write the app name by themselves, or to insert it using a parameter.

**Steps to reproduce the behavior:**
1. Translate the rating messages at translatewiki, and there are two of them. There should be one.

**Screenshots**

**Environment**
- Version of Kiwix Android : The current thing I see at translatewiki.
- Device : 
- OS version : 

**Logs**

**Comment by kelson42** [comment]
@MohitMaliFtechiz Woukd you;be able please to still fix this quickly in 3.6.0?

**Comment by amire80** [comment]
Thanks a lot for fixing this! I see it in translatewiki now.

A tiny follow-up: #2931.
