### ISSUE TITLE
Literal `n` in a message

### ISSUE THREAD

**Issue by Nikerabbit** [kiwix/kiwix-android#2921]
**Describe the bug**

```<string name="delete_zim_body">The following zim file(s) will be deleted:n\n%s</string>```

I think the removal of `\` before the `n` after the colon was a mistake.

**Expected behavior**

**Steps to reproduce the behavior:**
1. 

**Screenshots**

**Environment**
- Version of Kiwix Android : 
- Device : 
- OS version : 

**Logs**

**Comment by kelson42** [comment]
@MohitMaliDeveloper @gouri-panda To be fixed before 3.6.0 release.

**Comment by gouri-panda** [comment]
I can take this. It's a small fix.
