### ISSUE TITLE
zim file not recognized with wikimed app

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#293]
After installing WikiMed mini (version 2017-08 Build 1172340) and upon opening, I get the error message: "zim file not recognized". Same thing after deinstalling- reinstalling. Weirdly enough, the WikiMed mini app shows the Get content menu item and allows me to open other files stored locally (the online library shows "no network connection").
That's when it asks me for permissions: I give them and then it works fine (i.e. Mini zim is opened normally). I still get the Get content menu item though.

I also opened Kiwix Android (2.3 Build 1173302) which was already installed and worked fine until recently: I have a similar problem upon opening the app (see image)
![kiwix](https://user-images.githubusercontent.com/21675885/33327444-cdee15b4-d457-11e7-9f29-0d79b0a8c714.png)

BUT
Upon removing and re-downloading the zim files the problem disappears and I can open them normally.
Config: Huawei P8 Lite, Android 7.0; 3Gb/32Gb

**Comment by mhutti1** [comment]
I can't reproduce the zim opening error but I can see the get content button. It shouldn't be there.

**Comment by Popolechien** [comment]
I can reproduce if all versions of Kiwix are uninstalled. If there's one working one (e.g. Kiwix), then the new one (e.g. WikiMed) works

**Comment by kelson42** [comment]
I think this is a fundamentaly importenat ticket to understand why a few users complains about "zim file not recognized"

**Comment by kelson42** [comment]
@Popolechien @mhutti1 I have open a separate ticket for the "custom apps" https://github.com/kiwix/kiwix-android/issues/341

**Comment by kelson42** [comment]
@Popolechien I guess you can not reproduce that pb anymore with last version?

**Comment by Popolechien** [comment]
Not really, I cannot reproduce anymore. But then there's a separate (and new) issue of it not having a landing page anymore to start with (Version 2018-08 build 1182421).

**Comment by kelson42** [comment]
@macgills What would you recommend here?

**Comment by macgills** [comment]
Are these releases to the app store that are malfunctioning? I'd say hold tight and let me get automated releases working. I have no way of knowing what version of kiwix was used or what the bug could be

**Comment by kelson42** [comment]
I will close that ticket for the moment as we have a fully revamped custom app process and in additional a fallback solution allowing users to get the ZIM file through a direct HTTP download. If this problem still occurs we should then reopen this ticket.
