### ISSUE TITLE
[Kiwix 3.5.0] F-Droid - App not installed

### ISSUE THREAD

**Issue by Mitia99** [kiwix/kiwix-android#2938]
**Describe the bug**
App not installed

**Expected behavior**
App installed

**Steps to reproduce the behavior:**
1. Download Kiwix 3.5.0 from F-Droid
2. Install the app

**Screenshots**
![Screenshot_20220805_092314_com.google.android.packageinstaller.jpg](https://user-images.githubusercontent.com/56766778/183014655-4a2c2a8e-0aec-4fec-817f-801ccf4bf03a.jpg)
For your info, I had ver 3.4.5 installed previously and it was working

**Environment**
- Version of Kiwix Android : 3.5.0
- Device : Huawei P30 ELE-L09 
- OS version : Android 10 - EMUI 12.0.0

**Comment by kelson42** [comment]
@Mitia99 It is the only app of F-Droid which currently does not install on your device?

**Comment by Mitia99** [comment]
@kelson42 I can't find link for 3.5.0.apk in repo assets and I don't have tools for installing from source code. Would be nice if someone drop apk on assets. Thanks

**Comment by kelson42** [comment]
APK ate available here http://download.kiwix.org/release/kiwix-android/

**Comment by MohitMaliFtechiz** [comment]
hi @Mitia99 , F-Droid does not have 3.4.5 version so most probably you downloaded it  play store or download.kiwix.org , since base version is not from F-Droid so its can be install as an update , you must need to uninstall the 3.4.5 and then installed 3.5.0 from F-Droid.

**Comment by Mitia99** [comment]
Thanks for the link. Seems like it's an issue with the F-Droid one cause the one you shared is working well![Screenshot_20220805_094618_com.google.android.packageinstaller.jpg](https://user-images.githubusercontent.com/56766778/183018303-3ca0fc26-8c1b-4abd-98b9-812b4d7c4226.jpg)

**Comment by Mitia99** [comment]
@MohitMaliFtechiz I already uninstalled previous version (3.4.5) before installing 3.5.0 from F-Droid. Only @kelson42 app link works

**Comment by MohitMaliFtechiz** [comment]
hi ,

I have tested the scenario from F-droid its working fine.

**Comment by Mitia99** [comment]
@MohitMaliFtechiz Maybe may depend on device. Since 3.6.0 is out, I'll close this

**Comment by kelson42** [comment]
3.6.0 is now available on F-Droid.

**Comment by Mitia99** [comment]
@kelson42 I'll close this issue then
