### ISSUE TITLE
Kiwix now displays a blank screen after loading recent wikipedia

### ISSUE THREAD

**Issue by ddevz** [kiwix/kiwix-android#2947]
Kiwix for android worked for several .zim files before using the integrated download screen to install wikipedia_en_all_maxi_2022_05

Now selecting *any* zim in the library shows a essentially blank screen (shows the top bar (hamburger button, name of the .zim data and the number of "tabs"), and the bottom bar ("reader", "library", "download"), but nothing else)

Deleting wikipedia did not resolve the issue

Interestingly, selecting the hamburger button, then bookmarks, then selecting a bookmark for a zim thats still installed *does* show that page.  One can even then go to the homepage of that repository.
The same works for hamburger button->"history"

Nothing flagged as error shows in the logcat

I would like to try to diagnose this by copying all bookmarks, notes, and zim files, uninstalling kiwix, reinstalling kiwix, then adding things back one at a time to see where things break.

Since there does not seem to be "backup history, bookmarks, and notes" option for kiwix-android, manually copying them is a option, but where are the bookmarks stored, and where is the history stored?

By stored, I mean for example, the notes can be found in /sdcard/Kiwix/Notes, and zim files can be found in /sdcard/Android/data/org.kiwix.kiwixmobile/files/Kiwix/*

(note: Issue #2794 ("Where are bookmarks stored?") was "solved", but the answer was not put in the issue)

**Environment**
- Version of Kiwix Android :  3.5.0
- Device :  samsung tablet
- OS version :  9

**Comment by kelson42** [comment]
@ddevz I would try with latest nightly http://download.kiwix.org/nightly/2022-08-11/dev-universal-debug.apk

**Comment by ddevz** [comment]
> @ddevz I would try with latest nightly http://download.kiwix.org/nightly/2022-08-11/dev-universal-debug.apk

Sure.  I'm not willing to risk loosing my bookmarks and history though, can you tell me where I can find the bookmarks and history on the filesystem so I can back them up in a second location before doing so?

**Comment by gouri-panda** [comment]
@ddevz Now we are storing history and bookmarks in the database but it would be a good idea to have an option to backup.
 
@kelson42 @MohitMaliFtechiz What do you think?

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda , Yes we can add this feature request.

**Comment by ddevz** [comment]
> @ddevz Now we are storing history and bookmarks in the database but it would be a good idea to have an option to backup.

Cool.  That would be ".../user/0/org.kiwix.kiwixmobile/databases/Kiwix.db", right?  I'll back up Kiwix.db, as well as my notes, move the zim files, and then set the zim files to read-only.  Then I think I should be safe to remove Kiwix and install it again and begin testing.

(having a backup that can be initiated through the user interface will still be a cool feature in the future as I believe many people don't have root)

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

can you please confirm the feature request so that i can create a ticket for this.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Here, we should fix the ticket first. For anything else (like feature request about bookmark export or backup, etc...), please open a dedicated ticket (if not already done). Do we know what goes wrong on @ddevz device?

**Comment by ddevz** [comment]
> Do we know what goes wrong on @ddevz device?

I uninstalled, reinstalled (the same version), and it happened again, but after reinstalling I also found a workaround.  

Workaround Procedure:
* try to open a item in the library (and get a blank screen, with just a partial header, for example, no "random" button)
* click the "1" in the upper right corner to make the "tabs" screen appear
* click the "1" in the upper right corner to make the "tabs" screen disappear.  The rest of the header will now appear (including the random button)
* click the random button, and a random page, including the footer will now appear (including the home button)
* click the home button, things are now operational again.

I can live with this. 

Maybe we close the original ticket, and just reopen the original ticket if someone else has the problem?

As for creating the new ticket for a method of exporting the bookmarks, I'd like to mention that I'm hoping it'll be exported to a ascii or other editable format so I can edit the exported bookmarks, in order to migrate my bookmarks from wikipedia-2020-05 to wikipedia-2022-01 or whatever.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I wonder what we should do with this ticket as we have no explanation and I believe we are not able to reproduce the bug?

**Comment by MohitMaliFtechiz** [comment]
@kelson42, Yes, we are unable to reproduce this bug with Wikipedia files as I have tried with the latest Wikipedia files.


https://github.com/kiwix/kiwix-android/assets/34593983/526f2fe7-bb5d-4264-ada7-3a0f509eb723


https://github.com/kiwix/kiwix-android/assets/34593983/1b3687be-f1c8-44a9-9117-b1e8d8d59b63

**Comment by kelson42** [comment]
@ddevz We belive to have fixed this in Kiwix-Android 3.7.1 (currently in testing in Play Store). Please reopen if you are still impacted.

**Comment by ddevz** [comment]
I'll try it out once I'm able to get it.  Thanks
