### ISSUE TITLE
Non-FOSS in F-Droid build

### ISSUE THREAD

**Issue by licaon-kter** [kiwix/kiwix-android#2959]
ref:  https://github.com/kiwix/kiwix-android/commit/3a14a7409085bc89b3da2406eadd738f5fcc54d6#diff-df8b4af8cccf28e19228317a74d3fba23fed6c067665f72670b7d4986515ad39R428

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/2899620162#L992

**Comment by kelson42** [comment]
I don't understand this ticket.

**Comment by licaon-kter** [comment]
This library is not open source: https://mvnrepository.com/artifact/com.google.android.play/core/1.10.3

**Comment by julianharty** [comment]
@kelson42 From what I can tell:

- The commit [3a14a74](https://github.com/kiwix/kiwix-android/commit/3a14a7409085bc89b3da2406eadd738f5fcc54d6#diff-df8b4af8cccf28e19228317a74d3fba23fed6c067665f72670b7d4986515ad39R428) added Google Play Services to the app's codebase. 
- This means the binary now includes a Google non-open / proprietary library
- Therefore the build process for the f-droid binary has failed because it detected the inclusion of Google Play Services.

Does this help clarify things?

**Comment by kelson42** [comment]
@julianharty thx
@MohitMaliFtechiz you confirm?

**Comment by MohitMaliFtechiz** [comment]
yes its being added for object box crashes , we can remove it its only for prompting dialog if architecture is not supportable..

**Comment by MohitMaliFtechiz** [comment]
hi,

its being added to fix this https://github.com/kiwix/kiwix-android/issues/2904

**Comment by kelson42** [comment]
@MohitMaliFtechiz so we can close the ticket?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 , we need to remove ```google_android_play_core``` lib and make changes to master need to retagged 3.6.0 then its will work on FDROID. but we have to compromise on https://github.com/kiwix/kiwix-android/issues/2904 fix.

**Comment by licaon-kter** [comment]
Note that a Tag is not needed, we can use whatever commit has the fixed code ;)

**Comment by julianharty** [comment]
@kelson42 @MohitMaliFtechiz Here are some ideas about ways we can address the needs of [#2904](https://github.com/kiwix/kiwix-android/issues/2904) for both the F-Droid Build and the Google Play Builds while also helping the end users. I expect there will be some details to resolve in terms of the implementation.

1. We want the apps to work regardless of where users obtain them from.
2. Google provides an API and a library that can a) detect when the files are missing and b) presents the end-user with a dialog asking them to visit Google Play to download the app again, c) it provides the underlying functionality to download the missing files (possibly as a complete re-install, I don't know how it works exactly).
3. If we incorporate the Google Android approach (as we have done recently) users who are willing and able to use Google Play can download the missing files and use the app without the objectbox crash. However, this approach does not work well  for:
    - the F-droid app.
    - Users who can't, don't, or won't use Google Play. 
    - Users who want to share the app locally.

Potentially we could write our own detection code and UI (e.g. to help end users find a local solution e.g. if they've copied the app binary locally perhaps they could also copy across the missing files). And similarly, we could potentially write our own download code to obtain the missing files from a) Google Play (if that's practical and they let us do so programmatically) and b) our own servers. 

If the download code + hosting the necessary files isn't viable then the first two aspects (writing our own detection code and UI) combined with code that then exits the app (similar to how the Google approach works) could be an alternative.

Another suggestion is that we only implement the Google-based code in the builds that target Google Play, however that'd probably add to the complexity of our code.

What do you think? would any of these suggestions help?
Thank you

Julian

**Comment by MohitMaliFtechiz** [comment]
hi @licaon-kter , Please build the F-Droid build now.

**Comment by licaon-kter** [comment]
Done https://gitlab.com/fdroid/fdroiddata/-/commit/c64a0bffebdcd61fba41ca265c43c7a63c9242ad
