### ISSUE TITLE
URL in the external link warning window

### ISSUE THREAD

**Issue by opk12** [kiwix/kiwix-android#2965]
**Is your feature request related to a problem? Please describe.**
(Edit - I copy @kelson42's clearer and shorter version here at the top)
When clicking on an external link, a warning is displayed that the user will leave the Kiwix application, but the URL is is not given. This is unoptimal from a security perspective. Having the URL displayed will help the Kiwix user to decide if he wants to continue or not.

(Original report)

If the warning window is enabled, it might as well display the URL, or at least the domain, to double-check with a quick glance. While the bigger WMF wikis do not have a real issue with malicious links, wikis with smaller communities and third-party content could be easier to use as an attack vector.

For example, most links in a Wiktionary point to a couple well-known online dictionaries used as sources. On Wikipedia, one could check that the destination is a reputable official source or newspaper, or at least that the name "sounds like" the source declared in the link label.

**Describe the solution you'd like**
Display the URL, or the domain, or a shortened URL version with at least the domain.

**Comment by kelson42** [comment]
I'm not fully sure by reading this ticket I understand what this is about. But it seems this is about what happen with clicking on an external link. A warning is displayed that the user will leave the Kiwix application but the URL is is not given. This seems to be unoptimal from a security perspective. Having the URL displayed will help the Kiwix user to decide if he wants to continue or not.

That said, it has to be smart IMO, so the URL can be readable (not too long).

**Comment by opk12** [comment]
> this is about what happen with clicking on an external link. A warning is displayed that the user will leave the Kiwix application but the URL is is not given. This seems to be unoptimal from a security perspective. Having the URL displayed will help the Kiwix user to decide if he wants to continue or not.

Yes. Sorry for not being as clear, I copied this at the top of the issue.

> If I understand properly this is a different topic of https://github.com/kiwix/kiwix-android/issues/2966

Yes. 2966 could also potentially be approached in such a way that the external link warning window's implementation changes, but it is another topic (copying the URL into the clipboard vs displaying the URL on-screen).

**Comment by cdhiraj40** [comment]
> That said, it has to be smart IMO, so the URL can be readable (not too long).

I think even showing the domain name would be more than enough to help the Kiwix user to decide if the user wants to continue or not, we can have a link with ellipsis text alongside copy button.
Somewhat like this in the dialog box: 
![illustration of Link with copy button](https://user-images.githubusercontent.com/75211982/202176357-5cd64333-4b10-4bfc-89b7-40a7afbb7c4c.png)

What do you think? 🤔 @kelson42 @gouri-panda

**Comment by gouri-panda** [comment]
@cdhiraj40 Good idea! We can further reduce size by replacing copy text with copy icon. As @kelson42 mentioned the url should readable as much possible.

**Comment by opk12** [comment]
Size can be further reduced if the `Copy` button is below, rather than on the same line.

**Comment by shankarpriyank** [comment]
Is this issue still relevant? the app still does not show the URL when warning the user about an external link...
 Would love to work on it

**Comment by kelson42** [comment]
@gouri-panda @shankarpriyank what is exactly the changes you propose to implement?

**Comment by gouri-panda** [comment]
>My opinion is let the users see the  external link. We can add this in the same warning dialog window. Further we can add a copy button like when we copy in mobile browser which allows users copy the external link quickly and open it their other browsers.

@kelson42 We should display the external link in the warning window and a copy button is a good idea too.

**Comment by kelson42** [comment]
OK, good to me.
