### ISSUE TITLE
Ability to copy the URL of an external link

### ISSUE THREAD

**Issue by opk12** [kiwix/kiwix-android#2966]
**Is your feature request related to a problem? Please describe.**
I would like to copy an external URL into my personal notes or share to a chat.

**Describe the solution you'd like**
Any way of copying the URL would be fine. For example, I could long-tap the link and see a toast message `URL copied`.

**Comment by gouri-panda** [comment]
We can do this by displaying the link. Maybe we can merge the feature with #2965.

**Comment by kelson42** [comment]
@gouri-panda Where would you display it? My first intuition would be to allow long click on external link and then have the overlay to copy the data.

**Comment by gouri-panda** [comment]
@kelson42 We can add this along with the Url link (#2965).

**Comment by opk12** [comment]
I was thinking something along the lines of what @kelson42 said. @gouri-panda The external window will not show up if it is disabled in the settings, or if `Do not ask anymore` was clicked. A change to the window to allow for copying would duplicate the work of implementing another means of copying for the case that the window is disabled.

**Comment by kelson42** [comment]
@shankarpriyank Is that something you coukd implement?

**Comment by shankarpriyank** [comment]
> @shankarpriyank Is that something you coukd implement?

Implemented it in #3193
