### ISSUE TITLE
Deinstallation automatically deletes ZIM files. Don't do that. Ask the user, if they really want to delete the downloaded files (if this is technically possible)

### ISSUE THREAD

**Issue by Wikinaut** [kiwix/kiwix-android#298]
I had to reinstall Kiwix (because I wanted to determine whether a search bug #134 disappears then (no)).

I noticed, that my big downloaded content file was automatically deleted then, this should not happen.

**Comment by divadsn** [comment]
Hmm, weird, as Kiwix isn't saving ZIM files in it's data folder, what Android version are you running?

**Comment by Wikinaut** [comment]
* Android 7.0
* Sicherheitspatchebene 05.10.2017

ZIM files are on sdcard/Android/data/org.kiwix.kiwixmobile/files//Kiwix/*.zimaa until *.zimam

**Comment by Wikinaut** [comment]
Formerly I stored Kiwixbooks on sdcard/Kiwix/*.zim , but I removed that completely, before I tried to dwnload the 25 GB German WP novid.

**Comment by Wikinaut** [comment]
Correction: this sdcard/Kiwix/*ZIM was automatically deleted, when I deinstalled Kiwix before reinstalling it.

**Comment by divadsn** [comment]
> ZIM files are on sdcard/Android/data/org.kiwix.kiwixmobile/files//Kiwix/*.zimaa until *.zimam
That's somehow unintended, on my Android Emulator the files are stored directly on the sdcard in `/mnt/sdcard/Kiwix`, are you running with an additional software overlay like EMUI, MIUI or TouchWiz?

**Comment by Wikinaut** [comment]
@divadsn HUAWEI runs EMUI

**Comment by mhutti1** [comment]
@Wikinaut As an app we do not have any say in how we are uninstalled. Generally uninstalling an app will also remove all data that that app has stored in its private directories. These are the autogenerated directories such as sdcard/Android/data/org.kiwix.kiwixmobile/ We have no control over this deletion process. If you wish your files to remain intact after uninstall you must not save them in our app specific location as the OS will delete these files and there is nothing we can do to stop it. You can change the storage location in our settings menu. We have chosen by default to store in some cases the ZIM files in our data directory as we received many complaints about us hogging device space after an uninstall otherwise.

**Comment by Wikinaut** [comment]
@mhutti1 ok, this is also my understanding on who Android works.

From your comment I understand, that this is **not** a bug, but you expected this behaviour (is this correct? Then please close the issue, I'm fine if you close it.)

I just wanted to mention (as an expert) my user experience, and users should perhaps hinted to save their "precious" big downloaded ZIM files.

**Comment by kelson42** [comment]
@mhutti1 @Wikinaut Is the problematic path, one that the app has chosen per default to save ZIM files? Do we have a way to detect if a this directory is a "private directory" (to be deleted at uninstall)?. I think it's quite problematic that the files are deleted without informing/warning the user.

**Comment by Wikinaut** [comment]
@kelson42 other apps' data like nextcloud can "survive" a reinstallation (as far as I remember), or Music player like Vanilla Music. Think of deletion of your xx GB music library by a mere reinstallation of a music player ( #epicfail ).

**Comment by Wikinaut** [comment]
Dear all, please feel! free! to modify my issue title so it perhaps better fits.

**Comment by mhutti1** [comment]
Yeah but your average listener might change their music player and would be annoyed if the music they downloaded was deleted. As Kiwix android is the only ZIM reader for Android and most of our users likely do not even know that ZIM is an open format they expect the downloaded content to only be accessible with Kiwix and as such removing Kiwix should remove the content as by uninstall kiwix they have expressed their wish to no longer use Kiwix and in their mind also the content that is intrinsically linked to Kiwix. Our average user from past experience has not understood any reason why ZIM files should be kept after uninstall and numerous comments have in the past been left to this affect. If this is an issue to you I propose the solution of warning the User that files stored in the default directory are not persistant the first time they attempt to download to this directory.
