### ISSUE TITLE
Misalignment of `FloatingActionButton` 

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2984]
**Describe the bug**
The `FloatingActionButton` stays above the app is newly installed.

**Expected behavior**
Align with the top of `BottomNavigationBar`
**Steps to reproduce the behavior:**
* Fresh install the app

**Screenshots**
![Screenshot_2022-08-27-14-23-41-10_924282dd390cc14aae1af1e29436bb16](https://user-images.githubusercontent.com/43576162/187023196-4e1a18b8-5b17-463a-a285-85bab375100c.jpg)

**Environment**
- Version of Kiwix Android : 3.7.0
- Device : Realme
- OS version : 11

**Comment by kelson42** [comment]
@gouri-panda This is a regression? Do we still have it in 3.6.0?

**Comment by gouri-panda** [comment]
@kelson42 sorry! It's 3.7.0. Yeah may be it's a regression.

**Comment by kelson42** [comment]
OK, feel free if you have a fix in mind. I hate regressions.

**Comment by gouri-panda** [comment]
@kelson42 Ok :)

**Comment by MohitMaliFtechiz** [comment]
Hi @gouri-panda ,

I Noticed this issue is present when zim files loading first time After zim files loaded and recyclerview is visible to screen this error is gone.
also same with this issue.
BottomNavBar is Blank #3069
