### ISSUE TITLE
Wrong content description in file picker floating button

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2993]
https://github.com/kiwix/kiwix-android/blob/53407ffcb8b6d7995f879d2b02a2f046ea381267/app/src/main/res/layout/fragment_destination_library.xml#L87
**Expected**
Give a good content description so that users can easily know the functionality of the  button

**Comment by kelson42** [comment]
@gouri-panda not sure here about the user impact. This ticket has been triggered by an other ticket… but there is no link :( So I don’t understand the ticket.
