### ISSUE TITLE
Convert BookDao.java into kotlin

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#2995]
Parent Issue: #1826

**Comment by kelson42** [comment]
Superseeded by #3106

**Comment by kelson42** [comment]
@gouri-panda Reopening this ticket as I suspect that we will need thsi class (in Kotlin) to allow a smooth Migration of the data to Room. What is exactly the purpose of this class?

**Comment by gouri-panda** [comment]
@kelson42 This class is responsible for accessing book/zim from the database. We are filtering, deleting, and setting the book details such as id, title, description, language, creator, publisher, etc.

**Comment by kelson42** [comment]
OK, Whatever how we will handle in the future the local/remote library (Room or libkiwix, still to be clarified)... at some point we will have to migrate the local library data (at least the list of local books). Therefore we will need that class for the next 2-3 releases IMO (long enough so all the users can have a smooth migration). Threfore the corresponding PR should be reviewed and merged IMO.
