### ISSUE TITLE
Rename "ZIM management" to "Library"

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#302]
More consistent and understandable for end users. Everyone knows what a library is. Not everyone understands what a ZIM is.
(I'm putting this because I pitched Kiwix and people were all "wtf does that mean" - so that's my use case right there)

**Comment by kelson42** [comment]
@Popolechien Where is this "ZIM management" appearing?

**Comment by Popolechien** [comment]
When clicking on "Get content" on android, this is the title page

![screenshot_20180117-105811](https://user-images.githubusercontent.com/21675885/35036684-64d50e62-fb75-11e7-9b17-0c2527324aa4.png)

**Comment by kelson42** [comment]
@Popolechien Arf... thx... I'm really blind.

**Comment by kelson42** [comment]
done.
