### ISSUE TITLE
After rotating the device, the 'refresh' doesn't respond in the Content Manager.

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#303]
This is quite simple, and perhaps not very important, however there's a bug in the GUI which occurs after rotating the device so the screen rotates while the 'Content Management'->Device is displayed.

The Refresh button stops responding. (the one with 2 semi-circular arrows). I expect it to 'refresh' the content each time I press it.

This happens regardless of whether I rotate from portrait to landscape, or from landscape to portrait. Once it happens the button is not functional until I go back to another aspect of the app (e.g. displaying content of a zim file) and use 'Get Content' again. Switching tabs in the Content Manager doesn't fix the problem.

Details: 

- Tested on a Samsung S7 phone. It's running Android 6.0.1
- In landscape mode, the scanning content pop-up is too low to be fully displayed (possibly worth creating another issue for this - ask and I'll do so).
- Also tested on a Lenovo Yoga running Android 4.4.2 - the button also stops refreshing the content once the screen has been rotated.

**Comment by mhutti1** [comment]
We have now moved to a swipe refresh as of https://github.com/kiwix/kiwix-android/pull/297 we should see if that changes anything.

**Comment by julianharty** [comment]
Cool, I agree. You've merged those changes into the master branch, haven't you. I'm happy to test those changes on devices. Is it the swizzly little circle that appears each time the Device tab is displayed, and when I 'pull down' the list of zim files? If so, it's not failed yet :)

**Comment by kelson42** [comment]
@julianharty Yes, I would be happy to have test again if that has been fixed.

**Comment by kelson42** [comment]
I have tested with 2.4 and it seems to work fine now. @julianharty Please reopen the ticket if not.
