### ISSUE TITLE
Add `DEBUG_KEYSTORE` in Settings.

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3038]
**Steps**
* Run fdroid nightly --show-secret-var in the local git repo that is being setup, e.g. fdroid/fdroidclient. It will print out the SSH Public Key. Using --show-secret-var will make it print out base 64 text to be pasted into secret variable called DEBUG_KEYSTORE.
* In the Settings of the project being built, find “Actions” under “Secrets” in the “Security” section. Paste the whole DEBUG_KEYSTORE output line into a new repository secret called DEBUG_KEYSTORE, e.g. https://github.com/kiwix/kiwix-android/settings/secrets/actions
More info https://f-droid.org/docs/Publishing_Nightly_Builds/

**Comment by kelson42** [comment]
Done, see https://github.com/kiwix/kiwix-android-nightly/issues/1
