### ISSUE TITLE
Shall we add a global exception handler?

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#304]
We've various open issues (particularly #240 #287 #62 ) related to crashes affecting the Android app, some percolate from the native code, others may be triggered in the Java code.

@ISNIT0 and I are exploring (with the help of some new volunteers) possible ways to address #62 Meanwhile we wondered about the benefits of adding a global exception handler to the app. @ISNIT0 found the following app https://github.com/Ereza/CustomActivityOnCrash which might form the basis of this enhancement (it's licensed using Apache 2.0 which AFAIK is OK to incorporate) or we could write one ourselves. 

I'll try incorporating https://github.com/Ereza/CustomActivityOnCrash in a local test build as in theory it's as simple as adding 
```
 dependencies {
    compile 'cat.ereza:customactivityoncrash:2.2.0'
} 
```
to our Gradle build file. I'll update this issue with the results of my testing.

There are various discussions on ways to add a Global Exception Handler to minimise potential runtime problems e.g. https://stackoverflow.com/questions/2764394/ideal-way-to-set-global-uncaught-exception-handler-in-android 

BTW: It'd be cool if we could allow & enable users who want to to send us a log along the same lines as https://stackoverflow.com/questions/19897628/need-to-handle-uncaught-exception-and-send-log-file I'll raise this as a separate issue so we can discuss the implications.

**Comment by julianharty** [comment]
Well it works well so far, 
I've committed a simple p-o-c in a branch https://github.com/kiwix/kiwix-android/tree/julianharty/custom_crash_poc in https://github.com/kiwix/kiwix-android/commit/ff778954c078186fc964768b3bf0f30cabed6437 

This generates a runtime exception when deleting a bookmark using the bookmark manager UI. Of course, this code shouldn't be merged as-is. Firstly for the obvious reason that it includes a forced runtime exception, second as we'd want to agree (a) adding a global exception handler makes sense (b) we like this library (c) we're OK with incorporating code released using the Apache 2.0 license. 

Thoughts?

**Comment by mhutti1** [comment]
I think anything to help catch errors makes sense. I don't have any experience with this kind of library though. As for licences I think that that is more @kelson42 domain.

**Comment by kelson42** [comment]
I think the ticket should be more clear about which kind of additional information will or should be gathered that way. That said, having an instrumented build of Kiwix has my vote. I would tend to use standard solutions provided by big players to do that. I trust you to choose something robust and maintained properly. Last but not least, first, I'm quite against having this is the published app and would like to have it build - beside the standard one, as a nightly.

**Comment by mhutti1** [comment]
I think we should close this as it is covered by other issues at this point.
