### ISSUE TITLE
Unable to open .zim on external storage

### ISSUE THREAD

**Issue by Jbollenbacher** [kiwix/kiwix-android#306]
Hi all, I've got a .zim file on a USB flashdrive plugged into my phone (2016 Pixel) via usb-to-usbc adapter, and I'm having trouble getting Kiwix to read it. 

The phone can see the drive, and access/copy/move/etc. the files on it. But when I try to use the "Open With" option to open the .zim with kiwix, kiwix gives this error: "Error: The selected ZIM file could not be found."

If I move the file to the phone's internal storage and do the same Open With, it works. The file also appears in the Kiwix app under "Get Content -> Device."  When I move the file back to the external drive, it's no longer visible under Get Content, and the Open With command fails as before. 

When I go to "Settings" in kiwix, I see under "Storage" my internal storage space, but no external storage space (the usb drive).  I believe kiwix simply cannot see the usb device, even though it's accessible within the android file system. 

I believe Kiwix is intended to be able to "see" external storage, but it cannot in this case. Any chance we can fix that? 

PS: thanks for running a great project! kiwix is neat.

**Comment by kelson42** [comment]
We (and Android to some extend) does not support OTG. Sorry:(

**Comment by realeatham** [comment]
For me , the Zim loads fine but is not added to library. Would be nice if that was fixed

**Comment by realeatham** [comment]
Would it be hard to fix

**Comment by kelson42** [comment]
@realeatham Ivstrongly recommend to open a new ticket... or wsit a bir to see if 3.10.0 will fix the problem.

**Comment by realeatham** [comment]
I updated to 3.9.1 and it is the same but now the main page doesn't load. I can search for pages or use random page but just the main page won't load

**Comment by realeatham** [comment]
I will open a new ticket in a bit

**Comment by kelson42** [comment]
@realeatham 3.10.0 apk is here http://download.kiwix.org/release/kiwix-android/kiwix-3.10.0.apk, maybe you can try it?

**Comment by realeatham** [comment]
@kelson42 it now shows in library correctly, but the front page of Wikipedia doesn't load (all other pages do). The Zim loads on the pwa on my computer fine including the front page, so it's not an issue with the Zim.

**Comment by realeatham** [comment]
The iFixit (internal storage) front page loads fine, so it is probably a issue with connecting a usb

**Comment by kelson42** [comment]
@realeatham We do progresses, please open an issue and share details and steps to reproduce.

**Comment by realeatham** [comment]
Ok I will in a bit
