### ISSUE TITLE
Missing correct headers on Android

### ISSUE THREAD

**Issue by digitalnature** [kiwix/kiwix-android#308]
Headers from the right menu appear as ellipsis in Kiwix app on Android 7.1.2.
But they are displayed correctly in the Medical Wikipedia app, which is based on Kiwix.

![screenshot_20171204-032156](https://user-images.githubusercontent.com/99317/33532450-8a148748-d8a2-11e7-9913-8f3a135eb9ac.png)

![screenshot_20171204-032543](https://user-images.githubusercontent.com/99317/33532512-f4f0c7d4-d8a2-11e7-934b-db4d0ec60eb8.png)

**Comment by kelson42** [comment]
@digitalnature I think this bug has already been fixed. May you please try with 2.3 and confirm? http://download.kiwix.org/bin/android/2.3/

**Comment by digitalnature** [comment]
Yes, they seem to show up in this version. Another issue is that only the main content headers are clickable. Clicking on the sub-headers (ie. "Viruses", "Transmission" in the pic above) has no effect unless the associated content sections are already expanded.

**Comment by kelson42** [comment]
I close the ticket and I have open a new one for the specific last problem https://github.com/kiwix/kiwix-android/issues/309
