### ISSUE TITLE
Initial download doesn't happen

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3080]
**Describe the bug**
If the user first times download, it only shows the storage option. After that, it doesn't download the selected zim files.
**Expected behavior**
Download the zim file as user wanted 
**Steps to reproduce the behavior:**
1. Fresh install the app/ remove caches or storage
2. Go to download
3. Click a zim file 
4. You'll have an option to select storage, click yes(see nothing happens)

**Screenshots**

**Environment**
- Version of Kiwix Android: 3.7.0 
- Device: realme
- OS version: 11

**Comment by kelson42** [comment]
@gouri-panda Sounds like a regression?

**Comment by gouri-panda** [comment]
@kelson42 Yes.

**Comment by kelson42** [comment]
@gouri-panda I don't have tested but this sounds a serious regression. Do we know which PR is faulty? Would that be possible to build an automated test to avoid a similar regression in the future?

**Comment by gouri-panda** [comment]
@kelson42 I'll look into it. 

>Would that be possible to build an automated test to avoid a similar regression in the future?

Yes. We should add tests in the following PR.

**Comment by kelson42** [comment]
@gouri-panda Thank you very much. We really need to do the max to avoid regression, which are basically a step backward.
