### ISSUE TITLE
Some test failing on android 13 

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3085]
**Describe the bug**
We have found that right now only ```google_api``` are available for target 33 which is causing failure of test cases , if we select target as ```google_apis``` on even target 30 test are failing and works fine with default api this indicate that we have wait till default api is available are target 33. So i have by pass some test on https://github.com/kiwix/kiwix-android/pull/2944. 

we will keep this open when default api is available we can test and move forward.

**Comment by kelson42** [comment]
What is midding in android 33 in comparison to earlier version? why it had been removed, whete is the official announcemeny? what is the impact for end-users? other impacts?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

I think you misunderstood this let me explain in details for you. 

a) First we don't need  emulator target system image ```google_apis```  to run our test cases , previously for target 21 and 30 we were running test on  system image ```default_apis``` but on CI its was showing as google it was bug .I have placed fix on https://github.com/kiwix/kiwix-android/pull/2944. So basically we were working with only system image ```default_api``` for previous target including nightly build.

b) Now on android 33 support , only system image ```google_apis`` were available no ```default_api``` system image were there for android 33 , so we were running test cases on emulator targetting system image```google_apis``` since ```google_apis``` include all google services which makes emulator slow which leads to test failure on github actions while running fine on local emulator ,  I have check similar behaviour with targeting ```google_apis``` for android 30 while with ```default_apis``` system image it was working fine.

c) So since system image ```google_apis``` were leading to failing some test cases on android 33 so we ignored some and open this ticket so that we can test those test cases on ```default_apis``` whenever it will available for android 33. So we don't need emulator targeting ```google_apis``` but we don't have ```default_apis``` system image for android 33.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

1.  Yes this is what i am doing in https://github.com/kiwix/kiwix-android/pull/2944. , We are using ```google_apis``` specifically for android 33.
2. Test are failing only on github actions not on locally , I have tested with ```google_apis``` emulator on local they are working fine only failing some test on CI. So i don't think end-user will be impacted. Its just seems issue with github runner with ```google_apis``` since its required more resource then ```default_apis```
3. Yes this is already done https://github.com/kiwix/kiwix-android/pull/2944. We are only ignoring some test on android 33.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please reassess this ticket? Anything else to do?

**Comment by kelson42** [comment]
@MohitMaliFtechiz Still waiting a feedback. How is this ticket different fron #3189? We should probably merge the two tickets?

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 , 

https://github.com/kiwix/kiwix-android/issues/3189 they are similar only difference is i have mentioned all the steps that is executed for fix this issue and none is working at a moment , We can close this one.  Detailed version of this ticket is on https://github.com/kiwix/kiwix-android/issues/3189
