### ISSUE TITLE
Unable to open ZIM files that Kiwix for Android did not download. 

### ISSUE THREAD

**Issue by traverseda** [kiwix/kiwix-android#3087]
Zim files loaded via android MTP are not available in kiwix for android.

**Environment**
- Version of Kiwix Android :  3.4.5 build 7230405
- Device : Galaxy Note10+
- OS version :  Android 12

**Logs**

[logs1663948131516.txt](https://github.com/kiwix/kiwix-android/files/9635169/logs1663948131516.txt)

**Comment by MohitMaliFtechiz** [comment]
Hi @traverseda  ,

We have fix for this issue on 3.6.0. Please download an test.

**Comment by traverseda** [comment]
Thanks, didn't quite get to it in time as I had to make preparations for keeping the ducklings warm, but we got lucky with the storm and we've already got power back! I'll make sure to get a new version from fdroid.
