### ISSUE TITLE
Remove deprecate objects from `LibraryNetworkEntitiy `

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3092]
We deprecated the `File` object in `LibraryNetworkEntitiy`. Perhaps it's time to remove deprecated objects/methods.
https://github.com/kiwix/kiwix-android/blob/2ab7a552d7b763b342f64a88956607ad0a0e85e6/core/src/main/java/org/kiwix/kiwixmobile/core/entity/LibraryNetworkEntity.java#L94-L97

_Originally posted by @gouri-panda in https://github.com/kiwix/kiwix-android/pull/3051#discussion_r973580519_

**Solution**
We have to find alternative methods for this. We should refactor other classes' dependencies as well.

**Comment by soCallmeAdityaKumar** [comment]
I am interested in doing it can help me out.

**Comment by kelson42** [comment]
@gouri-panda Honestly I don’t understand this ticket. Who deprecated what exactly? For which reason? How to fix the problem?

We have here again a ticket which is not understable for anybody except the developers. An effort should be made to avoid this because nothing can be done as long as the ticket is not understandable.

**Comment by kelson42** [comment]
@MohitMaliDeveloper Would that be complicated to fix?

**Comment by gouri-panda** [comment]
@kelson42 Sorry for the late reply! I don't know why it has been deprecated. I think it's for good reasons Sean deprecated it. The purpose of this ticket is the replace with the good alternatives.

**Comment by rishujam** [comment]
Hey @gouri-panda can I work on this?

**Comment by kelson42** [comment]
@rishujam @gouri-panda @MohitMaliDeveloper What is exactly the plan here? If we don’t understand why this is deprecated, the I would do nothing. What woukd be an alternative and why it should be better?

**Comment by rishujam** [comment]
I guess it does not literally mean that the File object is deprecated instead we should stop using these attributes from LibraryNetworkEntitiy class as remoteUrl attribute is also not being used anywhere in the project. Is it right @gouri-panda ?

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please then domthe bit which is then necessar to close this ticket.
