### ISSUE TITLE
Article opening after search page result leads to blank  page on wikihow (Chinese)

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3094]
**Describe the bug**
Article opening after search page result leads to blank  page on wikihow (Chinese)

**Expected behavior**
Article must open without any issue

**Steps to reproduce the behaviour:**
1) Open wikihow (chinese)
2) Search for any article 
3) Try opening the article leads to blank page.

*

**Environment**
- Version of Kiwix Android : 3.6.0 with https://github.com/kiwix/libkiwix/issues/824 
- Device : Redmi note 9
- OS version :  11

https://user-images.githubusercontent.com/34593983/192785788-e3f9a7d4-6727-4390-b60a-1ea208c42ac6.mp4

**Comment by mgautierfr** [comment]
This is probably the same issue than https://github.com/kiwix/libkiwix/issues/824

If you display the main entry (`C/대문`) as the main page (`/`) links are broken.
You must redirect the main page (`/`) to the path (`C/대문`) and display the content of the entry. This way, the application knows that current path is `/C/...`, and relative links are ok.

**Comment by kelson42** [comment]
@MohitMaliFtechiz What are the status in this, it shoukd work with libkiwix10+. Do you still have problems with the libkiwix or libzim?

**Comment by MohitMaliFtechiz** [comment]
hi ,

Issue exist's with Latest libkiwix12 with my wrapper changes , will wait and test again with mathiew  wrapper changes.

**Comment by kelson42** [comment]
@MohitMaliFtechiz This impacts as well all youtube ZIM files now, check with the « mali » one. We really need to fix this, indoubt we can oublish 3.7 with this big, considering the amount of ZIM files meanwhile impacted.

**Comment by MohitMaliFtechiz** [comment]
Hi @kelson42 , @mgautierfr in lbkiwix `10.1.1` i have found issues to load home page with most of the updated zim files as described below.

**For Budding authors Zim file:**
```
When opening home page
E/ZimFileReader: getRedirect: actual url https://kiwix.app/mainPage 
     redirected url from libkiwix https://kiwix.app/ 
     main page url return from the libkiwix:- mainPage
```  
   
If we open home page from search screen
```
E/ZimFileReader: getRedirect: actual url https://kiwix.app/home 
     redirected url from libkiwix https://kiwix.app/home 
     main page url return from the libkiwix:- mainPage
```


https://github.com/kiwix/kiwix-android/assets/34593983/0d440193-cc92-46b5-a9e5-97606942a646



The page is the same, which is the `home` page, but when we are retrieving the home page URL using `JNIKiwixReader.getMainPage()`, it always returns `https://kiwix.app/`, whereas the home page URL should be `https://kiwix.app/home`.

**For the chinese wikihow zim file:**

I have downloaded the latest `Chinese wikiHow` Zim file and tested this scenario. The issue is now resolved as it is able to read articles after the search screen. However, it is now showing a blank screen on the home page.

```
E/ZimFileReader: getRedirect: actual url https://kiwix.app/mainPage 
     redirected url from libkiwix https://kiwix.app/ 
     main page url return from the libkiwix:- mainPage
```

https://github.com/kiwix/kiwix-android/assets/34593983/a1275483-094a-4788-a4b3-ee21157b6b4e
     

**For the mali zim file:**
It is also returning the same URL as it does for other Zim files. I have noticed that in most of the updated Zim files, the home page is not loading as mentioned in `Budding authors`, `Chinese wikiHow` and `Off the Grid`. @mgautierfr please confirm, if this issue already resolved in the latest libkiwix then we will close this ticket and open another ticket to secure the handling of home page in the update zim files.


https://github.com/kiwix/kiwix-android/assets/34593983/421296c3-1375-43f9-98b7-02dfdfe1e76d


https://github.com/kiwix/kiwix-android/assets/34593983/6ec3e59a-f24e-4c9f-867b-ced891c1f7cd


https://github.com/kiwix/kiwix-android/assets/34593983/500c9dce-431a-4ff2-9c91-80b31d5bf7e3

**Comment by mgautierfr** [comment]
@MohitMaliFtechiz Can you point me the code where you load the home page please ?

The things is that you always must redirect to the home page, you never load `/`.
For "old" zim, when you get the mainpage entry (for exemple `/home/index.html`) which is not a redirection but you must do a redirect to `/home/index.html`) anyway.
Because of that, for "new" zim, when you get the mainpage, you always have a `/mainPage` entry which is a redirection to `/home/index.html`, so you just have to do the redirection as for any other redirect.

To handle both zim file transparently, the algorithm is:
```
check that ask url is a main page (empty string or `/` or any custom this depending of your reader).
If yes:
    if it is a redirect:       <--- It seems that it is this part missing on your side
        resolve redirect       <---
    create a (http) redirection to the path of the final entry
If not:
   if it is a redirect:
       create a (http) redirection to the target path
   if not:
       respond with the content of the item.
```

When (if) we stop handling old zim file, the first part can be dropped.

>  @mgautierfr please confirm, if this issue already resolved in the latest libkiwix then we will close this ticket and open another ticket to secure the handling of home page in the update zim files.

Except if we do https://github.com/kiwix/libkiwix/issues/740, this will not be fixed by new libkiwix as this point is part of routing, and libkiwix doesn't handle that for now (or only if you spawn a "real" server)

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Can you point me the code where you load the home page please ?

Here we are getting the home page URL from libkiwix
https://github.com/kiwix/kiwix-android/blob/d828f5255b0726f00ab2aa4bc7fce6e4426d334e/core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt#L76

**Comment by kelson42** [comment]
@MohitMaliFtechiz AFAIK most of this has already been discussed/explained at https://github.com/kiwix/libkiwix/issues/824.

**Comment by mgautierfr** [comment]
Well, I think you are stuck here. You cannot access the main page entry from the old java libkiwix and the code of the wrapper return you a wrong value.
On this point, the new java-libkiwix will allow you to access the entry and you will be able to handle the redirect correctly.

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr Okay Thanks, then we will update this ticket, when we start using the updated `java-libkiwix`. As for now, we don't have an updated wrapper to handle this.

**Comment by mgautierfr** [comment]
As a workaround, you can try to get the entry `W/mainPage` as a classic entry. If it exists, it will be a redirect to the main page. If not, you can use `jniKiwixReader.mainPage` as before.

Something like:
```
val mainPage = jniKiwixReader.checkUrl("W/mainPage");
if (mainPage.isEmpty()) {
    mainPage = jniKiwixReader.mainPage;
}
```

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you please check this ASAP so we check if this works?

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr, I have tested with both `jniKiwixReader.checkUrl("W/mainPage")` and `jniKiwixReader.checkUrl("https://kiwix.app/W/mainPage")` but it gives the URL as before for the above zim files.

**Comment by mgautierfr** [comment]
It cannot. Either it gives you an empty string (because the pages doesn't exist) or a different url (because the page exists and it is a redirect)

**Comment by mgautierfr** [comment]
Which version of libzim/libkiwix are you using ?
On which zim files are you testing ?
I will test on my side.

**Comment by MohitMaliFtechiz** [comment]
Hi @mgautierfr Sorry for late reply, 
* I am using the libkiwix `10.1.1` .
* I have tested on several Zim files e.g. `Budding author 2023-05-11` , `Artificial Intelligence 22023-04-30`, `Wikihow Chinese 2023-04-10`, and `Le Mali Pour Les Nuls 2023-03-09`.
