### ISSUE TITLE
Kwix on F-Droid only goes up to version 2.4 and has not been updated since 2018-09-21

### ISSUE THREAD

**Issue by novellus** [kiwix/kiwix-android#3097]
Kwix on F-Droid only goes up to version 2.4 and has not been updated since 2018-09-21.
Expected: F-Droid should host the latest builds

https://f-droid.org/packages/org.kiwix.kiwixmobile/

**Comment by kelson42** [comment]
@novellus I discovered the problem 30 mn ago. I guess the problem is directly a consequence of #3091. To be confirmed.

**Comment by kelson42** [comment]
Duplicate of #3091
