### ISSUE TITLE
Android menu is unreadable on Huawei Mate S, 5.1.

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#31]
_From @mhutti1 on December 31, 2016 11:5_

![a4114dcc-c938-11e6-9e75-b5d22cc502a4](https://cloud.githubusercontent.com/assets/2286937/21577172/0196170a-cf49-11e6-9a4b-a9b527f7386d.png)

_Copied from original issue: kiwix/kiwix#415_

**Comment by kelson42** [comment]
@mhutti1 @EladKeyshawn What is the status on this? Who exactly can reproduce the problem with on of its test device?

**Comment by kelson42** [comment]
_From @EladKeyshawn on February 5, 2017 11:15_

I still have it on my Huawei device

**Comment by kelson42** [comment]
@EladKeyshawn @mhutti1 What is the solution to fix that problem? Elad seems to be the only one able to reproduce the problem (I have tried hardly on BitBar to find a device with the same problem without success)

**Comment by mhutti1** [comment]
@kelson42 I don't know I can't replicate it :(

**Comment by kelson42** [comment]
@EladKeyshawn I seem you are the only one able to reproduce it and as a consequence the only one who can fix it. Could you please have a look so we get a change to close that tricky ticket?

**Comment by kelson42** [comment]
@EladKeyshawn It would be really great to go ahead quickly on this as we should release 2.3 ASAP now.

**Comment by EladKeyshawn** [comment]
@kelson42 I can't actually reproduce it now

**Comment by kelson42** [comment]
@thx for the feedback. I'll close the ticket as this has probably been fixed with an Android update on your phone (I suppose). Anyway we can not fix a problem we can not reproduce.
