### ISSUE TITLE
Migrate from ObjectBox to Room

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3101]
We previously discussed why it's important for our applications in #3091  

**Describe the solution you'd like**
We can create helper classes that migrate the previous data of the user to the new room database and then refactor necessary the code along the way.

**Comment by kelson42** [comment]
@gouri-panda What are all the sub-tasks?

**Comment by gouri-panda** [comment]
@kelson42 Subtasks are in #3102 .

**Comment by kelson42** [comment]
OK, I have created a project with the same purpose, so I guess this ombrela ticket can be closed.
