### ISSUE TITLE
Update the  database tests 

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3102]
This is a subtask of #3101. Some of the breaking changes are we doing in those areas.

* History(Responsible for the save history, deleting history, and deleting pages) https://github.com/kiwix/kiwix-android/blob/e2c901bf22034ea891c29ce12bc5793df7eccf52/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/HistoryEntity.kt
* NewBookDaoTest (Responsible for offline storing Books/Zims in) https://github.com/kiwix/kiwix-android/blob/e2c901bf22034ea891c29ce12bc5793df7eccf52/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/BookOnDiskEntity.kt
* BookmarkEntity (Responsible for stroing and updating Bookmarks) https://github.com/kiwix/kiwix-android/blob/e2c901bf22034ea891c29ce12bc5793df7eccf52/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/BookmarkEntity.kt
* FetchDownloadEntity (Responsible for online Book/zim lists that the user can download) https://github.com/kiwix/kiwix-android/blob/e2c901bf22034ea891c29ce12bc5793df7eccf52/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/FetchDownloadEntity.kt
* RecentSearchEntity (Responisble for recent searches) https://github.com/kiwix/kiwix-android/blob/e2c901bf22034ea891c29ce12bc5793df7eccf52/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/RecentSearchEntity.kt 
* LanguageEntity (Responsible for storing all language lists that user can search) https://github.com/kiwix/kiwix-android/blob/e2c901bf22034ea891c29ce12bc5793df7eccf52/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/LanguageEntity.kt
* NotesEntity (Responsible for Notes that user has saved (https://github.com/kiwix/kiwix-android/blob/eb4f078200c2de81161883e7454587ec6b390707/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/NotesEntity.kt

As well we should test all the migration test to ensure that in the migration process user shouldn't lost the data.

As we will refactor a large base code of the database we should tests all the previous subtasks, migration helper classes .

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

Please let me know if we are ready to migrate to Room so i will assigned some of the ticket to myself ?

**Comment by kelson42** [comment]
@MohitMaliFtechiz We are ready to to move but I plan to assign the job to @gouri-panda so you can keep focusing on your priorities.

**Comment by kelson42** [comment]
@gouri-panda Thank you for the task. Here are my requests:
* Create one ticket per task, do things in a way than a ticket takes one day maximum to implement (worse case 2 days)
* Everything you will newly have to created has to be unit tested (this mean low level tests - directly the class). Please test appropriatly the edge cases
* It's important a ticket is created to have a transition path for our users so they don't remark this technology change
* Please go through all the tickets and see if one of them should be fixed at the same time of this project
* Put all tickets matching the above pre-requisites to milestone `3.7.0` and project `Room`
* Once all of this is done, we will be able to close this ticket

**Comment by gouri-panda** [comment]
@kelson42 I have opened the necessary subtasks. I think we should open this ticket if we need any further tests in the future.
