### ISSUE TITLE
Room migration of History

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3107]
This is a subtask for #3102 . Write migration test and new database test for History.

Should be done:
* A kind of generic and abstract accessor to access Room data
* Secure the Room DB is created properly at start (if it is not easy to create on the fly) if necessary (first installation or migration context)
* The data structure and accessor to the history (based on what exists in ObjectBox)
* Link with the existing code around the history(disconnect this from ObjectBox)
* Write the automated tests (Unit tests and maybe one UI test) for that new Room code (adapt what exists for ObjectBox)
* Write the migration function (for the data) from the ObjectBox history DB to the Room DB
* Write automated tests for that migration function
* History(Responsible for the save history, deleting history, and deleting pages) https://github.com/kiwix/kiwix-android/blob/e2c901bf22034ea891c29ce12bc5793df7eccf52/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/HistoryEntity.kt

**Comment by kelson42** [comment]
@gouri-panda I think this is the ticket you should start with. This is 100% independent of the libkiwix.

**Comment by kelson42** [comment]
@MohitMaliFtechiz This would be the next one to migrate to room. Here again we had a PR.
