### ISSUE TITLE
Search crashes the Kiwix, and main page restarts. Renders Kiwix unusable.

### ISSUE THREAD

**Issue by Wikinaut** [kiwix/kiwix-android#311]
As already mentioned in my comment to #134 , kiwix crashes (Kiwix main page is shown) when I search for certain items.

I already built the latest master version:
* 03f27f6580c769f8f02adde36ec9018058c8b34f

Found, that many searches are not functioning

One example is my test search for "tatort":
* only 6 results on first letter "t" ("t-Nomenklatur" until "tRNA") ; and
* there are no results after having typed "ta".

Before the reinstallation, Kiwix crashed after having typed "jimi".

With "crash" I meant that certain search entries (characters) immediately killed the search and returned me to the Kiwix startpage. Currently I don't know, if this is an NPE, but could be something like that.

* HUAWEI P8 LITE 2017
* Android 7.0
* 128 GB fast SD card
* KIWIX from Google Play 2.2 Build 53 or
* KIWIX master 03f27f6580c769f8f02adde36ec9018058c8b34f
* Content file(s) downloaded with Kiwix: 
  * Wikipedia Deutsch novid 2017-08-27
  * Filenames are now like ```wikipedia_de_all_novid_2017-08.zima*```

Renders Kiwix fully unusable. I never had a Kiwix version which works for me.

**Comment by Wikinaut** [comment]
ping @kelson42 . Please check the German files.

**Comment by kelson42** [comment]
@Wikinaut Need to have a look how things behave with a ZIM file with fulltext index... the kind of file you have won't exist anymore soon (at leas we won't publish new one without fulltext index).

**Comment by Wikinaut** [comment]
If you send me detailed instructions, I will(I did already, because I can) build Kiwix from the sources, and will help to find the reason for this problem quickly. As perhaps some of you know I invested a lot of efforts in the last decade to create static wiki dumps.

**Comment by julianharty** [comment]
@Wikinaut A quick update: I've spent much of the day debugging another crash that was blocking various aspects of my testing. I think I've managed to fix the bug and therefore make progress again. I've started downloading wikipedia_de_all_novid_2017-08.zim to a 64GB memory card (formatted with exFAT) and will try this in a device or two on Friday 15th Dec. Today's crash was ugly as it didn't have any information about where in the app had triggered it. Here's hoping that the crash you're experiencing is more helpful.

**Comment by julianharty** [comment]
Note: Search works on the old version of Kiwix Android version 1.99 and matches tatort. This isn't to say the old search was perfect.

**Comment by julianharty** [comment]
I've finally managed to co-opt enough moving parts to be able to open this ZIM file on a device, safely stored on an SD-Card. Many of my devices don't have an SD-Card, others refused exFAT formatting, etc. Anyway, here's what I ended up with:
* A Samsung Galaxy Core Prime (a mid-range device) running Android 5.1.1
* The app, built as the `debug` build at commit https://github.com/kiwix/kiwix-android/commit/b9c78f7ca76cf264f94d95d0a2db83c6935fbed2 
* A 64GB memory card, formatted as FAT32
* The German language ZIM file No Videos, 2017-08-27 (which took about 5 hours to download on my WiFi)

As evidence of the ZIM file:
```
ls -l /storage/extSdCard/Android/data/org.kiwix.kiwixmobile/files/Kiwix/
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 01:12 wikipedia_de_all_novid_2017-08.zimaa
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 01:26 wikipedia_de_all_novid_2017-08.zimab
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 01:42 wikipedia_de_all_novid_2017-08.zimac
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 01:56 wikipedia_de_all_novid_2017-08.zimad
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 02:11 wikipedia_de_all_novid_2017-08.zimae
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 02:26 wikipedia_de_all_novid_2017-08.zimaf
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 02:40 wikipedia_de_all_novid_2017-08.zimag
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 02:54 wikipedia_de_all_novid_2017-08.zimah
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 03:09 wikipedia_de_all_novid_2017-08.zimai
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 03:23 wikipedia_de_all_novid_2017-08.zimaj
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 03:37 wikipedia_de_all_novid_2017-08.zimak
-rwxrwx--- u0_a172  sdcard_r 2147483649 2017-12-16 03:49 wikipedia_de_all_novid_2017-08.zimal
-rwxrwx--- u0_a172  sdcard_r 1534885007 2017-12-16 03:54 wikipedia_de_all_novid_2017-08.zimam
```
I've been trying the same search you mentioned, so far it behaves similarly to the older version of Kiwix (1.99) I had tried earlier today. 

I'm pretty convinced there are bugs related to search and that the app may crash in the process. Any chance you could confirm which model of the HUAWEI P8 LITE 2017 you have as there seem to be at least 2 by that name, one with a black/clear glass back, the other seems to have a metal back (at least according to my online searches). I'm guessing yours has the glass back. I ask as I'd like to try using the same device and Android version if practical. I don't think I've a micro-SD card of 128GB, but hopefully that's not a factor. I'll keep testing. Perhaps @Wikinaut  you'd be willing to pull the latest changes to the code and try that build on your device. I did fix a bug that was causing crashes in the GUI https://github.com/kiwix/kiwix-android/commit/c10d83637005e4d7859be34e5248afb69d9d54d6 but don't know if it's somehow also fixed the search, I suspect not.

**Comment by julianharty** [comment]
@Wikinaut BTW do you have a full text index on/for this file?

**Comment by Wikinaut** [comment]
@julianharty I deinstalled Kiwix, because it was not working (useless app). So I cannot answer your question. May be yes.

**Comment by julianharty** [comment]
@Wikinaut I'm sorry you believe the app is useless. I agree the search problems you've experienced sound like a major frustration and limitation especially for how you use the app. 

Would you be willing to try again? Like you I'm a volunteer. I appreciate all your help so far in identifying problems and it'd be great if we can collectively nail the problems and address them in the app. Inspired by your contribution I've created https://github.com/kiwix/kiwix-android/wiki/Heuristics-for-testing-search and also raised the following issue #315

All the best
Julian

**Comment by Wikinaut** [comment]
@julianharty Pls. let me know (git hash of Kiwix app) exactly, which version you want me to test.

**Comment by julianharty** [comment]
@Wikinaut this one https://github.com/kiwix/kiwix-android/commit/6abee5807e64b28a0bc07955c21c46d22ea06156 which is the latest commit (made by me). It's on a branch as I don't want to merge these changes yet and I hope to improve the search experience based on both our testing and feedback (others are most welcome to contribute too).

If you see an upside-down ladybird (ladybug for US readers) it means the app crashed. For now, I've not added additional code that'd enable you to send us information from the app (you'd choose to do so, the app doesn't do so by itself). We have another code branch with experimental logging and reporting I can incorporate here if that'd be something you're willing to try.

Thank you very much

BTW: are you able to use android's `logcat` (it's incorporated into Android Studio and available from the command line as `adb logcat`) to observe and copy + paste the logs from Kiwix when it misbehaves...

**Comment by GeVic** [comment]
@Wikinaut Please close the issue as I reported it again and working on it right now.

**Comment by kelson42** [comment]
@GeVic Usually it works the other way arround. Duplicates are the last created tickets and should be close, you can work on this one.

**Comment by GeVic** [comment]
@kelson42 As you assigned it to me so I thought that this one should be closed.

**Comment by GeVic** [comment]
@kelson42 Anyhow can you please refer to my last comment on #665.

**Comment by kelson42** [comment]
Search should not crash the app or activity anymore, even with 2.5.3.
