### ISSUE TITLE
Room migration of  Notes

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3113]
This is a subtask for #3102 . Write migration test and new database test for NotesEntity.
Should be done:
* A kind of generic and abstract accessor to access Room data
* Secure the Room DB is created properly at start (if it is not easy to create on the fly) if necessary (first installation or migration context)
* The data structure and accessor to the notes (based on what exists in ObjectBox)
* Link with the existing code around the notes(disconnect this from ObjectBox)
* Write the automated tests (Unit tests and maybe one UI test) for that new Room code (adapt what exists for ObjectBox)
* Write the migration function (for the data) from the ObjectBox notes DB to the Room DB
* Write automated tests for that migration function
* NotesEntity (Responsible for Notes that user has saved (https://github.com/kiwix/kiwix-android/blob/eb4f078200c2de81161883e7454587ec6b390707/core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/NotesEntity.kt

**Comment by kelson42** [comment]
My long plan is to really assess if we could somehow merge the two features bookmarks and notes within one, both UI and storage backend side. I'm not decided yet when we should handle that, if we should first migrate to Room and then do that, or do that straight.

**Comment by kelson42** [comment]
@MohitMaliFtechiz We know now we want to store these notes with room. Please rework PR done by @gouri-panda
