### ISSUE TITLE
Replace `SimpleXmlConverterFactory` to `JAXB` coverter

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3114]
We are currently using Retrofit's`SimpleXmlConverterFactory` to convert XML to objects from our services. Retrofit deprecated this class a while ago. So it would be best if we use `JAXB`. `JAXB` classes for both JSON and XML parsing whereas `SimpleXmlConverterFactory` for only XML. In the future it will also benefit us if we change from XML to JSON in our services.

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda ,

JAXB is not available for android as per retrofit https://github.com/square/retrofit/tree/master/retrofit-converters/jaxb. There is another libarary suggested on this link https://github.com/square/retrofit/issues/2733 which is https://github.com/Tickaroo/tikxml.

**Comment by kelson42** [comment]
@gouri-panda For which purpose this lib is useful exactly? To parse library.xml?

**Comment by gouri-panda** [comment]
>JAXB is not available for android as per retrofit https://github.com/square/retrofit/tree/master/retrofit-converters/jaxb. There is another libarary suggested on this link https://github.com/square/retrofit/issues/2733 which is https://github.com/Tickaroo/tikxml.

Ok @MohitMaliFtechiz . Although it's not urgent unless we change the receive data from XML to JSON.
>@gouri-panda For which purpose this lib is useful exactly? To parse library.xml?

Yes @kelson42

**Comment by kelson42** [comment]
All the XML decoding should be done in the libkiwix. We will move soon on this, first with what is necessary wirhin the Room project and then the rest. Therefore, I think we should do nothing on this now.
