### ISSUE TITLE
Hosted books doesn't show on the web

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3118]
Sometimes in the web doesn't show hosted books and if it shows it doesn't know the path of the book if we open the book it doesn't know the path.

**Describe the bug**

**Expected behavior**

**Steps to reproduce the behavior:**
1. Download the new recent APK or run the develop branch
2. Go to the WIFI hotspot
3. Start the server
4. Go to the URL and observe this behavior in your web browser

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.6.0
- Device : realme
- OS version : 11

**Logs**

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda ,

I debug this issue , its sometimes crashes due to crash on library side which native crash is showing as ```fatal exception```. I think we can test with when latest java-libkiwix were released. May be it will auto fix on latest libkiwix.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz ok, I'll test this.

**Comment by kelson42** [comment]
Let’s wait intoduction of libkiwix12

**Comment by gouri-panda** [comment]
@kelson42  I can't reproduce it any more. @MohitMaliFtechiz  It would be a good idea if you can test this to ensure that the bug has gone. Thanks!

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda I have tested it and I am unable to reproduce the error.
