### ISSUE TITLE
Italian translation string

### ISSUE THREAD

**Issue by opk12** [kiwix/kiwix-android#3135]
Set the device language to Italian, download a book. In the notification, `Cancel` under the progress bar is not translated. It should read: `Annulla`

**Comment by kelson42** [comment]
@gouri-panda @MohitMaliFtechiz It's a problem in An old version of Kiwix? In Translatewiki? In our code?

**Comment by gouri-panda** [comment]
@kelson42 It happens because we don't control the download part of the string. We use a third party service for this.

**Comment by kelson42** [comment]
@gouri-panda This is not because device language is English? So Fetch is not localised?

**Comment by gouri-panda** [comment]
>@gouri-panda This is not because device language is English? So Fetch is not localised?

@kelson42 The API we are using for the downloading doesn't support multi language or maybe only Italian. So if the android can't find the local language strings  it picks default strings in this case English.

**Comment by kelson42** [comment]
@gouri-panda You mean "only English"? What is the name of this API? This is fetch or something else?

**Comment by gouri-panda** [comment]
@kelson42 Yes!

**Comment by kelson42** [comment]
@gouri-panda yes what, I have three questions in my comment?

**Comment by gouri-panda** [comment]
@kelson42 Sorry! Yes, only English. That is the [Fetch](https://github.com/tonyofrancis/Fetch) API.

**Comment by kelson42** [comment]
Then we should find or open a ticket in Fetch library and link it here. Problem is upstream.

**Comment by gouri-panda** [comment]
The library isn't currently maintained.

**Comment by kelson42** [comment]
Yes, that's the ultimate problem.

**Comment by gouri-panda** [comment]
@kelson42 Should we close this issue as not planned?

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda and @kelson42 ,

We have already override the file as ```FetchDownloadNotificationManager``` of ftech library we can override the ``string.xml``` and get it from our own project.  It will resolve the issue , I have tested it locally and its work fine.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Sounds good to me!
