### ISSUE TITLE
Alternative to Fetch library (not maintain repo on github)

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3141]
**Describe the bug**
Since Fetch library is no more maintain on github , we must find some alternative for future.

**Comment by kelson42** [comment]
Not a prority to fix, moving to 3.8.0

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

We can deploy Fetch fork to maven , We can follow above document to deploy https://gist.github.com/StefMa/7a4a910e2f570566a0b1 apart from this we have couple of project but they are also maintain and are on jitpack like https://github.com/SIARAY/DownloadManagerPlus

**Comment by kelson42** [comment]
@MohitMaliFtechiz Your comment is confusing, it looks like the first part of your comment is for #3169. For the rest we will see in milestone 3.8.0.

**Comment by MohitMaliFtechiz** [comment]
Hi @gouri-panda, have you found any suitable replacement for the `Fetch Library` (which is not on the `jitpack`), like https://github.com/SIARAY/DownloadManagerPlus
https://github.com/amitshekhariitbhu/PRDownloader
, or do you think it is to better to deploy the fetch library on maven if no suitable replacement is found? If you have a better approach (like [Android Download manager](https://developer.android.com/reference/android/app/DownloadManager)).

**Comment by gouri-panda** [comment]
Not sure, if we should add another library for this, I think we should try the native approach like the Android download manager.

**Comment by MohitMaliFtechiz** [comment]
> Not sure, if we should add another library for this, I think we should try the native approach like the Android download manager.

@gouri-panda IMO, it is better to use native approach for the `Fetch library` replacement because the native approach improves according to the latest android versions.

**Comment by kelson42** [comment]
I'm not in favour of changing anything related to this before next release. Focus should be on the tickets in the milestone. That said, its true that first thing is to decide which library we should use to replace fetch.

**Comment by kelson42** [comment]
So, with Android DownloadManager, what is the problem, the limtations? Can we have the same features like today with fetch?

**Comment by MohitMaliFtechiz** [comment]
> So, with Android DownloadManager, what is the problem, the limtations?

@kelson42 DownloadManager does not have the pause/resume functionality we have to manage these functionalities ourselves with proper error handling.

> Can we have the same features like today with fetch?

Fetch has many features with proper error handling
 e.g. 
* Network specific downloading support.
*  Ability to retry failed downloads.
* Easy progress and status tracking.
* Download remaining time reporting (ETA).
* Download speed reporting.
 
 We need to manage these manually with `DownloadManager`.

**Comment by MohitMaliFtechiz** [comment]
> Network specific downloading support.
> I don't understand this...

@kelson42 This Means Fetch can handle whether the downloading should be performed via mobile internet or wifi, but with DownloadManager we need to handle this manually because we have this functionality in our app where users can set on which network, files should be downloaded. 

> This is a problem

We have to implement this functionality like Fetch.

> I guess this can be somehow achieve just by monitoring the size of the output file. But I would really wonder the primitive are not there.
> Easy to compute if you know how much has been downloded already.

Yes, we can handle it, but we need to do it manually DownloadManager does not provide this by default.

**Comment by kelson42** [comment]
We have to fix with DownloadManager ASAP

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have started working on this.
