### ISSUE TITLE
Nightly worflow should only compile and upload APK

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3142]
Following https://farm.openzim.org/pipeline/00574c2051b106670951b836 discussion

**Comment by gouri-panda** [comment]
Ok @kelson42 !

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

I think you posted the wrong link in description , So basically we should  run test cases on different api level those who are not tested during coverage on nightly ?
So basically API level 21 , 30 should be removed from nightly ?
