### ISSUE TITLE
Detecting Memory Leak on CI

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3154]
**Describe the bug**
Detecting Memory Leak on CI

**Comment by kelson42** [comment]
@MohitMaliFtechiz What is the purpose of this ticket? Do you mean that currently memory leak are not detected in the CI?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz What is the purpose of this ticket? Do you mean that currently memory leak are not detected in the CI?

yes

**Comment by kelson42** [comment]
@MohitMaliFtechiz OK.... I was quite sure that @gouri-panda told me in the past that detected (by Canary) memory leak would cause the CI dying. If this is really not the case, yes, this is important this ticket is implemented immediatly.

**Comment by MohitMaliFtechiz** [comment]
> 

hi @kelson42 ,

I have not found any check related to this on CI @gouri-panda please confirmed.

**Comment by gouri-panda** [comment]
@kelson42 We were discussing that it would be a good idea to implement this feature in the CI. We haven't implemented yet.

**Comment by kelson42** [comment]
OK, sorry for my misunderstanding. We should then. Really important and probably pretty trivial to do.
