### ISSUE TITLE
Some search issues reported in App Store Reviews, mainly for WikiMed...

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#316]
Here are some extracts from recent reviews, indicative of various flaws being reported:

* WikiMed: New review on Dec 11, 2017 at 3:10 PM GMT [★★★ Dear kiwix team,  I have been using this app,  find it very useful. but in this version,  it shows nothing just blank in most of the searches.....  plz fix it...
* WikiMed: New review on Dec 9, 2017 at 8:13 AM GMT★
Okay, so initially I loved this app, but now NOTHING WORKS!!! Every time I search something it gives me a blank screen PLEASE FIX THIS
* WikiMed: New review on Dec 4, 2017 at 11:27 AM GMT ★★★★★ please found problem in search
* WikiMed: New review on Nov 25, 2017 at 8:31 PM GMT ★★★ The new updated version is little misbehaving while typing terms in search option the app suddenly restarts from first and home page appears and again it continues
* WikiMed: New review on Nov 22, 2017 at 4:19 PM GMT ★★★★ Hey....it's a very nice app. Just one problem to fix. The topic I have to search is different than suggestions. The last version was better in this (search).
* WikiMed: New review on Nov 13, 2017 at 5:51 PM GMT ★★★ il y a quelques choses que je recherche qui ne sont pas présents
* WikiMed: New review on Nov 14, 2017 at 6:10 AM GMT ★★★★ New update keeps crashing on search (on redmi note 4).....
* WikiMed: New review on Nov 11, 2017 at 7:42 AM GMT ★★★ Need work especially in areas of search as it crashes automatically. Can get 5 stars.
* Offline Medical Wikipedia: New review on Nov 8, 2017 at 1:13 PM GMT ★★★★★ This thing amazing . However Search mechanism is tough . Doesn't work alphabetilcally sometimes.

**Comment by julianharty** [comment]
WikiMed: New review on Dec 16, 2017 at 2:25 PM GMT★★★★ 
_Needs to improve more by allowing sentence questions._

**Comment by kelson42** [comment]
Yes, we know we have problem with the search but most of the users use an old version of the software and/or the ZIM files... So I think there is nothing much we can do with them. We need to tackle problems one by one and they need to be reproducible by devs on a recent code/data base.

**Comment by julianharty** [comment]
I've been thinking how we can improve the testing of search, and be able to isolate that testing rather than submerging it (or testing it) via the kiwix-android app. I don't know how practical the following idea is, it relies on knowledge and expertise I don't currently have personally, however between us I hope we'll be able to resolve the unknowns and write suitable code:

* We need data in ZIM files and some sources of what to test. The ZIM files are distinct and some of the testing would probably be improved by using real instances of ZIM files available for general audiences e.g. `wikipedia_en...`. These files are large and it'd be costly and slow to download these in a typical continuous build environment where everything is intended to be downloaded at the time. _Therefore, perhaps it'd be worth having a test environment where both the ZIM files and the source queries are available long term, over many builds._
* Could we write a small, dedicated client, perhaps in C++, that can run on the various architectures, including all our target Android architectures (ARM32, ARM64, etc.) that performs API testing of `kiwix-lib`? If so, let's raise a feature request in the relevant repo... 

AFAIK I'm essentially proposing a layered testing approach, where we construct layers of tests, from unit, via these dedicated test clients, up to application and finally end-to-end tests (where the ZIM files would be downloaded by the client and the tests run using the downloaded ZIM file(s).

I've enough devices to enable some of that testing to run locally in the short and medium term. If these tests prove useful longer term we can then decide how to test more efficiently and effectively.

In parallel it'd be great to develop ZIM files for testing, with known rich content in various languages.

**Comment by julianharty** [comment]
New review on Dec 12, 2017 at 7:19 PM GMT ★★★★★
_Con la actualización se me cierra al buscar contenido. I've wiped the app's data and don't work. Smartphone: Motorola Moto G Play_
The Spanish is translated as: _With the update I'm closed when I search for content._

**Comment by julianharty** [comment]
Kiwix: Updated user review on Dec 16, 2017 at 1:34 PM GMT ★★★★
_Was ich noch vermisse, ist die Option in den Preferences , den Suchverlauf zu löschen (optional beim Beenden) . Das wär aus datenschutztechnischer Sicht noch Super! Ansonsten super App, die einem komfortabel die Wikipedia durchstöbern lässt.  Nachtrag 15.12.17 : beim Aufruf des Artikels "kreiszahl" hängt sich die App auf.. auch ist mir aufgefallen, dass das" Inhalte wechseln" rumbockt und ich das 2x anklicken muss, damit es das Image wechselt..._

Which Google Translate approximates to:
_What I still miss is the option in the preferences to clear the search history (optional on exit). That would be from a data protection point of view, still great! Otherwise, great app that lets you comfortably browse the Wikipedia. Addendum 15.12.17: when calling the article "circle number" hangs the app on .. synonymous I noticed that the "change content" rumbleockt and I have to click twice, so it changes the image ..._

**Comment by mgautierfr** [comment]
> We need data in ZIM files and some sources of what to test. The ZIM files are distinct and some of the testing would probably be improved by using real instances of ZIM files available for general audiences e.g. wikipedia_en.... These files are large and it'd be costly and slow to download these in a typical continuous build environment where everything is intended to be downloaded at the time. Therefore, perhaps it'd be worth having a test environment where both the ZIM files and the source queries are available long term, over many builds.

That's a real question. 
Most of the search results now come from the xapian embeded indexed. (Either by searching in title only when searching for suggestions or full text for "classical" search). So, most of the question is how xapian define weight for article/keywords and how it will sort the results. (And how we could tweak this as/when/if needed).

The thing here is that we should use real life example as article/keywords weights are relative to others. Having a small test zim with very few content to test searching will probably not be accurate.

> Could we write a small, dedicated client, perhaps in C++, that can run on the various architectures, including all our target Android architectures (ARM32, ARM64, etc.) that performs API testing of kiwix-lib? If so, let's raise a feature request in the relevant repo...

I'm personally using `kiwix-serve` to test search. We could use it as tool to test search (with some kind of web api).
We can also do a quick python wrapper (it's very easy) and use python tools ([py.test](https://docs.pytest.org/en/latest/) is reeaaallllyyy cool) to do some tests.

**Comment by julianharty** [comment]
WikiMed: New review on Dec 19, 2017 at 11:51 AM GMT ★★★★
_Sometimes during search , the app automatically closes...It takes place for past 1 week....Not expected , otherwise it is the very best medical wikipedia app_

**Comment by kelson42** [comment]
Most of the reports are really old and there is not more we can do with them. Suggestion system has been seriously improved in Kiwix-Android 3.0 / libzim 6.0.0. New tickets should be open if a specific new problem happen.
