### ISSUE TITLE
Tests failing due to being Gradle incompatible.

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3164]
Some tests are failing due to being incompatible with Gradle 8.0

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
```
Solution:
Remove deprecated gradle features from the project. We have a handful of this so this won't make much time.

**Comment by MohitMaliFtechiz** [comment]
hi @gouri-panda ,

Let me handle this ticket.
