### ISSUE TITLE
Android widget resize

### ISSUE THREAD

**Issue by kiravv** [kiwix/kiwix-android#3166]
Widget cannot be resized (especially horizontally) on One UI 5.
So it cannot easily fit some home screens.

Allow user resizing home screen widget.

Android 13, oneui 5, note 20 ultra

**Comment by gouri-panda** [comment]
@kelson42 Yes! We can minimize the horizontal(width) to a certain size i.e 250dp. We can't go lower from this. I'll place a fix there.

**Comment by kelson42** [comment]
@gouri-panda THX! Not only the (default) size seem not optinmal, but the user ask to be able to resize it (which I wonder is not already the case).

**Comment by gouri-panda** [comment]
@kelson42 User can resize it. If they are on tablet or any other large device they can change it. The minimum resize width is too high(250dp).Currently If the device has width more than 250dp then they can change it . Most mobile phones are usually less than 250dp in width in this case we can't resize it.

**Comment by kelson42** [comment]
@gouri-panda I understand now. Thank you for the explanation to me ... and the PR.
