### ISSUE TITLE
Host com.github.tonyofrancis:fetch on dev.kiwix.org due to unstable jitpack

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3169]
**Describe the bug**
Current problem is fetch library is rely on jitpack which is very unstable leads to compilation failure so we have decided to move fetch lib to dev.kiwix.org until we replace it on 3.8.0 milestone.

**Comment by kelson42** [comment]
Putting a bit in standby for the moment. But next time there is a problem with Jitpack, we will have to do it.

**Comment by kelson42** [comment]
@MohitMaliFtechiz How long would you need for this?

**Comment by kelson42** [comment]
Closing for the moment as it seems the last months Jitpack has been stable enouh. We shoukd anyway replace Fetch library, see #3141
