### ISSUE TITLE
Tracking reported issues with SD-Cards and storage generally

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#317]
We've learned about various problems related to different devices and storage locations. Many of these adversely affect the user experience. Sometimes we're notified via reviews in the app store. I'd like to establish an overview of the range and scope of the problems, what works and what doesn't. This issue is mainly so we can collate bug reports and feedback, then we can try to address the underlying issues so we can then improve the app :)

Please do add any information you have and cross-reference any other related issues.

**Comment by julianharty** [comment]
* Kiwix: New review on Dec 13, 2017 at 6:43 PM GMT ★ I need to run this off otg and it wont find the otg usb flash drive on my LGv20 when plugged in. It completely defeats the purpose for me. I would reassess my rating if not for this flaw but it needs to be adressed.

**Comment by julianharty** [comment]
Another issue #306 confirms OTG isn't supported. If not, perhaps it'd be worth providing that info in the app somewhere, somehow?  TBC.

**Comment by julianharty** [comment]
And via sourceforge: "My LG Android tablet has a USB slot, so I'd like to store the "full" version of Wikipedia (the one with with photos) on a flash drive, instead of the MicroSD card I currently have in the tablet (because the Wikipedia files almost max out its 64GB capacity).

The problem is that the Kiwix app can't see the USB flash drive, just the sd card and the tablet's internal storage. I even tried copying the wikipedia files to the flash drive, duplicating the folder structure, but Kiwix still didn't see the USB drive.

Is there a way to get Kiwix to use the flash drive? I'd rather not spend $50 on a 128GB sd card if I can help it."

**Comment by julianharty** [comment]
And perhaps the death of being able to support OTG in the app, via #211 
"From @mhutti1 on March 16, 2016 22:15

While Marshmallow adds OTG support universally it seems to completely lock it down for security reasons. [This](https://source.android.com/devices/storage/traditional.html#support_usb_media) states that the only way to access this storage without root is to go through the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html). Unfortunately this wont return a usable file path and the best that could be done would be to buffer the file directly into the native code. (I don't know if this would be easy to implement as I have not had time to study the native code in depth) . In conclusion from what I can see the only way to fix this is too either add root support to the app (if JNI can use root) or change the way the app interacts with the JNI."

**Comment by julianharty** [comment]
OK, so OTG doesn't seem viable, sadly. Therefore it'd be great if we could provide users this info somewhere so they're informed and don't have unmet expectations. As a suggestion, let's explore whether it'd be practical to add a FAQ in the app or online or as part of the App Store description? Meanwhile I'll see what other issues I can find related to storage.

**Comment by julianharty** [comment]
Formatting of SD-cards is one topic... e.g. (via sourceforge)
"_My androïd does not recognize my SD card reformated in NTFS or Exfat. The nopic for wikipedia.fr amounts 5 Go. I don't see any solution for installing it on the card. Can you help me ? Thanks_"

**Comment by julianharty** [comment]
#222 discusses challenges related to the path allocated by the Android OS on various devices, in that instance a Huawei P8 Lit

**Comment by julianharty** [comment]
"_I have Android phone. I can use small no pic version on my 32gb sdcard but on my 128gb card I cant use large kiwix._" https://sourceforge.net/p/kiwix/discussion/604121/thread/523d2751/?limit=25#31ee

**Comment by julianharty** [comment]
Updated user review on Nov 11, 2017 at 7:41 PM GMT ★ 
_Nasty crashes after the latest update. I have two zim files on SD card but  Kiwix can't find any of them. When I tap Get Content, it tries to get online or show "scanning for downloadable content message" but crashes immediately. the update rendered the app useless.  I have to take 5 stars back and give it one because everything was good before the update._

**Comment by julianharty** [comment]
_I have two ASUS devices, a Zenpad and a Zenfon, both with Android 6. I have installed Kiwix 2.2.53 on both of them. I have downloaded .zim files to micro-SD-cards in both devices. On the phone everything works, I can change between different content files in different languages. On the tablet I could never get Kiwix to work. Installation works, when starting "Get Content" the program searches for the ZIM files, a zim-file name flashes up for a short second and and then Kiwix crashes with a window telling it was terminated. I have sent the error report several times without any effect. Just uninstalled and reinstalled Kiwix, no change. I have compared configuration in the tablet with configuration in the phone, no error as much as I can see.
Any idea what I could do to make it work on the android tablet?_

Kiwix crashes on ASUS Tablet, but not on ASUS phone, both Android 6
https://sourceforge.net/p/kiwix/discussion/604121/thread/c60b6c74/?limit=25#3e88

**Comment by julianharty** [comment]
New review on Sep 1, 2017 at 3:32 AM GMT ★
_No se pueden guardan los grandes archivos en la tarjeta SD_

Which I interpret as: Can't store large archives on the target SD Card...

**Comment by julianharty** [comment]
Another request:
WikiMed: New review on Dec 14, 2017 at 8:44 AM GMT ★★★★
_No options to install on or move to SD card all app content..but nice job..thanks_

**Comment by julianharty** [comment]
New review on Dec 21, 2017 at 7:27 PM GMT ★
_Non riconosce la memoria esterna_ (It does not recognise external storage.)

I've asked the user for more details on the type of external storage they're using.

Here are details of the device and Kiwix version
* Version code 53 Version name 2.2

DEVICE
* Device Galaxy A5(2017) (a5y17lte) 
* Manufacturer Samsung 
* Device type Phone 
* Device language Italian 
* CPU make Samsung 
* CPU model Exynos 7880 
* Native platform armeabi-v7a, armeabi, arm64-v8a 
* RAM (MB) 3072 
* Screen size 1080 × 1920 
* Screen density (DPI) 480 
* OpenGL ES version 3.2 
* OS Android 7.0

**Comment by kelson42** [comment]
@julianharty @macgills I would like to get a chance to close this ticket with 3.0.

**Comment by macgills** [comment]
general issues should be avoided (I have made this mistake myself) and to group things we should label them appropriately, this would be my suggestion.
Focused conversations on the constituent errors should be the best way to resolve problems.

**Comment by kelson42** [comment]
@macgills Agree
