### ISSUE TITLE
APK crashes If the git branches change

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3170]
**Describe the bug**
Recently If we change the branch, objectBox changes the id automatically, leading to crash  APK.

**Expected behavior**
It shouldn't crash.

**Steps to reproduce the behavior:**
1.  Change the branch or create a new branch
2. Install the APK

Related issue #3136 

**Environment**
- Version of Kiwix Android : 3.6
- Device : relame 
- OS version: 11

**Comment by kelson42** [comment]
@gouri-panda What is exactly the difference with #3136?

**Comment by kelson42** [comment]
@gouri-panda What donyou mean exactly with « the branch »?

**Comment by kelson42** [comment]
@MohitMaliDeveloper Would you be able to explain that bug? Its exact impact (quality and qiantity)? And to fix ir?

**Comment by gouri-panda** [comment]
@kelson42 Sorry for the late reply! I forgot to answer this. 
>Also, why it works like this and what does it exactly does so the app crashes?

The bug happens because object box updates its index id(database id) automatically, and we forgot to add this to our git log maybe. That's why I think it's happening.
>How many users are impacted?
I don't think this will impact users. This is a development issue for the developers.

**Comment by kelson42** [comment]
@gouri-panda Sorry I still don't understand. Your explanation is too short, incomplete.

Read https://en.m.wikipedia.org/wiki/Rubber_duck_debugging

**Comment by gouri-panda** [comment]
@kelson42 At some point we renamed an entity class or just a property. Without further information, ObjectBox will remove the old entity/property and add a new one with the new name. If the database of the previous id and new id isn't the same then ObjectBox has no idea how to map existing data to the new model which leads to the crash the APK.
Here is a link of an ObjectBox which shows how to deal with these things https://docs.objectbox.io/advanced/meta-model-ids-and-uids . Let me know if my explanation makes perfect sense :)
