### ISSUE TITLE
Lint error in translate wiki PR (Invalid format string) in ```values-it```

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3177]
**Describe the bug**
Lint error in translate wiki PR ```Invalid format string```  in core/values-it/string.xml.

```
<string name="pref_text_zoom_summary">Aumenta o diminuisci la dimensione del testo del 25% alla volta.</string>
```

**Comment by kelson42** [comment]
@MohitMaliFtechiz What is the problem here, the`%` needs a special treatment?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz What is the problem here, the`%` needs a special treatment? It should be `%%`?

Hi @kelson42 ,
Yes ```%``` needs a special treatment here. It should be ```%%```.

**Comment by kelson42** [comment]
Any update?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 ,
I have made changes on translate wiki but it's pending yet. we should wait for translate wiki update.
