### ISSUE TITLE
Lint error in translate wiki PR (Ellipsis string can be replaced with ellipsis character)

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3179]
**Describe the bug**
Lint error in translate wiki PR ```Ellipsis string can be replaced with ellipsis character``` in ```core/values-fr/string.xml```, ```core/values-sl/string.xml``` on these strings

```
   <string name="crash_title">Hé bien... c’est embarrassant.</string> 
   <string name="preparing_files">Priprava datotek za prenos ...</string>  
   <string name="performing_handshake">Rokovanje ...</string>
   <string name="preparing_files">Préparation des fichiers pour le transfert...</string>
   <string name="performing_handshake">Négociation de la liaison...</string>
```

**Comment by kelson42** [comment]
@MohitMaliFtechiz Assuming the original (in English), has the proper three dots characters, we just need to fix the problem upstream on translatewiki.net. Then on next update of the PR, it will be fixed. Can you do that here and in the future?

**Comment by kelson42** [comment]
Not really, I created my account 10 years ago and I don't really translate on TW. You should manage it by starting with https://translatewiki.net/wiki/Translating:How_to_start/en

**Comment by MohitMaliFtechiz** [comment]
@kelson42 , some translation is pending yet in this issue.

**Comment by kelson42** [comment]
@MohitMaliFtechiz pending what exactly?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 ,
This translation is fixed in values-fr/string.xml
```
<string name="crash_title">Hé bien... c’est embarrassant.</string> 
```

**Comment by kelson42** [comment]
@MohitMaliFtechiz Why you don't have fixed the other occurrences on Translatewiki?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Why you don't have fixed the other occurrences on Translatewiki?

I have made all fix but they are still wait for approval.

**Comment by kelson42** [comment]
@MohitMaliFtechiz OK, i don't remember this approval thing... maybe because you are a new contributor. Anyway, I don't think there is anything more we can do here. You understand now how Translatewiki works. In the future if a translation does not pass the linter or is somehow wrong in the PR. You know how to fix with Translatewiki (instead of fixibg each time rhe PRs). From now please just do so directly without opening issue tickets.
