### ISSUE TITLE
Lint error in translate wiki PR (StringFormatCount)

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3180]
**Describe the bug**
Lint error in translate wiki PR ```StringFormatCount``` 

```core/values-de/string.xml```
```
   <string name="pref_text_zoom_summary">Schriftgröße in 25%-Schritten ändern.</string>
```
```core/values-nqo/string.xml```
```
   <string name="pref_text_zoom_summary">ߞߟߏߘߋ߲ ߢߊ߲ߞߊ߲ ߡߊߝߊ߬ߟߋ߲߫ ߡߞߊ߬ߝߏ߬ߟߌ ٪߂߅ ߘߌ߫.</string>
```

Logs:-
```
Inconsistent number of arguments in formatting string pref_text_zoom_summary; found 1 in values-de and 0 in values-nqo/strings.xml
```

**Comment by kelson42** [comment]
@MohitMaliFtechiz This is pretty straight forward and quick to do, please move forward on this, so next TW pull request does not suffer on this. Please update as well the `README.md` with a section of the translation with the most important information.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

Please elaborate what needs include on ```README.md``` file. Apart form that its done.

**Comment by kelson42** [comment]
@MohitMaliFtechiz The basics a developer should know to deal with translations
