### ISSUE TITLE
Test failing on android 13(API level 33) with google_apis(System image) emulator

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3189]
**Describe the bug**
Test failing on ```android 13(API level 33)``` with ```google_apis(System image)``` emulator on CI.

**Steps to reproduce the behaviour:**
* Remove this condition from test cases and make a PR.
```
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
}
```

**Environment**
- Version of Kiwix Android : 3.6.0
- Device : on CI
- OS version : Android 13

For now ```default_apis(System image)``` is not available for android 13. Since ```google_apis``` is heavy compare to ```default_apis``` because it contains extra things to run google services.

**What i have tried for solve this problem**
* Removed deprecated ```ActivityTestRule```([More Information about deprecation](https://developer.android.com/reference/androidx/test/rule/ActivityTestRule)) and added ```ActivityScenarioRule``` for test cases.
* Upgraded test dependencies to stable android 13 emulator.

| Dependency | From | To |
| :---         |     :---:      |     :---:      |
|  androidx.test:rules  |   1.4.0   | 1.5.0  |
|  androidx.test:runner  |   1.4.0   | 1.5.1  |
|  androidx.test:core  |   1.5.0-alpha02   | 1.5.0  |
|  androidx.test:rules  |   1.5.0-alpha02   | 1.5.0  |
|  androidx.test.espresso:espresso-web  |   3.4.0   | 3.5.0  |
|  androidx.test.espresso:espresso-intents  |   3.4.0   | 3.5.0  |
|  androidx.test.espresso:espresso-core  |   3.4.0   | 3.5.0  |
|  androidx.test.espresso:espresso-contrib  |   3.4.0   | 3.5.0  |
|  org.junit.jupiter:junit-jupiter  |   5.7.0   | 5.9.1  |
|  androidx.test.ext:junit  |   1.1.2   | 1.1.4  |

* Since ```google_apis``` heavy i have increased ram size to 8GB.
* I have tried to run all ```target(Api levels)``` with ```google_apis``` only ```android 21``` is working fine. Api level 33(android 13), 30(android 11) both are failing with ```google_apis``` in CI.

**Note**
All test cases are passed in local emulator(android 13).

All these changes are here https://github.com/kiwix/kiwix-android/pull/3182

**Comment by kelson42** [comment]
@MohitMaliFtechiz Its time to finally fix this ticket IMO

**Comment by willoliveira-weel** [comment]
I had the same error when using API level 33 (android 13), and 30 (android 11) both are failing with google_apis in CI (macOS-latest GH actions).

**Comment by MohitMaliFtechiz** [comment]
> I had the same error when using API level 33 (android 13), and 30 (android 11) both are failing with google_apis in CI (macOS-latest GH actions).

hi @willoliveira-weel, we have fixed the problem for the `Android 13` emulator with `google_apis`. Sometimes some `system dialogs` are visible on the window, that's why it's not finding any view in test cases you can take reference from #3303 on how you can close the system dialog if any is visible on the window, apart from that you should use the latest versions of test dependencies to support latest emulators.
