### ISSUE TITLE
Sometimes ```DownloadTest``` failing in CI.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3190]
**Describe the bug**
* Sometimes test are failing with view not found exception due to lag in emulator.
* Sometimes it fails due to action mode visible in ```local library fragment``` [More information here](https://github.com/kiwix/kiwix-android/issues/3197)

**Logs**
```
org.kiwix.kiwixmobile.download.DownloadTest > downloadTest[test(AVD) - 11] FAILED 
	java.lang.AssertionError: Couldn't find downloaded file ' Off the Grid ' Original Exception: Off the Grid downloaded successfully. But failed to delete Off the Grid file Actual exception No view found with Id org.kiwix.kiwixmobile:id/zim_file_delete_item
	at org.junit.Assert.fail(Assert.java:89)
```

**Why test failing**

* This is because when we deleting downloaded Zim file sometimes Espresso failed to find ```Delete dialog``` immediately that's why test failure occurs.
* Sometimes no view found(```downloadsFragment```) error occurs in download test.
* Sometimes no view found(```zim_file_delete_item```) error occurs in download test.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can we close this generic ticket to more specific one?
