### ISSUE TITLE
Implement a automod system for the Android custom app version_name

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#32]
_From @kelson42 on December 30, 2016 20:22_

gen-custom-android-build.py is the script used to create custom apps, ie. apps which include a unique content (ZIM file) and are rebranded.

If version_name is empty, then script gen-custom-android-build.py should try to take it from the ZIM file content. It can do that because:
* Custom apps versions are the date of the content, for example 2016-12
* This date is in the file name of the ZIM content.

So if there is not version_name, then gen-custom-android-build.py should try to extract the date from the ZIM file name which ends with it: for example "wikipedia_en_medicine_2016-12.zim" will give "2016-12".

_Copied from original issue: kiwix/kiwix#410_

**Comment by kelson42** [comment]
@EladKeyshawn If you could look at this one this would be great also. We are almost over to allow "automatically" to create new custom apps.

**Comment by EladKeyshawn** [comment]
@kelson42 Is this still relevant ? since Issac is already doing a new custom-apps gen in gradle?

**Comment by mhutti1** [comment]
This should now be implemented in build.gradle

**Comment by kelson42** [comment]
@mgautierfr @mgautierfr I think this should work now, please confirm and close this ticket.

**Comment by mgautierfr** [comment]
This is done for the `VERSION_CODE` (internal "true" version number).
The `VERSION_CODE` is automatically defined for custom app by the script `build_custom_app.py` in kiwix/kiwix-build repository.
It is base on the current day. If you want to make several release on the same day, you can use the option `--extra-code` (`0` by default) and increment it.

The `VERSION_NAME` is not really relevant, it is just a string displayed to the user.
It is taken from the json_file and can be overridden with `--version-name` option.

If we are using the "unversioned" url (ie `http://download.kiwix.org/zim/wikipedia_en_medicine.zim`) we will not have a version of the content.

**Comment by kelson42** [comment]
@mgautierfr Thx for the status update (and reminders about version_code), then it looks like this ticket is pretty much still something to do.

**Comment by macgills** [comment]
https://github.com/kiwix/kiwix-android/issues/36#issuecomment-544901831 much the same answer as here, we can set the version name to be `date+versionCode`

**Comment by kelson42** [comment]
Like my comment in #36, we need to respect the yyyy-mm format, where this date is the publication date of the ZIM file.
