### ISSUE TITLE
Last book (at the bootom of the screen) is still not fully visible 

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3210]
See
![image](https://user-images.githubusercontent.com/1029718/213165170-d3bacc55-9398-4317-93b9-24f8974f6a61.png)

It's cut by the bottom bar.

This has been reported really many times here! Any chance to fix it once for all?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 ,
I have placed a fix for this.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thank you!
