### ISSUE TITLE
[REGRESSION] Broken workflow and bad visual artefact around network authorisation

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3211]
Here is what I get if I have mobile only data:
![image](https://user-images.githubusercontent.com/1029718/213166126-af546742-511a-466e-a238-80b361bca044.png)

So far so good, but then I click "no"
![image](https://user-images.githubusercontent.com/1029718/213166218-a8e61885-0f86-4a9d-8f54-85f337ccc513.png)

This is not what I should get.

Nothing should be displayed (I have already said, I don't want).

Actually I wonder what is this (wrongly displayed) message "Please allow internet permission to download content". Why we have this? When was that introduced? This message is wrong by many way:
* Personnaly I don't know what is "internet permission"?
* The message is transparent and barely readable
* We should have a choice "yes" or "no".

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,
this feature is introduce here https://github.com/kiwix/kiwix-android/issues/2841.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thanks. What is this "internet permission"? I don't have this on my Android10. If I have internet via Wifi, the kwix app just use it! Is that something new?

**Comment by kelson42** [comment]
After discussing with @MohitMaliFtechiz here is how it should be IMO:
* The message "Please allow internet permission to download content" should be replaced with "Swipe Down for Books"
* Remove the "Allow" button
* This should not be an overlay, but display as alternative (and like) the error "No network connection"
