### ISSUE TITLE
"Allow download content via mobile network" message still not proper

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3224]
Reproduction steps:
* wifi: on, mobile data: on
* Deactivate wifi (so we have: wifi: off, mobile data: on)
* Go to online library, "Allow download content via mobile network" is displayed
* Click "no" and go to local library
* Activate wifi (so we have: wifi: on, mobile data: on)
* Go to online library

You get:
* "Allow download content via mobile network" is displayed
* This alert will be displayed automatically each time we 

We should get:
* No dialog, online library is downloaded via wifi

Remark:
* It seems to me that when the wifi is deactivated, then an event is send and handled properly by Kiwix... but nothing happens when wifi is activated (and connection to internet is secured).

**Comment by Hbkharsh** [comment]
hey can i try?

**Comment by kelson42** [comment]
There os already a PR for this!
