### ISSUE TITLE
Endless media access permission request

### ISSUE THREAD

**Issue by Samuel-Aktar-Laskar** [kiwix/kiwix-android#3229]
**Describe the bug**

The media access permission request keeps on popping again in infinite loop if you click deny. Also, if you click 'deny and don't ask again', it keeps on popping toast asking for giving permission in infinite loop. 

**Expected behavior**

If user clicks on deny, it should not ask for permission again, but it should show the toast only once. 
I think it would be better if instead of toast, in the UI itself in the 'library tab.'  it explains users that it needs storage permission for accessing downloaded zim files. Like here in VLC. 
<img src="https://user-images.githubusercontent.com/83684042/216510926-d70a97d4-dabc-4362-a501-9771bae40161.jpeg" width="30%" height="30%">
And if user has clicked 'deny and don't ask again', then on clicking grant permission, it should redirect to 'App Info' in settings to let the user grant permission from there. 

**Steps to reproduce the behavior:**
1.  Open the app for the first time after installing, or just 'clear all data' in app settings, and then open.
2.  Skip through introduction screens.
3.  Deny the permission for storage access.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Any comment?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 ,

* We need this permission for downloading content (ZIM files) and accessing zim files from storage.
* I have tested it and found this bug is exist in our app.
* we are checking everywhere for this permission where we need this. we can do everwhere like we did in ```OnlineLibraryFragment``` https://github.com/kiwix/kiwix-android/blob/0d1593f4e4414c785282c2aa19e16ee51e85bda5/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt#L402

here we are checking if we can take permission from user via android specific funtion ```ActivityCompat.shouldShowRequestPermissionRationale```, if not then we are showing a dialog to user and after clicking on yes user go into settings like mention above in issue.

**Comment by kelson42** [comment]
@MohitMaliFtechiz If we agree that Kiwix has no value, no use case, without his permission; why we ask? It should a requirement at install time!

**Comment by MohitMaliFtechiz** [comment]
* We are asking this permission on install time.
* For asking this permission everywhere 
   * if user manually remove this permission from app settings (app system setting). 
   * in newer android version we have a new option for permission ```allow only this time``` and if our app running in background for long time android runtime automatically remove this permission if user select ```allow only this time``` option (if user is on download screen so there we are checking this permission). or in some other cases (which is depend on user actions).

* I have just tested with custom apps and found if we can not give this permission then it showing a ```Storage Permission Denied ``` dialog. but the button message is wrong there (but functionality is right going to app setting). i'm attaching a screenshot.
![Screenshot_2023-02-03-18-51-21-513_org kiwix kiwixcustomcustomexample](https://user-images.githubusercontent.com/34593983/216614270-22153c7f-801b-4194-a7a8-84fb850f8e34.jpg)

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thx! Do you disagree with this:
* no reason to allow to use the app, both custom and kiwix, without this permission
* we shoukd not allow to deny giving the permission. If NOK, then quit the app
* dialog should be clear about error, reason and way to give permission

**Comment by Samuel-Aktar-Laskar** [comment]
Should I make it like this: 
When user open the app for the first time, it will show a dialog justifying why it needs storage access permission. 
If user clicks yes, it will ask for it. 
If the user denys in the dialog or if the user denys after clicking yes on dialog or if the user has previously denied, then in the LocalLibraryFragment, in fragment ui itself, it will explain user that the offline books are unavailable without storage access permission. Like in the screenshot of vlc app I attached in the issue.
What is your opinion?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 ,

> no reason to allow to use the app, both custom and kiwix, without this permission
 
* For custom app, if this permission is not granted then we can not use the application but we can use kiwix app without this permission.

https://user-images.githubusercontent.com/34593983/216947421-c43f2b12-69d0-49ae-98a8-352db7dfa1cd.mp4

> we shoukd not allow to deny giving the permission. If NOK, then quit the app

  for this we should use this dialog which is in video sample because it is non cancelable so user can not use the app without giving this permission.

> dialog should be clear about error, reason and way to give permission

We can show this dialog in both apps (custom and kiwix) and change the message(```This app requires the ability to read storage to function. Please grant the storage permission in your app setting```) and button (Go to setting or OK) text

![Screenshot_2023-02-03-18-51-21-513_org kiwix kiwixcustomcustomexample](https://user-images.githubusercontent.com/34593983/216614270-22153c7f-801b-4194-a7a8-84fb850f8e34.jpg)

>  think it would be better if instead of toast, in the UI itself in the 'library tab.' it explains users that it needs storage permission for accessing downloaded zim files. Like here in VLC.

if we use above solution then we don't need this. @kelson42 is this look good to you?

**Comment by kelson42** [comment]
> > no reason to allow to use the app, both custom and kiwix, without this permission
> 
>     * For custom app, if this permission is not granted then we can not use the application but we can use kiwix app without this permission.

How can we use Kiwix app without this permission? You have yourself written "We need this permission for downloading content (ZIM files) and accessing zim files from storage.". Without content Kiwix has no value!

**Comment by kelson42** [comment]
> @MohitMaliFtechiz Thx! Do you disagree with this:
> 
>     * no reason to allow to use the app, both custom and kiwix, without this permission
> 
>     * we shoukd not allow to deny giving the permission. If NOK, then quit the app
> 
>     * dialog should be clear about error, reason and way to give permission

Looks good to me, a least I don't have a better idea. Please isolate and modularise the dialog code properly that we don't have the kind of error we have currently with the wrong messaging.

**Comment by MohitMaliFtechiz** [comment]
> > > no reason to allow to use the app, both custom and kiwix, without this permission
> > 
> > 
> > ```
> > * For custom app, if this permission is not granted then we can not use the application but we can use kiwix app without this permission.
> > ```
> 
> How can we use Kiwix app without this permission? You have yourself written "We need this permission for downloading content (ZIM files) and accessing zim files from storage.". Without content Kiwix has no value!

@kelson42 , I meant without this permission we can not download content and reading the zim files. But we can use the other part of application (I'm attaching a video for this ). In custom app we can not access the other part of app firstly we need this permission after that user can use the app  (as shown above in video sample).


https://user-images.githubusercontent.com/34593983/216957048-87431c42-e41b-4999-ab5c-c7272257b24f.mp4

**Comment by kelson42** [comment]
@Samuel-Aktar-Laskar I was and I'm still unsure. But considering that we have also related bug and that this bug is heavy, I would prefer if @MohitMaliFtechiz would fix it straight. Would you be OK to test if everything looks good to you and review the PR?

**Comment by Samuel-Aktar-Laskar** [comment]
Okay sure, 
then I am looking for other good first issues

**Comment by kelson42** [comment]
@MohitMaliFtechiz Finally I have tested this scenario on my phone (I removed the authorization in Android apps settings) and I'm not able to reproduce this behaviour. I have the toast "To access offline content we need access to your storage" which is displayed all the time, but no popup. So wonder if @Samuel-Aktar-Laskar has done this with an old version or has followed on other path.

Anyway, it seems that our solution is mostly to remove the "deny" and "don't ask anymore" buttons... but at the end this dialog will be displayed the whole time as long as the permission is not given. So in a way a pretty similar symptom which has been described in the ticket. It will just be clearer for the user that he has to give the permission. If OK for you, please implement.

**Comment by kelson42** [comment]
> Okay sure, then I am looking for other good first issues

And reporting bugs is really useful as well. The app is pretty mature actually, there is no that much new things to do. But there is a lot to do to improve te existing.

**Comment by MohitMaliFtechiz** [comment]
> It will just be clearer for the user that he has to give the permission. If OK for you, please implement.

@kelson42 , ok i'm implementing this.
