### ISSUE TITLE
No items != no network

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#323]
This is a corner-case, however it helps indicate scope for improving the messages displayed to users by the app when there are content and network issues.

When testing with an empty `library_zim.xml` file. Kiwix Android displays `no network connection` rather than something like "no items available to download". I think there'll be other network conditions that are also reported as `no network connection` rather than what's happening. 

How about we make a start at improving the error reporting to users (and perhaps also log the errors so we can diagnose what's going wrong)? See #252 on improving the logging to help diagnose issues.

Note: We'll probably end up creating some additional strings that'll need translating.

**Comment by julianharty** [comment]
Here's the code that seems to display the message erroneously
```
  @Override
  public void displayNoNetworkConnection() {
    if (books.size() != 0) {
      Toast.makeText(super.getActivity(), R.string.no_network_connection, Toast.LENGTH_LONG).show();
      return;
    }

    networkText.setText(R.string.no_network_msg);
    networkText.setVisibility(View.VISIBLE);
    permissionButton.setVisibility(View.GONE);
    swipeRefreshLayout.setRefreshing(false);
    swipeRefreshLayout.setEnabled(false);
    TestingUtils.unbindResource(LibraryFragment.class);
  }
```

As a detail, at least in English we have the identical text for 2 strings: `no_network_msg` and `no_network_connection`. Perhaps it'd be worth revising the text for the first message e.g. to `No network available.`?

**Comment by kelson42** [comment]
Yes, maybe a duplicate with #263?

**Comment by julianharty** [comment]
They (this issue and #263) are affected a common limitation in the app, however they're distinct flaws and deserve distinct informational messages for users, in my view. Now I've established the local_download_server build flavour and have a local instance of a mini kiwix download server we can test and try to address #263 more easily, I hope... Ditto this one should be easier to test and address now we have suitable `library_zim.xml` files. Thanks for finding the connection, now we can address them both.

**Comment by divadsn** [comment]
I was working with that section of code, I was also confused but I haven't got that message displayed.

**Comment by divadsn** [comment]
Some progress, I just added `127.0.0.1 download.kiwix.org` into the hosts on my local machine and configured the local NGINX server to return an empty XML file, it seems to cause this then:
`01-20 18:44:07.012 10212-10212/org.kiwix.kiwixmobile W/kiwixLibrary: Error loading books:Attempt to invoke virtual method 'int java.util.LinkedList.size()' on a null object reference`

**Comment by divadsn** [comment]
Playing a bit around, I think I am close to have it fixed :)

```
@Override
  public void showBooks(LinkedList<Book> books) {
    if (books == null) {
      Toast.makeText(super.getActivity(), "NOTHUNG", Toast.LENGTH_LONG).show();
      return;
    }

    Log.i("kiwix-showBooks", "Contains: " + books.size());
    libraryAdapter.setAllBooks(books);
    if (faActivity.searchView != null) {
      libraryAdapter.getFilter().filter(
          faActivity.searchView.getQuery(),
          i -> stopScanningContent());
    } else {
      libraryAdapter.getFilter().filter("", i -> stopScanningContent()  );
    }
    libraryAdapter.notifyDataSetChanged();
    libraryList.setOnItemClickListener(this);
  }
```

Results with this:
![screenshot_1516470768](https://user-images.githubusercontent.com/28547847/35186359-355cbe3c-fe13-11e7-90dc-6bfc6f0077d9.png)

**Comment by divadsn** [comment]
And here's the empty list returned by the local web server:
![Empty XML list](https://i.imgur.com/8ve2x0s.png)

If this is how the empty XML should be, then the fix is ready to create a PR.

**Comment by mhutti1** [comment]
I think that is correct from what I can see.

**Comment by kelson42** [comment]
@divadsn Well done, I see creating a repro-case needed here a bit of instrumentation!

**Comment by julianharty** [comment]
@divadsn Thanks for the improvement.
