### ISSUE TITLE
Kiwix unable to find files on my SD card

### ISSUE THREAD

**Issue by ducmatgoctoanlyhoa** [kiwix/kiwix-android#3231]
v

**Describe the bug**

Kiwix does not read the wikipedia_en_all_maxi_2022-05.zim in my microsd card

**Expected behavior**

It should detect the file

- [ ] **Steps to reproduce the behavior:**

I downloaded the ZIM file (via torrents)
and moved it to my MicroSD card

**Screenshots**

![Screenshot_20230206_072739_Kiwix.jpg](https://user-images.githubusercontent.com/71325886/216855700-258fb9b6-82cc-4d3e-92ac-7b08daa06251.jpg)

![Screenshot_20230206_073341_My Files.jpg](https://user-images.githubusercontent.com/71325886/216856167-7e3015d8-ba71-4bd4-8304-8b297799b0c8.jpg)

**Environment**
- Version of Kiwix Android : 3.4.4 Build 6330404
- Device : Samsung Galaxy A72
- OS version : Android 13

**Comment by kelson42** [comment]
@ducmatgoctoanlyhoa Can you please try with latest release https://download.kiwix.org/release/kiwix-android/kiwix-3.6.0.apk (not on playstore yet)?

**Comment by ducmatgoctoanlyhoa** [comment]
@kelson42 ![Screenshot_20230206_152622_My Files.jpg](https://user-images.githubusercontent.com/71325886/216921617-8b5efafe-e87f-4eb8-aa6f-5ca6565bf2f0.jpg)

I got a bunch of folders like this, what do I do? There seems to have no binary folder.

**Comment by kelson42** [comment]
@ducmatgoctoanlyhoa Have you installed latest version like requested?

**Comment by ducmatgoctoanlyhoa** [comment]
> @ducmatgoctoanlyhoa Have you installed latest version like requested?

@kelson42 I did. But now I am running with some sort of a paradoxical issue here.

You see, Kiwix requires access to internal memory. However, when I go to the settings  to change, there was no option to enable memory access.

![Screenshot_20230207_200808_Permission controller.jpg](https://user-images.githubusercontent.com/71325886/217253960-c442dd7b-cffb-4365-8ae2-a8f35bc14ece.jpg)

What should I do?

**Comment by MohitMaliFtechiz** [comment]
@ducmatgoctoanlyhoa ,

Since you are using android 13 we can not directly access zim file from your whole SD Card. You can follow these steps.
* Goto kiwix app setting.
* Select storage option and select SD card, then choose your desire folder where zim file should downloaded.
* Now move you ZIM file into that folder, then check ZIM file is read by kiwix app.

**Note**
* Please make sure in your ```bin or trash folder``` have not contain any ZIM file.

**Comment by MohitMaliFtechiz** [comment]
> @kelson42 I did. But now I am running into some sort of a paradoxical issue here.
You see, Kiwix requires access to internal memory. However, when I go to the settings to change, there was no option to enable memory access.

hi @ducmatgoctoanlyhoa ,

* I have check this and in latest nightly build this popup is not showing (are you using latest nightly build?).
* If still you facing this problem then please follow these steps.
   * Goto kiwix app setting.
   * Select ```Allow to read and write ZIM files on SD card``` option as showing in below image.
   * Give access to kiwix app.

   | Kiwix setting | Phone setting |
   | ------------- | ------------- |
   | ![Screenshot from 2023-02-10 12-41-50](https://user-images.githubusercontent.com/34593983/218027690-32097878-7c8f-429b-8ed4-58ca0c959b5a.png) | ![settings](https://user-images.githubusercontent.com/34593983/218027935-2f2f4266-5a72-4e0a-81e7-615e06880e7f.png) |

**Comment by ducmatgoctoanlyhoa** [comment]
> @ducmatgoctoanlyhoa Have you installed latest version like requested?

@kelson42 I did. But now I am running with some sort of a paradoxical issue here.

You see, Kiwix requires access to internal memory. However, when I go to the settings  to change, there was no option to enable memory access.

![Screenshot_20230207_200808_Permission controller.jpg](https://user-images.githubusercontent.com/71325886/217253960-c442dd7b-cffb-4365-8ae2-a8f35bc14ece.jpg)

What should I do?
   
@MohitMaliFtechiz I did, and no more broken! 

but there is a problem. I have the ZIM file of wikipedia downloaded straight from the Kiwix server, stored it in the card, and when I try to open it manually Kiwix responded with not a valid ZIM! What should I do next?

**Comment by MohitMaliFtechiz** [comment]
@ducmatgoctoanlyhoa ,

* You said when you open it manually then it's showing not a valid ZIM. 
* Is this ZIM file showing in Library window which you want to open manually?
* If it is not showing in library window then please put it into that folder which you have give permission previously in SD card (```via following these steps```  _Originally posted by @MohitMaliFtechiz in https://github.com/kiwix/kiwix-android/issues/3231#issuecomment-1422596792_ ) and try again to open it manually.

**Comment by kelson42** [comment]
@ducmatgoctoanlyhoa any feedback?

**Comment by ducmatgoctoanlyhoa** [comment]
@kelson42 @MohitMaliFtechiz so this is more of a Android issue than a Kiwix issue. Thanks for your help!

**Comment by MohitMaliFtechiz** [comment]
@ducmatgoctoanlyhoa , yes in android 13 they restrict apps to only access app specific directory on SD card.
