### ISSUE TITLE
[Updated] Requested URL cannot be loaded as service workers are not supported here

### ISSUE THREAD

**Issue by prahladyeri** [kiwix/kiwix-android#3234]
**Describe the bug**
This error appears saying that requested URL cannot be loaded as service workers are not supported here. Particularly found while viewing MDN Web Docs zim file on Android Chrome browser (latest version of Chrome as of today).

**Expected behavior**
View the Kiwix resource.

**Steps to reproduce the behavior:**

1. install kiwix android
2. Download MDN Web Docs'
3. Try to open file in Kiwix Android

**Screenshot**

![mdn_docs_error](https://user-images.githubusercontent.com/5732256/217033333-b45eb32a-ab35-43dc-ab86-29bf8d4cb052.jpg)

**Environment**
- Version of Kiwix Android : 
- Device : Redmi Y2
- OS version : 9 (Pie)

So, this is just a re-raising of bug #2789 created earlier as the issue doesn't seem to have resolved yet. I'm facing this even with the latest version of Chrome installed. If not a fix, could you at least provide a workaround?

**Comment by kelson42** [comment]
This should work. Looks really like a bug. I will try to reproduce.

**Comment by prahladyeri** [comment]
@kelson42 The version is:

```
3.3.4 Build: 5230304
```

**Comment by kelson42** [comment]
> @kelson42 The version is:
> 
> ```
> 3.3.4 Build: 5230304
> ```

This is probably the reason, please install latest stable version from https://download.kiwix.org/release/kiwix-android/kiwix-3.6.0.apk. It should work.

**Comment by prahladyeri** [comment]
@kelson42 Thanks a lot! This got resolved after the upgrade to latest version.
