### ISSUE TITLE
When we scroll up, then white space showing in LocalLibraryFragment .

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3240]
**Describe the bug**
When we scroll up, then white space showing in ```LocalLibraryFragment``` . 

**Expected behavior**
It should not show the white space when we scrolling.

**Steps to reproduce the behavior:**
1. Open Local Library Fragment
2. Scroll up
3. You will see the white space in bottom of screen.

**Environment**
- Version of Kiwix Android : Latest develop branch
- Device : Redmi note 9
- OS version : Android 12

**Video**

https://user-images.githubusercontent.com/34593983/220914724-1de3b2e9-19e0-4d39-93a7-fc3a5f6ccdbe.mp4

**Comment by kelson42** [comment]
Ohoh, I see last bug around bottom bar has not been 100% fixed!?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 , No last bug is fixed, This bug is introduce after placing fix for https://github.com/kiwix/kiwix-android/issues/3210 .

**Comment by kelson42** [comment]
This is the bug i meant

**Comment by MohitMaliFtechiz** [comment]
> This is the bug i meant

yes, this is the bug.
