### ISSUE TITLE
Replace depreacted API with new ones

### ISSUE THREAD

**Issue by criticalAY** [kiwix/kiwix-android#3245]
I suggested updating the deprecated methods with new API that google provided as deprecated methods cause problems in long run
**Describe the bug**

For Example :
```
Deprecated
androidx.activity.ComponentActivity now implements MenuHost, an interface that allows any component, including your activity itself, to add menu items by calling addMenuProvider(MenuProvider) without forcing all components through this single method override. Each MenuProvider then provides a consistent, optionally Lifecycle-aware, and modular way to handle menu item selection for the menu items created by that provider. Replace usages of this method with one or more calls to addMenuProvider(MenuProvider) in your Activity's onCreate(Bundle) method, delegating menu item selection to the individual MenuProvider that created the menu items you wish to handle.
```
**Expected behavior**
No Deprecation warning

-->

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.6.0
- Device :  Emulator
- OS version : 12

**Logs**

**Comment by criticalAY** [comment]
I suggest not closing this issue until we are done with most of the Deprecated methods

**Comment by kelson42** [comment]
@criticalAY One ticket, one PR. Either there is a problem which can be all tacle the same way in one PR... or we have multiple problems which should be tacle differrently and then we have multiple tickets.

**Comment by criticalAY** [comment]
@kelson42 ok I will hunt down all the deprecated API related to menu and replace with relevant ones. But there are mutiple deprecation in the projects that must be updated or handled properly using compat files in case they don't work on old SDKs

**Comment by criticalAY** [comment]
Well the #3092 seems to be pointing in a wrong direction these files are unused rather than deprecated deprecation is usually tragets `@Target(CLASS, FUNCTION, PROPERTY, ANNOTATION_CLASS, CONSTRUCTOR, PROPERTY_SETTER, PROPERTY_GETTER, TYPEALIAS)`
