### ISSUE TITLE
Add "Tabs Closed" Dialog

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3249]
**Is your feature request related to a problem? Please describe.**

It would be very frustrating if the user accidently clicked on "x" FAB in "Tab switcher" while reading. All the pages will be gone and then the user have to open them again manually.
<img src="https://user-images.githubusercontent.com/85388413/221396531-185e9a6f-d94d-4013-a247-e3fcbb83973d.png" height="500px">
So, there should be a Snackbar to show Undo option also for "Closing all tabs"(Already exist for Closing Individual Tab).

**Describe the solution you'd like**

Show a Similar Snackbar to Undo the changes.
<img src="https://user-images.githubusercontent.com/85388413/221396611-1964a111-6ba0-420e-9a6a-03c7cc05a9e0.png" height="500px">
In code, when we have this feature for individual tabs, we have a "File" object that stores the "tempZimFileForUndo", instead we can use a "List<File>" for both the cases, or we can have a different List<File> object to store temp removed Files for undo. And then we can use the same functionality for "Closing all tabs" to achieve a better user experience.

**Comment by Sagar0-0** [comment]
I found all the required changes that needs to be done. Let me know if this looks valid to you and assign it to me so that I can start creating PR.

**Comment by kelson42** [comment]
@Sagar0-0 Feature sounds neat and useful if implemented properly. I let @MohitMaliFtechiz react on the tech details, but one approach would be just to hide the tab first and destroy it with the snackbar.

**Comment by Sagar0-0** [comment]
> @Sagar0-0 Feature sounds neat and useful if implemented properly. I let @MohitMaliFtechiz react on the tech details, but one approach would be just to hide the tab first and destroy it with the snackbar.

Great, that will be also easy to Implement in code, and also we don't have to change any existing thing of storing the temp files.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 , @Sagar0-0 , This feature look useful to me from user point of view, we should implement this.

> but one approach would be just to hide the tab first and destroy it with the snackbar.

good point. Also we should clear the temp list after ```snack bar``` is hidden, by this way we will avoid the memory leak as well.

**Comment by Sagar0-0** [comment]
Great, thanks for responding! Please assign this issue to me, so that now I can start Implementing it.

**Comment by kelson42** [comment]
@Sagar0-0 Would you volunteer to implement this feature in the next days? Should I assign the ticket to you?

**Comment by Sagar0-0** [comment]
Sure @kelson42

**Comment by Sagar0-0** [comment]
Should we implement a confirmation Dialog/Snackbar? In that way, we don't have to create and store any list of temp files and it will be quick also(comparatively). 
OR
We can just clear the webViewList(just for showing) and then convert the "closeAllTabsButton" button into a "✔️"(confirm) button, and thennnn we can actually clear the List after confirmation.(also have show an undo option then)

**Comment by kelson42** [comment]
No confirmation, simple deletion and then the snackbar is displayed for a few second with an "undo" button, then disappear.

**Comment by Sagar0-0** [comment]
[device-2023-03-01-155753.webm](https://user-images.githubusercontent.com/85388413/222113471-246d7cc9-6adf-428f-928b-0197f8a6a3bc.webm)
LGTM, should I PR now?

**Comment by HimanshuMahto** [comment]
hello can you tell me what is the name of the layout in which we need to work as I'm new to this so that I can solve it.

**Comment by HimanshuMahto** [comment]
i think the issue has been resolved as the feature you are talking about is present in the app

**Comment by Sagar0-0** [comment]
No need, already done PR.
