### ISSUE TITLE
Add "Delete Note" Dialog

### ISSUE THREAD

**Issue by vishesh211** [kiwix/kiwix-android#3255]
**Is your feature request related to a problem? Please describe.**

If the user accidentally clicks on the delete note button it will be very frustrating for the user to write the whole note again. Therefore it is better to confirm it from the user before deleting the note.

!<img src="https://user-images.githubusercontent.com/61341524/221638678-d58af762-5c67-4ae1-872c-c2018333fe23.jpeg" width=30% height=30%>

**Describe the solution you'd like**

1) Show a dialog asking the user to confirm if they want to delete the note.
2) The dialog will contain the following string "Are you sure you want to delete the dialog?". With buttons "YES" and "NO".
3) The dialog will follow the standard dialog template used in the application. It will look something like the dialog below.

!<img src="https://user-images.githubusercontent.com/61341524/221640243-44888b14-5218-40d6-8bbb-78779dff70bf.jpeg" width=30% height=30%>

**Comment by criticalAY** [comment]
I would like to be assigned to this issue

**Comment by kelson42** [comment]
Not convinced we should do that. Confirm dialog are annoying.

**Comment by kelson42** [comment]
I think the solution is a temporary snackbar with an "undo" button.

**Comment by vishesh211** [comment]
@kelson42  snackbar works. I have implemented and checked it. I have identified all the necessary changes that needs to be done and almost implemented it. I would request you to assign this issue to me so that i can go ahead and create a PR.
