### ISSUE TITLE
APK file not working

### ISSUE THREAD

**Issue by svikrantaxioned** [kiwix/kiwix-android#3256]
Description -
We have downloaded apk file from https://download.kiwix.org/nightly/kiwix-universal.apk 
Once the file is downloaded, the file cannot be installed on android device.
Can you provide steps to install the file ?

**Comment by MohitMaliFtechiz** [comment]
@svikrantaxioned ,
* Which android version you are using?
* What is the error message exactly when you try to install?
* Please uninstall previous version if any installed in your device.

**Comment by svikrantaxioned** [comment]
Thanks for your help/support. We are able to install the .apk file now. As it was sent as a .zip extension we first needed to rename it to .apk and it seems working.

We can close this ticket
