### ISSUE TITLE
None version work with my Android 4.1.2 tablet

### ISSUE THREAD

**Issue by SuperUserNameMan** [kiwix/kiwix-android#3259]
Hi,

**Environment**
- Version of Kiwix Android : all of them
- Device : Acer Iconia B1 tablet
- OS version : android 4.1.2

**Describe the bugS**

- it can't install Kiwix above version 3.2.1, and it displays error message in french meaning : "Analyze error : encountered a problem while analyzing the package" (i tried all the .apk version i found on your github and on this page https://download.kiwix.org/release/kiwix-android/)

- with Kiwix 3.2.1 and below, it install fine, but it can't download any online ZIM : The list of all available ZIM is displayed correctly ; too large files are greyed ; nothing happen when clicking on the tiny non-greyed ZIM ; there is no "download" button, nothing ...

- with Kiwix 3.2.1 and any older version, it can't read ZIM copied from external download (#1447). I copied it into the internal SD which has 4,23 GB  of free space available, and also into a 32GB external SD card. Both fail with different errors (see logs) :

**Logs**

When copied into internal SD, the `loagcat.txt` says : 
````
E/kiwix   ( 3342): Error opening ZIM file
E/kiwix   ( 3342): Cannot mmap size 4026733382 at off 80 : Invalid argument
E/kiwix   ( 3342): Attempting to create reader with: /storage/sdcard0/Kiwix/wikipedia_fr_all_mini_2023-02.zim
````
When copied into external SD, the `logcat.txt` says :
````
E/kiwix (5185): Attempting to create reader with: /storage/sdcard1/vikidia_fr_all_maxi_2023-02.zim
E/kiwix (5185): Unable to get zim title
E/kiwix (5185): Invalid comrpession flag
E/kiwix (5185): Unable to get zim creator
E/kiwix (5185): Invalid comrpession flag
````

**Comment by kelson42** [comment]
@SuperUserNameMan Use latest version of Kiwix https://download.kiwix.org/release/kiwix-android/kiwix-3.6.0.apk... all the version your give are old.

**Comment by SuperUserNameMan** [comment]
> @SuperUserNameMan Use latest version of Kiwix https://download.kiwix.org/release/kiwix-android/kiwix-3.6.0.apk... all the version your give are old.

I know it old. But as i mentioned, none recent version want to install.

The last installable version is 3.2.1.

After that it displays error message in french meaning : "Analyze error : encountered a problem while analyzing the package"

**Comment by kelson42** [comment]
@SuperUserNameMan without a full report with latest apk, i will close the ticket but i realized your Android is probably not even supported anymore anyway.

**Comment by SuperUserNameMan** [comment]
To whoever encounter same problem : here is a workaround thanks to @Jaifroid 

https://github.com/kiwix/kiwix-android/issues/2592#issuecomment-1464091382
