### ISSUE TITLE
Kiwix-android seems to corrupt ZIM chunks file names (and kills kiwix-android)

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#326]
I believe we're already aware of the behaviour, here's an example that triggered the application dying when it was trying to open a zim file.

I've got a 64GB SD-card formatted with FAT32 (so the older tablet can read the content) with 2 large ZIM files: a fairly old Spanish wikipedia that's been on the card and in the device for a long time, and a newer ZIM file - the german novid wikipedia content I've just added directly (not downloaded using Kiwix Android).

The device is a Lenovo Yoga Tab B6000-H running Android 4.2.2 

I'll try testing on other devices that can accept the SD-Card.

Here's an extract of adb logcat. The jdwp messages are flooding log BTW
```
I/kiwix: Opening ZIM file /storage/sdcard1/wikipedia_es_all_05_201.zimaa
A/libc: ../../SOURCE/libzim/src/file_reader.cpp:90: virtual void zim::FileReader::read(char*, zim::offset_type, zim::offset_type) const: assertion "offset < _size" failed
D/jdwp: sendRequest : Len=0x56
A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 18322 (Thread-863)
```

**Comment by julianharty** [comment]
The same Spanish ZIM file can be read by an older version of Kiwix Android (version 1.99) installed in a Nook HD+ running CyanogenMod 6.0.1

**Comment by julianharty** [comment]
Reproduced this crash when I created a zero-byte `test.zim` on a Barnes & Noble Nook HD+ (Android 6.0.1). I doubt the specific device is that relevant though. Anyway, the same assertion failed.
The file was created using a file manager. `touch test.zim` would also create a similar file (run from `adb shell` etc.)

```
12-15 12:15:48.278 22482-22549/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/body.js
12-15 12:15:48.283 22482-22528/org.kiwix.kiwixmobile W/ContentResolver: Failed to get type for: content://org.kiwix.kiwixmobile.zim.base/-/j/body.js (Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference)
12-15 12:15:48.283 22482-22528/org.kiwix.kiwixmobile W/ContentResolver: Failed to get type for: content://org.kiwix.kiwixmobile.zim.base/-/j/body.js (Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference)
12-15 12:15:48.283 22482-22554/org.kiwix.kiwixmobile D/kiwix: reading  -/j/body.js(mime: application/javascript, size: 17200) finished.
12-15 12:15:49.271 22482-22482/org.kiwix.kiwixmobile D/kiwix: Loaded URL: content://org.kiwix.kiwixmobile.zim.base/A/index.html
12-15 12:15:49.297 22482-22482/org.kiwix.kiwixmobile D/kiwix: Loaded URL: content://org.kiwix.kiwixmobile.zim.base/A/index.html
12-15 12:15:50.145 22482-22482/org.kiwix.kiwixmobile I/ListPopupWindow: Could not find method setEpicenterBounds(Rect) on PopupWindow. Oh well.
12-15 12:15:52.890 22482-22482/org.kiwix.kiwixmobile D/kiwix: onPause Save currentzimfile to preferences: /storage/6665-3832/Android/data/org.kiwix.kiwixmobile/wikipedia_en_uganda_09_2014 - copy.zim
12-15 12:15:53.089 22482-22482/org.kiwix.kiwixmobile I/kiwix: ZimManageActivity successfully bootstrapped
12-15 12:15:53.263 22482-22558/org.kiwix.kiwixmobile A/libc: ../../SOURCE/libzim/src/file_reader.cpp:90: virtual void zim::FileReader::read(char*, zim::offset_type, zim::offset_type) const: assertion "offset < _size" failed
12-15 12:15:53.308 22482-22557/org.kiwix.kiwixmobile D/android-storage-devices: Unable to create marker file, duplicates may be listed
12-15 12:15:53.431 22482-22557/org.kiwix.kiwixmobile D/android-storage-devices: Unable to create marker file, duplicates may be listed
12-15 12:15:53.443 22482-22558/org.kiwix.kiwixmobile W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
12-15 12:15:53.443 22482-22558/org.kiwix.kiwixmobile W/google-breakpad: Chrome build fingerprint:
12-15 12:15:53.443 22482-22558/org.kiwix.kiwixmobile W/google-breakpad: 2.3
12-15 12:15:53.443 22482-22558/org.kiwix.kiwixmobile W/google-breakpad: 55
12-15 12:15:53.443 22482-22558/org.kiwix.kiwixmobile W/google-breakpad: 023f32a1-4862-425f-a49b-e5b1792614ed
12-15 12:15:53.443 22482-22558/org.kiwix.kiwixmobile W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
12-15 12:15:53.443 22482-22558/org.kiwix.kiwixmobile E/chromium: ### WebView Version 44.0.2403.119 (code 246011900)
12-15 12:15:53.444 22482-22558/org.kiwix.kiwixmobile A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 22558 (Thread-519)
12-15 12:15:53.461 22482-22557/org.kiwix.kiwixmobile D/kiwix: Searching directory /mnt
```

**Comment by mgautierfr** [comment]
Please open a issue on libzim. The bug is definitively there.

**Comment by julianharty** [comment]
Done, the bug will be tracked at https://github.com/openzim/libzim/issues/106 we can close this one once there's a fix. Thank you @mgautierfr

**Comment by kelson42** [comment]
@julianharty The libzim should not crash. This is definilty a bug. That said, please investigate why kiwix-android seems to try to open `/storage/sdcard1/wikipedia_es_all_05_201.zimaa` instead of `/storage/sdcard1/wikipedia_es_all_05_2017.zimaa`. Highly probable we have a but here to, this time in Android.

**Comment by julianharty** [comment]
@kelson42 I guess the strange filename would have been because I'd renamed the zim file. I can't find the combination of device and ZIM file I used at the time (too many Nooks :) Once we have a potential fix I'll dig out a copy of the Spanish wikipedia from May 2017 and try with it.

**Comment by kelson42** [comment]
@julianharty The crash scenario at the libzim level has been fixed and the app does not write ZIM chunks (*.zimaa, ...) as long as the full content has not been download (see #355). I strongly believed this should have fixed this bug. Therefore I'll close it.
