### ISSUE TITLE
Upgrade android gradle version to 8.0

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3266]
**Describe the bug**
We are using android gradle version 7.6. we should use 8.0 as translate wiki suggested for take advantage of new gradle. Previously we are refactored our code to make compatible with gradle 8.0 in https://github.com/kiwix/kiwix-android/pull/3165.

**Comment by arexnnnn** [comment]
Hey Mohit! Can I help you on solving this issue?
