### ISSUE TITLE
Make local ZIM files selectable

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#327]
In preparation for Cross ZIM search it must be possible for the user to select the list of ZIM files that they wish their search to take place in. We should add a checkbox to local ZIM files and the state of this box should be stored persistently as a column in our databases Book table. (Remember to increase our database version when implementing this).

Also provide a utility method in https://github.com/kiwix/kiwix-android/blob/master/app/src/main/java/org/kiwix/kiwixmobile/database/BookDao.java to get the list of selected ZIM files.

**Comment by divadsn** [comment]
Where should the user see those checkboxes?

**Comment by mhutti1** [comment]
They should be located on the list of locally downloaded files in the content manager. If you think that a long click multi item select with some form of persistent indicator of selection (i.e colour) would be more appropriate then that would also be acceptable.

**Comment by kelson42** [comment]
On iOS this list can be changed at the time of the search. I think it is quite a good approach to have this configured someone at the search time instead at in the library.

**Comment by Ananthusubramanian** [comment]
Is anyone working on this issue?

**Comment by brijeshshah13** [comment]
@Ananthusubramanian No one has been assigned the task. However, please clarify first about how the implementation is to be carried out with @mhutti1 @kelson42.

**Comment by mhutti1** [comment]
This issue is the first part of an issue that was partitioned for GCI. I am going to close it as such and we will come up with a more robust single implementation.
