### ISSUE TITLE
Library showing a blank screen in android 13

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3273]
**Describe the bug**
```LibraryFrgment``` showing a blank screen in android 13.

**Expected behavior**
It should show the zim files instead of blank screen.

**Steps to reproduce the behavior:**
* Install kiwix app in android 13 emulator or in real device.
* Open application and download any zim file
* Goto library screen you will see the blank screen instead of zim files.

**Screenshots**
![Screenshot from 2023-03-17 14-42-07](https://user-images.githubusercontent.com/34593983/225862781-d6b7b203-7ab2-402a-8e1d-680a189a71f8.png)

**Environment**
- Version of Kiwix Android : Current develop branch
- Device : Emulator
- OS version : Android 13

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please write an automated test that such a bug can not go unoticed.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 , For this, We have already automated test cases like (```DownloadTest```  ```InitialDownloadTest```) in these test cases we are deleting the zim file in ```LocalLibrary fragment``` (First we downloading the zim file and after that it delete if it fails to delete the zim file then test cases will failed)

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Have we seen failing those tests? Or It's only failing on Android 13. In this case, we should integrate Android 13 as well in our tests.

**Comment by kelson42** [comment]
@gouri-panda Exactly! If the test was not failing, there was no test of this scenario!

**Comment by MohitMaliFtechiz** [comment]
>  Have we seen failing those tests?

@gouri-panda , yes, i remember i have seen these test are failing in a PR https://github.com/kiwix/kiwix-android/pull/3233 for that i have placed a condition in test cases. It's failing on android 13 and play store build.

> we should integrate Android 13 as well in our tests.

yes, we have a ticket open for it https://github.com/kiwix/kiwix-android/issues/3189, but automated test cases are not passing on android 13. I have spent many days on it and tried every possible way to run test cases on android 13 but due to unavailability of ```default_apis```  test cases are not passed on ```google_apis``` system images.

> @gouri-panda Exactly! If the test was not failing, there was no test of this scenario!

@kelson42 , the test cases not failing here because we are not testing on android 13 and in play store build.

**Very Important point**
I was testing this functionality in play store build, i have seen downloading is not working in play store build.

```
java.lang.RuntimeException: org.simpleframework.xml.core.PersistenceException: Constructor not matched for class org.kiwix.kiwixmobile.core.entity.MetaLinkNetworkEntity$Pieces
retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(SimpleXmlResponseBodyConverter.java:53)
at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:57)
at retrofit2.OkHttpCall.execute(OkHttpCall.java:25)
at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:22)
at io.reactivex.Observable.subscribe(Observable.java:3)
at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:8)
at io.reactivex.Observable.subscribe(Observable.java:3)
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:9)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:10)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:14)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:1)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: org.simpleframework.xml.core.PersistenceException: Constructor not matched for class org.kiwix.kiwixmobile.core.entity.MetaLinkNetworkEntity$Pieces
org.simpleframework.xml.core.ClassInstantiator.getInstance(ClassInstantiator.java:4)
org.simpleframework.xml.core.Composite$Injector.readInject(Composite.java:9)
org.simpleframework.xml.core.Composite$Injector.read(Composite.java:30)
org.simpleframework.xml.core.Composite.read(Composite.java:19)
org.simpleframework.xml.core.Composite.read(Composite.java:7)
org.simpleframework.xml.core.Composite.readVariable(Composite.java:47)
org.simpleframework.xml.core.Composite.readInstance(Composite.java:1)
org.simpleframework.xml.core.Composite.readUnion(Composite.java:1)
org.simpleframework.xml.core.Composite.readElement(Composite.java:76)
org.simpleframework.xml.core.Composite.readElements(Composite.java:25)
org.simpleframework.xml.core.Composite.access$400(Composite.java:1)
org.simpleframework.xml.core.Composite$Injector.read(Composite.java:27)
org.simpleframework.xml.core.Composite.read(Composite.java:19)
org.simpleframework.xml.core.Composite.read(Composite.java:7)
org.simpleframework.xml.core.Composite.readVariable(Composite.java:47)
org.simpleframework.xml.core.Composite.readInstance(Composite.java:1)
org.simpleframework.xml.core.Composite.readUnion(Composite.java:1)
org.simpleframework.xml.core.Composite.readElement(Composite.java:76)
org.simpleframework.xml.core.Composite.readElements(Composite.java:25)
org.simpleframework.xml.core.Composite.access$400(Composite.java:1)
org.simpleframework.xml.core.Composite$Builder.read(Composite.java:37)
org.simpleframework.xml.core.Composite.read(Composite.java:19)
org.simpleframework.xml.core.Composite.read(Composite.java:7)
org.simpleframework.xml.core.Traverser.read(Traverser.java:2)
org.simpleframework.xml.core.Persister.read(Persister.java:16)
org.simpleframework.xml.core.Persister.read(Persister.java:15)
org.simpleframework.xml.core.Persister.read(Persister.java:13)
org.simpleframework.xml.core.Persister.read(Persister.java:11)
retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(SimpleXmlResponseBodyConverter.java:13)
... 15 more
```

@kelson42 , @gouri-panda , IMO we should run automated test cases for play store build as well to avoid this type of errors.

**Comment by gouri-panda** [comment]
>yes, we have a ticket open for it #3189, but automated test cases are not passing on android 13. I have spent many days on it and tried every possible way to run test cases on android 13 but due to unavailability of default_apis test cases are not passed on google_apis system images.
