### ISSUE TITLE
Downloading file not listed in DOWNLOADING tab, visible in Android Notification

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#329]
I'm downloading a large ZIM file, 25GB. This has taken an hour and will take several more. The app had stopped (possibly as Google Play / The device was updating Google Chrome, as the Chrome WebView component disappeared while Kiwix was running). I restarted the app. I can see from `adb logcat` that the download continues, yet the downloading ZIM file isn't listed on the Downloading tab. I don't know if the file is still listed in the ONLINE tab as that's got over 2300 to scroll through at about 3 per screen & is prone to refreshing itself if I accidentally trigger a refresh. See #324 for some related UI/UX discussions.

I'd like to see the downloads listed with their progress in the DOWNLOADING tab. 

Note: the code is built from the `master` branch today (15 Dec 2017) while we're working as part of the mini-hackathon.

**Comment by paologarcia002** [comment]
This issue happens even with smaller files, as this one is only 9.8 GB and I did not leave the app, just left the downloading page.

![image](https://user-images.githubusercontent.com/35015371/36454947-0cc06138-166c-11e8-81fc-0f7bb0668cd5.png)
![image](https://user-images.githubusercontent.com/35015371/36455017-54209dae-166c-11e8-81b1-60eae413ff05.png)

**Comment by mhutti1** [comment]
@paologarcia002 if you can get reproduction steps it would be a great help.

**Comment by paologarcia002** [comment]
Yeah sure should I just write them out here or make a new post @mhutti1

**Comment by mhutti1** [comment]
Put them here

**Comment by iadeelzafar** [comment]
@abdulwd I tried to reproduce this issue and I think it has been resolved.

**Comment by abdulwd** [comment]
I'm closing this issue if it has not been resolved please reopen it.
