### ISSUE TITLE
Add support for Android 13's themed app icons

### ISSUE THREAD

**Issue by icejuice-enjoyer** [kiwix/kiwix-android#3291]
**Is your feature request related to a problem? Please describe.**

Kiwix looks out of place on my launcher when placed aside apps that support [Android 13's themed app icons](https://developer.android.com/about/versions/13/features#themed-app-icons).

**Describe the solution you'd like**

I would like Kiwix to support Android 13's themed app icons.

**Additional context**

https://developer.android.com/about/versions/13/features#themed-app-icons
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

**Comment by kelson42** [comment]
@gouri-panda Is that something you could fix while @MohitMaliDeveloper tires to fix the custom app publishing?

**Comment by gouri-panda** [comment]
@kelson42 Sure!
