### ISSUE TITLE
Snack Bar Not Visible in download library

### ISSUE THREAD

**Issue by shashank-0-0** [kiwix/kiwix-android#3298]
**Describe the bug**

Snack Bar hidden below the Bottom Navigation View in the download Screen (Online Library Fragment)

**Expected Behavior**

Snack bar should appear above the bottom Nav view 

**Steps to reproduce the Behavior:**
1. navigate to the download screen and once the content is loaded
2. Turn off the internet and u see the No network connection snack bar hidden below the bottom Navigation view 

**Screenshots**

![WhatsApp Image 2023-04-23 at 11 50 19](https://user-images.githubusercontent.com/111702455/233824443-887b9ca1-c453-4094-8d41-07ea628c05df.jpeg)

**Environment**
- Version of Kiwix Android : 3.6.0 (develop branch)
- Device : Realme 3i
- OS version : Android 10

**Comment by shashank-0-0** [comment]
I am excited to make my first contribution to the project ,can i fix this (if this is a valid issue)?

**Comment by kelson42** [comment]
@shashank-0-0  Check with latest nighlty, I think this is fixed http://download.kiwix.org/nightly/2023-04-23/

**Comment by kelson42** [comment]
@MohitMaliFtechiz You confirm? I really wonder how many more PR we need to get this working perfectly. Why we fail to get it working fine?

**Comment by shashank-0-0** [comment]
The snack bar works fine in other fragments , anchoring it with respect to the bottom navigation view will do the trick

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz You confirm?

@kelson42 I confirm this is a valid issue.

 >  I really wonder how many more PR we need to get this working perfectly. Why we fail to get it working fine?

This issue is different from what we fixed, it is in the `Download screen` we fixed the bottom margin in `LocalLibraryFragment` .

**Comment by kelson42** [comment]
@MohitMaliFtechiz OK. Please secure all this with the snack bar visibility is tested and fully fixed. This is already what was requested in last ticket. It is not normal to have so many similar tickets/issues regarding the very same sub component. It is expected from devs to analyse problems globally and not to just fix _a minima_ what is reported.

**Comment by kelson42** [comment]
@shashank-0-0 go for it! Waiting to your PR.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz OK. Please secure all this with the snack bar visibility is tested and fully fixed. This is already what was requested in last ticket. It is not normal to have so many similar tickets/issues regarding the very same sub component. It is expected from devs to analyse problems globally and not to just fix a minima what is reported.

@kelson42 , I have check all other snackbars and found this problem also exists with the `Insufficient space snackbar` when bottom navigation appears, apart from that all other snackbars are looking fine.

**Comment by shashank-0-0** [comment]
@MohitMaliFtechiz  @kelson42 , i have made the changes and it fixes the issues ,please review it and il be happy to rework if there are changes needed

**Comment by MohitMaliFtechiz** [comment]
@shashank-0-0 Thanks for your fix, I am reviewing the PR.
