### ISSUE TITLE
Invalid bookmark creation on Android

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#33]
_From @kelson42 on April 9, 2016 19:56_

1 - Click many times on "random" and "bookmark" icons in the action bar (to create dozens of random bookmarks
2 - Open the bookmarks (long clikc on bookmark icon)
3 - Part of the bookmarks listed are listed as content://org.kiwix.zim.base/..... and trying to open these bookmark opens the welcome page of the current ZIM file

The problem probably happens if the HTML is not fully loaded at the time the bookmark icon is clicked. Then the title of the page is probably unknown (HTML not fully parsed).

IMO, if the page is not fully loaded the bookmarking code should be triggered one time the page is loaded (non blocking). 

_Copied from original issue: kiwix/kiwix#20_

**Comment by mhutti1** [comment]
_From @EladKeyshawn on April 9, 2016 19:58_

im still on the version before the long click to open bookmarks and i dont see any problem

**Comment by mhutti1** [comment]
_From @EladKeyshawn on April 9, 2016 20:19_

Now i see its on tablet. i got a 4.4.4 android tablet and crashes when trying to open any article not just random

**Comment by mhutti1** [comment]
_From @EladKeyshawn on May 7, 2016 21:28_

@mhutti1, @kelson42  Is this still relevant ? as i have tested it and could not reproduce the problem.

**Comment by mhutti1** [comment]
_From @kelson42 on May 12, 2016 16:12_

Pretty sure if that was not fixed by a better bookmarking approach. Try with and old/lowend/slow device.

**Comment by mhutti1** [comment]
_From @EladKeyshawn on May 12, 2016 16:28_

I have a pretty cheap tablet running 4.4.4 and still can't reproduce.

**Comment by mhutti1** [comment]
You need to do it **very quickly** and have the random button in your action bar to allow the quick clicking.

**Comment by mhutti1** [comment]
_From @kelson42 on July 24, 2016 14:27_

@EladKeyshawn Any way to make this button (bookmark) actionable only at the time the page is completly loaded?

**Comment by mhutti1** [comment]
_From @EladKeyshawn on July 25, 2016 20:43_

@kelson42 Yes i'll check that, even though i could no reproduce the problem in anyway

**Comment by mhutti1** [comment]
_From @kelson42 on August 28, 2016 16:9_

@EladKeyshawn Do a check to be sure you can get the HTML title (so wait the page is fully loaded) and it will fix the problem

**Comment by mhutti1** [comment]
This is a tricky bug to reproduce. I don't know if we can get a 100% way for someone to reproduce unless they have a slow android tablet. My emulator is far to fast.

**Comment by mhutti1** [comment]
_From @kelson42 on November 22, 2016 18:25_

@mhutti1 I can always reproduce it. At least easy for me.

**Comment by mhutti1** [comment]
@kelson42 Yeah but its the kind of bug that can't be solved without testing and as we can't come up with guaranteed reproduction steps it may not be suitable for GCI at this time.

**Comment by kelson42** [comment]
@EladKeyshawn Could you help us on this? It seems you are the only developer able to reproduce the problem. Would you be able to implement soon the idea written in that comment https://github.com/kiwix/kiwix-android/issues/33#issuecomment-287542472? This would be great to close that old/tricky ticket.

**Comment by kelson42** [comment]
I will try to reproduce it with 3.0

**Comment by kelson42** [comment]
We believe this has been fixed.
