### ISSUE TITLE
Open ZIM-File on external USB-Stick in Android (Wikipedia)

### ISSUE THREAD

**Issue by Ohm66** [kiwix/kiwix-android#3304]
New Smartphones do not have a memory card slot.
So I organized a very small USB-Stick and planned to use it for the full blown Wikipedia, to have all information available on trips in foreign countries (without Internet).

On my new S23, I tested it, but was not able to open the ZIM-File, which I download by my former smartphone.
Is there a way to enable this?

Thanks, and best regards 
Ohm

**Comment by kelson42** [comment]
> New Smartphones do not have a memory card slot.

This is an over simplification.

A few years ago, external USB via OTG was not supported in Kiwix because it does not allow a native access to the filesystem. We have many closed tickets here on that topic.

@MohitMaliFtechiz @gouri-panda You confirm the situation does not have changed?

**Comment by gouri-panda** [comment]
@kelson42 Yes, it's possible now. Currently, we detect if the sd card mounted or not then our `StorageObserver` API detect all files from the sd card. We can add the external usb funcanality to our app. We detect if the external drive has mounted or not by receiving broadcast from system then we can search and add all the zim files to our library list same thing in vice versa if the external media has been removed. Here are helpful docs https://source.android.com/docs/core/storage/traditional#support_usb_media

**Comment by Ohm66** [comment]
Would be great to add the USB-functionality! 
I quess in future more will have the need to carry books on a memory stick, since 128GB main memory (most smartphones) are not enough for carrying when no SD card is there..
Thanks in advance Ralf

**Comment by kelson42** [comment]
@gouri-panda The link you have given explicitly says there is no direct access to USB storage since Android 6.0.

**Comment by kelson42** [comment]
@gouri-panda The link you have given explicitly says there is no direct access to USB storage since Android 6.0.

**Comment by Ohm66** [comment]
> @Ohm66 Can you use the + icon in the library section? This allows you to navigate external drives. Then you can open the zim files from there.
I cannot see any + Icon in Library section, I see just the online available files

**Comment by Ohm66** [comment]
I cannot see any "+ Icon" in Library section, I see just a remark: No Files available, add documents", and if I press this button, I get the online available files

![Screenshot_20230510_190752_Kiwix](https://github.com/kiwix/kiwix-android/assets/132337073/671583bb-0c77-456f-b6b3-834740ac5cb2)

**Comment by Ohm66** [comment]
I have newest version from Google Playstore, V3.4.4.
Is there a newer version as APK available? Where?

**Comment by gouri-panda** [comment]
Yes!, 3.6.0. https://github.com/kiwix/kiwix-android/releases/tag/3.6.0 . Let us know if you need any help.

**Comment by Ohm66** [comment]
Does not Work, I tried the APK Files.
Seems top bei a rights Problem. App says need permission to access memory. but only "Location"  and "devices nearby" are available permissions.
The Zim file is shown in + dialogue, but when I try to open, system says "Zim file not found"

**Comment by Ohm66** [comment]
The official Version  3.4.4. from Google Play Store hast the permission to access the memoroy, but the + dialog ist missing

**Comment by Ohm66** [comment]
Hi, thank you that you obviously fixed that problem. Is there a new version (3.7.0??) available?  on the link above under .../releases I could not find.
Thanks again for your great support!

**Comment by kelson42** [comment]
We work on the 3.7.0 release, but you can check with the nightly build http://download.kiwix.org/nightly/.

**Comment by blackle** [comment]
I just tried this on an Pixel 4a (android 13), with Kiwix 3.7.1, using an external usb drive connected to the phone.

I've enabled "Allow to read and write ZIM files on SD card"

I can use the + button to navigate to the external USB device, but when I tap on the zim file I have there it says "Error: The selected zim file could not be found"

The zim file works when I copy it to internal storage.

**Comment by MohitMaliFtechiz** [comment]
@blackle Can you please try with https://github.com/kiwix/kiwix-android/pull/3471, is now you able to open zim files via USB?

**Comment by Ohm66** [comment]
Hi there,
I just tested it, and IT works perfekt now using app V3.7.1 from general
repository

Thanks again for your good work!

Greetings from Bavaria
Ralf


Am 22. August 2023 15:55:59 schrieb MohitMaliFtechiz
***@***.***>:

**Comment by blackle** [comment]
Forgot about this! Nightly works for me too, thanks!

For anyone searching this in the future: make sure you enable SD card access in kiwix settings

**Comment by vb0** [comment]
Nightly isn't working for me with Pixel 7 and Android 14 (wasn't working on 13 either). Same symptoms as [described above](https://github.com/kiwix/kiwix-android/issues/3304#issuecomment-1620716801).

**Comment by kelson42** [comment]
@vb0 Thank you for your feedback, can you please open a new ticket with your details?

**Comment by Ohm66** [comment]
I have again the same problem. For me it was solved in August, using one of the nightly builds.
Now it did not work anymore from external USB-Stick, obviously an automatic process updated my app.
What happened? Can you please re-repair the apk-File?

I see the external file in Kiwix, but click on it says "file not found" (in German).
The allowance for Reading/Writing external card is set
