### ISSUE TITLE
Online content(Zim files) are removed if there is no internet connection

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3309]
**Describe the bug**
After the items are loaded, if we turn off the internet and refresh, whole items are removed, and `no items available` is displayed, It also happens if the user turns off the internet twice. Reported by @shashank-0-0 

**Expected behavior**
It should not remove the already loaded items, it should the snackbar of `no internet connection` which is the scenario of our application.

**Steps to reproduce the behavior:**
* Go to the `online library` fragment.
* Wait for the loading of the `zim files`.
* Turn off the internet and pull down to refresh the list.
* You will see the `no items available` text.

**Comment by kelson42** [comment]
@MohitMaliFtechiz We already had many tickets around that. Find a way please that this is the last one. It's not normal that we again and again open bugs for the very same feature.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I challenge the propose solution. Why should we display online books if you are not able to download them?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz I challenge the propose solution. Why should we display online books if you are not able to download them?

@kelson42 We are not introducing any new feature here, this is the already behavior of our application.
* Currently, we are using a deprecated method to check if the internet is available or not, then we are showing the no internet connection snack bar, when we are refershing the items. https://github.com/kiwix/kiwix-android/blob/ce423820f0b2aee20cdd69e064095ba4db24b4a2/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt#L338
* The current deprecated method always returns `false` that's why the already loaded zim files list is removed, but in the current behavior of our application, it should show the `no internet connection` snack bar. https://github.com/kiwix/kiwix-android/blob/ce423820f0b2aee20cdd69e064095ba4db24b4a2/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt#L138

**Comment by shashank-0-0** [comment]
> @MohitMaliFtechiz I challenge the propose solution. Why should we display online books if you are not able to download them?

It takes roughly 10 seconds to load the books ,i think it would not be ideal to remove them just because user switched off his internet twice.
Along with the deprecated method , i think we should check if there are items(books) already in the adapter https://github.com/kiwix/kiwix-android/blob/ce423820f0b2aee20cdd69e064095ba4db24b4a2/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt#L323
https://github.com/kiwix/kiwix-android/blob/ce423820f0b2aee20cdd69e064095ba4db24b4a2/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt#L324

**Comment by kelson42** [comment]
@MohitMaliFtechiz OK, once we use the API properly it will be faster and then this argument will fall off.

**Comment by shashank-0-0** [comment]
@kelson42 and also i was excited about making my second PR and fixed the issue ;( , can i submit my PR (WIP).

**Comment by MohitMaliFtechiz** [comment]
@shashank-0-0, would you be able to kindly test the latest PR and verify if it resolves the reported issue? Thanks for your bug report and suggestions. Any suggestion would be appreciated :)

**Comment by shashank-0-0** [comment]
@MohitMaliFtechiz I did and it fixes the important issue now :) . Another thing to notice is this  
https://github.com/kiwix/kiwix-android/blob/ce423820f0b2aee20cdd69e064095ba4db24b4a2/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt#L324
https://github.com/kiwix/kiwix-android/blob/ce423820f0b2aee20cdd69e064095ba4db24b4a2/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt#L325

After the items are loaded if we, turnoff internet -> turnon -> turn off we get empty items and that is set ,as a result whole items loaded are removed . But i guess it can be ignored or will a check be better?

**Comment by shashank-0-0** [comment]
@MohitMaliFtechiz ok got it, now it makes sense for me thanks
