### ISSUE TITLE
Disable language split for App Bundle in each APK

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3312]
We are already using this in our `kiwix-android` . We disable the language split so that the App Bundle does NOT split the APK for each language. We're gonna use the same APK for all languages.

**Comment by kelson42** [comment]
@gouri-panda This is a ticket which is phrased from the solution perspective. What is the problem and its concrete consequences?

**Comment by gouri-panda** [comment]
@kelson42 We have already discussed with this in #2704 . We are having the same problem with custom apps as well. https://github.com/kiwix/kiwix-android-custom/actions/runs/5023460704/jobs/9008077874#step:7:416
