### ISSUE TITLE
In the Hebrew Wikipedia, the labels and values in the infobox are aligned incorrectly

### ISSUE THREAD

**Issue by amire80** [kiwix/kiwix-android#3321]
To test, open the article אנה קארנינה in the Hebrew Wikipedia ZIM. Look at the infobox: The labels and the values are aligned to the left. They are supposed to be aligned to the right. The rest of the article works well in terms of RTL alignment.

**Screenshots**

![Screenshot_20230520_141521_Kiwix](https://github.com/kiwix/kiwix-android/assets/346271/de3767b7-78f2-403b-8327-583e573c5d46)

**Environment**
- Version of Kiwix Android : 3.4.5 build 7230405
- Device : Samsung Galaxy S20 FE
- OS version : 13

**Comment by MohitMaliFtechiz** [comment]
@amire80, @kelson42, I have debugged it and found that the zim file is missing style attributes to support right-to-left (RTL) content in tables.

For demonstration, I have added those attributes to the `<th>`, `<td>`,

```
<td style="
    direction: rtl;
    text-align: right;">
content here
</td>


<th style="
    direction: rtl;
    text-align: right;">
content here
</th>
```


After making these changes, the content now supports RTL.

![Screenshot from 2023-07-11 14-44-07](https://github.com/kiwix/kiwix-android/assets/34593983/cf1b22cc-e629-406f-bea4-e3fbe1cf0b12)

**Comment by kelson42** [comment]
This is a ticket for `openzim/mwoffliner`
