### ISSUE TITLE
Support and re-architecture custom app file in Android bundle

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3326]
Description:

Issue
We already support the bundle format in our `kiwix-android` but the real use cases or benefits will come if we complete the support bundle format in the custom apps as well. We don't currently add the expansion file in the correct way so we have problems in the GitHub actions when we try to upload the bundle format. We need to integrate expansion files for our Android app bundle to accommodate large assets that exceed the APK file size limit. This will ensure that users can download and install our app without any issues.

Expected Behavior
When users download and install the app from the Google Play Store, the expansion file should be automatically included and accessible by the app. This will enable us to deliver a seamless experience for users, even with large assets.

Steps to Reproduce

Attempt to download and install the app from the Google Play Store on a device with limited storage.
Verify if the app successfully downloads and installs, and if the expansion file is accessible by the app.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Can you please secure this bug is fixed in priority?

@kelson42 I am on it.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Shoukd we close in favour of #3355.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Yes, we should close this issue.
