### ISSUE TITLE
PHeT content in Russian please.

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#333]
A user recently gave the Chemistry and Physics simulations app 1 star as it doesn't include Russian. 
There seem to be around 50 of the HTML5 simulations available in Russian according to https://phet.colorado.edu/en/simulations/translated/ru so it'd be great to make these available for users who prefer Russian.

New review on Dec 17, 2017 at 10:18 AM GMT ★
_Что за бред, есть все языки кроме русского??!!!_

**Comment by kelson42** [comment]
This is to 90% a ZIM issue (if confirmed), should be moved to the phet scrapper git repo.

**Comment by kelson42** [comment]
This issue was moved to openzim/phet#38
