### ISSUE TITLE
```ProgressDialog``` is deprecated

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3336]
Parent Issue #3314

**Describe the bug**
 We are using `ProgressDialog` in `ZimHostFragment` while we are starting the kiwix hotspot. This method is now deprecated and the suggested replacement is to use `ProgressBar` or we can create a custom view for it and show it in the dialog.

**Logs**
'ProgressDialog' is deprecated. Deprecated in Java

**Comment by MohitMaliFtechiz** [comment]
Hi @gouri-panda @kelson42, since ProgressDialog is deprecated, we have two approaches to address this deprecation:

* According to the official documentation, it is recommended to use a progress bar, which will result in a complete change in the current UI.
* Alternatively, we can create a custom dialog and include a progress bar and a title, making it resemble the progress dialog.


What is your opinion on this? We should discuss before implementing the fix for this deprecation.

**Comment by MohitMaliFtechiz** [comment]
> Option 2 sounds good to me. Since we're using some custom dialogues on the various screen, we can get some advantages from it.

Thanks for the confirmation, I am also thinking the same for this option as it would not affect any UI.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I don’t understand the user visible added value of this progressbar? Can i have a screencast? No way to just get rid of it?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 We are using the ProgressDailog in the hotspot screen to notify the user that the server is starting. We can use dialog instead of ProgressDailog with the same UI as we have in ProgressDailog so it will not affect any user experience.


https://github.com/kiwix/kiwix-android/assets/34593983/3727c773-b3b2-453c-a82f-5a87b1f8cdf3

**Comment by kelson42** [comment]
OK, so its not a progressBar, it's a spinner. Proper naming again...

**Comment by kelson42** [comment]
@MohitMaliFtechiz Solution #2 seems better to me... and please rename to appropriate name!
