### ISSUE TITLE
Invasive "access photos and media" permission request at start

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3370]
![Screenshot_20230529-164227.png](https://github.com/kiwix/kiwix-android/assets/1029718/983c8aef-bed3-4cb5-8270-32b5cd69ebb6)

Just after installation of a custom app, I get this. AFAIK, this is only to allow a user to save a picture.

This is a valid use case, but we have no way to just allow to save (and not read pictures) and/or to ask just if someone tries to save a picture?

**Comment by gouri-panda** [comment]
Ok. We should ask permission when they need it. Not before the start.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Sorry to come back on this, but I’m not satisfied by the solution. Current solution needs many clicks, this is uselessly complicated. Please just display the same dialog box like here reported in this ticket, but at the time this is needed.

**Comment by MohitMaliFtechiz** [comment]
@kelson42, Okay.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have placed a fix for this in https://github.com/kiwix/kiwix-android/pull/3439
