### ISSUE TITLE
Fullscreen feature is broken

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3371]
I should not see such a bar at top
![Screenshot_20230529-164759.png](https://github.com/kiwix/kiwix-android/assets/1029718/d199b1a6-665c-4f9b-9d4a-e0cb95920017)

**Comment by MohitMaliFtechiz** [comment]
@kelson42, can you please provide the additional information, on which zim file you are facing this issue, I have tried with `3.6.0` and the top bar looks fine.

| Landscape mode  | Portairt mode |
| ------------- | ------------- |
| ![1685425867955](https://github.com/kiwix/kiwix-android/assets/34593983/96a2212f-e152-4b8d-baf2-9c0ff34b7c5c) | ![1685425568255](https://github.com/kiwix/kiwix-android/assets/34593983/432ed84b-1182-4035-8bad-071e143a72fb) |

**Comment by kelson42** [comment]
@MohitMaliFtechiz with latest tunisie app

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Thanks, I am able to reproduce the issue, I have placed a fix for it in https://github.com/kiwix/kiwix-android/pull/3372.
