### ISSUE TITLE
Option to Always Show Toolbar

### ISSUE THREAD

**Issue by E0697** [kiwix/kiwix-android#3398]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Please add an option to disable toolbar hiding on scrolling.

**Describe alternatives you've considered**

**Additional context**

**Comment by kelson42** [comment]
> Please add an option to disable toolbar hiding on scrolling.

Why? What is the problem you face with auto hidfing?

**Comment by E0697** [comment]
Not exactly a problem, just not a fan of it.
I can live with it if it requires a lot of work tho.

**Comment by kelson42** [comment]
@MohitMaliDeveloper @gouri-panda What do you think about the pertinence of this feature request?

**Comment by gouri-panda** [comment]
>Please add an option to disable toolbar hiding on scrolling.
 @kelson42 @E0697 Why do we want this? What's the particular use case for this? In terms of adding the feature, it's pretty simple forward to do this.

**Comment by E0697** [comment]
> >Please add an option to disable toolbar hiding on scrolling.
> 
>  @kelson42 @E0697 Why do we want this? What's the particular use case for this? It's a common Android UX pattern to hide the scrollbar when the user scrolls. In terms of adding the feature, it's pretty simple forward to do this.
> 

It's just a matter of preference. I understand 👍
