### ISSUE TITLE
not durable when relocated to external drive

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#34]
_From @Thetoxicarcade on March 14, 2017 4:15_

I tried moving kiwix to a removable drive.

Kiwix essentially bricks itself when trying to list repos afterwards.

It's possible I'm just stupid, but if we could explain this process better, that would make working with an external (portable) kiwix installation dir a much better process.

Maybe the answer is better explanations, maybe the solution is a "migrate" function (for library data, or for the entire .kiwix folder), maybe the solution is a heal-button that resets all the woes, instead of me redownloading a clean install instead of my bricked one.

Ideas?

_Copied from original issue: kiwix/kiwix#473_

**Comment by kelson42** [comment]
@Thetoxicarcade That should work, can you please give us the step-by-step procedure to reproduce the problem? I suspect you use Linux? Can you explain what means exactly "bricks itself"?

**Comment by Thetoxicarcade** [comment]
Why did we move it here??

**Comment by kelson42** [comment]
Indeed, this is not an Android issue.
