### ISSUE TITLE
`KiwixTextToSpeech` uses some deprecated methods

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3405]
**Describe the bug**
`KiwixTextToSpeech` using some deprecated methods.
* `AudioManager.abandonAudioFocus(onAudioFocusChangeListener)` is deprecated now.
* `tts.speak` method is now deprecated.

**Expected behavior**
We should repace these methods with updated API's.

**Logs**
```
'speak(String!, Int, HashMap<String!, String!>!): Int' is deprecated. Deprecated in Java
'abandonAudioFocus(AudioManager.OnAudioFocusChangeListener!): Int' is deprecated. Deprecated in Java
```

**Comment by avidseeker** [comment]
I get spammed with these notifications:
> Initialization of Text to Speech failed. Please Try again.

They might be related to this issue.

**Comment by kelson42** [comment]
@avidseeker No, its not IMO. Please test with version 3.7, in beta on play store or downloadable at http://download.kiwix.org/release/kiwix-android/ and if you still have problems, please open a new ticket.
