### ISSUE TITLE
No filepicker anymore in local library

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3406]
![Screenshot_20230609-065904.png](https://github.com/kiwix/kiwix-android/assets/1029718/badd79c9-5cc0-4ba1-bcbc-625c1c6a9f24)

It's impossible to manually load a ZIM file downloaded with the web browser.

With Android 10.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Where/when this feature introduced mid 2022 has been removed?

**Comment by MohitMaliFtechiz** [comment]
@kelson42, This feature is not removed, We only hiding this feature in play store build on android 11 and above. I have tried with android 10 device and the file picker is showing.
Are you using the play store variant?
Are you using android 11 and above?


https://github.com/kiwix/kiwix-android/blob/0d631d9d8f8d28000ea4c0ad35c88d03e6941174/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt#LL242C39-L242C39

```
 private fun hideFilePickerButton() {
    if (sharedPreferenceUtil.isPlayStoreBuild) {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
        fragmentDestinationLibraryBinding?.selectFile?.visibility = View.GONE
      }
    }

    fragmentDestinationLibraryBinding?.selectFile?.setOnClickListener {
      showFileChooser()
    }
  }
  ```

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please:
* update the readme for users explaining what is possible and not for end-usets, based on version and android versions
* in the contributing file, please write the rationals behind current situation.

I use version 3.7.1 of playstore on anfroid 10.

**Comment by MohitMaliFtechiz** [comment]
> update the readme for users explaining what is possible and not for end-usets, based on version and android versions
in the contributing file, please write the rationals behind current situation.

Okay.

> I use version 3.7.1 of playstore on anfroid 10.

Thanks I am testing it on another android 10 device to reproduce the scenario.

> How is that possible, on android 11, that Signal app, via its + button can insert a ZIM file downloaded with Fitefox... and kiwix can not?!

I remember we have discussed this topic, `Signal app` is a messaging app AFAIK it uses the `Storage Access Framework` as we are using via clicking on the + button, but after that `Signal app` makes a temp file from the picked `URI` (as messaging apps set a limit to send files) and after sending the file they delete the temp file, but for `kiwix` we can not use this approach as the zim files can be bigger so making temp file is not a good idea.

**Comment by kelson42** [comment]
@MohitMaliFtechiz To avoid further discussions, this is why i have asked to document properly, both from a user perspective and from a technical perspective what is the status.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 ,
* I have updated the readme file.

> Thanks I am testing it on another android 10 device to reproduce the scenario.
* I have checked this with the play store variant of 3.7.1 within the emulator and real device too, but I am unable to reproduce the error, the + icon is visible there.

![Screenshot from 2023-06-13 16-21-46](https://github.com/kiwix/kiwix-android/assets/34593983/e18ba386-91ac-4331-b3fb-81795191f51c)

**Comment by Jaifroid** [comment]
@MohitMaliFtechiz As @danielzgtg showed in #3265#issuecomment-1468077804, it is possible to pick files without copying them, but the app would need to be modified to accept URIs instead of FILE references, which is a big piece of work, it seems. Obviously not feasible for upcoming release, but in my view it's really important to have a file picker in the Play Store version of the app. Many average users will simply move on if asked to install apps from other sources. I completely understand that this is a complex issue, and is something to look at after upcoming releases.
