### ISSUE TITLE
Text to Speech init failed

### ISSUE THREAD

**Issue by avidseeker** [kiwix/kiwix-android#3408]
**Describe the bug**
Upon opening the app, this message shows: 
> Initialization of Text to Speech failed. Please Try again.

It repeats whenever returning back to main menu.

---
Kiwix: v3.7.1

**Comment by kelson42** [comment]
@avidseeker We will have a look next week. In the meantime can you please share:
* your version of android
* is that related to a specific content?

**Comment by avidseeker** [comment]
* Android 13.
* No. I can browse fine, but whenever I go back to main menu (e.g: from search), I get the message again.

I don't have any text-to-speech service installed. Kiwix seems to look for one and expects it to be there. Not sure this is the job of Kiwix anyways. This should be handled by keyboard or the text-to-speech service.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz It may be the internet problem. What do you think? @avidseeker you can give us the logs that would help us to diagnose. 
Steps:-
1. Reproduce the event
2. Go to the help section(Under left menu bar)
3. Click the Send diagnostic report

That will generate the log file. Then you can upload it here. Thanks!

**Comment by kelson42** [comment]
@MohitMaliFtechiz @gouri-panda Why do we need to do that often for tts, although the user does no use at all the feature.

**Comment by avidseeker** [comment]
```
...
06-10 05:22:17.693 24626 24626 D kiwix   : Initializing TextToSpeech
06-10 05:22:17.704 24626 24764 D libEGL  : loaded /vendor/lib64/egl/libGLES_mali.so
06-10 05:22:17.704 24626 24691 W cr_media: BLUETOOTH_CONNECT permission is missing.
06-10 05:22:17.705 24626 24691 W cr_media: registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission
06-10 05:22:17.705 24626 24626 D kiwix   : actionandroid.intent.action.MAIN
...
06-10 05:22:39.878 24626 24626 W TextToSpeech: shutdown failed: not bound to TTS engine
06-10 05:22:39.899 24626 24626 E RecyclerView: No adapter attached; skipping layout
06-10 05:23:07.939 24626 24626 D KIWIX   : Writing all logs into [/data/user/0/org.kiwix.kiwixmobile/files/logs]
...
```

**Comment by kelson42** [comment]
@MohitMaliFtechiz Any feedback, this sounds a very impairing issue!

**Comment by MohitMaliFtechiz** [comment]
> Initialization of Text to Speech failed. Please Try again.

This error comes when `TTS` is unable to initialize in our application. https://github.com/kiwix/kiwix-android/blob/1148c04ae689f914ff6ad83fde527be5f4b564c7/core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt#L70


> 06-10 05:22:39.878 24626 24626 W TextToSpeech: shutdown failed: not bound to TTS engine

@kelson42, I have researched about this error and discovered that on Android 11 and above, we need to include the following code snippet in our manifest file to properly use the TTS service on our devices:

```
<queries>
  <intent>
      <action android:name="android.intent.action.TTS_SERVICE" />
  </intent>
 </queries>
 ```

This information is also mentioned in the  [Offical docs](https://developer.android.com/reference/android/speech/tts/TextToSpeech).
Furthermore, during my investigation, I found a similar issue reported by a user facing the same problem on `MIUI 13.0.4 (Android 12)`. The user resolved the error by declaring the `TTS_SERVICE` in the manifest https://gitlab.com/axet/android-hourly-reminder/-/issues/57

**Comment by kelson42** [comment]
@avidseeker Thank you very much for your bug report. This will be fixed not in the next days and ship with the next `3.8.0` release (still not relase date). If you face other oddities/bugs, please continue to report them.
