### ISSUE TITLE
Create CI check to identify usage of deprecated classes or methods

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3409]
**Issue Description:**

**Background:**
As our codebase evolves, it is important to ensure that we maintain code quality and prevent the usage of deprecated classes or methods. Deprecated code can lead to compatibility issues, reduced performance, and potential bugs. To address this concern, we need to implement a Continuous Integration (CI) check that identifies any usage of deprecated classes or methods in our codebase.

**Expected Behavior:**
When changes are made to the codebase, the CI system should analyze the modified code and flag any usage of deprecated classes or methods. This will help developers identify and update deprecated code, ensuring that our codebase stays up-to-date and avoids potential issues.

**Steps to Reproduce:**

1. Implement a CI check script or plugin that analyzes the codebase for deprecated code usage.
2. Configure the CI system to execute the script or plugin whenever a code change is pushed to the repository.
3. Ensure that the script or plugin scans all relevant code files (e.g., Kotlin, java) for deprecated code patterns.
4. When deprecated code is detected, the CI system should generate a report or provide a clear indication of the affected files, classes, and methods.

**Acceptance Criteria:**

* The CI check script or plugin is implemented and integrated into the CI system.
* The CI system analyzes the codebase for deprecated code whenever changes are pushed.
* The script or plugin scans all relevant code files for deprecated code patterns.
* The CI system provides a clear report indicating the affected files, classes, and methods using deprecated code.
* Developers are able to quickly identify and address any usage of deprecated code based on the CI check results.

**Additional Considerations:**

* It may be helpful to provide guidelines or documentation on how to update deprecated code to non-deprecated alternatives.
* The CI check should be efficient and not significantly impact the build or test execution time.

**Comment by kelson42** [comment]
Actually i just want to have the ci red if deprecated api is used.
