### ISSUE TITLE
Slight margin appears when switching between tabs

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3412]
From a user:

I'm currently using a Samsung Galaxy Fold 4 and a Samsung Galaxy Tab S8 Ultra and the bug happens on both devices using the latest version of Kiwix (3.4.4). When moving between tabs, the library navigator bar (on the reader tab) has a bottom margin separated from the top navigation bar.

https://github.com/kiwix/kiwix-android/assets/21675885/baed03d2-1f27-41f3-92cc-e23d988cc427

**Comment by kelson42** [comment]
This has been fixed, please try with 3.7.
