### ISSUE TITLE
Unable to open the support link with default browser

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3426]
![Screenshot_20230615-162829.png](https://github.com/kiwix/kiwix-android/assets/1029718/7046fc8b-c45e-48eb-8b6b-907020308a88)

Same behaviour if I click on an external link in an article.

But Firefox is installed as default browser!

**Comment by kelson42** [comment]
@MohitMaliFtechiz any news here?

**Comment by MohitMaliFtechiz** [comment]
Hi @kelson42, I have tried to reproduce the bug on several devices, including real devices running Android 11 and Android 12, and it is working fine. It also works fine on emulators with both the default browsers and Firefox.

However, when I manually disable the browser or when there is no browser installed on the device. In these cases, the above message appears.

Could you please provide me with the following additional information?
1) Which Android version are you using?
2) Is Firefox disabled?
3) Have you tried using a different device?

**Comment by kelson42** [comment]
I will have a look again.

**Comment by wbillan** [comment]
When I click on a link in the Kiwix's Wikivoyage app, version 2023-06, which I'm assuming is using much of the same code, the link does not open and rather a message shows up briefly on the screen of "Could not find an installed application for this type of file."  This is with a Samsung A51 on Android 13.  I can confirm that there is a default browser set.  Setting a different default browser has no effect.  Other apps open my default browser when I click on a link without issue.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz OK, so now we are two users... there really something wrong somewhere.


@kelson42 You are right, Let me deeply debug this problem.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have found the actual problem with default phone apps, I have placed a fix in #3504. @kelson42, @wbillan can you please test with #3504, and let me know if this issue still exists at your end?
