### ISSUE TITLE
Snackbar buttons are too small

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3434]
Reported by Android Play Store Pre-launch test: Snackbar buttons are too small - all of them - which arms the overall app usability
![image](https://github.com/kiwix/kiwix-android/assets/1029718/addaa7d0-5257-43f5-a3d0-99837dcb41fb)

Here are the rationals behind https://support.google.com/accessibility/android/answer/7101858?hl=en

The sensitive zone seems too small but actually the logo are quite small themselves.

Both of them should be bigger to satisfy Pre-launch test, but without increasing the snackbar height.

**Comment by CYBWEBALI** [comment]
I can fix this issue assign it to me.

**Comment by CYBWEBALI** [comment]
Done PR #3435 .
