### ISSUE TITLE
Zim file does not download / pending forever

### ISSUE THREAD

**Issue by shashank-0-0** [kiwix/kiwix-android#3441]
**Describe the bug**

zim files does not download again after cancelling the download from the notification  and is pending forever.

**Expected behavior**

If the user cancels the download from the notification and wants to download the same file again it should download again.

**Steps to reproduce the behavior:**
1. start downloading any zim file
2. cancel the download from the notification
3. start downloading the same file again
4. The download is pending and never downloads 

**ScreenRecording**

https://github.com/kiwix/kiwix-android/assets/111702455/35d3af0b-c475-4092-880c-0a05c4a22b14

**Environment Tested**
- Version of Kiwix Android : 3.7.1 Develop version
- Device : Real me 3i (Physical Device) , Pixel 5 Api 33 (Emulator)
- OS version : Android 10 , Android 13

**Comment by shashank-0-0** [comment]
@MohitMaliFtechiz  @gouri-panda 

**Cause** :

I looked in to it and here is what i found
fetch.cancel() = cancels a download but fetch keeps it in memory so that if user downloads again it could continue from where it left of.
fetch.delete()= delete's the downloading instance
we are cancelling a download when the user presses cancel instead of deleting , Fetch library  keeps the cancelled downloaded instance in the memory so that it could continue downloading from where it left off. 

Ideally if we enqueue / download the same file again it should start downloading but the problem is that there are multiple urls to download the same file again  as a result a different fetch download ID is generated though we are attempting to download the same file , hence cancel does not work.

**Possible Solution** :

We can delete the download instance instead of cancel when the user presses cancel in the notification and that would make sure the file is deleted and can be downloaded again.
https://github.com/kiwix/kiwix-android/blob/b00c3ecc9e42f814966ff77d2f95f160900fcd07/core/src/main/java/org/kiwix/kiwixmobile/core/downloader/fetch/FetchDownloadNotificationManager.kt#L104
@kelson42 I am excited to make my 4th contribution ,assign it to me :)

**Comment by gouri-panda** [comment]
@shashank-0-0   Thanks for the report! We can  find another solution with out deleting the old existing file. I think it was intentional to keep the old file to minimize the bandwidth of the user to download the content.
