### ISSUE TITLE
Search feature does not work with Ask Ubuntu (2023-05-08)

### ISSUE THREAD

**Issue by texophen** [kiwix/kiwix-android#3452]
I installed Kiwix (Android), downloaded Ask Ubuntu (2023-05-08) book.

I opened Ask Ubuntu book on Kiwix, search with 'free disk' keyword.

On the list of of results, I clicked on 'Missing free disk space' item. Home page was displayed instead of the article.

I checked with many keywords and search results but same things happen.

**Comment by kelson42** [comment]
@texophen which version of kiwix do you use?

**Comment by texophen** [comment]
I use Kiwix 3.4.5 (Build 7230405). 

My phone is LG L455DL (Android 9).

**Comment by kelson42** [comment]
@texophen This is basically the same bug report like #3410. Therefore I will close it and keep #3410 open. We are working right now to fix it.
