### ISSUE TITLE
Can't open EPUB from Project Gutenberg in external app

### ISSUE THREAD

**Issue by dnut** [kiwix/kiwix-android#3453]
This reopens the issue from #2517. I see the same exact behavior. Either there was a regression, or this was never fixed. I have not tested PDFs because I don't see any PDFs in project gutenberg, only EPUBs, so this issue is only for EPUB.

#2517 was supposedly fixed by #2825. But that pr says it only fixes PDF, and says nothing about EPUB. So I'm guessing 2517 was never actually fixed, and was closed by mistake.

I don't see why the file type even matters. It should just write the file into the Download folder. Nonetheless, I have no problem opening EPUB files from other apps, like a file manager; they always open in my ebook reader (ReadEra) without issue.

**Environment**
- Version of Kiwix Android : 3.7.1
- Device : SM-N976U
- OS version : Android 11

**Comment by kelson42** [comment]
@dnut Thank you for your bug report, we will look soon to fix this.
@MohitMaliFtechiz we need a generic approach here, we can not habdle mime-type by mime-type.

**Comment by MohitMaliFtechiz** [comment]
@dnut, @kelson42 

I confirm this bug now exists in all the epub files (Tested in Android 12 Redmi Note 9). It appears that the issue was initially fixed in the https://github.com/kiwix/kiwix-android/issues/2517. However, the problem resurfaced when we removed the `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />` permission to comply with the Play Store policy in https://github.com/kiwix/kiwix-android/issues/3361.

The reason behind this issue is that `intent.resolveActivity(activity.packageManager)` returns null without the `QUERY_ALL_PACKAGES` permission. This is because the application doesn't have permission to access other packages on the Android device. As a result, a toast message is displayed while opening the EPUB files, while the PDF files work without any issue.

https://github.com/kiwix/kiwix-android/assets/34593983/f56d4822-5ed4-41f4-b3a6-69df42b92794

**Comment by MohitMaliFtechiz** [comment]
@dnut, @kelson42 I have placed a fix for this issue in https://github.com/kiwix/kiwix-android/pull/3455. @dnut if possible can you please try with #3455, we are glad to have your feedback on this.

**Comment by MohitMaliFtechiz** [comment]
> Does the github workflow produce an apk file? 

@dnut yes, GitHub nightly workflow produces the apk. But for this fix, there is no apk available yet. But I have shared an apk with you on `dnut@*************.github.com` please check your mail.

**Comment by dnut** [comment]
I'm unable to install the apk. 

https://github.com/kiwix/kiwix-android/assets/15116250/e0edf568-59bd-48ce-9a86-13e2f5d7537d

**Comment by MohitMaliFtechiz** [comment]
@dnut, Have you uninstalled the previous apk from the device? This problem occurs when there is already installed an apk with the same package name in the device.

**Comment by kelson42** [comment]
> I get the \"Entering External Link!\" popup, warning me that I'm about to open a link to \"content://org.kiwix...\", which is a little weird, but not a problem.

@MohitMaliFtechiz This should not happen.

**Comment by MohitMaliFtechiz** [comment]
@dnut, Thanks for the feedback.

> But I wonder how general this is. What if it's a different file type, or I don't have an app installed that can open it? It would be nice if kiwix could write the file to the downloads folder on the device regardless of the file type or the apps on my system. 

In the Kiwix app, content is downloaded to the "Download" folder before attempting to open the file with an external reader. Regardless of the file type (e.g., epub or pdf), the app first downloads the file and then tries to open it in an external app, if such an app is available to read the file.

> @MohitMaliFtechiz This should not happen.

@kelson42, We have the functionality to show an external link in a popup if the user tries to open any URL in an external application. The user can copy that link. However, I agree with you and @dnut that it is unnecessary to show the epub and pdf URIs in the popup, as they are not URLs. If the user copies and pastes these links into an external browser, they will not open. Hence, displaying these links in the popup for epub and pdf files is not ideal.

Both pdf and epub URIs start with the "content://" prefix, so it is easy to hide this from the user.

![pdfUrl](https://github.com/kiwix/kiwix-android/assets/34593983/03d5ebbd-8b22-45a9-b18f-254be1f18331)
![epubUrl](https://github.com/kiwix/kiwix-android/assets/34593983/10d52e00-1b54-4a6f-9542-1468ee2ad7b2)

**Comment by MohitMaliFtechiz** [comment]
@kelson42, I have placed a fix for this in https://github.com/kiwix/kiwix-android/pull/3455 also updated the PR description with relative screenshots.

**Comment by kelson42** [comment]
I don’t want any specific behaviour for epub, pdf or whatever. Either the mime-type can be handled by kiwix or can not and the can be delegated to a third party app. I’m sure this is something I already have written clearly. Please make a PR dedicated to this wrong decoding problem around semi-colon first (with all the necessary unit testing).

**Comment by MohitMaliFtechiz** [comment]
> I’m sure this is something I already have written clearly. 

@kelson42 I was following your previous [comments](https://github.com/kiwix/kiwix-android/issues/3455#issuecomment-1643567981)  of https://github.com/kiwix/kiwix-android/pull/3455 in https://github.com/kiwix/kiwix-android/pull/3738. Where we are showing the download and open options to the user, and this looks more related to this feature.

> PDF/EPUB in a ZIM are not external links... https://github.com/kiwix/kiwix-android/pull/3455#discussion_r1359373948
Or this is an internal link and you pass to kiwix to open and then kiwix decides based on the mime-type stored in the ZIM to open itself or to pass to the OS to open via a third party app https://github.com/kiwix/kiwix-android/pull/3455#discussion_r1359374794

Here you are right we are handling the PDF/Epub in our reader, we are now only showing the `Download/Open` dialog when it is a redirect entry(not handled by the Kiwix means dedicated to the OS) else it is handling by the kiwix reader like shown in the below video. Before it was showing the "Entering External Url" dialog with `content://..../..` and we .


https://github.com/kiwix/kiwix-android/assets/34593983/1ebdb23d-bf98-43e5-b205-5a47a34e6835

**Comment by kelson42** [comment]
@MohitMaliFtechiz Your code might do have the right behaviour from a user perspective, but this is not [what I said](https://github.com/kiwix/kiwix-android/issues/3453#issuecomment-2002336496). I don't want to to see any code which is epub or pdf specific except if there is a really good reason.
