### ISSUE TITLE
Use Lucene 7.3.0 for search feature in Kiwix

### ISSUE THREAD

**Issue by texophen** [kiwix/kiwix-android#3454]
Currently, Kiwix only search for article title. By using Lucene 7.3.0, Kiwix can search in article body like search engines (google, bing).

I successfully modified Lucene 7.3.0 for using in Android: https://github.com/texophen/lucene-android 

The modification includes:
+ Add log feature in org.apache.lucene.LucenePackage
+ Add org.apache.lucene.util.ADClassValue to replace java.lang.ClassValue in JDK 8 (but not available in Android)
+ Modify org.apache.lucene.util.AttributeFactory
```
  static final MethodHandle findAttributeImplCtor(Class<? extends AttributeImpl> clazz) {
    try {
      //org.apache.lucene.LucenePackage.writeLog("AttributeFactory.findAttributeImplCtor() - 1: " + lookup.findConstructor(clazz, NO_ARG_CTOR).toString());
      MethodHandle mh = null;
      if (lookup.findConstructor(clazz, NO_ARG_CTOR).toString().endsWith("PackedTokenAttributeImpl")) {
        mh = lookup.findConstructor(clazz, NO_ARG_CTOR).asType(MethodType.methodType(org.apache.lucene.analysis.tokenattributes.PackedTokenAttributeImpl.class));
      } else {
        mh = lookup.findConstructor(clazz, NO_ARG_CTOR).asType(NO_ARG_RETURNING_ATTRIBUTEIMPL);
      }
      //org.apache.lucene.LucenePackage.writeLog("AttributeFactory.findAttributeImplCtor() - 2: " + mh.toString());
      return mh;
    } catch (NoSuchMethodException | IllegalAccessException e) {
      throw new IllegalArgumentException("Cannot lookup accessible no-arg constructor for: " + clazz.getName(), e);
    }
  }
```
(I just test with my Android app. If your app does not work, you can add your type to above method and it can work)

**Comment by kelson42** [comment]
We use Xapian which does the job. It ia just not available on Kiwix for Android. See #1324
