### ISSUE TITLE
App versions on F-Droid and Google Play Store are out of date

### ISSUE THREAD

**Issue by AxelBoldt** [kiwix/kiwix-android#3460]
Both F-Droid and the Google Play Store have version 3.4.5 of the Kiwix app. Unfortunately, that version has a (for me) fatal bug (#2592) which has been fixed in newer versions. After downloading version 3.7.1 from kiwix.org, my issues were solved. Please update the app store versions.

**Comment by kelson42** [comment]
@AxelBoldt Bot app store will benefit of 3.8.0. In the meantime you can install the apk from download.kiwix.org/releases

**Comment by Ryonez** [comment]
@kelson42 
The last 2 releases, 3.7.0 and 3.7.1 only have source code, there are no builds on them.

**Comment by djoris** [comment]
For whoever stumbles upon this as I did: 
The [IzzyOnDroid repository for F-droid](https://apt.izzysoft.de/fdroid/) offers 3.6.0 currently https://apt.izzysoft.de/fdroid/index/apk/org.kiwix.kiwixmobile
