### ISSUE TITLE
It would be nice if kiwix would open zim files from USB-OTG

### ISSUE THREAD

**Issue by ottischwenk** [kiwix/kiwix-android#3462]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jaifroid** [comment]
@ottischwenk Currently the Play Store variant of the Android app cannot access archives outside of its own download directory. There are two possible solutions:

* Get the `Direct APK` (app package) version from the Kiwix web site here: https://kiwix.org/en/applications/. You will need to sideload this. See if that can open OTG files;
* Try with the PWA which can open OTG USB storage (I have done this myself) so long as you pick the correct file provider when opening the ZIM. To try the PWA, go to: https://pwa.kiwix.org in Chrome or Samsung Internet (if you have that, it's a bit faster with File Access) on your phone. Wait a few seconds (up to 30) for an Install button to appear in Configuration. Click Install. Then try picking the file -- you might need to provide more than one file provider.

Either way, file access over USB will be slow, so be patient when loading and searching for articles!

**Comment by kelson42** [comment]
AFAIK there is no technical way to access directly the filesustem via OTG.

@MohitMaliFtechiz Please confirm and put a section on the README.md explaining why we don't do so.

**Comment by MohitMaliFtechiz** [comment]
@kelson42, I have researched and tried many ways to do it on Android 11 and above devices and I got success to use `USB-OTG` on these devices I have made changes in https://github.com/kiwix/kiwix-android/pull/3471.

@ottischwenk Can you please try with #3471 ?
