### ISSUE TITLE
Video viewer should allow change of reading speed

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3465]
Many players allows their users to modify the video reading speed, either more slowly to ease comprehension or faster for speed-viewing (e.g. 0.75x - 1.25x)

**Comment by kelson42** [comment]
@Popolechien This is control in the zim, not in the reader.

**Comment by Popolechien** [comment]
@kelson42 Should I move this to [openzim/youtube](../../../openzim/youtube) or to another repo, ie [libzim](../../../openzim/libzim)?

**Comment by kelson42** [comment]
Yes, youtube repo. is not bad.

**Comment by Popolechien** [comment]
Done as [youtube/issues/174](../../../openzim/youtube/issues/174)
