### ISSUE TITLE
Text cleared repeatedly in search

### ISSUE THREAD

**Issue by limisk** [kiwix/kiwix-android#3468]
**Describe the bug**
Sometimes when searching, the keyboard keeps repeatedly disappearing and reappearing, clearing the input. This doesn't happen predictably, but mostly occurs when a page is loading when you open search.  The jittering stops eventually. The ZIM file I use is very large, so search is fairly slow in general.

Video: https://github.com/kiwix/kiwix-android/assets/117564699/54e1c54c-1849-4a0e-95be-fa6f193e6734

**Steps to reproduce the behavior:**
One way to get this to happen frequently is to click a link and then quickly click search.

**Environment**
- Kiwix version: 3.7.1 (from GitHub)
- ZIM file: wikipedia_en_all_maxi_2023-05.zim (stored on internal storage)
- Android version: 13 (LineageOS running on a OnePlus 8)

Thank you all for your work, Kiwix is really valuable!

**Comment by MohitMaliFtechiz** [comment]
@limisk We have placed a fix for this, can you please try with https://github.com/kiwix/kiwix-android/pull/3469 is this issue still exist at your end.
