### ISSUE TITLE
"Get Content" window: getting stuck on ru.wikipedia and other items

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#347]
_From @aleksejrs on December 7, 2017 15:47_

Sometimes I open Russian Wikipedia or some other zim, and then cannot open a different zim: the zim currently open loads every time for many attempts.  Kiwix 2.2 on Android.  I usually have no problem with the middle of the screen, but have had this one with Kiwix since the beginning (one to one-and-half years).

_Copied from original issue: kiwix/overview#1_

**Comment by kelson42** [comment]
No clue what is going one here. @mhutti1 any idea?
Maybe you could try to see if the problem still appear in this (still unpublished) version of Kiwix for Android https://download.kiwix.org/bin/android/2.3/

**Comment by kelson42** [comment]
_From @aleksejrs on December 8, 2017 13:53_

I can't install it (the installation process ends with "App was not installed").  It seems that my smartphone has an ARMv7 processor.

**Comment by kelson42** [comment]
@aleksejrs Have you tried with both kiwix-2.3_armeabi.apk and kiwix-2.3_arm64-v8a.apk ?

**Comment by kelson42** [comment]
_From @aleksejrs on December 8, 2017 20:26_

Yes, both.

**Comment by aleksejrs** [comment]
I found later that pressing near the bottom of the entry worked much better.

**Comment by kelson42** [comment]
We should try again with recently release version 2.4.

**Comment by aleksejrs** [comment]
Even later, "pressing near the bottom of the entry" stopped helping. Could have depended on the screen orientation though.

**Comment by kelson42** [comment]
@aleksejrs @run-dey Would be good to know if this still happen with 2.5.

**Comment by kelson42** [comment]
We don't have experienced this problem since more than a year. I will assume the bug has been fixed meanwhile.
