### ISSUE TITLE
Accessibility – hyperlinks are invisible 

### ISSUE THREAD

**Issue by Paol-M** [kiwix/kiwix-android#3482]
Hyperlinks are indistinguishable from other text for completely colorblind individuals or those who use grayscale mode on their phone.

**Comment by Shkzeen** [comment]
Or sleep mode really, making it even more important.
I'd suggest maybe underline, italicize, or bolden links.

**Comment by Paol-M** [comment]
The issue is in Wikipedia, Wiktionary, and probably many other ZIMs.

**Comment by kelson42** [comment]
@Paol-M But the link are exactly like on the online version!? So you have the same problem with en.wikipedia.org for example?

**Comment by Paol-M** [comment]
No, I don't have the same problem. On the online version, links appear as a slightly different shade of black, and, in the setting, I have the option to enable an option to underline links. In the Kiwix app for Android, links and non-links are indistinguishable in both dark and light mode.

**Comment by kelson42** [comment]
Moving to `openzim/mwoffliner

**Comment by kelson42** [comment]
Kamino closed and cloned this issue to [openzim/mwoffliner](https://github.com/openzim/mwoffliner/issues/1994)
