### ISSUE TITLE
Search result order is confusing when there are exact and inexact matches. 

### ISSUE THREAD

**Issue by maksbotan** [kiwix/kiwix-android#3486]
**Describe the bug**
I'm using Kiwix to look up words in Wiktionary. It's common for Wiktionary to contain an entry for an exact word, and other entries containing that word as a substring. When I search for such a word, exact match is not the first in the result list and often is hard to find. 

**Expected behavior**
I'd expect to have exact match on the top of the search result, with other matches below it. Or more general, to have shorter (relative to the query) matches closer to the top. 

**Steps to reproduce the behavior:**
1. Download "English Wiktionary text only" zim, I have 2023.07.27 version at the time of reporting 
2. Search for a short word, for example "shame" 
3. Observe that the required word is far from the top of the list

**Screenshots**

![Screenshot_20230920_194352_Kiwix](https://github.com/kiwix/kiwix-android/assets/275614/611624bb-243b-4808-a6c3-85cdb8965fdb)

**Environment**
- Version of Kiwix Android : 3.4.5 build 7230405 from Google play 
- Device : Samsung Galaxy S22+
- OS version : Android 13

**Logs**

**Comment by kelson42** [comment]
This has to be tested again with future 3.8.0 version, but at the end if something has to be done, it won't be in kiwix-android but somewhere else.

**Comment by maksbotan** [comment]
Thanks for the response! Is there a way to test future version without building from source? Maybe you have some prerelease builds?

If not kiwix-android, what be a correct place to report bug? Do you use some shared search engine across all clients?

**Comment by kelson42** [comment]
@maksbotan yes we do have nightlies http://download.kiwix.org/nightly/

**Comment by maksbotan** [comment]
I've installed 2023-09-27 apk from your link and it looks like search order is better now!

![Screenshot_20230927_114717_Kiwix](https://github.com/kiwix/kiwix-android/assets/275614/6468db78-747a-4764-a545-cbb6e3ac7379)

**Comment by kelson42** [comment]
Great to read this :) This version 3.8 is almost ready to release. Please report further any problem you might have with it.
