### ISSUE TITLE
Offline translation

### ISSUE THREAD

**Issue by PixelQubits** [kiwix/kiwix-android#3490]
A legal feature would add translation to articles from other languages offline, for example using https://www.argosopentech.com/

**Comment by kelson42** [comment]
I don’t understand the feature request. Please detail the use case.

**Comment by PixelQubits** [comment]
A function that translates articles like a browser, when the user accesses a website and asks if they want to translate the page.

**Comment by kelson42** [comment]
@PixelQubits This is clearly out of the scope of Kiwix. But do you have any example of third party software providing such a feature? Maybe we could check if in integrates properly?

**Comment by PixelQubits** [comment]
https://www.argosopentech.com/

**Comment by kelson42** [comment]
This is a software library, not a ready to use software for wnd-user. Closing as there basically nothing here we will do.
