### ISSUE TITLE
gen-custom-android-build.py should provide a solution to override info.json

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#35]
_From @kelson42 on December 30, 2016 20:17_

gen-custom-android-build.py is the script used to create custom apps, ie. apps which include a unique content (ZIM file) and are rebranded.

The custom apps properties are stored in a json file like custom/wikimedpt/info.json for example. We need a solution to be able to call gen-custom-android-build.py with a info json file and overrides json files properties on the fly.

Here is how it should work:
`./gen-custom-android-build.py custom/wikimedpt/info.json --override-version_code=42 `

should overwrite the "version_code" in the info.json file. This should work for all the possible values in the json file (--override-version_name, --override-enforced_lang, ...)

_Copied from original issue: kiwix/kiwix#409_

**Comment by kelson42** [comment]
_From @EladKeyshawn on December 31, 2016 1:7_

@kelson42 tell me if this what you required

**Comment by kelson42** [comment]
@EladKeyshawn Thx, works for me. Before closing this ticket, I think it would be even better to check the arguments (base on DEFAULT_JSDATA to detect early any typo). You probably need to change a little the way how it works with mandatory fields (they are commented out).

**Comment by kelson42** [comment]
_From @EladKeyshawn on December 31, 2016 9:24_

@kelson42 yeah I look a bit further into it;)

**Comment by kelson42** [comment]
_From @EladKeyshawn on January 1, 2017 10:21_

@LFT09KA ?

**Comment by kelson42** [comment]
_From @mhutti1 on January 1, 2017 19:51_

@EladKeyshawn Hes a spammer.

**Comment by kelson42** [comment]
_From @tim-moody on January 19, 2017 13:52_

could we also have the zim directory as a separate optional parameter to which zim_file would be relative.

**Comment by kelson42** [comment]
@tim-moody I would open a new ticket asking to put absolute path in the "zim_file" field

**Comment by kelson42** [comment]
@EladKeyshawn Could you got ahead/finish that ticket? You have almost done most of the work.

**Comment by kelson42** [comment]
_From @EladKeyshawn on February 5, 2017 8:41_

@kelson42 Remind me what addition do I need to do?

**Comment by kelson42** [comment]
https://github.com/kiwix/kiwix/issues/409#issuecomment-269856148

**Comment by kelson42** [comment]
_From @tim-moody on February 5, 2017 14:35_

putting an absolute path for the zim and image files in the json file already worked, at least the last time I ran it.  but I am asking for the opposite, having a separate path parameter so the json files don't all have to be changed if I move the zims.

**Comment by kelson42** [comment]
@tim-moody I do not really understand how this would be easier to what we already have. But you can implement yourself, and I would merge it if that really helps you. I think in particular that you should use #387 new feature.

**Comment by kelson42** [comment]
@mgautierfr I think this feature request is outdated... but may you please explain why?

**Comment by tim-moody** [comment]
Haven't tried this for awhile, so not sure if my request is satisfied. I had a workaround before which hopefully still works.

**Comment by kelson42** [comment]
We won't do that.
