### ISSUE TITLE
Unable to upload APK on play store for new apps.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3505]
**Describe the bug**
We are not able to upload APKs for new apps on the Play console since APKs are not allowed anymore for new apps, but previously uploaded apps can upload the APK.
We are uploading multiple APKs for a different architecture on the Play Store for custom apps with embedded expansion file(ZIM file), and now we have a new app called `DWDS` which we want to publish on the Play Store, but we are not able to publish APK for application on play store since APKs are not allowed, and we can not upload expansion file in AAB(Android app bundle).

**Describe the solution**
So here comes the [Play asset delivery](https://developer.android.com/guide/playcore/asset-delivery) concept specially introduced for AAB by Google. In this, we can embed a file(ZIM file) as a module in our application which we can retrieve when the application is first time launched like we were uploading the aab file inside the APKs. 
Here we will use the `install_time` play asset delivery mode that will provide zim file at the first run of the application.

**Challenges**
* It is a bit challenging to automate the whole process because we need to define these assets in our gradle file, well for now we will manually do this process for the DWDS app and later we will look further to automate the whole process.
* It has a limitation of 1GB means we can only upload a maximum of 1GB file.

**Comment by gouri-panda** [comment]
At the moment we can manually do it for the DWDS app except the downloading the zim file & upload it to the ci.

**Comment by kelson42** [comment]
@gouri-panda please do manually
@MohitMaliFtechiz does that mean the zim will be downloaded at first run?

**Comment by gouri-panda** [comment]
@kelson42 yes, the first time that we do same with the expansion file.

**Comment by kelson42** [comment]
> @kelson42 yes, the first time that we do same with the expansion file.

no, expension files are normally downloaded at install time.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz does that mean the zim will be downloaded at first run?

It is not like that, here we already have the zim file embedded inside the application as an asset, on the first run we get that file from the asset folder as `input stream` and will copy that into the internal storage of the device. By doing this if the user clears the app data, then we can again do the same just copy the file into storage, it does not require any downloading process.

**Comment by kelson42** [comment]
> > @MohitMaliFtechiz does that mean the zim will be downloaded at first run?

So you will use the install-time delivery mode?

**Comment by gouri-panda** [comment]
>no, expension files are normally downloaded at install time. Please secure zim is downloaded and installed at install time using delivery mode 

@kelson42 previously we download the expansion file and put it to all the flavors app by gradle.  Now, we just upload the bundle and assets and Google play store will take care of all the flavors with that asset in the install time.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 for our current situation I would suggest using `install_time` delivery mode as it does not require downloading process and it has a higher size limit to contain the asset.

`install_time` = 1GB.
`fast-follow` and `on-demand ` = 512 MB.
as mentioned in the official docs https://developer.android.com/guide/playcore/asset-delivery#download-size-limits
