### ISSUE TITLE
DWDS app is very slow when opening a search result

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-android#3508]
When I search a term in DWDS app, search is very fast to provide results live.

But when I click on a result to open the corresponding page, it takes about 2 secs for the app to close the search results and open the page.

I do not experience the same latency when navigating from one page to another one inside the ZIM via links present in the pages.

Logs:
[logs1697785830332.txt](https://github.com/kiwix/kiwix-android-custom/files/13051033/logs1697785830332.txt)

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you please point us to the piece of code handling this click (the part which deal with the libkiwix)

**Comment by MohitMaliFtechiz** [comment]
@kelson42 We are handling this click here, firstly we are saving the searched term in the database.

https://github.com/kiwix/kiwix-android/blob/8cf8e1baa381929909dfa5219c685d8e1818e9db/core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt#L168-L178

and after that, we are opening the searched item.

https://github.com/kiwix/kiwix-android/blob/8cf8e1baa381929909dfa5219c685d8e1818e9db/core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItem.kt#L34-L41

Here we are dealing with libkiwix functions.
https://github.com/kiwix/kiwix-android/blob/8cf8e1baa381929909dfa5219c685d8e1818e9db/custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt#L100-L107

and these are the functions we are using to get data from libkiwix.
https://github.com/kiwix/kiwix-android/blob/8cf8e1baa381929909dfa5219c685d8e1818e9db/core/src/main/java/org/kiwix/kiwixmobile/core/utils/ZimReaderContainerUtils.kt#L25-L35

**Comment by kelson42** [comment]
@mgautierfr does that look correct?

**Comment by mgautierfr** [comment]
Difficult to say for now.

It seems with "start" with a call to `saveSearchAndOpenItem(searchListItem: SearchListItem, openInNewTab: Boolean)`. But `searchListItem` is already a search item with a value (something to open). So the search is already done at this time. @MohitMaliFtechiz how this search is done ?

And why do you have a `titleToUrl` method ? In which case you have a title and no url (and so you need this method) ?

If you do a search using libzim, you should have a result with has both title and url. If you need the url you have it. No need to infer a url from the title.

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr Good point :clap:.
`Search` provides the URL with `searchTerm`, but we are not adding this in `SearchListItem` that's why we are calling this function `titleToUrl` to get the URL for a specific title. Probably it was introduced like this because that time, `Search` did not provide the URL with searchTerm or probably there was some issue with the provided URL, might be this is the reason we are not saving the URL in the database. https://github.com/kiwix/kiwix-android/blob/8cf8e1baa381929909dfa5219c685d8e1818e9db/core/src/main/java/org/kiwix/kiwixmobile/core/dao/NewRecentSearchDao.kt#L49
I don't know exactly as this was introduced so long back.
But now `Search` is providing the URL with `searchTerm` and by using the current approach we are getting the URL from the same search result twice, that's the reason why when `ZimFile` is big then it takes time to get the result for search item.

**Comment by MohitMaliFtechiz** [comment]
>@MohitMaliFtechiz Good, please fix. I wonder as well if updating recentsearches should not be done at the end, to avoid slpwing down the whole display of suggestions.

@kelson42 We are showing recent searches with pagination to efficiently display the `Recent Searches`. For previously searched `searchTerms` we are displaying those initially. or am i missing something?

**Comment by kelson42** [comment]
> > @MohitMaliFtechiz Good, please fix. I wonder as well if updating recentsearches should not be done at the end, to avoid slpwing down the whole display of suggestions.
> 
> @kelson42 We are showing recent searches with pagination to efficiently display the `Recent Searches`. For previously searched `searchTerms` we are displaying those initially. or am i missing something?

We don't understand each other. Goal is to display the suggestions ASAP. If you call `saveSearchAndOpenItem()` before anything else, this slows down the display of the suggestions. Do that at the end and in the background to be sure this does not impact the speed of display of the suggestions (from a user perspective).

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have made changes in #3514 as you requested.

**Comment by kelson42** [comment]
@gouri-panda Can you please review?
