### ISSUE TITLE
Cannot open ZIM files from phone storage

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-android#3515]
I cannot open ZIMs which have not been downloaded from the Kiwix app.

Kiwix Android 3.7.1 Build 7230701 (2023-10-26 nightly)

ZIMs downloaded by the app (and hence placed in the app data folder where app obviously has proper permissions) are opening well.

ZIMs downloaded by something else (Firefox in current test, but I'm sure it does not matters) and not placed in this folder (placed in Download folder in my test) do not open with the error "Impossible de lire ce fichier ZIM" (in French which is expected on my phone).

Maybe a permission issue to access storage?

Probably a close duplicate of #1447 (not exactly the same, there is probably no file handler issue, but still a permission problem).

Logs:
[logs1697787018926.txt](https://github.com/kiwix/libkiwix/files/13175333/logs1697787018926.txt)

Steps to reproduce:
- download a ZIM from the internet from your browser (e.g. https://library.kiwix.org/ or https://dev.library.kiwix.org/)
- open Kiwix app
- go to the Catalog
- click the "+" sign in the bottom right corner to add a local ZIM
- select the ZIM you just downloaded
- et voilà

**Comment by benoit74** [comment]
I don't know how I achieved to open this issue in the wrong repo initially ^^

**Comment by MohitMaliFtechiz** [comment]
@benoit74 are you able to see the downloaded zim file on the `Library screen`? if not can you please check whether `Allow management of all files` permission is enabled or not?

| Library screen  | Permission |
| ------------- | ------------- |
| ![1698312227703](https://github.com/kiwix/kiwix-android/assets/34593983/74222735-ce3e-446e-a3b4-e519a03611f8)  | ![1698312090900](https://github.com/kiwix/kiwix-android/assets/34593983/1180b634-3e9d-4f07-b0f3-0f7378f14731)  |

**Comment by benoit74** [comment]
No, the downloaded ZIM is not listed in the Library.

And No, `Allow management of all files` permission is not enabled in Kiwix application, it is not even listed so cannot grant the permission (or I don't know how to do this)
| Library screen  | Permission |
| ------------- | ------------- |
| ![Screenshot_20231027-134508](https://github.com/kiwix/kiwix-android/assets/7102089/dd16f35b-4847-4305-89f2-e6cb1a513d8e) | ![Screenshot_20231027-134300](https://github.com/kiwix/kiwix-android/assets/7102089/76f33a86-3c26-463e-ba6d-4805d8a846aa) |

**Comment by MohitMaliFtechiz** [comment]
> No, the downloaded ZIM is not listed in the Library.
And No, Allow management of all files permission is not enabled in the Kiwix application, it is not even listed so cannot grant the permission (or I don't know how to do this)

@benoit74 Thanks for the information it is a permission-related issue I am able to reproduce it on my device.

> It is not even listed so cannot grant the permission (or I don't know how to do this)

In Android 13 `MANAGE_EXTERNAL_STORAGE` is a special permission and it is not directly listed under the app info. We can find this permission in our phone settings.

**Settings->Apps->Special App Access->All File Access.**

Here you will see the `kiwix` app click on that and enable the permission, after that you will be able to load zim files via file picker also the zim files will be listed on the `LocalLibraryFragment`.

But it should show the `Allow Files Permission needed` dialog which takes the user directly to the setting. I am placing a fix for it.

**Comment by MohitMaliFtechiz** [comment]
@benoit74 This issue will be fix by https://github.com/kiwix/kiwix-android/pull/3518.
