### ISSUE TITLE
Custom App Updates Do not Result in Updated ZIM Content

### ISSUE THREAD

**Issue by gremid** [kiwix/kiwix-android#3522]
**Describe the bug**
When updating a custom app (DWDS in this case), the updated ZIM bundled with the app is not available. Only after clearing the cache and local files of the app, the updated ZIM can be accessed. 

**Expected behavior**

A custom app update with updated ZIM data should provide the updated information in the ZIM immediately without requiring to manually clear cached files.

**Steps to reproduce the behavior:**
1. Install the DWDS custom app.
2. Start the app and use the app.
3. Wait for an updated version and run the update via the Play Store.
4. After the update, check whether the ZIM data displayed in the updated app have been updated as well. 

**Environment**
- Version of Kiwix Android : DWDS Custom App 2023-10-26 Build: 7232990
- Device : Redmi Note 0S
- OS version : Android 13 TP1A.220624.014

**Comment by gremid** [comment]
My guess is that [CustomFileValidator](https://github.com/kiwix/kiwix-android/blob/develop/custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomFileValidator.kt#L37-L41) lacks handling of an additional `NeedsUpdate` state. As long as a ZIM file has been copied from the assets to local storage once, I do not see any code detecting and handling updates, i. e. via checksums. But my overview of the code base is very limited.

**Comment by kelson42** [comment]
@gremid Pretty sure this will be fixed with #3516.
@MohitMaliFtechiz You confirm?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Yes, it will be fixed by #3516
