### ISSUE TITLE
All-Books-Mode Redundant for Bookmarks, Notes and History in Custom Apps

### ISSUE THREAD

**Issue by gremid** [kiwix/kiwix-android#3523]
**Describe the bug**

In the DWDS custom app, the pages for History, Bookmarks and Notes display switches for changing the focus between the current ZIM/book and all books available in the reader app. As the custom app is bundled with a specific ZIM, these switches are redundant and misleading for a user without knowledge about Kiwix library concept.

**Expected behavior**

The switches should not be displayed in custom apps with a bundled ZIM.

**Environment**
- Version of Kiwix Android : DWDS Custom App 2023-10-26 Build: 7232990
- Device : Redmi Note 0S
- OS version : Android 13 TP1A.220624.014

**Comment by kelson42** [comment]
@MohitMaliFtechiz A regression?

**Comment by MohitMaliFtechiz** [comment]
@gremid Thanks for reporting the issue.

@kelson42 it's not fully regression as it is not affecting any functionality of the application, but yes it should not display the switches in the custom apps as there is only a zim. So we should hide these switches from these screens for better UI, and will not confuse the user.

**Comment by kelson42** [comment]
> @kelson42 it's not fully regression as it is not affecting any functionality of the applicatio

I mean with "regression", those switches were not hidden properly in the past?

**Comment by MohitMaliFtechiz** [comment]
> I mean with "regression", those switches were not hidden properly in the past?

Yes, switches were not hidden in the past, they were showing like showing in the `kiwix-app`.

**Comment by MohitMaliFtechiz** [comment]
This issue will be fix by https://github.com/kiwix/kiwix-android/pull/3525
