### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [kiwix/kiwix-android#3529]
Please support the Android 13 Themed App Icons feature.

![Screenshot_2023-11-09-02-55-55-093_de mm20 launcher2 release](https://github.com/kiwix/kiwix-android/assets/23485114/bfd1ba14-2024-4d00-aa18-7a600ef980ae)

**Comment by wbillan** [comment]
I'm all for this, but considering that Kiwix is now de-listed per [Google Play Policy](https://support.google.com/googleplay/android-developer/answer/11926878) for users who are on Android 12+ devices who have never installed the app, due to the latest version of this app on Play Store targeting Android 11, is this critical for the next release?

**Comment by xmha97** [comment]
For me, yes, it is vital.
Because all app icons are monochrome and the Kiwix icon does not follow this rule.

![Screenshot_2023-11-15-18-52-54-118_de.mm20.launcher2.release.jpg](https://github.com/kiwix/kiwix-android/assets/23485114/3e4a41d5-d3b4-43cb-989d-3ba010fd487e)

**Comment by gouri-panda** [comment]
I believe we implemented that feature in #3291 . @xmha97 Which version of kiwix and Android are you using?

**Comment by kelson42** [comment]
@gouri-panda concretly, where is thst in source code?

**Comment by MohitMaliFtechiz** [comment]
@xmha97 Can you please confirm which application version are you using? Also can you please confirm which device you are using?

you can find it under **Settings=>Version**

![1700140579657](https://github.com/kiwix/kiwix-android/assets/34593983/cec2be78-0e94-41a5-ba65-0abb47baeed9)


I have Google pixel 7a(Android 13) and it is showing `Themed app icons`

| Themed icon  | Themed icon | Without Themed icon |
| ------------- | ------------- | ------------- |
| ![1700140771713](https://github.com/kiwix/kiwix-android/assets/34593983/826c1027-cbbf-4148-81ae-0fbc1845502c)  | ![1700140448191](https://github.com/kiwix/kiwix-android/assets/34593983/f1d730f1-e671-46ab-927f-63a17290d5b1) | ![1700140837468](https://github.com/kiwix/kiwix-android/assets/34593983/5ab9e95b-761c-4fc6-93b4-8a7965715c44) |

**Comment by MohitMaliFtechiz** [comment]
> @gouri-panda concretly, where is thst in source code?

@kelson42 Here we have put the monochrome icons https://github.com/kiwix/kiwix-android/tree/develop/core/src/main/res/mipmap-anydpi-v26 which we have added in https://github.com/kiwix/kiwix-android/pull/3294
