### ISSUE TITLE
Lots of problem with links (reported by PlayStore)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3549]
![image](https://github.com/kiwix/kiwix-android/assets/1029718/43b5614e-0e84-4eed-bf9f-a0d86179ddff)

**Comment by kelson42** [comment]
@MohitMaliFtechiz What is the impact of this bug to end-users?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz What is the impact of this bug to end-users?

Starting from Android 12, it is mandatory to specify `android:autoVerify="true"` in deep linking. This attribute provides more control to developers and end-users, signaling to the system to verify whether your app belongs to the URL domains used in your intent filters, thus making the process faster. This also makes deep linking compatible with new Android versions, as there have been numerous changes introduced. [More info here](https://developer.android.com/training/app-links/verify-android-applinks)

**Comment by kelson42** [comment]
@MohitMaliFtechiz What is the impact of this bug to end-users?

I have still no clue what is concretly impact on users...
