### ISSUE TITLE
Identify split ZIM files as partial until complete download

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#355]
Currently downloading a split ZIM file will create a.zimaa.part then rename to a.zimaa then download a.zimab.part then rename ... We should change this system so the split parts are still identified as such until the final chunk is download. One way to implement this would be a double .part.part for split ZIMs

**Comment by Kartik2016** [comment]
I'd like to work on this. Can i go ahead?

**Comment by mhutti1** [comment]
@Kartik2016 Yeah go ahead.

**Comment by Kartik2016** [comment]
Correct me if i am wrong. I need to edit the getZimChunkFileNames method in the ChunkUtils.java class to rename the files with .part.part instead of only .part?
Is there anything else that also needs to be done

**Comment by mhutti1** [comment]
You will need to remove the first .part when the chunk is downloaded (as currently occurs) but only remove the second .part when the entire file is downloaded.

**Comment by Kartik2016** [comment]
Ok. Thanks

**Comment by Kartik2016** [comment]
https://github.com/kiwix/kiwix-android/blob/c359881df8fe12efde9a45bfb268c2275d50bd1e/app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java#L508
In this method, the .part is removed only when the whole file is downloaded. Please guide me to the method where a split chunk is downloaded completely and where the first .part needs to be removed.

**Comment by mhutti1** [comment]
@Kartik2016 That is that method. Its in the method called DownloadChunk and thats what it does.

**Comment by mhutti1** [comment]
@Kartik2016 If you meant the first .part by string not by time (what I assumed) then that should be removed once the whole file is downloaded. It is good to get a sense of the code base and find this method for yourself.

**Comment by Kartik2016** [comment]
While deleting the split chunks, mainting a list was not a viable solution since the service could be destroyed and the list would not persist. Will creating a shared preference file help? Any other suggestions?

**Comment by kelson42** [comment]
@Kartik2016 No chunk is ever deleted, only renamed. Here is how it should work IMO: just keep the chunk filenames with "part" until the end. One time the download has reached the end. Rename all of them at a time. By doing so, you will probably need to change the logic to detect if a chunk has been fully downloaded, this could be done by checking the file size and/or by seen if the next chunk has started to download. @mhutti1 Please confirm.

**Comment by Kartik2016** [comment]
Yes i have done exactly this in the code. When the entire book is download, i have called the function to rename all chunks to remove the .part in the end. My doubt is regarding the case when the download is stopped midway or a downloaded book is deleted.

**Comment by mhutti1** [comment]
You can either used sharedpreferences or a database entry. We already use the database when downloading "books".

**Comment by sakchhams** [comment]
@mhutti1 @kelson42 if no one is working on this anymore, may I proceed with this?

**Comment by kelson42** [comment]
@sakchhams Yes you can

**Comment by kelson42** [comment]
@mhutti1 Thx for this bug fix!
