### ISSUE TITLE
 "App Freeze and Persistent Notification Post Denial of Media Access Permission"

### ISSUE THREAD

**Issue by Sivam-kuma** [kiwix/kiwix-android#3553]
**Describe the bug**
Upon denying media access permission and selecting "Don't ask again" in the latest version of Kiwix Android available on the Google Play Store (3.4.5), the app becomes unresponsive, displaying a toast message at the bottom of the screen. Exiting the app, the toast message persists on the device's home screen, even when not actively using the application.

**Expected behavior**
After denying media access permission and selecting "Don't ask again," the app should gracefully handle the denial without affecting its functionality or freezing. Additionally, no toast message should persist on the device's home screen after exiting the app.

**Steps to reproduce the behavior:**
 1. Launch Kiwix Android.
 2. Deny media access permission when prompted and select "Don't ask again."
 3. Observe the app becoming unresponsive and displaying a toast message.
 4. Exit the app and notice the toast message lingering on the device's home screen.

Environment

 1. Version of Kiwix Android:  3.4.5(latest version available on Google Play Store)
 2.Device: [Android 10]
 3.OS version: Android 10
**Screenshots**

**Comment by Sivam-kuma** [comment]
Please assign this issue to me so I can thoroughly analyze the problem and work towards a resolution.

Thank you."

**Comment by kelson42** [comment]
We are just about releasing version `3.8.0` to the Play Store, I guess this will be fixed there. You can also download the APK at https://download.kiwix.org/release/kiwix-android/kiwix-3.8.0.apk

**Comment by Sivam-kuma** [comment]
I am pleased to confirm that the reported issue has been successfully addressed and resolved in version 3.8.0 of the application.
