### ISSUE TITLE
3.4.5 Kiwix offline Playstore update 

### ISSUE THREAD

**Issue by Mitia99** [kiwix/kiwix-android#3554]
**Describe the bug**

There's a 3.4.5 update available on Playstore though I have 3.8.0 installed

**Expected behavior**

No update available 

**Steps to reproduce the behavior:**
1. Install [Kiwix 3.8.0](https://github.com/kiwix/kiwix-android/releases/download/3.8.0/3.8.0-arm64-v8a-release.apk)
2. Open Google Playstore and check updates available

**Screenshots**
![Screenshot_20231126_082043_com.android.vending_edit_355644071298.jpg](https://github.com/kiwix/kiwix-android/assets/56766778/1eee4751-bf3a-467a-9893-7bdab824f102)

**Environment**
- Version of Kiwix Android : 3.8.0
- Device : Huawei P30 ELE-L09 
- OS version : Android 10

**Comment by kelson42** [comment]
3.8.0 is in open testing on the play store. Join https://play.google.com/apps/testing/org.kiwix.kiwixmobile

**Comment by Mitia99** [comment]
> 3.8.0 is in open testing on the play store. Join https://play.google.com/apps/testing/org.kiwix.kiwixmobile

Thanks for letting me know.

So the 3.8.0 in Releases isn't stable?
