### ISSUE TITLE
Many `TypographyQuotes` errors came after upgrading the gradle.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3555]
**Describe the bug**
While upgrading the project to support Android 14, we upgraded our gradle but after upgrading the gradle many `TypographyQuotes` errors were found by the lint.

**Expected behavior**
We should fix these issues on the upstream.

**Screenshots**
![Screenshot from 2023-11-27 14-48-47](https://github.com/kiwix/kiwix-android/assets/34593983/aac634de-6304-4d69-a7f8-07adafaeb294)

For compiling the project we have suppressed the lint, see https://github.com/kiwix/kiwix-android/pull/3481/commits/07bb2f3b3d43774dc7cea89a5ccf564b48c7f96c .

**Comment by kelson42** [comment]
@MohitMaliFtechiz We are waiting a few review to complete `3.10.0`. In the meantime can you fix this "nobrainer" please?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Sure.

**Comment by kelson42** [comment]
@MohitMaliFtechiz How much is left to fix? Why our linter does not complain?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have changed all the affected strings on the upstream. Some of the changes have been came in the latest translate wiki PR https://github.com/kiwix/kiwix-android/pull/3670/files, hope all the changes will came soon.

**Comment by MohitMaliFtechiz** [comment]
> Why our linter does not complain?

@kelson42 In our current gradle lint treats this issue as a warning since this version of gradle contains the old lint, so it does not complain, but after upgrading the Gradle it starts to report this warning as an error, as this version of gradle comes along with the upgraded lint.

**Comment by kelson42** [comment]
@MohitMaliFtechiz why gradle is not updated to a recent version? We should not detect this kind of things in rhe playstore. We should detect this earlier.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Gradle is up to date with our current `targetSDK` version(33). For upgrade gradle we need to upgrade our `targetSDK` version to 34 which we were doing in https://github.com/kiwix/kiwix-android/pull/3481.

**Comment by kelson42** [comment]
Closimg as we won‘t wait all steings are translated in all languages before closing this ticket. There is nothing more we can do.
