### ISSUE TITLE
Pages with a slash '/' in the title/path are shown blank

### ISSUE THREAD

**Issue by ManzoniGiuseppe** [kiwix/kiwix-android#3557]
**Describe the bug**
Any page with a '/' in its path/title is displayed blank, and the title (both when viewing the open tabs, and when creating a note) is 'kiwix.app/A/' followed by the page name, which always contains a '/' somewhere

**Expected behavior**
Should show the page instead of blank, and it should show the title intead of the url

**Zims**

I first saw the issue on Wikibook english full, so I deleted it, thinking it was a problem with it, as Wikipedia and Wiktionary English full work perfectly (but they don't have pages with a '/' in them either) I tried wikibook english without images and again I deleted it for the same reason. Then I downloaded Wikisource english with images and I realized it was not a problem of wikibook. I did all the testing there.

**Steps to reproduce the behavior:**
Quickest
 1. Open Wikisource
 2. Click to get a random article
 3. It shows a blank page
Note: Most likely it'll be one with a '/' due to how wikisource is structured, which I checked at every test by looking at the title (by clicking to make a note)

Search based
 1. Open Wikisource
 2. Search something generic (e.g 'of')
 3. click a result with a '/' in the name. (e.g. 'Of Gardens/Of Gardens')
 4. It shows a blank page
Note: All the other results (without '/') that I checked work

Navigation based
 1. Open Wikisource
 2. From the main page open a link to any book (e.g 'A Simplified Grammar of the Swedish Language')
 3. Scroll down to the index of that book
 4. Click any link to open a volume or a chapter. (e.g 'The Alphabet')
 5. It shows a blank page

**Environment**
- Version of Kiwix Android : 3.8.0 (upgraded from 3.7.1 because it didn't work there either) with the testing done on the 3.8.0, both obtained from direct apk
- Device : Fairphone 4
- OS version : Android 13 (DivestOS 20)

**Comment by ManzoniGiuseppe** [comment]
The new apk of issue #3556 solved this too, thank you

**Comment by MohitMaliFtechiz** [comment]
@ManzoniGiuseppe Glad to know this. Thanks for opening the issue :innocent:.
