### ISSUE TITLE
Titles of Redirect Entries do not Show Up in Search Results 

### ISSUE THREAD

**Issue by gremid** [kiwix/kiwix-android#3559]
**Describe the bug**
When searching for titles, titles of redirect entries do not appear in the results. In the case of the DWDS custom app, we have about 16,000 redirect entries for alternative spellings of dictionary entries (i. e. "Delphin" vs. "Delfin") and while the major spelling variant can be found in the title search (i. e. "Delfin"), the alternative spelling does not show up (i. e. "Delphin").

**Expected behavior**

Both types of ZIM entries, content as well as redirect entries, should be indexed and searchable.

**Steps to reproduce the behavior:**
1. Open the DWDS custom app.
2. Search for "Delphin" vs. "Delfin".

**Environment**
- Version of Kiwix Android : DWDS Custom App 2023-11-20 Build: 7233250
- Device : Redmi Note 0S
- OS version : Android 13 TP1A.220624.014

**Comment by kelson42** [comment]
@mgautierfr I guess the problem is that in `zimwriterfs`, `ZimCreatorFS::add_redirectArticles_from_file()` does not have any hint?! I "yes", can you please make a fix.

**Comment by kelson42** [comment]
Kamino closed and cloned this issue to [openzim/zim-tools](https://github.com/openzim/zim-tools/issues/388)
