### ISSUE TITLE
Opening Library Items crashes the app

### ISSUE THREAD

**Issue by suhan-paradkar** [kiwix/kiwix-android#3563]
Latest version 3.8.0 from F-Droid

**Describe the bug**

Clicking on any library item crashes the app
Note that I have downloaded and am using zim files from sdcard

**Expected behavior**

No crash

**Steps to reproduce the behavior:**
1.Just click on any item in Library

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.8.0
- Device : OPPO A12 (CPH2083)
- OS version : Android 9

**Comment by suhan-paradkar** [comment]
Here's a screen recording..

https://github.com/kiwix/kiwix-android/assets/76830230/6c1cc78f-5e40-4add-9396-345da5e9961a

**Comment by kelson42** [comment]
@suhan-paradkar 3.8.0 is not available on FDroid. Sonething is wrong somewhere.

**Comment by suhan-paradkar** [comment]
@kelson42 It is on IzzyOnDroid repo... and references this repo as its source...
Is it added by somebody else?

**Comment by suhan-paradkar** [comment]
Heres screenshots

![Screenshot_2023-11-30_07-00-34](https://github.com/kiwix/kiwix-android/assets/76830230/0ccf4eb8-a808-44a0-87b3-7eaf1671bb23)
![Screenshot_2023-11-30_07-00-41](https://github.com/kiwix/kiwix-android/assets/76830230/91cde4d5-8a70-4c69-b156-b7f6d22f832f)

**Comment by suhan-paradkar** [comment]
Closing it as it cannot be reproduced on play-store version
