### ISSUE TITLE
unable to open zim files on sd card in version 3.8.1

### ISSUE THREAD

**Issue by s-i-m-s** [kiwix/kiwix-android#3577]
3.8.1 installed from https://download.kiwix.org/release/kiwix-android/kiwix.apk
Android 13 on LG v60

It can see the zim files on my sd card but it can't open them it gives `Error: The selected ZIM file could not be found.`

If I try to add one it says `Unable to read this zim file!`

Trying to download via the app just says pending indefinitely.

![Screenshot_20231204-095812](https://github.com/kiwix/kiwix-android/assets/27518110/c484959c-ffeb-4371-b08a-b4e22b0f3e7f)
![Screenshot_20231204-095806](https://github.com/kiwix/kiwix-android/assets/27518110/5d2fdc7f-191b-404d-85a9-fcbbb903ef37)
![Screenshot_20231204-095801](https://github.com/kiwix/kiwix-android/assets/27518110/730d6312-7edd-434a-bed6-7704015f0e93)

**Comment by s-i-m-s** [comment]
Just to note the behavior is the same both from the kiwix.org apk and when installed from the play store.

**Comment by kelson42** [comment]
@MohitMaliFtechiz You confirm? How is that possible!?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz You confirm? How is that possible!? The APK should work!?

@kelson42 Everthing seems working with the SD card the symptoms described by the user occur in the absence of `MANAGE_EXTERNAL_STORAGE` permission.

**Comment by s-i-m-s** [comment]
@MohitMaliFtechiz Confirming that was indeed the issue.

I see what happened now. When I install 3.8.0 from APK it prompts for all files permission on first run which I grant but when I install 3.8.1 it doesn't prompt for permission and for whatever reason I did not think of it nor notice that the new version isn't prompting.

Thanks!

**Comment by kelson42** [comment]
@MohitMaliFtechiz if new permissions are needed, we should prompt after update . Can we fix this?

**Comment by s-i-m-s** [comment]
Screen recordings;
3.8.0 install from apk with show touches and show touch data enabled, android 13 LG V60
https://github.com/kiwix/kiwix-android/assets/27518110/406ee065-01db-4630-8900-3735fbe5d91b

3.8.1 install from apk with show touches and show touch data enabled, android 13 LG V60
https://github.com/kiwix/kiwix-android/assets/27518110/f1f4914d-04ab-4c91-8f34-16ef3424c4fc

**Comment by MohitMaliFtechiz** [comment]
> Notably 3.8.1 also doesn't give the "welcome to the family" first run screen either.

@s-i-m-s Thanks for providing this information. Have you uninstalled the previous version of the app from your device before installing the new one?

**Comment by s-i-m-s** [comment]
@MohitMaliFtechiz

Yes I have uninstalled the app prior to installing the APK each time.

If I install 3.8.0 first, don't open the app then upgrade to 3.8.1 and open the app the welcome screen activates and it prompts for permission.

Likewise if I install 3.8.0 and open it the welcome screen runs and prompts for permissions, if I set the permissions they persist when I update to 3.8.1 and it works as normal.

But if I uninstall the app then install 3.8.1 and open the app the welcome screen doesn't run and it doesn't prompt for permissions.

**Comment by MohitMaliFtechiz** [comment]
@s-i-m-s Thanks for confirming, we have placed a fix for this in #3593. It will ask for permission if you will try to use those features that require this permission such as downloading ZIM files, selecting a ZIM file from storage via the file picker, and refreshing the list of available ZIM files in storage.
