### ISSUE TITLE
On 3.8.1 installed from Play Store (at least), Zimit archives are not displaying correctly

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-android#3578]
With v3.8.1 from the Play Store, I noticed that two recent Zimit archives are displaying without the Service Worker transforming links. I haven't found any Zimit archives that display correctly yet, 

Top screenshots are the Android version (ignore inversion, that's not the issue), and bottom screenshots show how they should both look (from the Zimit support in Kiwix JS Browser Extension). The first ZIM is `bestedlessons.org_en_all_2023-11.zim`, and the second is `internet-encyclopedia-philosophy_en_all_2023-08.zim`. These are small ZIMs, so can easily be tested, in case it's just my copy of the app (v3.8.1 build 7230801 on Android 12):

![image](https://github.com/kiwix/kiwix-android/assets/4304337/4063802d-88a7-45f8-8303-6ed922bb361a)

**Comment by Jaifroid** [comment]
Is anyone else able to confirm this issue, especially if using the APK version, to rule out this being somehow related to the Play Store?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz This is a regression! Please fix ASAP.

@kelson42 I have placed a fix for it in https://github.com/kiwix/kiwix-android/pull/3580. @Jaifroid if possible can you please try with #3580?

**Comment by Jaifroid** [comment]
(I replied to the PR.)
