### ISSUE TITLE
Add issues and pull request templates to the project.

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#358]
Currently there isn't any issues and PR template for the project. It is very useful to have and almost all the standard projects have it.

@kelson42 @mhutti1 Please review if i should add them or not ?

**Comment by mhutti1** [comment]
This sounds like a good idea. I would love to see your suggestions and we can discuss them.

**Comment by kelson42** [comment]
@srv-twry We have created one here https://github.com/openzim/overview/blob/master/REPORT_BUG.md

**Comment by srv-twry** [comment]
@kelson42 Great! , I'll add them in this repo also.

**Comment by kelson42** [comment]
@srv-twry Sorry, my bad. I have given you the wrong link. This is what I meant https://github.com/openzim/sotoki/blob/master/.github/ISSUE_TEMPLATE.md
