### ISSUE TITLE
Submenu "Help" in Sidebar is Misleading in Custom Apps

### ISSUE THREAD

**Issue by gremid** [kiwix/kiwix-android#3584]
**Describe the bug**

In custom apps like the DWDS app, the "Help" menu in the sidebar only contains options for sending feedback and diagnostic information, whereas entries providing guidance for the user are not available.

**Expected behavior**

Separate the submenu into two, "Feedback" and "Help" and remove "Help" in custom apps.

**Steps to reproduce the behavior:**

1. Open the sidebar in the DWDS custom app.
2. Open the "Help" submenu, finding only feedback options.

**Environment**
- Version of Kiwix Android : DWDS Custom App 2023-11-20 Build: 7233250
- Device : Redmi Note 0S
- OS version : Android 13 TP1A.220624.014

**Comment by kelson42** [comment]
@MohitMaliFtechiz The best IMO is to hide this help for all custom apps.

**Comment by gouri-panda** [comment]
@kelson42 @MohitMaliFtechiz Shouldn't we solve this problem another way instead of removing this? We should add a better name and rearrange the section.
