### ISSUE TITLE
Improve Sidebar "Support Kiwix" icon

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3585]
App would benefit of the replacement of the lifebuoy icon with something better:

For example:
* https://fontawesome.com/icons/info?f=classic&s=solid
* https://fontawesome.com/icons/arrow-up-right-from-square?f=classic&s=solid

**Comment by kelson42** [comment]
I think we could indeed do better, but not really happy with the current proposals. I have made a few researches and I think something like this would be better
![image](https://github.com/kiwix/kiwix-android/assets/1029718/09cbd0b1-030e-4b07-9a14-c1901309c145)

But I don't have found a free version of this logo. Many just a heart logo would be good as well?

**Comment by Shreyassp002** [comment]
@kelson42 Hey, I found a heart icon from here [Heart Icon](https://fontawesome.com/icons/heart?f=classic&s=regular), if this is a good fit then I will open a PR.

![d](https://github.com/kiwix/kiwix-android/assets/96625037/06059cfe-a508-4bca-87ee-cf7d9e925cb4)

**Comment by kelson42** [comment]
@Shreyassp002 Thx, looks good, even if I believe the icon to be a bit to big in comparison to the other icon. A PR is welcome.
