### ISSUE TITLE
Remove redundant castings in the project.

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#359]
**Actual behaviour**

There are a lot of redundant casting in the project. 
For eg: 
``` Java
TextView title = (TextView) convertView.findViewById(R.id.title);
```
Casting it to ```TextView``` isn't required at all. There are a lot of instances of these castings. 

**Expected behaviour**

They should be removed to keep the code cleaner.
Not a big issue but certainly can be taken as a first issue.

**Would you like to go ahead with it ?**

Yes.

@kelson42 @mhutti1 please review whether i should go ahead with this or not ? 
thanks.

**Comment by mhutti1** [comment]
I think these casts were required in the past but aren't any more. Cleaning up code like this is definitely a good idea.
