### ISSUE TITLE
Allow custom app version_code to be unspecified and to instead query Google Play and increment

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#36]
_From @mhutti1 on December 30, 2016 20:12_

If the version code is unspecified (not available or empty string) in a custom apps json we should query Google play and increment the version code from the latest version that is published (including alpha/beta).

_Copied from original issue: kiwix/kiwix#408_

**Comment by kelson42** [comment]
This is one of the few mandatory things to do to allow to build an auto-update system for custom apps. Important ticket.

**Comment by kelson42** [comment]
@mgautierfr I think this feature request is outdated... but may you please explain why?

**Comment by macgills** [comment]
[Gradle play publisher](https://github.com/Triple-T/gradle-play-publisher#handling-version-conflicts) has a mode where it can automatically choose the next sequential version code

**Comment by kelson42** [comment]
@macgills So we should close that one? What is importante is the version name, what is displayed to the user (it should stay with the format yyyy-mm).

**Comment by macgills** [comment]
I need to implement it so keep the ticket open
