### ISSUE TITLE
Addition to "How To Report A Bug"

### ISSUE THREAD

**Issue by Beater34** [kiwix/kiwix-android#3607]
https://kiwix.org/en/how-to-report-a-bug/ is very helpful, but it does not say how to open a "ticket", which is actually called an "issue" on github. I suggest adding:

How to open a ticket (issue)
1. Go to https://github.com/kiwix/kiwix-android/issues
2. Click on the green "New issue" button near the top right.

**Comment by kelson42** [comment]
@Beater34 This is not a step-by-step tutorial and there is already a link to the Kiwix Android issue page. That said, maybe we could/should replace "Ticket" by "Issue" in the documentation. @Popolechien What do you think?

**Comment by kelson42** [comment]
@Popolechien ???

**Comment by Popolechien** [comment]
I've fixed the text (grammar, simplification, replaced `ticket` with `issue` across the board), and added an actual screenshot of the issue.
