### ISSUE TITLE
Inconsistent Visibility Behavior: Text and Button Overlay When Opening Tabs

### ISSUE THREAD

**Issue by Santoshpant23** [kiwix/kiwix-android#3623]
**Describe the bug**
Upon attempting to view currently open tabs within the app, I noticed an inconsistency in behavior. Specifically, the text ("No open book") and the button ("Open Library") exhibited conflicting placement. The button was positioned on top of the tab, while the text appeared behind it.

**Expected behavior**
When initially opening the app, the reader section should display zero tabs at the top, indicating no opened tabs. If this behavior is intentional, then upon clicking the tabs button, neither text nor buttons should be visible.

**Steps to reproduce the behavior:**
1. Open the application
2. If there are existing tabs, clear them all.
3. Click on the Library and return to the Reader.
4. Despite clearing all tabs, you will observe one tab.
5. Click on the tabs button to witness the UI inconsistency.

**Screenshots**

![Open1](https://github.com/kiwix/kiwix-android/assets/72144199/1f3285d7-4aef-46d7-bf3a-3520a543cabb)

![Open2](https://github.com/kiwix/kiwix-android/assets/72144199/2ecd17c4-0f4b-4957-9bda-00402bcf484c)

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : Samsung Galaxy S21 Fe
- OS version : Android 13

**Comment by gouri-panda** [comment]
@Santoshpant23 Do you produce this consistently?  I think it may be lagging of your phone.

**Comment by Santoshpant23** [comment]
@gouri-panda  I have tried it multiple times, and I do not think it is because of lagging. Can you check and verify it?

**Comment by gouri-panda** [comment]
>@gouri-panda I have tried it multiple times, and I do not think it is because of lagging. Can you check and verify it?

@Santoshpant23 Sorry! I can't produce this bug. @MohitMaliDeveloper Can you?

**Comment by Santoshpant23** [comment]
@gouri-panda I figured out something interesting. The actual problem occurs when switching between light and dark mode. When the light mode is turned on, everything seems to be perfect. However, when dark mode is turned on, the UI becomes inconsistent. 

Have a look when the light mode is turned on: 

![open3](https://github.com/kiwix/kiwix-android/assets/72144199/e8115fb7-7793-4f62-8f6c-60106685aee5)

**Comment by satvik2131** [comment]
is anyone working on this issue , or I can work on this ?

**Comment by kelson42** [comment]
@satvik2131 Nobody is working on this ticket... but @gouri-panda or @MohitMaliFtechiz please confirm the bug first.

**Comment by gouri-panda** [comment]
@kelson42 Still No. @MohitMaliDeveloper  @satvik2131  Do you? @Santoshpant23 still are you facing this problem too? If yes, you can create this action and send us logs to see maybe that'll help a little bit.

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda, @kelson42 I am able to reproduce this error on my device. 


https://github.com/kiwix/kiwix-android/assets/34593983/ba5d7518-a06b-473e-b733-b51ea3381b0e

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Great!

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda, @kelson42 I have placed a fix for this issue in https://github.com/kiwix/kiwix-android/pull/3688. Also, I have found a small UI issue, when we close all tabs that means currently no zim file is present in the reader at this moment, the "Read Aloud" button is showing in the menu so I have placed a fix for that also.
