### ISSUE TITLE
Unable to search for Chinese words

### ISSUE THREAD

**Issue by uname2p** [kiwix/kiwix-android#3631]
Kiwix from v3.7.1 after the version can not be normal search for Chinese phrases, you can search for a single word, but can not search for a word.
![Screenshot_20231226_142531_org kiwix kiwixmobile](https://github.com/kiwix/kiwix-android/assets/19523804/c6bb282a-1c99-490d-8808-1393062b531d)

For example, I want to search for the word "孔丘", so I first input "孔", then I can retrieve the related words in the zim file. 
![Screenshot_20231226_142042_org kiwix kiwixmobile](https://github.com/kiwix/kiwix-android/assets/19523804/c329b2b8-2445-4e73-9d64-a814c30581f4)

Then, I input "丘" to form the word "孔丘" and there is no match.
![Screenshot_20231226_142052_org kiwix kiwixmobile](https://github.com/kiwix/kiwix-android/assets/19523804/f61e0776-2835-46af-96ce-fad82ca19497)

However, if I search for English words, there is no such bug.
![Screenshot_20231226_144146_org kiwix kiwixmobile](https://github.com/kiwix/kiwix-android/assets/19523804/5b862fdc-fd21-4174-8b02-b86b2b1a5141)

**Comment by kelson42** [comment]
@uname2p Thank you for your detailed bug report. I confirm the bug. It's actually in the libzim and handled there https://github.com/openzim/libzim/issues/794. I'll close here to avoid duplication.
