### ISSUE TITLE
Use leak canary to control/avoid memory leaks

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#364]
**Proposal**

Currently we aren't using any library to avoid memory leaks. [Leak canary](https://github.com/square/leakcanary) is a lightweight library by Square which can be used to control and avoid memory leaks in the application.
It is a very famous library and used in various open source projects. I think it should be used in this project also.

@mhutti1 @kelson42 Please review and suggest if i should add it or not ?

**Comment by brijeshshah13** [comment]
@srv-twry Doesn't it install its's own app to display the leaks which occupies quite a lot of space?

**Comment by srv-twry** [comment]
1. Yes it installs another application.
2. No, I think it doesn't occupy quite a lot of space.
3. Most importantly, Leak canary will be installed only for the debug build. Hence as a developer we definitely can allow it some space.

**Comment by brijeshshah13** [comment]
@srv-twry My past experiences with its own application has educated me that it sometime reaches the size of nearly 60 Mb. But as you mentioned that it will enabled only for the debug build, then sure you must go ahead with it.

**Comment by rashiq** [comment]
I love Leak canary! Would definitely like to have it. Especially since it wouldn't introduce any run time dependencies. Just for the dev builds.

**Comment by srv-twry** [comment]
@rashiq @mhutti1 Alright, I will send in the PR shortly
