### ISSUE TITLE
Position of the cancel search button (X) must be aligned to the right

### ISSUE THREAD

**Issue by Koundinyalanka** [kiwix/kiwix-android#365]
![screenshot_20180213-201457](https://user-images.githubusercontent.com/23225734/36155739-3024153c-10fb-11e8-9fd3-c4f613915f33.png)

**Comment by Koundinyalanka** [comment]
Resolved this issue by using setMaxWidth
![screenshot_20180215-092349](https://user-images.githubusercontent.com/23225734/36239775-4640069a-1232-11e8-81c4-05da83f45474.png)

**Comment by kelson42** [comment]
@Koundinyalanka Could you please give the link of the PR for that ticket please?

**Comment by mhutti1** [comment]
@Koundinyalanka are you still working on this?

**Comment by abdulwd** [comment]
Close via #642.
