### ISSUE TITLE
When we pick any ZIM file via file picker then it is not adding into library screen.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3650]
**Describe the bug**
If user devices have lots of files in storage, our scanning takes time to list the ZIM file on the library screen. If the user selects the ZIM file via file picker then also it is not showing in the library screen because it does not remember the opened file via file picker (All the other actions are working fine e.g. opening this file from bookmark, history etc).
Only scanning is responsible for showing the ZIM files on the library screen. 
A user is experiencing this issue on his device see https://github.com/kiwix/kiwix-android/issues/3646 for more details.

**Expected behavior**
If a user selects the ZIM file via file picker it should remember that file and should be listed on the local library screen since our app already knows this file exists in the file system.

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : Any device.
- OS version : Any android version.

**Comment by kelson42** [comment]
@MohitMaliFtechiz You misunderstand the problem and makes link which are unrelated. If we know about a ZIM file (which is the case here because file is open via filepicker) then it has to be remembered in local library.... this whatever the scanning does or doen't do. This is why this us a bug.

**Comment by MohitMaliFtechiz** [comment]
> If the app knows about a ZIM file (which is the case here because file is open via filepicker) then it has to be remembered in local library.

@kelson42 Thanks for additional clarification, I think the issue description is a little short to explain, I have updated the description.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Its obvious and is probably already handled, but duplicated entries in local library... in any cases. Shoild be anyway trivial to implement.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 We have placed a fix for it in https://github.com/kiwix/kiwix-android/pull/3652.  To slow down the scanning progress i have created 20K dummy files in my device, for proper testing of this scenario, everything working fine. I have put a video on the PR description.
