### ISSUE TITLE
Clear Search Button in Reading

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3658]
**Is your feature request related to a problem? Please describe.**

I searched for a query and found the results but after that, I wanted to clear the search and get the whole list. Sadly, there was no button to clear the search filter and get back to the default state.
![photo_6107086600765814465_y](https://github.com/kiwix/kiwix-android/assets/85388413/13643c88-2412-4350-91ff-f90bd0254576)

**Describe the solution you'd like**

When we have the same query we can have the clear button instead of the search button. 

**Describe alternatives you've considered**

An alternative could be to use the cross(x) button in the text field to clear the search query and list.

**Comment by Sagar0-0** [comment]
Should I start working on it?

**Comment by kelson42** [comment]
This is not the right repository to report this feature request. It should be in "openzim/gutenberg".

**Comment by Sagar0-0** [comment]
I mean this is UI related issue, right?

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 This is not the Kiwix UI-related issue. This search is performed inside the ZIM file so the solution will be placed inside the ZIM file. I think we should move this ticket to "openzim/gutenberg" as @kelson42 mentioned.

**Comment by kelson42** [comment]
Kamino closed and cloned this issue to [openzim/gutenberg](https://github.com/openzim/gutenberg/issues/215)
