### ISSUE TITLE
Application crashes by libzim_wrapper.so] Java_org_kiwix_libzim_Archive_getEntryByPath 

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3662]
**Describe the bug**
Reported by google playstore from phet
**Expected behavior**

**Screenshots**

**Environment**
- Version of Kiwix Android : 
- Device : Samsung m51
- OS version : Android 12

**Logs**
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 16358 >>> org.kiwix.kiwixcustomphet <<<

backtrace:
  #00  pc 0x000000000000fa78  /data/app/~~WsT91eLMY2R6XQrHktQY0w==/org.kiwix.kiwixcustomphet-xmDIwWVjWWwscLXdlwyanA==/split_config.arm64_v8a.apk!libzim_wrapper.so (Java_org_kiwix_libzim_Archive_getEntryByPath__Ljava_lang_String_2+120) (BuildId: 6c0d6ee977af86c7d817e067ec4176543043faa4)
  #01  pc 0x000000000009f530  /data/app/~~WsT91eLMY2R6XQrHktQY0w==/org.kiwix.kiwixcustomphet-xmDIwWVjWWwscLXdlwyanA==/oat/arm64/base.odex (art_jni_trampoline+128)

```

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda it seems the duplicate of https://github.com/kiwix/kiwix-android/issues/3638. In #3638 there are more logs I have added on the ticket description that are reported by the playstore.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Thanks! I didn't look at the second log.
