### ISSUE TITLE
Complete verification of Playstore account

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#3664]
![Screenshot 2024-01-09 at 18 36 36](https://github.com/kiwix/kiwix-android/assets/43576162/f6e89008-6a67-44bc-866f-a7c61566a9fb)
It starts from the June 6 2024

**Comment by kelson42** [comment]
@gouri-panda Which account is not verified?

**Comment by gouri-panda** [comment]
@kelsom42  https://play.google.com/console/u/0/developers/9116215767541857492/contact-details

**Comment by Popolechien** [comment]
That's kind of odd that they put this out so early while also saying that verification can only be done after 6 June 2024.

**Comment by kelson42** [comment]
We will see when we are so far. Seems to early to bother and act on this.
