### ISSUE TITLE
Unexpected Texts in Reader

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3667]
**Describe the bug**

The text is unexpected and maybe because of some issue

**Expected behavior**

The real human-readable text

**Steps to reproduce the behavior:**
1. Go to reader and open a book

**Screenshots**

![photo_6129545036296206225_y](https://github.com/kiwix/kiwix-android/assets/85388413/1450e620-bbb6-4dbe-bfd7-db0f7e8bef7e)

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : Realme GT NEO 3T
- OS version : 13

**Logs**

**Comment by kelson42** [comment]
@Sagar0-0 Which ZIM file is that?

**Comment by Sagar0-0** [comment]
Budding Authors is the name of file I downloaded, and I can still reproduce it.

**Comment by satvik2131** [comment]
![Screenshot from 2024-01-17 12-23-31](https://github.com/kiwix/kiwix-android/assets/59243339/2cc422e5-7129-4536-ae8f-032dc83f5fbb)
Is this what needs to be done ? @Sagar0-0

**Comment by Sagar0-0** [comment]
Video will be more understandable

**Comment by Sagar0-0** [comment]
I believe It is only related to the Budding Authors ZIM file.

**Comment by kelson42** [comment]
Kamino closed and cloned this issue to [openzim/nautilus](https://github.com/openzim/nautilus/issues/66)
