### ISSUE TITLE
Refactor KiwixMobileActivity class to reduce it's size

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#367]
**Description**

The ```KiwixMobileActivity``` class is huge(2005 lines). Having such a huge class makes it tough to manage it. We can move some of the code to ```KiwixMobileActivityUtility``` or ```KiwixMobileActivityRepository``` class(Need to create them) if possible. I haven't looked at it in detail but will look at it very soon !

@mhutti1 @kelson42 What do you think ?

**Comment by mhutti1** [comment]
We already have some issues open about refactoring. I am not sure how up to date some of them are though. I would suggest looking into them first. https://github.com/kiwix/kiwix-android/issues?utf8=%E2%9C%93&q=refactor

**Comment by srv-twry** [comment]
Closing as it is already covered in #29
