### ISSUE TITLE
Suspend F-droid store

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3672]
F-droid is currently presenting users with Version 2.4, which seems to cause a lot of issues for users. While I understand a new version is on its way, it has been so for months if not years and this is damaging to the brand. Better pull out and re-add when ready.

**Comment by Jaifroid** [comment]
Alternatively, link to the izzydroid F-Droid version (3.8.0) as outlined in this issue: https://github.com/kiwix/kiwix-android/issues/3651.

**Comment by kelson42** [comment]
I'm in favour of a suspension if possible. Not in favour of removal and then adding again. We should really remove ObjectBox in February and be back with recent version in FDroid.

**Comment by Jaifroid** [comment]
Is ObjectBox now removed in a released version, or is that still pending, and if so, which release?

**Comment by kelson42** [comment]
no, its not. One of the two main topics for milestone 3.11.

**Comment by kelson42** [comment]
@MohitMaliDeveloper Please go forward and ask suspension to fdroid

**Comment by kelson42** [comment]
Done
