### ISSUE TITLE
Search results bug in both 3.9 and 3.9.1

### ISSUE THREAD

**Issue by ramko93** [kiwix/kiwix-android#3698]
**Describe the bug**

**Expected behavior**

**Steps to reproduce the behavior:**
1. 

**Screenshots**

**Environment**
- Version of Kiwix Android : 
- Device : 
- OS version : 

**Logs**

If I searched for 'bo' and many other phrases within the 78 gb wiki file on sd card of Samsung tAb s7 plus android 13 I'm getting very few results ![Screenshot_20240214_101830_Kiwix.png](https://github.com/kiwix/kiwix-android/assets/56144733/d76d8a1a-c490-408b-b6b1-e17619da0d9a)

![Screenshot_20240214_101830_Kiwix.png](https://github.com/kiwix/kiwix-android/assets/56144733/718c3d1c-9c3b-498e-92d5-7846b7017f99)

![log.docx](https://github.com/kiwix/kiwix-android/files/14275444/log.docx)

**Comment by kelson42** [comment]
@ramko93 You mean Wikipedia in English? What other results to you expects?

**Comment by ramko93** [comment]
I used to get 2 page of results

**Comment by kelson42** [comment]
OK, there nothing clear you are missing?

**Comment by ramko93** [comment]
File is from 2018

**Comment by ramko93** [comment]
![Screenshot_20240214_114135_Settings.png](https://github.com/kiwix/kiwix-android/assets/56144733/1828f1b9-14b3-4e06-9130-7490864647a8)

**Comment by ramko93** [comment]
Native os not modified or rooted

**Comment by ramko93** [comment]
But Search is just fine with the Kiwix extension on my kiwi browser!
But it doesn't show side menu on any article what a bummer!
Could you just take it as a feature request

**Comment by kelson42** [comment]
@ramko93 Your ZIM file is really old and we have changed many things in the meantime, please check again with a recent version of the ZIM file.
