### ISSUE TITLE
objectbox start working after 3 days

### ISSUE THREAD

**Issue by RjMakwana2660** [kiwix/kiwix-android#3712]
**Problem**
I have got to know from users using my app that the data which they are using from objectbox stops working after almost 3 days.
I have mechanism which syncs data from my source to the objectbox which is failing after the duration of 3 days.
is there any issue with write permission for objectbox after 3 days or something
Guidance needed.

**Comment by kelson42** [comment]
Wrong repository, we don't provide help about objectbox.
