### ISSUE TITLE
 Selected files count is not showing initially in LocalLibrary screen.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3715]
**Describe the bug**
If we select any zim file in the LocalLibrary screen for sharing or deleting initially it does not show the numbers in the toolbar of selected zim files.

**Expected behavior**
It should show the number of selected zim files initially.

**Steps to reproduce the behavior:**
1. Long press on any ZIM file in the LocalLibrary screen
2. In the toolbar you will not see the numbers of selected zim files
3. but if you select one more zim file then it will start showing how many zim files are selected.

https://github.com/kiwix/kiwix-android/assets/34593983/6b7d5df6-790a-4576-b58d-7f3ff323f5fe

**Environment**
- Version of Kiwix Android: 3.9.1
- Device: Google Pixel 7a.
- OS version: Android 13

**Comment by HimanshuMahto** [comment]
is this still open to work on.

**Comment by MohitMaliFtechiz** [comment]
@HimanshuMahto Thanks for showing interest but the fix is placed for this issue in https://github.com/kiwix/kiwix-android/pull/3716.

**Comment by HimanshuMahto** [comment]
Ok
