### ISSUE TITLE
Bookmark screen title is set as `Kiwix` if we open the `Bookmarks` screen from Widget.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3718]
**Describe the bug**
If we open the bookmark screen from our app widget then the bookmark screen title shows wrong. It shows the "Kiwix" as the bookmark title instead of the Bookmark.

**Expected behavior**
It should show the `Bookmark` on the title instead of `Kiwix`.

**Steps to reproduce the behavior:**
1. Add kiwix widget on your home screen.
2. Click on the bookmark icon on the widget.
3. It will open the bookmark screen.
4. See the screen title.

**Environment**
- Version of Kiwix Android: 3.9.1
- Device: Google Pixel 7a
- OS version: Android 13

https://github.com/kiwix/kiwix-android/assets/34593983/2fbbe806-c363-41c1-b4a6-3bca2a3e9a17

**Comment by HimanshuMahto** [comment]
hey there, can i work on this issue
