### ISSUE TITLE
Proposal: Create a bot for the organisation.

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#373]
**Proposal**

Most of the open-source organisations these days have a bot to manage things like assigning, unassigning developers. Adding labels like "In-Progress" etc.

OpenDataKit - opendatakitbot handles labelling/unlabelling of issues and pr's using commands.
 You can claim an issue using it. 
It automatically assigns developers and shows a welcome message if it's your first contribution to the project. 
It automatically un-assigns the developer in 7 days if there isn't any activity associated with it. 
[Here](https://github.com/opendatakit/collect/issues/1859) is an example issue and how it works.

Other organisations such as Fossasia also have their bots.

This will be very helpful in the long run specially with GSoC round the corner.

@mhutti1 @kelson42 Please review.
PS: I don't know how to make one but i can certainly ask them if it seems interesting to you.

**Comment by kelson42** [comment]
@srv-twry Thank you for this idea. It would be great IMO if you could complete your ticket by explaining quite clearly which problem(s) this solution should give an answer to.

**Comment by srv-twry** [comment]
1. Ability to claim an issue and assign it to yourself by using something like ```@kiwixbot-claim```.

2. Automatically unassign the developer if there isn't any update in 7/10 days.

3. Label the issues which have a PR with label "has-PR" as soon as a linked PR is opened.

4. As soon as a PR is opened, label it ```needs-review```. As soon as it is approved, automatically label it ```reviewed``` or ```approved``` or even ```needs-testing``` if we want every PR to be tested by the community.

5. If a developer claims the issue for the first time i.e. his/her first ever claim, show him/her a good welcome message with links to contribution guidelines etc.

This is what i could think of so far. Other's can also suggest something :smile: .

**Comment by siddharth2010** [comment]
Hi everyone, I am siddharth sharma. I was checking out the community and I really liked what you guys are doing here. I also loved the idea to download ted talks... Actually a few years earlier, when I didn't have good internet connectivity at home, I used to do the same thing, download these articles and then read them offline...

I found this issue really intriguing. I was wondering if you wanted something like a chatbot that works on gitter or slack and that can do all of the tasks like assigning an issue, unassigning an inactive issue, label issues with corresponding PR's and also label other PR's (need review, etc.), basically all the basic tasks... Also I can integrate Natural language processing and internet scraping that will help in referencing some code from stackoverflow... I would really like to work on this as my gsoc project...

I would really like to know your views on whether this will be beneficial to the community, and should I work on this as my gsoc project.

I have done some research and found the err-bot python library apt for this. I could set up a prototype for this in a few days if you want.

I have also sent an email regarding this in the gsoc mailing list.

Thanks a lot!

**Comment by srv-twry** [comment]
@siddharth2010 Hi, 
I think you've misunderstood what i've proposed in this issue. The aim of this issue is to create a simple github application which will do all these things(Should hardly take couple of days to a week at max). 

> I was wondering if you wanted something like a chatbot that works on gitter or slack and that can do all of the above tasks

Why do we need a chatbot for it when github supports this ? BDW i think we already have a bot on IRC. I would suggest you please look at the linked example that i have given in my issue to get a better understanding of what i am proposing here.

> Also I can integrate Natural language processing and internet scraping that will help in referencing some code from stackoverflow

Sorry didn't get the use case here. Can you please elaborate a bit more ?

>  I would really like to work on this as my gsoc project.

IMO developing something like this that wouldn't affect the user community isn't a good idea as a GSOC project. Right now the organisation is new and the aim should be to expand the user community by developing features in the app/library in order to make the user's life easier. We can take care of integrating developer tools after we have achieved our primary goals.


PS: I am not a mentor, i am just a contributor hence don't take my word for everything. Whatever i have expressed above is meant to be taken as a suggestion. I would wait for mentors to confirm if this is a good idea for GSOC project or not.

**Comment by mhutti1** [comment]
@siddharth2010 While I think this would be useful, I don't think it would be the best use of a GSoC project as many other projects would have more of an impact and we will only be allocated so many slots from Google especially as we are a first time org.

**Comment by siddharth2010** [comment]
I guess you all are right. This is not really the best use of GSoC. And @srv-twry , I just checked out the link and I understand the idea now. The idea I had in mind was too complicated. And most of the functionality is already there in the freenode bot. So my idea is not really the best one to implement right now...
Thanks a lot for your suggestions!

**Comment by mhutti1** [comment]
@kelson42 This should be moved to kiwix/overview
