### ISSUE TITLE
[Bug] Read aloud feature does nothing

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3739]
**Describe the bug**

THe read aloud feature in the reader does nothing when we try to read a file,(notification permissions were not granted)

**Expected behavior**

It should pop up the dialog to ask for notification persmission

**Steps to reproduce the behavior:**
1. Turn off notification permission
2. Open any zim file in reader
3. Click on 3 dots at top right cornet
4. Click on Read aloud option, it will do nothing
-->

**Screenshots**

https://github.com/kiwix/kiwix-android/assets/85388413/75035cda-677e-4e3d-894f-619d48824484

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : REALME GT
- OS version : 13

**Logs**

**Comment by kelson42** [comment]
@Sagar0-0 Thank you for your bug report, can you please try if your are still suffering of that bug using latest nightly build? https://download.kiwix.org/nightly/2024-03-10/kiwix-universal-2024-03-10.apk

**Comment by kelson42** [comment]
@Sagar0-0 Can you please open a dedicated bug for that new one? I will close that one.
