### ISSUE TITLE
App keeps crashing (Tecno Spark 4)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3749]
User report, I'll try to have them confirm their android and kiwix version, but feel free to close if ticket hasn't been updated in a week or so:

_I download the app from Google play store and after installing when I try to open the app it keeps saying" app keeps stopping". What can I do now?my phone model is techno spark 4 with 32 GB storage and now has more than 4 GB storage._

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can we do anything with this ticket?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have checked this device's crash logs in the play console it has the `armeabi-v7a` architecture, and these crash logs are the same as we are facing in the https://github.com/kiwix/kiwix-android/issues/3661.

![Screenshot from 2024-03-12 18-41-17](https://github.com/kiwix/kiwix-android/assets/34593983/0dd5ded0-15aa-46f7-8a1f-debb16495159)

![Screenshot from 2024-03-12 18-43-59](https://github.com/kiwix/kiwix-android/assets/34593983/e02a7097-a5d2-4d26-8704-c3e88719f04f)
