### ISSUE TITLE
Replace PNG files with XML ones

### ISSUE THREAD

**Issue by brijeshshah13** [kiwix/kiwix-android#375]
**Description**

Currently, there are a lot of `png` files which contribute to increase in `apk` size. Replacing possible ones with `xml` files would be better approach towards saving space and backward compatibility.

**Would like to work on this issue?**
Yes.

@mhutti1 Please share your suggestions.

**Comment by kelson42** [comment]
@brijeshshah13 Do you mean SVG files? If "yes" do we know how would that impact the rendering time?

**Comment by brijeshshah13** [comment]
In a way, yes. Because SVG files are stored as XML file formats. This [link](https://watb.co.uk/5-reasons-you-should-be-using-svgs-over-pngs/) might answer your question about the impact on rendering time. Your review please.

**Comment by kelson42** [comment]
@brijeshshah13 Thx for the link. Looks good to me but pleas wait approval of @mhutti1.

**Comment by brijeshshah13** [comment]
@kelson42 Yes sure😃

**Comment by mhutti1** [comment]
@brijeshshah13 This sounds like a good idea.

**Comment by brijeshshah13** [comment]
@mhutti1 Thank you. Will start working on it right away.

**Comment by brijeshshah13** [comment]
@mhutti1 Shall I add `vectorDrawables.useSupportLibrary = true` as stated [here](https://developer.android.com/guide/topics/graphics/vector-drawable-resources.html#vector-drawables-backward-solution) to support vector drawable for backward compatibility?

**Comment by brijeshshah13** [comment]
I guess we should add it nevertheless for future compatibility. And please acknowledge me if I should change some icons to adhere to the Google's Material Design Guidelines such as `fullscreen` icon, etc.?

**Comment by mhutti1** [comment]
@brijeshshah13 Yeah we should be adhering to material design within reason so if you want to fix those make a pull request.

**Comment by brijeshshah13** [comment]
@mhutti1 On it. Will send the PR shortly after the final touch up.

**Comment by brijeshshah13** [comment]
The size of the `fullscreen_exit` has been decreased to allow users to better view the content. Is this okay? @mhutti1 

![screenshot_20180214-200932](https://user-images.githubusercontent.com/18366144/36209928-2314a64a-11c3-11e8-87dd-1b917b639096.png)

**Comment by kelson42** [comment]
@mhutti1 Any feedback? Looks ok to me to reduce a bit the size of the logo.

**Comment by abdulwd** [comment]
@brijeshshah13 @kelson42 May I help? I have done this type of refactoring multiple times.

**Comment by kelson42** [comment]
@abdulwd This task is assigned and Afaik mostky waiting a review of the PR

**Comment by abdulwd** [comment]
Okay. :)

**Comment by abdulwd** [comment]
@mhutti1 It's done. It took me time as my laptop was not working. Vectors can be used from API 7, our minSdkVersion is 14. So the changes will work.
