### ISSUE TITLE
[Improvement] File drawer in Tabs screen

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3754]
**Describe the bug**

File drawer is accessible in the Tabs screen which is not valid or required.

**Expected behavior**

If should not be accessed by swiping from right

**Steps to reproduce the behavior:**
1. Go to tab switcher and swipe from right side

**Screenshots**

![00dc0d19-827e-408c-a688-c8959c1c72f0](https://github.com/kiwix/kiwix-android/assets/85388413/5fae9a96-48b0-4cc7-a35c-56475182a779)

**Environment**
- Version of Kiwix Android : 3.9.0
- Device : REALME GT
- OS version : 13

**Logs**

**Comment by kelson42** [comment]
@MohitMaliDeveloper Domyou understand the bug? confirm it?

**Comment by Sagar0-0** [comment]
You can simply open the zim drawer(from right side) in tab switcher. I want to restrict it, as it's having no use in tab switcher

**Comment by Sagar0-0** [comment]
@kelson42 @MohitMaliDeveloper if you got the idea here, then let me know I will start working on it.

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 Thanks for opening the issue, and finding a good enhancement. 

> as it's having no use in tab switcher

The right tab switcher acts on the currently selected tab even if the tabs are active user can select the items from the side drawer when the tab switcher is active. But yes it should not show the right drawer when the tabs are showing to improve the user experience.

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 I have assigned this issue to you. Please make sure the right drawer should re-appear properly with the currently selected tab(with content) after the tab switcher is closed in both modules (app and custom).

**Comment by Sagar0-0** [comment]
Is the logic for this drawer present in both (app, custom) modules? If yes, then why?

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 Any update on this?

**Comment by Sagar0-0** [comment]
Couldn't find the actual logic to disable the opening and closing of drawer

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 OK, thanks for trying i will look into it and place a fix for it.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Coukd you please implement
