### ISSUE TITLE
Processing of special characters / URL encoded links is not working as expected

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-android#3755]
**Description**

See https://github.com/openzim/libzim/issues/865#issuecomment-2003154791 for details. We should probably wait for discussion to settle in this issue before developing some on Android, but we most probably have to fix something on Android.

We have a test ZIM at https://tmp.kiwix.org/ci/zim_characters_encoding/characters_encoding.zim with many situations in terms of URL encoding inside an HTML document and corresponding ZIM entry path.

Current Android reader behavior is not aligned with kiwix-serve behavior and will probably have to aligned (again, once discussion on https://github.com/openzim/libzim/issues/865 has settled) :
- many links are not working while they should (at least they work in kiwix-serve)
- some links are working but not leading to the proper ZIM entry (at least the one which is served by kiwix-serve on web browser desktop)

**Environment**
- Version of Kiwix Android : 2024-03-17 nightly
- Device : Fairphone 4
- OS version : 13

**Comment by kelson42** [comment]
@MohitMaliFtechiz Very serious bug/topic, please look in priority. I can only insist again than URL parsing should be solid and well tested.

**Comment by MohitMaliFtechiz** [comment]
@benoit74 Thanks for providing the ZIM file, we have refactored our code to support the URLs in our application at https://github.com/kiwix/kiwix-android/pull/3768. Now it is working like `kiwix-server`.

**Comment by benoit74** [comment]
Great ! I just had a look at the video in PR and confirm the new behavior is exactly as expected. Glad a great test case / ZIM helped to solve this complex topic so fast!

**Comment by MohitMaliFtechiz** [comment]
@benoit74 Thanks for giving your feedback.

**Comment by benoit74** [comment]
I've installed last nightly and can confirm it works as expected from my PoV.
