### ISSUE TITLE
Deprecated dependency configurations in use

### ISSUE THREAD

**Issue by brijeshshah13** [kiwix/kiwix-android#376]
**Actual Behaviour**

Deprecated dependency configurations such as `compile`, `testCompile` and `androidtestcompile` in use.

**Expected Behaviour**

Replacements are as below:
`compile` -> `implementation`
`testCompile` -> `testImplementation`
`androidTestCompile` -> `androidTestImplementation`

**Steps to reproduce it**

Check `kiwixlib` level `build.gradle` file.

**LogCat for the issue**

N/A. Just Warnings.

**Would you like to work on the issue?**

Yes. M on it.

@mhutti1 Please review.

**Comment by mhutti1** [comment]
kiwix-lib is a bit of a special case. It is built using the kiwixlib repo but we don't currently have an easy process to deploy new versions to the dev repo. Lets keep the issue open but its not worth looking at until we refine this process,

**Comment by brijeshshah13** [comment]
@mhutti1 Okay. Well, ping me in case you decide to resolve this.

**Comment by abdulwd** [comment]
This should be close via #478.
