### ISSUE TITLE
[Improvement] Find in Page button ripple

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3764]
**Describe the bug**

The ripple is circular

**Expected behavior**

It should be for whole Text

**Steps to reproduce the behavior:**
1. Go to search and click on Find in Page

**Screenshots**
![photo_6332481309024303644_y](https://github.com/kiwix/kiwix-android/assets/85388413/3126a8d9-443a-4ef4-8f84-7840406bc497)

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : REALME
- OS version : 13

**Logs**

**Comment by kelson42** [comment]
@MohitMaliDeveloper You confirm this makes sense? Why this has not been done that way in a first place?

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 How do you propose to implement this? 

> @MohitMaliDeveloper You confirm this makes sense? Why this has not been done that way in the first place?

Yes, it makes sense it will improve the UX. The default behavior of ripple in the menu item is a circle which is enough to notify the user that this button is clicked which is the purpose of this ripple effect that's why it never came into focus.

**Comment by Sagar0-0** [comment]
> @Sagar0-0 How do you propose to implement this?

I can create a custom Ripple for the textbutton and use it.

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 Please make a PR with your changes.

**Comment by Sagar0-0** [comment]
I have added the functionality but clicking on it is not doing anything, can you help me with adding the actionlayout into the code

**Comment by MohitMaliFtechiz** [comment]
@Sagar0-0 Can you please create a PR so that i can help you.

**Comment by Sagar0-0** [comment]
@MohitMaliFtechiz please review the PR.
