### ISSUE TITLE
Upgrade Minimum SDK version to 25

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3783]
**Describe the bug**
We have an issue with API level 24. This API level does not trust the [Let's Encrypt](https://letsencrypt.org/docs/certificate-compatibility/) `ISRG Root X1`. We have added a hack in https://github.com/kiwix/kiwix-android/issues/3772 to support this API level. 

**Expected behavior**
We should upgrade our minimum SDK to API level 25, since [1.3% of devices](https://www.composables.com/tools/distribution-chart) that are using the API level 24.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please implement this issue right now. Modify kiwix/java-libkiwix is needed as well.
