### ISSUE TITLE
CI Take a long time to run

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-android#3784]
It appears that the CI take a long time to run.

See for example (just picking some random run for `CI` workflow):
- https://github.com/kiwix/kiwix-android/actions/runs/8612957727?pr=3782 (failed in 2h12m)
- https://github.com/kiwix/kiwix-android/actions/runs/8614306925?pr=3782 (succeed in 50minutes)
- https://github.com/kiwix/kiwix-android/actions/runs/8599745067?pr=3770 (failed in 3h4m)
- https://github.com/kiwix/kiwix-android/actions/runs/8570616944?pr=3782 (failed in 6h30m)
- https://github.com/kiwix/kiwix-android/actions/runs/8553991850?pr=3782 (succeed in 4h26m)
- https://github.com/kiwix/kiwix-android/actions/runs/8549651284?pr=3780 (cancelled after 7h11m)

On top of that, the CI workflow is composed of 3 jobs using macos builders and is run for each PR update.

The macos builder is limited to 5 per organization. This means that few PRs updates can trigger a lots of CI job on macos which can (and do) block other projects using macos builder (without saying that android devs just have to wait hours before see the CI green)

Please, see how you can reduce that. I would suggest :
- Fix workflow to not take such long (and cannot see how building kiwix-android can take hours)
- Don't run CI workflow on pull request
- Run less jobs per workflow
- Run CI workflow on ubuntu workers (20 workers per organization)
- Limit the number of jobs run in parallel (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel)
- Cancel running jobs if one of them fails (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast)

**Comment by MohitMaliFtechiz** [comment]
@mgautierfr Thanks for opening the issue and suggesting the changes. We are working on this issue to reduce the CI timing, and we have reduced the CI timing in https://github.com/kiwix/kiwix-android/pull/3782.

> Cancel running jobs if one of them fails (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast)

We tried it in #3782 see https://github.com/kiwix/kiwix-android/actions/runs/8567414969, but at that time we reverted this change. But I think you have a valid point, if a CI fails then running it on other APIs does not make sense. @kelson42 What do you think?

> Don't run CI workflow on pull request
Run less jobs per workflow

@kelson42 What do you think about this?

**Comment by kelson42** [comment]
> We tried it in #3782 see https://github.com/kiwix/kiwix-android/actions/runs/8567414969, but at that time we reverted this change. But I think you have a valid point, if a CI fails then running it on other APIs does not make sense. @kelson42 What do you think?

OK

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Here is the concurrent limit of workers in GitHub action https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits, they do not explicitly mention the limit of Linux runner but the total concurrent limit is 20(probably this is for linux) and concurrent limit for `macOs` is 5. But one more reason to move on to the Linux runner is performance https://github.com/actions/runner-images/issues/1336#issuecomment-741932436. As described in https://github.com/actions/runner-images/issues/1336 macOs runners are slow compared to Linux runners.
