### ISSUE TITLE
Adding  a Sharing button

### ISSUE THREAD

**Issue by Ananthusubramanian** [kiwix/kiwix-android#379]
Adding a sharing button would increase the user experience of the app ,so that app becomes available to new users.
![screenshot_2018-02-14-20-38-08-090_org kiwix kiwixmobile](https://user-images.githubusercontent.com/22250995/36211382-2034db76-11c7-11e8-909c-273a8c6b67c4.png)

**Comment by pprathameshmore** [comment]
I am trying to Share Button in Menu Options

**Comment by pprathameshmore** [comment]
Hey Please help!
I am added button share button in Menu Option. But I don't know how to commit main repo.

**Comment by kelson42** [comment]
@pprathameshmore You need to make a pull request, here is explained how https://help.github.com/articles/creating-a-pull-request/

**Comment by pprathameshmore** [comment]
Thank you! Okay I will try!

**Comment by RajaVamsi11** [comment]
Can i work on this issue?

**Comment by mhutti1** [comment]
@pprathameshmore  is already working on it https://github.com/Ananthusubramanian/kiwix-android/commit/dca58c2891092927178c72efc3b6cdf868dc38be

**Comment by RajaVamsi11** [comment]
ok.I will search for another issue.

**Comment by abdulwd** [comment]
Link to download the app can be shared from the PlayStore so there is no need to have an explicit share button.
