### ISSUE TITLE
Support Chinese variant conversion markers

### ISSUE THREAD

**Issue by DeepChirp** [kiwix/kiwix-android#3799]
**Is your feature request related to a problem? Please describe.**

Since both Simplified Chinese and Traditional Chinese use the Chinese Wikipedia, different Chinese variants are provided simply through the site's word conversion feature. At the same time, kiwix only provides the Chinese version of Wikipedia and does not provide its variants. The word conversion function uses some special tags, but they cannot be applied correctly in this software and some content cannot be displayed.

An example: [`阿波罗计划` (Project Apollo) on Chinese Wikipedia](https://zh.wikipedia.org/wiki/%E9%98%BF%E6%B3%A2%E7%BD%97%E8%AE%A1%E5%88%92). In the first paragraph, the `-{}-` mark is used to indicate the display content under different Chinese variants, but in kiwix, this content disappears directly. This may affect the reader's reading experience.

Additionally, allowing readers to use their preferred variant of Chinese will make reading easier. Currently, various Chinese variants are mixed together, making it difficult to read. At the same time, some users both using Chinese and kiwix have complained about this.

**Describe the solution you'd like**

Added Chinese variant conversion function.

**Describe alternatives you've considered**

Provide zim files of different Chinese variants for users to download.

**Additional context**

[A documentation on Chinese Wikipedia](https://zh.wikipedia.org/wiki/Help:%E4%B8%AD%E6%96%87%E7%BB%B4%E5%9F%BA%E7%99%BE%E7%A7%91%E7%9A%84%E7%B9%81%E7%AE%80%E3%80%81%E5%9C%B0%E5%8C%BA%E8%AF%8D%E5%A4%84%E7%90%86) describes how word conversion works. If add conversion functionality, this article should be useful.

**Comment by kelson42** [comment]
@DeepChirp Thank you for your bug report, but the handling of the content is done in specfic scraper code repositories. In fact I suspect that your ticket is a duplicate of https://github.com/openzim/mwoffliner/issues/840

**Comment by DeepChirp** [comment]
> @DeepChirp Thank you for your bug report, but the handling of the content is done in specfic scraper code repositories. In fact I suspect that your ticket is a duplicate of [openzim/mwoffliner#840](https://github.com/openzim/mwoffliner/issues/840)

Sorry, I didn't search in this repository you mentioned. I just searched in the app's library and found no results. I will close this duplicate issue.
