### ISSUE TITLE
Search in Chinese

### ISSUE THREAD

**Issue by cmd-rm-rf** [kiwix/kiwix-android#3816]
**Describe the bug**
When search in Chinese, it can only match when the words is single character, if you input more than one chinese characters in the search box, it says that no match.

**Expected behavior**
when input more than one chinese character, there will also be right result instead of no match

**Steps to reproduce the behavior:**
1 let's try "舊唐書"
2 just input 舊, it will show result
3 now input 舊唐書，this is 3 chinese characters, there will be no reslut

**Screenshots**
![Screenshot_20240502-104144_Kiwix](https://github.com/kiwix/kiwix-android/assets/152496521/8c5c8f53-1173-4a96-8e0e-54877d2dd6c9)
![Screenshot_20240502-104208_Kiwix](https://github.com/kiwix/kiwix-android/assets/152496521/71f73fbf-7479-4926-b3ca-d8cd5102fc6d)

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : Redmi K60
- OS version : A13

**Comment by kelson42** [comment]
@cmd-rm-rf Thank you for your bug report. This is a known issue with Wikimedia content. Actually the problem is that the scraper still relies on an older version of our core library libzim. This will be fixed in the next months. But for now there is nothing we can do here.

**Comment by ljj314zz** [comment]
Is there any progress on this issue?

**Comment by tedaz** [comment]
As of version 3.12.0, this issue still unfixed.

**Comment by Serenaishere** [comment]
May have a online version of Kivix can search by Chinese?The desktop version can't acheive the goal.

**Comment by lizy14** [comment]
updating ZIM file worked for me. https://github.com/kiwix/kiwix-android/issues/4049#issuecomment-4002151601
