### ISSUE TITLE
Library language selection box is too slow to display

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#383]
With the development version:
1 - Go the library
2 - Open the online tab
3 - Click on the "globe" icon in the top-right corner

What I get:
After many seconds the dialog box listening the languages appears

What I want:
This should be displayed almost instantly.

Remark:
If I try to scroll down just after the list appears... then I might even achieve to make the app crash. It seems the whole stuff is not really robust and "efficiently" coded. I suspect that list should be built in background during the library parsing. Not "on the fly" like it seems to be the case today.

**Comment by sashank27** [comment]
I want to work on this.

**Comment by mhutti1** [comment]
@sashank27 Go ahead. Some tips:
@kelson42 does this occur every launch or just on first install?
For me if you try click the globe for the first time it displays an empty box and doesn't load unless you reload it.

**Comment by kelson42** [comment]
@mhutti1 It always happen. Looks like the CPU of my table is simply not strong enough to display it quickly.

**Comment by kelson42** [comment]
The empty box bug has been reported here #389

**Comment by arpank10** [comment]
I think unless the books are loaded, the languageCount remains zero, so the languages are still not added to the languages list due to this line in updateLanguages() in LibraryAdapter.java

> if (languageCounts.get(locale.getISO3Language()) != null) 

Hence the empty dialog box.

**Comment by kelson42** [comment]
The empty dialog box has been fixed, but the rest of the problem is still there.

**Comment by arpank10** [comment]
@kelson42 The code is written in such a way that unless we get the languages count, the dialog box would remain empty or in this case not display, and whenever we click the globe everytime `Locale.getISOLanguages()` returns a list of languages. All those languages are checked then if they are in languageCount list. I think in your case, this is where it gets slow.

**Comment by abdulwd** [comment]
@mhutti1 This is made redundant by the new language activity in #774.
