### ISSUE TITLE
Zim files are not opening with kiwix when clicking from the storage.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3832]
**Describe the bug**
Zim files are not opening with kiwix when clicking from the storage. However, externally downloaded zim files open in kiwix if we click on those zim files e.g. chrome download screen.

**Expected behavior**
It should open the zim files with Kiwix if we click on the storage.

https://github.com/kiwix/kiwix-android/assets/34593983/150b6939-5209-43d4-87aa-4215d274bc6e

**Comment by triffid** [comment]
> Zim files are not opening with kiwix when clicking from the storage.

I'm experiencing this in 3.11.0, should I open another bug?

I've manually told my file explorer to open them with kiwix, but the kiwix app just throws a toast that says:
```
Failed to open file
Please try looking for this file in the Device Tab of your Library
```

But I don't see any device tab in Library?

**Comment by kelson42** [comment]
> Zim files are not opening with kiwix when clicking from the storage.\n\nI'm experiencing this in 3.11.0, should I open another bug?

Yes please.
