### ISSUE TITLE
Crashes when opening ZIM files

### ISSUE THREAD

**Issue by hartsie** [kiwix/kiwix-android#3850]
**Describe the bug**

app crashing kiwix 3.10.1

**Expected behavior**

**Steps to reproduce the behavior:**
1. Open Kiwix

I’ve tried resetting the tab. Software updated to 
T387VVRU3CUI2 Release date 

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.10.1
- Device : Galaxy Tab A8 SM-T387V
- OS version : android 10

**Logs**

**Comment by MohitMaliFtechiz** [comment]
@hartsie We have this type of problem with a specific architecture including your device, and we are working on it in #3661.

**Comment by hartsie** [comment]
> @hartsie We have this type of problem with a specific architecture including your device, and we are working on it in #3661.

Thank you much!!!

**Comment by hartsie** [comment]
Is there an expected release date?

**Comment by hartsie** [comment]
Thank you!!!

**Comment by hartsie** [comment]
> @hartsie We will release after https://github.com/kiwix/kiwix-android/issues/3661 has been fixed. We probably release a new version by end of the next week. 

Any updates good friend?

**Comment by MohitMaliFtechiz** [comment]
@hartsie Thanks for your patience. We have found the issue https://github.com/kiwix/kiwix-build/pull/704, and we will release the new version of the application by tomorrow.

**Comment by hartsie** [comment]
> @hartsie Thanks for your patience. We have found the issue https://github.com/kiwix/kiwix-build/pull/704, and we will release the new version of the application within 2 days.

You guys are really something. I'm very impressed.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Fixed by #3867?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Yes this issue is fixed by the #3867.

**Comment by kelson42** [comment]
@hartsie Thank you for your bug report and patience. Should work with version `3.11` going to beta testing today. Please open a new issue if you have any other issue.

**Comment by hartsie** [comment]
Thank you so much yall! This is very exciting! You are very impressive.
