### ISSUE TITLE
Zimit2 Youtube video still doesn't play on Android reader

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-android#3860]
**Disclaimer:** I open the issue on this Android repo because I need help from Android experts, but the issue might well have to be solved in openzim/warc2zim repo, this will have to be discussed.

We have a test ZIM at https://dev.library.kiwix.org/viewer#100rabbits_en_2024-05 or https://mirror.download.kiwix.org/zim/.hidden/dev/100rabbits_en_2024-05.zim which has Youtube videos embedded.

This ZIM has been built with under-development zimit2 / warczim2 scraper, so it is still experimental.

The ZIM plays very well except Youtube videos. You can find them on Orca or Dotgrid pages for instance (links available on ZIM homepage).

These Youtube videos  seems to now be OK on kiwix-serve (even on Firefox / Chrome on an Android device), Kiwix Apple MacOS, and probably others (more confirmation will come soon in https://github.com/openzim/zim-requests/issues/1011).

I do not have sufficient tooling to debug this, could someone with proper tooling help me diagnose what is going on? Does it looks like a bug in Android reader (i.e. it should have worked differently) or a bug in how the ZIM is built (to be solved in openzim/warc2zim)?

Please remember that these zimit ZIMs have ad-blocker enabled at crawl time, so we have quite a significant amount of request to ad-blocker / trackers failing, but these are normal (or at least expected). The "game" consists in finding which request is not an ad / tracker and should have worked but did not. You can of course compare with behavior inside Chrome / Firefox.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Once 3.11 ready to release, pkease help @benoit74 on this one

**Comment by benoit74** [comment]
Note that Zimit 2.0 has been released and we are publishing more and more ZIMs with this new scraper / bug on YouTube videos in Android reader. Quite important to move this issue forward before users complain too much.

**Comment by MohitMaliFtechiz** [comment]
@benoit74 Thanks for opening the issue, it was an android reader issue. I have placed a fix for this issue in https://github.com/kiwix/kiwix-android/pull/3879.

**Comment by benoit74** [comment]
Glad this could be easily solved. Thank you!
