### ISSUE TITLE
Allow searching for words in article titles that are not at the beginning

### ISSUE THREAD

**Issue by AxelBoldt** [kiwix/kiwix-android#3871]
When I search for an article, only the beginning of the article title is matched against my search word. This is especially inconvenient when searching for a person by last name, since the Wikipedia article title typically begins with the first name.

**Comment by kelson42** [comment]
@AxelBoldt This should not be like this and if confirmed, this is a regression.

**Comment by kelson42** [comment]
I can not reproduce rhis bug. Pkease share step by step what you do with all the details so we can reproduce the bug.

**Comment by AxelBoldt** [comment]
I am using Android Kiwix 3.7.1 to read the file wikipedia_de_all_novid_2018-11.zim (I can't use a newer Kiwix because of bug 3605.) There is a Wikipedia article titled "Große Abchasische Mauer". If I start a Kiwix search for "Abchasische Mauer" I get "No Results".

**Comment by kelson42** [comment]
@AxelBoldt OK, both ZIM and softwares are super old. Not much I can say about them, beside that it works now.
