### ISSUE TITLE
$25 Raspberry Pi IMG

### ISSUE THREAD

**Issue by WirelessDJ** [kiwix/kiwix-android#3881]
Pi5.  Imager version 1.8.5.  I purchased the $25 Raspberry Pi IMG from https://kiwix.org/en/wifi-hotspot/. It took hours to download the 200GB IMG file, I used a Sandisk 256GB card and Raspberry Pi Imager to make the image. it powered up. It resized the volume, then shut off.  now does not boot. It Keeps turning off.  NOTE: I did use custom settings (password, WiFi) when making the image, could that be the issue?   The contact form on the website does not work.  Please help or refund my purchase.

**Comment by kelson42** [comment]
@rgaudin ping?

**Comment by WirelessDJ** [comment]
I am sorry, I do not understand?

**Comment by WirelessDJ** [comment]
Thank you, I found an email on that page.
