### ISSUE TITLE
Download notification disappearing

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3882]
I have no clear reproduction steps, but downloading large files at some point make the download notification disappearing.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Can you please provide some addtional information so that the problem can be narrowed down?

* Which version of Android were you testing this scenario on?
* How much large file you were downloading? I am testing this with 6.4GB, and 9GB files.
* Did the notification disappear when the application was running or in the background or did disappear when the application was closed?
* Did the notification permanently disappear?

**Comment by kelson42** [comment]
Android 13, only one download at a time.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have tested this issue with different large zim files, and left the phone until the files were not downloading, and monitored the behavior but the notification was visible all the time. The notification only disappeared when I killed the application(closed from the background list), and again visible when I reopened the application. Apart from this, the notification is triggering from the fetch lib with the `downloadProgress` see the below method of fetch lib.

https://github.com/tonyofrancis/Fetch/blob/c450f681035ed47d2bd6e5e2b7cf4b921665e669/fetch2/src/main/java/com/tonyodev/fetch2/fetch/ListenerCoordinator.kt#L413

```kotlin
override fun progress(download: Download, etaInMilliSeconds: Long, downloadedBytesPerSecond: Long) {
            synchronized(lock) {
                fetchNotificationHandler.post {
                    synchronized(lock) {
                        for (fetchNotificationManager in fetchNotificationManagerList) {
                            if (fetchNotificationManager.postDownloadUpdate(download)) break
                        }
                    }
                }
                fetchListenerMap.values.forEach {
                    val iterator = it.iterator()
                    while (iterator.hasNext()) {
                        val fetchListener = iterator.next().get()
                        if (fetchListener == null) {
                            iterator.remove()
                        } else {
                            uiHandler.post {
                                fetchListener.onProgress(download, etaInMilliSeconds, downloadedBytesPerSecond)
                            }
                        }
                    }
                }
                if (fetchGroupListenerMap.isNotEmpty()) {
                    val groupId = download.group
                    val fetchGroup = groupInfoProvider.getGroupReplace(groupId, download, Reason.DOWNLOAD_PROGRESS_CHANGED)
                    fetchGroupListenerMap.values.forEach {
                        val iterator = it.iterator()
                        while (iterator.hasNext()) {
                            val fetchListener = iterator.next().get()
                            if (fetchListener == null) {
                                iterator.remove()
                            } else {
                                fetchListener.onProgress(groupId, download, etaInMilliSeconds, downloadedBytesPerSecond, fetchGroup)
                            }
                        }
                    }
                } else {
                    groupInfoProvider.postGroupReplace(download.group, download, Reason.DOWNLOAD_PROGRESS_CHANGED)
                }
                val downloadObserverSet = downloadsObserverMap[download.id]
                downloadObserverSet?.forEach {
                    val observer = it.get()
                    if (observer != null) {
                        uiHandler.post {
                            observer.onChanged(download, Reason.DOWNLOAD_PROGRESS_CHANGED)
                        }
                    }
                }
            }
        }
```

In the above code, `notification` and `downloadProgress` are triggering via this method.

This code triggers the notification

```kotlin
for (fetchNotificationManager in fetchNotificationManagerList) {
      if (fetchNotificationManager.postDownloadUpdate(download)) break
}
```

As you mentioned downloads continue so this method is running as it is publishing the download progress via below method, and we are [handling this progress](https://github.com/kiwix/kiwix-android/blob/4a6fecd2d6edce942082543a628545993adefbeb/core/src/main/java/org/kiwix/kiwixmobile/core/downloader/fetch/FetchDownloadMonitor.kt#L72) and showing it in `LocalLibrary`.

```kotlin
fetchListener.onProgress(download, etaInMilliSeconds, downloadedBytesPerSecond)
```

So the `postDownloadUpdate` method is not calling which updates the notification, somehow the `fetchNotificationManager` listener was removed. The removal and adding of the `fetchNotificationManager` listener is internal to fetch. The [notification disappears after 10 seconds](https://github.com/kiwix/kiwix-android/blob/4a6fecd2d6edce942082543a628545993adefbeb/core/src/main/java/org/kiwix/kiwixmobile/core/downloader/fetch/FetchDownloadNotificationManager.kt#L100) if it is not updated(To handle the app killing scenarios).

**Comment by kelson42** [comment]
I will retest once #3940 is merged

**Comment by MohitMaliFtechiz** [comment]
@kelson42 This issue is fixed by the https://github.com/kiwix/kiwix-android/pull/3935, you can retest this issue on your end.
