### ISSUE TITLE
bookmark.xml Error in file

### ISSUE THREAD

**Issue by A3148475824** [kiwix/kiwix-android#3890]
I opened Kiwix in the file manager data directory! I found a pattern, that is, each bookmark is a space, but I found that two bookmarks are connected together! I don't know what's going on!
![Screenshot_20240624-212433_质感文件](https://github.com/kiwix/kiwix-android/assets/70214970/a05096a8-712b-455c-bbe9-42fcd2dfa0dc)
![Screenshot_20240624-212443_质感文件](https://github.com/kiwix/kiwix-android/assets/70214970/5bd1a7d7-c407-4e03-865b-946c853052ab)

**Comment by MohitMaliFtechiz** [comment]
@A3148475824 Where you are seeing that two bookmarks are connected? in your screenshots, I do not see that two bookmarks are connected with each other. Maybe these are screenshots so that's why I am not seeing the connected bookmarks. Can you please provide the `bookmark.xml` file to investigate? or can you please point to the connected bookmarks?

**Comment by A3148475824** [comment]
> @A3148475824 Where you are seeing that two bookmarks are connected? in your screenshots, I do not see that two bookmarks are connected with each other. Maybe these are screenshots so that's why I am not seeing the connected bookmarks. Can you please provide the `bookmark.xml` file to investigate? or can you please point to the connected bookmarks?

![Screenshot_20240701-212338_Kiwix](https://github.com/kiwix/kiwix-android/assets/70214970/c0b8a187-a832-4c97-bd06-16181da99d67)
![Screenshot_20240701-212433_质感文件](https://github.com/kiwix/kiwix-android/assets/70214970/77835be9-7dad-46c5-b8c2-8c904296b4d3)
I sent you a screenshot now. It appears in the Kiwix bookmark settings and is connected together. In the phone file manager, I open the bookmark file and see it exists. You can see it in the two screenshots.

**Comment by MohitMaliFtechiz** [comment]
@A3148475824 Thanks for the screenshots. Now I understand why it is showing two bookmarks for the same title. As you can see the `bookmarkUrl` is different for both bookmarks that's why it looks connected to bookmarks, and this is the reason that 2 same bookmarks are showing in #3913.
