### ISSUE TITLE
Mul file not recognized as such and listing pretty much all languages

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3892]
Steps to reproduce:

- Download https://dev.library.kiwix.org/#lang=&q=anthropocene
- Open via Kiwix android
- result:
![Screenshot_20240624-213904](https://github.com/kiwix/kiwix-android/assets/21675885/5c95e144-a91a-494f-895a-191a0398c9c3)

**Comment by kelson42** [comment]
We should find anice way to display these files

**Comment by kelson42** [comment]
@MohitMaliFtechiz We have many of such files. Could you please treat this in priority with the other bugs listed in `3.12.0`?
