### ISSUE TITLE
Click the settings button and a red line will appear

### ISSUE THREAD

**Issue by A3148475824** [kiwix/kiwix-android#3894]
In the kiwix-universal-debug version, when you click the settings button, red lines will appear around the screen. The chance of this happening is very high! Sometimes red lines will also appear when you exit the program

![Screenshot_20240626-124226_Aves](https://github.com/kiwix/kiwix-android/assets/70214970/fed3d81c-ed04-424f-b16f-83e3d76e1173)

**Comment by kelson42** [comment]
This is debug version and on purpose. Release versions don't have it.
