### ISSUE TITLE
The app takes 6 seconds to enter the program

### ISSUE THREAD

**Issue by A3148475824** [kiwix/kiwix-android#3895]
In the kiwix-universal-debug version, every function button will freeze when clicked, and the fluency of the entire software is not as good as the official version! The loading speed of opening content is still a bit slow, not very smooth, and the time to click the app is as high as 6 seconds, while the official version is less than 2 seconds! The entire software needs to be optimized for fluency!

**Comment by kelson42** [comment]
@A3148475824 We will release a new official version rhis week. Thw debug version is dlower and this is normal but I would be interested to get details feedback about the production version.

**Comment by kelson42** [comment]
@A3148475824 Any feedback with version 3.11.1?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Production version `3.11.1` from `PlayStore` also takes 1-2 seconds to open(I have checked this on both low and high-end devices), the debug version is slow from the production version takes 3-5 seconds to open the application(as we doing some additional setup in this version for detecting the potential errors and memory leaks, disk violation, etc).

@A3148475824 Would be glad to have your feedback on the new production version.

**Comment by kelson42** [comment]
OK, then the extra long start on debug is explained. Closing.
