### ISSUE TITLE
can only search for one Chinese character from 3.8.0 started

### ISSUE THREAD

**Issue by fishergz** [kiwix/kiwix-android#3896]
For example, searching for "计" is okay, but searching for "计算" yields no results.
3.11.0 can only search for one Chinese character
3.9.1 can only search for one Chinese character
3.9.0 can only search for one Chinese character
3.8.1 can only search for one Chinese character
3.8.0 can only search for one Chinese character
3.7.1 all ok but unable to access zim files after a few days

**Comment by fishergz** [comment]
Android 11

**Comment by kelson42** [comment]
@fishergz Thank you for the bug report, this is a known issue and a duplicate of https://github.com/kiwix/kiwix-android/issues/3816

**Comment by tedaz** [comment]
As of version 3.12.0, this issue still unfixed.

**Comment by lizy14** [comment]
updating ZIM file worked for me. https://github.com/kiwix/kiwix-android/issues/4049#issuecomment-4002151601
