### ISSUE TITLE
[Bug] Android TTS does not work for Dutch [sf#821]

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#39]
_From @rashiq on June 8, 2016 13:6_

**Reported by kelson42 on 2015-01-24 08:51 UTC**
TTS does not work for Dutch Wikipedia ZIM file. After investigating the code it seems that the TTS class simply does not access Locale( 'nl' ) although the Free Google voice claims the support of it.

_Copied from original issue: kiwix/kiwix#185_

**Comment by mhutti1** [comment]
_From @rashiq on June 8, 2016 13:15_

**Updated by kelson42 on 2015-02-23 10:26 UTC**
- **summary**: Android TTS does not work for russian --> Android TTS does not work for Dutch
- Description has changed:

Diff:

```

--- old
+++ new
@@ -1 +1 @@
-TTS does not work on android with ZIM file in russian... although russian seems to be a supported language (by android TTS)
+TTS does not work for Dutch Wikipedia ZIM file. After investigating the code it seems that the TTS class simply does not access Locale( 'nl' ) although the Free Google voice claims the support of it.

```

**Comment by mhutti1** [comment]
_From @kelson42 on August 28, 2016 14:8_

I re-open that bug... Reason to close it is not clear to me.

**Comment by kelson42** [comment]
I need to check if we still have the bug with 3.0.

**Comment by kelson42** [comment]
This works now
