### ISSUE TITLE
Text "use network to download content list." should be in the center of screen

### ISSUE THREAD

**Issue by parasg97** [kiwix/kiwix-android#390]
![screenshot_20180214-222149](https://user-images.githubusercontent.com/23073395/36245241-331be606-1250-11e8-984a-966e54b377c3.png)

**Comment by kelson42** [comment]
@parasg97 Thx for the bug report. You are right, please go ahead if you want to fix that bug.

**Comment by parasg97** [comment]
Yes i would like to fix this

**Comment by pprathameshmore** [comment]
I would like to fix this bug

**Comment by parasg97** [comment]
Currently, the margin of both textview and button is fixed to 230dp.I think it is not a good idea to keep margin fixed at a particular value. Also, there is no use of linear layout as its only child relative layout has dimensions match parent. Is it cool if I convert the layout to constraint layout?
![screenshot 30](https://user-images.githubusercontent.com/23073395/36257578-7cc243cc-127d-11e8-8d87-73d4cc6f3fc4.png)

**Comment by mhutti1** [comment]
@parasg97 make any changes you need to to refactor the layout. I think Android is moving to wards constraint layouts if you want to make use of them.

**Comment by kelson42** [comment]
@abdulwd @siddharth2010 May one you please just do a little fix to help quickly to fix that bug?

**Comment by macgills** [comment]
This button no longer exists. However I feel the "No content" text is not consistent across these 3 screens, in either positioning or size

**Comment by CheshtaK** [comment]
I'd like to work on this issue, can I please go ahead and do that?

**Comment by macgills** [comment]
@CheshtaK please do. Just give our contributing guidelines a quick read first please, it might be best to click on them in the repo as opposed to following the links on the readme those are linking to slightly old copies right now but will be updated on the next release

**Comment by parasg97** [comment]
how do I unsubscribe to this thread?

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/63837125-c4663c80-c972-11e9-8976-014a906a5e9a.png)
I assume you have similar options to myself @parasg97

**Comment by siddharth2010** [comment]
@parasg97 , you can also unsubscribe from Gmail itself.

![image](https://user-images.githubusercontent.com/32238400/63843019-52f2b200-c9a3-11e9-8274-f64a1ca4bfae.png)
