### ISSUE TITLE
Sometimes migration test took longer in migration in lower device(e.g. API level 25) and fails the test case.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3907]
**Describe the bug**
The `ObjectBoxToRoomMigrator` test sometimes fails on API level 25 due to exceeding the migration time and fails the whole CI. We have implemented a retry mechanism in our CI which runs the test cases again to this API level which makes the CI slower. However, migration is completed but due to timing issues, the test fails.

See https://github.com/kiwix/kiwix-android/actions/runs/9696481028/job/26758502101#step:8:592, https://github.com/kiwix/kiwix-android/actions/runs/9695876596/job/26756571306

**Expected behavior**
We should increase the timing of this test or probably remove this timing test since it upto the device that how long it would take in migration.

**Comment by kelson42** [comment]
I can not understand how such a migration can take more rhan a few seconds. This is pb fir the CI or in production?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 This is impacting the CI, not the production build as I have run this test on a real device 20 times and it takes a few seconds to migrate `5000 history`. Every time this test case is passed on a real device.

> This is pb for the CI or in production? If this impacts only the CI, please release and move this to 3.12.0.

Okay, I am moving this ticket to the next milestone.
