### ISSUE TITLE
Minor error in displaying numbers

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#391]
The content manager page looks like this:

![screenshot_20180215-150456](https://user-images.githubusercontent.com/32238400/36249766-a36f6850-1233-11e8-9008-9551894ad383.png)

The "number of articles" should have commas instead of points, (e.g. 10,000 instead of 10.000)

**Comment by mhutti1** [comment]
This is hard coded into content files. It is this way because it is the continental way of writing numbers. I would prefer it to be a comma coming from the UK but it is up to @kelson42 and is not an issue with Kiwix Android (short of creating a local specific workaround)?

**Comment by siddharth2010** [comment]
oh, I didn't know that. I guess you are right, its not really an issue then...

**Comment by kelson42** [comment]
@mhutti1 I'm quite sure the numbers are not formatted in the ZIM files, and the Kiwix lib should provide them unformatted.
@siddharth2010 What you need to know is that the way to represent (big) numbers might change from language to language as each language tends to have its own typography rules. Libicu provides a small page about that here http://userguide.icu-project.org/formatparse/numbers. As libicu is basically installed on Android, you should somehow be able to format things properly using the java SDK. That said all of this needs to depend from the current UI language IMO.

**Comment by siddharth2010** [comment]
sure. I will  look into it.

**Comment by mhutti1** [comment]
@kelson42 Numbers sure but the 50000 articles is a String in a description and as such no such formatting exists.
