### ISSUE TITLE
Opening an article will show that it has been added as a bookmark

### ISSUE THREAD

**Issue by A3148475824** [kiwix/kiwix-android#3912]
No matter which article is opened, it will show that it has been added as a bookmark, and can only wait for two or three seconds. He may be reviewing it in the background to check whether the bookmark is added!

**Comment by MohitMaliFtechiz** [comment]
@A3148475824 Thanks for opening the issue, can you please tell me in which zim file you are testing and facing this bug(A video and logs would be helpful to debug the problem)?

I have tested it with `wikipedia_en_all_mini_2024-04.zim` but I can not reproduce this error with the zim files that I have on my device.


https://github.com/kiwix/kiwix-android/assets/34593983/7fca8030-114f-4883-b938-133613cc9d4c

**Comment by A3148475824** [comment]
> @A3148475824Thanks for opening the issue, can you please tell me in which zim file you are testing and facing this bug(A video and logs would be helpful to debug the problem)?感谢您打开问题，您能否告诉我您正在测试哪个 zim 文件并面临此错误（视频和日志将有助于调试问题）？
> 
> I have tested it with我已经测试过它`wikipedia_en_all_mini_2024-04.zim`but I can not reproduce this error with the zim files that I have on my device.但是我无法使用设备上的zim文件重现此错误。
> 
>  screen-20240629-113326.mp4

If I view the content on the bookmark interface that has been added, I click a new interface at will, then the bookmarks have been added below. If there is no real condition, it will disappear after two or three seconds! Conversely, if you return to the previous level, the bookmark will show that the bookmark has not been added, and the bookmark has been added after two or three seconds!

**Comment by MohitMaliFtechiz** [comment]
@A3148475824 Can you please provide the device logs?

You can send it from the `Help` screen. `Help->Send diagnostic report->Send Details` will generate a log file please attach that log file here.

**Comment by A3148475824** [comment]
> @A3148475824 Can you please provide the device logs?
> 
> You can send it from the `Help` screen. `Help->Send diagnostic report->Send Details` will generate a log file please attach that log file here.

https://mega.nz/file/N9xUCKTa#sLmfiVt6sS1jXAC26sTzxkhamd7XF1R72CSnfZMhux0

**Comment by MohitMaliFtechiz** [comment]
@A3148475824 Thanks for opening the issue. It was a latency issue. We have fixed that issue in #3918. If you want to test this on your side, you can test this APK https://drive.google.com/file/d/11JYfBfYf3H4dIUibZ0tuMlT_vtOEm0xn/view?usp=drive_link.
