### ISSUE TITLE
Minor spelling mistake

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#392]
There are some spelling errors in the Content Manager page:

![screenshot_20180215-151622](https://user-images.githubusercontent.com/32238400/36250233-1f00ae88-1235-11e8-9c4a-3410295e2ab6.png)

it should be "All Wikipedia article**s** about Indian cinema" instead of "All Wikipedia article about Indian cinema"

**Comment by Koundinyalanka** [comment]
Heyy is this the screenshot of the app installed from google play @siddharth2010

**Comment by mhutti1** [comment]
This is not a kiwix android issue. We fetch this info directly from http://mirror.download.kiwix.org/library/library.xml @kelson42 is there a good place to put issues like this?

**Comment by kelson42** [comment]
@siddharth2010 Thx, fixed here https://github.com/kiwix/maintenance/commit/8807a2cef07ca96caf4bc57033ec9bbea8c71c72
