### ISSUE TITLE
org.kiwix.libzim.Archive.getRandomEntry java.lang.Exception

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#3931]
![image](https://github.com/kiwix/kiwix-android/assets/1029718/ec5d50f4-200f-4048-aae2-11da29668fce)

**Comment by MohitMaliFtechiz** [comment]
@kelson42 This is duplicate of https://github.com/kiwix/kiwix-android/issues/3926 that we already fixed in https://github.com/kiwix/kiwix-android/pull/3927.
