### ISSUE TITLE
Images are not saving in `TED` zim files.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3936]
**Describe the bug**
We have a functionality to save the images by long-clicking on the image. But this functionality does not work in `TED` zim files. e.g. https://library.kiwix.org/#lang=eng&q=conducting.

https://github.com/user-attachments/assets/610f9976-0df4-45e9-966e-783e84fdd185

**Expected behavior**
It should save the image for this zim file too.

**Steps to reproduce the behavior:**
1. Download the `TED conducting` zim file.
2. Open it in the reader.
3. Long-click on any image, and you will see the error.

**Environment**
- Version of Kiwix Android: 3.11.1
- Device: Google Pixel 7a, and Honor 7C.
- OS version: Android 13, Android 8

**Comment by kelson42** [comment]
Maybe this is because you long click on a video? Actually this shoukd alow to save the video.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 This is a thumbnail of the video on which I am long-clicking. In the next zim file in the video, there is also the same type of content with the thumbnail of the video as in the TED zim file and it is saved in the storage. So in the TED zim file also thumbnail should be saved.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I guess, you mean the video poster? https://www.w3schools.com/tags/att_video_poster.asp

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Yes.

**Comment by kelson42** [comment]
Definitly an edge case, but yes can be considered as as a bug. Would still expect to save the video or audio file in place of the poster.

**Comment by MohitMaliFtechiz** [comment]
For the `TED` zim files if I click on the video poster then the `URL` is this https://kiwix.app/a-virtual-choir-2000-voices-strong?lang=undefined and `src` is https://kiwix.app/videos/1110/thumbnail.webp which comes from the webview. Because of this, the thumbnail is not saving as the URL is not null, and according to our current logic, it is giving the fileName `null` for this URL.

Here the URL is the next page URL on which this video is showing, it is not a video URL

![image](https://github.com/user-attachments/assets/2a4f5105-be45-4310-8f98-af46d96d8a90)

And the video URL of this page is https://kiwix.app/videos/1110/video.webm
