### ISSUE TITLE
Download zim files in `Android/media/org.kiwix...` folder instead of internal `app-specific` directory.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3939]
**Describe the bug**
Currently, we are storing the downloaded zim files in the internal app-specific directory which is not accessible by the file manager so user can not copy their already downloaded zim files in this directory using their mobile. They need a computer to copy the zim files in this directory and then they can read the zim file.

**Expected behavior**
* We should download the zim files in the `Andorid/media/org.kiwix...` directory as it is a public app-specific directory and users can copy the zim files from this folder before uninstalling the application. So that, they do not require to download again those zim files, when they install the application again.
* Also, this directory is accessible to the file manager so users can move their already downloaded files in this directory and the app can read those zim files.
* Update the readme file to educate users that they can copy their already downloaded zim files in the `Android/media/org.kiwix....` folder, and before uninstalling the application they can copy all zim files to another directory to prevent losing the zim files.

**Comment by Jaifroid** [comment]
Just to add, it would be great to give users a choice whether to download into the `/media/org.kiwix...` directory on Internal Storage or into the equivalent directory on any microSD card, if it exists. On lower-spec Android devices, the Internal Storage may be pretty crowded, and a microSD card is used to store large files in many apps (e.g. Open Street maps - OSM Android or Organic Maps, where the user is given just such a choice).

**Comment by MohitMaliFtechiz** [comment]
> Just to add, it would be great to give users a choice whether to download into the /media/org.kiwix... directory on Internal Storage or into the equivalent directory on any microSD card, if it exists. On lower-spec Android devices, the Internal Storage may be pretty crowded, and a microSD card is used to store large files in many apps (e.g. Open Street maps - OSM Android or Organic Maps, where the user is given just such a choice).

@Jaifroid There is a choice to download in internal or external storage in the settings screen. Also, the application asks first time where to download the content(internal or external storage).

**Comment by Jaifroid** [comment]
> @Jaifroid There is a choice to download in internal or external storage in the settings screen. Also, the application asks first time where to download the content(internal or external storage).

Excellent! Thanks for explaining.

**Comment by MohitMaliFtechiz** [comment]
> Why we don't have downloaded to that directory first? Do we have any inconvenient in comparison to current one? Please don't implement anything until everything is clear.

@kelson42 It will work the same as the current one, this one is a public app-specific directory for the application. We have not faced this issue also someone never reported that they are facing an issue in copying the zim files so our focus never went on this side, my bad (We were mainly focusing on how we can do the scanning, and accessing the files from storage). We were already using the internal app-specific directory for saving the notes, and we used this same directory for downloading zim files.
