### ISSUE TITLE
minor changes to text

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#394]
I think we should change the text in the downloading tab of the content management screen from "No downloads here" to something else, like "Download queue is empty", or something like "The download queue is empty... Select a file from the online tab to start downloading"

![screenshot_20180215-160253](https://user-images.githubusercontent.com/32238400/36252238-c3d33b96-123b-11e8-8e7d-9401845dbaa1.png)

**Comment by mhutti1** [comment]
Superseded by https://github.com/kiwix/kiwix-android/issues/75. Won't fix.
