### ISSUE TITLE
Kiwix saying "Error: invalid zim file"

### ISSUE THREAD

**Issue by Brand2204** [kiwix/kiwix-android#3955]
**Describe the bug**
Kiwix can't open zim file I downloaded. It's displaying Error: file not a valid zim article.

I downloaded zim file for medicine (4-2024) from the kiwix website, previously I've been using kiwix js PWA on mobile, but it stopped opening the file. So I downloaded the kiwix app proper. And when I tried to open the file on it, it gave that prompt. Besides, previously, I had downloaded the app and it did a similar thing which made me to go to the extension (kiwix is PWA), but it stopped working, so I came back to the main app. And it's still doing the same thing.
My OS and the file version is up to date for my device.

**Screenshot**
![Screenshot_2024-07-24-10-54-17-313_org kiwix kiwixmobile](https://github.com/user-attachments/assets/57bc3719-1a99-4819-a7b8-2909c691a477)

**Expected behavior**
The app should be able to open all zim files provided that they are downloaded from the appropriate source (either the app directly or the kiwix site)

**Steps to reproduce the behavior:**
1. Open the app
2. Click on + in the library section 
3. Scroll down tk file and click on it
4. It displays "Error: file is not a valid zim article 

**Environment**
- Version of Kiwix Android : 3.11.1
- Device : Redmi 9c
- OS version : MIUI Global 12.0.23 Stable

**Comment by kelson42** [comment]
@Brand2204 Thank you for reporting this problem. 
@MohitMaliFtechiz Can you please investigate?

**Comment by MohitMaliFtechiz** [comment]
@Brand2204 Thanks for opening the issue. Can you please provide some additional information?

* Can you please tell me which medicine zim file you are using?
* Is this behavior the same for all zim files or are you facing this issue with this particular zim file?
* Is this zim file showing in the Library screen when you refresh the list by swiping it down?
* You are using the website apk(as you have the + icon in your library so it should open all your zim files). It seems the application is unable to create the reader for your given zim file. Can you please share the device logs? so that I can investigate more.

**Comment by Brand2204** [comment]
Sorry for the late reply 🙏

It has been resolved. I redownloaded the zim file from the app and it opened. I think it was because I downloaded from the site instead of from the app


![IMG_20240727_210530](https://github.com/user-attachments/assets/74fbc3f3-138c-4b91-9ca5-052c6163553f)

![IMG_20240727_210512](https://github.com/user-attachments/assets/c813edae-dde5-4446-acf3-fc1dc91b5baf)

**Comment by Brand2204** [comment]
![Screenshot_2024-08-02-13-49-04-193_org kiwix kiwixmobile](https://github.com/user-attachments/assets/815de21a-2097-46c1-94d4-cf5ffa4cd4df)
It happened again, this time with the main kiwix app. Is this a bug?

**Comment by MohitMaliFtechiz** [comment]
@Brand2204 "Main kiwix app" meaning playStore version? or you are using the webSite APK?

**Comment by Brand2204** [comment]
Main kiwix app downloaded from play store

**Comment by MohitMaliFtechiz** [comment]
@Brand2204 Thanks for confirming. Can you please share some more details?

* Have you downloaded this file from the application with playStore application?
* If not downloaded with the application, then where is the file located in the storage?
* Is the zim file showing in the "Library Screen"?
* Please share the device logs, that would be very helpful in diagnosing the problem.

**Comment by Brand2204** [comment]
I downloaded the file from the app itself (with the playstore application)
It was showing

Sorry, I've already deleted the app. I'll use the online Wikipedia
