### ISSUE TITLE
Where can I find Kiwix apk’s package name and signing certificate for verify it’s integrity

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3975]
From a user:

> I’m using Obtainium and AppVerifier to download and update my Android apps. Sadly Kiwix’s signing certificate is not in the [AppVerifier](https://github.com/soupslurpr/AppVerifier)’s internal database yet, so I have to find and verify it externally. This is where my question comes in: where can I find Kiwix apk’s package name and signing certificate to verify its integrity?

**Comment by kelson42** [comment]
@MohitMaliDeveloper At this stage I have no clue what these apps do and if we have something we should improve. Do you?

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you help with an answer?

**Comment by kelson42** [comment]
@Popolechien question answered.
@MohitMaliFtechiz Merci
