### ISSUE TITLE
The emulator caching is unstable, it sometimes fails to launch the emualtor from caching.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3978]
**Describe the bug**
The emualtor caching is unstable, it sometimes fails to launch the emualtor from the cache. Sometimes it launches the emualtor but sometimes not. We have currently removed the caching from our CI in https://github.com/kiwix/kiwix-android/pull/3976 to fix the CI, but we should re-enable the caching for the emulator at some point(probably when it is stable).

See these workflows:
1. https://github.com/kiwix/kiwix-android/actions/runs/10416574005/job/28849083778
2. https://github.com/kiwix/kiwix-android/actions/runs/10416260992/job/28848165248
3. https://github.com/kiwix/kiwix-android/actions/runs/10415166498/job/28845238263

**Expected behavior**
It should run the emualtor from the cache.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you please fix?
