### ISSUE TITLE
Verify play store account.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3987]
**Describe the bug**
There is a new verification policy that comes into the playStore in which we need to verify our playStore account before 6 November 2024.

![Screenshot from 2024-09-10 10-25-48](https://github.com/user-attachments/assets/2cc0be41-9dc9-4a43-a902-5efab1b7472e)

**Comment by kelson42** [comment]
I went through and this is not being processed by Google.

@MohitMaliFtechiz On checkbox was requesting me to authorize publishing information about Kiwix on the PlayStore. One of this information was my phone number. I hope this information is not concerned. Do you know more? We should verify this accurately.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 As our developer account is organization type so we have to follow this organization type verification https://support.google.com/googleplay/android-developer/answer/14177239. Since we have not provided the organization name and address which shows on the Google PlayStore, and related to the phone number, playStore requires this for contacting us and we have to verify it via OTP.  Also, it will ask for proof of organization as mentioned in the help article https://support.google.com/googleplay/android-developer/answer/14177239.

![Screenshot from 2024-09-10 14-53-30](https://github.com/user-attachments/assets/01580578-4119-42e1-a299-d5be010bf43e)

**Comment by kelson42** [comment]
@MohitMaliDeveloper I don't understand, I went through the whole process following the invite at the top of the page... It was written that I had to wait google... and now I see again the invitation... and it seems I have to start again everything from start.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I have also no clue where your screenshot comes from

**Comment by MohitMaliFtechiz** [comment]
@kelson42 This screenshot comes from the `Account details` page.

![Screenshot from 2024-09-10 16-42-49](https://github.com/user-attachments/assets/8897bc23-ac6d-4dc8-8e33-681e0a20f0f6)

**Comment by MohitMaliFtechiz** [comment]
And for the details that are required to verify the organization-type developer account that are mentioned in the official docs https://support.google.com/googleplay/android-developer/answer/14177239.

![Screenshot from 2024-09-10 16-48-09](https://github.com/user-attachments/assets/9b0dedc3-70cd-4f04-b8e5-3f6dbf7c3d7a)

**Comment by Popolechien** [comment]
All the necessary info should be in there already, and I've shared the Register of Commerce documents with @kelson42 . Iam not able to edit the profile myself, which is kind of problematic as it means that we have a single point of failure for all account-related things.
