### ISSUE TITLE
Multiple tabs created when pressed undo.

### ISSUE THREAD

**Issue by arpank10** [kiwix/kiwix-android#399]
When we close the last open tab and press undo,two instances of the same tab is created.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24573296/36257599-8e018c74-127d-11e8-99e5-7aa15e8d5997.gif)

This has two possible solutions:
1. Create a default starting tab to display(for now we can set it to help tab) when all the tabs are closed.
2. Right now at least one tab is always displayed, there can be provision for no opened tabs, where no tabs are opened, and a starting page is displayed.

**Would you like to work on it?**
Yes

@mhutti1 @kelson42 What do you think about it?

**Comment by arpank10** [comment]
When the new tab button is pressed, a tab with any one of the articles downloaded is opened. I would try and create a starting tab displaying the list of currently downloaded articles then.

**Comment by mhutti1** [comment]
@arpank10 I would stick with displaying the current articles home page for now imo. Your solution might be usefull once multi zim comes in but until then I think its best to display the home page.

**Comment by arpank10** [comment]
Okay, then I am closing this issue.
