### ISSUE TITLE
App appears corrupted when user is logged out

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#4]
From the OTRS queue:
"The Wikivoyage Offline Travel Book app only starts when I'm logged in
as the user who first installed it. When logged in as another user,
the app displays the following error message when started:

"Wikivoyage"
"Your application is corrupted."
"This might happen when you remove files on the SD Card."
"You need to uninstall then reinstall the App from the Play Store."

The device is a Google Nexus 10 tablet running CyanogenMod 13 with
Android 6.0.1 and two user accounts. Please note that I haven't
removed anything from the SD card, the device doesn't even have one. I
have only installed the app from the Play Store for both users. Of
course, uninstalling and reinstalling the app from the Play Store as
suggested does not change anything to the problem.

In Settings > Apps > Wikivoyage, 713 MB of storage is reportedly used
by the app if logged in as the user who first installed it, while only
43.6 MB is reported if logged in as another user. So it looks like the
app has files that are only accessible to the first user.

Additional info: if the user who first installed the app is /not/ the
device's owner (the first user created at system installation), then
after trying to open the app as the device's owner, it becomes
"corrupted" for the first user too: the same error message appears and
storage usage drops from 713 MB to 43.6 MB. This behavior does not
happen, as far as I can tell, if the user who first installed the app
/is/ the device's owner: in this case the app remains functional for
him after trying to open it as another user."

**Comment by kelson42** [comment]
@mhutti1 @EladKeyshawn @rashiq Ideas? I thought first to a hardware/fs problem with the SD card... but this sounds finally a bit more serious (I was not aware that on Android it was possible to have many users).

**Comment by kelson42** [comment]
@mhutti1 Unable to understand anything regarding that ticket, do you think you have fixed it with your commit?

**Comment by mhutti1** [comment]
@kelson42 Idk will add to 2.3 milestone

**Comment by mhutti1** [comment]
I am struggling to reproduce so am pushing to 3.0

**Comment by kelson42** [comment]
I will try to reproduce that problem.

**Comment by kelson42** [comment]
@macgills Do you think there is a bug at all here?

**Comment by macgills** [comment]
@kelson42 It is possible? This was a custom app and depending on file permissions it could make sense that that the obb file is unreadable by another user. There isn't really a way to work around this, a users files should be a users files. Potentially this is just a problem with cynagenmod and android now has a proper inclusion of file rights for obbs on shared app installs.
Regardless we do now have the fallback downloader to provide the file. In this scenario the user would end up with 2 copies of the zim though

**Comment by kelson42** [comment]
@macgills Does that not sounds weird to have the app available for all but the extension only for a user? Is that not a sign of a misconfiguration?

**Comment by macgills** [comment]
The play store handles downloading & storing of an obb file, I couldn't misconfigure something if I tried.

**Comment by kelson42** [comment]
I close the ticket as there is nothing we really can do here. Works as Google has conceived it!
