### ISSUE TITLE
Allow updates to storage locations without app update

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#40]
_From @mhutti1 on December 16, 2016 23:36_

Allow the app to get an updated list of locations from the internet to ensure we can quickly fix devices that users can't access.

_Copied from original issue: kiwix/kiwix#393_

**Comment by mhutti1** [comment]
I have implemented a half way solution that doesn't require and internet connection. Users can input their own path to the mount point and instead use that.
