### ISSUE TITLE
Scrolling in the Content Manager Screen

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#400]
The Content manager screen scrolls leaving a blank space at the bottom of the screen.

![screenshot_20180215-181715](https://user-images.githubusercontent.com/32238400/36257555-6e69248a-127d-11e8-87f7-8ba8e04b9ca1.png)

and here as well:

![screenshot_20180215-182208](https://user-images.githubusercontent.com/32238400/36257558-6f9efc26-127d-11e8-99be-0e1fa11d903c.png)

Steps to reproduce:
in the Content Manager screen, Scroll up using the black header.

**Comment by mhutti1** [comment]
Good spot. I think the best fix is to simply disable scrolling from the black bar.

**Comment by arpank10** [comment]
@siddharth2010 Are you working on it or should I proceed?

**Comment by siddharth2010** [comment]
yes, I am working on it.

**Comment by siddharth2010** [comment]
@mhutti1 @kelson42 Please review the PR.

**Comment by mhutti1** [comment]
@siddharth2010 Myself and kelson have other full time commitments and are likely in timezones considerably different to yours. We get email notifications about pull requests and will get to them when we have the time.

**Comment by siddharth2010** [comment]
I am really sorry about that. I will take care of it in future.
