### ISSUE TITLE
Remove "Send feedback" option from Help tab

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#4004]
The Send feedback menu item opens users' email client on their phone, with no other indication as to what to do next. I guess the expected behaviour would be for people to tell us how much they like Kiwix or send suggestions, but it turns out that in 99.999% of cases we only receive empty emails in Arabic or Spanish because users can't/won't read the FAQ below, or those do not answer their question, or they don't know what kind of feedback they're expected to give when the short answer is "Kiwix is not working as I expected it to, please help". Every day we also have users sending multiple empty emails, I guess in the hope that some automated Help function will activate, I guess?

In any case, no help is forthcoming because when we tried responding to these with a canned response asking for more details, we would never hear back. So much so that we stopped responding altogether. Meaningful feedback, when it arrives, actually comes from the contact form at kiwix.org.

Sorting through these emails, even if only to ignore them, takes time (we get 10/day, probably more on week-ends). There is no added value for either us or the users (I would even say that it creates false expectations), so the functionality should be deprecated.

**Comment by kelson42** [comment]
I will assrss this issue before implementation.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please delete the feature
