### ISSUE TITLE
In Samsung tablet of Android 14, downloaded files can not be opened via file picker or deep linking.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#4008]
**Describe the bug**
In Samsung tablet of Android 14, downloaded files can not be opened via file picker or deep linking. However, other zim files I can open via filePicker or deep linking e.g. which are in the document, and in other folders (which I just copy from my computer).

This issue is in the non-playStore variant.

**Expected behavior**
It should open the downloaded zim files as well.

**Steps to reproduce the behavior:**
1. Download the application on a Samsung tablet(Android 14).
2. Download a Zim file via any browser(Chrome, Firefox).
3. Try to open that ZIM file with Kiwix, You will see the error.

**Environment**
- Version of Kiwix Android: 3.11.1
- Device: Samsung Galaxy Tab S9 FE SM-X510
- OS version: Android 14

**Comment by kelson42** [comment]
I just installed VLC and downloaded a mp4 file, here is what I get when I try to open the mp4 file from the Samsung file browser
![Screenshot_20240927_092119_Android System](https://github.com/user-attachments/assets/1c0501cb-e367-4ea3-ba40-4896386c9117)

The result 8s convincing: there is an efficient way for the file browser to propose appropriate apps.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Which PR fixes this?
