### ISSUE TITLE
Downloading Fandoms

### ISSUE THREAD

**Issue by aknight2015** [kiwix/kiwix-android#4023]
Do you have any plans to support downloading individual fandoms?

**Comment by MohitMaliFtechiz** [comment]
@aknight2015 Can you please elaborate this? The description is very short to understand your question.

**Comment by kelson42** [comment]
We do have Fandom wikis https://library.kiwix.org/#lang=&q=fandom

**Comment by aknight2015** [comment]
I'm specifically looking for the Doom, Star Wars, and Warhammer 40K fandoms.

**Comment by kelson42** [comment]
Please open one issue per request at https://github.com/openzim/zim-requests
