### ISSUE TITLE
Last "Publish App to PlayStore" task failed to upload the application on PlayStore.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#4026]
**Describe the bug**
The last "Publish App to PlayStore" task failed to upload the application on PlayStore. https://github.com/kiwix/kiwix-android/actions/runs/11215178124/job/31171826224

**Expected behavior**
It should upload the application to the Play Store.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 We are using two foreground services in our project, and we need to inform the Google Play Console about them as outlined in the official documentation: https://support.google.com/googleplay/android-developer/answer/13392821?hl=en. However, there is a catch: the option to provide this information to Google is not directly available in the Play Console. We have to manually upload the app bundle to the Play Store, after which this option will appear during the upload process. I have researched this and found no direct option to fill out the form beforehand. I came across this official response: https://support.google.com/googleplay/android-developer/thread/287886182/google-api-error-foreground-service-permissions-required-please-assist?hl=en.

So here we need to provide the:
1. A short description of each foreground service.
2. A video demonstrating the feature.

All these steps are detailed here: https://support.google.com/googleplay/android-developer/answer/13392821?hl=en#.


Before we proceed, we need to refactor our code for custom apps. Since ReadAloudService is used in both the main app and custom apps, but the HotspotService is currently only used in the main app, we enabled it for custom apps in https://github.com/kiwix/kiwix-android/pull/3487. However, due to the use of file descriptors (fd) in custom apps, we hid this feature from custom apps in https://github.com/kiwix/kiwix-android/pull/3516.

We need to remove this Service from custom apps because we are required to provide explanations and videos for all custom apps as well. Since this feature is currently inactive for custom apps, it could lead to their rejection. We will re-enable this feature for custom apps when we are able to open the server using file descriptors.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz We should have an issue requesting the introduction of the hotspot for custom apps because we don't have one and this is unclear what is missing to get it back.

@kelson42 For the hotspot feature of custom apps I have created a separate ticket with all details https://github.com/kiwix/kiwix-android/issues/4028.

**Comment by MohitMaliFtechiz** [comment]
Video samples for our foreground services which we have to provide on the playStore.

| Hotspot Kiwix foreground service:  | ReadAloud foreground service(Kiwix App): | ReadAloud foreground service(Custom App): |
| ------------- | ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/0b40661c-7620-48dd-b5e5-46977787c799" />  |  <video src="https://github.com/user-attachments/assets/6d876205-1f4f-4024-8683-0b196afc217f" /> | <video src="https://github.com/user-attachments/assets/280dbce9-242e-4b60-ab15-a0c35bb49afc" />  |


**Hotspot foreground service:** 
We are using the `dataSync`(android.permission.FOREGROUND_SERVICE_DATA_SYNC) type for this service. Because it hosts our ZIM files on the server.

**Read aloud foreground service**
We are using the `mediaPlayback`(android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK) for this service as this service performs the reading action.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 We are ready to fix the playStore publishing, we have made all the changes in our code and we have the video and explanation about the hotspot foreground service. We should start the explanation process.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Not sure what is left to do, but lease go ahead.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Not sure what is left to do, but lease go ahead.

@kelson42 We are ready to upload the Kiwix app to the PlayStore to fix this issue. We have refactored our code in https://github.com/kiwix/kiwix-android/pull/4027, and we have the video sample of our foreground service and explanation in this ticket which we have to give to playStore.

> What is the situation for all custom apps? What should be done there?
 
@kelson42 For custom apps, we can directly upload them to PlayStore with Android 14 since there are no foreground services in the custom apps. Therefore, we do not need to give any explanation to Play Store for custom apps(we have made the `read aloud` service a normal service).

**Comment by kelson42** [comment]
@MohitMaliFtechiz Have you make the request? How long is expected to again be able to upload to the PS?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 Yes, I have requested to the playStore. It is in review, it can take 1 day to review.

![Image](https://github.com/user-attachments/assets/2ef244e2-c7e7-44a3-92c6-21caf4bc4b6a)

**Comment by kelson42** [comment]
Lets hope we can upload tomorrow and close the issue.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 PlayStore approved our request, and the last app bundle has been successfully uploaded to PlayStore via our CI https://github.com/kiwix/kiwix-android/actions/runs/11606984848/job/32319808646. So I am closing this issue.

![Image](https://github.com/user-attachments/assets/c4c129c4-9fa4-4264-98da-e4e6d715305f)


![Image](https://github.com/user-attachments/assets/a8ed2735-5b14-455b-bfb3-37876ccd46ee)
