### ISSUE TITLE
Replace  icons with Material Design icons

### ISSUE THREAD

**Issue by RajaVamsi11** [kiwix/kiwix-android#403]
**Description:**
Refresh icon in the app looks somewhat outdated.so we can replace it with android material icon.
![ic_refresh_black_24dp](https://user-images.githubusercontent.com/30550059/36265596-9110e91a-1295-11e8-9ef8-85b3534e7eec.png)

Along with Refresh icon ,there are many 2 more icons that can be replaced.
1.FullScreen
![ic_fullscreen_black_24dp](https://user-images.githubusercontent.com/30550059/36267752-af61e23e-129a-11e8-92f7-00b843daa39f.png)
2.FullScreen Exit
![ic_fullscreen_exit_black_24dp](https://user-images.githubusercontent.com/30550059/36267863-faab424e-129a-11e8-8b7d-dd50a893c767.png)

Can i proceed?  @mhutti1 @kelson42

**Comment by pprathameshmore** [comment]
Yes I will do!

**Comment by RajaVamsi11** [comment]
@pprathameshmore  I am working on it. Kindly go and find another issue.

**Comment by RajaVamsi11** [comment]
@mhutti1 @kelson42  I have changed the icons of Fullscreen , Fullscreen exit and Refresh with material design icons.

**Comment by RajaVamsi11** [comment]
As the issue has been solved .I am closing it.
