### ISSUE TITLE
Still displaying old storage configurator (at first download)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#4047]
![Screenshot_20241101_121842_Kiwix.jpg](https://github.com/user-attachments/assets/21475c8b-07a7-4053-9f33-44cc514df514)

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can we display the new storage configurator in a dialog box like this or should we lead the user to the settings panel?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 We should display the new storage configurator here instead of leading the user to the settings panel.

**Comment by kelson42** [comment]
@MohitMaliFtechiz OK. Can you please make a proposal mergin this widget with the one before (asking if we want to custom). I would like to have only one widget to simplify the user journey. So question would be on the top probably, thendisplay the storages, and then the buttons at the bottom.
