### ISSUE TITLE
The android version cannot search for Chinese Wikipedia Data, empty result return.

### ISSUE THREAD

**Issue by tedaz** [kiwix/kiwix-android#4049]
**Describe the bug**
The android version cannot search for Chinese Wikipedia Data, empty result return.

**Expected behavior**

After type a Chinese word in the earch box, there should be results/candidates listed.

On andriod app, after type the chinese word "中文", showed no result.
With the same Data File, on windows app, after type the chinese word "中文", search result showed without any issue.
It is the andorid app issue.

**Steps to reproduce the behavior:**
1. Download the Chinese Wikipedia Data from https://download.kiwix.org/zim/wikipedia/wikipedia_zh_all_maxi_2024-04.zim
2. Load the data file wikipedia_zh_all_maxi_2024-04.zim
3. Type a word in the search box, i.e. "中文"
4. There will be nothing displayed.
5. On older version of Kiwix android app, and older Data file, there will be search results/candidates showed.

**Screenshots**

Data File = wikipedia_zh_all_maxi_2024-04.zim
Android app showed no result
![Image](https://github.com/user-attachments/assets/543e7c72-50c1-48ec-8189-de6acc6ca110)

Windows app showed correct results
![Image](https://github.com/user-attachments/assets/6555e053-344b-40bd-82fc-8c4a31d4a6ee)

**Environment**
- Version of Kiwix Android : 3.11.1
- Device : Samsung Galaxy Note 20 Ultra
- OS version : Android 13

**Logs**

**Comment by kelson42** [comment]
Duplicate of #3816

**Comment by tedaz** [comment]
The bug is known to be resolved by updating libzim, but according to ticket #3816, libzim has already been fixed. However, the bug still persists in the latest version. Could you clarify whether libzim was not updated according to the original timeline, or if the fix was applied but the bug still remains?

**Comment by ljj314zz** [comment]
This error still exists on Chinese characters, what can we do to avoid this error

**Comment by tedaz** [comment]
As of version 3.12.0 build 7231234, this issue still exist.

**Comment by unohara-fuukei** [comment]
> This error still exists on Chinese characters, what can we do to avoid this error

downgrade to 3.7.1 build 7230701 will fix it, but this version has blank home page issue.

**Comment by kelson42** [comment]
FYI, we will finally release new Wikipedia ZH ZIM files... with the fix... in the next days

**Comment by lizy14** [comment]
I'm surprised that the issue is with ZIM file, not Kiwix android app. Because 3.6.0 works for me, 3.14.0 does not work, for the same ZIM file.

**Comment by lizy14** [comment]
Android app 3.6.0:
✅2024-04 ZIM file works

Android app 3.14.0:
❌2024-04 ZIM file does not work
✅2025-09 ZIM file works

**Comment by kelson42** [comment]
@lizy14 What matters the most is always works now with both recent books AND software.
