### ISSUE TITLE
Do we really need to set `usesCleartextTraffic` set in the manifest.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#4055]
**Describe the bug**
We have currently set the `usesCleartextTraffic=true` in our manifest. This attribute is mainly used for allowing the `http` requests(Mainly used for network requests). The network requests are only used for downloading the ZIM files in our application, and if there are no HTTP urls for downloading the ZIM files then we do not need this attributes to set in the manifest.

**Environment**
- Version of Kiwix Android: 3.11.1

**Comment by kelson42** [comment]
@MohitMaliFtechiz Many mirror are still http, https://ftp.nluug.nl/pub/kiwix/mirrors.html

**Comment by MohitMaliFtechiz** [comment]
@kelson42 So we need to keep the `usesCleartextTraffic` in our manifest.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I have wrongly informed you: we should not have any mirror anymore in HTTP, you can remove this from the manifest

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz I have wrongly informed you: we should not have any mirror anymore in HTTP, you can remove this from the manifest

Great 😍 , I am removing this.
