### ISSUE TITLE
Crash on old Mi

### ISSUE THREAD

**Issue by TNTima** [kiwix/kiwix-android#4056]
**Describe the bug**

App crashes when i try to open downloaded archive from Library 

**Expected behavior**

Archive opens in Reader where i can read it

**Steps to reproduce the behavior:**

1. Download any archive
2. Click library 
3. Click on downloaded archive
4. App freezes then crashes

**Environment**
- Version of Kiwix Android : 3.8.0
- Device : Redmi 5 Plus
- OS version : 7.1.2

**Logs**

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/vince/vince:7.1.2/N2G47H/V9.2.0.2.NEGMIEI:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 23617, tid: 23617, name: wix.kiwixmobile  >>> org.kiwix.kiwixmobile <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe
    r0 00000002  r1 ffd5b8fc  r2 ffd5b954  r3 00000000
    r4 00000002  r5 e4f23b48  r6 00000000  r7 e507a420
    r8 ffd5ba04  r9 e5078100  sl f2ca3310  fp ffd5b9f0
    ip f41d9fd4  sp ffd5b8e8  lr f41d4664  pc f4e9ef84  cpsr 600b0010

backtrace:
    #00 pc 0000af84  /system/lib/liblog.so (__gnu_Unwind_Resume+4)
    #01 pc 0001b660  /system/lib/libm.so (___Unwind_Resume+20)

**Comment by MohitMaliFtechiz** [comment]
@kelson42 It is the same issue we have fixed in version `3.11.0` https://github.com/kiwix/kiwix-android/issues/3661. @TNTima Can you please try with our latest APK [kiwix-3.11.1.apk](https://download.kiwix.org/release/kiwix-android/kiwix-3.11.1.apk)?

**Comment by kelson42** [comment]
@TNTima Please install latest version 3.11.1 and let us know if you still have problems.

**Comment by TNTima** [comment]
Everything is working fine! Thank you!
