### ISSUE TITLE
Revamp Bottom Toolbar and Left Drawer from ground up

### ISSUE THREAD

**Issue by brijeshshah13** [kiwix/kiwix-android#406]
**Actual Behavior**

`Left Drawer:`

Current Left Drawer contains the `action_back_button`, `action_forward_button` and `plusDrawable` which are responsible to enable the user go back and forth. However, current UI disables the user himself to see what is the current main screen while going back and forth from the left drawer, which results into the situation where he has to visit the main screen every time to make sure that he is on the right page.

`Bottom Tollbar:`

When enabled from the settings, the current bottom toolbar is static all the way and does not fade out when the screen is still, which causes hindrance for the user to read and scroll more. Also, as per the Guidelines of Material Design, the name of each button in the bottom toolbar must be displayed, which is not yet supported. And, even when the toolbar is activated, same functionalities are provided in the menu present in the top toolbar, which must be removed.

**Expected Behavior:**

`Left Drawer:`

Left drawer must be responsible or handling the tabs only. All the 3 actions must be migrated to the bottom toolbar so that user can see what is the current content of the screen.

`Bottom Tollbar:`

Current bottom toolbar is implemented using `TabLayout` which makes it very difficult to fill out the issues mentioned above. Using `BottomNavigationView` would be better.
Sample:

![bottom_nav_view](https://user-images.githubusercontent.com/18366144/36267248-7666adbc-1299-11e8-9e40-2f88b7a63e42.png)

Major benefit from this would be, we will be able to use `BottomSheetDialog` and `BottomSheetDialogFragment` to display more options like `fullscreen`, `search in file`, `home`, `bookmark` and `share` properly rather than putting everything in the menu of the top toolbar and making a cumbersome experience for the user.
Sample:

![bottom_sheet_dialog](https://user-images.githubusercontent.com/18366144/36267478-f77cc102-1299-11e8-8196-ddb94a12b15e.png)

**P.S.:** We are already using `com.android.support:design:27.0.1`, so we need not add any extra dependencies, except if we use any library to provide more functionalities for `BottomNavigationView`.

**Would like to work on this issue?**
Yes.

@mhutti1 @kelson42 Your reviews please?

**Comment by mhutti1** [comment]
Sounds great. I am not sure about fading out. It already scrolls out of view along with the top toolbar.

**Comment by brijeshshah13** [comment]
@mhutti1 Changing from `TabLayout` to `BottomNavigationView` might require different approach for fade out. Also, it doesn't disappear from the screen as it should even when not in fullscreen mode.

**Comment by mhutti1** [comment]
@brijeshshah13 It should not require a different approach as it is still a view.

**Comment by mhutti1** [comment]
If you are having issues with the current implementation please submit a new issue.

**Comment by brijeshshah13** [comment]
@mhutti1 I'm working on it. Will let you know about further developments.

**Comment by abdulwd** [comment]
Redundant by #832.
