### ISSUE TITLE
Why are some contents available only on the PC version ?

### ISSUE THREAD

**Issue by stemy2** [kiwix/kiwix-android#4063]
Hello,

I'd like to download wikipedia, but the content is not telechargeable on the mobile version (where the choice is grayed) and available on the PC version. I don't get the reason.

**Comment by MohitMaliFtechiz** [comment]
> I'd like to download wikipedia, but the content is not telechargeable on the mobile version (where the choice is grayed) and available on the PC version. I don't get the reason.

Hi @stemy2 Thanks for opening the issue. If it showing grey on mobile that means your device does not have enough storage to download that ZIM file. If you long click on the grey content you will see the error, it will ask you to configure the storage(If SD card is available in your device).

**Comment by MohitMaliFtechiz** [comment]
@kelson42, @stemy2 I was correct your device does not have enough storage to download the ZIM file. That's why it is showing grey on that ZIM file. Can you please try to add an SD card(if possible) and let us know?

https://github.com/user-attachments/assets/f2aa04f1-d380-4e06-a720-fb6d9bfe573c

**Comment by kelson42** [comment]
I guess we can close this issue. @stemy2 Please reopen if necessary or open a new issue if you have another problem.
