### ISSUE TITLE
Is it possible to access content stored on a flash drive?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#4071]
A user reported trying to plug a flash drive (not an SD, which they already had) onto their phone, and Kiwix not being able to locate it.

I guess this makes it a double question:
- can the app pick up more than one external drive?
- can it pick up flash drives?

I've asked the user for a bit more context / info, but here's a first round.

**Comment by MohitMaliFtechiz** [comment]
> A user reported trying to plug a flash drive (not an SD, which they already had) onto their phone, and Kiwix not being able to locate it.

@Popolechien Flas drives will not show in the Kiwix setting for configuration storage, like SD card(). But we can access the content of the flash drive in Kiwix.

We have 2 variants of our application:
1. **PlayStore variant:** In this variant, we have just enabled the file picker in version `3.12.0` and users can pick the ZIM files from their flash drive through the file picker, and Kiwix will ask to copy/move the ZIM file in kiwix's own directory to properly read it.
2. **Website variant:** In this variant, we already have the file picker functionality, so the user can directly pick the ZIM file and Kiwix will read it.

For example: I have attached the "flash drive" to my Samsung device, and Kiwix can read its content via file picker.

https://github.com/user-attachments/assets/26890892-f647-46be-9fb2-fa53af13d4d7


> can the app pick up more than one external drive?
> can it pick up flash drives?

Yes, it can.

**Comment by Popolechien** [comment]
No idea, I'm going to ask

**Comment by Popolechien** [comment]
But should they not reply, thank you very much already 👍

**Comment by Popolechien** [comment]
For the record: user was using 10" Tablet - Lenovo Tab M10 Plus 3rd Gen.   Model: Lenovo TB125FU running on Android 13
The Kiwix app is 3.11.1 from the Android store.
