### ISSUE TITLE
ZIM file location in Android

### ISSUE THREAD

**Issue by SonoftheBaconator** [kiwix/kiwix-android#4076]
I have an Android tablet and I'm looking to transfer some ZIM files between my internal storage and my external storage (micro sd card). In what folder do I find the ZIM files?

**Comment by MohitMaliFtechiz** [comment]
@SonoftheBaconator It is hard to say directly where is your ZIM files are located without knowing which version of Kiwix you are using, and whether you have installed the application from playStore or our website.

But here are my points which help you to find the ZIM files.

If you are using the `3.11.1` or below version of Kiwix.

**For playStore application:**
If you are using the Android 11 and above device then the downloaded ZIM files are located inside the `storage/0/Android/data/org.kiwix.kiwixmobile/Kiwix` folder or if you are using the below Android 11 tablet then the ZIM files are  located in the `storage/0/Kiwix` folder.

**For website APK**
The ZIM files are located inside the `storage/0/Kiwix` folder.

**Comment by MohitMaliFtechiz** [comment]
@SonoftheBaconator Have you found the ZIM files?

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thx, closing as it seems clear now.
