### ISSUE TITLE
Zim downloaded notification does not open the zim file.

### ISSUE THREAD

**Issue by shashank-0-0** [kiwix/kiwix-android#4078]
Clicking on Downloaded zim notification does not open the zim file if the app is not in the background .

**Expected behavior**

Ideally clicking on the notification should open the zim file.

**Steps to reproduce the behavior:**
1. Download a zim file
2. Close the application
3. click on the downloaded notification

**Screenshots**

https://github.com/user-attachments/assets/fd81fe2c-4361-4f58-9dac-127e70ad9b23

**Environment**
- Version of Kiwix Android :  3.11.1
- Device :  pixel 7 Emulator
- OS version :  11

**Comment by shashank-0-0** [comment]
@MohitMaliFtechiz just came across this small issue. We aren't handling notification Intent in onCreate  . Shall i raise a pr ?

**Comment by MohitMaliFtechiz** [comment]
@shashank-0-0 Thanks for opening the issue, yes please open a PR  to call `handleNotificationIntent(intent)` in onCreate like it is in the `onNewIntent` method.
