### ISSUE TITLE
Listing features like Random Article , Full Screen and Find in page are redundant in menu if  Bottom toolbar is enabled

### ISSUE THREAD

**Issue by Koundinyalanka** [kiwix/kiwix-android#408]
![screenshot_20180215-222040](https://user-images.githubusercontent.com/23225734/36269283-d246a150-129e-11e8-8b35-47233ecf0d11.png)

**Comment by Koundinyalanka** [comment]
I can work on this @mhutti1

**Comment by brijeshshah13** [comment]
@Koundinyalanka It is already included in #406. Please close this issue if there are not other developments.

**Comment by brijeshshah13** [comment]
@mhutti1 Please review it. It is already included in #406.

**Comment by mhutti1** [comment]
Already in the scope of #406.
