### ISSUE TITLE
French translation is loosy

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-android#4081]
I spotted a bunch of bad translations to French, for which it was sometimes even hard to understand without translating it back to English.

I think it might to worth to have a whole review before releasing 3.12 (it would be a shame for a company with so many French people).

**Comment by kelson42** [comment]
@benoit74 Would be very thankfull if you coulf do that on TW.

**Comment by kelson42** [comment]
@benoit74 Thank you! Agree with everything you said. We should have only "Read aloud" IMHO.

**Comment by MohitMaliFtechiz** [comment]
> I found some strings which have already been fixed and merged few weeks ago, but are not yet fixed in the nightly ... a bit surprising. 

@benoit74 They are not merged yet(https://github.com/kiwix/kiwix-android/pull/4050/files#diff-131e595015eaa131fe870f22f00f273694be7a70a53c89a9fa730b8f3dbd008b) that's why they are not showing in the nightly APK.

**Comment by benoit74** [comment]
I think we can close the issue now
