### ISSUE TITLE
Do we really want to warn the user who wants to make a donation?

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-android#4083]
When I click the donation button (on the left sidebar), and probably because I asked to be warned of external links (which is the default), I get displayed with a warning saying that I'm going online.

While this is technically true, it feels pretty weird to me:
- I'm being warned of something while I want to spend money ... being warned is never something really comfortable, especially when it's about my money, not sure it is the best way to encourage users to give us money
- While browsing a ZIM is expected to be done offline without consuming my data, I don't think that most people would be surprised by being forced to go online
- And in any case, the link opens in the regular phone browsers, so it is quite visible to the user that he is leaving the app and going online

Is this behavior really intentional or only accidental?

**Comment by kelson42** [comment]
This is "accidental".

**Comment by angrezichatterbox** [comment]
Could I work on removing the warning to the user when they click the donation button?
