### ISSUE TITLE
set colour standards

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#411]
All throughout the app, the color is black, but however, the check boxes and the OK button in the select language are of different colors (blue and green) which looks quite odd.

![sss](https://user-images.githubusercontent.com/32238400/36276484-2050eb7a-12b4-11e8-8802-60deafc65361.png)

I guess both should be black or at least of the same color, if not black.

**Comment by siddharth2010** [comment]
I would like to work on this.

**Comment by mhutti1** [comment]
See https://github.com/kiwix/kiwix-xulrunner/issues/259 I am not sure about the green. I think it might be a system UI thing. It might be a good idea to change it. Can you find any Android docs on it?

**Comment by siddharth2010** [comment]
I will check it out and let you know as soon as I get something.

**Comment by siddharth2010** [comment]
I found a solution to changing the color if the OK button to blue as well. the dialog box is basically an AlertDialog that takes the theme "Theme_AppCompat_Light_Dialog_Alert" in light mode and the theme "Theme_Holo_Dialog" in dark mode. So I just need to modify the theme to change the color of the button. I was thinking of matching the color of the ok button to the color of the checkbox.
