### ISSUE TITLE
The release job is publishing the standalone APK in the GitHub release, which can not be uploaded to `IzzyOnDroid` due to a different `package name`.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#4114]
**Describe the bug**
We have just released version `3.12.0` of our application, and there is a `standalone variant` APK in GitHub release, which can not be uploaded on `IzzyOnDroid` since IzzyOnDroid uses the GitHub release to fetch the APK from our release and uploads it to their platform.  See https://github.com/kiwix/kiwix-android/issues/4053#issuecomment-2503916590

Currently on `IzzyOnDroid` the application is published with the `org.kiwix.kiwixmobile` package name but our current standalone APK package name is `org.kiwix.kiwixmobile.standalone` which we have done to fix the https://github.com/kiwix/kiwix-android/issues/3933. Due to this issue, we have updated our release job to generate and upload the standalone APK to our website and the same APK we are uploading in the github release. 

**Expected behavior**
We have to upload the application with the `org.kiwix.kiwixmobile` package name in the GitHub release so that IzzyOnDroid can easily update our application on their platform.

**Comment by kelson42** [comment]
We are not going to change the appid

**Comment by MohitMaliFtechiz** [comment]
We are just updating the release job to upload the application with the original package name. For the website and nightly APK, there are the same standalone APK will publish as published before.

**Comment by kelson42** [comment]
yes, the consequences will be that apk in github won't be the same as on download.kiwix.org and won't follow new approached decided a few months ago.
