### ISSUE TITLE
The android version 3.12.0 cannot search for Chinese Wikipedia Data, empty result return.

### ISSUE THREAD

**Issue by tedaz** [kiwix/kiwix-android#4121]
Describe the bug
The android version cannot search for Chinese Wikipedia Data, empty result return.

Expected behavior

After type a Chinese word in the earch box, there should be results/candidates listed.

On andriod app, after type the chinese word "中文", showed no result.
With the same Data File, on windows app, after type the chinese word "中文", search result showed without any issue.
It is the andorid app issue.

Download the Chinese Wikipedia Data from https://download.kiwix.org/zim/wikipedia/wikipedia_zh_all_maxi_2024-04.zim
Load the data file wikipedia_zh_all_maxi_2024-04.zim
Type a word in the search box, i.e. "中文"
There will be nothing displayed.

On older version of Kiwix android app, and older Data file, there will be search results/candidates showed.

Data File = wikipedia_zh_all_maxi_2024-04.zim

Environment

Version of Kiwix Android : 3.12.0
Device : Samsung Galaxy Note 20 Ultra
OS version : Android 13

Related issue = https://github.com/kiwix/kiwix-android/issues/4049

Submited this issue again as it marked as will be resolved by version 3.12 and closed previously, however this issue still exist as of version 3.12.0.

**Comment by kelson42** [comment]
Reopening issues again and again does not help. The problem is not here but in the scraper MWoffliner where a ticket is already open.

**Comment by tedaz** [comment]
As of now, it is clearly the Kiwix Android version bug, as the same zim file (https://download.kiwix.org/zim/wikipedia/wikipedia_zh_all_maxi_2024-04.zim) already compiled with the new fixed zimlab.

wikipedia_zh_all_maxi_2024-04.zim can correctly search with Kiwix Android 3.6.0, but on Kiwix Android 3.12.0.
wikipedia_zh_all_maxi_2024-04.zim can correctly search with Kiwix Windows.

so the zim file already fixed, but the Kiwix Android still has bug, that why re-submit this issue again, as it was marked as will be fixed by android version 3.12.

**Comment by lizy14** [comment]
updating ZIM file worked for me. https://github.com/kiwix/kiwix-android/issues/4049#issuecomment-4002151601
