### ISSUE TITLE
Hard-coded values in layouts

### ISSUE THREAD

**Issue by brijeshshah13** [kiwix/kiwix-android#413]
**Actual Behavior**

Layout files have hard-coded values which is not feasible.

**Expected Behavior**

All dimensions of resources must be extracted and referenced accordingly.

**Would you like to work on this?**
Yes.

@mhutti1 Please review.

**Comment by brijeshshah13** [comment]
@kelson42 Please review.

**Comment by mhutti1** [comment]
If you find any hard coded values then trying to change them would be a good idea.

**Comment by brijeshshah13** [comment]
@mhutti1 I sent a PR for the same. Please review it.

**Comment by mhutti1** [comment]
@brijeshshah13 Yeah, just saw. I will get to it soon.

**Comment by brijeshshah13** [comment]
@mhutti1 Its okay. No hurries. :)

**Comment by mhutti1** [comment]
See notes in the closed pull request for remaining work needed

**Comment by kelson42** [comment]
@brijeshshah13 @mhutti1 Can we please clearly document here (in this ticket) what is still to do (I see nothing here https://github.com/kiwix/kiwix-android/pull/449 ?

**Comment by mhutti1** [comment]
@kelson42 its in #415 in a review. Hard to see though as its auto closed.
