### ISSUE TITLE
Adding Transition Animations

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#414]
There are no animations while opening a new article and when going back to index.
I would like to add some sliding animations

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32238400/36278302-78c39442-12b9-11e8-899e-63ae9846bd60.gif)

**Comment by siddharth2010** [comment]
I would like to work on this issue. Can you please assign this to me.

**Comment by mhutti1** [comment]
I personally don't think this would fit the theme of the app. Does chrome have animations when you browse a webpage? @kelson42 thoughts?

**Comment by siddharth2010** [comment]
@kelson42 , I'd love to have your thoughts on this.

**Comment by kelson42** [comment]
@mhutti1 @siddharth2010 I'm a bit overasked here. My answer would tend to be "no" as it does not seem really necessary and this kind of feature tends to consume quite a bit of CPU resources which makes the whole app will probably slower on low-end devies (and we do not want this).
