### ISSUE TITLE
Add animations to Action bar

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#417]
The buttons on the action bar do not have any material design click animation, unlike the tab buttons on the Library screen.

the same problem is with the globe icon in the library screen and the OK button in the select Language screen

![www](https://user-images.githubusercontent.com/32238400/36282003-a890460a-12c5-11e8-89bf-95b183c754e4.gif)

the correct behaviour should be something like this:

![33](https://user-images.githubusercontent.com/32238400/36282530-78171ede-12c7-11e8-97d3-6175c772fa01.gif)

**Comment by RajaVamsi11** [comment]
@mhutti1  I am interested in working on this issue.

**Comment by siddharth2010** [comment]
@RajaVamsi11 , I just noticed something:
I changed android animation speed to 5x from the developer options and noticed that there is an animation in the menu, however it is too fast to notice.
There is however no such animation in the globe icon and the ok button in the sanguage selection dialog box.
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/32238400/36306472-e0455ebe-133d-11e8-8a06-929890f057a3.gif)

**Comment by RajaVamsi11** [comment]
@siddharth2010  yes the animation is too fast to notice.I liked the animation part of opening menu items.
Can we add animations to OK button and Globe icons?

**Comment by siddharth2010** [comment]
I guess what we are looking for is the ripple effect:
![untitled-5](https://user-images.githubusercontent.com/32238400/36308288-fe3451fc-1345-11e8-8b5b-c8dc6906bd12.gif)
It seems easy to impliment, just google it...

**Comment by RajaVamsi11** [comment]
I will @siddharth2010

**Comment by siddharth2010** [comment]
@mhutti1 @RajaVamsi11 , I was just looking at chome and I noticed that chrome too has removed the ripple animation in the overflow options menu in the latest version:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32238400/36416071-01835eb0-164e-11e8-9855-34304fd9d7c1.gif)

So I was wondering whether adding ripple animation, to the overflow options menu, would be good, or not.
I would really live to have your openion regarding this.

**Comment by mhutti1** [comment]
I really don't think its a major issue and likely we should stick with the default (probably what it is now_

**Comment by kelson42** [comment]
Yes, all of this needs more hardware resources and we want a light app working find on low-end devices.
