### ISSUE TITLE
Improve the README of the project

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#419]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

#### Feature Description

The README of the project needs a lot of improvements. Here are a few of them:

- [ ] Add the title of the project as a header at the top.
- [ ] Add badge for build status from travis.
- [ ] Divide data into relevant groups such as build instructions, branch policy etc.
- [ ] Improve the header for Contact and Legal/Disclaimer
- [ ] Add license for the project and a link to it.   
- [ ] Commit style
- [ ] Code style
- [ ] Libraries used

Please suggest something if i have missed it.

**Comment by brijeshshah13** [comment]
@srv-twry Can we have **Roadmap**, **Libraries used** and some **Screenshots** attached as well. It would attract more readability.

**Comment by srv-twry** [comment]
Yes, i will add the libraries used. I thought about the Roadmap and Screenshots as well, i don't think adding screenshots would be okay right now. The application is undergoing a huge amount of changes specially UI, it would be better IMO to wait till the end of GSOC to add the screenshots.

@mhutti1 Can you suggest what to add in the Roadmap. Do we have an abstract plan on how we want to go about developing the features in the application ?

**Comment by knightcube** [comment]
Hi i want to work on this issue. I have experience in android development as well and would like to work on some issues listed. However it seems like all are already assigned to someone or the other but i want to contribute as well. Can someone please guide me?

**Comment by mhutti1** [comment]
There are plenty of issues. A lot of the easy ones are currently being attempted. There are lots of older issues to look at (they might require a rescope or are difficult to reproduce) and if you find any issues yourself you can report those.

**Comment by mhutti1** [comment]
@srv-twry @brijeshshah13 The 4 items listed on our GSoC page would form the basis of a Roadmap along with features implemented in kiwix-lib and then supported in kiwix-android. When I have a bit more time I will look at writing one up in collaboration with other stake holders.

**Comment by ashutoshbsathe** [comment]
Is this still being worked on ? If not then I'm interested in doing so

**Comment by srv-twry** [comment]
@ashutoshbsathe The linked PR is still active, so yeah it is still being worked upon :smile:

**Comment by mhutti1** [comment]
@ashutoshbsathe Please don't edit out comments unless necessary :(. Put an EDIT: below the original so we don't get confused by later comments.
