### ISSUE TITLE
Adding a tutorial screen that includes app icon and instructions.

### ISSUE THREAD

**Issue by harshvardhan-takawale** [kiwix/kiwix-android#421]
**Is it a ?**
 Feature Request
![capture](https://user-images.githubusercontent.com/28982436/36295089-27c68160-130b-11e8-9bed-89d8757c429c.PNG)

  
  
#### Feature Description

For helping the first time users, the app should have a set of instructions that tell them what this app is all about and how to use the app along with the icon.

##Are you willing to work on the issue?

Yes.

**Comment by brijeshshah13** [comment]
@mhutti1 @harshvardhan-takawale I think we provide enough info about the app and it's work around via `Help` screen. Please visit it if you haven't already.

**Comment by harshvardhan-takawale** [comment]
@brijeshshah13 I think the Help screen is a bit more technical for first-time users. The instructions in the tutorial screen would be a bit simpler.

**Comment by brijeshshah13** [comment]
@harshvardhan-takawale Let's wait for @mhutti1. Although, I think instead of adding Tutorial screen, editing the contents of the Help screen would be better.

**Comment by harshvardhan-takawale** [comment]
We can use showcase views to guide them to certain activities during the introduction.
![capture1](https://user-images.githubusercontent.com/28982436/36295631-d84f6e04-130e-11e8-8f95-326476e2a593.PNG)

**Comment by arpank10** [comment]
I think showcase view would be better, help does not provide all instructions like someone has to figure out that to delete a content you have to long click on that.

**Comment by brijeshshah13** [comment]
@mhutti1 @arpank10 @harshvardhan-takawale ShowcaseView sounds better.

**Comment by srv-twry** [comment]
@harshvardhan-takawale If i understood correctly, you want to add a First Launch Activity to the application, right ? 
If yes, then seems like a good idea.

**Comment by harshvardhan-takawale** [comment]
Yes. I will start working on it as soon as the mentors give a thumbs up.

**Comment by mhutti1** [comment]
@harshvardhan-takawale I would go ahead and build a prototype of this that we can review and then see how it flows

**Comment by harshvardhan-takawale** [comment]
So I can work on it, right? I will make a prototype and share it with you. Also, can we use new opensource libraries while contributing to the org? @mhutti1

**Comment by mhutti1** [comment]
@harshvardhan-takawale You can use opensource libraries however keeping apk size down is also important.

**Comment by harshvardhan-takawale** [comment]
@mhutti1 So I worked on it and here is a demo. (I didn't pay a lot of attention to text,drawables, and color, I'll change it later and I can try animating the swipe gesture)
![onboard](https://user-images.githubusercontent.com/28982436/36341638-53debd32-1417-11e8-8698-8a94e2d8cef2.gif)

**Comment by rashiq** [comment]
I think something like this wasn't what we had in mind but more of a paging
wizard

**Comment by harshvardhan-takawale** [comment]
You mean something like in the image in my issue?

**Comment by mhutti1** [comment]
@harshvardhan-takawale This could work well possibly. There is currently a vertical offset issue and its too quick do you have this uploaded anywhere to test?

**Comment by harshvardhan-takawale** [comment]
I have rectified the offset issue. Where should I upload it, to my forked repository? @mhutti1

**Comment by mhutti1** [comment]
Yeah

**Comment by harshvardhan-takawale** [comment]
Done. It is in the "showcase" branch

**Comment by harshvardhan-takawale** [comment]
@mhutti1 Did you take a look at the feature? Should I implement it in the actual app and make a PR?

**Comment by kelson42** [comment]
@ISNIT0 had a made a mockup of something similar. Would be great to link it here.

**Comment by mhutti1** [comment]
I will look at it soon. You can create a pr if you want but beware it might be for nothing if we need to redesign the suggestion.

**Comment by ISNIT0** [comment]
@kelson42 The mockups weren't fully featured/thought out, they can be seen here though: https://www.figma.com/file/aloDDgh0zCRTtRYwURNdXdU6/KIWIX

**Comment by mhutti1** [comment]
I think the scope of this issue can vary drastically. We should probably start by implementing a simple screen.

**Comment by harshvardhan-takawale** [comment]
@mhutti1 Should I start implementing this? Can you state your ideas so that I can work on that, as in what do we exactly want? (Showcase view kind of thing or a viewpager)

**Comment by kelson42** [comment]
In general, I think that we should focus to fix bugs and make the app easier to use. If we achieve that I strongly believe we won't have to write tutorials.

**Comment by harshvardhan-takawale** [comment]
I don't know, many apps these days have something like this for first-time users so that they do not get overwhelmed when they start using the app, so I just made a basic mockup like @mhutti1 suggested. We can add or remove things from this basic structure.

**Comment by abdulwd** [comment]
Closed via #754
