### ISSUE TITLE
Make search button's Onclick Action more precise.

### ISSUE THREAD

**Issue by moksh-mahajan** [kiwix/kiwix-android#423]
The **search bar** opens up even when you click on **"Test"** i.e the space between the **3 bar icon** and the actual **search** button. Change the code so that **seach bar** will only appear when the **actual search icon**(**magnifying lens**) is clicked on.

**Comment by brijeshshah13** [comment]
@mhutti1 @moksh-mahajan Sounds good. Go ahead and refine it.

**Comment by mhutti1** [comment]
Won't fix. Feature not bug

**Comment by moksh-mahajan** [comment]
Ok @mhutti1
