### ISSUE TITLE
Negative Image on Help Screen in night mode

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#425]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : App
  * version of the software you use : Version 2.3 Build: 55
  * device / operating system : Android 7.0 (Samsung Galaxy S6)
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
  In the night mode, the image on the help screen turns negative:
  screenshot:
![screenshot_20180216-102025](https://user-images.githubusercontent.com/32238400/36298910-83da6024-1320-11e8-8723-663d709d6078.png)
**This problem is only in this image. There is no problem in the images from wikipedia**
  * When does this occur? 
  In the night mode only
#### Steps to reproduce:

  1. enable night mode in settings
  2. Go to the help screen
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
  I think the color of the image should not be negative.

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
#### Feature Description

Please describe the feature you want to add to the project.

**Comment by siddharth2010** [comment]
I would like to work on this issue.

**Comment by mhutti1** [comment]
I think it's better imo as there is less blinding white. Anyone else have any opinions?

**Comment by siddharth2010** [comment]
Now that you pointed it out, I guess you are right; the white background would sort of ruin the whole purpose of the night mode...

**Comment by mhutti1** [comment]
If you don't like the look you could try recolouring it to look better while keeping minimal white else we can close this.

**Comment by siddharth2010** [comment]
sure I will tinker around with it on photoshop, and see if I can improve it in some way...

**Comment by siddharth2010** [comment]
I think that this is probably the best solution. I thought of making the background grey instead of brown, but I think that brown gave a better overall highlight to the image... So I guess we can close this issue then.

**Comment by siddharth2010** [comment]
@mhutti1 @kelson42 @srv-twry What do you think about this?

![new](https://user-images.githubusercontent.com/32238400/36426216-66471474-166f-11e8-8612-d06dffefabfe.png)

Adding a blue light filter not only makes it easier for the eyes but also helps in retaining the original feel of the image that was somehow lost in making it negative...

Do you suggest some other edits?

**Comment by siddharth2010** [comment]
Here are the images:
original:
![kiwix_welcome](https://user-images.githubusercontent.com/32238400/36426393-d6bdedea-166f-11e8-9be8-8566e4684e3b.png)
new (for night mode):
![sid](https://user-images.githubusercontent.com/32238400/36426477-1c2a119c-1670-11e8-92a3-14f145c8894f.png)

**Comment by siddharth2010** [comment]
I can remove the dark high light from the ends if you like...

**Comment by mhutti1** [comment]
Looks good to me.

**Comment by siddharth2010** [comment]
@mhutti1 @srv-twry @kelson42 , to do this task, I was thinking of using Data Binding (https://developer.android.com/topic/libraries/data-binding/index.html) in the help.xml layout file to set the src of the image based on the boolean value of the nightMode variable from userPreferences.

Do you think this is the correct way, or is there any other better way.

**Comment by mhutti1** [comment]
@siddharth2010 I have never used data bindings before but they look interesting. If you want to try to use them then sure go ahead and I am sure I will learn something.

**Comment by srv-twry** [comment]
@mhutti1 @siddharth2010 I have used Data bindings before and it's a really good library to use. Although IMO we should either use Data bindings in each and every layout or shouldn't use it all. There should be consistency throughout the application.
