### ISSUE TITLE
Make the search button onclick action more precise.

### ISSUE THREAD

**Issue by moksh-mahajan** [kiwix/kiwix-android#429]
The search bar pops up even if we click on the space between the actual search button and the 3 bar icon. Make appropriate changes in the code so that it will open search bar only when search button is clicked.

**Comment by moksh-mahajan** [comment]
Kindly review this issue @mhutti1  @kelson42

**Comment by srv-twry** [comment]
@moksh-mahajan can you attach a GIF ?

**Comment by arpank10** [comment]
@moksh-mahajan I think @mhutti1 already closed your previous issue saying that it is not a bug. This issue is the same. Please check and close the issue.

**Comment by srv-twry** [comment]
@moksh-mahajan Please avoid doing this. You were already told that it isn't a bug. Creating the same issue multiple times won't make it any relevant.
It is strictly advised not to repeat this.

**Comment by moksh-mahajan** [comment]
@srv-twry  sorry my bad, I am new to github :(
