### ISSUE TITLE
Add i18n check to Kiwix Android's compilation script

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#43]
_From @kelson42 on December 11, 2016 12:55_

Your task is to implement a check to detect string literals in Kiwix app source code and - using this new feature - move the few detected string literals still in the code to the string resource file.

Steps to reproduce:

- Compile Kiwix for Android

What you get:

- Compilation run fine - even if string literals (hard coded strings not in our strings.xml file) are in the code.

What we want:

- Compilation should die with an informative error.

What do to:
- Change the compilation process to forbids string literals (non-externalized strings/NON-NLS) in the code.
- Put all the strings which has to be localized (only user facing strings) in the strings.xml file (this gets tranlated by volunteers automatically)
- Put a tag to skip detection (compilation error) on all strings which have to stay as literals in the code (i.e id codes).

Helpful resources:
- https://developer.android.com/studio/write/lint.html
- https://sites.google.com/a/android.com/tools/recent/non-translatablestrings

_Copied from original issue: kiwix/kiwix#385_

**Comment by mhutti1** [comment]
As we are reworking how we build our apps we should think about this.

**Comment by kelson42** [comment]
Is that possible to add a "lint" test during the build and just stop building if the test fails?

**Comment by mhutti1** [comment]
Yeah I think that should be possible with gradle.

**Comment by mhutti1** [comment]
https://github.com/kiwix/kiwix-android/pull/97
