### ISSUE TITLE
Inappropriate dialog box in downloading fragment

### ISSUE THREAD

**Issue by RajaVamsi11** [kiwix/kiwix-android#430]
**Is it a ?**
 Bug report
## Bug Report
When a user want to cancel the downloading wiki article,a dialog box is popping up with white shaded in background.I attached a screenshot below.

### Step 2 : What is your environment ?
  * browser / app : ___app__
  * version of the software you use : _2.2 Build:53__
  * device / operating system : ___Android Version 4.4.2 ( ASUS_T00J)__
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
![screenshot_2018-02-16-16-35-54](https://user-images.githubusercontent.com/30550059/36305562-1795b930-133a-11e8-9471-ddf7861cd5e1.jpg)

  * When does this occur? 
When user cancel the ongoing download in downloading fragment.

  * What should be the behaviour from your point of view? How do you expect the service to work?
    The behaviour of dialog box should be simple one clearing the white background as seen in the screen shot.

**Do you want to work on this?**
Yes

@mhutti1 @kelson42   Your reviews please?

**Comment by RajaVamsi11** [comment]
@mhutti1  I thought it was solved because  the dialog box is normal when i imported the latest version code from github.

**Comment by mhutti1** [comment]
It is not fixed for me on an API 16 emulator.

**Comment by RajaVamsi11** [comment]
Ok..i will work on it @mhutti1

**Comment by kelson42** [comment]
@RajaVamsi11 @mhutti1 Is that still a problem with 2.5?
