### ISSUE TITLE
Delete unused import statements

### ISSUE THREAD

**Issue by RajaVamsi11** [kiwix/kiwix-android#431]
After going through the code base of app ,I found there are import statements which are not (app.. 8-10 import statements) used in that class.My idea is to delete the unused import statements.

**Would you like to work on it?**
Yes.

@mhutti1 @kelson42 what do you say?

**Comment by mhutti1** [comment]
You can do this if you want. Its not a huge issue at the moment.

**Comment by RajaVamsi11** [comment]
I will

**Comment by srv-twry** [comment]
@RajaVamsi11 I would suggest you please don't go ahead with it right now.
We can do it after we have a plan on how to avoid unused imports from creeping in the project at the first place. I was thinking about opening an issue to setup Codacy PR reviews which can be configured to take care of things like unused imports, unused variables and methods in a PR. 
Then only we can clear these and make sure we don't get any of them in the future.

@mhutti1 What do you think ? If you like the idea, i will open an issue for it and add more details and examples.

**Comment by mhutti1** [comment]
@srv-twry That certainly sounds interesting. If you want to open an issue go ahead. We already have a basic linter I am not sure what the advantages of other specialised tools would be.

**Comment by RajaVamsi11** [comment]
@srv-twry  Can i close this issue?
