### ISSUE TITLE
Text headings of both the app drawers are not proper.

### ISSUE THREAD

**Issue by moksh-mahajan** [kiwix/kiwix-android#432]
The text headings of the left and right app drawer are little trimmed from the top. I have attached screenshots. Kindly review it.

![screenshot_2018-02-16-21-40-52-755_org kiwix kiwixmobile](https://user-images.githubusercontent.com/36201975/36317625-9720e98a-1363-11e8-9c41-3fb96d3bb7b7.png)
![screenshot_2018-02-16-21-40-47-036_org kiwix kiwixmobile](https://user-images.githubusercontent.com/36201975/36317627-97c1c3aa-1363-11e8-9103-990c0d7473d4.png)

**Comment by mhutti1** [comment]
Can you post your device details. Following the https://github.com/kiwix/kiwix-android/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by moksh-mahajan** [comment]
@mhutti1 
browser / app :Kiwix 
version of the software you use : 2.2
device / operating system : Xiaomi Redmi 1s/ Android version 4.4.4

**Comment by moksh-mahajan** [comment]
@siddharth2010 Mine too!!

**Comment by harsh-2711** [comment]
Is this issue still open?

**Comment by abdulwd** [comment]
Redundant by #832.
