### ISSUE TITLE
Download resumes on restarting app even after stopping.

### ISSUE THREAD

**Issue by arpank10** [kiwix/kiwix-android#433]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

## Bug Report

On stopping the download, it stops, but as soon as kiwix is restarted, it resumes. Stopping from both the library downloads and notification gives this behaviour.
### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : app
  * version of the software you use : 2.3 Build 55
  * device / operating system : Android 7.1.1( Lenovo K8 plus)
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
![whatsapp video 2018-02-16 at 9 35 14 pm](https://user-images.githubusercontent.com/24573296/36317739-efbea3f2-1363-11e8-98da-6fdfe383eefa.gif)

  * When does this occur? 
After stopping download and restarting.
#### Steps to reproduce:

  1. Start a download and stop it from notification or download screen
  2. Restart app
  3. Download resumes
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
Download should not resume.

**Would you like to work on this?**

Yes

**Comment by MayankChuriwal** [comment]
Does this problem still continues or it has been fixed? @arpank10 because I am not getting this problem.

**Comment by arpank10** [comment]
The PR is still not merged I think. @MayankChuriwal  Did you kill the app and then restart?

**Comment by MayankChuriwal** [comment]
Yes I did kill the app and restarted it. Did it happen once or the problem still continues? @arpank10

**Comment by arpank10** [comment]
It happens everytime. I have made a pull request solving this issue. It has not merged yet.
