### ISSUE TITLE
Adding a search option to bookmark page

### ISSUE THREAD

**Issue by Nair18** [kiwix/kiwix-android#435]
When you have too many bookmarks to deal with its better to have a "search in bookmark" option which will make it easier to search through marked contents instead of just linearly searching.
  

![screenshot_2018-02-17-01-43-35-619_org kiwix kiwixmobile](https://user-images.githubusercontent.com/15075776/36327547-eb7cf7a0-1384-11e8-8614-c98571a19aba.png)

**Comment by brijeshshah13** [comment]
@mhutti1 @Nair18 Nice idea. Go ahead and implement it.

**Comment by mhutti1** [comment]
I would hold out on implementing this now as per #55 @kelson42 Is this going to be included in the changes?

**Comment by moksh-mahajan** [comment]
Appreciate this idea!!

**Comment by kelson42** [comment]
@mhutti1 I confirm, I would not invest time to implement new features on the bookmarks. For the future, all the bookmarks features should be provided by the core library so the kiwix-android developers can focus on UI stuff.
