### ISSUE TITLE
Crunch PNG files

### ISSUE THREAD

**Issue by brijeshshah13** [kiwix/kiwix-android#437]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request  
  
#### Feature Description

`aapt` tool can optimize the image resources placed in `res/drawable/` with lossless compression & can convert a true color PNG that does not require more than 256 colors to an 8-bit PNG with a color palette.

**Proof**

Before:
![before](https://user-images.githubusercontent.com/18366144/36328173-2d8f6e28-1387-11e8-8507-bad4d49e0d47.png)
After:
![after](https://user-images.githubusercontent.com/18366144/36328178-327a4372-1387-11e8-82fe-df3ec85433cc.png)

As new image resources will added in the future, this feature will make sure that they are optimized first.

I will be also removing unused resources.

@mhutti1 @kelson42 Please review.

**Comment by kelson42** [comment]
@brijeshshah13 just go ahead please and make a PR.

**Comment by brijeshshah13** [comment]
@kelson42 The PR has already been issued. It is pending due to some rebasing issues which will be issued as soon as @mhutti1 guides me about the commits he wants in the branch to be able to merge.
