### ISSUE TITLE
Add fastscroller in search option

### ISSUE THREAD

**Issue by ArifinCse** [kiwix/kiwix-android#440]
![screenshot-1494-e1427143922842](https://user-images.githubusercontent.com/35919505/36339507-d4211f38-13f1-11e8-92a2-b0722eca0d72.png)

#### Feature Description

A simple FastScroller where a user can also search by index (alphabetically).

**Comment by kelson42** [comment]
@ArifinCse I do not understand where do you want to build that exactly?

**Comment by mhutti1** [comment]
I assume this is for scrolling through content. Is this an external library or does it come with the support libraries?

**Comment by ArifinCse** [comment]
@mhutti1 external library is not needed. After indexing content, you can scroll to that position manually. All of the code logic for indexing and scrolling need to be written.

**Comment by srv-twry** [comment]
@ArifinCse Where will you apply this ? I mean which list/RecyclerView do you want to apply it on ?

**Comment by ArifinCse** [comment]
@srv-twry In SearchActivity.java (listview). Keep an available titles (uri) in sorted order in a list. Then apply fastscroller. In current implementation,  search window is empty for the very first time. Then it keeps recent search history shown when enters into search window. In my proposal, list is filled up with available uri and uris are indexed. Most recent search can be shown when a user tap on search icon on top of listview. (for recent history, it's like google search  showing suggestions).

**Comment by ArifinCse** [comment]
Indexing logic is totally handled by code. We don't need to use any library. Non-latin alphabets have ascii value. So we can index using ascii value or use "Trie data structure" or hashing, any logic can be applied for indexing depending on the situation with .
Added value:
- User gets more information in the search window.
- User gets search results more faster.Instead of typing letters,  by clicking on index, user gets the result.
- User friendly. Supports both typing and clicking.
- Indexing can be done based on device language support too.

**Comment by savannahar68** [comment]
I want to work on this issue,please assign it,
Thank you!

**Comment by kelson42** [comment]
Does not make sense (anymore) because:
* suggestions start with the same letter as given in search box
* Suggestions are not sorted alphabetically
