### ISSUE TITLE
text being cut on Help screen

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#442]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : App
  * version of the software you use :  2.3 Build 55
  * device / operating system : Android 7.0 (Samsung Galaxy S6)
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
The text at the bottom of the help screen is being cut.
this is the screenshot of the bottom of the app:
![image](https://user-images.githubusercontent.com/32238400/36340041-e25d1f64-13f8-11e8-9011-f29056e44191.png)
while this is the one that should actually be displayed:
![image](https://user-images.githubusercontent.com/32238400/36340048-2c575a8a-13f9-11e8-955c-efda2957d9d4.png)

  * When does this occur? 

#### Steps to reproduce:

  1. navigate to the bottom of the help screen
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

The text should not be cut and the card ending should be properly displayed

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
#### Feature Description

Please describe the feature you want to add to the project.

**Comment by siddharth2010** [comment]
I would like to work on this issue

**Comment by kelson42** [comment]
@siddharth2010 I do not understand the problem, can you not just scroll down?

**Comment by siddharth2010** [comment]
yes thats the problem... I cant scroll down below that

**Comment by kelson42** [comment]
@siddharth2010 Then go ahead :)

**Comment by srv-twry** [comment]
@siddharth2010 Sorry but i couldn't understand what you meant by text get's cut ? Can you please elaborate :)

**Comment by siddharth2010** [comment]
I checked the app with quite a few devices, and came to the conclusion that this is an issue with the Samsung android rom and not  with the app. this issue is present in both Samsung S6 and S7.

**Comment by omkarprabhu-98** [comment]
@siddharth2010  Even I am facing the same issue. I have Motorola G4 Plus.

**Comment by brijeshshah13** [comment]
@siddharth2010 @omkarprabhu-98 Can you please try adding `android:paddingBottom="20dp"` (you can change the value to what suits the best) and try to test it again on the devices in which the last card gets cut off and let me know if that works?

**Comment by siddharth2010** [comment]
@omkarprabhu-98 , I actually tried it on a moto g4 plus myself, and it was working perfectly.

**Comment by siddharth2010** [comment]
@brijeshshah13 , I already tried that. It doesn't work. However, adding a "space" widget of height 85dp in the ind fixes this issue on my device. But then the devices on which the app was earlier showing correctly start showing a blank space in the end...

**Comment by siddharth2010** [comment]
Hey @brijeshshah13 , @omkarprabhu-98  I found a fix.

**Comment by siddharth2010** [comment]
I uninstalled all instances of the app from my phone and deleted the kiwix associated folder from the internal storage. Then I reinstalled the app and now it's working perfectly on my phone.

**Comment by siddharth2010** [comment]
This does sounds a bit unlikely, but after opening and closing the app a couple of times, the same thing started happening again, and so now the text is again being cut.

**Comment by brijeshshah13** [comment]
@siddharth2010 Okay. Thank you for the updates. Can you please try to change the `layout_height` to `match_parent` and see if that works for the good?

**Comment by siddharth2010** [comment]
sure, just a second.

**Comment by siddharth2010** [comment]
I tested this on 3 phones: 2 android 7.0 and one android 6.0.1. 
heres the report:
Samsung S6, and Moto g4+ (android 7.0): text was being cut initially,
Coolpad 3600I android 6.0: layout was initially perfect.

after adding padding to scrollview of 85dp, the layout on samsung and moto phones was perfect however, on coolpad it showed a persistant space on the screen.

the rest of the fixes had no effect.

**Comment by brijeshshah13** [comment]
@siddharth2010 Alright. Well, let's put this issue alive then until someone gets a workaround or a solution.

**Comment by siddharth2010** [comment]
sure.

**Comment by harsh-2711** [comment]
I have made necessary changes in PR #524. Please review it.

**Comment by brijeshshah13** [comment]
@jb1998 Indeed. @harsh-2711 is currently working on the issue with another approach. However, you can create a new issue to solve this particular issue.

**Comment by jb1998** [comment]
@brijeshshah13 Okay.I opened a new issue to remove this unwanted relation between "Keep Toolbar Visible" and bottom text :)

**Comment by abdulwd** [comment]
Redundant by #803.
