### ISSUE TITLE
change font color of "Clear all history" dialogbox

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#453]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : App
  * version of the software you use : 2.3 Build 55
  * device / operating system : Android 7.0 (Samsung Galaxy S6)
  
### Step 3: Describe the problem:
The text color of the whole text in the clear all history dialog box is blue.
screenshot:
![screenshot_20180218-141852](https://user-images.githubusercontent.com/32238400/36350051-81cecd82-14b6-11e8-8908-8d4d13b7638b.png)

The color of the main text and the heading of the dialog box should be black, not blue.

  * What do you obtain? A copy of the error message or a screenshot is always useful

  * When does this occur? 

#### Steps to reproduce:

  1. Go to settings
  2. tap on clear history
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

The color of the main text and the heading of the dialog box should be black, not blue.

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
#### Feature Description

Please describe the feature you want to add to the project.

**Comment by kelson42** [comment]
What does the Android UI guidelines say about that? I hardly believe that blue color has been chosen randomly.

**Comment by siddharth2010** [comment]
Actually the blue color was chosen here: https://github.com/kiwix/kiwix-xulrunner/issues/259

**Comment by kelson42** [comment]
@siddharth2010 Thank you for digging out that ticket. @mhutti1 You are in lead here, what ever the decision is we need to be coherent and being able to explain why we do that way.

**Comment by mhutti1** [comment]
Text like this should certainly be black
