### ISSUE TITLE
Create a custom Toast View

### ISSUE THREAD

**Issue by RajaVamsi11** [kiwix/kiwix-android#456]
**Is it a ?**

- [  ] Bug Report

- [ ] Feature Request

### Step 2 : What is your environment ?
  * browser / app : ___app__
  * version of the software you use : ___2.3 Bulid:55__
  * device / operating system : _android emulator____
  
### Step 3: Describe the problem:

When a user click an article in the list of Wikipedia articles in online fragment,if the phone has no sufficient memory to down load , Toast message will  be produced along with snackbar. the background colour of the toast message and the online fragment background colour  resembles.It looks somewhat weird.
My idea is to create a customized toast view for that toast message.(Changing background color and other changes)

  * What do you obtain? A copy of the error message or a screenshot is always useful
![imageedit_3_6945749916](https://user-images.githubusercontent.com/30550059/36352566-d11170f0-14e0-11e8-969d-e6cd8af216c0.png)
 Cropped photo of screeshot

 
**Would you like to work on it?**
Yes

@mhutti1 @srv-twry  your reviews please?

**Comment by brijeshshah13** [comment]
@RajaVamsi11 Can you please specify your phone details and android version because for me it's working all fine. Here:

![screenshot_20180218-211521](https://user-images.githubusercontent.com/18366144/36353817-2037aeb4-14f1-11e8-9b45-ab1c8d71cad4.png)

**Comment by RajaVamsi11** [comment]
It is in emulator @brijeshshah13

**Comment by brijeshshah13** [comment]
@RajaVamsi11 Still can you please post the Android version so that we can confirm that it is infact the issue of the emulator.

**Comment by RajaVamsi11** [comment]
Android version 8.1.0  (Emulator)

**Comment by mhutti1** [comment]
Lets keep this open for a bit and see if anyone can reproduce unless you have specific information that leads you to think this is the emulato.,

**Comment by paologarcia002** [comment]
I don’t have the screen shot but when I was working earlier today this happened, although I’ll redo it and get a screen cap if I see if the bug gets reproduced again.

**Comment by RajaVamsi11** [comment]
ok..lets wait and see @mhutti1

**Comment by cmeher196** [comment]
@RajaVamsi11 hey is this issue still open?? or issue is fixed?? if not then can i work on it?

**Comment by srv-twry** [comment]
@cmeher196 
I would suggest you please go through the above discussion.

**Comment by RajaVamsi11** [comment]
@cmeher196  The issue was with emmulator itself.It works fine in actual devices.

**Comment by mhutti1** [comment]
Closing this as we should use the standard android toast imo.
