### ISSUE TITLE
Increment the compile and target SDK version

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#457]
**Is it a**

- [x] Bug Report

- [ ] Feature Request

## Bug Report
The compileSdkVersion and targetSdkVersion which are set to versions 26 and 25, respectively, must be changed to 27 as latest Android APIs must be used to make use of the latest features. Along with it build tools version has to be changed and Travis CI has to be reconfigured.

@mhutti1 @kelson42 Can you please review the issue? I will fix it.

**Comment by kelson42** [comment]
@abdulwd Would that brake any compatibility with older devices?

**Comment by abdulwd** [comment]
@kelson42 That will not break any compatibility with older devices as minSdkVersion will remain same.

**Comment by kelson42** [comment]
@abdulwd thx
@mhutti1 this decision is for you to make taken.

**Comment by abdulwd** [comment]
@mhutti1 I have sent a PR resolving this issue. I never saw you have assigned this to yourself. :(
But the issue is resolved with the PR, so you can merge it if you have not worked on this issue. ;-)
