### ISSUE TITLE
Add Dialog Box

### ISSUE THREAD

**Issue by RajaVamsi11** [kiwix/kiwix-android#458]
**Is it a ?**

- [ ] Bug Report

- [  ] Feature Request

#### Feature Description

In online fragment there are many Wikipedia articles available to download.When an user click on any particular article,it will begin to start downloading.

My feature request is that to add a conformation dialog box (To confirm download)  which pops up when a user clicks on the article to download in online fragment.

**Would you like to work on this?**
Yes

Your reviews please @mhutti1  @kelson42

**Comment by kelson42** [comment]
I have no strong opinion on this.

**Comment by RajaVamsi11** [comment]
@kelson42  What does it mean??

**Comment by kelson42** [comment]
@RajaVamsi11 I'm neither a strong supporter nor a strongly against.

**Comment by srv-twry** [comment]
@RajaVamsi11 I disagree on this. It isn't standard to confirm for downloading things. 
We usually confirm for changes which aren't invertible for eg. deleting something. If the user starts downloading accidently, he/she can easily cancel the downloading without any harm done.

**Comment by RajaVamsi11** [comment]
@srv-twry  OK. Can i close it?

**Comment by srv-twry** [comment]
Let's wait for other's suggestion on this.

**Comment by mhutti1** [comment]
I don't think this is a problem. We already have one for non WiFi connections,
