### ISSUE TITLE
Migrate to RxJava 2.x

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#459]
**Is it a**

- [x] Bug Report

- [ ] Feature Request

## Bug Report
**RxJava 2.x** was released _a long time back_ and it was completed written from scratch and it evolved out of **RxJava 1.x**. Presently, RxJava 1.x is being used in the app but we must migrate to **RxJava 2.x** as it is more powerful and will have longer support. Most libraries have switched to **RxJava 2.x**. I can see 10 instances where RxJava is used so migrating to **RxJava 2.x** at this time will not be difficult but in future, it will become more difficult as the codebase grows.

  * I have experience in using RxJava so I can do the migration.

**Comment by abdulwd** [comment]
@kelson42 @mhutti1 Please review this issue.

**Comment by kelson42** [comment]
@mhutti1 For you, no clue about that.

**Comment by srv-twry** [comment]
I agree. We should upgrade to RxJava2 since it is now the new standard.

**Comment by mhutti1** [comment]
Sure go ahead.
