### ISSUE TITLE
Add Android 7.1.1 Circular icons

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#46]
_From @mhutti1 on December 6, 2016 23:4_

We should implement circular icons for the main app and for the custom apps. I am not entirely sure how best to do this for custom apps @kelson42 do you have any ideas.

https://developer.android.com/about/versions/nougat/android-7.1.html?utm_campaign=android_launch_androidnougat_120516&utm_source=anddev&utm_medium=blog#circular-icons

_Copied from original issue: kiwix/kiwix#381_

**Comment by kelson42** [comment]
@mhutti1 Sounds relatively trivial!? For custom apps, each app round icon should indeed be created. They are all in their respective directories in the "custom" directory. Not sure how they are put in the "res", but that should be easy.

**Comment by kelson42** [comment]
_From @mhutti1 on December 7, 2016 11:50_

@kelson42 Currently we do this by python script calling a linux command. I don't know how it would work for a circle as it would require cropping in a weird way.

**Comment by kelson42** [comment]
_From @EladKeyshawn on December 7, 2016 11:56_

@mhutti1 I think it could be done by an online service of which we can upload the icon with specific parameters and get the result. I'll look into it later.

**Comment by kelson42** [comment]
@mhutti1 @EladKeyshawn Could someone of you do it for Kiwix, I would then do the necessary for custom apps (maybe create a new feature request if necessary).

**Comment by kelson42** [comment]
_From @mhutti1 on December 31, 2016 17:23_

@kelson42 I have added the assets for the Kiwix icon (not the code yet). The custom apps need just one icon with I think the highest resolution and then we can get the python script to create the different resolutions at build as we do at the moment.

**Comment by kelson42** [comment]
Here is a tool to do them https://jgilfelt.github.io/AndroidAssetStudio/icons-launcher.html. I have created one for the custom_app "phets". Can someone update the kiwix-build script to deal with that?

**Comment by kelson42** [comment]
@mhutti1 I do not know how important/urgent is that, but if you confirm it's not, I would postpone to 3.0.

**Comment by Koundinyalanka** [comment]
@mhutti1 I will solve this issue

**Comment by Koundinyalanka** [comment]
Should I modify the existing Icon? @mhutti1

**Comment by Koundinyalanka** [comment]
How about this @mhutti1 
![web_hi_res_512](https://user-images.githubusercontent.com/23225734/36260930-d312179c-1288-11e8-976c-df9369e41780.png)

**Comment by mhutti1** [comment]
Yeah is there some black at the bottom though?

**Comment by Koundinyalanka** [comment]
![ic_launcher](https://user-images.githubusercontent.com/23225734/36261253-c73630b0-1289-11e8-8bdc-c70d2f2a3fea.png)

**Comment by Koundinyalanka** [comment]
How about that? @mhutti1

**Comment by mhutti1** [comment]
Looks good to me.

**Comment by Koundinyalanka** [comment]
![screenshot_20180215-200832](https://user-images.githubusercontent.com/23225734/36263740-e01497b4-1290-11e8-8bd8-77ca9c519f2d.png)
Looks like this in launcher see bottom round icon @kelson42 @mhutti1

**Comment by RohanBh** [comment]
I think this ticket can be closed as the launcher icon has been made an [adaptive icon](https://youtu.be/5MHFYfXno9c) in [this PR](https://github.com/kiwix/kiwix-android/pull/496).

**Comment by RajaVamsi11** [comment]
Can we close this issue? @mhutti1

**Comment by mhutti1** [comment]
I do not think this is resolved as the adaptive icon only deals with the vanilla app and only on Oreo+. We still have the task of a script to possibly build rounded apps for custom apps.

**Comment by kelson42** [comment]
@macgills As you are working on adaptive icon, have you fixed that one? What would be needed?

**Comment by macgills** [comment]
Android Asset Studio also produces round icons, this will be fixed

**Comment by kelson42** [comment]
@macgills Great, just secure the stuff is fixed for Kiwix app as well please.
