### ISSUE TITLE
Add GPL3 header in each source file

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#460]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

#### Feature Description

As discussed in #420, we should all GPL3 header like in [this](https://github.com/kiwix/kiwix-xulrunner/blob/master/src/server/kiwix-serve.cpp) in every source file.

**Comment by kelson42** [comment]
@srv-twry yes!

**Comment by abdulwd** [comment]
In my opinion, we must keep this open for new contributors. We can accept the addition of the licence to a single source file from each new contributor. So in this way, it will help different new contributors learn how to contribute to open source organisation.

**Comment by srv-twry** [comment]
Cool with that.

**Comment by RajaVamsi11** [comment]
@srv-twry  The issue is about copying  and pasting  the given GPL3 header in the example file above in all source files of app.
Can i start  doing it ?

**Comment by srv-twry** [comment]
@RajaVamsi11 You have already contributed to the project multiple times. I would suggest you pick up some more involving issues. This can be left for first timers.

**Comment by ashutoshbsathe** [comment]
Can I do this ? Or this has already been assigned ?

**Comment by kelson42** [comment]
@ashutoshbsathe Yes you can

**Comment by ashutoshbsathe** [comment]
@kelson42 Thanks, 
The header should have year 2018 right ? And only java code needs these right ? 
I checked a couple of android apps and they are only having license on manifest and java code
Should I do the same ? Thanks again

**Comment by kelson42** [comment]
Yes and yes

**Comment by kelson42** [comment]
@ashutoshbsathe thx for your work!
