### ISSUE TITLE
Remove redundant "kiwix" label from each entry in online tab in library

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#461]
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request

- [x] Something Else

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : App
  * version of the software you use : 2.3 Build 55
  * device / operating system : Android 7.0 (Samsung Galaxy S6)
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
There is a "kiwix" label in each entry of the list in the online tab in library.
It is redundant and not needed
screenshot:
![screenshot_20180219-002646](https://user-images.githubusercontent.com/32238400/36355624-1d25f8aa-150c-11e8-9e8c-4e317fdcfd3e.png)

  * When does this occur? 

#### Steps to reproduce:

  1. Go to help
  2. Tap on "get content"
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

The "kiwix" label is redundant and not really needed. 
I think we should remove it and also shift up the right column of each list item by one line.
Expected output:
![screenshot_20180219-002646](https://user-images.githubusercontent.com/32238400/36355705-354b4f60-150d-11e8-8e9e-350d4c4e0a2b.png)

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
#### Feature Description

Please describe the feature you want to add to the project.

**Comment by kelson42** [comment]
Kiwix is the "publisher" metadata of the content. This is maybe a good idea.

**Comment by siddharth2010** [comment]
So do you think we should go ahead with removing it?

**Comment by mhutti1** [comment]
Shifting up likely wouldn't work as some descriptions are quite long.

**Comment by cmeher196** [comment]
since one is working on this issue am trying to remove it.

**Comment by mhutti1** [comment]
Closing this as the publisher might have an effect for local ZIM files and if we are going to remove it it would be part of a larger redesign.
