### ISSUE TITLE
Zoom controls option in settings seems redundant. 

### ISSUE THREAD

**Issue by Nair18** [kiwix/kiwix-android#462]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 2 : What is your environment ?
  * browser / app : kiwix
  * version of the software you use : latest
  * device / operating system : redmi 1s/4.4 kitkat
  
### Step 3: Describe the problem:
       I find the zoom controls option in settings redundant because I am able to zoom in and out even if  the option is disabled and even if I enable it i dont find any change. Also other thing i noticed is on zooming out, the entire content gets left aligned.
  * What do you obtain? A copy of the error message or a screenshot is always useful
       
  * When does this occur? 

 
![screenshot_2018-02-19-01-14-46-284_org kiwix kiwixmobile](https://user-images.githubusercontent.com/15075776/36356126-5cc0f472-1513-11e8-9d1d-9394018a35a6.png)
![screenshot_2018-02-19-01-14-53-914_org kiwix kiwixmobile](https://user-images.githubusercontent.com/15075776/36356127-5d482a3c-1513-11e8-968d-0d34e1231184.png)

**Comment by mhutti1** [comment]
I agree the UI isn't very clear but the option enables the button bellow. Can you confirm that you didn't realise this?

**Comment by Nair18** [comment]
Yah I noticed my mistake I am sorry.

**Comment by brijeshshah13** [comment]
@Nair18 Please close the issue if it has been resolved or conceptually cleared.
