### ISSUE TITLE
Feature: Update Side Nav

### ISSUE THREAD

**Issue by omkarprabhu-98** [kiwix/kiwix-android#470]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

#### Feature Description

Update the side nav with Material design guidelines

Before: 
![screenshot_20180219-232938 1](https://user-images.githubusercontent.com/23053768/36391564-fea4ddda-15cc-11e8-8d88-85427285e2de.png)

To achieve:

![layout-structure-sidenav2](https://user-images.githubusercontent.com/23053768/36391588-245bfea0-15cd-11e8-8592-4707184ed4c7.png)

@mhutti1 @brijeshshah13 Could you please check if this modification is fine and would be a fit for the application? Thank you!

**Comment by mhutti1** [comment]
I don't know. The trouble is that that style is normally used for separate fragments with different functions as it ocludes the search bar this makes sense. Our tabs are not really like that. I think that might be a deeper issue. It is proberbly a better idea to switch to tabs the way that chrome/wikipedia app do.

**Comment by brijeshshah13** [comment]
@omkarprabhu-98 I agree with @mhutti1's view. Instead of revamping the navigation drawer, we must go with the tabs, which will indeed take a lot of time and conflict solving.

**Comment by omkarprabhu-98** [comment]
Thank you for your views @mhutti1 and @brijeshshah13. 

@mhutti1  the point "that style is normally used for separate fragments with different functions" makes perfect sense, Thank you very much for the advice.

So should I change this issue and try to integrate tabs? 
And also try working on other issues to understanding the code base better

**Comment by mhutti1** [comment]
@omkarprabhu-98 I would close this issue and make another specifying creation of a tab structure (it is a big task though so make sure to tag it with the challenge label).

**Comment by omkarprabhu-98** [comment]
Alright @mhutti1, thanks again for the input
