### ISSUE TITLE
Text not showing in Library screen in dark mode

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#472]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : App
  * version of the software you use : 2.3 build 55
  * device / operating system : Android 7.0 (Samsung Galaxy S6)
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
The text on the Device tab in the library screen is not displayed in dark mode when there is no .zim file in the device.
Screenshot:
![screenshot_20180220-110428](https://user-images.githubusercontent.com/32238400/36414734-5230a660-1649-11e8-8125-f1ce616ee25f.png)
Here is the screen in light mode:
![screenshot_20180220-110414](https://user-images.githubusercontent.com/32238400/36414735-52465262-1649-11e8-9520-df40af9e4831.png)

  * When does this occur? 

#### Steps to reproduce:

  1. Go to settings and enable dark mode
  2. navigate to the device tab in the library and delete all .zim files
    
  * What should be the behaviour from your point of view? How do you expect the service to work?
  
  The text "No files here" should be displayed.

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
#### Feature Description

Please describe the feature you want to add to the project.

**Comment by kelson42** [comment]
Indeed.

**Comment by Abishek10** [comment]
@kelson42 Can I work on this ?

**Comment by brijeshshah13** [comment]
@Abishek10 Please make sure with @siddharth2010 that you can be assigned the issue because he is already assigned and you didn't get any confirmation from @kelson42.

**Comment by siddharth2010** [comment]
@Abishek10 , actually I have been busy with my university exams, so I wasn't able to work on this issue. Sure you can go ahead...
