### ISSUE TITLE
Multiple files download feature

### ISSUE THREAD

**Issue by knightcube** [kiwix/kiwix-android#473]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

## Feature Request
A feature to download Multiple Files by selecting multiple files in the listview in the Online tab
#### Feature Description
There can be a feature where the user selects multiple files from the list provided in the Online tab. And then show an Alert Dialog to confirm the downloads and then start downloading files one by one. Update the list accordingly in the Downloading tab as well

**Comment by mhutti1** [comment]
I think this would likely clutter what should be a simple user interaction.

**Comment by kelson42** [comment]
Yes, quite disagree with this. I propose to close the ticket.
