### ISSUE TITLE
Stop Reading Aloud once the random article option is selected

### ISSUE THREAD

**Issue by knightcube** [kiwix/kiwix-android#474]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : app
  * version of the software you use : Latest
  * device / operating system : J7 prime/Android Marshmallow
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
The read aloud button continues to play even when the webview gets updated with the random article. Basically it keeps reading the last article.
  * When does this occur? 
This occurs each time the webview gets updated by a random article
#### Steps to reproduce:

  1. Download any file
  2. Open it
  3. From the menu options on the right hand top corner select random article
  4. Once the webview is loaded select the read aloud option from the menu
  5. Then tap on the random article option again
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
The voice should stop reading the information from the webview and should get restarted for the new article

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.

**Comment by mhutti1** [comment]
I don't know which option is better but there are certainly benefits to the way it currently works as you could keep browsing while listening to an article you find interesting.

**Comment by kelson42** [comment]
Agree with @mhutti1. I close the ticket.
