### ISSUE TITLE
Add background colour to List view items

### ISSUE THREAD

**Issue by RajaVamsi11** [kiwix/kiwix-android#475]
**Is it a ?**

- [ ] Bug Report

- [  ] Feature Request

  
#### Feature Description
The articles in the Online fragment,Bookmarks Fragment and where ever List views are used are back grounded with white colour.
My idea is to add a light colour (like grey or something) in the background of  article in the listview.

**Would you like to work on it?**
Yes

@mhutti1  your reviews please.

**Comment by srv-twry** [comment]
@RajaVamsi11 Please attach screenshots for the current status as well as the intended final outcome.

**Comment by mhutti1** [comment]
Yeah its quite hard to visualise.

**Comment by RajaVamsi11** [comment]
Before background colour
![screenshot_2018-02-21-12-35-50](https://user-images.githubusercontent.com/30550059/36482899-9e897b30-173a-11e8-9ad7-b5a55c30e162.jpg)

After background colour( Divider lines can be deleted , we can add background color to each article in listview)
![screenshot 2](https://user-images.githubusercontent.com/30550059/36483041-0fb43d4a-173b-11e8-95c7-33638822e601.png)

**Comment by srv-twry** [comment]
@RajaVamsi11 Pardon, but i can't see any change in it. Is it gray in second image ?

**Comment by mhutti1** [comment]
I personally think the current version looks cleaner. But still don't really get what has changed.

**Comment by RajaVamsi11** [comment]
Yes the color is blue grey of density 50.
I think that present version of app looks good. I am ready to close this issue.
shall i?
