### ISSUE TITLE
Ripple effect

### ISSUE THREAD

**Issue by RajaVamsi11** [kiwix/kiwix-android#477]
**Is it a ?**

- [ ] Bug Report

- [  ] Feature Request

#### Feature Description
 
Get Context button has no ripple effect. I am interested in adding ripple effect to Get Context button so that it looks nice to user.

**Would you like to work on this?**
Yes

What do you say ?@mhutti1

**Comment by srv-twry** [comment]
Please attach a GIF for the current behaviour.

**Comment by mhutti1** [comment]
@RajaVamsi11 we did try this before. It might be in the old repository. check that out before starting on this.

**Comment by RajaVamsi11** [comment]
Ripple effect is only for android API level 21 but own API min level is 14. so we cannot use ripple effect.
Replacing ripple effect we can  add attribute 
        **android:background="?attr/selectableItemBackground"**
in the button list.
But it was not effective as ripple effect.
shall i continue?

**Comment by RajaVamsi11** [comment]
Android version : 8.1.0 (emulator)
