### ISSUE TITLE
Bug in SplashActiviy

### ISSUE THREAD

**Issue by suyash0103** [kiwix/kiwix-android#479]
**Is it a ?**

- [✔️] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [✔️ ] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : app
  * version of the software you use : Android Studio 3.0.1, Android 7.0
  * device / operating system : Motorola Moto M, Android 7.0
  
### Step 3: Describe the problem:
  
The Activity 'SplashActivity' does not have a layout specified, resulting in crashing of app.

  * What do you obtain? A copy of the error message or a screenshot is always useful
  App crashes.

  * When does this occur? 
When app is opened.

#### Steps to reproduce:

  1. Build and run app from Android Studio.
  2. App crashes completely.
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
If a new layout is created for 'SplashActivity', app would not crash. 

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
#### Feature Description

Please describe the feature you want to add to the project.

**Comment by suyash0103** [comment]
I can work on the above bug, should I?

**Comment by srv-twry** [comment]
@

**Comment by srv-twry** [comment]
@suyash0103 Can you please change your build flavour to ```kiwixDebug```? I think that's the issue you're facing. Not sure though. Please check and update.

**Comment by mhutti1** [comment]
Also provide a stacktrace for any crashes.

**Comment by RajaVamsi11** [comment]
I also faced same issue few days before. Just changing build varient to KiwikDebug as @srv-twry  says works fine.

**Comment by suyash0103** [comment]
Yes works! Thanks @srv-twry @RajaVamsi11

**Comment by srv-twry** [comment]
@suyash0103 It's a bug in the c++ backend which leads to a segmentation fault in the custom application flavour.
