### ISSUE TITLE
[Bug] "Unterminated quoted string" error during compilation [sf#886]

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#48]
_From @rashiq on June 8, 2016 13:7_

**Reported by nicolas_raoul on 2015-06-05 07:25 UTC**
Seen during compilation (it does not seem to prevent compilation though):

```
/home/nico/src/kiwix-kiwix/platforms/arm-linux-androideabi/arm-linux-androideabi/bin/strip /home/nico/src/kiwix-kiwix/android/libs/armeabi/libkiwix.so
-----------
/bin/sh: 1: Syntax error: Unterminated quoted string
```

_Copied from original issue: kiwix/kiwix#208_

**Comment by mhutti1** [comment]
_From @rashiq on June 8, 2016 13:12_

**Commented by nicolas_raoul on 2015-06-05 07:37 UTC**
The same error actually appears several times:

```
/home/nico/src/kiwix-kiwix/platforms/x86/i686-linux-android/bin/strip /home/nico/src/kiwix-kiwix/android/libs/x86/libkiwix.so
-----------
/bin/sh: 1: Syntax error: Unterminated quoted string
Created locales.txt file.
```

Ubuntu 2014.04 LTS bash 4.3.11

**Comment by mhutti1** [comment]
_From @rashiq on June 8, 2016 13:12_

**Commented by kelson42 on 2015-06-05 11:10 UTC**
What is your exact command (to get this errors)?

**Comment by mhutti1** [comment]
_From @rashiq on June 8, 2016 13:12_

**Commented by nicolas_raoul on 2015-06-19 05:50 UTC**
kiwix/android$ ./gen-custom-android-build.py customapp-json/wikivoyageen.json

```
[...]
/home/nico/src/kiwix-kiwix/platforms/x86/i686-linux-android/bin/strip /home/nico/src/kiwix-kiwix/android-custom-b74kfe/libs/x86/libkiwix.so
-----------
/bin/sh: 1: Syntax error: Unterminated quoted string
Created locales.txt file.
-----------
ls -lh build/outputs/apk/org.kiwix.kiwixcustomwikivoyage-*
-----------
ls: cannot access build/outputs/apk/org.kiwix.kiwixcustomwikivoyage-*: No such file or directory
-----------
./build-android-with-native.py --apk --clean
-----------
/bin/sh: 1: Syntax error: Unterminated quoted string
/bin/sh: 1: Syntax error: Unterminated quoted string
/bin/sh: 1: Syntax error: Unterminated quoted string
-----------
rm -f build/outputs/apk/*.apk
[...]
```

**Comment by kelson42** [comment]
The compilation script in Python has been rewritten by @mgautierfr, so I suppose this bug has just vanished by doing so. This should be checked.

**Comment by mhutti1** [comment]
build-android-with-native.py has been rewritten but I think this relates to gen-custom-android-build.py, which has yet to be improved.

**Comment by kelson42** [comment]
The generation of custom apps has been rewritten too... So this bug has been fixed.
