### ISSUE TITLE
Add chrome like tabs

### ISSUE THREAD

**Issue by omkarprabhu-98** [kiwix/kiwix-android#483]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
  
#### Feature Description

Currently the application has a side nav to navigate between the tabs.

![screenshot_20180221-210520 1](https://user-images.githubusercontent.com/23053768/36489106-31bbf8fa-174b-11e8-9cbf-8b0fdb01be80.png)

### The idea is to change it to something similar to tabs creation and navigation which Chrome uses:

![screenshot_20180221-210608 1](https://user-images.githubusercontent.com/23053768/36489215-72b54eb0-174b-11e8-80dd-3d33cc612eae.png)

**Comment by knightcube** [comment]
I want to work on this

**Comment by omkarprabhu-98** [comment]
@knightcube Please find another issue to work on. I am working on this issue

**Comment by knightcube** [comment]
okay

**Comment by abdulwd** [comment]
Closed via #832.
