### ISSUE TITLE
Create script to build kiwixlib module and upload to bintray linking in with kiwix-build

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#489]
## Feature Request

We should create a script either in kiwix-android or kiwix-build probably a bit of both to populate the kiwixlib module with native executables and then upload to bintray.

**Comment by RajaVamsi11** [comment]
@mhutti1 I think i can work on this issue if you guide me.please explain me.

**Comment by mhutti1** [comment]
@RajaVamsi11 its quite complex and will require access to some cloud accounts as such needs to be implemented by a more seasoned contributor with this access (or possibly as part of GSoC as part of a task with such oversight).

**Comment by RajaVamsi11** [comment]
Ok @mhutti1

**Comment by macgills** [comment]
@mgautierfr I would appreciate your input on this and I will outline what the current process is and the solutions we can explore.
As it stands we have a local Android Library Module that possesses the gradle task `bintrayUpload` that, as one would expect, uploads this project to bintray.
To create the next version we take the following outputs from kiwix-build and paste them into this project: 
![image](https://user-images.githubusercontent.com/3358282/59690460-629e8f00-91d9-11e9-8ce5-6ae96d24df6a.png)
Update the version in the build.gradle, run `gradlew bintrayUpload` and on success we have a new published artifact. This task requires 2 secure pieces of information, user & apiKey.

What is actually important is the .so files and the declaration of the JNI interface as we could create the same end result (apks split by architecture) by including these files in the existing android-kiwix project.

Some solutions I have considered:

**Standalone Project**
We create a new github project `kiwix-lib-android` with a similar branching strategy to `kiwix-android` eg master/develop/feature. This project would have it's own travis build and on a tag of master would auto publish. To prepare it to publish a developer would have to take the outputs of `kiwix-lib`, JNI interface and .so files, add them in a PR. Travis would hold the encrypted variables so nobody would have explicit knowledge of them.
Pros: distributed and independent, clear versioning. I can do this without needing any assistance
Cons: Still quite manual aside from publishing

**Kiwix-Lib Integrated**
We add this project to kiwixlib and add a deploy `tags: true` on travis where we copy the output files (I think .so's get generated here?) into it and then run the gradle task to publish.
Pros: closest to the source of truth
Cons: mixing build systems in one project, I would probably need slight help getting set up in an evironment to test this, appropriate linux vms, etc


**Kiwix-Build Integrated**
Kiwix-Build gets an option added? Here is where I am really out of my depth. No idea where to start, what is idiomatic or how it all integrates. I don't know if it runs on ci or just locally. I can't see a secrets.tar so if the build is unencrypting some variables at some point I can't see where that happens? A build stage is missing? I at least can't see `android_build`. I find it very difficult to follow but I am no travis expert.
Pros: centralised, organisation standard
Cons: I have no idea how to contribute

**Comment by macgills** [comment]
Output of discussion between @mgautierfr and myself:
I will create the android publishing library inside kiwix-lib, kiwixbuild will populate this with the necessary files and invoke the gradle publishing command
