### ISSUE TITLE
Search box should be align on the right if UI uses a RTL language

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#49]
_From @kelson42 on November 26, 2016 15:13_

Currently it's alway aligned on the left.

_Copied from original issue: kiwix/kiwix#370_

**Comment by kelson42** [comment]
_From @mhutti1 on November 26, 2016 15:29_

@kelson42 Do you mean that the text should be typed right to left when searching?

**Comment by kelson42** [comment]
@mhutti1 the box itself should be on the right. But yes of course the text should be typed from right to the left (but this is maybe already the case).

**Comment by kelson42** [comment]
_From @mhutti1 on November 26, 2016 15:33_

@kelson42 For me the box is on the right I think? Are you talking about content search, online search or file search?

**Comment by kelson42** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1029718/20641437/f1378658-b3f7-11e6-8966-d30822019392.png)

**Comment by kelson42** [comment]
_From @mhutti1 on November 26, 2016 15:50_

![screenshot](https://lh3.googleusercontent.com/5DipVgDfmK8x8qSHHs_8zVOSD5LvdWw4DUpfHCyJDmh2L3GGChl-gyK_IzVe0rhwKCRyXvwmgie-=w557-h990-no)

**Comment by kelson42** [comment]
_From @mhutti1 on November 26, 2016 15:51_

It seems that long search bar can have the wrong text. But even short search bar when you type is the wrong way round.

**Comment by kelson42** [comment]
_From @EladKeyshawn on November 26, 2016 15:59_

@mhutti1 On portrait the search box is aligned correctly, the problem is the box itself is not fully fit to the actionbar (it's at the middle).

**Comment by kelson42** [comment]
@EladKeyshawn yes, this is an other bug... and @mhutti1 also discovered that (with last wikimed ar) makeing landscape-portrait-landscape puts the whole set of buttons on the wrong side (right), it should be left like at the beginning.... Seems we have a little bit work to do around this ;)

**Comment by kelson42** [comment]
_From @mhutti1 on November 26, 2016 16:2_

http://www.phonearena.com/news/How-to-force-right-to-left-RTL-layouts-on-Android_id64154

This allows you to test in english.

**Comment by kelson42** [comment]
_From @mhutti1 on November 26, 2016 16:4_

@kelson42 We could potential make a few GCI tasks out of this each to fix a part of the RTL layout. Now we can reproduce easily enough it should be in a students capability,

**Comment by kelson42** [comment]
_From @EladKeyshawn on November 26, 2016 16:4_

@kelson42 I have not encountered this yet ;)

**Comment by kelson42** [comment]
@mhutti1 Yes, split as much as you think this is necessary. Makes perfectly sense to me.

**Comment by kelson42** [comment]
_From @EladKeyshawn on November 26, 2016 16:7_

@mhutti1 So you mean once the device is RTL and searching in LTR then I confirm its unaligned

**Comment by kelson42** [comment]
_From @mhutti1 on November 26, 2016 16:10_

@EladKeyshawn I can see 3 bugs at the moment. 

1. Search is LTR 100% of the time once you start typing. 
2. If the search bar is large enough it can show LTR initially.
3. If you switch orientation twice then you are reset to LTR.

**Comment by kelson42** [comment]
_From @EladKeyshawn on November 26, 2016 16:16_

@mhutti1  For me when I set my device to Hebrew you can see when I type english it uses RTL. 
![screenshot 06-13 26 2016](https://cloud.githubusercontent.com/assets/17123769/20641621/741c018c-b404-11e6-9ca6-f50b78f13290.png)

**Comment by kelson42** [comment]
_From @mhutti1 on November 26, 2016 16:28_

@EladKeyshawn This doesn't happen for me. What device/os?

**Comment by kelson42** [comment]
_From @EladKeyshawn on November 26, 2016 16:40_

@mhutti1 5.1 huawei mate s, but I checked on other apps like messanger and others and the behaviour is similar. So I dont think this is worth fixing.

**Comment by RohanBh** [comment]
@mhutti1 I am new to this repo and would like to work on this issue.

**Comment by mhutti1** [comment]
@Koundinyalanka you have created issue #365 are you working on this as well?

**Comment by Koundinyalanka** [comment]
@mhutti1 fixed #365  and created a pull request please check

**Comment by RohanBh** [comment]
@mhutti1 @kelson42 Is this issue fixed?

**Comment by mhutti1** [comment]
@RohanBh Please instead of asking us this question, do a bit of work for yourself and find out. We don't have infinite memories. If you come back and think its fixed then we can verify this and then close the issue.

**Comment by RohanBh** [comment]
@mhutti1 I am sorry for before.
I have checked with the latest build on master as of now and have found the following

1. While searching in forced RTL mode(via developer settings), the text is always LTR. Other apps like Chrome, Play Store, WhatsApp, etc. behave in the same way. 
2. In LTR searching, back arrow and the cross are opposite to each other. But, in RTL searching, both of these icons clump together in the left corner.
![LTR](https://user-images.githubusercontent.com/24610859/36939308-9f9fadf6-1f54-11e8-91ab-f2dcd5f385d2.jpg)
![RTL](https://user-images.githubusercontent.com/24610859/36939290-6ef1cac2-1f54-11e8-93c2-85cf97300a61.jpg)
3. The problem in #365 is partially fixed. The cross appears at the corner in the portrait mode but in the middle in landscape mode.
![Portrait](https://user-images.githubusercontent.com/24610859/36939190-fb83acb4-1f52-11e8-8abb-04d73ff6a3fb.jpg) ![Landscape](https://user-images.githubusercontent.com/24610859/36939196-062eaef2-1f53-11e8-9359-2c617b98256e.jpg)

I'd like to work on these two issues. Do I have to create a separate issue for point 2?

**Comment by mhutti1** [comment]
I would.

**Comment by RohanBh** [comment]
#582 
I have created a new issue.

**Comment by RohanBh** [comment]
@mhutti1 can you please assign me #582 and #365?

**Comment by abdulwd** [comment]
Closed via #642.
