### ISSUE TITLE
Content gets blocked underneath exit full-screen button

### ISSUE THREAD

**Issue by brijeshshah13** [kiwix/kiwix-android#490]
**Is it a ?**

- [x] Bug Report

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : app
  * version of the software you use : 2.3 build 55
  * device / operating system : Motorola E3 Power, Android version 6.0
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful

    The text behind the `fullscreen_exit` icon is not visible use to the background color which can deteriorate the user experience.

![screenshot_20180222-182003](https://user-images.githubusercontent.com/18366144/36539878-48fe4136-17fe-11e8-99d0-4eda7c64e17c.png)

  * When does this occur? 

    When entered in full-screen mode.

#### Steps to reproduce:

  1. Open any content or help screen in full-screen mode
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

    The background of the `fullscreen_exit` button should be transparent so that the user can easily read the text underneath the button.

**Would you like to work on this?**
Yes,

@mhutti1 @srv-twry Please review.

**Comment by srv-twry** [comment]
LGTM.

**Comment by kelson42** [comment]
I'm not sure at all this is an improvement. The icon will be really more difficult to identify if the background is fully transparent. In addition that does not solve the problem that this is currently not at all visible in case of white background. So all in one, I think this is quite a bad idea.

**Comment by brijeshshah13** [comment]
@kelson42 No offence, but I surveyed asking some people before raising this issue and they said that the icon looked like it was cut and paste from an image and that the background of the icon must be transparent. Also, when the background changes from white to black while using night mode, the icon can be changed to white.

**Comment by brijeshshah13** [comment]
@kelson42 I definitely agree on this. I will try to provide the same functionality for the full-screen exit button as you described. @mhutti1 Will the current improvement be merged or shall I close this issue?

**Comment by mhutti1** [comment]
Yeah removing it sounds good to me. I think auto hide is now default if its not we should enable that at the same time.

**Comment by brijeshshah13** [comment]
@mhutti1 I'm closing this issue for now. Will open a new issue with the discussed behavior of the full-screen exit button.
