### ISSUE TITLE
Problems with app's language

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#491]
**Is it a**

- [x] Bug Report

- [ ] Feature Request

## Bug Report

The following bugs are present in **_Setting -> Language_**:
### 1. Default language name should be shown instead of language code. 
_English_ should be shown instead of _en_in_.
#### Screenshots:
![webp net-resizeimage](https://user-images.githubusercontent.com/20206262/36541328-89ad988a-1803-11e8-84e8-12528e5fd31d.png)

#### Steps to reproduce:
- Clear data of the app.
- Goto _Settings -> Language_.

### 2. Radio buttons must be used instead of checkboxes while selecting a language. 
Checkboxes are used for multiple selections.

#### Steps to reproduce:
- Clear data of the app.
- Goto Settings -> Language.

#### Screenshot:
![image](https://user-images.githubusercontent.com/20206262/36542118-f82a8848-1805-11e8-9348-a47947527013.png)

#### Steps to reproduce:
- Goto _Settings -> Language_.
- Select an RTL language, for instance, Urdu and press **OK**
- Again go to _Settings -> Language_. When language is clicked the list in RTL language is not rendered properly

**Comment by abdulwd** [comment]
@kelson42 @mhutti1 Please review this issue. I would like to fix it. :)

**Comment by mhutti1** [comment]
If this is an issue for you then it is clearly not the correct end user result so please work on it.
