### ISSUE TITLE
Improve "back to the top" feature

### ISSUE THREAD

**Issue by sdivakarrajesh** [kiwix/kiwix-android#493]
**It is a**

- [ ] Feature Request
- and i would love to work on it..
- have done some works on android and a good programming experience

### Environment 
  * App
  * Android
  
### Feature

  * A Floating action button that appears while scrolling down - when clicked helps to reach the top of the page

#### Feature Description

  * This might come handy when reading long articles

 * Reduces the effort and time taken to scroll and reach the top. 

 * Why necessary? - Because most wiki articles have the main info at the beginning and then delves deeper. It might come in handy after scrolling a long way down and when the user wishes to reach back to the top

### Note 
   This is not the iOS patented version of touch at the top to scroll. Works to achieve the same but differently - so no legal issues. In fact a large number of popular apps already out there have done similar things to achieve the same.

Example: WhatsApp has a FAB to reach the bottom. A similar feature can be used to reach the top

https://user-images.githubusercontent.com/30803637/36548278-dbf27c02-1815-11e8-9e2d-380b5e358260.gif

![img_3456](https://user-images.githubusercontent.com/30803637/36548278-dbf27c02-1815-11e8-9e2d-380b5e358260.gif)

**Comment by mhutti1** [comment]
Please do research before opening issues. We already have a back to top option in settings. If you would like to improve this then please make a comparison to it.

**Comment by kelson42** [comment]
There is an other problem with the "back to top" bar, it is going to be masked by the bottom bar (if both activated).

**Comment by sdivakarrajesh** [comment]
I am currently working on a new branch that overcomes this issue.
will soon make a pull request

**Comment by Abishek10** [comment]
@kelson42 Can I work on this ?

**Comment by mhutti1** [comment]
@Abishek10 as you can clearly see by the comment just above yours (please actually read issues fully before attempting to comment) @sdivakarrajesh has been working on it for 5 days. If after a week or two still no work has been completed then we can think about reassigning it.

**Comment by savannahar68** [comment]
@mhutti1 Hello sir, the issue is open since 8 days and @sdivakarrajesh hasn't even forked the repo and started to work, I have already made the necessary changes and made it look good if you say sir can I send a PR.

**Comment by sdivakarrajesh** [comment]
Hey there..
I am working on a local cloned repo..
There is a persisting bug that makes the app crash that I discovered while implementing the feature..
That’s why I haven’t made a PR yet..

**Comment by savannahar68** [comment]
@sdivakarrajesh Ok cool,I have already made changes and the app works perfectly fine ,if you want I can make a PR and add the feature

**Comment by sdivakarrajesh** [comment]
Happy to say that i am ready to make the pull request now..:-)

**Comment by sdivakarrajesh** [comment]
i have opened a new pull request #564 

-Still the back to top feature is set as a user preference and can be enabled or disabled.
-But now the button has been replaced by FAB and it does not overlap the bottom tool bar when both are enabled
-Added a night mode version of the FAB too

**Comment by abdulwd** [comment]
Fixed in #832.
