### ISSUE TITLE
Searching is not working in after running app.

### ISSUE THREAD

**Issue by pprathameshmore** [kiwix/kiwix-android#494]
**Is it a ?**

- [x] Bug Report

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : __app___
  * version of the software you use : 
  * device / operating system : Android Emulator API 26
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful

I am running this app in emulator but Search results are not showing.
Do I need any configuration for that?

![capturejjg](https://user-images.githubusercontent.com/17108186/36552319-94cfa818-181f-11e8-9d66-2d048b0113cb.JPG)

  * When does this occur? 

After compiling or running on real device.

#### Steps to reproduce:

  1. Open app and search for any query in Wikipedia.
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
#### Feature Description

Please describe the feature you want to add to the project.

**Comment by arpank10** [comment]
I don't think it would work in emulator unless you have downloaded a zim file. With no zim file, the search button shouldn't show up ideally. Are you using the kiwixDebug build variant?

**Comment by mhutti1** [comment]
Not enough details. Please make a new issue with more details so I can work out what you are trying to convey.
