### ISSUE TITLE
Bottom toolbar Bookmark

### ISSUE THREAD

**Issue by MayankChuriwal** [kiwix/kiwix-android#495]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : app
  * version of the software you use : android studio 3.0.1 
  * device / operating system : xiaomi redmi 3s prime/ android 6.0
  
### Step 3: Describe the problem:

Enabling the bottom toolbar on Help page and then selecting bookmark from the bottom tab crashes the app completely.

  * What do you obtain? A copy of the error message or a screenshot is always useful

  * When does this occur? 

#### Steps to reproduce:

  1. Enable the bottom toolbar option from setting on Help page
  2. Selecting the bookmark option from the bottom toolbar
  3. _____
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

I think there must be a toast message saying that the help page cannot be bookmarked.

**Comment by mhutti1** [comment]
Please upload a stacktrace for crashes.

**Comment by ashutoshbsathe** [comment]
@mhutti1 here's the stacktrace https://del.dog/waqecepone.sql
Should I go ahead and fix it ?

**Comment by ashutoshbsathe** [comment]
@brijeshshah13 Should I create the PR for this ? Or is it already been fixed and I'm just being blind ? xD
Anyway if it's still open, I have a quick fix for this which I would like to merge

**Comment by brijeshshah13** [comment]
@ashutoshbsathe It's working fine for me. Can you make sure that you are in sync with the latest master branch?

**Comment by ashutoshbsathe** [comment]
@brijeshshah13 No, it does crash for me. Check the log I posted.

**Comment by brijeshshah13** [comment]
@ashutoshbsathe Can you please attach a gif for the same?

**Comment by jb1998** [comment]
Hi ,
@brijeshshah13 I am facing the same issue, I was just about to open one but then I saw this issue.
Below I am attaching gif for the same.
Device : Micromax A106
Android version : 5.0
![crash](https://user-images.githubusercontent.com/23710417/36864489-d685c6aa-1db2-11e8-9e6c-93109a6c55a5.gif)

**Comment by RajaVamsi11** [comment]
@jb1998 What is the version of the app you are using?

**Comment by jb1998** [comment]
I have the current version.
I have set up the project 2 hrs ago.

**Comment by harsh-2711** [comment]
In my mobile, the bookmark(star) button doesn't work when on home page whereas it works for all other pages. So there's no issue.

**Comment by brijeshshah13** [comment]
@MayankChuriwal What is the status of the PR?

**Comment by mhutti1** [comment]
Resolved with the new bottom bar.
