### ISSUE TITLE
Support OSM maps and markers in WikiVoyage

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#5]
From the OTRS queue:
"The Wikivoyage website offers numeric markers in the text, usually in
the "See" section of articles, that open an OpenStreetMap map when
they are clicked. This feature is extremely useful when visiting a
place: the markers in the text and on the map are the easiest way to
find one's way to a mentioned landmark.

Wikivoyage European Travels and Wikivoyage Offline Travel Book do not
support this feature. Instead of markers there are non-clickable "1s",
see attached pictures.

Could you please consider supporting this feature? It would be
immensely useful. The map itself need not be offline (with proper
warning about data usage), however if it is, it's an added bonus
(perhaps with a map download feature similar to the ones in Google
Maps and MAPS.ME)."

Although come to think of it this is much more a mwoffliner isssue than Android, isn't it?

**Comment by kelson42** [comment]
@Popolechien Could you please put the picture (like written in the feedback)?

**Comment by Popolechien** [comment]
Dude forgot to add the picture to his email - I wrote him back asking for it.

**Comment by kelson42** [comment]
@Popolechien thx, it's important.

**Comment by kelson42** [comment]
Few feedbacks about this:
* Mediawiki/Wikipedia/Wikivoyage has or had many ways to specify links pointing to a geo coordinates.
* Two "systems" were supported, but the "new" "Special:Map' were not
* This is a mwoffliner topic, not a reader one
* We have decided a long time ago to code this kind of links with the prefix "geo", like "geo:lat,lon". More details here https://en.wikipedia.org/wiki/Geo_URI_scheme
* I just have implemented the support of "Special:Map" links - to generate "geo:" links in the ZIM
* This should allow to switch directly from Kiwix to a map app on mobile

I think the ticket is fixed, we will see the result in future ZIM files.

**Comment by Popolechien** [comment]
Ok just for the record, here are the images:
Mobile website: markers in text:
![1 - mobile website - markers in text](https://cloud.githubusercontent.com/assets/21675885/22640624/cc543b30-ec53-11e6-85ab-7d34e045492d.png)
Mobile website: markers on map
![2 - mobile website - markers on map](https://cloud.githubusercontent.com/assets/21675885/22640623/cc53b4ee-ec53-11e6-95fb-2309ba1f6b02.png)
App: no map / no marker
![3 - app - no map and marker support](https://cloud.githubusercontent.com/assets/21675885/22640625/cc54e6f2-ec53-11e6-9f78-e4e7c8f70c3c.png)

**Comment by rocky-III** [comment]
hi
I´m testing kiwix on android and i would find it very usfull if the geo links in WikiVoyage would also work in the offline version but all maps do not show up in the first place... Why ??
If the links could linked to an offline map like OsmAnd this would be perfect for traveling.
thanks

**Comment by kelson42** [comment]
@rocky-III This is a complex problem as we would need to integrate a mapping system in the ZIM file itself. Currently in many places you have a `geo:` link which should redirect to whatever mapping app you prefer.

**Comment by rocky-III** [comment]
Ok thanks but I can´t find this `geo:` links in the german WikiVoyage Kiwix version... where do i have to search?

**Comment by kelson42** [comment]
@rocky-III This is a decision of Wikivoyage DE then. For now, there is nothing more we can do on our side.

**Comment by rocky-III** [comment]
i just wnat to be sure that i don´t miss something...

that is how is looks for HAMBURG online:
![h-burg-01](https://user-images.githubusercontent.com/6730765/64323033-f6574e80-cfc3-11e9-8d39-3b1fb13d25cf.jpg)

and this is kiwix showing:
![2Screenshot_20190905-100256_Kiwix](https://user-images.githubusercontent.com/6730765/64323352-9f05ae00-cfc4-11e9-8608-c72910091f4d.png)


where are the geo links i could try?
