### ISSUE TITLE
[Bug] On Android, pages with "%" character can not be loaded [sf#900]

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#50]
_From @rashiq on June 8, 2016 13:7_

**Reported by kelson42 on 2015-07-22 20:13 UTC**
Pages where the title has a % don't load. Try eg, "100% Chance of Rain" or "1%CLUB". 
http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_2015-05.zim

_Copied from original issue: kiwix/kiwix#212_

**Comment by mhutti1** [comment]
_From @jan-wassenberg on June 8, 2016 14:45_

Possibly related: #222 (cannot search for pages with %)

**Comment by mhutti1** [comment]
@kelson42 I created a zim with 1%CLUB only with zimbalaka and I can't open on desktop either. I can't download full wikipedia on my device to test it with that though so it could be a zimbalaka issue.

**Comment by mhutti1** [comment]
_From @kelson42 on August 30, 2016 18:37_

@mhutti1 not sure, but might be a problem in the ZIM file in that case. Will try to confirm the problem with a smaller ZIM file than wikipedia_en_all

**Comment by mhutti1** [comment]
_From @kelson42 on August 30, 2016 19:55_

I have retested again with wikipedia/wikipedia_fr_all_nopic_2016-06.zim and I confirm the problem, I'am not able to open the article "101%"

**Comment by mhutti1** [comment]
@kelson42 In this case can we assume this is not an issue with android but Kiwix itself?

**Comment by mhutti1** [comment]
_From @kelson42 on August 30, 2016 20:0_

@mhutti, pretty sure. The "%" is used as meta-character in URLs, this is a URL encoding issue.

**Comment by mhutti1** [comment]
Pretty positive this is a problem with the C++ as it doesn't seem to work on desktop either.

**Comment by mhutti1** [comment]
_From @kelson42 on September 9, 2016 5:12_

@mhutti1 Will have a looks this WE

**Comment by kelson42** [comment]
@mhutti1 I just have merged a PR to kiwix-lib which might have fixed that problem to : https://github.com/kiwix/kiwix-lib/pull/97.

**Comment by kelson42** [comment]
Still there in 2.3, but 3.0 should have it fixed.
