### ISSUE TITLE
Ripple Effect on Card View

### ISSUE THREAD

**Issue by pprathameshmore** [kiwix/kiwix-android#501]
- [x] Feature Request
  
## Feature Request

Add ripple effect on Card View

#### Feature Description

Ripple Effect looks great.
Can I work on this feature?

**Comment by MayankChuriwal** [comment]
Why do you need ripple effect on card views when they are only meant to provide first time information to the user. But open to comments from other contributors as well.

**Comment by brijeshshah13** [comment]
@pprathameshmore I don't think this is required. However, it can be implemented for `Get Content` button present in the Help screen. @mhutti1 What do you think?

**Comment by RajaVamsi11** [comment]
@brijeshshah13  I had worked on the ripple effect of the **Get Content** button  and send a PR also.you can check it in pull requests.

**Comment by brijeshshah13** [comment]
@RajaVamsi11 Thank you for the update. @mhutti1 I'm closing this issue as this addition does not enhance either user experience or performance of the app.
