### ISSUE TITLE
Display number of matches of the string found by using "Find in page"

### ISSUE THREAD

**Issue by RohanBh** [kiwix/kiwix-android#507]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
  
#### Feature Description
Currently when we use the *Find in page* feature of the app, we do not get the total matches found and the index of the match currently highlighted on the page. I'd like to add this to the app.

**Comment by kelson42** [comment]
@RohanBh concrete example of mis-behaviour?

**Comment by RohanBh** [comment]
![find_in_page](https://user-images.githubusercontent.com/24610859/36634003-23fc1882-19c4-11e8-9e6a-5f7c307d49d4.jpeg)
@kelson42 this is the screenshot from the app.
![screenshot from 2018-02-25 00-38-48](https://user-images.githubusercontent.com/24610859/36634016-4f987774-19c4-11e8-8547-51dea8572865.png)
and this is a screenshot from a browser's *find in page* feature.

**Comment by kelson42** [comment]
@RohanBh I do not understand, which word exactly is not detected properly in your screenshot?

**Comment by RohanBh** [comment]
@kelson42 read your first comment. Sorry for the confusing language :sweat_smile:
