### ISSUE TITLE
Enhanced the items in the download using cardview[Feature]

### ISSUE THREAD

**Issue by Ananthusubramanian** [kiwix/kiwix-android#511]
Feature Request:

Cardview looks nice in the download list items view with elevation on the cardview makes it look better.

Changes Added:
Changing the layout by adding cardview to the items

Screenshots:
![screenshot_2018-02-25-00-08-49-164_org kiwix kiwixmobile](https://user-images.githubusercontent.com/22250995/36638511-21c19b4c-1a1d-11e8-85e4-fa6904eff947.png)
![screenshot_2018-02-25-00-19-08-608_org kiwix kiwixmobile](https://user-images.githubusercontent.com/22250995/36638512-2340a2c4-1a1d-11e8-95df-ac29ef842403.png)

**Comment by kelson42** [comment]
The rounded corners do not seems to be properly done, I still see the square corner.

**Comment by kelson42** [comment]
@brijeshshah13 I'm not convinced myself. The whole library UI should be revamped IMO. This kind of small change does not really fix the fundamental problems... but keep people busy away of doing it.

**Comment by mhutti1** [comment]
Agreed with @kelson42 closing this. We need to revamp the library however this is a large coordinated task that will not be solved with small incremental changes which change our design in sometimes opposite directions.
