### ISSUE TITLE
Change dialog icon color according to night mode

### ISSUE THREAD

**Issue by ashutoshbsathe** [kiwix/kiwix-android#517]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

## Feature Request
Change the color of warning icon in "Clear All History Dialog"
![screenshot_20180225-171131](https://user-images.githubusercontent.com/22210756/36641016-3851fafa-1a4f-11e8-8b89-28549c7fd046.png)

#### Feature Description
As you can see in the screenshot, the warning icon isn't clearly visible, This feature will enable black icon without nightmode and current(white) icon in night mode.

I also have worked on this issue and have it implemented locally

Just wanted to notify this before I create a PR

**Comment by ashutoshbsathe** [comment]
This here is the result of changes I'm proposing : 
Night Mode Off : 
![screenshot_1519564369](https://user-images.githubusercontent.com/22210756/36641836-5744a2d4-1a5c-11e8-8c66-79e5c3f9aa71.png)
Night Mode On : 
![screenshot_1519564595](https://user-images.githubusercontent.com/22210756/36641837-611ce0fa-1a5c-11e8-9f2c-215a4b14bcc6.png)
I guess this looks much better !
Should I create the PR ?

**Comment by brijeshshah13** [comment]
@ashutoshbsathe Can you please remove the extra area above in the top blue line including it so that both the versions have uniform UI?

**Comment by ashutoshbsathe** [comment]
@brijeshshah13 sure I will try to do that !

**Comment by ashutoshbsathe** [comment]
@brijeshshah13 It's fixed ! 
Night Mode looks like this now ! 
![screenshot_1519621333](https://user-images.githubusercontent.com/22210756/36655479-f38027e0-1ae8-11e8-9963-3357bffee4f3.png)
Should I create separate PR's for both the issues ?

**Comment by brijeshshah13** [comment]
@ashutoshbsathe Nice. However, the `Cancel` and the `OK` button must be of the same color as in the regular mode.

**Comment by ashutoshbsathe** [comment]
Done @brijeshshah13 Check out the PR I created

**Comment by arunkiddo** [comment]
Yep I like to work on this.Could You assign me this ??

**Comment by RajaVamsi11** [comment]
@arunkiddo I think that @ashutoshbsathe was working on it.He also created a PR.
Kindly find an another issue or create your own issue and start working on it.

**Comment by ashutoshbsathe** [comment]
@arunkiddo This issue is almost fixed and PR is also up !
I will close this issue when the PR is merged. 
So I'd suggest look for another issue 
Peace
