### ISSUE TITLE
Explicitly include codestyle for XML files

### ISSUE THREAD

**Issue by brijeshshah13** [kiwix/kiwix-android#519]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

#### Feature Description

Noticing that almost all the PR's are facing the Indentation issue for the XML files, I think it would be great if we could specify that `kiwix` follows `2dp` for the `Indent` and `Continuous Indent` values.

We can even provide the following screenshot in the `codestyle.md` file to indicate the same.

![indent_final](https://user-images.githubusercontent.com/18366144/36643640-891a6d9e-1a74-11e8-8164-ca14a041faa2.png)

After changing the values, we can simply `select the files we want to indent`, `right click` -> `Reformat Code` -> Check `Rearrange entries` -> `OK`. And just like that all the future indentation issues will be prevented saving a heck lot of time while reviewing.

@mhutti1 @kelson42 @srv-twry Please review.

**Comment by mhutti1** [comment]
This sounds like a reasonable idea in general.

**Comment by amerinoo** [comment]
Possible GSoC trying to help :). What do you think about export the Kiwix project settings? Developers as me could import then the correct settings and should be easier follow the codestyle.
 
![](https://lh3.googleusercontent.com/6IPPym4134jWfSh0nmiIhHF_icsMuQWCrc36N7pFVQ-yXxGV6l6-qrLyzMjxMcuun_Fz7X3KGyBxygKuGd4vv9YbdXsO5AtFDTwkp7ZP1LSvpn4QLhSsGEep3yX7AShryWyFJMJXqq_gsE4SmYjHbMbIQy71an_oqxcBANhH6nkgLIOJte4MTbQRgLG3oc3EOjF_mItUR6AGtCU8cTQspCpweV8O17Kk4A67JkN9AcgQfCrO2wPV5bJFuUpqBwzCpXd9B-tq-CxfN6oP3XvemxmsIJwzHMniqXpAaEsRcKscgZnXsrqPCBs-kBoX33D34QNuVMqhrD2pJ1ev_EaTPSRBBUQHWgT8dI9fa8ogR0Dg1KAwst56n62aAXwX1AO6UQOHYcaJzwDMohZVEeXKvZP_3fjhLnmxeevyhza7UftP3kQjhdH2ZIqgXU-LZr2A7CfbpHBHoPbFYehD2CW3IAsTL0EkZJndsYIZFdpC2BiiyoDDf5HUiogg_zzV8C0V9GKlXKfXraVnH4ezH_yEhPLea1V7oLmk3g1o9VoZdFQKktUF3vguqw5mP47ajrZ15EvO3StatkJW-ns_j1vr_enz0GrMXMhkAJOlEz0=w1033-h701-no)

**Comment by mhutti1** [comment]
We are looking at implementing a style check into our build process after that we can look into exporting standard settings.
