### ISSUE TITLE
Kiwix for Android should integrate a feedback system

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#52]
_From @kelson42 on June 22, 2016 12:27_

Speaking with the Wikimed community, it's popup that this Wikipedia community would love to get feedback from the field about articles.

To do so it would be greate to have in the wikimed app:
- An option activating a feedback box
- This feedback box would allow to put a text (maybe a picture) to each article (at the end).
- The feedback would be saved locally and each time the device is online, this would be puched as new topic to a pre-defined Wikipedia talk page.

_Copied from original issue: kiwix/kiwix#249_

**Comment by mhutti1** [comment]
_From @kelson42 on June 22, 2016 14:27_

Re-using the code of the Mediawiki feedback extension might be a good idea:
https://www.mediawiki.org/wiki/Article_feedback

**Comment by mhutti1** [comment]
_From @kelson42 on September 11, 2016 8:42_

@zaeemsiddiq Any news on this? We are almost ready to release kiwix 2.0 (next week) for android and just after it would be a good timing to integrate your work. Are you ready?

**Comment by mhutti1** [comment]
_From @zaeemsiddiq on September 13, 2016 14:42_

@kelson42 Hopefully i will be able to finish it by the end of this month. Was busy with other assignment projects

**Comment by kelson42** [comment]
This topic has not poped up since a long time. For the moment WONTFIX.
