### ISSUE TITLE
Action bar gets cut off on API 16 emulator

### ISSUE THREAD

**Issue by brijeshshah13** [kiwix/kiwix-android#520]
**Is it a ?**

- [x] Bug Report

### Step 1: Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have tested with the last (dev) version of the software.  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2: What is your environment?
  * version of the software you use : 2.3 build 55
  * device / operating system : Android Studio API 16 Emulator and Genymotion API 16 Emulator
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful.

    The `ActionBar` gets cut off while running on API 16 emulator.

    **Screenshot from Android Studio API 16 Emulator**
   
![screenshot_1519581206](https://user-images.githubusercontent.com/18366144/36644731-c585239a-1a84-11e8-9262-a1343c1350cb.png)

   **Screenshot from Genymotion API 16 Emulator**

![api16_1](https://user-images.githubusercontent.com/18366144/36644738-d9671cf6-1a84-11e8-96ed-73daf8f1b047.PNG)

  * When does this occur?

    Opening the app. 

#### Steps to reproduce:

  1. Open the app
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

    `ActionBar` must not be cut off.

**I want to verify if anyone else is facing this issue on any other API level or is it just me?**

**Comment by abdulwd** [comment]
Me too. :stuck_out_tongue: 
On a device with API 17.

**Comment by RajaVamsi11** [comment]
Me too on a device with API level 16.

**Comment by brijeshshah13** [comment]
@vansh1sh Kindly first ask using comments if anyone is already working on the issue and if available, then start working on the issue rather then asking here and directly sending the PR. First time contributors might get discouraged from such incidents.

**Comment by vansh1sh** [comment]
@brijeshshah13 Sure, will do that from next time :)
