### ISSUE TITLE
Language name overlapping with the number of files

### ISSUE THREAD

**Issue by harshvardhan-takawale** [kiwix/kiwix-android#528]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have tested with the last (dev) version of the software.  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2: What is your environment?
  * version of the software you use : 2.3 Build: 55
  * device: Moto G4 plus
  
### Step 3: Describe the problem:
When you open the dialog to select the language, the language name overlaps with the number of files.

#### Steps to reproduce:

![screenshot_20180228-112200](https://user-images.githubusercontent.com/28982436/36772618-f0f21bca-1c7b-11e8-87ee-80d4896bd8ee.png)

  
  * What should be the behavior from your point of view? How do you expect the service to work?
     The text should resize so that no overlap takes place.

### Are you willing to work on the issue?
        Yes.
  

@mhutti1 @kelson42 @brijeshshah13 @srv-twry Please review.

**Comment by harsh-2711** [comment]
Can I work on this issue?

**Comment by srv-twry** [comment]
@harshvardhan-takawale What is your proposed solution for this problem ?

@harsh-2711 It is already assigned. Please find another issue to work on.

**Comment by harshvardhan-takawale** [comment]
@srv-twry I have thought of a few approaches. Please let me know which one to follow.
1) Ellipsize
2) Horizontally scrolling text
3) Autosizing textview (but that will only be effective with newer phones- API 26)

**Comment by srv-twry** [comment]
I would go for Ellipsize. Let's wait for other's suggestions.

**Comment by srv-twry** [comment]
Appologies, Accidently closed it.

**Comment by brijeshshah13** [comment]
@harshvardhan-takawale @srv-twry I think the approach suggested by @abdulwd would be the best as the whole info matters. Still, wait until @mhutti1 reviews it.

**Comment by RajaVamsi11** [comment]
Another vote for @abdulwd

**Comment by harshvardhan-takawale** [comment]
@mhutti1 @brijeshshah13 @srv-twry @abdulwd @RajaVamsi11 I have one more idea. Can we shift the "localized name" below the "language name"?

**Comment by abdulwd** [comment]
@harshvardhan-takawale That's what I said. :)
If you want to do it for every item, it will increase the size of the list too much. So it would be better to show the **localized name** in next line if the text is long.

**Comment by harshvardhan-takawale** [comment]
@abdulwd I'll have to think how to do that as it would require different layout file for some items only. Also, the size if the list won't increase  even if we move all the **localized names** below as the height of the layout is already fixed as "?android:attr/listPreferredItemHeightSmall", it's just that the text will be a bit smaller for **localized name** .
