### ISSUE TITLE
Problem in full screen mode

### ISSUE THREAD

**Issue by harsh-2711** [kiwix/kiwix-android#530]
**It is a **

- [ ] Bug Report

### Step 1: Are you ready to report?
   - Yes

### Step 2: What is your environment?
  * version of the software you use : 2017-07
  * device / operating system : One Plus 5T
  
### Step 3: Describe the problem:

  * The bottom toolbar disappears as soon as the view is shifted to full screen

#### Steps to reproduce:

  1. In Settings, enable bottom toolbar
  2. From overflow menu, switch to full-screen
 
  * What should be the behaviour from your point of view? How do you expect the service to work?

In full-screen mode also, bottom toolbar should appear so that navigation is easy.
  
![20180228_171823 1](https://user-images.githubusercontent.com/32356267/36786201-87118ce2-1cab-11e8-8e31-1afb94ca20fe.gif)

Want to work on the issue?

Yes

**Comment by harsh-2711** [comment]
please review it @mhutti1

**Comment by arunkiddo** [comment]
Yep I like Work on this issue

**Comment by harsh-2711** [comment]
But I am currently working on it..

**Comment by abdulwd** [comment]
Fullscreen mode is provided to make the UX more immersive. If you want the bottom toolbar, you can switch off **Keep Toolbar Visible** in settings and enable bottom toolbar. That will make the toolbars visible on scrolling else it's fullscreen.
