### ISSUE TITLE
Replace checkboxes with radio buttons in Language selection

### ISSUE THREAD

**Issue by omkarprabhu-98** [kiwix/kiwix-android#531]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

#### Feature Description

Currently the application has checkboxes to select between Languages,

![screenshot_20180228-184931 1](https://user-images.githubusercontent.com/23053768/36789688-69ad9774-1cb8-11e8-9d5e-1287d10b9fb2.png)

<b>This can be replaced with radio buttons for selection</b>

#### Are you willing to work on this issue? 
YES

@mhutti1 , @kelson42 
Could you please me give your thoughts on this issue, will this change work well with the application?

**Comment by abdulwd** [comment]
This is same as #491. I have sent the PR for this so you can safely close this. :)
Also, you must go through the open issues before opening one.

**Comment by omkarprabhu-98** [comment]
Extremely sorry @abdulwd, @kelson42 @mhutti1  
I had searched for issues with checkboxes, didn't find any. Might have missed this one.
