### ISSUE TITLE
Stop music from other apps when Read Aloud is enabled.

### ISSUE THREAD

**Issue by Abishek10** [kiwix/kiwix-android#535]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have tested with the last (dev) version of the software.  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2: What is your environment?
  * version of the software you use : 2.3
  * device / operating system : OnePlus 5T / Android Version 8.0
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful.
When read aloud is enabled, the sound overlaps with any other music playing from other apps.
  * When does this occur? 

#### Steps to reproduce:

  1. Play music from any other application.
  2. Select Read aloud from the menu.
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
The music from other applications should be paused when read aloud is enabled.

**Comment by brijeshshah13** [comment]
@Abishek10 If you are going to work on it, I can assign it to you. Shall I?

**Comment by Abishek10** [comment]
@brijeshshah13 Yes. I am willing to working on it.
