### ISSUE TITLE
App crashes when changing ZIM language in landscape mode

### ISSUE THREAD

**Issue by ISNIT0** [kiwix/kiwix-android#538]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have tested with the last (dev) version of the software.  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2: What is your environment?
  * version of the software you use :  Commit 149088e
  * device / operating system : Android (Nexus 4)
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful.
![screenshot_2018-03-01-14-35-49](https://user-images.githubusercontent.com/5173131/36850285-38d38d24-1d5e-11e8-85ef-d47b25f6f8af.png)

  * When does this occur? 
In Landscape view, on the "Get Content" page under library, clicking the "globe" icon crashes the app

#### Steps to reproduce:

  1. Rotate device to be *portrait*
  2. Go to "Get Content"
  3. Rotate device to be landscape
  4. Click "Online"
  5. Click the globe icon
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
#### Feature Description

Please describe the feature you want to add to the project.

**Comment by harsh-2711** [comment]
It's working fine for me.

**Comment by ISNIT0** [comment]
For more info, see http://159.65.37.191/crash/b5890dbfb57fc1444f88dbf309eac3e7d76f3b0c

**Comment by ISNIT0** [comment]
After happening "reliably" 5 times in a row, it now happens 50% of the time for me.

**Comment by ISNIT0** [comment]
@harsh-2711 What device(s) are you using?

**Comment by harsh-2711** [comment]
One Plus 5T

**Comment by ISNIT0** [comment]
@harsh-2711 Just reproduced it on an Android Emulator

**Comment by brijeshshah13** [comment]
@ISNIT0 Crashing for me as well on Motorola E3 Power, Android 6.0

**Comment by GeVic** [comment]
@ISNIT0 @harsh-2711  It didn't crash for me but i saw a very odd behavior that is after fetching the content online if i change the orientation the content doesn't load again.

**Comment by amerinoo** [comment]
Hi, in my case didn't crash instead of it the screen freeze with a white background.

**Comment by amerinoo** [comment]
@GeVic You are right with "the activity is getting created and destroyed again if the orientation changes." because is the proper behaviour of the fragment lifecycle. When the user rotates the device the view is automatically destroyed and created again. Check this [link](https://stackoverflow.com/a/17135346) for more information.

**Comment by abdulwd** [comment]
Redundant by the new **LanguageActivity**. See #774.
