### ISSUE TITLE
Update title when opening help.

### ISSUE THREAD

**Issue by ashutoshbsathe** [kiwix/kiwix-android#540]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report?
   - [x] I have tested with the last (dev) version of the software.  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2: What is your environment?
  * version of the software you use : Kiwix Dev apk compiled locally from android studio 3
  * device / operating system : Xiaomi Mi A1 / Android 8.0.0
  
### Step 3: Describe the problem:

  * KiwixMobileActivity does not update title on going to help from menu(3 dot menu)

#### Steps to reproduce:

  1. Download some content
  2. Open your content and quit the app
  3. Reopen the app and you will be greeted with your last content
  4. Go to help from 3 dot menu and title will still be the ZimFileTitle
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
  When it goes to help, title of the activity should be properly updated to "Kiwix"

### Step 4 (optional) : Here's a GIF explaining the issue 
(Sorry for the low quality but GitHub won't allow larger GIFs)
![ezgif com-optimize](https://user-images.githubusercontent.com/22210756/36852574-ffd6575c-1d91-11e8-8d2a-03acb8fe7da7.gif)

Yes, I have a fix in my mind and I'll try it out ASAP.
@brijeshshah13

**Comment by brijeshshah13** [comment]
@ashutoshbsathe Please go ahead and fix it.

**Comment by abdulwd** [comment]
Made redundant by the new HelpActivity.
