### ISSUE TITLE
HTML <i> Tag showing in the Navigation menu

### ISSUE THREAD

**Issue by aryanagarwal15** [kiwix/kiwix-android#543]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have tested with the last (dev) version of the software.  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2: What is your environment?
  * version of the software you use : Kiwix Dev apk compiled locally from android studio 3
  * device / operating system : Nexus 5X  / Android 8.1.0
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful.

![Image of Yaktocat](https://preview.ibb.co/hhnuYH/Screenshot_20180301_234121.png)
  * When does this occur?
  All headings which are italic in Wikipedia
 

#### Steps to reproduce:

  1. Go to Get Content
  2. Download Bollywood wikipedia articles
  3. Search for "Ring Master"
  4. Open the Navigation menu.
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
  The HTML tag should not appear in the Navigation Menu

### Step 4 (optional) : Other Comments:
  Have a fix in mind. Would like to work on it.

**Comment by harshvardhan-takawale** [comment]
@aryanagarwal15 An issue has already opened regarding this (Issue #537 ).

**Comment by aryanagarwal15** [comment]
@harshvardhan-takawale Issue #537 only shows this bug in Bookmark activity.

**Comment by harshvardhan-takawale** [comment]
@aryanagarwal15 Actually @ISNIT0 later mentioned about the menu in the comments

**Comment by aryanagarwal15** [comment]
@harshvardhan-takawale Are you already working on it? If yes I'll close this issue.

**Comment by harshvardhan-takawale** [comment]
Yes. Thank you.
