### ISSUE TITLE
Double tap to zoom for main screen

### ISSUE THREAD

**Issue by aryanagarwal15** [kiwix/kiwix-android#544]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

#### Feature Description

Please describe the feature you want to add to the project.
- Currently pinch to zoom in active for the main screen, but double tap to zoom will give users more flexibility to navigate in the application. It is very intuitive to double tao to zoom in a particular word/sentence. 
Leading browsers like chrome and safari already have this feature.

I would like to implement this feature.

**Comment by RajaVamsi11** [comment]
@aryanagarwal15 Nice idea

**Comment by mhutti1** [comment]
@aryanagarwal15 Firstly this might be difficult as it is part of the Android WebView secondly I just tried this out on my phone and chrome does not do this.

This might lead to people accidentally zooming do you have any more evidence to back this up?

**Comment by aryanagarwal15** [comment]
@mhutti1 Chrome (mobile) does have double tap to zoom but it doesn't work for websites that are responsive, try opening website in Desktop mode and using double tap to zoom. You can try using google search as a test site. If you want I can upload a gif for the same.

**Comment by mhutti1** [comment]
@aryanagarwal15 Its an interesting dilemma then because most of our content is responsive but I don't think its under any obligation to be. My gut feeling is that this isn't really needed and will cause more confusion than anything else but if anyone disagrees I would like to here their opinion.

**Comment by brijeshshah13** [comment]
@aryanagarwal15 @RajaVamsi11 I agree with @mhutti1 and do not think it's really needed as we already have pinch to zoom and text size zoom (in progress). This may even lead to accidental opening of unwanted hyper links as there are many in the content.

**Comment by aryanagarwal15** [comment]
@brijeshshah13 So should I close the issue then?

**Comment by brijeshshah13** [comment]
@mhutti1 @aryanagarwal15 Yes please.
