### ISSUE TITLE
Bottom Navigation Bar Scrollable.

### ISSUE THREAD

**Issue by suyash0103** [kiwix/kiwix-android#548]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

### Step 1: Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have tested with the last (dev) version of the software.  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2: What is your environment?
  * version of the software you use : Android Studio 3.0.1
  * device / operating system : Motorola Moto M, Android 7
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful.
Bottom Toolbar can be made scrollable for a better user experience.

  * When does this occur? 
When enabling Bottom Toolbar.

#### Steps to reproduce:

  1. Go to Settings
  2. Enable Bottom Toolbar
  3. Scroll Up and Down
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
Scrollable Bottom Toolbar.

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
Generally used in many mobile applications, gives a better look
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
#### Feature Description

Please describe the feature you want to add to the project.

Can I try implementing this? @mhutti1 @brijeshshah13

**Comment by RajaVamsi11** [comment]
@suyash0103  Decsribe the feature you want to add.

**Comment by mhutti1** [comment]
Firstly the template is a template. You are meant to comment out the questions and write your answer, leaving the whole thing in makes it almost unreadable,

Secondly closing this as I have no clue what you are describing. Please create a new issue with more detail and some graphics.
