### ISSUE TITLE
Allow bookmarks to be sorted into folders

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#55]
_From @mhutti1 on August 25, 2016 14:19_

It should be possible to create folders to easily sort bookmarks.

_Copied from original issue: kiwix/kiwix#295_

**Comment by mhutti1** [comment]
_From @EladKeyshawn on August 25, 2016 20:15_

:+1:  nice suggestion

**Comment by mhutti1** [comment]
Was not my idea :P One of our users suggested it on google play. Now we can make this dream a reality for him/her.

**Comment by mhutti1** [comment]
_From @kelson42 on August 31, 2016 18:47_

Was also reported here https://sourceforge.net/p/kiwix/feature-requests/889/

**Comment by mhutti1** [comment]
I think this would be suitable for GCI if we split it into 2 sub-tasks of:
1. Create the UI with a placeholder array of folder names.
2. Update the database to allow persistence.

**Comment by mhutti1** [comment]
_From @kelson42 on November 13, 2016 13:40_

@mhutti1 OK for me if you have a pretty clear idea how this feature should really looks like. On my side I do not know how to provide all of this (add/move/delete folder/booksmarks) with a simple UI.

**Comment by srv-twry** [comment]
@mhutti1 Can i take this ? Would like to work on this before the other issue(Content Manager tweaks) assigned to me since i need time to think of an intuitive UI for it.

**Comment by mhutti1** [comment]
@srv-twry I would wait for a bit. There were plans to move bookmark management to C++. @kelson42 any news on this?

**Comment by kelson42** [comment]
@mhutti1 Should come around May

**Comment by mhutti1** [comment]
Closing this as it is being made redundant.
