### ISSUE TITLE
Unnecessary padding in Full-Screen 

### ISSUE THREAD

**Issue by GeVic** [kiwix/kiwix-android#561]
### It is a?

- [x] Bug Report
- [ ] Enhancement

### Are you ready to report?
- [x] Ensure you have tested with the last (dev) version of the software.  (If not, and if possible, run your test again with the most recent version available.)

### Environment
  * version of the software you use : **3.0.1**
  * device / operating system : **Huwawei BLN-L22 (Android 7.0 API 24 )**
  
### The Bug:
  * Screen recording of the bug !

![issue-full_screen](https://user-images.githubusercontent.com/29516629/36934038-1942cf90-1f09-11e8-9311-863be5da99b5.gif)

#### Steps to reproduce:

1. **Enable full-screen** from anywhere (Menu or bottom tab)
2. Now draw the **open articles from left**
3. Click on the article/ page
4. You should be able to see the **unnecessary padding** above

  * What should be the behaviour from your point of view? How do you expect the service to work?
     It shouldn't be there if it's not serving any purpose.

### Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
     It gives bad user experience and it create confusion as padding is of same colour.

I would like to work on this issue
@mhutti1 Do let me know what you think.

**Comment by harsh-2711** [comment]
There's no problem with my device. I am using One Plus 5T(Android 8.0). No extra padding is appearing.

**Comment by GeVic** [comment]
@harsh-2711  When i run this repository on the studio it shows the padding even on the emulator but the app "kiwix" on the play store doesn't. 
Can you please tell me why?

**Comment by RohanBh** [comment]
I am confirming that this issue exists. My device is oneplus 3(Android 8.0).

**Comment by harsh-2711** [comment]
@GeVic What is the Android version of your emulator?

**Comment by GeVic** [comment]
@harsh-2711  Its 8.0

**Comment by GeVic** [comment]
@RohanBh Yeah its still there so @mhutti1 can i work on this issue.

**Comment by RohanBh** [comment]
Yes, I think you can start working on it. Mhutti1 might have gone to sleep
now.

On Mar 4, 2018 3:43 PM, "Veeki Yadav" <notifications@github.com> wrote:

@RohanBh <https://github.com/rohanbh> Yeah its still there so @mhutti1
<https://github.com/mhutti1> can i work on this issue.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kiwix/kiwix-android/issues/561#issuecomment-370217338>,
or mute the thread

**Comment by GeVic** [comment]
@RohanBh So i was working on the issue and was trying to fix it and made some changes but as soon as i undo those changes the problem was gone. I don't how but the problem is no longer there.
It would be good if you can also give a check to it in your studio and let me know.
And the problem occurs only when you have not-ticked "Keep toolbar visible". So can you give it a try to be sure?

**Comment by GeVic** [comment]
@RohanBh  also the GIF above was before any changes i made so it's weird.

**Comment by mhutti1** [comment]
At the moment we have about 5 open issues regarding variations on bottom and top bar padding. One could easily have fixed this. @GeVic can you confirm this is now fixed on master so we can close this up?

**Comment by GeVic** [comment]
Sure!

**Comment by GeVic** [comment]
@mhutti1 The issue has been resolved but someone messed up with the search button in the help section as the app crashes when i click on it.
Should i resolve it?

**Comment by GeVic** [comment]
@mhutti1 @RohanBh So it was because of the recent merges made to the searchactivity which made the app to crash.
Should i go ahead and correct those changes?
Anyhow this issue #561 is resolved so you can close this one.

**Comment by mhutti1** [comment]
@GeVic Can you report your crash in a new issue if it isn't already then you can work on it.

**Comment by GeVic** [comment]
@mhutti1 actually it's already been reported by @RohanBh and he created PR too.

**Comment by mhutti1** [comment]
Great, thanks for the work 👍
