### ISSUE TITLE
Refactor: Move Play-Store URI constants to `goToRateApp` method

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#563]
#### Feature Description

Currently the PlayStore URI's are created in the ```initPlayStoreUri``` method in the ```KiwixMobileActivity```. 
They should be made a public static const field inside the ```NetworkUtils``` and used directly inside the Activity.

It's a very simple issue hence should be tackled only by first timers.

**Comment by venomousboxer** [comment]
can I work on this?
I am a first timer.

**Comment by srv-twry** [comment]
Yes, please go ahead.

**Comment by ShreyanshLodha** [comment]
Can I work on this issue?

**Comment by venomousboxer** [comment]
@ShreyanshLodha I have already submitted the pull request

**Comment by bhaskargupta98** [comment]
So we just have to move this method and change it's type?
I'm completely new to open source so not familiar with the way people talk here.

**Comment by kelson42** [comment]
@mhutti1 Could you please help @bhaskargupta98 ?

**Comment by mhutti1** [comment]
A pull request already exists for this so it is not a good issue to start with.

**Comment by bhaskargupta98** [comment]
> A pull request already exists for this so it is not a good issue to start with.

So please tell me where to start from. Actually I'm completely new to development and open source but I'm really intrigued by the concept of Kiwix so wanted to contribute here. I'm fluent in Java so the experts at IRC suggested me to go with Kiwix Android.

**Comment by mhutti1** [comment]
A good place to start might be to add some tests. This will familiarise you with the code base and increase our code coverage :)

**Comment by mhutti1** [comment]
Tests are an important way of detecting regressions. This task is to add some UI tests to the Kiwix Offline Wikipedia Android Project.

We use https://developer.android.com/training/testing/espresso/in this project this allows tests to be written and then run on real devices.

It might be worth checking out https://developer.android.com/studio/test/espresso-test-recorder for a tool to help but it won't do it all for you and there might be edge cases to consider.
