### ISSUE TITLE
Bottom text hidden when toolbar visibility is off

### ISSUE THREAD

**Issue by jb1998** [kiwix/kiwix-android#566]
### Are you ready to report?
   - Yes

### Environment
  * version of the software you use : Android Studio 3.0.1
  * device / operating system : Micromax / 5.0
  
### The Bug:

  * What do you obtain? A copy of the error message or a screenshot is always useful.
gif showing the issue

<img src="https://user-images.githubusercontent.com/23710417/36935061-4ab266e4-1f18-11e8-9c5d-08321d22b59a.gif" height="500" width="300" >

#### Steps to reproduce:

  1. In help screen scroll to bottom and last few lines are not visible
  2. From settings enable "Keep Toolbar Visible"
  3. Then again in help screen scroll to bottom and surprisingly the last few lines are visible

  
  * What should be the behaviour from your point of view? How do you expect the service to work?
The last few lines should be visible no matter "Keep Toolbar Visible" is enabled or disabled.

I would like explore and work on this issue and remove the dependency of bottom text on "Keep Toolbar Visible" option in settings .

**Comment by amerinoo** [comment]
On my phone is working well. I can see the full text without enable the option "Keep Toolbar Visible"

**Comment by srv-twry** [comment]
@amerinoo 
@jb1998 has already mentioned that he would like to explore and work on this issue.

**Comment by amerinoo** [comment]
@srv-twry  Ok, I just wanted to help. I will find another issue for me, any suggestion?

**Comment by srv-twry** [comment]
#583 May be ?

**Comment by abdulwd** [comment]
Fixed in #832.
