### ISSUE TITLE
App directly minimizes on back pressed in full-screen mode

### ISSUE THREAD

**Issue by brijeshshah13** [kiwix/kiwix-android#569]
### Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - Ensure you have tested with the last (dev) version of the software.  (If not, and if possible, run your test again with the most recent version available.)

### Environment
  * version of the software you use : 2.3 build 55
  * device / operating system : Motorola E3 Power, Android version 6.0
  
### The Bug:

  * What do you obtain? A copy of the error message or a screenshot is always useful.

    When in full-screen mode, if back button is pressed, the app directly minimizes.

  * When does this occur? 

#### Steps to reproduce:

  1. Open any screen (hep or content) in full-screen mode
  2. Press back button
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

    The expected behavior should be just to exit to the full-screen mode. Now, this can be implemented 2 ways:

- Just exit the full-screen mode like this:

![20180304_010749](https://user-images.githubusercontent.com/18366144/36938551-faa14040-1f48-11e8-9a56-13112b604c89.gif)

**OR**

- Go back till the parent WebView and then exit the full-screen like this:

![20180304_011016](https://user-images.githubusercontent.com/18366144/36938558-28723506-1f49-11e8-9a41-9caa1a20a737.gif)

Which one should I go with? @mhutti1 @srv-twry Open to your reviews. Others can say their minds as well.

**Comment by srv-twry** [comment]
IMO we should go with the second one i.e. go to the parent webview before exiting the full screen mode. 

Reason: If we go for the first one, then we won't have any way to go back to the previous webview without leaving full screen. In that case the user would have to leave full screen first, go back to previous web view and then enter full screen again.

While in the second option, if he/she wants to stay at the current screen and only leave full screen, the exit full screen button can be used.

Seems fair ?

**Comment by brijeshshah13** [comment]
@srv-twry Sounds logical to me. I'll wait for @mhutti1's view, although I think even he will go with the second one.

**Comment by RohanBh** [comment]
I too think that the second approach is better.

**Comment by mhutti1** [comment]
Yeah second sounds better.
