### ISSUE TITLE
Screen Rotation deletes the user input in the search bar

### ISSUE THREAD

**Issue by vansh1sh** [kiwix/kiwix-android#572]
**Is it a ?**

- [x] Bug Report

### Step 1: Are you ready to report?
   - [x] I have tested with the last (dev) version of the software.  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2: What is your environment?
  * version of the software you use :  3.0.1
  * device / operating system :  Samsung J7 / 7.0
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful.
    
    When the device is rotated, activity is destroyed and re created resulting in loss of search input by 
    the user.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16793070/36939780-1e4a6120-1f5d-11e8-8e5b-d27e84158d45.gif)

   
### Step 4 (optional) : Other Comments:

  * What is the context of this ticket? If not obvious, explain why you need to do this.
     Screen rotation should be handled correctly in order to prevent state destruction.
    
   
Please describe the feature you want to add to the project.

I would like to work on this issue.
@mhutti1 @brijeshshah13 Do let me know what you think.

**Comment by brijeshshah13** [comment]
@vansh1sh Please go ahead and fix it.

**Comment by aditmehta9** [comment]
@brijeshshah13  when made changes in the app and installed it again on the device, changes weren't shown in the original app instead a custom test app was installed. Please help me how can I make changes in main app and install that on my device with the changes I made?

**Comment by abdulwd** [comment]
@aditmehta9 You need to select the build variant as **kiwixDebug** which you will find on the left side in Android Studio.

**Comment by aditmehta9** [comment]
Thank you veyr much @abdulwd

**Comment by ilovrencic** [comment]
I would like to tackle this problem. Is anybody still working on this?

**Comment by abdulwd** [comment]
@ilovrencic You may work on this issue if it still persists otherwise you can report that it has been resolved and we can close this.

**Comment by Afleh** [comment]
@abdulwd  can i work on this?

**Comment by abdulwd** [comment]
@Afleh Can you check if it still persists?

**Comment by sauravchandra** [comment]
@abdulwd The issue seems to be resolved.


![rotate-issue](https://user-images.githubusercontent.com/10370619/54549583-5afbfe00-49d0-11e9-8094-99af8775a1c1.gif)
