### ISSUE TITLE
Bottom Toolbar hides the content of the last few lines on any page

### ISSUE THREAD

**Issue by RohanBh** [kiwix/kiwix-android#573]
### Are you ready to report?
Yes

### Environment
  * version of the software you use : v2.3 Build 55
  * device / operating system : oneplus 3, Android 8.0
  
### The Bug:

![20180304_035223](https://user-images.githubusercontent.com/24610859/36939934-a27c2134-1f5f-11e8-9605-51f0d4e3a220.gif)
The Bottom Toolbar when visible hides the last few lines of the webpage. 

#### Steps to reproduce:

  1. Enable Bottom Toolbar from the settings screen 
  2. Try scrolling down to last line

Expected Behavior: Either the webview should resize so that it is not covered by the Bottom Toolbar or the Bottom Toolbar should disappear when we reach at the end of the page. 

I would like to work on this. 

Please reviews @mhutti1 @kelson42 @brijeshshah13.

**Comment by mhutti1** [comment]
I am very worried about us simply going in circles with #555 and #556 and this possibly. These issues must be fixed synchronously not concurrently otherwise its very likely you will accidentally just undo each others work to get your issue fixed.

**Comment by RohanBh** [comment]
I agree with you. I noticed this issue while working on [this PR](https://github.com/kiwix/kiwix-android/pull/570), since movement of bottom toolbar is constrained with that of action bar. So I opened this as soon as I completed that PR without realizing that similar issues have been opened.
Should I close this issue now?

**Comment by mhutti1** [comment]
Its up to you. Imo we should combine all issues relating to this into a single issue.

**Comment by brijeshshah13** [comment]
@RohanBh @mhutti1 Agreed. There are multiple people working on this same task under different issues and PR's. Also, please note that we require a fix and not a hack.

**Comment by RohanBh** [comment]
@brijeshshah13 What do you mean by a hack?

**Comment by brijeshshah13** [comment]
@RohanBh Like making the bottom toolbar transparent or as such.

**Comment by RohanBh** [comment]
@mhutti1 How do we merge these issues? I can think of creating a main issue covering all the points in these sub-issues. Then reference the main issue from all these sub-issues and close them.
Or we can assign a person to work on all these issues and when he makes a PR, he'll just reference all these issues at once, thereby closing them as the PR is merged.

**Comment by brijeshshah13** [comment]
@RohanBh The first approach sounds better.

**Comment by mhutti1** [comment]
Yeah we should do that. The person who created the first issue should get first attempt at solving the combined issue and the second next as such.

**Comment by abdulwd** [comment]
I have fixed this in #832.
