### ISSUE TITLE
Open downloaded content library section on closing last tab

### ISSUE THREAD

**Issue by sdivakarrajesh** [kiwix/kiwix-android#574]
### Are you ready to report?
   - Yes
 

### Environment
  * version of the software you use : 2.3 Build 55
  * device / operating system : nexus 5(Emulator) / Nougat
  
### The Bug:

  * Closing the last tab (with the first page) of the  article opens the first page of the same article again
  * it should open the available downloaded articles (in device section)  

#### Steps to reproduce:

  1. Download and open an article
  2. Open the left drawer and close the tab with the main page

![test](https://user-images.githubusercontent.com/30803637/36943338-d547388a-1fad-11e8-817c-e93470189cd3.gif)

  
  * It should open the downloaded articles available in the device

**Comment by mhutti1** [comment]
No it should not. For now the current solution is what is intended.
