### ISSUE TITLE
Refactor: Unify common code in BookDao

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#581]
#### Feature Description

BookDao contains methods ```getDownloadingBooks```, ```getBooks```, ```saveBook``` and ```saveBooks```. There is a lot of common code between ```getDownloadingBooks``` and ```getBooks```. We should extract out the common code in another method. 
Similarly in case of ```saveBook``` and ```saveBooks```.

**Comment by GeVic** [comment]
@srv-twry i would like to work on this.

**Comment by GeVic** [comment]
@srv-twry  I would like to work on this.

**Comment by srv-twry** [comment]
Please go ahead.
