### ISSUE TITLE
Icons are clumped together in RTL global search

### ISSUE THREAD

**Issue by RohanBh** [kiwix/kiwix-android#582]
### Are you ready to report?
   Yes
### Environment
  * version of the software you use: v2.3 Build 55
  * device / operating system: oneplus 3, Android 8.0
  
### The Bug:
In LTR searching, back arrow and the cross are opposite to each other. But, in RTL searching, both of these icons clump together in the left corner.
![LTR](https://user-images.githubusercontent.com/24610859/36939308-9f9fadf6-1f54-11e8-91ab-f2dcd5f385d2.jpg)
![RTL](https://user-images.githubusercontent.com/24610859/36939290-6ef1cac2-1f54-11e8-93c2-85cf97300a61.jpg)

#### Steps to reproduce:

  1. Enable Force RTL option from developer settings on your device.
  2. Type something in the global search bar.
  
Expected behavior: The icons must be at the opposite ends in RTL searching too.

I am working on this.

**Comment by RohanBh** [comment]
@mhutti1 I have fixed this issue. But currently, search activity crashes when it opens in the master branch. Can you please take a look at [this PR](https://github.com/kiwix/kiwix-android/pull/586) which fixes the crash, so that I can create a PR for this issue. Also, the work that is done in this PR so less. I was wondering if I can make a PR that fixes #365 as well since they are related.

**Comment by mhutti1** [comment]
give @Koundinyalanka one more day then you can be reassigned.

**Comment by RohanBh** [comment]
Can I be assigned #365 now @mhutti1?

**Comment by kelson42** [comment]
@RohanBh Any news on this?

**Comment by RohanBh** [comment]
@kelson42 I was busy with a project for this college fest this week. I have made a PR now fixing the assigned issues. Sorry for the delay.
