### ISSUE TITLE
Refactor: Make KiwixDatabase and DAOs available through DI

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#583]
# For a Feature Request:

#### Feature Description

Currently we aren't using Dependency injection for KiwixDatabase and it's DAO classes. We must provide them using Dagger.

**Comment by amerinoo** [comment]
I will work on that.

**Comment by mhutti1** [comment]
Read up on it and look what we have already implemented in the di folder.

**Comment by srv-twry** [comment]
@amerinoo Status please ?

**Comment by amerinoo** [comment]
Working on that. I've have never use it so I'm going slow.

**Comment by abdulwd** [comment]
Closed via #721
