### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by anandwana001** [kiwix/kiwix-android#588]
## Feature Request
Improve Readme 

#### Feature Description
Improve Readme file with play store account link, app logo, chat badge and Used libraries description which can help newcomers to get easy access and it makes readme file look appropriate

**Comment by abdulwd** [comment]
I think we must further improve the documents like **README.md**, **CONTRIBUTING.md**, etc.
I have seen for small changes contributors are making multiple commits. So we must include this, that a single commit is sufficient for such type of changes and multiple commits are only required when solving a big issue.
Also, I think **COPYING** should be renamed to **LICENSE.md**.
If someone can incorporate all these things and improve these documents it will be great!
Maintainers can give more feedback on this. I don't know if it has been done in another issue.

**Comment by mhutti1** [comment]
Related to #112

**Comment by srv-twry** [comment]
> So we must include this, that a single commit is sufficient for such type of changes and multiple commits are only required when solving a big issue.

There should be a single commit before opening a PR but they shouldn't squash the commits into one after changes have been requested on the PR. It is quite easier to review PRs in that way as that would allow the reviewer to check the changes after the changes were requested. 
Also i believe multiple commits are never a problem. After the PR is reviewed and approved, @mhutti1 can easily squash and merge the commits using the github interface only with the suitable commit message.

**Comment by mhutti1** [comment]
This depends. The issue arises when it is a large change that would ideally be split into multiple commits but because of a messy history I am left with no option but to squash and merge. It is more on a case by case basis though.
