### ISSUE TITLE
Kiwix doesn't work with talk back

### ISSUE THREAD

**Issue by amirh123123** [kiwix/kiwix-android#590]
#### Feature Description

Get Talk back reading Kiwix articles

https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback&hl=en_GB

**Comment by ashutoshbsathe** [comment]
I'm not clear with what issue you are having
But you need to enable "Read aloud" function for reading aloud

**Comment by amirh123123** [comment]
hi i use talk back but cant read articles with touching

**Comment by RajaVamsi11** [comment]
@amirh123123  Are you working on this issue?

**Comment by amirh123123** [comment]
hi i use talk back but not read articles in kiwix i connect to internet and open article in kiwix but read article

**Comment by ritwikagarwal** [comment]
Are all objects labelled?
Are decorative objects ignored?
Are all form inputs labelled?
Are changes of state announced?
Are the correct input types used?
Is content order logical

Check these on Lint.
Also there may be problems for talk back to render articles from web as it can't access web content from hybrid apps So web accessibility can be enhanced from the Setting option in the mobile.

In either case the articles have to be properly downloaded on the app as local content and not merely as an offline web content which is an interesting thing to be worked on.

**Comment by amirh123123** [comment]
hi 
Where to access the settings thanks for helping

**Comment by kelson42** [comment]
"Read aloud" is the feature to read full article or selection. You can access it via the app. menu.
