### ISSUE TITLE
Update to Dagger 2.15

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#591]
## Feature Request
Update **Dagger** to version **_2.15_**
#### Feature Description
**Dagger** is a great dependency injection framework but presently, we are using **Dagger 2.0.2** which was released around 2 years ago. Many improvements have been made in 2 years so we must upgrade to the latest version.
After upgrading the version number, many changes might have to be made in the code since **Dagger** has changed a bit. I am quite versed in using this framework. So I can refactor the code.

@mhutti1 Please review this issue.

**Comment by mhutti1** [comment]
Yeah we should go ahead but after #515 has been sorted.

**Comment by srv-twry** [comment]
@mhutti1 What do you mean by "sorted" ? Isn't it already merged ?
