### ISSUE TITLE
Bug: Navigation buttons of left sliding-tab

### ISSUE THREAD

**Issue by Aditya-Sood** [kiwix/kiwix-android#592]
### Environment
  * version of the software you use : v2.2
  * device / operating system : Moto G5 Plus / Android 7.0
  
### The Bug:

  * What do you obtain?
The navigational history of the current collection-tab (in terms of which of the two directions, forward and/or backward, can the user navigate to from the current position) is carried forward to the next collection-tab a user navigates to from the left sliding-tab.

  * When does this occur? 
Whenever more than one collection-tab is open, and the user jumps to another collection-tab using the left sliding-tab, the navigational history is carried forward.

#### Steps to reproduce:

In the end, you'll see the erroneously enabled right arrow:

![mobizen_20180306_214539](https://user-images.githubusercontent.com/15438998/37046089-7be70c16-218d-11e8-9222-9536da54f61f.gif)

Steps followed in the gif:
  1. Open a collection from the list of downloaded ones.
  2. A collection-tab with the main page will already be opened. DO NOT tap on any of the links on this collection-tab.
  3. Swipe right to open the left sliding-tab, and tap on the '+' button to open a new (main page) collection-tab.
  4. On this newly opened collection-tab, tap on any link to navigate to another page (in the same collection-tab).
  5. Repeat step 4 at least once, then go back by one page. (Now, you should be at a page which has a previously opened page in both the left and right 'directions')
  6. Swipe right to open the left sliding-tab, and tap on the originally opened 'Main Page' collection-tab.
  7. After coming onto this original collection-tab, again swipe right to open the left sliding-tab. You'll notice that the right navigation button is activated, even though you didn't jump/use a link on this page.

### Other Comments:
The history is carried forward only in the case of previously open collection-tabs. It is not carried onto a newly created collection-tab.

Even in the case of a previously open tab when the history is carried forward,
(i) By navigating in the right direction (if required navigation button is enabled in the left sliding-tab, or by pressing back), or
(ii) If the app is paused (no longer in foreground), and then resumed

Both the cases restore the correct history of navigation.

  * What is the context of this ticket?
This bug either leaves users with additionally enabled button(s) which don't work, or disables buttons which should work. Both are undesirable, **_especially_** in case of visually-impaired users who heavily depend on the app to show them the correct navigation options available for use.
 
  * If you have an idea about the technical background of the ticket, please share it.
This is probably an issue of the newly opened tab accessing the navigation history of the previous tab instead of reloading the history of the current tab.

### Intent to work on the issue
Also, I would like to work on the issue. I've already started digging around for it.

**Comment by Aditya-Sood** [comment]
@mhutti1 
Pl have a look at the issue

**Comment by brijeshshah13** [comment]
@Aditya-Sood Nice work finding out this bug. Please go ahead and try to fix it.

**Comment by Aditya-Sood** [comment]
@brijeshshah13 
Thanks
I'll get started
