### ISSUE TITLE
Removing application, Downloaded ZIM file still in storage.

### ISSUE THREAD

**Issue by JunsuLime** [kiwix/kiwix-android#596]
### Are you ready to report?
Ready to report :)

### Environment
  * version of the software you use : version name 2.3, version_code 55
  * device / operating system : Huawei honor A6 / Android 7.0
  
### The Bug

Exactly, Not Bug but enhancement. 

* **Problem**
When we remove Kiwix application, Downloaded zim files are remained. Zim file is so large that it takes up our device storage space.

* **Suggestion**
Removing Kiwix application, remove downloaded file too (If downloaded file is in our default device storage).

* **Steps to reproduce**

  1. Install Kiwix application.
  2. Download several zim files.
  3. Remove Kiwix application.

  Then we can see that zim file still in our device storage.

I would like to work on this issue !!

**Comment by mhutti1** [comment]
Actively removing files on uninstall is  impossible without workarounds violating Androids TOS. In most cases we should be using a file location that should get cleaned up by Android but on some devices we are direct to use an external (or fake external) location that does not do this. Do you have any specific workarounds to this as it has been discussed in multiple places before?

**Comment by JunsuLime** [comment]
## Problem

Current codes of Kiwix get default download directory by 
```java
SD_CARD = Environment.getExternalStorageDirectory().getPath();
KIWIX_ROOT = SD_CARD + "/Klwix/;
```
In this code, `SD_CARD` is user accessible storage. And `KIWIX_ROOT` is Kiwix dowloaded files directory.
`KIWIX_ROOT` is not dependent on Application because it is not included in application data folder.

So, when we remove Kiwix application, this directory and files are not removed.

## How to solve

Instead of `Environment.getExernalStorageDirectory().getPath()` Using
```
context.getExternalFilesDir(type)
```
is good way to solve this problem. this method returns  `[user accessible dir]/Android/data/[app package name]/[type]`

This directory is removed when application is removed because this path is dependent on application.
Using this path to download files, we can remove local app data(like zim file) when we remove application.

I've tested this in
* Huawei Honor A6

by modifying kiwix code `DownloadService.java`

```java
// KIWIX_ROOT = SD_CARD + "/KIWIX/
KIWIX_ROOT = getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS).getPath();
```

And it works like I expected.

1. Check remained storage size
2. Save large file with using path `[user accessible dir]/Android/data/[app package name]/[type]`
3. Check application's size and data size.
4. Remove application.
5. Check remained storage size and application data path
6. If remained storage size is same as we expected and data path is removed, OK

**Comment by mhutti1** [comment]
"Returns the absolute path to the directory on the primary shared/external storage device where the application can place persistent files it owns. These files are internal to the applications, and not typically visible to the user as media." from https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir(java.lang.String). Is this misleading and can the user and other programs always access these files? I didn't think that was the case.

**Comment by JunsuLime** [comment]
Except Kiwix, other programs need to access downloaded zim file too?

If downloaded zim file is only for Kiwix, then It will work. 
Doing something through Kiwix application, user can control all files in `getExternalFilesDir(...).getPath`.

**Comment by mhutti1** [comment]
@JunsuLime Its debatable. One of the great aspects of ZIM files is they are shareable. That is why I think this feature is fairly essential. @kelson42 any views?

**Comment by JunsuLime** [comment]
Oh! If ZIM file needs to be shared with other application then .., should not get rid of the file when application is removed.

Is there any case using ZIM file in other application?

**Comment by kelson42** [comment]
I think we can arg for both approaches. I'm not myself sure what is the best solution. Probably to propose a choice to the user... but that seems impossible :( So probably keeping it like it is is the best approach.

**Comment by mhutti1** [comment]
It is probably possible to ask them but idk if its worth it. I think also as they can select a path themselves to save ZIM files to it might not be needed entirely.

**Comment by Raghav-intrigue** [comment]
I believe that if we want the zim files to be shareable, we can add a share option in the content management page which would allow the user to share the large files via ShareIt or any other peer to peer sharing system easily. 
This would also allow us to keep the storage path in the Kiwix Root and not having the user worry about the storage location as well. Plus the zim files which remain after uninstall do pose a cleaning problem which is faced by our users. The users do believe that if they're uninstalling the app, they are deleting everything related to it as well.

**Comment by kelson42** [comment]
I my case, using nightly, it in fact already works as this - and this is annoying to me:
1 - Download last nightly
2 - Download a large ZIM file
3 - Kiwix complains that I do not have enought storage and I should the external SD card
4 - Download goes to the end and everything works fine.
5 - ZIM file (chunks) are stored in /storage/9724-C9BE/Android/data/org.kiwix.kiwixmobile/files/Kiwix
6 - Uninstall Kiwix (because I want to test a new nightly)
7 - Install new nightly, my large ZIM file is not available... and has been deleted during previous uninstallation process.

**Comment by mhutti1** [comment]
It might be nice to expose this to the user but it is a difficult concept to convey.

**Comment by brijeshshah13** [comment]
@kelson42 @mhutti1 How about we simply inform the users that the ZIM files will not be deleted when they uninstall the app and the instructions to remove them if they want to, in either the `Help` page or a message via a Dialog box when they download their first ZIM file.

**Comment by Popolechien** [comment]
Disagree. If the user doesn't want Kiwix there is little reason for them to want to keep the zim files, and we have to aim at lowest tech skill possible (ie people won't be able to/won't bother look into a file storage tree).
There is no point in semi-stealth occupation of useful storage space (it's not like zim files are small and unobstrusive).

**Comment by brijeshshah13** [comment]
@Popolechien I agree. I was just providing an approach to inform the users about the same if in case we finalize not to remove the ZIM files.

**Comment by kelson42** [comment]
@macgills I strongly suspect this will be clarified with 3.0?

**Comment by macgills** [comment]
All files will be in app private storage whether that is internal or removable storage so it will be deleted on uninstall

**Comment by kelson42** [comment]
OK, so this can be considered to be done in 3.0.
