### ISSUE TITLE
App crushes when pause the download whose progress is 100%

### ISSUE THREAD

**Issue by Wanjuuuuu** [kiwix/kiwix-android#597]
### Environment
  * version of the software you use : version name 2.3
  * device / operating system :  Galaxy S8 / Android 7.0
  
### The Bug:

When the progress of download is 100% and clicked the pause button, app crush has occurred.

* Why happened?
Since the downloaded one has already been cleared in another worker thread, cannot access and pause it. It would be better to check whether done or not before pausing.

* Steps to reproduce:
  1. Download the files.
  2. Pause the download when progress is 100%.
  3. App Crushes.
 
P.S.
Most of time when download has finished, it disappears. However, I found some cases it remained.
It is a pity that I have not recognized why it remains. Anyhow, I would like to work on no more crush happened again.

**Comment by macgills** [comment]
Fixed in #1170
