### ISSUE TITLE
[Bug] TextView going out of the screen in landscape view

### ISSUE THREAD

**Issue by divyanshub024** [kiwix/kiwix-android#599]
# Bug 

## Environment
  * version of the software you use: Android Studio 3.0.1
  * device / operating system : Nexus 6 / Android 7.0.1
  
### The Bug:
Bottom TextView in Home screen with the text "Thank you for choosing Kiwix" is going out of the screen in landscape view.

### Image
![device-2018-03-08-113400](https://user-images.githubusercontent.com/16731434/37136374-56bc5096-22c7-11e8-8cbf-8a8810faa5cd.png)

**Comment by brijeshshah13** [comment]
Duplicate #555.
