### ISSUE TITLE
Problem with WikiMed on Android 7.0

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#6]
From the OTRS feedback queue:
"This app is very useful and thank you.
But I want to report a problem that it doesn't work on android 7.0
It worked correctly on android 6 but since I upgrade to android 7 it doesn't and get error: The selected file is not a valid ZIM file. and then show nothing but a white page.
I attached a screenshot of that error"
![screenshot_20170206-024203](https://cloud.githubusercontent.com/assets/21675885/22640465/0c5bdc3e-ec53-11e6-91c4-d152dc079c4b.png)

**Comment by kelson42** [comment]
@mhutti1 We should really verify this. Sounds weird to me.

**Comment by mhutti1** [comment]
@kelson42 This sounds like its an Android issue. Can we get the user to reinstall the app?

**Comment by kelson42** [comment]
@Popolechien What is the status on this? Could you ask the user to reinstall the app?

**Comment by Popolechien** [comment]
It looks like the user had reinstalled the app back then. I'll ping him again.

**Comment by kelson42** [comment]
@Popolechien without feedback, we will have to close that ticket.

**Comment by Popolechien** [comment]
No more feedback from user. Case closed.
