### ISSUE TITLE
[PLAY STORE] Custom app/Wikimed fails to install on low-end devices

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#60]
_From @kelson42 on September 11, 2016 9:8_

A few people report that they are not able to install the Wikimed app (in English). The installation crashs at 99%. At a first I thought this is a problem with the internet connection, but it seems that we face here an other problem. I suspect Google Play to compress the companion files and then to crash during the decompression of this file at the installation time. This might be cause (here too) by a lack of memory - considering that the Wikimed ZIM file (companion file) is 1GB big. I think that if we cut the ZIM file in many parts, then it should be able to install correctly, even on low-end devices.

Feedbacks about this theory welcome.

_Copied from original issue: kiwix/kiwix#310_

**Comment by mhutti1** [comment]
_From @julianharty on September 11, 2016 20:47_

I've got some low-end devices and can test the theory locally. I'm
interested in learning more about the download process that's integrated
into Google's system for extension files anyway. I thought there was a
2-file limit for extension files anyway, so if we were to chop the file
into several smaller ones we're likely to break the Google guidelines
anyway (there are ways it could be done from what I can tell from reading
the documentation
https://developer.android.com/google/play/expansion-files.html e.g. by
using App A to download expansion files for App A and App B (etc) however
this might not work - it depends on how the Application Licensing service
generates the URLs and whether it somehow enforces a limit that App A can
only download the files uploaded with App A, etc.

"However, in some cases your app must download the expansion files itself
by requesting them from a URL provided to you in a response from Google
Play's Application Licensing
https://developer.android.com/google/play/licensing/index.html service."

There is also a discussion in the article on compression, limits to
compression, reading from zip file formats, etc. I don't know whether
Google applies additional compression OTA for files that are already
compressed. TBD... I'm also interested on how robust the partial download
and continue mechanisms are. From some of the review comments I've seen it
seems there may be flaws where Google Play restarts downloads when the
network connection is flaky (and eats up all the user's credits). If we're
able to find a way to chop the files into smaller discrete pieces that can
be (a) transferred reliably on whatever flavour of connection and whatever
spec of supported device and (b) the files can be used independently
without needing the entire volume of material to be downloaded before any
can be used - I think we may be able to make a significant number of users
happier.
Ciao for now

Julian

**Comment by mhutti1** [comment]
_From @kelson42 on October 15, 2016 10:53_

@julianharty any test results about this?

**Comment by kelson42** [comment]
@macgills I propose to pospine that one, it has to be a problem with Play app or the device... Nothing I believe we can easily fix on our side in this milestone.

**Comment by macgills** [comment]
There is really nothing to be done, using obb files we can at most provide 2 files to the user so splitting is not incredibly viable here. I'd close it as won't fix

**Comment by kelson42** [comment]
We have revamped the system of installation. I will close this ticket for now and this should be reopen if we still have problems. In worse case the direct download fallback we have implemented should save most of the edge cases.
