### ISSUE TITLE
Download do not continue after device restart

### ISSUE THREAD

**Issue by divyanshub024** [kiwix/kiwix-android#601]
#### Feature Description

The download does not continue when you restart the device while downloading.

**Comment by mhutti1** [comment]
@divyanshub024 If you reopen our download page it does work for me. Are you sure this is the case for you?

**Comment by divyanshub024** [comment]
Yes, this is the case. I tried 2-3 times it doesn't work for me.

**Comment by divyanshub024** [comment]
@mhutti1 It's working now. Maybe there was some other problem before.
