### ISSUE TITLE
Online content reloads again after screen rotation 

### ISSUE THREAD

**Issue by divyanshub024** [kiwix/kiwix-android#608]
### Are you ready to report?
   
yes

### Environment
  * version of the software you use: Latest master
  * device / operating system: Nexus 6/ Android 7.1
  
### The Bug:
Online Content reload again after screen rotation. 

#### Steps to reproduce:

  1. **go to** get content -> online
  2. Load the content
  3. change screen orientation

  * **What should be the behavior from your point of view? How do you expect the service to work?**
App should save its state when screen orientation is changed.

**Comment by GeVic** [comment]
@divyanshub024 This issue is already reported #559 and worked on

**Comment by GeVic** [comment]
@divyanshub024 This issue has already been reported #559 and being worked on.

**Comment by divyanshub024** [comment]
Ok, I will close the issue.
