### ISSUE TITLE
[Bug] Bottom toolbar hides reading aloud control toolbar

### ISSUE THREAD

**Issue by divyanshub024** [kiwix/kiwix-android#609]
### Are you ready to report?
   -Yes
### Environment
  * version of the software you use: Latest master
  * device / operating system: Nexus 6/ Android 7.1
  
### The Bug:

  When you enable the bottom toolbar and start reading aloud, the bottom toolbar will hide reading aloud control bar.

**Comment by GeVic** [comment]
It's a bug and it happens when "Keep toolbar visible" is true otherwise it's fine.
I can resolve the issue, should i start working on it @mhutti1

**Comment by divyanshub024** [comment]
even if  "Keep toolbar visible" is false the toolbar will hide only on scroll otherwise it will be shown, which is not the correct way.

**Comment by divyanshub024** [comment]
@GeVic @mhutti1 I think we should allow users to control the reading aloud feature from notification just like other music apps do. @mhutti1 if you allow I can start working on that.

**Comment by GeVic** [comment]
@divyanshub024  Actually yeah you are right, and since you wants to work on it i'll take a step back.

**Comment by mhutti1** [comment]
@divyanshub024 That sounds like a good idea but please create a separate issue.

**Comment by divyanshub024** [comment]
@mhutti1 sure. But what do you think about this issue? How should this issue be resolved?

**Comment by mhutti1** [comment]
We have a lot of trouble with the Bottom bar atm. I think its best too wait that out for a bit and see if this is resolved.

**Comment by abdulwd** [comment]
Fixed in #832.
