### ISSUE TITLE
FDroid version update

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#61]
_From @homlett on September 15, 2016 16:52_

Kiwix for Android sounds great, but it should to be updated.

_Copied from original issue: kiwix/kiwix#312_

**Comment by mhutti1** [comment]
_From @kelson42 on September 15, 2016 18:47_

@homlett Why not asking the FDroid team?

**Comment by mhutti1** [comment]
@kelson42 I think he is asking why fdroid version is 1.97 but google play version is 1.99

**Comment by mhutti1** [comment]
_From @kelson42 on September 15, 2016 18:51_

@mhutti1 I don't know. The question should be asked to the FDroid team. I have tried to ping them a little bit without success. Now, the best is to release 2.0 and then ask again I think.

**Comment by mhutti1** [comment]
@kelson42 Ok I might look into it a bit after 2.0 release.

**Comment by mhutti1** [comment]
_From @kelson42 on December 4, 2016 20:26_

The problem is that they have a strange Python problem. They told me they will retry but no news. I have asked again today someone of the Fdroid team.

**Comment by mhutti1** [comment]
_From @kelson42 on February 13, 2017 18:56_

@rashiq Could you please have a special look to this ticket as you know personnaly mvdan and are familliar with both Android an Python?

**Comment by mhutti1** [comment]
_From @rashiq on February 13, 2017 18:57_

@kelson42 will do! I only noticed a few days ago that the kiwix version on fdroid is very outdated

**Comment by mhutti1** [comment]
_From @kelson42 on February 13, 2017 18:59_

@rashiq Thx very much. Yes, because (what looks like to be) a silly Python bug/problem, FDroid is behind our release mgmt of more than 6 months.

**Comment by mhutti1** [comment]
_From @mvdan on March 4, 2017 21:18_

@rashiq did indeed stalk me in real life, so I'm having a look at the moment.

To provide some context, Kiwix is one of the more complex builds on the main repo so it makes sense that it would easily fall behind unless someone actively works on updates.

**Comment by mhutti1** [comment]
_From @mvdan on March 4, 2017 22:12_

This took a while, but got a build working. Pushed https://gitlab.com/fdroid/fdroiddata/commit/6e10f23954ed608ccf6a1cbad5741886dfdaa21b.

**Comment by mhutti1** [comment]
_From @rashiq on March 4, 2017 22:24_

Thanks again @mvdan :)

**Comment by mhutti1** [comment]
_From @kelson42 on March 5, 2017 10:40_

@mvdan @rashiq Thank you very much for the good work. @mgautierfr is currently working to revamp compilation scripts for the whole project (Android included). Things should be over next week for Android. It should make the maintenance work on FDroid side easier. I least we hope so... let see for the next releases :)

**Comment by mhutti1** [comment]
_From @mvdan on March 12, 2017 19:42_

This is really weird - the build worked locally, but we're hitting the same utf8 error on the buildserver: https://f-droid.org/wiki/page/org.kiwix.kiwixmobile/lastbuild_45

I've filed a very probable fix for this in our python codebase: https://gitlab.com/fdroid/fdroidserver/merge_requests/224

When I first encountered this crash, I think my understanding of encodings in Python just wasn't good enough to figure out a proper fix. This still isn't perfect - it will ignore the bytes - but it's certainly better than a crash.

Will update this issue if there are any news.

**Comment by mhutti1** [comment]
_From @mvdan on March 15, 2017 12:33_

There happens to be a huge backlog of apps with failing builds, so this is taking longer than usual. Still waiting on a build with the updated python code.

**Comment by mhutti1** [comment]
_From @mvdan on March 16, 2017 11:19_

Finally succeeded: https://f-droid.org/wiki/page/org.kiwix.kiwixmobile/lastbuild_45

The index update will happen in a few hours - then it will be visible on https://f-droid.org/app/org.kiwix.kiwixmobile

**Comment by mhutti1** [comment]
_From @rashiq on March 16, 2017 14:49_

Awesome! Thanks :)

Daniel Martí <notifications@github.com> schrieb am Do., 16. März 2017,
12:19:

**Comment by mhutti1** [comment]
_From @kelson42 on March 18, 2017 10:56_

@mvdan I just saw this morning that Kiwix has been updated on my Fdroid! Yohoo! Then I remarked... that this is not the last version: this is version 2.1 and we have released 2.2 a few weeks ago. Not sure the reason why, maybe because we did not had tagged the git for Kiwix git repo correctly. Anyway, I have done this now https://github.com/kiwix/kiwix/releases/tag/android_v2.20... and may you please try to update to 2.2?

**Comment by mvdan** [comment]
@kelson42 yeah, I didn't see 2.2 because there just wasn't a git tag.

Should we build from this new repo or from the regular one, then? I assume 2.2 still uses the same build system, still?

**Comment by kelson42** [comment]
@mvdan The build with the new repo (kiwix-android) is slightly different. I guess we will have a look together to this at some point, but later (and in an other ticket). 2.2 is available on the "legacy" repo like before, so you should just have to change the revision/tag to checkout and it should work (at least I hope so).

**Comment by mvdan** [comment]
Cool, I'll add the build then. This issue can be closed - just nag me here or on IRC if it doesn't show up in a day or two.

**Comment by kelson42** [comment]
@mvdan OK, thx a lot a again for your help on this!

**Comment by Bubu** [comment]
@kelson42 This was just reported as outdated on the F-Droid tracker again: https://gitlab.com/fdroid/fdroiddata/issues/1083

I'm not sure from which repo and how I could find the code that corresponds to the releases. Could you help me a bit here?

**Comment by mhutti1** [comment]
@Bubu As far as I can see the f droid version is still the current release build (2.2) but with a slightly lower build number.

**Comment by Bubu** [comment]
@mhutti1 Do you make multiple releases with the same version number? (This is fine and f-droid can work with that.)

Or rather the question is: Do we need to update the f-droid version at all right now?

**Comment by mhutti1** [comment]
@Bubu the f-droid version does not need updating right now. We have moved to a different build system and will have architecture specific apks with different version codes from our next release (3.0) onwards.

**Comment by Bubu** [comment]
Alright, thanks for the explanation. You can ping me, when you are at this point. (@mvdan left F-Droid a while ago.)

**Comment by mhutti1** [comment]
We have released version 2.4 (as 3.0 was taking longer than expected) so this version should be published.

**Comment by gilcu3** [comment]
Is current version (2.5) rolling to f-droid?

**Comment by kelson42** [comment]
@gilcu3 This is still a task to do :(

**Comment by kelson42** [comment]
FDroid has beeb updated with 2.5.1
