### ISSUE TITLE
[Bug] Bottom toolbar is allowing "Help" to be bookmarked

### ISSUE THREAD

**Issue by divyanshub024** [kiwix/kiwix-android#610]
### Are you ready to report?
   - Yes

### Environment
  * version of the software you use : Latest master
  * device / operating system : Android 7.1
  
### The Bug:

  Action bar doesn't allow Help to be bookmarked but when you enable bottom toolbar, it allows you to bookmark help.

**What should be the behaviour from your point of view? How do you expect the service to work?**

Help should not be allowed to be bookmarked as it is already there in menu.

**Comment by GeVic** [comment]
@divyanshub024 It would be better if you write below the issue report if you want to work on the same.

**Comment by hjoshi123** [comment]
@mhutti1 Can I be assigned to the bug? I would like to work on it

**Comment by hjoshi123** [comment]
@divyanshub024 the app crashes when I click on bookmark for help? Is that what you are talking here? Because I am working on that crash

**Comment by hjoshi123** [comment]
@divyanshub024 I fixed the crash. Can you tell me what exactly were u meaning when u posted the issue? Was it about the crash when you pressed on Bookmark?

**Comment by hjoshi123** [comment]
@divyanshub024 Should I create a PR for this?

**Comment by mhutti1** [comment]
Fixed by the new bookmark bar.
