### ISSUE TITLE
Bottom Toolbar darker shade

### ISSUE THREAD

**Issue by GeVic** [kiwix/kiwix-android#611]
## It is a:
- [ ] Bug Report 

- [x] Enhancement

### Description
The color of the bottom toolbar should be more darker according to me.
The present color: 
![1](https://user-images.githubusercontent.com/29516629/37209350-0770735a-23cb-11e8-98d6-028c3d3c290d.png)
One shade darker:
![3](https://user-images.githubusercontent.com/29516629/37209370-19b2e836-23cb-11e8-81cc-7b406aa6ba1a.png)
Two shades darker:
![2](https://user-images.githubusercontent.com/29516629/37209389-257207e2-23cb-11e8-9d6f-122ca8883579.png)

I think we should change the color to one shade darker. 
@mhutti1  should i ?

**Comment by mhutti1** [comment]
That does look better imo. Is there precedent in our styling for this? Is the colour already defined?

**Comment by GeVic** [comment]
@mhutti1 i didn't get your questions correctly but colour.xml file is defined in attributes where i changed the colour from.

**Comment by mhutti1** [comment]
As in is it a predefined colour?

**Comment by GeVic** [comment]
@mhutti1 yes

**Comment by GeVic** [comment]
@mhutti1 should i change the shade then? And which shade?

**Comment by GeVic** [comment]
@mhutti i think the last one would be good.

**Comment by mhutti1** [comment]
@GeVic open a PR for review

**Comment by mhutti1** [comment]
Redundant by #745
