### ISSUE TITLE
Language selection should be done on tapping the web imageview too

### ISSUE THREAD

**Issue by debasree88** [kiwix/kiwix-android#612]
The language choosing on tapping web imageview can not be done

###My  Environment
  * version of the software you use :2.2
  * device / operating system : Redmi note 4 /android nougat
 
   this is a feature request from the present version
 
  i feel that on tapping the web image view where users get the language lists for the 2nd time they should be able to modify their choice of language too except from settings.easy to use from user point of view.

**Comment by mhutti1** [comment]
Could you elaborate more please. I don't really understand what the "web imageview" is referring to.

**Comment by debasree88** [comment]
just mentioned the browser imageview on tapping which the language spinner comes

**Comment by mhutti1** [comment]
I am still not very clear. Language spinner?

**Comment by debasree88** [comment]
I just meant the drop down menu of the language lists.

**Comment by kelson42** [comment]
I do not understand either what goes wrong. Provide a step by step procedure of what you do. Explain clearly what you get and then why what you get is wrong.
