### ISSUE TITLE
Refactor: Convert ListView to RecyclerView in LibraryFragment

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#613]
#### Feature Description

As discussed, we should convert the ListView in LibraryFragment to a RecyclerView.

#### Parent issue
#547

**Comment by mahmoudhanoraa** [comment]
Can I work on this issue ? @srv-twry

**Comment by kelson42** [comment]
@mahmoudhanoraa looks like a pr is already ongoing...

**Comment by mahmoudhanoraa** [comment]
@kelson42  I did not notice. I will check the pull requests before asking next time. Thanks

**Comment by macgills** [comment]
Done in 2.5, closing
