### ISSUE TITLE
ZIM file transfer between two devices through the WIFI P2P Direct in-app feature

### ISSUE THREAD

**Issue by RishabhRawatAndroid** [kiwix/kiwix-android#616]
# ZIM file transfer between two devices through the WIFI P2P Direct in-app feature. 
 
## Feature Request
Transfer the ZIM file between two devices through the WIFI Direct without any need of internet. 

#### Feature Description
From **WIFI P2P Direct** the two devices are directly connected to each other without the need of any intermediate access point ( without the need of local router).So from this we can achieve the high data transfer speed.I think this in app feature will be helpful like if suppose userA has some ZIM file and userB has not any ZIM file and also userB has not an internet connection then from this feature both user can share the ZIM file.And the main usage of this feature is where Suppose a class students who have not enough money for internet or internet problem then the teacher can download the ZIM file and share the ZIM file to all students.

I have done almost 80% of work on this feature but I am facing one problem regarding this.The problem is during the transfer some data may be corrupted I am working on this issue.When i pull the requeat then i will describe all issue of this feature.And this will be my first contribution in GitHub.And this is my first issue so please ignore the English grammar mistake.
Thank You.

@mhutti1 please review this feature.      

**Transfer ZIM from sender**
![videotogif_2018 03 10_22 52 20 1](https://user-images.githubusercontent.com/26416942/37245071-c9e6c69e-24b8-11e8-99ac-690bbfa4b5b9.gif)

**Receiver receive the file.**
![videotogif_2018 03 10_23 02 59](https://user-images.githubusercontent.com/26416942/37245294-ef8e1f98-24bb-11e8-993d-21d5a646641b.gif)

See also #1136

**Comment by RajaVamsi11** [comment]
@RishabhRawatAndroid  Nice feature . @mhutti1  what do you say?

**Comment by srv-twry** [comment]
@RishabhRawatAndroid Nice feature ! Just a quick side note from my side.
Please always discuss the usefulness and the correct approach of adding any new feature before working on them. This would make sure, that your hard work never goes in vain.

**Comment by mhutti1** [comment]
This sounds like a good idea. If it is not too code intensive then It would be a good idea to add however when implementing these sort of features, one must always be careful not to implement large features that could be performed by a user installed app. I don't know how difficult this is/has been to implement so whether we decide to include it will depend on that.

**Comment by srv-twry** [comment]
> when implementing these sort of features, one must always be careful not to implement large features that could be performed by a user installed app.

There is a famous applications called ```Share It``` which does exactly that. It uses WIFI P2P to transfer files and application between phones. [Play-Store](https://play.google.com/store/apps/details?id=com.lenovo.anyshare.gps&hl=en)

**Comment by RishabhRawatAndroid** [comment]
@mhutti1 @RajaVamsi11 I think you all agree with this idea.Now I am working further to do this.When I complete this feature then I will immediately pull the request.

**Comment by kelson42** [comment]
@RishabhRawatAndroid We are super agree with the idea, but probably the implementation is not super easy to make it user friendly. Could you please upload a diagram which would explain the workflow between the two devices? To me it is not really clear from the the gifs you have uploaded.

**Comment by RishabhRawatAndroid** [comment]
@mhutti1 @RajaVamsi11 @kelson42 @srv-twry I just uploaded a youtube video for showing the app wifi p2p feature. https://www.youtube.com/watch?v=VlvmbrImH1I&feature=youtu.be . But till now the same problem(data corruption) are occurring so if you give the permission then I pull the request and resolve the further issue.
I want to tell one thing. In that app I am not updating the progress bar I just use the color scheme for knowing the status of an app like if the color is green that means data is fully transmitted or received.If color is red that means failed to transmit or received and when it blue that means data is transmitting or receiving.

**Comment by mhutti1** [comment]
This looks promising. If you open a PR it would be good to review. No promises yet though 👍

**Comment by kelson42** [comment]
@RishabhRawatAndroid Looks promising, keep going ahead.

**Comment by kelson42** [comment]
@RishabhRawatAndroid Looks promising, keep going ahead.

**Comment by GeVic** [comment]
@kelson42 @mhutti1 Why to load our app with extra code and increase the apk size? Instead we should use third-party apps like share-it etc. Wouldn't that would be a more optimized solution?

**Comment by GeVic** [comment]
@kelson42 Now a days everyone uses share-it, whats-app, also Gmail for sharing purposes. I am just saying that people are so used to these methods that they will probably won't have any problem using those for kiwix too.

**Comment by kelson42** [comment]
@GeVic Never heard about a user using that so far I can remember.

**Comment by GeVic** [comment]
@kelson42 Actually now a days whats-app is even more popular in sharing files but I am not sure on how big of files it can handle. Although share-it is pretty easy to use without and limits on files transfer.
Any suggestions again?

**Comment by RishabhRawatAndroid** [comment]
@kelson42 @GeVic @mhutti1  Never forget me I am working on this feature very long time.Nowadays I am working on this feature. 
@GeVic in some country peoples are not using the share-it app or any other third party application for sharing the data. And I always try to make a user-friendly kiwix app means any part of the application should not depend on the third party application.The main motive of this app is to provide the OFFLINE content reading and from the whats app sharing this can not be possible to share a very large content from whats app and for using the whats app we always need an internet connection. I know very well from this feature it may increase the apk size but I will reduce the size of apk using the proper proguard rule. 

@kelson42 please give the invitation to me for joining the **kiwix slack channel** my mail id is rishicentury@gmail.com.

**Comment by kelson42** [comment]
@RishabhRawatAndroid You should have got one.

**Comment by Xeddius** [comment]
I suggest implimenting the http server first as it can be merged with this feature and takes out two goals in one go. 

 [Kiwix-plug mode: Wifi hotspot + Kiwix HTTP server](https://github.com/kiwix/kiwix-android/issues/259)

**Comment by kelson42** [comment]
We need to make the kiwix-lib HTTP daemon ready first https://github.com/kiwix/kiwix-lib/issues/138

**Comment by samuk** [comment]
I also think this would be a great feature. I'd make it so it can share the kiwix.apk too, so users have everything they need, rather than assuming the second user already has Kiwix installed.

Two existing FOSS projects that use Wifi sharing are:

https://play.google.com/store/apps/details?id=de.fun2code.android.pawserver&hl=en
http://paw-android.fun2code.de/

And

https://play.google.com/store/apps/details?id=org.servalproject
https://github.com/servalproject/batphone

They may have some useful code?

**Comment by kelson42** [comment]
@Aditya-Sood @mhutti1 @macgills Should we not close that ticket, now that this feature has been implemented by @Aditya-Sood?

**Comment by macgills** [comment]
This is done by Aditya, closing
