### ISSUE TITLE
Control read aloud from notification

### ISSUE THREAD

**Issue by divyanshub024** [kiwix/kiwix-android#621]
#### Feature Description
Create a notification for controlling the read-aloud feature like play, pause and stop.

**Comment by divyanshub024** [comment]
@mhutti1 if you can assign it to me I can start working on it.

**Comment by prajurock** [comment]
@divyanshub024 Are you working on this issue.@mhutti1 Can I start working on this.

**Comment by mhutti1** [comment]
@prajurock Sure if you @divyanshub024 is not anymore

**Comment by divyanshub024** [comment]
@prajurock You can work on it.

**Comment by prajurock** [comment]
Thanks @divyanshub024 I will work on it

**Comment by kelson42** [comment]
@MohitMaliDeveloper What do you think about the feasability of such a feature request? Would that be possible to implement in a clean manner? Would that be complicated?

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliDeveloper What do you think about the feasability of such a feature request? Would that be possible to implement in a clean manner? Would that be complicated?

@kelson42 Its seems feasible for me, I will check it and update on this later on.
