### ISSUE TITLE
[Bug] Search function with widget do not work properly in specific case.

### ISSUE THREAD

**Issue by JunsuLime** [kiwix/kiwix-android#625]
### Are you ready to report?
    Yes 👍  

### Environment
  * version of the software you use : version name 2.3 (2018-03-12 master branch)
  * device / operating system : Samsung Galaxy S8, Huawei Honor A6
  
### The Bug:

  ![bug_report](https://user-images.githubusercontent.com/17852124/37279510-5d63770c-262e-11e8-8048-5cbfeaae2e38.gif)

In specific case when I use widget search, It does not go to search screen, goes to latest wiki page.

#### Steps to reproduce:

  1. Click widget's "search kiwix" button
  2. Then search screen will be appear. Press back press button to go to latest wiki page
  3. In latest wiki page, Press home button, go to home.
  4. At home, click widget's "search kiwix" button again.
  5. We'll see latest wiki page, not search screen.

If It work properly, at step 5 we can see search screen. But this case, It does not appear.

**I would like to work this issue.**

**Comment by sakchhams** [comment]
@mhutti1 I think it is a good idea to hide the FIND IN PAGE button when a search is triggered this way. It seems unnatural and doesn't make any sense there. What do you think?

**Comment by prajurock** [comment]
@soloturn @mhutti1 can i work on this.

**Comment by abdulwd** [comment]
@prajurock There is a PR already opened for this issue. Can you try rebasing the same?

**Comment by prajurock** [comment]
ok
@abdulwd but  `unknown repository` is  showing in his branch.
I dont know how to do that please HELP

**Comment by abdulwd** [comment]
You can open a new PR then.

**Comment by Afleh** [comment]
@abdulwd  can i work on this?

**Comment by abdulwd** [comment]
@Afleh A pull request is already there for this issue.

**Comment by kelson42** [comment]
@abdulwd @macgills @JunsuLime Might that be that this bug has been fixed and we have forgotten to close it?

**Comment by macgills** [comment]
I would say it could still be bugged
