### ISSUE TITLE
Improve Travis Cache speed

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#627]
### Environment
 Travis Build
  
### The Bug:

All builds force a recache. We should limit this so that builds are quicker.

#### Steps to reproduce:

  1. Run a travis build on a PR
  2. It passes but detects a cache change

  
In 99% of cases there should be no need to update the cache.

**Comment by GeVic** [comment]
@mhutti1 i can work on this if you can guide me. Can i ?

**Comment by mhutti1** [comment]
@GeVic once you accept the email invite I can assign you. Sure go ahead till then. Open a pr for a random change and see that travis recaches. I think we probably need to exclude some files that we are currently caching so that it doesn't keep recaching them.

**Comment by kelson42** [comment]
@GeVic I have assinged it to you... but is that not more a ticket for the "kiwix-build" repo?

**Comment by mhutti1** [comment]
No this is for improving kiwix-android build speed.

**Comment by GeVic** [comment]
@kelson42 first i had the same thought but no it's not

**Comment by GeVic** [comment]
Actually i am working on my gsoc proposal that's why resolving this issue is talking some time but I'll make sure to resolve it asap

**Comment by mhutti1** [comment]
Bumping this. Disabled cache in https://github.com/kiwix/kiwix-android/pull/1024 as it was more performant without.

**Comment by kelson42** [comment]
@mhutti1 So this ticket is now invalid?

**Comment by mhutti1** [comment]
I mean we could still improve travis' speed but I think that would probably be a separate issue.

**Comment by kelson42** [comment]
@mhutti1 I'm not sure about all of this, why the way we used the cache somehow slow down things. Anyway if you think you have an idea how we could speed up the CI (with the cache or not), please open a dedicated ticket. This is an important topic.

**Comment by mhutti1** [comment]
I don't have any specific ideas at the moment.
