### ISSUE TITLE
UI bug in "Languages" dialog box in "Settings"

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#631]
### Environment
  * version of the software you use : Version 2.3 Build 55 (Latest Commit)
  * device / operating system : Samsung Galaxy S6 Android 7.0
  
### The Bug:

The Header, as well as the OK button is not displayed in The Language dialog box in settings (in night mode)
![screenshot_20180313-112031](https://user-images.githubusercontent.com/32238400/37357340-68f2a0b2-26a5-11e8-884d-86209235e26b.png)

if night mode is not selected, then the dialog box is like this:
![screenshot_20180313-223329](https://user-images.githubusercontent.com/32238400/37357432-ab9c4fa8-26a5-11e8-87c2-77e290e753ad.png)

#### expected behaviour:

most probably, the bug is because the color and the header as well as the OK button are white and they are hidden in the white background.

Ideally, in night mode, White text should be displayed in a grey dialog box, such that the color scheme matches that of the night mode

something like this is required:
![screenshot_20180313-224558](https://user-images.githubusercontent.com/32238400/37358148-93e9d89c-26a7-11e8-9c7b-c907da8bb3dc.png)

**Comment by GeVic** [comment]
@siddharth2010 Can i go ahead with this issue ? Can you assign it to me ?

**Comment by siddharth2010** [comment]
Sure. Go ahead!

**Comment by GeVic** [comment]
@sidharth2010 can you help me here? Actually their is no custom dialogbox theme here it's the Android list preference which has its own dialogfragment.
I researched but didn't found any way to do this other that changing Android file itself or making new custom dialog.

**Comment by mhutti1** [comment]
Redundant by #774
