### ISSUE TITLE
The list of contents available for download do not have a line divider between each item.

### ISSUE THREAD

**Issue by kslohith** [kiwix/kiwix-android#632]
### The Bug:

  * The download option for the app displays a list of items that can be downloaded, but each item does not have a line divider separating it from the others.

![screenshot_2018-03-14-01-10-18](https://user-images.githubusercontent.com/32676813/37366472-89f9f554-2726-11e8-8d4a-23339dbb17ce.jpg)

  
    *All items should have a line divider between them for better viewing experience.

**Comment by mhutti1** [comment]
Won't fix. This is a design feature. If you would like to propose an alternate design please create a new issue with a mockup.
