### ISSUE TITLE
Unable to open certain articles of wikipedia_en_medicine_nodet_2018-03.zim

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#633]
### Environment
  * version of the software you use : Kiwix last nightly
  * device / operating system :  Samsung Galaxy Tab
  
### The Bug:

1 - download https://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_nodet_2018-03.zim
2 - open the welcome page
3 - Click on the first link "Cancer care"
4 - A blank page is displayed 
  
The article "Book:Cancer" should be displayed, if i search for "book:cancer" in the search box, I find it and it is displayed properly.

**Comment by Rahul5758** [comment]
@kelson42  Can I work on this issue? Please assign this to me.

**Comment by kelson42** [comment]
@Rahul5758 Yes :)

**Comment by Rahul5758** [comment]
@kelson42 Please share your operating system complete details and also provide the apk of kiwix you are using.

**Comment by kelson42** [comment]
https://download.kiwix.org/nightly/2018-03-15/kiwix-android_arm-debug.apk with android 6.0.1

**Comment by hjoshi123** [comment]
@kelson42 Can i work on this issue? Can you assign it to me?

**Comment by kelson42** [comment]
@hjoshi123 Yes

**Comment by Rahul5758** [comment]
I have already asked to be assigned this issue @kelson42  5 days ago. Kindly see into this.

**Comment by kelson42** [comment]
@hjoshi123 yes, sorry @Rahul5758 is already working on this. My bad.

**Comment by Rahul5758** [comment]
Can you assign this issue me now so that it is not reassigned again @kelson42 ?

**Comment by kelson42** [comment]
@Rahul5758 I have sent you an invitation, you have to accept it.

**Comment by kelson42** [comment]
We should probably call `urlDecode(path, true)` here https://github.com/kiwix/kiwix-lib/blob/master/src/reader.cpp#L467. @mhutti1 Can you try it please?
