### ISSUE TITLE
Language in dialog checked even when it is not selected in Library fragment

### ISSUE THREAD

**Issue by harshvardhan-takawale** [kiwix/kiwix-android#634]
# For a Bug Report:

### Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - Ensure you have tested with the last (dev) version of the software.  (If not, and if possible, run your test again with the most recent version available.)

### Environment
  * version of the software you use: 2.3 build: 55, Build variant: kiwixDebug 
  * device / operating system: Moto G4 Plus
  
#### Steps to reproduce:

  1. Open Library fragment and select some language from the dialog
  2. Press Back instead of 'ok'
  3. The filter is not applied. Now open the language select dialog again. The language is still selected.
  ...
  
  * What should be the behavior from your point of view? How do you expect the service to work?
The language should either be deselected automatically or the filter should be automatically be applied instead of it being applied after pressing back.

**Comment by GeVic** [comment]
@harshvardhan-takawale @mhutti1 why we need multiple checkbox style here ?
And instead of `ok` button what we should do is as soon as the language selected the dialog should perform the function qnd disappear. Also we should use checkbox style as we used in settings.

**Comment by harshvardhan-takawale** [comment]
@GeVic  I guess you are a bit confused about the use of this dialogbox. It is kind of a filter, so you can select multiple languages and list out the files in those languages. Therefore a checkbox is required and radio buttons won't do.

**Comment by GeVic** [comment]
@harshvardhan-takawale oh yes you're right i don't gave it a thought before writing.
Thanks by the way

**Comment by bhardwajaditya** [comment]
Can I try this issue?

**Comment by harshvardhan-takawale** [comment]
@bhardwajaditya Actually I have started working on it.

**Comment by mhutti1** [comment]
Redundant by new language activity.
