### ISSUE TITLE
Test Wikimed app on Xiaomi Redmi Note 4

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#637]
From the Google Play feedback analysis it seems that a lot of people have difficulties to install Wikimed https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikimed on a Xiaomi Redmi Note 4. As we do not have such a device my request would be to someone having one, please give a try and let us know if the install process (and the rest) works properly.

**Comment by kelson42** [comment]
@srv-twry would you be able to do that? It seems in general Kiwix has a lot of problem with this device - and maybe Xiaomi devices in general.

**Comment by srv-twry** [comment]
Yes, i don't have it though but i can arrange it and give feedback in a day or two.

**Comment by Rahul5758** [comment]
@kelson42 @srv-twry I have a Redmi note 3, Redmi 3s and Redmi 4 device. I can see into this.

**Comment by srv-twry** [comment]
@Rahul5758 Yes, please go ahead. Infact this issue can be tackled by more than one developers.

**Comment by kelson42** [comment]
@Rahul5758 @srv-twry Thank you to both of you, yes please check on all these devices. I'm quite confident that something goes really wrong with these these devices.

**Comment by Rahul5758** [comment]
@kelson42 @srv-twry I downloaded and installed the app on Redmi note 3, Redmi 4 and Redmi 2. The app installed correctly and also works properly. I will give the feedback on rest of the devices also soon.

**Comment by kelson42** [comment]
@Rahul5758 Thank you for this feedback. Yes please test on the rest of the device, really important is to test with Xiaomi Redmi Note 4.

**Comment by Rahul5758** [comment]
@kelson42 The app also installed and ran correctly on Redmi Note 4.

**Comment by kelson42** [comment]
Thank you all for your testing, the result is a bit puzzling... but it's an important info!

**Comment by srv-twry** [comment]
@kelson42 I also tested it and it works fine for me too.

**Comment by kelson42** [comment]
@srv-twry Thank you very much again for "closing that door".
