### ISSUE TITLE
Night Mode Accessibility

### ISSUE THREAD

**Issue by GeVic** [kiwix/kiwix-android#639]
# For a Bug Report:
- [x] Feature
- [ ] Bug

# For a Feature Request:

## Feature Description
Night mode is always frequently used so it accessibility does affect the UI design of the application. 
Providing button option Menu bar/ Bottom toolbar and also in the settings fragment will make it easier and enhance the UI.

Something like the image referred below
![night](https://user-images.githubusercontent.com/29516629/37555335-d1fe1ece-2a0b-11e8-9925-973ccdb4e0e6.png)

@mhutti1 Should i start working on it.

**Comment by kelson42** [comment]
I'm quite against having it in the Kiwix menu/bottom bar. This is not used often enough to justify this. That said the I do not understand what the screenshot is about - it's not Kiwix, so not sure I fully understand the feature request.

**Comment by GeVic** [comment]
@kelson42 doesn't have to be bottom bar but how about  giving it on side menu drawer.
But since you are saying not used much then this feature turns out to be null/void
