### ISSUE TITLE
cant download zim files

### ISSUE THREAD

**Issue by amirh123123** [kiwix/kiwix-android#643]
hi my phone is grand 2 but cant download zim files from library

**Comment by kelson42** [comment]
What happens exactly? Are you connected through Wifi? Is that a new problem?

**Comment by amirh123123** [comment]
hi i change my phone language to en us and zim files is downloaded

**Comment by kelson42** [comment]
@amirh123123 What was the original language? If you change back, does it fail again?

**Comment by kelson42** [comment]
No feedback here, but all of this should work fine with 2.5 (to be release soon). Please reopen if not.
