### ISSUE TITLE
Unable to run app

### ISSUE THREAD

**Issue by Rakshit1411** [kiwix/kiwix-android#647]
### Environment
  * version of the software you use : _android studio 3.0.1____
  * device / operating system : _Emulator Nexus_5x_API_26_2____
  
### The Bug:
I am unable to run the app using android studio. The app runs fine when we download from play store but not by compiling the code.
I have been working on this issue from the last 2 days but I am unable to figure the main problem.

Error : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 6475 (ixcustomexample)

**Comment by RohanBh** [comment]
You need to change your build variant to kiwxDebug as written in the [README](https://github.com/kiwix/kiwix-android/blob/master/README.md).
