### ISSUE TITLE
Proposal: Use Kotlin as the primary development language for Kiwix

### ISSUE THREAD

**Issue by RohanBh** [kiwix/kiwix-android#648]
#### Feature Description
Last year Koltin became an official language for Android Development. Since then, it has received enormous love from the community. A few advantages of using Kotlin over Java are:
1. Kotlin is a type and null-safe language.
2. Kotlin is concise and fun to write. It makes Android Development a lot faster.
3. It is interoperable with Java. We can call Kotlin code from Java code and vice-versa. 
4. Companies like Slack, Pinterest are already using it.
5. It is easy to learn. You can literally start writing Kotlin code after 2-3 days of [practice](https://kotlinlang.org/docs/tutorials/koans.html).
6. Google is also providing their support to Kotlin. A few months before, Google marked many function parameters with `@NonNull` annotation ([read more](https://proandroiddev.com/android-kotlin-and-api-27-2e6f3f893c2)). This was done to help Kotlin figure out the type of the parameters at compile time. Also, In February, Google released [android-ktx](https://github.com/android/android-ktx) library which contains very useful extension functions for commonly used android classes.
7. The [Kotlin Android Extensions](https://kotlinlang.org/docs/tutorials/android-plugin.html) plugin allows you to [replace butterknife](https://stackoverflow.com/a/46482618/7263373) library with its view binding abilities without annotating exposed fields!
8. Kotlin includes a lot of extension functions for the Collection class which lets you operate on these easily. For e.g., Kotlin Collections contains methods like `forEach()`, `filter()`, `findFirst()`, etc. which are only available for higher Android API's when using Java 8. 
The list doesn't end here. Kotlin's interoperability with Java lets you convert existing Java code one file at a time. 
@mhutti1 @kelson42 @rashiq Please consider this proposal.

**Comment by rashiq** [comment]
I like kotlin, but I think since there is a lot going on in the org (new contributors coming in, lots of new PRs), it's really hard to just start converting files. I'd like the code base to eventually be kotlin, but I think we should defer that for now. Just my two cents.

**Comment by RohanBh** [comment]
@rashiq I am not in favor conversion of Java code to Kotlin using Java to kotlin conversion feature in Android Studio as the Kotlin code isn't efficient that way. The process has to start sometime so I was planning to do it bit by bit. For e.g., we can start by converting model classes or interfaces to Kotlin as they aren't structurally much different from Java's.

**Comment by rashiq** [comment]
Yeah I get what you mean - it is interoperable after all. I just fear that even tho it is pretty easy to learn, it might turn away a lot of new comers and first-time-contributors. @mhutti1 what do you think?

**Comment by sakchhams** [comment]
@RohanBh how about using kotlin for new code while keeping Java code the same?

**Comment by RohanBh** [comment]
@rashiq Then we can wait. I just wanted to put forth the idea of using Kotlin in the project.
@sakchhams It doesn't solve @rashiq's concern. First-time contributors might leave seeing Kotlin code.

**Comment by kelson42** [comment]
Few other concerns:
* How many people are able to deal with Kotlin (in comparison to Java)?
* How many hours of work would be needed to move things *properly* from Java?

**Comment by abdulwd** [comment]
@RohanBh I like Kotlin and have a year experience in it but everything cannot be changed gradually. For instance, the last time I checked _annotationProcessor_ and _kapt_ were not compatible so the code using annotation processing has to be updated otherwise there is no source code generation.
If maintainers approve this issue I can provide a helping hand. :stuck_out_tongue:

**Comment by mhutti1** [comment]
I also agree on waiting. Kotlin in Android is still very new. I would suggest waiting a bit and seeing how support for it pans out.

**Comment by RohanBh** [comment]
@abdulwd This isn't true. If you read [kapt's doc](https://kotlinlang.org/docs/reference/kapt.html), you will find -
> If you previously used the Android support for annotation processors, replace usages of the annotationProcessor configuration with kapt. If your project contains Java classes, kapt will also take care of them.

**Comment by sakchhams** [comment]
@RohanBh Java and Kotlin both compile to the same intermediate code. So doesn't that make Kotlin sheer syntactic sugar? The shared intermediate should mean they both have the same feature set at the lower level. Am I missing something?

**Comment by RohanBh** [comment]
@mhutti1 Kotlin isn't "very new" in Android. It has been under development for many years. It's just Android made Kotlin a first-class supported language last year. There are so many articles flooding related to Kotlin. These are all by happy developers who shifted to Kotlin.
[Jake Wharton](https://github.com/JakeWharton) who worked for square earlier (now a Google Engineer) [loves Kotlin](https://www.youtube.com/watch?v=c6mhYGCKeaI) and has [given several talks](https://www.youtube.com/results?search_query=jake+wharton+kotlin) as to why is Kotlin better. He is even very much active on [Kotlin's official Slack](http://slack.kotlinlang.org/).
And big companies like Slack and Pinterest have shifted their entire source code to Kotlin.
In the end, it's your decision as you're the ones who have to live with this longer than us. I just wanted to tell how awesome Kotlin is.

**Comment by RohanBh** [comment]
Yes, It is true that Kotlin compiles to Java bytecode. It even compiles to JavaScript's source code. Yes, it won't change the size of final Dalvik Bytecode which is compressed and put in the apk. But at the higher level, you'll have to read/write lesser code. Thus it is easier to debug. 
I wasn't exactly sure where you were going with your question. Hope this answers it.

**Comment by abdulwd** [comment]
@RohanBh You didn't get my point. We will need to make changes in the tests simultaneously. Well, that won't be much of an issue once we start working everything will get sorted. ;)

**Comment by RohanBh** [comment]
@abdulwd What changes will we have to make?

**Comment by abdulwd** [comment]
@RohanBh Sorry for the late reply. I was quite busy these days. 

For instance, suppose we have a class called **NetworkUtils** where we have all the helper methods which are static. Consider one method `isNetworkAvailable(Context)`, presently we call this method using `NetworkUtils.isNetworkAvailable(Context)` but when we convert this class to _Kotlin_ we can have package level functions declared directly in a file called **NetworkUtils.kt**. Then we have to call the function `isNetworkAvailable(Context)` using `NetworkUtilsKt.isNetworkAvailable(Context)`. We have to add _Kt_. So there are other cases like this.

We can have more discussion over this once the maintainers approve it.

**Comment by RohanBh** [comment]
I don't think this is a big problem. We can change this default name using `@JvmName` annotation so that Java code can still use `NetworkUtils.isNetworkAvailable(Context)`.

**Comment by soloturn** [comment]
@RohanBh , @abdulwd you'd be interested in migrating apps/build.gradle to kotlin, #947 ?

**Comment by haroldadmin** [comment]
Kotlin has been proven to be a highly loved language. In the [StackOverflow 2018 survey](https://insights.stackoverflow.com/survey/2018/) Kotlin was voted as the second most loved language of all. I can attest to that fact, I love Kotlin ❤️ 

There are great guides to learn Kotlin for Java developers, such as this one: [Guide to Kotlin](https://github.com/Zhuinden/guide-to-kotlin)

I would like to start working on this issue, if it is available? We can start the conversion slowly, package by package.

**Comment by mhutti1** [comment]
I think that we should wait until 3.0 before thinking about doing this. It will introduce large changes to our codebase that could make tracking down bugs challenging.

**Comment by kelson42** [comment]
@mhutti1 yes, I strongly opposed any change on this front without educated argument. We could have this discussion this summer in person.

**Comment by kelson42** [comment]
Additonal info from @macgills 

> Kotlin is a new JVM language with huge potential and support in the android community specifically as Google have declared it a first class language that they will support. This lead to the creation of the Kotlin Foundation, a joint venture between Jetbrains and Google.
> Feature wise it is much richer than java, native optionals, compile time null checking, functional, data classes, algebraic datatypes, extension functions and all of it is completely interoperable with java. Projects written in Kotlin have been shown to be 40% smaller than their java counterparts.
> The one downside is that it is a different language with different idioms, though still maintaining a lot of similarity to java. This would be most relevant if you had a large java team and the switch would cause confusion across a large number of people and would be a significant penalty to the business.
> 
> https://medium.com/@magnus.chatt/why-you-should-totally-switch-to-kotlin-c7bbde9e10d5
>
