### ISSUE TITLE
List of contents to be downloaded vanishes on rotating the screen.

### ISSUE THREAD

**Issue by kslohith** [kiwix/kiwix-android#653]
### Environment
  * version of the software you use :  2.2
  * device / operating system :  android 6.0.1
  
### The Bug:
On rotating the screen after the contents are loaded in the online section , the list vanishes and we have to download content list again.

#### Steps to reproduce:

  1.  Go to the online section of get content. 
  2.  Click proceed.
  3.  After the list is populated , rotate your mobile and the downloaded list vanishes.
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
  The Downloaded list should not vanish when we rotate the screen.

### Other Comments:

 
  * I think we can solve it using savedInstanceState method.
  
  

![ezgif com-optimize](https://user-images.githubusercontent.com/32676813/37793962-1a6c1e12-2e36-11e8-8ea4-5b382b3c106f.gif)

**Comment by kslohith** [comment]
Can i work on this?

**Comment by brijeshshah13** [comment]
@hjoshi123 As you can notice, @kslohith has requested to work on this issue. Please allow him to try to resolve it.
@kslohith Go ahead and fix it.

**Comment by GeVic** [comment]
@brijeshshah13 I think it's been already worked on. I reported this issue a way back and someone said he's is already working. So please check if there is any on going issue with this.

**Comment by brijeshshah13** [comment]
@GeVic Thank you for pointing out. Duplicate #559.
