### ISSUE TITLE
Chore: Create separate issues template 

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#654]
#### Feature Description

With the new update to Github, it supports adding multiple issues templates according to the context. I propose to use it now and create separate issue templates for 

- [ ] bug
- [ ] feature
- [ ] chore/maintainence
- [ ] documentation

@rashiq @mhutti1 Your views please ?

**Comment by rashiq** [comment]
I didn't know that was possible. Would be really cool! can you link to the blog that introduces this feature?

**Comment by srv-twry** [comment]
Hi @rashiq , It's a new feature. You can find more information [here](https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/)
