### ISSUE TITLE
[Bug] Search function does not work perfectly

### ISSUE THREAD

**Issue by daroodar** [kiwix/kiwix-android#659]
# Search function does not work perfectly

# For a Bug Report:

### Are you ready to report?
   - Yes

### Environment
  * version of the software you use:  Latest master
  * device / operating system : Infinix X5010 Android 7.0
  
### The Bug:

  * If the search bar is tapped on, the keypad appears. If you tap anywhere outside of keypad or search bar, keypad should minimize and other taps on the screen should be considered after minimizing of the keypad.
 * This does not happen in Kiwix app. The keypad does not minimize and other taps are acted upon without minimizing of the keypad

  ![screenshot_20180323-195112](https://user-images.githubusercontent.com/11704509/37836848-6bfede3c-2ed5-11e8-86a6-4bf5dabe95c5.png)

 

#### Steps to reproduce:

  1. Open the app
  2. Tap on search
  3. Tap anywhere else on screen
  
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
The keypad should minimize on first tap and afterwards, other taps should be considered

**Comment by hjoshi123** [comment]
@daroodar The bug is that keyboard doesn't disappear right or is it about the search functionality?

**Comment by daroodar** [comment]
@hjoshi123 the bug is that the keyboard does not disappear

**Comment by hjoshi123** [comment]
Cool

**Comment by srv-twry** [comment]
@hjoshi123 @daroodar I think we have a lot of issues already open on the search problem. This is a feature which has a lot of problems right now. I would recommend going through the older issues to see if this issue has already been opened. If yes, then close this otherwise keep going!

**Comment by daroodar** [comment]
@hjoshi123 @srv-twry  Yes I think I have read the documentation again. It's correct. I will close the issue. Thanks!
