### ISSUE TITLE
Poor search feature on Android

### ISSUE THREAD

**Issue by khanhhung2512** [kiwix/kiwix-android#66]
I just performed a search on Kiwix for Android, Wikipedia database, non-indexed with keyword "eMMC" and it yielded no result. I had to search for "Multimedia Card" instead. However, on Windows, the search for "eMMC" yielded the right result, even though the database isn't indexed.

**Comment by kelson42** [comment]
This has been fixed with libzim 6.0.0 and Kiwix-Android 3.0, but a new ZIM file of WPEN will be needed.
