### ISSUE TITLE
Refactor: Convert File scan thread into RX operations

### ISSUE THREAD

**Issue by srv-twry** [kiwix/kiwix-android#661]
#### Feature Description

Right now we start separate threads in the ```scan``` method of the ```FileSearch``` class in order to do custom file search and media file search [here](https://github.com/kiwix/kiwix-android/blob/108af1096b9316f9dd00ecee912aff4c5cfc4942/app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileSearch.java#L62-L73).
These should be converted to RX Observable.

Parent issue: #176

**Comment by kelson42** [comment]
@macgills What is your opinion on this as you have already revamped that part?
