### ISSUE TITLE
Android Architecture Components

### ISSUE THREAD

**Issue by hjoshi123** [kiwix/kiwix-android#662]
#### Feature Description

Google introduced Architecture Components in I/O 2017 to handle lifecycle events gracefully among many other things. More and more orgs are moving to MVVM and arch components. We could handle data changes using LiveData and since we are already using RxJava we could easily integrate with it. What do you guys think? @kelson42 @rashiq

**Comment by srv-twry** [comment]
I also considered migrating to Architecture components but we have to consider a few things before we go ahead with this. 

**PROS**

1. It has official support
2. We can utilise the components specially LiveData ( I don't think we need to migrate to ROOM as SQUI db is working pretty well. 

**CONS**

Our project follow MVP architecture which is very different from the MVVM architecture and is extremely popular as well. I don't see any reason why we will put so much effort into moving from one architecture to another. The only time we should move from one architecture to another is when the current one hinders the development process which MVP doesn't by any means.

Ping @mhutti1

**Comment by RohanBh** [comment]
I feel that MVVM is a cleaner architecture than MVP. Using Architecture Components would be a great advantage. Although, Kiwix is based on MVP and one of the GSoC tasks involves writing unit tests for the presenter logic. I am not sure, but shifting from MVP to MVVM should take a lot of time (given the amount of code) hence hindering that task.

**Comment by hjoshi123** [comment]
I love LiveData very much. We could use the benefits of it to manage configuration changes and all. Especially because we use RxJava architecture components will easily merge.

**Comment by srv-twry** [comment]
> Especially because we use RxJava architecture components will easily merge.

Actually it won't be that easy. 
To use LiveData we will have to completely change the way the data flow happens in the application. MVP and MVVM are very different. One key difference is that the "presenter" holds a reference to "view" in MVP but the "ViewModel" doesn't hold any reference to the "view" in MVVM.

**Comment by hjoshi123** [comment]
@srv-twry True that. But we won't need to worry about configuration changes. Plus as you said before its officially supported. I am not proposing we do it now. We can implement it slowly. We can also do this as a GSoC task. What do you think?

**Comment by GeVic** [comment]
@hjoshi123 MVVP is more of a of a reactive programming and also produces less code to work with. So,  moving to MVVP is certainly a good choice keeping aside some of the cons that it brings with it. Although the amount of time it requires is not small But doing it as GSoC task might just work.But if we prioritize the GSoC ideas lists with this, then I think this should wait.
@mhutti1 @kelson42 Your views?

**Comment by kelson42** [comment]
This definitly a question for @mhutti1 and @rashiq

**Comment by mhutti1** [comment]
I don't have a huge amount of experience with this. I think unless there are major benefits to a new system we should stick with what we have.

**Comment by hjoshi123** [comment]
@mhutti1 I think it has great advantages for us. We don't to worry about Lifecycle events or data changes etc. I think we should start working on this.

**Comment by rashiq** [comment]
I'll take closer look in the coming days and will decide on it

**Comment by kelson42** [comment]
@rashiq @mhutti1 @macgills Do we have had enough time to give a definitive answer on this question?

**Comment by macgills** [comment]
We did it 🎊
