### ISSUE TITLE
Unable to build properly (in CI too) since Leakcanary dependence has been added to project

### ISSUE THREAD

**Issue by sam1096** [kiwix/kiwix-android#664]
#[Bug]While building kiwix-android app in android studio found error:package com.squareup.leakcanary does not exist

### Environment
  * version  : android studio
  * device / operating system : ubuntu 16.04
  
### The Bug:While running the app of kiwix-android on emulator there is an error occurred saying package com.squareup.leakcanary does not exist.Then I tried some of the solutions given on stackoverflow and github and have done some changes in build.gradle but still issue is not resolved.
I have added debugcompile and releasecompile in dependecies of build.gradle,but after running still I got an error.It looks like this:
![screenshot from 2018-03-24 03-28-57](https://user-images.githubusercontent.com/16611326/37867240-2f7c79ac-2f8d-11e8-93a5-491e232d424b.png)

#### Steps to reproduce:

  1. Build kiwix-android app in android studio from github.
  2. Run kiwix app on emulator.

  I want to run this app on android studio to have a look on its working.

**Comment by kelson42** [comment]
This seems to be a problem introduced by #364. Please @srv-twry and @rashiq, try to close that problem ASAP.

**Comment by srv-twry** [comment]
@sam1096 
1. You're adding the dependencies in the wrong ```build.gradle``` file.
2. You don't need to add any dependencies in the first place.

@kelson42 Yes, it has been introduced due to it but it works absolutely fine on my local machine. I think we need others to fetch the latest code and try to run it. @brijeshshah13 @hjoshi123 @siddharth2010 @RohanBh Can you guys check and confirm the issue ?

A stackoverflow discussion [here](https://stackoverflow.com/a/30166591/6748052) suggests cleaning and rebuilding the project.

**Comment by hjoshi123** [comment]
@srv-twry @sam1096 Its working fine for me. No issues in building

**Comment by srv-twry** [comment]
@sam1096 
Another possible case : Are you by any chance building the application in offline mode. I would suggest taking a look at your settings and disabling the offline mode in case it is enabled. 
You can find the settings in 
File -> Settings -> Build,Execution,Deployment -> Build Tools' -> 'Gradle'
Uncheck "offline work".

**Comment by brijeshshah13** [comment]
@srv-twry Works good for me as well.
By the way, did anyone notice that @sam1096 (even though it wasn't required to add the dependencies) added them in the `dependencies { }` present in the `buildscript { }`, and not in the root `dependencies { }` 😄 That's the reason of the error. Please close this issue if there are not other developments.

**Comment by GeVic** [comment]
@srv-twry @hjoshi123 Most probably its because of the dependencies that you added. As @srv-twry already stated its not required. But sometimes doing instant run also triggers the leakcanary to report memory leaks.

**Comment by sam1096** [comment]
I did all those things you told @srv-twry  and I removed those lines from dependencies,still I'm getting previous errors which I was getting when I run app for first time.For only those errors I added dependencies later.Could you please help me in fixing this.I took another screen shot after removing dependencies and "off line work" is also unchecked.
![firstlook](https://user-images.githubusercontent.com/16611326/37871200-576d3cfc-2f9d-11e8-88af-e89693e15f15.png)

**Comment by brijeshshah13** [comment]
@sam1096 It is because you are building the wrong Build Variant of the app. First you need to change the build variant to `kiwixDebug`. LeakCanary has been added in that build variant only.

**Comment by sam1096** [comment]
Changed build variant to kiwixDebug.It says about Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForKiwixDebug'.
> java.lang.IllegalArgumentException (no error message)
![bbb](https://user-images.githubusercontent.com/16611326/37873051-4cc501dc-2fc9-11e8-9478-eb7312e9a612.png)

**Comment by hjoshi123** [comment]
@sam1096 Have you enabled multidexing ?

**Comment by sam1096** [comment]
yes.
![multidex](https://user-images.githubusercontent.com/16611326/37873715-08985456-2fd7-11e8-8652-960adbc0d059.png)

**Comment by brijeshshah13** [comment]
@sam1096 I see that you have made some changes in the `app` level `build.gradle` file and `KiwixApplication.java` file as well. Can you please try stashing them and taking a fresh pull from the remote branch. After that, do `Clean Project` followed by the building the app again. Please post here if the issue persists.

**Comment by kelson42** [comment]
@rashiq @srv-twry Nightlies do not build anymore since this merge. See https://download.kiwix.org/nightly/.

**Comment by srv-twry** [comment]
```
BUILD SUCCESSFUL in 3m 49s
83 actionable tasks: 83 executed
Exception in thread "Thread-15" java.lang.NoClassDefFoundError: com/android/utils/PathUtils$1
	at com.android.utils.PathUtils.deleteIfExists(PathUtils.java:47)
	at com.android.utils.PathUtils.lambda$addRemovePathHook$0(PathUtils.java:125)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.android.utils.PathUtils$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
Running tests
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Waiting for results
Traceback (most recent call last):
  File "./testdroid.py", line 28, in <module>
    raise AssertionError("Success ratio only: {}".format(ratio))
AssertionError: Success ratio only: 0.909091
```

@kelson42 Are you sure this has been happening after the dependencies were introduced ? 
Isn't this related to #518 . Looks very similar.

**Comment by kelson42** [comment]
@srv-twry #518 is not blocking and does not make the CI fails. It exists since longer, but the CI has started to fail just after the last commit.

**Comment by hjoshi123** [comment]
@kelson42 Yeah it has started recently. My PR's got built successfully but @brijeshshah13 posted a PR today whose build failed.

**Comment by brijeshshah13** [comment]
@kelson42 @srv-twry After cloning the `master` 3 times for verifying this issue, I report that the error does occur when I build the default build variant. However, after I change to `kiwixDebug`, the build passes successfully and installs the app too.
