### ISSUE TITLE
Closing The ZIM file

### ISSUE THREAD

**Issue by Achintya999** [kiwix/kiwix-android#669]
Bug Report

Are you ready to report?

-Yes

Environment

version of the software you use: Latest master
device / operating system: One Plus 5/ Android 8.0

The Bug:
When we want to close any ZIM files from the Navbar and we click the close button. Instead of closing the zim file we are directed back onto the same page and we can't go to the home page. So i suggest on closing the ZIM we must be directed back to the home page.

**Comment by kelson42** [comment]
@Achintya999 What does "close" a ZIM file mean? I do not understand?

**Comment by Achintya999** [comment]
@kelson42 Like we download any ZIM file and when we open it it opens and at the time of closing there is no option of closing it, like in navbar there is a button infront of it but on pressing x it says tab closed and nothing happens, so particulary there is no way to get out from there as by clicking the "x" button and this is of no use so i consider it as a bug in the app.

**Comment by mhutti1** [comment]
Closing this as it is a feature and this behaviour will not make sense with multizim.
