### ISSUE TITLE
Add Adaptive Icon

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#67]
https://developer.android.com/preview/features/adaptive-icons.html
Is related to #46

**Comment by RajaVamsi11** [comment]
@mhutti1 I will work on this issue.

**Comment by RajaVamsi11** [comment]
@mhutti1 Adding adaptive icons require API level 26.After adding the adaptive icons i think the app can not run on mobiles whose API level is  less than 26.
What should i do?

**Comment by mhutti1** [comment]
If there is a work around to allow this to be used on 26+ and the previous version on < 25. Otherwise a script should be used as suggested in #46

**Comment by kelson42** [comment]
Related to https://github.com/kiwix/kiwix-android/issues/457 looks like

**Comment by mhutti1** [comment]
In a way but minsdk is what might block this

**Comment by abdulwd** [comment]
I don't think the **minSdk** version will be a problem in using adaptive icons. On APIs<26 the launcher will just fall back to the legacy icon. The **targetSdk** version might be a problem and I have incremented it. So after merge of PR #478, I think this issue can be worked upon. The app will work on all APIs from 14 to 27. You may refer to:
https://developer.android.com/studio/write/image-asset-studio.html#create-adaptive
