### ISSUE TITLE
Reducing the download chunk size for better validation and download process for the user.

### ISSUE THREAD

**Issue by harshvardhan-takawale** [kiwix/kiwix-android#671]
#### Feature Description:
I am suggesting to reduce the chunk size from current 4GB to something like 100MB. What this does is, in case of failure in the download of large files, few of the chunks are already fully downloaded and thus the download need not begin from the start and thus save the user data.
Another feature that this idea has a potential to serve is validation. If we validate files in chunks of smaller sizes the user need not download the entire file that has corruption somewhere in the middle. This saves user data and also makes the validation more accurate as chunks are small. But here I require help from the server-side team of the organization. I would require hashes for each chunk of 100MB(this should not be a difficult implementation using proper offset and size of the chunk as 100MB). But I am not very sure as I haven't tried anything of this sorts before. Can someone from the backend team let me know the possible problems that might come up during the implementation of this?

**Comment by harshvardhan-takawale** [comment]
@kelson42 @mhutti1 @rashiq I have provided a possible solution in my proposal please let me know if you find some problem in it. Also, please tag someone from the team who can answer the question.

**Comment by kelson42** [comment]
I will close this proposal because we have meanwhile ZIM files with content (like videos or fulltextindex) which can not be randomly cut in the middle ie. in two or more files). That means that the Java code can not know where to split a file. This information needs to be stored in the ZIM file itself. On the top of that, we are going to integrate the downloading library to the Kiwix-lib, so in the near future, this will be handled outside the Java. For now, I think nothing should be done to change fundamentally the download system in Java.

**Comment by harshvardhan-takawale** [comment]
@kelson42 Alright I'll drop the idea of reducing the chunk size. But we can go on with the validation of the entire file right(4GB chunks)?

**Comment by kelson42** [comment]
@harshvardhan-takawale I do not think so. Do you want to implement a Metalink/Bittorrent client in Java? How do you want to validate that 4GB chunk?

**Comment by harshvardhan-takawale** [comment]
Just a simple MD5 checksum after download won't do?

**Comment by kelson42** [comment]
@harshvardhan-takawale A md5 checksum is only a checksum... to make a validation, you need to validate against a reference? Which one?

**Comment by harshvardhan-takawale** [comment]
@kelson42 We do have an ID right with each file which is its MD5? Just another question, how does the pause feature work in the current download process for video files? Can't we try the same here?

**Comment by kelson42** [comment]
@harshvardhan-takawale We do not download videos. You need to clear out where your reference md5sum checksum would come from in your proposal IMO... Anyway it might come from the metalink provided online for each ZIM file, but then the size of each chunk would be driven from the metalink file (so server side)... and that would basically mean reimplementing Metalink in Java... which is a bad idea as we are integrating a metalink client anyway in the kiwix-lib.

**Comment by harshvardhan-takawale** [comment]
@kelson42 What if instead of downloading it in parts, we just pause it after a fixed interval and validate, the pause mechanism is already implemented right?

**Comment by harshvardhan-takawale** [comment]
@kelson42 I sent a draft yesterday from whatever I understood, you can read the proposal there in a bit detail. Anyway, after this discussion, I will make some major changes in it(maybe remove the entire download thing). You can comment there if you like something want it in the final proposal as I don't think there will be enough time for sending new draft. I guess the proposal was a bit too ambitious. Thanks for the help.

**Comment by harshvardhan-takawale** [comment]
@kelson42 Just a help one last time please. The id of the book we get is the MD5 of the file right? If yes, can we run the md5 algorithm on the file after completely downloading it and compare both the id and whatever we get after running the algorithm? I will not change a thing in the way download happens(no implementation of anything like Metalink,Bittorrent,etc. client in Java). Sorry, if I am not able to understand some point of what you are trying to convey.

**Comment by kelson42** [comment]
@harshvardhan-takawale The ID of a ZIM file is not the md5sum.

**Comment by harshvardhan-takawale** [comment]
@kelson42 I checked out the library and also tried downloading some files and for every `zim` file there is a corresponding `meta4` file that contains the details I need (md5 and sha hashes for the whole file, and also by parts) 
For eg. [wikipedia _ab_all_nopic_2017-07.zim](http://download.kiwix.org/zim/wikipedia/wikipedia_ab_all_nopic_2017-07.zim) and [wikipedia _ab_all_nopic_2017-07.zim.meta4](http://download.kiwix.org/zim/wikipedia/wikipedia_ab_all_nopic_2017-07.zim.meta4)
These can be used as reference values against which it can be validated.
Are meta4 files not present for all zim files or is there any other reason we should not be using it?
