### ISSUE TITLE
Search option for available languages.

### ISSUE THREAD

**Issue by sakchhams** [kiwix/kiwix-android#676]
#### Add an option to search for available languages.

The current Library->Online->Search - Select Languages looks like this.
![Screenshot of language selection dialog](https://i.imgur.com/fvzDw9Q.png)

There should be an option to search for a particular language in the list. Also, the selected languages should be shown on top of the list to make sure they're easily visible and accessible.

**Comment by sakchhams** [comment]
@mhutti1 @kelson42 I think this could come under 'good first issue'. What do you suggest?

**Comment by brijeshshah13** [comment]
@sakchhams I agree with you on the idea that the selected languages should be shown on the top of the list. And about the Search option for available languages, can you please provide any reference app screenshot showing how and where you want to implement it (as its a Dialog box) ?

**Comment by sakchhams** [comment]
@brijeshshah13 I'll try and pull up a sample. Although I guess you'd have surely seen it. It's a common UI practice to do so. Include a text field (EditText) on top of the list, and the list items would be filtered based on the entry in the text field.

**Comment by brijeshshah13** [comment]
@sakchhams I have, but still it would be better if you could post a reference here so that @mhutti1 and @kelson42 can verify the same before you start with the implementation.

**Comment by sakchhams** [comment]
@brijeshshah13 here's a crude mockup. <br/>![Screenshot](https://i.imgur.com/5DRMYZA.png)
Showing a text box to type the name of the language and a list that displays elements filtered based on the text entered. If no text is entered all items will be displayed in the list.

**Comment by brijeshshah13** [comment]
@sakchhams Alright. @kelson42 Please share your views of the mockup.

**Comment by abdulwd** [comment]
Closed via #774.
