### ISSUE TITLE
kiwix-android fails to compile on kiwix-build 's travis-ci

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-android#679]
## Bug Report

   Last commit https://github.com/kiwix/kiwix-android/commit/ebac71aeed61821c7c4c443d28cca5a40afdc82c fails to compile.

`leakcanary` doesn't exist.

Log from travis :
```
/home/travis/BUILD_android_arm/kiwix-android/app/src/main/java/org/kiwix/kiwixmobile/KiwixApplication.java:24: error: package com.squareup.leakcanary does not exist
import com.squareup.leakcanary.LeakCanary;
                              ^
1 error
```

### Environment
  * version of the software you use : master
  * device / operating system : travis-ci (kiwix-build)

**Comment by brijeshshah13** [comment]
@mgautierfr Please have a look at this issue #664.

**Comment by mgautierfr** [comment]
Oops, my bad. I'm closing this issue as a duplicate of #664.
