### ISSUE TITLE
Export reading to browser (or PDF)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#68]
I'll try to summarize the conversation I had with a visually impaired person who made a enhancement request: she essentially would like that articles can be opened in a separate browser (I assume one that caters better to her needs). When I asked what the browser offered that Kiwix didn't this is what she said:

"I can't speak for others, but to me being able to use the browser would allow for the various accessibility issues I've been having to no longer exist. (..) It can take a long time to actually navigate the article, because to get from one paragraph to the next can require multiple clicks, which also means that the beginnings of the article and where sources are referenced slow things down. This makes the reading experience slow and haulting. I then have a problem with not being able to use the "find-in-page" function, probably the fault of my device. Also, if I want to resume the reading of an article, it takes absolutely AGES to get there, because I have to navigate line by line... All these problems are not present in my browser. 

An additional advantage of doing it in browser is that the article could potentially be saved as a pdf, which might come in handy. So this would solve several problems for myself (and genuinely revolutionise my experience), and would probably have benefits for other users."

**Comment by Popolechien** [comment]
Additional info:
"I'm using an android tablet, which was released around July 2016, called the Braille Note Touch. This is by Humanware and it uses a skin on top of android kitkat called KeySoft."

**Comment by kelson42** [comment]
See also #19

**Comment by kelson42** [comment]
I see no reason why we should not have this feature on iOS but on Android. See https://github.com/kiwix/apple/issues/171. I believe we can have a blind friendly Kiwix without having this feature implemented.
