### ISSUE TITLE
Specify round icon in AndroidManifest

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#681]
### Environment
  * version of the software you use: 2.3
  * device / operating system: Moto G5S / Android 7.1.1
  
### The Bug:
The circular icon of the app is not shown by the launchers using circular icons.

Screenshot:
![image](https://user-images.githubusercontent.com/20206262/38167925-eee77326-355c-11e8-9a8a-6fefbf81da81.png)

**Comment by Rahul5758** [comment]
@abdulwd In your screenshot there are other apps too which do not have an round icon, so I don't think its necessary to specify a round icon.

**Comment by abdulwd** [comment]
@Rahul5758 I don't think this is a big change. I have only added a single line and we do have the round icon which was unused till now. Someone who has added the icon must have forgotten to define it in the manifest file. An excerpt from https://developer.android.com/about/versions/nougat/android-7.1.html#circular-icons : 

> apps should make sure to define both `android:icon` and `android:roundIcon` resources when responding to launcher intents

**Comment by jhbiggs** [comment]
@abdulwd Please let me know how this commit works for you all.
