### ISSUE TITLE
Add static shorts

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#688]
### Environment
  * version of the software you use: 2.3
### Feature Request
Add the following static shorts to the app:
- New tab
- Get content
#### Feature Description
App shortcuts were introduced in API 25, they let the user quickly do common tasks. So as we move to multi-ZIM paradigm these shortcuts will be more useful. Therefore, we must add them now. For more information refer to this [link](https://developer.android.com/guide/topics/ui/shortcuts.html#static)

**Comment by abdulwd** [comment]
@mhutti1 Please review this issue. May I start working on it? :)

**Comment by mhutti1** [comment]
Sure :)

**Comment by abdulwd** [comment]
Closed via #755
