### ISSUE TITLE
Bug: Content Header stale value from previous page used

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#691]
In my recent testing of Kiwix Android I discovered what seems to be a consistent bug where the Content Header retains the previous text if the current page does not have a suitable value.

I first noticed this when the automated Espresso `BasicTest` failed on a device where I'd used Kiwix previously (to read the Wikipedia for Schools zim file, etc). Instead of seeing `No Content Headers Found` the heading said `Wikipedia Selection for Schools`
Here's the extract from the log of the test failing:
```
Starting 6 tests on SM-G930F - 7.0

org.kiwix.kiwixmobile.tests.BasicTest > basicTest[SM-G930F - 7.0] FAILED 
        android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.kiwix.kiwixmobile:id/titleText and with text: is "Help" and Child at position 0 in parent Child at position 0 in parent with id: 2131296392 and is displayed on the screen to the user)

org.kiwix.kiwixmobile.tests.BasicTest > testRightDrawer[SM-G930F - 7.0] FAILED 
        android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.kiwix.kiwixmobile:id/titleText and with text: is "No Content Headers Found" and Child at position 0 in parent Child at position 0 in parent with id: 2131296445 and is displayed on the screen to the user)
```

I then managed to reproduce the problem using another ZIM file in a more general example. The ZIM file is Bollywood 2017-02-14 no pictures. The homepage doesn't have a heading in the page content and the RightDrawer menu correctly (but perhaps unhelpfully from a user's perspective) says there's no content header (see screenshot below)
![nocontentheadersfoundforbollywood homepage](https://user-images.githubusercontent.com/785891/38416455-a33c1d4e-398c-11e8-919a-b78163b908a4.png)
I then use the Random Page menu option to load another page, which happened to be: Good Night (film). This has a heading and the heading appears in the RightDrawer menu (see screenshot for confirmation)
![goodnightpagewithcontentheader](https://user-images.githubusercontent.com/785891/38416513-d86f6034-398c-11e8-81f0-856e4b44a633.png)
I then used the homepage menu to return to the homepage for the ZIM file which shows the Bollywood content, that doesn't have a header. _However the RightDrawer menu now shows the heading for the previous article._
![bollywoodnowhasheaderfrompreviouspage](https://user-images.githubusercontent.com/785891/38416636-40839078-398d-11e8-8a5d-e66ed0f0ffcd.png)

Note: the screenshots only show part of the RightDrawer menu so you can see the contents of the article below, as the RightDrawer becomes more visible the opacity increases over the article so it's no longer visible once the drawer is fully displayed.

**Comment by julianharty** [comment]
Here's another example using an Arabic Wikipedia ZIM file (Arabic No Videos 8.1GB 2018-03-18)
Here's the homepage without a Heading and with 'No Content Header'
![arabichomepagenocontentheaders](https://user-images.githubusercontent.com/785891/38417391-0a4da9f0-3990-11e8-839d-a0b8c229ef6e.png)

Then an article that does have a heading 
![an arabic page with a heading](https://user-images.githubusercontent.com/785891/38417425-2778285c-3990-11e8-85ba-714b00cf02b5.png)

And that heading remains in the RightDrawer menu for the previous page 
![arabic homepage now has contentheading from previous article](https://user-images.githubusercontent.com/785891/38417444-387f94c8-3990-11e8-87c4-db38d9cda5e9.png)

As Arabic is RTL it's harder to show the heading in the RightDrawer menu while also showing the article on screen, sorry. You're welcome to test directly :)

**Comment by kelson42** [comment]
Might that be the same bug as #344?

**Comment by julianharty** [comment]
@kelson42 Yes, looks like they are related bugs. Thanks for making the connection.

**Comment by julianharty** [comment]
My last example for now, Wikipedia Maths, 2017-12-07, English, 15 000 maths articles from Wikipedia 604MB

![welcometomathsnocontentheader](https://user-images.githubusercontent.com/785891/38417704-44223d0c-3991-11e8-952f-c9f2158e5f7c.png)

![welcometomaths bolzanoarticle](https://user-images.githubusercontent.com/785891/38417712-499825da-3991-11e8-876f-ec5495bd975b.png)

![welcometomathshomepagenowhasprevioustitle](https://user-images.githubusercontent.com/785891/38417721-4f15ccc4-3991-11e8-9102-dd1992200738.png)

**Comment by kelson42** [comment]
Would be really helpful to identify if the problem comes from the Java or the Kiwix/ZIM library.

**Comment by julianharty** [comment]
@kelson42  Agreed. My impression is the problem's more likely to be in the Java code of Kiwix Android from my testing this weekend but I've yet to isolate the cause.

BTW: if the homepage of the underlying Wikipedia source had a H1 heading then the problem would be less apparent (this would partly mask the issue, not fix, it to be clear...) Here's the source page https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Film/Offline_Bollywood

**Comment by RohanBh** [comment]
The bug was on Java side. I've created a PR (#701) to fix this issue.
