### ISSUE TITLE
Look into building all app variants in CI to reduce room for errors

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#692]
## Feature Request

Look into building all app variants in CI to reduce room for errors when some variants might fail. This will likely increase build time so a compromise might need to be found.

**Comment by kelson42** [comment]
@mhutti1 Which build variants are not built in the CI currently?

**Comment by mhutti1** [comment]
I think I told it to only build kiwixDebug to save time. Ideally we should be building and testing at least kiwixCustomExample as well though.

**Comment by macgills** [comment]
I agree on the building front, as part of this I would also suggest we delete `mock_network` & `local_download_server`, that way the only command we need run is `assemble` or perhaps `assembleDebug`.
Testing is less important to me as the code is shared, I don't know what meaningful test would arise from it.

**Comment by kelson42** [comment]
@macgills Could you please activate all the built variants in the CI (and close that ticket) and open a new ticket to remove `mock_network` & `local_download_server` (their value and way they work are totally unclear to me).

**Comment by macgills** [comment]
Activating all the build variants now would slow down the build quite a bit, I would say to wait until we have removed the other buildTypes.

**Comment by mhutti1** [comment]
I think this was partly my motivation for maybe having a two tier build system with the other flavours being run as an additional check but merging being allowed without them. Not sure if its a good idea though.

**Comment by macgills** [comment]
I think parallel stages are a thing travis can do? That would assuage fears of slowdown.
I think it should fail a build, the changes made have incurred a regression and it is the duty of that person to fix them

**Comment by kelson42** [comment]
Now that #1229 has been implemented. How much work would be needed to implement this ticket?

**Comment by macgills** [comment]
5 minutes?
