### ISSUE TITLE
Poor layout of Help page in landscape mode

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#693]
Kiwix can work in both portrait and landscape mode. 

In landscape mode the help content is rendered so that only the logo is visible, neither of the text or the 'Get Content' menu are visible.
![nexus7landscapelogofillsentireviewinlandscape](https://user-images.githubusercontent.com/785891/38501002-d2ff112a-3c03-11e8-8259-a3d4001ce1b0.png)

The screen need scrolling to see the text and the link.
![nexus7landscapescrolldowntofindgetcontent](https://user-images.githubusercontent.com/785891/38501035-e9354702-3c03-11e8-9380-33592387ec57.png)

I hope we can improve the layout so users don't need to scroll to see the text and the Get Content link.

Note: The current layout also prevents the DownloadTest from finding the `Get Content` link. We can change the test to use the `Get Content` option from the overflow menu, however it'd also be great to use the current navigation method too. This would help with #246 too. 

Tested with devices: Nexus 7 (2012) & (2013). It's likely to affect other devices in landscape mode.

**Comment by hjoshi123** [comment]
@julianharty I think Android itself is adjusting the layout because of rotation. What do you think we can do?

**Comment by mhutti1** [comment]
One solution would have 2+ columns for the cards in landscape mode.

**Comment by julianharty** [comment]
I've discovered there'd be a bit more work to do because of the way we load the help page in the app (apart from improving the layout in landscape mode). As I expect both @hjoshi123 and @mhutti1 know, the help contents are loaded in `onPageFinished(...)` in https://github.com/kiwix/kiwix-android/blob/master/app/src/main/java/org/kiwix/kiwixmobile/KiwixWebViewClient.java 

This only happens when a ZIM file is loaded, not on rotation. I discovered this when I created a simple landscape-mode help.xml file - it loaded fine when the device was in landscape mode mode, but also displayed when I rotated the device. Conversely if I started the app (or loaded a ZIM file via  the ZIM File Manager)  in portrait mode I only see the portrait view. I did experiment with removing the test for `if (view.findViewById(R.id.get_content_card) == null) {` in case that was causing the layout to be cached on rotation but that didn't seem to fix anything. However, I might be missing something which someone else can spot?

What I've done for now is hardcode the width of the image to 400dp in the main `app/src/main/res/layout/help.xml` file. This marginally reduces the image in portrait mode, it has a more marked effect in landscape mode and enables enough of the text and the Get Content button to be visible so they can be read and the button used. The espresso tests now run successfully on the Nexus 7 models in both portrait and landscape modes.

I'd love your help to find a better way to address both the layout and when the help page is loaded. It'd also be worth reviewing how we support night-mode. In my hands-on testing the night mode seems to be applied when I enable it and removed when I disable it, but I don't yet quite understand how it's doing so if this method is only being called when the app starts, or loads a ZIM file...

**Comment by RohanBh** [comment]
@julianharty The reason that rotation of device won't load the alternate resource file is that we've decided to handle such [configuration changes](https://developer.android.com/guide/topics/resources/runtime-changes.html) ourselves. This is why Android doesn't restart the `KiwixMobileActivity` to load the required XML resource file.
As mentioned [here](https://developer.android.com/guide/topics/resources/runtime-changes.html#HandlingTheChange), we can override the method `onConfigurationChanged` and do something like this:
 ```Java
@Override
public void onConfigurationChanged(Configuration newConfig) {
    super.onConfigurationChanged(newConfig);

    // Checks the orientation of the screen
    if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
        // load the help page in landscape
    } else if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT){
        // load the help page in portrait
    }
}
```
Although, the [docs](https://developer.android.com/guide/topics/resources/runtime-changes.html#HandlingTheChange) warn us against using this method and asks us to use it as a last resort only. Therefore, if possible, we should let Android handle the configuration change.

**Comment by julianharty** [comment]
@RohanBh Thanks for letting me know why you think it's not been called on Rotation Change. Looks like an elegant fix might take quite a bit of work as changes may ripple through the application. Perhaps a partial fix such as the one I've proposed would ameliorate (make less severe) the current limitation? At the moment I'm waiting for @mhutti1 or another of the main contributors to the codebase to provide their suggestions. I'm happy to create several layouts that'd render acceptably on various screen resolutions.

**Comment by RohanBh** [comment]
@julianharty I think that not much work will be needed if we just override the `onConfigurationChanged()` method. All we need to do is add the corresponding help layout (the XML resource file which is made for that orientation) as a child to WebView and update the WebViewClient's [help variable](https://github.com/kiwix/kiwix-android/blob/96704debdf503dadcd72c9ce5ff7431060242e3d/app/src/main/java/org/kiwix/kiwixmobile/KiwixWebViewClient.java#L44). But I am not sure if this is such a good idea.

**Comment by julianharty** [comment]
@RohanBh Thanks for the suggestion. How about we test both approaches?
Would you like to try the one you propose & I'll add some additional
layouts for the one I've suggested?

**Comment by RohanBh** [comment]
Sure, we can do this.

**Comment by abdulwd** [comment]
Help page has been moved to a separate activity. See #803.
