### ISSUE TITLE
Can not redirects to redirects (to URL with different depth) properly

### ISSUE THREAD

**Issue by okkebal** [kiwix/kiwix-android#694]
There is a huge problem with Kiwix on Android, (apart from the enormous search problems) wich is the fact that the download list is polluted with over a hundred Stack Exchange Zim files that do now work on android at all!

Thanks to this bug: https://github.com/kiwix/kiwix-lib/issues/70

There are: problems with Fonts, CSS, and images the pages are totally useless this way.

Please remove the Stack Exchange files from the Android "Online" tab. These files do not work, and should not be listed until they do.

**Comment by kelson42** [comment]
A few random click on any of the StackExchange ZIM file will show the problem: CSS files are not loaded properly.

**Comment by kelson42** [comment]
@mhutti1 I hope this will be fixed in the next few months for 3.0, so we do not need sophisticated/robust. Just skip all library_zim.xml where the "url" attribute has "/stack_exchange/" in it. I do not see better solution
