### ISSUE TITLE
Open Kiwix in search mode

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#70]
If Kiwix has already content loaded and it's not the first time it has been started then it might make sense to open it in "search mode", that ḿean with the searchbox available and the virtual keyboard layout visible. This is the feedback of a user and it seems to not be a fundamentally bad idea.

I do not have any strong opinion, maybe this behaviour could be made optional? This ticket is first mostly to get feedbacks.

@mhutti1 @rashiq @EladKeyshawn ?

**Comment by dhirajj75** [comment]
yes. Because every time we open the kiwix and click on get content it takes time and internet to load the content. I also think that kiwix should be opened in search mode so that the content already loaded is not loaded again and it will be user experience.
@mhutti1

**Comment by mhutti1** [comment]
@dhirajj75 I think you might misunderstand how remote content works. once you have downloaded it once it stays on your device.

**Comment by dhirajj75** [comment]
@mhutti1 I was talking about the content that we get to download after we click on Get Content Button. I think untill the user makes a new search the previously loaded content should be available for download.

**Comment by mhutti1** [comment]
@dhirajj75 Oh ok. That has no relation to this issue though and is part of a more long running backend task.

**Comment by rashiq** [comment]
I strongly disagree. The wikipedia app doesn't open in search mode either. No app does, because it's disruptive and an anti-pattern. 

Imagine you open the app, and then _bam_ keyboard pops up. It wouldn't be a nice UX flow.

**Comment by kelson42** [comment]
I would suggest that if people want to make straight away searches, then they probably have to use Kiwix search widget.

**Comment by rashiq** [comment]
Yes totally agree @kelson42. Shall we close this?
