### ISSUE TITLE
Use notification channels to post notifications

### ISSUE THREAD

**Issue by RohanBh** [kiwix/kiwix-android#702]
### Are you ready to report?
Yes

### Environment
  * version of the software you use: master branch
  * device / operating system: op3/Android 8.0.0
  
### The Bug:
When downloading zim files on Android O, notifications won't show.

This is because Notification Channels are [not used](https://github.com/kiwix/kiwix-android/blob/master/app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java#L189-L199) to post the notifications in Kiwix. In Android Oreo, all notifications must belong to a channel or they won't show.

##### Screenshot:
No Kiwix notification in the status bar.
![no_notification](https://user-images.githubusercontent.com/24610859/38671759-dc1498f8-3e69-11e8-9228-daec2c03f78f.jpg)

##### Related Links:
- [Notification Channel Official docs](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#ManageChannels)
- [Youtube Video](https://youtu.be/zGIw4MIJn5o)

#### Steps to reproduce:

  1. Get a phone running Android Oreo.
  2. Download a Zim file.
  3. Notifications for download doesn't show.

  * What should be the behavior from your point of view? How do you expect the service to work?
   We must use notification channels wherever notifications are posted so that users won't miss any important notification in newer devices.

I would like to work on this issue.

**Comment by mhutti1** [comment]
@RohanBh this is a priority. Please submit a fix ASAP.

**Comment by RohanBh** [comment]
I will submit a PR by the end of this weekend.

**Comment by kelson42** [comment]
@RohanBh This is buggy and does not seem to be tested properly, I get duplicates now in my notification bar. On the top of that the "downloading" tab is not refreshed properly (most of the time simply empty).

**Comment by RohanBh** [comment]
@kelson42 This is not because of what I pushed. I simply added a channel to the notification that was being shown. These bugs should've existed before. I will try to reproduce and find the source of these bugs this weekend.

**Comment by mhutti1** [comment]
Worked on with 3bead53f134ef3167015e55ce6a3cd5bbc39ef1d . @kelson42 the other issues are long standing and not related to this issue. If you feel they are blockers for 2.4 can you open a separate issue.

**Comment by kelson42** [comment]
@mhutti1 @RohanBh OK, thx

**Comment by iadeelzafar** [comment]
This issue has been resolved and I think this can be closed. @mhutti1 @kelson42
