### ISSUE TITLE
Download does not stop

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#703]
Observed on Huawei P7, Android 7.0

I started downloading a zim file and then interrupted it from the notification area. It showed that download had been interrupted (ie nothing left in the "downloading" window). It did however keep on downloading content, and afer I closed the app it actually resumed downloading in the background (I ended up uninstalling the app).

I do not seem to be able to reproduce the bug at the moment.

**Comment by kelson42** [comment]
We have many problems around download start/stop/sync with notifiation/UI.

See also: #670 #600 #658 #597 #329 #240

**Comment by mhutti1** [comment]
@kelson42 This is not a regression and while I agree there are a host of issues with downloading I don't think 2.4 is the time to address them. It would take me a very long time to track down each specific edge case. Would probably be better to rewrite the back end entirely.

**Comment by kelson42** [comment]
@mhutti1 OK. The libkiwix should handle the download in the near future (before end 2018). I descopte the ticket of the milestone.

**Comment by macgills** [comment]
Fixed in #1170
