### ISSUE TITLE
Help button is not helpful

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#704]
Tried to press "Help" in the menu but nothing happened (tried in English, French and Spanish): meaning that it took me back to the generic "welcome to Kiwix" page.

**Comment by Popolechien** [comment]
@brijeshshah13 Well that the Welcome page is so long already is an issue in an of itself. We could probably create an appropriately named "Help/FAQ" subpage that would already take both sections "Where is the content" and "How to use large zim files". The Where? part needs to be rewritten/simplified, I'll take care of it.

**Comment by mhutti1** [comment]
Yes it might be nice to have a bit of a FAQ page with more detail than the welcome page.

**Comment by harshvardhan-takawale** [comment]
@Popolechien @mhutti1 @brijeshshah13 Even the "Find in page" does not work on Help page. Should I make a different issue for this?

**Comment by mhutti1** [comment]
Sure

**Comment by abdulwd** [comment]
Closed via #803.
