### ISSUE TITLE
Updating Kiwix gives library error when (re)opening for the first time

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#706]
When updating to 2.4 and at first opening of Kiwix I got the below screen rather than the standard welcome message (or, better, remaining on the last article I had been checking out). Zim files were still around and were identified correctly when I went into my local library, however.

![screenshot_20180409-091544](https://user-images.githubusercontent.com/21675885/38725847-d77f750c-3f08-11e8-9e98-8fbde43768a7.png)

**Comment by mhutti1** [comment]
This has always been the case as far as I can remember. We should try to track down the cause.

**Comment by brijeshshah13** [comment]
@Popolechien What do you mean by "updating to 2.4"?

**Comment by Popolechien** [comment]
@brijeshshah13 Well I've updated to the beta release of 2.4 (build 11809880) but tbh and to @mhutti1 's point I never really paid attention if it was the same in earlier versions. I'll correct the title.

**Comment by mhutti1** [comment]
I have worked out this is due to us changing our provider base url to allow custom apps to not accidentally use another apps content. I will try fixing this where it occurs.
