### ISSUE TITLE
Render "opening" bar at top of screen in a more visible way

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#709]
There seems to be a bit of lag when opening an article in Kiwix. There is a dark blue "opening" bar at the top of the screen to show progress (see image) but it is not very visible and had me think a couple of times that the search was simply not functioning.

Consider turning it to orange so it stands out a little more.
![bar](https://user-images.githubusercontent.com/21675885/38726807-87e55054-3f0b-11e8-845d-d04f4d4fda2d.png)

**Comment by brijeshshah13** [comment]
@mhutti1 I think the current color is doing just fine. What are your views?

**Comment by kelson42** [comment]
Yes, I have difficulties myself to see the bar. Not sure here how much Android guidelines apply!? Maybe a bit of a brighter color would be better or one or two pixels higher progression bar. Anyway, not a blocker for maintenance release 2.4.

**Comment by sakchhams** [comment]
@kelson42 The color could be made brighter and perhaps an animation could be added to make it visually identifiable. I could work on the same if everyone approves.

**Comment by mhutti1** [comment]
I think there is a line between being jarring for the user and visible. I don't really know where we are on that line.

**Comment by Popolechien** [comment]
@schoenbaechler (testing if this works here too :-) Thoughts on this bar thing?

**Comment by schoenbaechler** [comment]
Hi all, agree that the progress bar’s current color needs more contrast, since the app header is a pure black (#000000). Attached you’ll find some suggestions that work better than the current dark blue (#304E9A). If there already brighter colors in use in another part of the app, I suggest to consider these as well to keep it consistent

![loading-bar-suggestion](https://user-images.githubusercontent.com/5031003/38940086-9e67c120-42e6-11e8-96a5-3e1090e7cb8e.png)

**Comment by kelson42** [comment]
@siddharth2010 The second proposal (blue) would be good enough. Do you think this is something you could implement?

**Comment by siddharth2010** [comment]
Sure @kelson42 ! Will just look into it.

**Comment by kelson42** [comment]
@siddharth2010 any news?

**Comment by 4shutosh** [comment]
Can I work on this issue?

**Comment by kelson42** [comment]
@4shutosh If you can fix it really quickly, yes.

**Comment by 4shutosh** [comment]
A color with better contrast for both modes(dark and light) can be used.
