### ISSUE TITLE
Change bookmark star icon to a heart

### ISSUE THREAD

**Issue by ISNIT0** [kiwix/kiwix-android#71]
Twitter did it for a reason :) Increase in feature usage by 6%, 9% in new users.

https://www.buzzfeed.com/alexkantrowitz/heres-the-data-that-shows-why-twitter-switched-to-hearts-fro?utm_term=.hvg3YBa84#.sr44vkBlq

Sorry I can't find the source anywhere.

**Comment by kelson42** [comment]
That might be a good idea. Would be great to check if that does not go against Android UI guidelines. In the worse case this might be done as an option (custom app config json). It seems to make really sense for the Phets custom app - at least.

**Comment by kelson42** [comment]
@mhutti1 Any opinion on that? That might make a good GCI simple task?

**Comment by mhutti1** [comment]
I'm no designer. I don't really have an opinion either way.

**Comment by kelson42** [comment]
@mhutti1 OK, then trust @ISNIT0 know-how. Let's do it.

**Comment by mhutti1** [comment]
@kelson42  So I did a bit of reading https://ux.stackexchange.com/questions/79221/star-vs-heart-icon-to-represent-save-as-a-favourite. I think a point here is valid. Do you really want to be hearting an article on a childhood disease?

**Comment by kelson42** [comment]
@ISNIT0 What do you think about last @mhutti1 remark?

**Comment by ISNIT0** [comment]
Either way I don't suppose it's a huge deal. The Twitter example was just for increasing the usage of the feature.

I'm not overly opinionated though.

**Comment by kelson42** [comment]
As it seems we are a bit unsure if this is a good move, I propose to close this ticket.
