### ISSUE TITLE
Deleting Kiwix does not delete zim files (nor some preferences)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#711]
Should it not clean the whole thing (or at least ask?)

I suspect it also does not delete some preferences either : uninstalling and reinstalling Kiwix, it remembered that I wanted it set in Spanish (yet did open in French, as explained in #710). All other preferences and permissions where however reset to zero.

**Comment by kelson42** [comment]
This is duplicate of #596
