### ISSUE TITLE
Could Kiwix detect somewhat accurately a phone's country of residence?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#714]
We get a lot of support requests from Cuba and I suspect there isn't much in terms of competition for operators there.

Ideally, I would want to have a dedicated Help page asking users to go to the government's Joven Clubs de Computacion to help them, since these offices do distribute localized versions of Kiwix.

**Comment by sakchhams** [comment]
@Popolechien using GPS, yes. If that is an option.

**Comment by Popolechien** [comment]
Probably not as many are low-end devices :-/
So basically there's no (easy) way to fish the mobile network's operator and then say "if Cubacell then Help.page is XYZ"?

**Comment by mhutti1** [comment]
There are multiple location layers in Android using a variety of techniques to attempt to acquire location. I think it is possible to get basic country information on most devices.

**Comment by Popolechien** [comment]
Ok, thanks - bonus question/remark then: a lot of people in Cuba I suspect are getting refurbished phones from the US, so the location function should not be device/or default-language related.
Either way, let me know when someone looks into it and I'll prepare the relevant message.

**Comment by mhutti1** [comment]
I think we should be able to get this info from the sim card if they have one using https://stackoverflow.com/questions/11872483/reliable-method-to-get-the-country-the-user-is-in. If they have a tablet without GPS or a SIM imported from the US not correctly wiped then it might be more difficult.

**Comment by Popolechien** [comment]
Well the worst case scenario (incorrectly wiped) would mean that they wouldn't see any difference with their current situation. So overall I only see benefits in trying.

**Comment by kelson42** [comment]
This kind of move:
* Will be heuristic
* Will need special new permissions (GPS access, SIM access, ...).

I understand the need, but I'm really worry the amount of permission/work and the uncertainty of result quality in consideration of the problem.

If the goal is to use more local support forces, other ways might exist: like for example, proposed an integrated support workflow pushing that (asking where people are, what is the kind of problem, etc... to route them to the right local service desk)

**Comment by harshvardhan-takawale** [comment]
Can we not just ask the user to enter the country they live in as one of the fields in the settings?

**Comment by mhutti1** [comment]
Regarding permissions only the fine grain accuracy options should need the full permissions. I think you should be able to get at least the country without any more permissions.

**Comment by kelson42** [comment]
@Popolechien I will close this ticket as the discussion about the real problem (from user perspective) is not properly set and the topic quite difficult to handle within a ticket of kiwix- android.
