### ISSUE TITLE
Merge library tabs "Device" & "Downloading"

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#716]
Having three different windows for content is a bit confusing, I suggest removing the "downloading" one to merge it with the local library. See image:

![improve](https://user-images.githubusercontent.com/21675885/38859004-6aeb848a-422d-11e8-8b70-6aa96958729e.png)

#75 (I closed it as duplicate) was mostly seing the same:
- Rename "Device" to "Downloaded"
- Move "Downloads" into "Downloaded" panel
- When a download is initiated, move the user to "Downloads"

**Comment by harshvardhan-takawale** [comment]
@mhutti1 Sounds like a good idea. If we are going foreward with this I would like to work on this.

**Comment by mhutti1** [comment]
I think this will be worked on by @abdulwd sorry.

**Comment by macgills** [comment]
@kelson42 @Popolechien this has some conflict with the ability to select books to delete/share. It is actually easier to merge Online/Downloading if that is desirable?
Otherwise when we enter a selection we temporarily hide the downloading books

**Comment by Popolechien** [comment]
@macgills Sounds good. The idea is to restrict the number of tabs, so merging Online/downloading does the exact same thing to me. 
Not a huge fan of hiding, because of file size people might wonder where those files are gone without realizing they've been downloading already for a while.

**Comment by macgills** [comment]
The hiding would only occur when users have done a long click to enter "Multiple Selection Mode" on the theoretical merged device/download list.

From a data model perspective I am happier to merge library/downloading but that should never be the only reason.
