### ISSUE TITLE
Help page drawers behave weirdly

### ISSUE THREAD

**Issue by ISNIT0** [kiwix/kiwix-android#718]
### The Bug:

On help page:
  * Left Drawer shows "Help", even in other languages
  * Right Drawer shows "No content headers" but should show "Help"

![screenshot_2018-04-18-17-39-42](https://user-images.githubusercontent.com/5173131/38946142-7fff31b0-4330-11e8-87ff-0e2f2741de1f.png)
![screenshot_2018-04-18-17-39-52](https://user-images.githubusercontent.com/5173131/38946146-80cd1e9a-4330-11e8-9966-7a61f6821ad3.png)

**Comment by abdulwd** [comment]
Made redundant by #832.
