### ISSUE TITLE
"Find in page" not working on Help page

### ISSUE THREAD

**Issue by harshvardhan-takawale** [kiwix/kiwix-android#727]
### Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - Ensure you have tested with the last (dev) version of the software.  (If not, and if possible, run your test again with the most recent version available.)

### Environment
  * version of the software you use : 2.3
  * device / operating system : Moto G4 Plus
  
### The Bug:

  * What do you obtain? A copy of the error message or a screenshot is always useful.
     The "Find in page" feature from the options menu does not work in Help page.

#### Steps to reproduce:

  1. Open Help page
  2. Open options overflow menu
  3. Select "Find in page" and search for some term.
  ...
  The search shows no matches.

**Comment by sparrow007** [comment]
can i work on this ??

**Comment by abdulwd** [comment]
@sparrow007 Sorry but this will not be applicable after #803 is merged.
You can take other issues from the issue tracker we have plenty of them. Maybe you can try #451 to get a quick start, but remember to pull the code from branch [3.0](https://github.com/kiwix/kiwix-android/tree/3.0). Also choose base branch as 3.0 while making the PR. :)
