### ISSUE TITLE
Improvement: Custom Storage Location (or at least move to Android/data)

### ISSUE THREAD

**Issue by metal450** [kiwix/kiwix-android#729]
Kiwix seems to be storing its downloaded content to the root of the internal storage (in a /Kiwix directory).  As standard practice is for apps to store their external data in /Android/data/<app folder>/files, please consider either moving the data there, or allowing the option to choose our own path.

By hard-coding the database to this top-level location, not only does it increase clutter unnecessarily (could you imagine if every Windows application stuck its data in the root C:\?), but it also causes it to be missed by common backup applications, which only look for app data in the standard Android/data location.

Edit: a 3rd side-effect of this is that it causes Android not to be aware of the true storage usage of the app (when viewed in the app settings).

**Comment by mhutti1** [comment]
This has already been implemented and is on master.

**Comment by mhutti1** [comment]
Yeah we are working on getting it out as quickly as possible. If you don't mind a bit of instability you can check out our nightlies: http://download.kiwix.org/nightly/

**Comment by metal450** [comment]
Do we have any idea when this might make it onto the app store? Looks like it hasn't been updated on there in over 16 months (Feb 27, 2017).

**Comment by mhutti1** [comment]
We are rolling out to 25% of users at the moment. Still resolving a few final issues before increasing that size.

**Comment by metal450** [comment]
I just got the update offered to my device - yay! :) And although I was able to change the path...unfortunately, the app still keeps recreating the Kiwix folder in the root-level storage, filling it with a single logcat.txt.  Since the goal was of course to get rid of the clutter in the device's root-level storage, recreation of the Kiwix folder for this logcat file seems to be negating the benefit of this new feature :/

**Comment by mhutti1** [comment]
@metal450 I am sorry we didn't fully address this in the release of 2.4 I have created a separate issue and I hope we can get it included in the next release.

**Comment by metal450** [comment]
Cool, thanks. I just really hope that one isn't another 17 months away! :/

**Comment by mhutti1** [comment]
Hopefully considerably sooner.
