### ISSUE TITLE
Set custom user-agent for the ZIM downloader

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#73]
This is necessary to get more detailed stats. I think to something like "kiwix-android x.y.z"

**Comment by mhutti1** [comment]
The android side of this looks to be done. We send the app version in the user agent. stats.kiwix.org doesn't look capable of displaying custom user agents. @kelson42 does it show up in the logs?

**Comment by kelson42** [comment]
@mhutti1 Thx, will take care of stats.kiwix.org. What is the string of the user-agent (can not find it in the commit)?

**Comment by mhutti1** [comment]
@kelson42 It should be "kiwix-android-version:x" I can't be 100% certain its working though so if you can't find it we might need to do some more debugging.

**Comment by kelson42** [comment]
@mhutti1 Thx, I have started to have a look to Piwik to find out how to deal with this, it looks like there is no clean solution:
1 - https://github.com/piwik/piwik/issues/11641 (so we need to write a plugin)
2 - Modify directly in the source code the list of browser to support this new user agent.

**Comment by kelson42** [comment]
Everything is done here on the kiwix-android side. Thx @mhutti1
