### ISSUE TITLE
Revert #734 to show stack exchange zims

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#735]
#### Feature Description

Re-enable stack exchange zim files once they work again.

**Comment by kelson42** [comment]
With 2.4 the ZIM file works, but the problem is that the CSS is broken. This seems to be a problem with Android (I suspect with subpages) as it works fine with kiwix-serve http://library.kiwix.org/3dprinting.stackexchange.com_en_all_2019-01/A/question/11.html

**Comment by mhutti1** [comment]
So there are still issues withe these ZIMs. I am going to try look into one now.

**Comment by mhutti1** [comment]
The issue seems to be with redirections. @mgautierfr will update kiwixlib to make redirections visible and then the android side will have to handle them.

**Comment by mhutti1** [comment]
Another update. So redirections are now visible but the issue is we need to know if we are to redirect before we attempt to load our content in order to throw a sane error that can be caught (otherwise we would have to use a hacky response body and listen out out for it). So we agreed to add a simple method to determine the redirect for a url to allow this to be run before attempting to load a page.
