### ISSUE TITLE
Left menu overlapped by header

### ISSUE THREAD

**Issue by ISNIT0** [kiwix/kiwix-android#74]
Android 4.4.2, app build is latest commit

**Comment by ISNIT0** [comment]
![screenshot_2017-04-05-08-40-34](https://cloud.githubusercontent.com/assets/5173131/24695032/1fa85180-19dc-11e7-9cfc-03c430b4d37e.png)

**Comment by mhutti1** [comment]
Can replicate in emulator api 19

**Comment by kelson42** [comment]
@EladKeyshawn Maybe you would have look to this as this is with the bookmarking system?

**Comment by mhutti1** [comment]
Don't worry its been fixed on my branch.
