### ISSUE TITLE
Create new home screen

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#743]
The present home screen is the help screen which is not user-friendly. So a new screen has been designed.

![image](https://user-images.githubusercontent.com/20206262/40384780-32981042-5e22-11e8-9a76-f0f69543518b.png)

This screen shows the offline books the user has downloaded. The user can just tap any of the
downloaded books to start reading from the start of the book. The book will open in the same
tab. If a user wants to open another book, the user can open another tab from which another
book can be opened. This is in accordance with the multi-ZIM paradigm. The books are
categorized on the basis of language.

**Comment by abdulwd** [comment]
Any suggestions for the screen design are welcomed. :)

**Comment by abdulwd** [comment]
@mhutti1 It will not be merged with #744. Are there any changes to be done on this home screen?

**Comment by mhutti1** [comment]
@abdulwd ? It is very confusing to have two separate screens that do the same things. Imo #744 should be a bridge between #498 and this.

**Comment by abdulwd** [comment]
This is the screen which the user will see whenever a new tab is opened so that he can just open the offline book and start reading right away. IMO this screen should be left as it is or at least we should provide a way to the user using which he/she can open the offline books easily.
#744 is only shown on the first-time launch so should I change #744 to look more like #498 and should I include suggested books there?

**Comment by mhutti1** [comment]
Ah ok. I see. I still think there is a lot of shared functionality. We should discuss this next call to come up with a common approach to minimise duplication. I think #744 should definitely link with #498 with regards to that. In regards to what to open on new tab I think that is another issue as well that needs to be thought out.

**Comment by abdulwd** [comment]
Closed via #761
