### ISSUE TITLE
Create new initial landing screen

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#744]
On first landing a dismissable card is shown which shows the
instructions to download new books, this is the recommended way to show empty [states
according to Material Guidelines](https://material.io/design/communication/empty-states.html#content). We can choose some ZIM files which
will be shown on the first launch as recommended books and the user can download those
books from the initial landing screen. After the user has downloaded his/her first book, the user
knows how to download more offline books. So, the list of offline books will be shown on the
home screen categorized on the basis of language (See #743)

![image](https://user-images.githubusercontent.com/20206262/40385378-06add852-5e24-11e8-9bde-5323694ff08c.png)

**Comment by brijeshshah13** [comment]
@abdulwd I think as it is the landing screen, the option to cancel that tab should not be available, hence showing the tab number should not be displayed.

**Comment by abdulwd** [comment]
@brijeshshah13 This screen has to be shown only on the first launch. We do have tab numbering in Google Chrome even if it's the first launch, I don't think it will be a problem as the UI is quite intuitive.

**Comment by brijeshshah13** [comment]
@abdulwd I agree. But they want to give user the option to clear all the tabs and display an empty screen with options, do we?

**Comment by abdulwd** [comment]
@brijeshshah13 Yes, we do.

**Comment by abdulwd** [comment]
Closed via #761
