### ISSUE TITLE
Refactor bottom toolbar

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#745]
The bottom toolbar has to be refactored to make it more user-friendly.

![image](https://user-images.githubusercontent.com/20206262/40385838-8896a578-5e25-11e8-9fea-00bfc82872c7.png)

This is just a mock-up final design has to be discussed with @mhutti1 and @rashiq.
Should we include a button for the table of contents like the Wikipedia app does?

**Comment by mhutti1** [comment]
I think having a button for table of contents might be a good idea.

**Comment by brijeshshah13** [comment]
@mhutti1 @abdulwd I agree, because its almost accidentally that the user can know about a right navigation drawer containing the table of contents.

**Comment by abdulwd** [comment]
@mhutti1 Which of these should we keep for night mode and day mode?
![image](https://user-images.githubusercontent.com/20206262/41367910-030a7ee4-6f5e-11e8-90fe-c3b0711102bf.png)
![image](https://user-images.githubusercontent.com/20206262/41367920-074cf180-6f5e-11e8-8b04-e418d1a3fa33.png)
![image](https://user-images.githubusercontent.com/20206262/41367926-0a98a8f2-6f5e-11e8-92b2-39046edcfad6.png)

**Comment by mhutti1** [comment]
Can we try black in day mode? Also what would position it as such

bookmark < home > contents?

**Comment by abdulwd** [comment]
@mhutti1 We generally do have a home button at the center. I don't think people generally use bookmarks at the center, IMO we should keep home in the center. So which of the 4 pictures we should implement and in which modes(night/day)?
![image](https://user-images.githubusercontent.com/20206262/41381892-4b9cd412-6f87-11e8-9155-774bc28c3762.png)

**Comment by mhutti1** [comment]
@abdulwd I am confused I didn't suggest moving bookmarks to the center? I suggested moving it to the far left.

**Comment by abdulwd** [comment]
@mhutti1 Sorry for misinterpreting it. So the ordering will be:
bookmark | back arrow | forward arrow | home | toc
Any change in color scheme?

**Comment by mhutti1** [comment]
See the pr

**Comment by abdulwd** [comment]
Closed via #763
