### ISSUE TITLE
Files can't download on first run

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#747]
### Environment
  * version of the software you use : master
  * device / operating system : 8.0 Emulator
  
### The Bug:

On first run files don't download.

#### Steps to reproduce:

  1. Install
  2. Attempt to download

### Other Comments:

I think this is an issue with leak canary

**Comment by kelson42** [comment]
@mhutti1 I think I can confirm that bug, somehow the book stays in the "online" tab... I need to reclick on it to finally say it in the "downloading" tab.
