### ISSUE TITLE
Content Management Tweaks

### ISSUE THREAD

**Issue by ISNIT0** [kiwix/kiwix-android#75]
As Discussed:
- Rename "Device" to "Downloaded"
- Move "Downloads" into "Downloaded" panel
- When a download is initiated, move the user to "Downloads"

**Comment by mhutti1** [comment]
Well currently we have 3 fragments in our content manger activity. This entails merging 2 along with their UIs

**Comment by srv-twry** [comment]
If i understood it correctly , Inside ```ZimManageActivity``` we have three fragments i.e. ```ZimFileSelectFragment```(Device), ```LibraryFragment```(Online) and ```DownloadFragment```(Downloading).

I have to rename "Device" to "Downloaded" and merge the ```ZimFileSelectFragment``` and ```DownloadFragment``` into one. Also have to redirect to the merged fragment after download starts. Right ?

**Comment by mhutti1** [comment]
Yes that is the intended outcome. But the UI split between Downloading and Downloaded Items needs to be intuitive.

**Comment by kelson42** [comment]
Duplicate of #716
