### ISSUE TITLE
Does not open articles with special characters

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#760]
Tested on Wikivoyage Europe (latest zim 2018-06-10) and Kiwix-Android 2.4 Build 1180980:

When searching for an article I can not open those with special characters (Saint-Lô, Zürich, Korčula): they are found in search, even without typing ô, ü or č, but clicking/tapping the name in the search list will return to the previously opened article.

**Comment by kelson42** [comment]
@mhutti1 I confirm this regression with http://mirror.download.kiwix.org/zim/wikivoyage/wikivoyage_en_europe_2018-06.zim :(

**Comment by mhutti1** [comment]
Seems to be related to https://github.com/kiwix/kiwix-android/pull/594/files

**Comment by mhutti1** [comment]
Root cause is #765 but I am  going to implement a quick fix here.

**Comment by Popolechien** [comment]
Ok FWIW it doesn't work with Chinese characters either.

**Comment by kelson42** [comment]
@mhutti1 I do not think you have do to so because (1) This was working fine, we have a regression here (2) kiwix-serve works that way too, and it works fine

**Comment by mhutti1** [comment]
@kelson42 Ok I have come up with a fix that should work but we should implement #765 for 3.0

**Comment by kelson42** [comment]
@mhutti1 thx, yes we should use urls instead of titles
