### ISSUE TITLE
Opening file from file browser put filename in search

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#762]
### Environment
  * version of the software you use : last nightly
  * device / operating system : Android 6 on Samsung Galaxy tab
  
#### Steps to reproduce:

  1. Open a file browser
  2. Click on a ZIM file
  3. Choose Kiwix
  4. Kiwix starts

But:
1 - The focus is on the search bar and the search bar is filled with the filename
2 - The ZIM home page does not display (but the correct ZIM seems to be loaded)

I want;
1 - The ZIM home page displayed
2 - Search bar empty (but maybe with the focus)

**Comment by mhutti1** [comment]
I thought I fixed this in #738

**Comment by mhutti1** [comment]
@kelson42 Just tried on Galaxy Tab 6.0.1 on bitbar and can't produce with latest nightly.

**Comment by mhutti1** [comment]
@kelson42 if you have this issue still reopen.
