### ISSUE TITLE
Create language selection screen

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#764]
Presently, a dialog box is shown which shows the list of languages but the dialog box is considerably small to show the long list of languages and it also makes searching for a language difficult so I have made a complete screen which makes the selection of languages for articles fast and easier. The list also shows the number of books in the particular language.

The cross icon will be replaced by checkmark icon to save the language preference and the cross icon will be added to the left of **Select languages** title.
![image](https://user-images.githubusercontent.com/20206262/41511008-5d0d9576-728c-11e8-9d32-a36dc418e741.png)

**Comment by abdulwd** [comment]
@mhutti1 Which color of the toolbar looks good in day mode? The same toolbar color will be implemented in all activities so we should choose wisely. IMO we should not go with white because then we have to change the tint of all the drawables programmatically every time when switching from day mode to night mode, resulting in more code.
In night mode the toolbar will remain black.

I have also made some tweaks to the UI so that it may be obvious to the user that the number next to the language represents the number of books.

![image](https://user-images.githubusercontent.com/20206262/41803131-97b97670-76a3-11e8-981f-80765c64dbcf.png)
![image](https://user-images.githubusercontent.com/20206262/41803139-b7e9e894-76a3-11e8-867c-2bcc6516cf65.png)
![image](https://user-images.githubusercontent.com/20206262/41803144-bac42782-76a3-11e8-80c2-0cabd9e67a2d.png)

**Comment by mhutti1** [comment]
I don't think this is a major issue as it can be changed with one line in the future. Do whichever you feel is best.

**Comment by abdulwd** [comment]
Closed via #774.
