### ISSUE TITLE
Convert search activity to use URLs not titles

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#765]
## Code Improvement

Convert the search activity to use URLs rather than titles to reference articles internally and in the saved recent search database.

**Comment by mhutti1** [comment]
This will require a database migration.

**Comment by Aditya-Sood** [comment]
@mhutti1 the recentSearch database has a zimID field which seems to contain dash separated hexadecimals. What does it refer to exactly? I couldn't figure that out

**Comment by mhutti1** [comment]
zimID is the id of the ZIM file every file should have a unique id. zimName doesn't change between content upgrades.

**Comment by Aditya-Sood** [comment]
So this issue is aimed at replacing the zim ID everywhere with the corresponding URL and then subsequently using that URL for identifying the zim file?

**Comment by mhutti1** [comment]
No its about the search activity not the content management activity.

**Comment by Aditya-Sood** [comment]
Discussion about integrating a possible fix for this issue is taking place at [kiwix-build/#354](https://github.com/kiwix/kiwix-build/issues/354)

**Comment by macgills** [comment]
@Aditya-Sood what is the state of this? Why does it need a kiwix-lib update?
```
 ZimContentProvider.searchSuggestions(query, 200);
            String suggestion;
            String suggestionUrl;
            List<String> alreadyAdded = new ArrayList<>();
            while ((suggestion = ZimContentProvider.getNextSuggestion()) != null) {
              suggestionUrl = ZimContentProvider.getPageUrlFromTitle(suggestion);
```
it seems like we already get all the data we need? Title/url of the suggestion and ZimContentProvider has the ZimId.
I feel like I am missing something here. This screen is also a prime candidate for unidirectional data flow and updating with a recyclerview

**Comment by Aditya-Sood** [comment]
There's an implementation of getNextSuggestion() in kiwix-lib which, along with a title, also returns the corresponding url ([link to function](https://github.com/kiwix/kiwix-lib/blob/master/src/reader.cpp#L814)). Using this implementation will help avoid the cost of an additional call at:
```
suggestionUrl = ZimContentProvider.getPageUrlFromTitle(suggestion);
```

That is what I am looking at until now. But I need to go through SearchActivity again because I think @mhutti1 is hinting at a more comprehensive overhaul of the activity.

**Comment by Aditya-Sood** [comment]
Before merging, the kiwix-android PR #1537 needs to be updated to use the kiwix-lib version number with the kiwix-lib PR [#289](https://github.com/kiwix/kiwix-lib/pull/289) merged to master
