### ISSUE TITLE
Create an activity to show history

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#773]
Selecting History from the options menu on the home screen will show this activity. Here the user can see the history of pages he/she has visited and can search his/her history of pages visited using the search icon. Upon long pressing any item a contextual menu will be shown to delete the items from history.
![image](https://user-images.githubusercontent.com/20206262/41797147-8d8fb47e-7686-11e8-99c5-7e0bd88ce4a4.png)

**Comment by abdulwd** [comment]
@mhutti1 Any suggestions?

**Comment by mhutti1** [comment]
I think some good additions might be a toggle to toggle global or currently open ZIM history.

**Comment by abdulwd** [comment]
Closed via #777.
