### ISSUE TITLE
UI Test History Activity

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#785]
Add UI Tests for the History Activity created under #777

**Comment by kelson42** [comment]
@siddharth2010 I'm really in favour of more automated testing... but this ticket seems stalled and nothing move forward. I'm not sure of the value of keeping it open, or do you plan to fix it?

**Comment by siddharth2010** [comment]
I agree @kelson42 , I was planning on adding some more tests after gsoc this year. I guess we should probably close this ticket. I will reopen it when I am back to testing!
