### ISSUE TITLE
UI issue in initial landing screen

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#797]
**Describe the bug**
- Opening the help activity and pressing back from the initial landing screen leads to the kiwix image (with the download books button) of the initial landing screen floating on top of the help activity.

**Expected behavior**

- Only the initial landing screen should appear

**Steps to reproduce the behavior:**
1. open the app (for the first time after installing the apk, so that it opens the intial landing screen)
2. Click on help from the overflow menu
3. press back

**Screenshots**

<img width="338" alt="sssssss" src="https://user-images.githubusercontent.com/32238400/42422880-fcae707e-830c-11e8-9089-aa448102e088.png">

**Environment**
- Version of Kiwix Android : 3.0
- Device : Samsung S6
- OS version : Android 7.0

**Comment by abdulwd** [comment]
@siddharth2010 Can you check #803 and see if it exists?

**Comment by siddharth2010** [comment]
@abdulwd sure, I will get right on it

**Comment by abdulwd** [comment]
Closed via #803.
