### ISSUE TITLE
Animations on the initial landing screen

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#799]
**Describe the bug**

- On scrolling down on the initial landing screen, the scroll down animation occurs below the kiwix dialog box.

**Expected behavior**

- The scrolling animation should occur on top of the screen below the action bar

**Steps to reproduce the behavior:**
1. open the app (for the first time after installing the apk, so that it opens the intial landing screen)
2. try to scroll down on the space below the kiwix image

**Screenshots**

<img width="342" alt="qwe" src="https://user-images.githubusercontent.com/32238400/42422992-9abd6d9a-830f-11e8-8a16-877f72373cf6.png">

**Environment**
- Version of Kiwix Android : 3.0
- Device : Samsung S6
- OS version : Android 7.0

**Comment by abdulwd** [comment]
@siddharth2010 I don't think it's an issue, the banner remains stationary and there's a recycler view below it. So the animation will always be below the banner. Also, most of the time there will be ZIM files present below the banner.
@mhutti1 I would like to have your opinions on this.

**Comment by siddharth2010** [comment]
oh yes, @abdulwd , It just slipped my mind. The recycler view is below the banner, which is stationary. So yes, its not an issue..

**Comment by abdulwd** [comment]
So I'm closing this for now.

**Comment by mhutti1** [comment]
Not important
