### ISSUE TITLE
Index not synced with article

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#8]
Sometimes, especially with many open tabs open and after closing one or more of them, I noticed that the index is incorrect for at least one open article. It looks as if the index is somehow not updated about the closed tabs. So the array of article-names-in-open-tabs differs from the array of article-names-in-index. 

tested with 2.1

![17746_2 0_stale_menu_122_72lo](https://cloud.githubusercontent.com/assets/1029718/23142573/f88a84ec-f7bc-11e6-9a86-39374c8e1a7a.jpg)

**Comment by mhutti1** [comment]
@kelson42 I am struggling to reproduce. Has this been fixed?

**Comment by kelson42** [comment]
@mhutti1 I will try to reproduce it with 2.2

**Comment by kelson42** [comment]
I will close that ticket as it looks quite hard to reproduce and nobody else has complained about that. The bug can anytime be reopen if we have a reprocase.
