### ISSUE TITLE
Fix ZIM file part code

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#801]
**Describe the bug**
There are a few issues with how we use .part and .part.part that can result in partially downloaded files not working correctly. These need to be fixed. One specific issue is the conflict between the current .part.part and .part and the original .part. I think we should use .part-part or similar to know which version is being used.

**Comment by kelson42** [comment]
@mhutti1 "part" files are temporary during the download I thinks? To me it is not a priority to provide people a Kiwix upgrade path which works smoothly during a download. The download problems I experience are not related to this and seems to me worse in a sense that they impact downloads started with 2.4.

**Comment by mhutti1** [comment]
They are related to this though. When the service restarts it currently looks for a .part. It should look for either .part or .part.part (should be renamed)
