### ISSUE TITLE
Add Idling Resources for Testing purposes

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#806]
Currently the **LanguageActivityTest** is is using the **BaristaSleepInteractions.sleep** method to wait for the network call to finish. This is not recommended as adding artificial delays to the tests makes it longer for the test suite to finish and the test can fail in conditions of low internet connectivity.

So we need to add the CountingIdlingResource to the LanguageActivity so that instead of the adding artificial delays, we can wait for the network call to finish.

**Comment by abdulwd** [comment]
@siddharth2010 I have fixed this in #803.

**Comment by siddharth2010** [comment]
@abdulwd sure then. I will close the pr #807

**Comment by abdulwd** [comment]
Closed via #803.
