### ISSUE TITLE
Add a "selected languages" list in the Language Activity in 3.0

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#809]
**Is your feature request related to a problem? Please describe.**

It was a problem to scroll through the whole list of languages to find out the ones you have selected, and to unselect them. 

**Describe the solution you'd like**

Display the list of selected languages in the beginning. It would give the user a birds eye view of the selected languages

**Additional context**
Heres the current screen:
<img width="338" alt="screen" src="https://user-images.githubusercontent.com/32238400/42839909-cc6deb7a-8a22-11e8-8403-8ed18f791a48.png">

and heres what I propose:
<img width="339" alt="new screen" src="https://user-images.githubusercontent.com/32238400/42839912-cffb97b0-8a22-11e8-9a95-e3a8ab06f79d.png">

**Comment by abdulwd** [comment]
Closed via #839.
