### ISSUE TITLE
Missing zim files in remote library

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#821]
When looking for content on Android I can only see the full (4.8Gb) Wikimed file: the nopic, novid and nodet versions are not to be seen.

PhET is also absent, and so are each and every StackExchange zim files.

**Comment by Popolechien** [comment]
German Wikipedia is also missing.

**Comment by kelson42** [comment]
Phets are in the library_zim.xml https://ftp.nluug.nl/pub/kiwix/library/library_zim.xml. Same for the 3 wikipedia_en_medicine versions

**Comment by mhutti1** [comment]
@kelson42 could this be an issue with the old library list?

**Comment by kelson42** [comment]
@mhutti1 yes, but Kiwix-Android 2.4 looks to https://download.kiwix.org/library/library_zim.xml !? I have checked on my device and I can see both last version of phets & Wikipedia in German! I can not confirm that bug.

**Comment by Popolechien** [comment]
I'm with 2.2 build 53. Uninstalled and reinstalled as trying to access library crashed the app. Confirm I still cannot see PhET. As a matter of fact, it now crashes rather systematically when I have files stored, and can't seem to find the content of the remote library (which I guess makes it a separate issue).

**Comment by kelson42** [comment]
@Popolechien Forget about 2.2, 2.4 is the last one.

**Comment by kelson42** [comment]
This bug is not reproduceable and the whole library mgmt has been strongly rewritten in 2.5. I will close the ticket.

**Comment by macgills** [comment]
>  every StackExchange zim files.

Those are still filtered out because of some bug? I just ported existing functionality

**Comment by kelson42** [comment]
@macgills Yes, there is a specific issue for that.
