### ISSUE TITLE
Export bookmarks feature

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#822]
A gentleman from Australia wrote to say that upon reinstall he'd lost all of his bookmarks. Maybe find a way to export it?

**Comment by Popolechien** [comment]
Be my guest.

**Comment by Aditya-Sood** [comment]
Thanks

**Comment by kelson42** [comment]
To me this is a function which has to be done in the kiwix-lib because:
* This is a common feature for all readres
* We want to have the file reusable on different systems

**Comment by kelson42** [comment]
See https://github.com/kiwix/libkiwix/issues/840

**Comment by kelson42** [comment]
@MohitMaliFtechiz Once #3109 is implemented, can you please implement quickly that one?
