### ISSUE TITLE
Empty storage device list

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#831]
Kiwix has a settings to choose where to save the content. I allows to choose in a list the storage devices. This list is empty for me.

My device as an SD card (available at /storage/9724-C9BE), so I should see two entries:
* Internal
* External
This was working fine with 2.2

**Steps to reproduce the behavior:**
1. Install Kiwix
2. Launch Kiwix
3. Go to the library and authorize the access to the filesystem
4. Leave the library and to go to the settings
5. Go the the storage settings and click on it

![screenshot](https://user-images.githubusercontent.com/1029718/43677861-834ed43c-9809-11e8-8c2a-28ad2bb8bf10.png)

**Environment**
- Version of Kiwix Android : 6.0.1
- Device : Galaxy Tab S (SM-T700)

**Logs**
Here is the logcat corresponding to the steps:
[logcat.txt](https://github.com/kiwix/kiwix-android/files/2259560/logcat.txt)

**Comment by mhutti1** [comment]
Can't reproduce on bitbar. @kelson42 can you add the path manually?

**Comment by kelson42** [comment]
@macgills Do you think we could close that ticket with 3.0? This was with the same tablet like yours?

**Comment by macgills** [comment]
This ticket is "Retrieving a list of writable storages is failing" and is a much more general issue. I wasn't intending a massive overhaul of storage detection as part of my work on replacing the downloads and moving the storage location

**Comment by kelson42** [comment]
@macgills This is an old ticket, even maybe outdated... and this was on my tablet (like yours), so I will close the ticket for now (I can not reproduce it anymore).
