### ISSUE TITLE
Kiwix 2.4 Build 1182160 randomly changes UI language

### ISSUE THREAD

**Issue by uwemock** [kiwix/kiwix-android#834]
This bug cannot be reproduced reliably.

At some stage, Kiwix switches to english UI while my device is set to German.

Deleting the app data will make Kiwix switch back to the device language.

**Comment by macgills** [comment]
```  public static void handleLocaleChange(Context context, String language) {

    Locale locale = new Locale(language);
    Locale.setDefault(locale);
    Configuration config = new Configuration();
    if (Build.VERSION.SDK_INT >= 17) {
      config.setLocale(locale);
      config.setLayoutDirection(locale);
    } else {
      config.locale = locale;
    }
    context.getResources()
        .updateConfiguration(config, context.getResources().getDisplayMetrics());
  }```
This is the only thing I can think of that could be causing this?
This code is unappealing to me anyway and I would move to delete it, we should not set the default locale. If a user wants to change their language they will do it on the device.

**Comment by kelson42** [comment]
@macgills I'm not sure about what you mean? Does that implies any change in term of feature?

**Comment by macgills** [comment]
We offer a feature to allow people to change the language of the app in-app. I think that is very misguided and we should just allow android's already existing feature of changing your device's language to function as it does.
Unless there is a very good requirement for keeping it I think it is a bad feature and should be deleted.

**Comment by kelson42** [comment]
@uwemock Have you been able to experience that problem recently with the 3.1 version of Kiwix Android?

**Comment by kelson42** [comment]
@macgills I’m not sure we can do anything here. #1738 should nail down the problem around this.

**Comment by macgills** [comment]
@kelson42 agreed, closing as duplicate
