### ISSUE TITLE
Missing strings on translatewiki

### ISSUE THREAD

**Issue by asereze** [kiwix/kiwix-android#838]
In the new 2.4 version there are a few strings in the settings menu that are not available for translation on translatewiki, and so I get them in English no matter what language I've been using:

"History"
"Extras"
"External" (in the "Memory" section)
"Enable bottom toolbar"
"Display a toolbar with quick actions at the bottom of the screen"
"Warn when entering external links"
"Display popup to warn about additional costs or not working in offline links."
"medium", "large" and "small" (under "Zoom level")

**Comment by mhutti1** [comment]
@kelson42 are we still using a manual script for this?

**Comment by kelson42** [comment]
@kelson, Yes I should make a sync.

**Comment by kelson42** [comment]
@macgills Now that it looks like we have a workflow to sync almost automatically both ways with Translatewiki, what about that ticket?

**Comment by macgills** [comment]
@kelson42 there is some ticket for us to clarify ambiguous strings on translatewiki? I would say that that supersedes this ticket and we can close this

**Comment by kelson42** [comment]
@macgills Good to me if you can really secure that afterward we would have proper translations (if done on TW) for strings listed above.

**Comment by macgills** [comment]
I confirm the strings in this issue now have translations
