### ISSUE TITLE
Search is not working on the latest Kiwix for Android with the latest Italian Wikipedia or Wikipedia Medicine. Other Italian .zim files from the Repository work correctly

### ISSUE THREAD

**Issue by andreapaolini** [kiwix/kiwix-android#840]
**Describe the bug**

**Expected behavior**

**Steps to reproduce the behavior:**
1. 

**Screenshots**

**Environment**
- Version of Kiwix Android : 
- Device : 
- OS version : 

**Logs**

**Comment by kelson42** [comment]
@andreapaolini Hmmm... we need the details?

**Comment by kelson42** [comment]
No details
