### ISSUE TITLE
"Search in page" text does not disappear when people type their search in top bar

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#841]
A gentleman raised this point today : when he was looking for text in the page (clicking on the magnifying glass on top) the "find in page" text does not disappear (see image). 
I would also add that if one use "find in page" in the options menu, then one has two little arrows only, which is a lot more convenient.
![2018813_93957241](https://user-images.githubusercontent.com/21675885/44147622-15022c92-a095-11e8-9b31-469d87ad976c.jpg)

**Comment by ritik2017** [comment]
Working on it

**Comment by kelson42** [comment]
@ritik2017 Thx.

**Comment by ritik2017** [comment]
@kelson42 how do i join the slack channel

**Comment by Popolechien** [comment]
@ritik2017 The easiest is via your web browser [chat.kiwix.org](http://chat.kiwix.org)

**Comment by Popolechien** [comment]
@ritik2017 I can send you an invite but tbh it's not super active, people here are more the irc type (http://chat.kiwix.org)

**Comment by ritik2017** [comment]
okay got it.. can i get an invite to the slack community

**Comment by Popolechien** [comment]
Sure. Send your email address to info@kiwix.org

**Comment by kelson42** [comment]
@ritik2017 has fixed that problem.
