### ISSUE TITLE
Cannot add german wikipedia

### ISSUE THREAD

**Issue by jeyca** [kiwix/kiwix-android#844]
This might be similar to #821, I installed Kiwix 2.2 47 on android phone (LineageOS 14.1) but cannot add german wikipedia. First I tried to find it within the app, but in Get Content->Online there were just a few downloads at all. Could not find the german wikipedia. I then downloaded it via the wiki Torrent

https://wiki.kiwix.org/wiki/Content_in_all_languages
`wikipedia (Deutsch) | de | 11G | 2018-05 | all nopic`

But now in `Kiwix->Get content->Device` it is not found after "scanning for downloadable content". I even do not understand this, where is it scanning for downloadable content? Why can't I choose just downloaded files in my filesystem? I even put the zim file to `/sdcard/kiwix` where the other wikis are located I could download from Get content->Online. But still, it does not show up.

**Comment by mhutti1** [comment]
You should be able to open the ZIM file directly from most file browsers. One issue users face is that the SD card might be formatted to only allow 4GB files to be used. In terms of seeing files it might have been a language issue. You can select more languages in the top right or search for what exactly you want.

**Comment by kelson42** [comment]
@jeyca We need you to update to 2.4 and let us know if the problem still occurs with this version.

**Comment by kelson42** [comment]
No feedback from the user. Being unable to reproduce the problem, there is nothing more we can do.
