### ISSUE TITLE
Kiwix crashes on Android 6

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#849]
The gentleman attached his log:
´´´
--------- beginning of main
08-23 16:50:07.789 25563 25563 D kiwix   : Initializing TextToSpeech
08-23 16:50:07.854 25563 25563 D kiwix   : Kiwix normal start, zimFile loaded last time -> Open last used zimFile /storage/F582-1110/Kiwix/wikipedia_de_all_nopic_2017-01.zimaa
08-23 16:50:07.855 25563 25563 I kiwix   : Attempting to create reader with: /storage/F582-1110/Kiwix/wikipedia_de_all_nopic_2017-01.zimaa
08-23 16:50:09.315 25563 25563 I kiwix   : Opening ZIM file /storage/F582-1110/Kiwix/wikipedia_de_all_nopic_2017-01.zimaa
08-23 16:50:09.620 25563 25563 W kiwix   : Kiwix shared preferences corrupted
08-23 16:50:09.620 25563 25563 W kiwix   : java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
08-23 16:50:09.620 25563 25563 W kiwix   : 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at java.util.ArrayList.get(ArrayList.java:308)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at org.kiwix.kiwixmobile.KiwixMobileActivity.selectTab(KiwixMobileActivity.java:826)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at org.kiwix.kiwixmobile.KiwixMobileActivity.restoreTabStates(KiwixMobileActivity.java:1761)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at org.kiwix.kiwixmobile.KiwixMobileActivity.manageExternalLaunchAndRestoringViewState(KiwixMobileActivity.java:1788)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at org.kiwix.kiwixmobile.KiwixMobileActivity.onCreate(KiwixMobileActivity.java:462)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at android.app.Activity.performCreate(Activity.java:6285)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at android.app.ActivityThread.access$900(ActivityThread.java:150)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at android.os.Looper.loop(Looper.java:148)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at android.app.ActivityThread.main(ActivityThread.java:5417)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at java.lang.reflect.Method.invoke(Native Method)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-23 16:50:09.620 25563 25563 W kiwix   : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
--------- beginning of crash

**Comment by mhutti1** [comment]
I would try wiping app data/reinstalling. It says the shared preferences have been corrupted.

**Comment by Popolechien** [comment]
It worked apparently, thanks.
