### ISSUE TITLE
Onboarding mockups

### ISSUE THREAD

**Issue by ISNIT0** [kiwix/kiwix-android#85]
https://www.figma.com/file/aloDDgh0zCRTtRYwURNdXdU6/KIWIX

**Comment by EladKeyshawn** [comment]
elad.keyshawn@gmail.com

**Comment by ISNIT0** [comment]
![kiwix logo white](https://cloud.githubusercontent.com/assets/5173131/24791468/17efc3be-1b72-11e7-83d1-833503d3e0be.png)

**Comment by ISNIT0** [comment]
[Archive.zip](https://github.com/kiwix/kiwix-android/files/904932/Archive.zip)

**Comment by abdulwd** [comment]
@ISNIT0 @kelson42 @EladKeyshawn If anything has to be done further in this issue, please reopen it. :)
Closed via #754.
