### ISSUE TITLE
Read adaptive icon

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#852]
Readd adaptive icon removed by https://github.com/kiwix/kiwix-android/pull/851

**Comment by mhutti1** [comment]
The reason this was removed was to fix custom apps using this. We would need to come up with a solution for custom apps.

**Comment by abdulwd** [comment]
@mhutti1 I think we can use [this](https://stackoverflow.com/a/22876224/7792129) for adding the icons to different build types or do we need to create the icons for custom apps?

**Comment by kelson42** [comment]
@macgills Anything new regarding that ticket.

**Comment by macgills** [comment]
I have nothing to report, I'll worry about icons when I can actually upload custom apps to the play store

**Comment by macgills** [comment]
>I'll worry about icons when I can actually upload custom apps to the play store

That turned out to be a bit of a lie, I am now interested in icon generation. Programmatically creating an adaptive icon will be difficult, doing it with the conventional way with the tools of android studio doesn't work, see:
![image](https://user-images.githubusercontent.com/3358282/68398395-8e141d00-016c-11ea-9a85-11e0e75e6195.png)
which produces these assets:

**Comment by macgills** [comment]
An example of what an adaptive icon should look like during this process: https://dev.to/sfarias051/how-to-create-adaptive-icons-for-android-using-android-studio-459h

The flow of custom app icon generation is
1. Use a [script](https://github.com/kiwix/kiwix-android-custom/blob/master/gen-std-icon.py) to create a 512*512 icon. Given a file or url of the original icon it pastes it onto a white background and adds the "offline" and "flag" icons
2. Resize this icon using another [script](https://github.com/kiwix/kiwix-android-custom/blob/master/gen-custom-android-directory.py
) for the various densities. This actually creates 2 icon set, one the app icon, one the widget icon, they are identical.

What we want from step 1 is  for there to be 2 outputs, the original and one without background but keep the flag/offline "stamping", possibly centering them so their placement makes sense across the variety of icons. If all the backgrounds of our app icons are to be white then that is fine, changing the icon background is more work if we need to meet that requirement.
Then step 2 needs to be augmented to generate all the appropriate icons eg foreground/round.

Or we take the output of step 1 and feed it into Android Asset Studio. That to me seems a lot simpler

**Comment by kelson42** [comment]
@macgills Do I understand properly:
* We use adaptive icon(s) already for Kiwix app? 
* The problem is how to get that icons for custom apps?

**Comment by macgills** [comment]
We do not use adaptive icons in the kiwix app because it would default to the kiwix icon (on certain api levels) for custom apps.

The prolem with not using adaptive icons is that our apps' launcher icon looks ugly compared to other apps.

**Comment by kelson42** [comment]
@macgills Thx for the answer. Why not extending https://github.com/kiwix/kiwix-android-custom/blob/master/gen-std-icon.py which is our solution to generate custom app icons to be able to generate all the flavours of bitmaps we need for the adaptive icons?

**Comment by macgills** [comment]
Because a) generating new icons is rare and b) in constant flux as google changes how icons work every other release.
The automation effort is probably not in step with the gain as we have to maintain this tool

**Comment by kelson42** [comment]
@rgaudin Do you see anything complicated to achieve here in Python in what @macgills has described?

**Comment by rgaudin** [comment]
Just discovered Adaptive icons so I may have missed something but my understanding is that we could fix the script to:

* Enforce a solid background color: white probably. It's already kinda the case as it helps us not to worry about how our flags would appear.
* Keep generating the previous version as it is (believe it's OK, right?).
* Generate a foreground PNG that fills the 36dp diameter of the safe zone, including the flags. This would require some testing.

I think @macgills concern is whether this effort is worth it compared to just pasting it in Android Assets Studio for each.

**Comment by macgills** [comment]
@rgaudin yes we talked about this on the call yesterday.
I will be modifying the script to produce a backgroundless icon and do the import in android studio to create the icons and will request your review on that PR
