### ISSUE TITLE
Cannot read zim file from external drive

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#853]
From OTRS feedback system - let me know if I should ask for more details:
"Downloaded 20GB English no pictures words to a 32GB flash drive. Can use this with tablets and PC, but latest version of Kiwix on Android 7.0 Moto 5gplus days file is large and spins apparently trying to maybe copy the Zim file to local storage? See screenshot"
![attachment](https://user-images.githubusercontent.com/21675885/44770842-9a184e00-ab69-11e8-9775-82862218c7a2.png)

**Comment by mhutti1** [comment]
If it doesn't let them open this then they might need to split it. I don't know if there is anything we can do.

**Comment by Popolechien** [comment]
Ok thanks.
