### ISSUE TITLE
Can't read files from ext. drive

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#855]
Copying feedback from user

"Can't read 360MB simple English Wikipedia (or any ZIM) from fat32 thumb drive with OTG cable. Android 7.0 and moto5gplus. This is an update to an earlier bug report.
Version 2.4 build 183160
Moto5gplus Android 7.0

I normally use this version of Kiwix with the 360mb simple wiki stored on my MicroSD card in  Works great. Also use schools version 2.6gb no problem. I decided to try using my thumb drive with an OTG cable. Kiwix just can't see the drive. As a test I loaded up some 300mb PDF files on the thumb drive and was able to see and open them with standard Adobe Reader. Different app of course, but I was just testing basic hardware functionality."

**Comment by kelson42** [comment]
Yes, we do not support OTG, it might or might not work.

**Comment by vb0** [comment]
Hello @kelson42 , all, is there a more recent issue treating this use case? Now all flagship phones except Sony's now have no microSDs; also on kiwix.org "flash drive" are the first listed in the examples for storage and "mobile phones" for devices - how is the use of both together is just not supported?  

I do understand the technical challenges and Android's war against storage in general but there should be at least a feature request tracking this very important (I'd say critical nowadays) use case.
