### ISSUE TITLE
APK size improvements

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#86]
We need to look at reducing apk size by:

- Using proguard
- <s>Utilising architecture specific apks</s>
- Reducing size of libkiwix by fixing bugs in that.
- Looking at possibility of using icu provided by android 24?

**Comment by kelson42** [comment]
@mhutti1 I think we have already done a lot here
- Using proguard (what is the status on that?)
- Utilising architecture specific apks (done)
- Reducing size of libkiwix by fixing bugs in that. (I do not understand what is meant?)
- Looking at possibility of using icu provided by android 24? (This would be really complicated... and that to win something like 2-3 MB... IMO far to much work and risk for a really quick win)

**Comment by okkebal** [comment]
"We need to look at reducing apk size"

Why?  Did anyone complain about this? People have to download Zim files that re many Gb's in size and you guys worry about a 15 Mb APK??   What is going on here?

**Comment by mhutti1** [comment]
Its generally a good idea to keep APK size down. Some ZIM files are only 10's of MB so this could impact people.

**Comment by kelson42** [comment]
@okkebal that said this is not (anymore) the TOP priority. APK distributed with Google Play are now architecture specific, and have meanwhile an acceptable size IMO.

**Comment by kelson42** [comment]
I don't think we can really do more here. Closing the ticket.
