### ISSUE TITLE
Find in page function not performing on collapsed sections

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#863]
When looking for a word in page in a wiki zim, no results will be returned if the section with the target word is collapsed: one has to expand all sections in order for the search to function correctly (see images).
![screenshot_20180919-125543](https://user-images.githubusercontent.com/21675885/45749422-ec4e0b80-bc0b-11e8-81eb-ef87b89e0daa.jpg)
![screenshot_20180919-125530](https://user-images.githubusercontent.com/21675885/45749423-ec4e0b80-bc0b-11e8-9caf-f978da2eea1f.jpg)

**Comment by mhutti1** [comment]
@ritik2017 We can't assign you on GitHub until you contribute a patch but consider yourself assigned.

**Comment by ritik2017** [comment]
Thanks @mhutti1 working to resolve the issue

**Comment by ritik2017** [comment]
I had some doubts regarding the code I searched for the dropdown and found that its actually a dynamic dropdown which loads from a url 
I found a function getCurrentWebView() which i think returns the view and by default all dropdowns are collapsed?? 
Am i going right?? @mhutti1  Is this the place of code from where i can open the collapsed icons??
![capture](https://user-images.githubusercontent.com/33036254/52173536-83c38d80-27ac-11e9-9b23-fc57db73e1e2.PNG)
![capture2](https://user-images.githubusercontent.com/33036254/52173538-88884180-27ac-11e9-84bf-670df52a7476.PNG)

**Comment by mhutti1** [comment]
@ritik2017 The code you have linked is for the side bar not for the searching in the page. I am almost certain the subtext isn't loaded dynamically. The main problem is how to display the user a consistent search. I think the easiest way might be to expand everything when the user attempts to find in page. Everything else might be challenging/ require some weird javascript magic.

**Comment by ritik2017** [comment]
Thanks @mhutti1 for the help i got this now
I am expanding the collapsed sections so that all the strings that match gets displayed

**Comment by ritik2017** [comment]
@mhutti1 @soloturn 
Sorry i was unable to find the snippet of code from where i can expand the collapsed section 
can you please help me out??

**Comment by mhutti1** [comment]
@ritik2017 Yeah its a bit complicated. You will likely have to inject some javascript into the webview to do it.

**Comment by kelson42** [comment]
I don't think this bug is really solvable as long as the ZIM does not provide a proper JS API to handle/instrument section collapsing from the apo.

**Comment by kelson42** [comment]
@MohitMaliFtechiz We have this very old bug report. To me there is basically nothing we can really do about that as the builtin function works that way. Domyou see things differently?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 The first point of your comment is true, the webview only finds text that is showing on the screen, and when the section is collapsed it does not search the words inside it. But to resolve this issue we can programmatically open the section(with the help of custom js) when we try to find it on the page so that all the relevant words can be searched. This is the only solution I am seeing.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Yes, but that would create visual glitches to open in js the sections. In addition, we will stop probably to have collapsable sections in Wikipedia which makes this requests less important. I will just close as WONTFIX
