### ISSUE TITLE
some Latex based formulas not shown on Kiwix Android APK 3.3.0/3.2.1

### ISSUE THREAD

**Issue by florian29** [kiwix/kiwix-android#864]
**Describe the bug**
All latex based formulas are very much smaller than the main text and therefore difficult to read. Some formulas are completely missing.

**Expected behavior**
Latex based formulas should have the same text size as the main text and every formula or symbol should appear.

**Steps to reproduce the behavior:**
open article "Satz des Pythagoras" of wikipedia_de_all_novid_2018-06.zim, you will notice that some formulas or symbols doesn't appear, the rest which appears is to small

**Screenshots**
![wikipedia_de_all_novid_2018-06](https://user-images.githubusercontent.com/43439672/45813970-621daa00-bcd4-11e8-882a-23919caa295d.png)

**Environment**
- Version of Kiwix Android : 2.4

**Comment by mhutti1** [comment]
It is working fine on my Galaxy S8 with 8.0 so I suspect this might be a Webview / Device bug. We might be able to workaround somehow though.

**Comment by florian29** [comment]
indeed the ZIM file is okay, it works fine on the alpha3 version for windows, the problem must be with the android kiwix apk version 2.4 (same issue with 2.3), I've tested it with Andy Android emulator and not a physical device, I will test it now on my Galaxy S4 mini and report you, by the way it worked well with Andy with kiwix apk 2.2 with an older version of the ZIM file, but the newer ZIM files doesn't open anymore with the version 2.2

**Comment by kelson42** [comment]
@florian29 older ZIM files had PNG files for equations. That might be the explanation why it was displaying properly.

**Comment by florian29** [comment]
Finally I was able to test it with my Galaxy S4 mini and, like @mhutti1 commented, the article "Satz des Pythagoras" works fine (kiwix 2.4 apk from Google Play). But then I tested it opening "Maxwell-Gleichungen" (wikipedia_de_all_novid_2018-06.zim) and there is the same issue as you can see in the screenshot:
![screenshot_2018-09-28-21-38-51](https://user-images.githubusercontent.com/43439672/46230211-2fc11c00-c368-11e8-96ac-24cc91c77096.png)

The same issue appears in a lot of articles with formulas and not only in the german wikipedia, but also in the spanish one. By the way: The kiwix app crashes very often, it was really difficult to open the file.

**Comment by kelson42** [comment]
I plan to close that ticket. The problem seems to be that that older versions of Android do not support SVG looks like. Nobody with a more or less recent device seems to be impacted.

**Comment by florian29** [comment]
I post you here a screenshot of the same article (Maxwell-Gleichungen) as above, with the same device (Galaxy S4 mini) but this time with the OLD version of the Kiwix Android apk (ver. 2.2) and the OLD zim file (wikipedia_de_all_2017-06.zim). As you can see everything worked pretty well and the pictures were SVG files too. The problem started with the new Kiwix Anroid apk ver. 2.4, which is necessary to open the newer ZIM files. The same issue occurs when opening the older ZIM files with the new 2.4 Kiwix apk. The problem is not the ZIM file, it is indeed an issue of the new Kiwix Android apk.
![screenshot_2018-09-29-14-25-23](https://user-images.githubusercontent.com/43439672/46245814-7a887580-c3f4-11e8-8d5d-48a5aac61983.png)

**Comment by florian29** [comment]
> 
> 
@kelson42 
> I plan to close that ticket. The problem seems to be that that older versions of Android do not support SVG looks like. Nobody with a more or less recent device seems to be impacted.

If you want to quit the support for older versions of Android, you will have to announce it to Google Play Store.
![sin titulo](https://user-images.githubusercontent.com/43439672/46257767-5a71b880-c4bf-11e8-864c-16a09c9e48ce.png)

**Comment by mhutti1** [comment]
Ok. Thanks for the reproduction steps. I think we should look into this and work out why the images are not loading correctly.

**Comment by florian29** [comment]
@mhutti1 Thank you for answering. If I can help something, please let me know. Maybe the issue occurs on how the android app handles the SVG files in the version 2.4. Since the 2.2 version handles the same SVG pictures correctly, maybe you can a take look what have changed in this kind of handling from version 2.2 to version 2.4.

**Comment by kelson42** [comment]
I have a Samsung Galaxy Tab with 4.2.2 with the same problem as reported here. The problem is not that SVG are not rendered at all, they are with 2.4 "in general" on this device (but "yes" they are really small in comparison with the font).

But, lets focus on the "missing equations". This is a specific problem with many of them on "Satz des Pythagoras".  Not all of them, like we see on the screenshot. We also know that the pictures in SVG are there in the ZIM file. So this is somehow a problem with the reading in the ZIM file OR with the rendering of these specific SVG files.

To help to understand the problem I upload here the "Satz des Pythagoras" loading log.
[logcat.txt](https://github.com/kiwix/kiwix-android/files/2431787/logcat.txt)

Maybe here is the interesting part of the log:
```
D/kiwix   ( 1989): Retrieving: content://org.kiwix.kiwixmobile.zim.base/I/m/f11423fbb2e967f986e36804a8ae4271734917c3.svg
W/webview_proxy( 1989): java.lang.Throwable: Warning: A WebView method was called on thread 'WebViewCoreThread'. All WebView methods must be called on the UI thread. Future versions of WebView may not su\
pport use on other threads.
W/webview_proxy( 1989):         at android.webkit.WebView.checkThread(WebView.java:2008)
W/webview_proxy( 1989):         at android.webkit.WebView.getSettings(WebView.java:1603)
W/webview_proxy( 1989):         at android.webkit.BrowserFrame.inputStreamForAndroidResource(BrowserFrame.java:883)
W/webview_proxy( 1989):         at android.webkit.BrowserFrame.shouldInterceptRequest(BrowserFrame.java:960)
W/webview_proxy( 1989):         at android.webkit.JWebCoreJavaBridge.nativeServiceFuncPtrQueue(Native Method)
W/webview_proxy( 1989):         at android.webkit.JWebCoreJavaBridge.handleMessage(JWebCoreJavaBridge.java:113)
W/webview_proxy( 1989):         at android.os.Handler.dispatchMessage(Handler.java:99)
W/webview_proxy( 1989):         at android.os.Looper.loop(Looper.java:175)
W/webview_proxy( 1989):         at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:1091)
W/webview_proxy( 1989):         at java.lang.Thread.run(Thread.java:856)
```

To end this, we have no way to verify that 2.2 was working fine properly in the same situation, as 2.2 can not open `wikipedia_de_all_novid_2018-06.zim`

**Comment by florian29** [comment]
> To end this, we have no way to verify that 2.2 was working fine properly in the same situation, as 2.2 can not open `wikipedia_de_all_novid_2018-06.zim`

But you can compare the versions 2.2 and 2.4 by opening the old ZIM file "wikipedia_de_all_2017-06.zim", which can be opened with both versions of the Kiwix Android app. I post you the screenshots above. The first one is a part of the article "Maxwell-Gleichungen" opened with the 2.2 apk. As you can see all the SVG images are displayed well:

![ver 2 2](https://user-images.githubusercontent.com/43439672/46281041-d9252f00-c56d-11e8-8d3c-baeb6d68086a.png)


The next screenshot is the same article of the same ZIM file, this time opened with the 2.4 apk:

![ver 2 4](https://user-images.githubusercontent.com/43439672/46281081-f823c100-c56d-11e8-931d-a70dfecab282.png)

I think you will agree that this is a big issue especially for users who want to read mathematics or scientific articles.

**Comment by mhutti1** [comment]
@kelson42 Couldn't we test this with kiwix serve to check this. I assume the pictures wouldn't display on that either.

**Comment by florian29** [comment]
The issue is solved now with Kiwix APK 2.5.1/2.5.2 and the new ZIM file wikipedia_de_all_maxi_novid_2019-08.zim.
The issue can be closed. Thank you!

**Comment by florian29** [comment]
The same issue is now back again with Kiwix APK 3.3.0 (and also 3.2.1) and the new ZIM file "wikipedia_de_all_maxi_2020-04.zim". Tested with Android 5.0.2 and also 4.4.4 with Samsung Galaxy Tab SM-T530 and also with Samsung Galaxy S4 mini.

To reproduce the issue open the ZIM file, then open some articles with many formulas, like "Maxwell-Gleichungen" and "Satz des Pythagoras". Scroll down the whole articles, so that all of the formulas have been shown. Then open "Sinus und Kosinus" et voilà:
![Screenshot_2020-04-24-14-47-26](https://user-images.githubusercontent.com/43439672/80214982-051a7080-863c-11ea-81b4-5d92e9c77d7a.png)
Than go to the Android Application Manager and clear the data and force stopping the Kiwix App. Than reopen the Kiwix App. Open again the article "Sinus and Kosinus" and than everything seems to be normal:
![Screenshot_2020-04-24-15-00-14](https://user-images.githubusercontent.com/43439672/80215237-68a49e00-863c-11ea-99aa-be8e0b930c08.png)
Maybe it's a problem with overloading the cache of the App or something like this. It should be a problem which can be solved. You should care about it, because it's not very comfortable to do this workaround (deleting the data of the app) after opening an article.
Thank you in advance.

**Comment by florian29** [comment]
I'm not sure if I have to open a new issue for reporting this. Feel free to do it for me or inform me please. Thank you very much!

**Comment by kelson42** [comment]
@florian29 Please open a new ticket. We will then have a look quickly.
