### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by chstdu** [kiwix/kiwix-android#878]
**Describe the bug**
When clicking on a search result, the old page remains and nothing happens. (Clicking on a link on the starting page of wikipedia works fine.)

**Expected behavior**
The article which I just clicked on should appear.

**Steps to reproduce the behavior:**
1. Download the German wikipedia without pictures, copy it to the android phone and open the content within kiwix.
2. Type in a search query.
3. Click on any result.

**Screenshots**
Nothing happens...

**Environment**
- Version of Kiwix Android : 2.4 Build: 1182160
- Device : Android Smartphone
- OS version : 7.0 (Kernel version 3.18.22)

**Comment by olllllii** [comment]
I ve exactly the same Problem, the APP is useless

**Comment by kelson42** [comment]
This is a problem with that specific file, not the app. We are going to regenerate a new version soon. Sorry for the problem.

**Comment by adnion** [comment]
How long does it take? What is the process of regenerating like?

**Comment by chstdu** [comment]
I see here (http://wiki.kiwix.org/wiki/Content/de) that the German wikipedia file **with pictures** was recently regenerated. However, this file is too large to save on my phone (34 GB). I can only use the smaller one without pictures (11 GB). So I cannot check whether the problem is solved (with the new file). Can anyone download the large file and check it please?

**Comment by adnion** [comment]
I could test the the 34 GB image and it works well. Nonetheless I prefer the smaller image **without pictures**. Do you have any idea how .zim files are created?

**Comment by mhutti1** [comment]
@kelson42 ^
