### ISSUE TITLE
On cancelling a download, Android notification shows 'downloaded' instead of 'cancelled' or 'stopped'.

### ISSUE THREAD

**Issue by vansha10** [kiwix/kiwix-android#881]
**Describe the bug**
In the get content tab, on stoppping an ongoing download, the downloading notification changes to downloaded.

**Expected behavior**
The notification should either disappear or show cancelled or stopped.

**Steps to reproduce the behavior:**
1. Download an article.
2. Go to downloading tab and stop the download. 
3. Check the notification of the same download.

**Screenshots**

![screenshot_20181026-013021](https://user-images.githubusercontent.com/29632425/47527691-c7ab1a80-d8c0-11e8-9963-57e19cb47d40.jpg)
**Click on stop here (from the downloading tab)**
![screenshot_20181026-013027](https://user-images.githubusercontent.com/29632425/47527692-c7ab1a80-d8c0-11e8-99c7-d11581471a40.jpg)
**The download stops**
![screenshot_20181026-013040](https://user-images.githubusercontent.com/29632425/47527694-c843b100-d8c0-11e8-8304-a5485dcbd045.jpg)
**But here it shows downloaded**
![screenshot_20181026-013046](https://user-images.githubusercontent.com/29632425/47527695-c8dc4780-d8c0-11e8-9fe5-76425d9c2142.jpg)

**Environment**
- Version of Kiwix Android : 2.4
- Device : OnePlus 5
- OS version : Android 8.1.0

**Comment by vansha10** [comment]
One more thing: facing this issue only in the app downloaded from the play store, not in the one that I ran from my laptop.

**Comment by iadeelzafar** [comment]
@abdulwd I think this issue is solved already. So, this should be closed.
