### ISSUE TITLE
Another search oddity in conjuction with suggestions

### ISSUE THREAD

**Issue by IrgendwerA8** [kiwix/kiwix-android#887]
Kiwix 2.4 Build 182160
Android 4.1.2
Wikipedia 2018-06-30 German, no video, 32.2 GB in 2 GB chunks

Tapping the magnifier icon for "find" and entering "Der kleine" will fill the drop down with matching articles. You will find there "Der kleine Maulwurf". OK.

But when typing "Der kleine M" to narrow the filter and reduce the number of entries, no matching article is found/shown.

**Comment by kelson42** [comment]
Strongly suspect this is fixed in Kiwix Android 3.0, but this will need to be verified.

**Comment by kelson42** [comment]
This has been fixed, we just need to generate a new ZIM file of WPDE. @IrgendwerA8 Thx again for reporting that pb.
