### ISSUE TITLE
Is is possible that a specific brand cannot open Kiwix?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#888]
A gentleman on OTRS says he can't open Wikimed nor Wikimed mini (neither from APKpure nor from the appstore). The app downloads and then is reported as corrupted (see images). Could it have to do with his phone's brand (oppo A5, so fairly recent) or settings?
![screenshot_2018-11-09-13-56-43-12 1](https://user-images.githubusercontent.com/21675885/48247320-2e692180-e3f3-11e8-9c8d-9691f4b51f61.png)

![screenshot_2018-10-31-21-23-21-65](https://user-images.githubusercontent.com/21675885/48247322-31fca880-e3f3-11e8-997d-a495d5a8b12d.png)

**Comment by mhutti1** [comment]
So there is likely an issue with apkpure. I don't know if it correctly downloads expansion files containing the ZIM. It might also be possible that trying once with this might corrupt the directory meaning it won't install from Google correctly either.

**Comment by kelson42** [comment]
@mhutti1 The bug report specifically says "neither from APKpure nor from the appstore".

**Comment by kelson42** [comment]
I would say we don't support AKpure... I have no clue how they have copied and distribute the APK. Nothing much we can do here. Our distribution channel for custom apps is only - for now - Google Play.
