### ISSUE TITLE
Download tab does not list downloading files after crash

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#889]
**Describe the bug**

If files are being downloaded and app crashes due to some reason, you lose control of the downloading files i.e you can't play or stop. They do not even go out from the notification bar. Only after restarting or uninstalling the notification goes.

**Expected behavior**

The downloading files should be visible on the notification bar even if the app crashed due to any reason.
**Steps to reproduce the behavior:**
1. 

1. Start downloading any file.
2. Try to crash the app with an option available.

**Screenshots**

![kiwix crash 2 gif](https://user-images.githubusercontent.com/34706326/48332019-57e6af00-e678-11e8-8390-5e0a57443949.gif)

**Environment**
- The version of Kiwix Android: Build version 2.4
- Device: Redmi 4
- OS version: Android 7.1.2

**Request**
Please assign me for this issue.

**Comment by macgills** [comment]
Fixed in #1170
