### ISSUE TITLE
Title bar items not visible

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#890]
**Describe the bug**

When the app is in the fragment screens, the title bar items are not visible. Since the letters are in white and the title bar is also set to white, so is the problem there.As could be seen clearly only those items which are not white in color are visible.

**Expected behavior**

It should be transparent or some other color so that items and text should be visible.

**Screenshots**
![kiwix white title bar 1](https://user-images.githubusercontent.com/34706326/48327027-82c60880-e662-11e8-85a4-d3f591d1e7c5.png)

![kiwix white title bar2](https://user-images.githubusercontent.com/34706326/48326883-bb191700-e661-11e8-848a-1d8bd9a4b139.png)
![kiwix white title bar3](https://user-images.githubusercontent.com/34706326/48326884-bb191700-e661-11e8-9280-b54d65bc07f0.png)

**Environment**

- Device: Redmi 4
- OS version : Android 7.1.2

**Request**
Please assign me for this issue.

**Comment by RajaVamsi11** [comment]
@mhutti1 Can I start working on this issue?

**Comment by kelson42** [comment]
@RajaVamsi11 Yes you can :)
