### ISSUE TITLE
Multiple tabs not working 

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#892]
**Describe the bug**

Even if multiple tabs are open one could not use all the tabs because once you open any document on one tab rest tabs get closed. Multiple tabs do not work like multiple tabs rather allow you to open only one tab finally.

**Expected behavior**

It should behave as the name suggests i.e. people could open different documents on different tabs.

**Steps to reproduce the behavior:**
1. 

1. Open multiple tabs.
2. On any one tab, go forward to open any book or click on any hyperlink of the main page.
3. The rest tabs get closed.

**Screenshots**

![kiwix crash 5 gif](https://user-images.githubusercontent.com/34706326/48439375-2969f080-e7ac-11e8-9d9f-45387ec62014.gif)

**Environment**
- Version of Kiwix Android : Build 2.4 : 55
- Device : Redmi 4
- OS version : Android 7.1

**Comment by sonusourav** [comment]
@mhutti1 Is it part of any milestone and is anybody currently working on this?

**Comment by mhutti1** [comment]
@sonusourav Its a very big update planned to be part of 3.0.

**Comment by mhutti1** [comment]
This will be supported once #54 is implemented.
