### ISSUE TITLE
Certain 3-Letter entries like ICC and NSA are not searchable (DE)

### ISSUE THREAD

**Issue by Wikinaut** [kiwix/kiwix-android#893]
* https://download.kiwix.org/zim/wikipedia/wikipedia_de_all_novid_2018-06.zim
* KiwixAndroid 2.4 build 1182160

I recently noticed, that abbreviations like "ICC" and "NSA" do not give the corresponding search results. Please can someone check this and report here?

**Comment by Wikinaut** [comment]
still a valid problem

**Comment by kelson42** [comment]
@Wikinaut Yes, a famous one. A singnificant amount of time will be invested on the search core component in the next two months. I hope we will found what goes wrong here.

**Comment by Wikinaut** [comment]
Since I filed this issue I found more example where the index is broken (it starts listing the suggesting entries but the listing stops somewhere and continues with shorter lenght suggestions). Let me know if you need the details. Then, and only then  I have to remember them.

**Comment by kelson42** [comment]
@Wikinaut Yes we are! Please open one ticket per problem.

**Comment by Wikinaut** [comment]
Because I regularly delete my search list, it will take some time. Unfortunately, until now, you did not  accept/implement my privacy idee https://github.com/kiwix/kiwix-android/issues/835 (on the Wikipedia App I coded that finally, but that ready-for-implementation patch was dismissed, so I stopped working for this team. I still regard privacy search settings as essential in certain environments. I have to look up the link in gerrit.)

**Comment by kelson42** [comment]
I think we have finally fixed this pb in the libzim. This will need to be confirmed.

**Comment by kelson42** [comment]
I confirmed this has been fixed. I have tested this with `wikipedia_fr_all_mini_2019-08.zim`. This was a problem in the libzim at indexing time, at least the redirects were not properly taking in account. We will need to regenerate a new WPDE ZIM file.
