### ISSUE TITLE
Annotate in Kiwix

### ISSUE THREAD

**Issue by samuk** [kiwix/kiwix-android#897]
I'm looking to build .zim files from textbooks that have questions in the text (.PDF files designed for printing)

I would like the users to be able to add the answers to these questions in 'notes' from within the Kiwix interface.

from the press/hold drop down a 'add note' menu item would appear. When adding a note a text box & keyboard would appear on screen.

The text would be marked in some way on an overlay screen (1) (2) etc. Clicking on the mark would open the note.

Notes would be stored in a plain text file, with new notes prepended at the top, and could be emailed/shared.

For now, I'll encourage users to install a plain text editor, and answer questions by selecting the text and sharing it to a text file, then editing the text file.

**Comment by kelson42** [comment]
This is a feature we had with Kiwix-Desktop 1.0. I think this is really a legitimate and valuable feature request. That said, this should be mostly implemented in the Kiwix-lib (before working on the Android UI). This might take a bit of time before we come to that feature, but this will be done.

**Comment by kelson42** [comment]
@Aditya-Sood I that not matching what your are currently implementing?

**Comment by Aditya-Sood** [comment]
@kelson42 yes, [feature/NoteKeeper](https://github.com/kiwix/kiwix-android/pull/1198) covers most of the requirements stated here except the nature of how notes are created. Right now the user can create one note file per article/page in the wiki, so it is not like annotating some lines (like in a PDF) as requested here:
> The text would be marked in some way on an overlay screen (1) (2) etc. Clicking on the mark would open the note.

Other than that, all notes exist as plain text files, can be shared through any app which accepts text files (chat, email), and are stored in the public storage area (so directly accessible from outside the app too).
Does this suffice for now @samuk ?

**Comment by macgills** [comment]
I will close this issue for now. @samuk please let us know if this is insufficient
