### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#898]
**Is your feature request related to a problem? Please describe.**

Since AndroidX is released, we should migrate the support libraries to the androidx namespace.

**Describe the solution you'd like**

Migrate the stable libraries to the androidx namespace.

**Additional context**

Please refer to this [link](https://developer.android.com/jetpack/androidx/migrate).

**Comment by knightcube** [comment]
How can this issue be solved? I mean which module or which file should we edit? In the link given I tried the "Refactor > Migrate to androidx" solution and that gives loads of refactoring to be done in about 85 files. So how where should I begin?

**Comment by knightcube** [comment]
Please assign this issue to someone else. I tried but could not get rid of various errors
