### ISSUE TITLE
UI - Text on Card Alignment

### ISSUE THREAD

**Issue by Asgardian8740** [kiwix/kiwix-android#903]
**Describe the bug**
 Misaligned content in the card view . 

**Expected behavior**
Text Content Should be within the boundary of the card. 

**Steps to reproduce the behavior:**

1.Download any book.
2.Close the app
3.Now open the Downloaded Book 

**Screenshots**
 
[screenshot_20181221-040127__01](https://user-images.githubusercontent.com/33763700/50314774-36c67900-04d6-11e9-9f48-eb1f74000033.jpg)

**Environment**
- Version of Kiwix Android : 2.4
- Device : One Plus 6
- OS version : Android 9

**Comment by mhutti1** [comment]
I don't think this is related specifically to the android version. It is likely a mobile formatting issue.

**Comment by Asgardian8740** [comment]
Ohk sir
