### ISSUE TITLE
Launch activity (night-mode) inverts colour of icons

### ISSUE THREAD

**Issue by Aditya-Sood** [kiwix/kiwix-android#905]
**Describe the bug**
Launch activity in night-mode inverts colour of the ZIM file icons

**Expected behavior**
The icons should retain their original colour

**Steps to reproduce the behavior:**
1. Activate night-mode
2. Navigate to the launch activity

**Screenshots**

![screenshot_20181223-023547](https://user-images.githubusercontent.com/15438998/50378844-753c6f00-0661-11e9-8154-b707395d1464.png)

**Environment**
- Version of Kiwix Android : 2.4
- Device : Moto G5 Plus
- OS version : Oreo 8.1.0

**Comment by Aditya-Sood** [comment]
Seems like a simple UI fix, as it doesn't occur in the library
I'll get to it

**Comment by kelson42** [comment]
@Aditya-Sood thx

**Comment by isaeef** [comment]
@kelson42  is this open for PR ?

**Comment by kelson42** [comment]
@isaeef Like you can seem, @Aditya-Sood is assigned to the ticket and seems to work on it.

**Comment by Aditya-Sood** [comment]
@isaeef you can use the `no:assignee` qualifier to search for unassigned issues

**Comment by Aditya-Sood** [comment]
@kelson42 turns out it's not as simple as I'd expected
This launch activity is not a regular layout but a webview. From my understanding, the webview's night mode is currently being handled by having the GPU invert the entire view currently rendered on the screen (unlike how a layout's night mode is implemented, by setting the app to use a night mode theme).

However, this error of image inversion is restricted to this page only (images and figures within books are not inverted). I will need some time to figure out why this page is behaving differently and fix it.

**Comment by mhutti1** [comment]
@Aditya-Sood If I can remember we flip the webview on the Java end and then use css injection to flip the images.

https://github.com/kiwix/kiwix-android/blob/master/app/src/main/java/org/kiwix/kiwixmobile/data/ZimContentProvider.java#L485

**Comment by mhutti1** [comment]
This won't be run for non ZIM pages.

**Comment by Aditya-Sood** [comment]
Thanks @mhutti1 
I'll see how to work with this
