### ISSUE TITLE
No Online Items availabe to download , even when connected to internet.

### ISSUE THREAD

**Issue by theLimitBreaker** [kiwix/kiwix-android#907]
**Describe the bug**
Not Getting any online items after tapping Get Content option. Even after connected to working Internet.

**Expected behavior**
Should present the items from online to download

**Steps to reproduce the behavior:**
1. Click on options menu
2. Click on 'Get Content' option

**Screenshot**
<img src = "https://user-images.githubusercontent.com/24780524/50513391-7d5f3900-0abd-11e9-942c-7b5b0cd69bb5.jpeg" width = 360>

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Nokia 6.1
- OS version : Android 9.0

**Comment by Asgardian8740** [comment]
I checked this on my one plus 6.It was working perfectly.
This is i guess something device specific issue which is being caused due to permission issue or restricted data usage.
![unnamed](https://user-images.githubusercontent.com/33763700/50565202-50778400-0d52-11e9-9e35-a4937088262a.jpg)

**Comment by macgills** [comment]
Fixed in #1170
