### ISSUE TITLE
Question: How can I see which of the downloads can do fulltext search?

### ISSUE THREAD

**Issue by chasingTheDragon** [kiwix/kiwix-android#908]
I wanted to download a zim file with index for fulltext search, but it's unclear which file I need to download.

**Comment by kelson42** [comment]
All ZIM files which allow fulltext search have the _ftindex tag.

**Comment by chasingTheDragon** [comment]
Thank you. Do I understand correctly, the filename contains "_ftindex"? 
If so, do you know where I can download these? There seem to be none on https://wiki.kiwix.org/wiki/Content_in_all_languages or http://download.kiwix.org/zim/wikipedia/

**Comment by kelson42** [comment]
@chasingTheDragon No, this is a tag, so a meta-data of the ZIM file. That said, just remarked that the Kiwix Android does not display the hidden tag. But you can assume that any new ZIM we produce are with a fulltext index.

**Comment by chasingTheDragon** [comment]
I understand. with the kiwix-desktop program I can see the _ftindex tag. 
Do you happen to know if splitting the zim to zimaa, zimab,... breaks the index functionality? Because I downloaded the file wikipedia_de_all_novid_2018-11.zim and splitted it and transferred those to the phone and now fulltext search does not seem to work.

**Comment by kelson42** [comment]
@chasingTheDragon yes, it can. That is the reason why we do not recommend anymore to split the ZIM files.
