### ISSUE TITLE
Tab not loading in certain cases

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#909]
**Describe the bug**

in some cases a new tab is not loaded (and is blank), and needs to be refreshed.

**Expected behavior**

The tab should to load properly.

**Steps to reproduce the behavior:**
1. open a zim file
2. click on the tab overview button
3. open "History" from the overflow menu
4. press back

**Screenshots**
![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/32238400/50861708-84d8e900-13bf-11e9-8f9f-c58235f93440.gif)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Samsung S6
- OS version : 7.0

**Comment by siddharth2010** [comment]
A similar thing also happens when we click on the tab overview and then click on "Get Content" from the overflow menu, and then press back.

Here's the gif:
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/32238400/50861170-e8faad80-13bd-11e9-9919-56ce738820d2.gif)

**Comment by kelson42** [comment]
@macgills Might that be that you have fixed that pb at the same time as #1487?

**Comment by macgills** [comment]
I wouldn't be incredibly confident? notionally it should but MainActivity is so overfull that it makes it impossible to authoritatively say anything

**Comment by kelson42** [comment]
@siddharth2010 Have you been able to reproduce/experience the bug recently with 3.0?

**Comment by siddharth2010** [comment]
@kelson42 , yes, I just tested it. Looks like this bug still exists in 3.0

**Comment by macgills** [comment]
The fix is not on the 3.0 branch yet, it is in review

**Comment by kelson42** [comment]
@siddharth2010 Which PR are we talkinga about? I see nothing in that ticket linked to a PR!

**Comment by macgills** [comment]
https://github.com/kiwix/kiwix-android/pull/1492

**Comment by kelson42** [comment]
@macgills OK, so I guess this is fixed now.

**Comment by macgills** [comment]
It is likely it is fixed, I have not tested it but my fix is now on 3.0
