### ISSUE TITLE
Change activity transition style for mode change (from dark to light and vice versa)

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#910]
**Is your feature request related to a problem? Please describe.**

Right now we are using slide animations all throughout the app. However for mode change (from light to dark, and vice versa), the fade transition should be a much better option.

Here's the current animation for mode change:
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/32238400/50858227-d41a1c00-13b5-11e9-90b0-c105c3272d84.gif)

**Describe the solution you'd like**

I think that probably the fade animation suits this better.

Here's how the fade animation looks:
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/32238400/50859746-2fe6a400-13ba-11e9-88d0-67b24dfa8d71.gif)

**Comment by RajaVamsi11** [comment]
@siddharth2010 I am interested in working this. Can you please assign me?

**Comment by siddharth2010** [comment]
@RajaVamsi11, sure. There you go.

**Comment by 287mdsahil** [comment]
@siddharth2010 Hello, I am new to the kiwix community. If the issue is still not solved can I work for it?

**Comment by siddharth2010** [comment]
Hi @287mdsahil , I am not sure about it.
@RajaVamsi11 , are you still working in this?

**Comment by RajaVamsi11** [comment]
@287mdsahil You can work on this issue.

**Comment by 287mdsahil** [comment]
@siddharth2010 I have put a pull request for the issue
