### ISSUE TITLE
Fix aspect ratio of main banner in home screen

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#911]
**Is your feature request related to a problem? Please describe.**

when the device is rotated, the main Kiwix banner looks distorted.

Here's the screen:
![screenshot_20190109-023355](https://user-images.githubusercontent.com/32238400/50860096-0f6b1980-13bb-11e9-990e-de8d88979cf4.png)

And heres how it looks when the device is rotated:
![screenshot_20190109-024049](https://user-images.githubusercontent.com/32238400/50860102-12660a00-13bb-11e9-92fa-41b4b1633b9a.png)

**Describe the solution you'd like**

we could create the banner using three layers, (one for the main rectangle base, one for the kiwix logo, and one for the side pattern), instead of one. Then, in rotated mode, we can just change the size of the base layer, and change the relative positions of the side pattern, and the kiwix logo).

**Comment by 287mdsahil** [comment]
@siddharth2010 I would like to work on this issue. I am really new to this community, and I want to contribute

**Comment by siddharth2010** [comment]
Sure! Go ahead!

**Comment by siddharth2010** [comment]
I am unable to assign you as this is your first contribution, but, consider yourself assigned!

**Comment by 287mdsahil** [comment]
@siddharth2010 Can you send me the source file for the `ic_home_kiwix_banner.png` , please.
Extracting the pattern form the png files included in the repo would a very tedious task (although I am willing to do it if no other way out is possible :) )

**Comment by sonusourav** [comment]
@siddharth2010 I have come up with an idea in which we will have two XML layouts for home screen and depending on the screen orientation we will set it to the relevant one. I am already done with the idea and it works perfectly fine. Here is how it looks now.
![kiwix_issue_ 911_resolved](https://user-images.githubusercontent.com/34706326/52467861-e225ad00-2bac-11e9-8c18-8904b4601b2d.gif)

If it looks fine to you, I request you to provide the side pattern so that I add it and can create a pull request. Also, please assign me to this.

**Comment by siddharth2010** [comment]
Yes this actually looks good

**Comment by siddharth2010** [comment]
@287mdsahil , Are you still working on this issue, or can @sonusourav work on this.

**Comment by abdulwd** [comment]
I think our present home screen card background looks better than that introduced in #942 if it is to be replaced consider making it more visually appealing than the current one. The source of `ic_home_kiwix_banner.png` was needed, it can be found on this link: https://wiki.kiwix.org/wiki/Special:ListFiles.

**Comment by kelson42** [comment]
@siddharth2010 Instill believe this would be really great to fix that problem soon. Would you by any chance in position to tacle that problem?

**Comment by siddharth2010** [comment]
Sure @kelson42 , I will fix it in a day or two.

**Comment by kelson42** [comment]
@siddharth2010 Any news? We are approaching the end of the 3.0 milestone.

**Comment by macgills** [comment]
From the PR:
>Got it @macgills ! sorry for the late reply, but I was in the middle with my univ lab exams. I will be getting over with them on 10th. will fix it then.
