### ISSUE TITLE
[Question]: what is the use of the find in page option in the initial home screen?

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#912]
**Screenshots**

![screenshot_20190109-031117](https://user-images.githubusercontent.com/32238400/50860893-198e1780-13bd-11e9-8e82-a2f030ec7b67.png)

**Environment**
- Version of Kiwix Android : Version 2.3 Build 55
- Device : Samsung S6
- OS version : 7.0

**Comment by abdulwd** [comment]
I think we should add the functionality of searching the ZIM file on the home screen using find in page.

**Comment by Popolechien** [comment]
Well it already does that, doesn't it?
This being said, I realize your home screen looks a bit different from the one I currently have (and I like yours better)
![screenshot_20190206-100836](https://user-images.githubusercontent.com/21675885/52331061-764e1380-29f7-11e9-9c0c-5636824c326e.jpg)

- V2.4 build 1182160
- Huawei p20 Lite
- Android 8.0

**Comment by abdulwd** [comment]
@Popolechien The latest home screen is on the master branch while you are building from 2.4.

**Comment by abdulwd** [comment]
@siddharth2010 I'm unable to find `Find in page` on the home screen. Can you please double? If it's not present we can close this issue.

**Comment by siddharth2010** [comment]
let me just check

**Comment by siddharth2010** [comment]
Yeah, so if you click on the :mag: button on the action bar, you get the "find in page" option on the right.

**Comment by abdulwd** [comment]
I was searching for it in the overflow menu. 😕

**Comment by kelson42** [comment]
I think we should simply remove that tool for that page.
