### ISSUE TITLE
Make dialog boxes uniform for both light and dark modes

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#913]
**Describe the bug**

The "Entering External Link" Dialog box looks very different in light and dark modes.

![screenshot_20190109-044013](https://user-images.githubusercontent.com/32238400/50864807-34ff1f80-13c9-11e9-99c0-fabd425f8f6a.png)

![screenshot_20190109-044030](https://user-images.githubusercontent.com/32238400/50864812-392b3d00-13c9-11e9-810a-94af6da675ab.png)

**Expected behavior**

The dialog box should have the same basic structure.

**Environment**
- Version of Kiwix Android : 2.3 Build 55
- Device : Samsung S6
- OS version : 7.0

**Comment by ritik2017** [comment]
Working on it.

**Comment by ritik2017** [comment]
how should the dialog look as per the dark theme or the light theme @siddharth2010

**Comment by ritik2017** [comment]
Fixed the issue and created a pull request. Waiting for review.

**Comment by AnkurIngale** [comment]
In darkmode the button "Do not ask anymore" is white while others are blue.

**Comment by abdulwd** [comment]
Closed via #919.
