### ISSUE TITLE
Zoom Level retains last value when clicked on cancel. This leads to wrong zoom value when zoom is disabled.

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#914]
**Describe the bug**

when we change the value of the zoom slider and tap cancel, the slider level is still fixed to the newly set value. Therefore, when the zoom toggle is switched off, the zoom level, is initialized with the value of the slider (which now contains the wrong value). This leads to the wrong zoom level being set.

**Expected behavior**

The zoom level should reset to the last used value when the cancel button is tapped.

**Steps to reproduce the behavior:**
1. open settings
2. toggle zoom controls "on"
3. tap on zoom level and change the value of the slider
4. tap cancel
5. Toggle zoom controls "off", and then "on"
6. zoom level has now been set to the value to which you changed it in step 3.

**Screenshots**

![ezgif com-video-to-gif 6](https://user-images.githubusercontent.com/32238400/50865650-9b397180-13cc-11e9-94ab-f63f755e73b8.gif)

**Environment**
- Version of Kiwix Android : 2.3 Build 55
- Device : Samsung S6
- OS version : 7.0

**Comment by ravi-kishan** [comment]
I would like to work on this issue

**Comment by abdulwd** [comment]
@ravi-kishan Go ahead!

**Comment by siddharth2010** [comment]
Sure!
