### ISSUE TITLE
Request: Add redirects to search results

### ISSUE THREAD

**Issue by ARR8** [kiwix/kiwix-android#915]
So that, e.g., one could type JFK in the Wikivoyage app rather than John F. Kennedy International Airport. Would be more convenient for on-the-go use.

**Comment by ARR8** [comment]
I'm not sure what you mean. I'm referring to pages like this one: https://en.wikivoyage.org/w/index.php?title=JFK&redirect=no

**Comment by kelson42** [comment]
@ARR8 I think we have fixed this in the last libzim, but this need to be confirmed.

**Comment by kelson42** [comment]
They are added with newer ZIM files and are available in Kiwix Android 3.0
