### ISSUE TITLE
Video not working on Huawei P Smart 2019 (Android Pie)

### ISSUE THREAD

**Issue by okkebal** [kiwix/kiwix-android#922]
On my new phone videos do not work. I just see two spinning circles on top of each other. The video controls are greyed out.

**Expected behavior**
The video should play

**Steps to reproduce the behavior:**
1. Download any TED or Crash Course file with videos
2. Use a Huawei P Smart 2019
3. Open a page with a video

**Environment**
- Version of Kiwix Android : 2.4
- Device : Huawei P Smart 2019
- OS version : Android Pie

I've tried the current nighly but it crashes on "get content"

**Comment by okkebal** [comment]
I just downgraded to 2.3 and now video works...

**Comment by soloturn** [comment]
@okkebal , can you please try with a build from master?

**Comment by kelson42** [comment]
@soloturn We provide nightlies https://download.kiwix.org/nightly/

**Comment by kelson42** [comment]
@okkebal This is a problem with the ZIM file codec. So far we dont have found the perfect solution regardings codecs. Here you had a file with h264, something which is not supported well in Android.
