### ISSUE TITLE
Update the compile and target SDK versions 

### ISSUE THREAD

**Issue by RajaVamsi11** [kiwix/kiwix-android#926]
**Summary:**
The compileSdkVersion and targetSdkVersion in the build. gradle file of kiwixlib which are now set to versions 27 and 27 respectively, must be changed to 28( Android Pie) as the latest Android APIs must be used to make use of the latest features.

**Comment by RajaVamsi11** [comment]
@mhutti1 Working on this.

**Comment by abdulwd** [comment]
I have done this in #925.

**Comment by RajaVamsi11** [comment]
@abdulwd Please check [here](https://github.com/kiwix/kiwix-android/blob/master/kiwixlib/build.gradle#L4). The compile and target versions are set to 27.
Can I start working on this?

**Comment by RajaVamsi11** [comment]
@abdulwd Closing this as you have done.
