### ISSUE TITLE
Travis-CI failing again we need to accept android-28 licenses

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#927]
As per #279 which we addressed just over a year ago, it seems we need to update the android-sdk-license file on our web site 
https://github.com/kiwix/kiwix-android/issues/279#issuecomment-337059428 
@kelson42 please could you update the contents of http://download.kiwix.org/dev/android/api/licenses/android-sdk-licenses with
```
8933bad161af4178b1185d1a37fbf41ea5269c55
d56f5187479451eabf01fb78af6dfcb131a6481e
24333f8a63b6825ea9c5514f83c2829b004d1fee
```
please? 
I can't guarantee it'll fix the issue, however my local builds are working OK and this *might* fix the issue. Otherwise I'm happy to explore changing our build script to apply techniques from https://stackoverflow.com/questions/54268074/jitpack-failed-to-install-the-following-android-sdk-packages-as-some-licences-h

**Comment by julianharty** [comment]
In case it's a Google bug, see https://issuetracker.google.com/issues/123054726 which is affecting many projects currently.

**Comment by kelson42** [comment]
@julianharty thank you for reporting this. I have updated the file following your instructions. What about https://download.kiwix.org/dev/android/api/licenses/android-sdk-preview-license ? What is the purpose of this file?

**Comment by soloturn** [comment]
master builds green now, so should be fixed.

**Comment by kelson42** [comment]
@julianharty Should we close the ticket?
