### ISSUE TITLE
Add "Support Kiwix" item in app menu

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#929]
It would be nice/useful to have a "Support Kiwix" list item in the menu (probably below "Settings")
![screenshot_20190201-171427](https://user-images.githubusercontent.com/21675885/52134946-05001080-2645-11e9-9492-26e11e0ce4c9.jpg)

The item would be an external link to https://www.kiwix.org/support

**Comment by abdulwd** [comment]
@287mdsahil You can work on this issue.

**Comment by prajurock** [comment]
@abdulwd Can I work if @287mdsahil is not working.
