### ISSUE TITLE
When running an Android backup, do not backup the .zim files

### ISSUE THREAD

**Issue by genodeftest** [kiwix/kiwix-android#932]
**Is your feature request related to a problem? Please describe.**
Taking a backup of the kiwix app using adb (`adb backup -apk org.kiwix.kiwixmobile`) or of the whole system (`adb backup -apk -shared -all`) is quite large and contains all the .zim files. When restoring a backup, they are likely outdated anyways. In the mean time, they just make the backup size bigger

**Describe the solution you'd like**
Do not put the .zim files into the backup. This could be done by excluding them, see [the official documentation](https://developer.android.com/guide/topics/data/autobackup#IncludingFiles).

This is a general issue (independent from Kiwix and Android version) so no need to put a version info here.

**Comment by kelson42** [comment]
@mhutti1 That sounds sensible, what do you think about that?

**Comment by mhutti1** [comment]
Yeah sounds like a good idea.

**Comment by Aditya-Sood** [comment]
@mhutti1 I would like to work on this if @genodeftest doesn't plan to

**Comment by kelson42** [comment]
@Aditya-Sood No problem, go head and make a PR.

**Comment by genodeftest** [comment]
@Aditya-Sood : I don't plan on working on this.

**Comment by Aditya-Sood** [comment]
@genodeftest how were you backing-up the data when you faced the issue?
I have tried backing up with both `adb backup -apk org.kiwix.kiwixmobile` and using the backup manager `adb shell bgmr`, and in both cases the zim files that were in `.../Internal Storage/Kiwix/` directory weren't present after restoring the backup (I deleted the zims before restoring the backup)
Does it happen when you're backing-up to Drive?

**Comment by jhbiggs** [comment]
Is this still a valid issue?

**Comment by Aditya-Sood** [comment]
@jhbiggs I haven't heard back from anyone or faced the problem when I was trying to recreate it, so not sure if it is

**Comment by mhutti1** [comment]
I would imagine it is still valid.

**Comment by macgills** [comment]
This problem has probably been reintroduced because we use our private storage for downloading zim files now

**Comment by kelson42** [comment]
@Aditya-Sood @jhbiggs Would one of you be able to check the nature of the problem/feature with Kiwix 3.0? Do you also now how could we configure, on the app side, which data will be backup with a standard `adb` call?

**Comment by jhbiggs** [comment]
Sure, I will give it a go.

**Comment by kelson42** [comment]
@jhbiggs Thank you!

**Comment by jhbiggs** [comment]
@kelson42 Would you like to add a setting to affect the adb backup behavior?

**Comment by kelson42** [comment]
@jhbiggs You an on/off new setting which would give the ability (or not) to backup the ZIM files by running the `adb` command?

**Comment by macgills** [comment]
Going by the [advice](https://developer.android.com/guide/topics/data/backup)
>Generally, we recommend Auto Backup because it's enabled by default and requires no work to implement. Apps that target Android 6.0 (API level 23) or higher are automatically enabled for Auto Backup.

>By default, Auto Backup includes almost all of the app's files. You can use XML to include and exclude files.

The xml files are declared in the manifest so they cannot be changed at runtime.

**Comment by kelson42** [comment]
I'm anyway not in favour of making this customisable. But I would configure the manifest in a way the ZIM files are not backuped. Or @macgills do  you think this whole feature request is a bad idea?

**Comment by macgills** [comment]
The zim files should be excluded. Seeing as how the backup size is 25MB I don't think they would be anyways but probably good to define that

**Comment by kelson42** [comment]
@jhbiggs I guess you have your answer then :)

**Comment by jhbiggs** [comment]
Please help! I can't seem to find a way to filter the domain such that it excludes only .zim files.  I've tried path = "*.zim", "/*.zim", "%.zim" and others.  I can tell the zims are in the backups in these cases because I receive an error message "Size quota exceeded."  I've sought information online but haven't found anything helpful.

**Comment by genodeftest** [comment]
@jhbiggs I can't exactly tell you the solution, but if you run your backup using adb, you will not run into the size limitation. At least in my case (stock Android 9) several apps have much larger backup content. Hope that this info helps.

I couldn't find any exclude syntax either which can filter on file endings. Can't you filter by folders?

**Comment by macgills** [comment]
You can filter by folders. Zim files are saved to a folder called `Kiwix`
![image](https://user-images.githubusercontent.com/3358282/68194938-da652e80-ffad-11e9-9cbb-37b97b1d1084.png)

![image](https://user-images.githubusercontent.com/3358282/68194863-ad188080-ffad-11e9-9b15-91b92d0b8d42.png)
So try `./Kiwix` for your path? eventually something will work

**Comment by jhbiggs** [comment]
Ok, I think I got it.  Is there any other external file besides a zim?

**Comment by kelson42** [comment]
> Ok, I think I got it. Is there any other external file besides a zim?

I don't think so.

**Comment by jhbiggs** [comment]
Ok, great.  Then this should work for zim files.  I tried it with lots of scenarios and a couple of zims that were over the backup memory limit.  It seems to function properly.  Shall I create a pull request?

**Comment by kelson42** [comment]
@jhbiggs Definitely :)
