### ISSUE TITLE
Add up button to the action bar

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#935]
**Is your feature request related to a problem? Please describe.**
If user presses back button, it will close the app in some cases. Hence there needs to be an up button so that user goes back to the previous activity when clicking on the up button.

**Describe the solution you'd like**
I'd like to work on this issue. By adding an up button. 
1- on the toolbar, set navigation icon to an image of an arrow
2- Adding a navigation click listener to the toolbar

**Describe alternatives you've considered**

When user touches the up button, he goes to the activity that started the one he's currently using.
**Additional context**

![screenshot_20](https://user-images.githubusercontent.com/36811908/52327886-7fe37580-2a0f-11e9-8f92-3c808e71c0aa.png)

**Comment by mhutti1** [comment]
Do you think this is a good use of screenspace? Long titles can already be difficult to view. Can you provide a case when going back might close the app?

**Comment by reeshabhkumarranjan** [comment]
I am interested in this issue. Can I make a pull request for this?

**Comment by abdulwd** [comment]
If a link is opened in Google Chrome from some other app and the back button is pressed the browser is closed. So I'm closing this for now if a more lucrative solution is found please reopen it.
