### ISSUE TITLE
Kiwix not recognising "wikipedia no vidc

### ISSUE THREAD

**Issue by beep-inc** [kiwix/kiwix-android#940]
**Describe the bug**
1. I've successfully downloaded and opened several wikis: ray Charles, wikipedia-no-pic (34.8gb), wikimed (4.8gb)
2. I've also successfully downloaded Wikipedia-no-vid (78gb), and can see the files in the same "SD card > android >org.kiwix. kiwix mobile > data > kiwix" directory. But "Wikipedia-no-vid" does not appear in the list of content available on device that i can open.

**Expected behavior**
I had expected to be able to open Wikipedia file with pictures. 

**Steps to reproduce the behavior:**
1. From "get content > library > online" page,  select and download wikipedia-no-vid
2. On "get content > library > downloading" page, confirm download is completed. 
3.  check on "get content > library > device" page, with intention to open that big Wikipedia file, but in moot case,  this item dress not appear on the page. 

**Environment**
- Version of Kiwix Android : 2.4 build 1182160
- Device : Samsung tab s3 (sm-T813)
- OS version : android 7.0

**Comment by mhutti1** [comment]
Can you check that the files exist on the system. It should probably be split into multiple .zimaa .zimab .zimac ... files due to FAT32 limitations?

**Comment by kelson42** [comment]
@mhutti1 We should not recommend any more to people to split their ZIM files as this brakes potentially the embedded fulltext index.

**Comment by beep-inc** [comment]
It was downloaded thru the kiwix app,  so the big zim was automatically split into .zimxx as expected, each 2Gb in size. Screenshots of the folder as below. Interestingly the last file *.zimbn shows zero byte size, while the second last file *.zimbm shows 690mb.

https://drive.google.com/file/d/1k7QnyJ0tkq2tPV47VhWwbAT-e_K1GZrD/view?usp=drivesdk

**Comment by mhutti1** [comment]
Yeah, hmm that looks like the download has been corrupted. I am not sure what the best way to fix it might be. Redownloading might work but its a lot of work.

**Comment by kelson42** [comment]
The download has probably been corrupted here. The version 3.0 of Kiwix will be released in a few days and has a fully rewritten downloader service. If such a problem happens again with 3.0 then please open a new ticket and we will be quicker to handle it this time :) Thx for your report anyway.
