### ISSUE TITLE
Deprecated API Usage

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#943]
**Describe the bug**
Deprecated API Usage in 2 files.

**Expected behavior**
Import updated classes and use it's methods.

**Steps to reproduce the behavior:**
1. Deprecated API Usage in KiwixDatabaseTest.Java and TestUtils.java.
2. androidTestImplementation of junit can be updated in build.gradle.
3. import updated class of AndroidJUnit and InstrumentationRegistry in KiwixdatabaseTest.Java.
4. import updated class of InstrumentationRegistry in TestUtils.Java.

**Comment by mhutti1** [comment]
We need to make sure testdroid supports this. Testdroid isn't run on fork prs so will need to be merged into a branch on origin then a new pr created so that the full test suite runs.

**Comment by iadeelzafar** [comment]
@mhutti1 Thanks for the response. Let me know if there's anything that I need to do. Id love to refine this and make it work.

**Comment by kelson42** [comment]
@mhutti1 @macgills Testdroid is not used anymore and the question of which farm of devices we should use is again fully open. Therefore, it seems to me we could close this issue?

**Comment by mhutti1** [comment]
I think it means we should implement the fixes?

**Comment by macgills** [comment]
Deprecated usages can be a bit annoying but it isn't the most urgent. We could raise the IDE inspection to error to heavily discourage deprecated usages happening in the future?

**Comment by amCap1712** [comment]
Is this still open for work?

**Comment by kelson42** [comment]
> Is this still open for work?

@macgills ?

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/72149793-d681ce00-339b-11ea-9901-06f10afdb938.png)
There are usages of deprecated apis.

The ticket does beg the question if we should finally get rid of things we have marked deprecated in our own codebase. This is mostly the old daos, removing them would mean user database data could no longer be migrated from pre 2.5 to latter versions, I think right now this would amount to 20,000 users so is probably still a no go even though cutting that library out would mean a reduced apk size/method count

**Comment by kelson42** [comment]
@MohitMaliFtechiz Can you please update this ticket? Is that still valid? I think now we can not have anymore deprecation as you have removed all of them and the CI checks this at each run?!

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Can you please update this ticket? Is that still valid?

@kelson42 We have removed the deprecated code from our codebase and `KiwixDatabaseTest.Java` is more exist in our codebase and `TestUtils.java` is already refactored. 

> CI checks this at each run?!

We are checking deprecated code with `detekt` and we have excluded the test packages from `detekt` to not check in those folders, Currently we have 2 test cases (`SearchViewModelTest`, and `NewRecentSearchDaoTest`) that are using some deprecated methods.

**Comment by kelson42** [comment]
@MohitMaliFtechiz OK, so I guess this implemented then? closing.
