### ISSUE TITLE
Share button is not working in Device Fragment

### ISSUE THREAD

**Issue by prajurock** [kiwix/kiwix-android#945]
**Describe the bug**
App chrashes when share option is click on Device Fragment

**Steps to reproduce the behavior:**
1. open the Device fragment
2. Click on Share Button

**Screenshots**
![screencast-genymotion-2019-02-09_12 53 12 926](https://user-images.githubusercontent.com/26791135/52518315-d995ab00-2c6e-11e9-9814-607bf5da8bff.gif)

**Environment**
- Version of Kiwix Android : Latest master version
- Device : Google Nexus 4
- OS version :4.1(API 16).

**Would you like to work?**
Yes.

**Comment by prajurock** [comment]
@Popolechien @mhutti1 Kindly check this :)

**Comment by mhutti1** [comment]
It works on my device but will test on an older API.

**Comment by prajurock** [comment]
Yes @mhutti1 problem is with older API

**Comment by prajurock** [comment]
c
