### ISSUE TITLE
Activity Header size quite small in landscape orientation

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#946]
**Describe the bug**

In landscape orientation, the activity header, is really small.
This problem exists for the Following activities:
1. Settings Activity
2. Help Activity
3. Bookmarks Activity
4. Library (For downloading new zim files)
5. History Activity

**Steps to reproduce the behavior:**
1. Open any of the following activities
2. Rotate device in Landscape mode

**Screenshots**

![screenshot_20190209-190801](https://user-images.githubusercontent.com/32238400/52521516-3492c680-2c9e-11e9-8cd1-92a01c21e436.png)

![screenshot_20190209-191424](https://user-images.githubusercontent.com/32238400/52521572-05c92000-2c9f-11e9-80dc-15eb7a5abe73.png)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Samsung S6
- OS version : Android 7.0

**Comment by 287mdsahil** [comment]
I would like to work on this issue

**Comment by siddharth2010** [comment]
Sure! Go Ahead

**Comment by abdulwd** [comment]
Is it not in accordance with the material guidelines?

**Comment by siddharth2010** [comment]
Yes, i just noticed that this is a present in the Gmail app as well.
