### ISSUE TITLE
Changing screen orientations in tab overview

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#948]
**Describe the bug**

Changing screen orientation in Tab view and opening new tabs makes the whole UI quite messy.

**Steps to reproduce the behavior:**
1. open tab view
2. change screen orientation
3. click on the '+' button on the top left
4. open tab view again

**Screenshots**

![screenshot_20190209-193835](https://user-images.githubusercontent.com/32238400/52521786-a66d0f00-2ca2-11e9-8c39-2786fe23c388.png)
![screenshot_20190209-193823](https://user-images.githubusercontent.com/32238400/52521794-b08f0d80-2ca2-11e9-8da7-c866f488f1c3.png)

**Environment**
- Version of Kiwix Android : version 2.4 Build 55
- Device : Samsung S6
- OS version : Android 7.0

**Comment by siddharth2010** [comment]
Also, once this starts, the only way to fix it is to restart the app. Closing the tabs does not help as the new tabs still open in a specific orientation.

**Comment by iadeelzafar** [comment]
@siddharth2010  I'd like to work on this issue.

**Comment by siddharth2010** [comment]
Sure. Go ahead!

**Comment by iadeelzafar** [comment]
I'm working on this. I'll make a PR soon.

**Comment by iadeelzafar** [comment]
@siddharth2010 @abdulwd The solution for this that I've figured out is that on screen rotation to landscape, the tab overview should show all tabs in landscape mode and vice versa on screen rotation to portrait. But the issue I'm facing is that on screen rotation to landscape, in tab overview, it only shows tabs in landscape when a new tab is created and then it messes up the UI. It doesn't works for the tabs that were created previously in portrait.

**Comment by sonusourav** [comment]
@iadeelzafar Brother, if you are not working, can I work on this?
@abdulwd Could you assign this to me?

**Comment by iadeelzafar** [comment]
@sonusourav I am working on this but I need some directions. See my comment above.

**Comment by abdulwd** [comment]
There are two ways to show the tabs in the tabs overview screen:
- Get the bitmap of the WebView and use that bitmap in the **TabsAdapter** to get the preview of the tab.
- Use the WebView in the **TabsAdapter** as it is without changing it to bitmap. Then there are specifically two things which you need to handle.
     - You have to change the `layout_height` and `layout_width` of the WebView to a smaller size when the list of tabs is visible and when you select a tab you again have to change them back to full.
    - You have to handle the touch events when the list of tabs is shown so that when a tab is selected the touch event is not passed to the child WebView of the RecyclerView. Otherwise, the touch may trigger navigation within the WebView even when the list of tabs is visible i.e. you will navigate from page to next within the WebView if you click on a link in the WebView even when the list of tabs is visible.

We are using the first approach, so you have to try the second one in order to get this working for landscape. It is easier said than done. If anything is unclear feel free to ping me.

**Comment by iadeelzafar** [comment]
@abdulwd Thanks for writing. I really appreciate this. I'm looking forward to fixing this issue :)

**Comment by iadeelzafar** [comment]
Due to some family commitments, I am not able to give time to this ticket. @sonusourav You may proceed with working on this. The directions above will be really helpful for you. Good Luck!

**Comment by siddharth2010** [comment]
This issue has been fixed, (in the sense that the images all have the same dimensions), however, the aspect ratio of the images is not same. and the tabs opened in horizontal orientation appear stretched.

![Screenshot_20190811-173243](https://user-images.githubusercontent.com/32238400/62835982-a0aab300-bc5e-11e9-9b41-c89642ffbb6f.png)
