### ISSUE TITLE
Add 'Today' and 'Yesterday' instead of specific dates in History activity

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#949]
**Is your feature request related to a problem? Please describe.**

When viewing the History it's easier to just reference the date with today instead of the exact date, in case we viewed the article quite recently.

**Describe the solution you'd like**

In the history activity we should add the headings 'today' and 'yesterday' instead of the date for these two specific dates.

**Additional context**
![image](https://user-images.githubusercontent.com/32238400/52522068-99521f00-2ca6-11e9-9318-91871785b7d9.png)

**Comment by iadeelzafar** [comment]
@siddharth2010  I'd love to work on this issue.

**Comment by siddharth2010** [comment]
Sure. Go ahead!

**Comment by VishalBhosale5** [comment]
@siddharth2010  Is this issue closed?if not i would like to work.

**Comment by iadeelzafar** [comment]
A PR has been made for this issue already.

**Comment by VishalBhosale5** [comment]
@iadeelzafar  then why it is open?

**Comment by siddharth2010** [comment]
@VishalBhosale5, A PR has already been made for this issue and is ready to be merged.
