### ISSUE TITLE
Touch up README

### ISSUE THREAD

**Issue by EladKeyshawn** [kiwix/kiwix-android#95]
We should  update the readme to readme.md and enhance the format to be more readable and look better

**Comment by EladKeyshawn** [comment]
@kelson42 @mhutti1 Can I switch the readme to use markdown (.md)?

**Comment by kelson42** [comment]
@EladKeyshawn OK to me.

**Comment by kelson42** [comment]
This seems to be a duplicate of #112 which provides over more information. So I will close it.
