### ISSUE TITLE
In downloading fragment last image is not full visible

### ISSUE THREAD

**Issue by prajurock** [kiwix/kiwix-android#954]
**Describe the bug**
the last image is not fully visible in the Downlaoding Fragment.

**Expected behavior**
Image should be fully visible

**Steps to reproduce the behavior:**
1.open online fragment.
2. Download more then 5 books.
3 Scroll last at downlaoding Fragment

**Screenshots**
![screenshot-2019-02-10_01 09 56 518](https://user-images.githubusercontent.com/26791135/52525571-90c30e00-2cd1-11e9-85c5-abed2dfb2d4f.png)

**Environment**
- Version of Kiwix Android : Latest master
- Device : Google Nexus 6
- OS version: API 26

**Comment by prajurock** [comment]
I would Like to work on this issue.

**Comment by abdulwd** [comment]
Closed via #982.
