### ISSUE TITLE
Double click to exit form App.

### ISSUE THREAD

**Issue by prajurock** [kiwix/kiwix-android#955]
**Is your feature request related to a problem? Please describe.**
App closes in between reading books if the back button is pressed accidentally.

**Describe the solution you'd like**
I would like to add Double click on Back Button to exit.

**Describe alternatives you've considered**
A dialogue Box open to close the Application.

**Comment by prajurock** [comment]
I would like to work on this issue

**Comment by siddharth2010** [comment]
@prajurock , this has already been discussed at length in #678 .

**Comment by prajurock** [comment]
okay.
