### ISSUE TITLE
 On rotating the screen online fragment start Loading data again

### ISSUE THREAD

**Issue by prajurock** [kiwix/kiwix-android#958]
**Describe the bug**
 On rotating the screen online fragment start downloading data again

**Steps to reproduce the behavior:**
1. Open the Online fragment
2. Wait for loading data take place
3. Change orientation of app
4 loading of page start again

**Screenshots**
![screencast-genymotion-2019-02-10_01 32 43 875](https://user-images.githubusercontent.com/26791135/52525968-d7b40200-2cd7-11e9-8cff-a0a8d0a65fe1.gif)

**Environment**
- Version of Kiwix Android: Latest master
- Device: Google Nexus 6
- OS version: API 26 

**would like to work on this?**
yes

**Comment by abdulwd** [comment]
It will be fixed by #559.

**Comment by prajurock** [comment]
Okay @abdulwd I will close this issue.

**Comment by mhutti1** [comment]
This causes issues on some devices.

**Comment by prajurock** [comment]
Yes.I will work on this.

**Comment by soloturn** [comment]
is there a relation to #1030 #1031 ?

**Comment by prajurock** [comment]
No @soloturn i don't think so.

**Comment by macgills** [comment]
This is not the case anymore. The ViewModel requests the data on creation and the viewmodel persists across config changes
