### ISSUE TITLE
Move kiwixlib to a separate library and import with gradle

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#96]
Kiwixlib should be build automatically and published to a repository e.g jcenter/mavencentral that can be downloaded by gradle.

**Comment by mhutti1** [comment]
We have discussed this further and separate libraries for each architecture might be easier to generate and just as easy to import.

**Comment by kelson42** [comment]
@mhutti1 I think that is done meanwhile. Can you please put the URL where the kiwixlib can be found?

**Comment by mhutti1** [comment]
@kelson42 This isn't done. Kiwixlib is being built but not packaged for android or uploaded to a distribution service yet.

**Comment by mhutti1** [comment]
Fixed in #216
