### ISSUE TITLE
Make Alert Dialog boxes Uniform

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#960]
**Describe the bug**
Some alert Dialog boxes in the app have different icons in the top left. I think we should also make all the icons in the dialog boxes uniform as well.

**Screenshots**

![image](https://user-images.githubusercontent.com/32238400/52522487-fbf9e980-2cab-11e9-9479-8beefdc0eada.png)

**Environment**
- Version of Kiwix Android : Version 2.4 build 55
- Device : Samsung S6
- OS version : Android 7.0

**Comment by prajurock** [comment]
I would like to work.

**Comment by AminMekacher** [comment]
May I work on this issue?

**Comment by prajurock** [comment]
@AminMekacher I already made PR

**Comment by jhbiggs** [comment]
Hi, 

Would you like the first set of icons to appear (i.e. "clear_all_history" dialog, or the second set?

**Comment by kelson42** [comment]
@siddharth2010 Is that still an active feature request? If "yes" what is the value of the attached PR? Would something be reusable? Would you be able to advise @jhbiggs on this ticket?

**Comment by siddharth2010** [comment]
@kelson42 , The basic dialog box style has been fixed. However, the icons corresponding to the 'Alert symbol' still needs to be made the same for all the textboxes:
<img width="550" alt="Screen Shot 2019-06-25 at 1 27 13 AM" src="https://user-images.githubusercontent.com/32238400/60047916-8f2a3d80-96e8-11e9-8dbf-cbc56e311fff.png">

The attached PR is not quite the fix we are looking for and has some other bugs (different heights of the language dialog boxes in light and dark modes). So I guess a new PR seems like a good idea.

@jhbiggs , The first set of icons (clear_all_history) seems much better in my opinion.

**Comment by jhbiggs** [comment]
Ok, I see my rebase attempt was for naught.  Retrying...

**Comment by jhbiggs** [comment]
Right, so I merged a fix for this issue, and I hope I was not being too presumptuous.  Open for comments, definitely new still but trying my best to follow commitstyle, etc.

**Comment by jhbiggs** [comment]
Could someone please advise me on creating a pull request for my fixed issue #960 branch to the develop branch?  I was able to compare across forks, but I'm missing something here.

**Comment by jhbiggs** [comment]
Aha!  I figured it out.  Git skullduggery...
