### ISSUE TITLE
Add animations to Switches in Settings Activity

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#965]
**Is your feature request related to a problem? Please describe.**
The switch animations in the app are not that good.

**Describe the solution you'd like**
We should add animations as per the material design guide [here](https://material.io/design/components/selection-controls.html#switches), so as to get that native look and feel in the app.

| Kiwix App | Settings App   
| -------------        |:-------------:| 
|![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32238400/52534221-f3191e80-2d64-11e9-98ae-b4be1f4fabfd.gif)|![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/32238400/52534223-f4e2e200-2d64-11e9-84a8-0bdc961539e4.gif)

**Comment by 287mdsahil** [comment]
I would like to work on it.

**Comment by siddharth2010** [comment]
sure. go ahead

**Comment by harshika-arya** [comment]
@siddharth2010 I would like to work on it since it has been inactive for a long time.

**Comment by siddharth2010** [comment]
Sure, go ahead!
