### ISSUE TITLE
Tab headings incorrect in tab overview after deleting all zim files

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#966]
**Describe the bug**
After deleting all zim files opening a new tab after closing all open tabs gives wrong heading to that tab.

**Steps to reproduce the behavior:**
1. delete all your zim files
2. open the tab overview (by clicking on the  ![image](https://user-images.githubusercontent.com/32238400/52534452-9703c980-2d67-11e9-9f6a-9573ffb95576.png) button)
3. close all open tabs
4. click on the ![image](https://user-images.githubusercontent.com/32238400/52534452-9703c980-2d67-11e9-9f6a-9573ffb95576.png) button again

**Screenshots**

![screenshot_20190210-190539](https://user-images.githubusercontent.com/32238400/52534465-c31f4a80-2d67-11e9-801c-dcdaa882196a.png)

**Environment**
- Version of Kiwix Android : Version 2.4 Build 55
- Device : Samsung S6
- OS version : Android 7.0

**Comment by iadeelzafar** [comment]
Id love to work on this.

**Comment by siddharth2010** [comment]
Sure. Go Ahead

**Comment by sonusourav** [comment]
@iadeelzafar Since, this issue is resolved you could close this issue.

**Comment by iadeelzafar** [comment]
@abdulwd @siddharth2010 Could you please close this issue as it has been resolved.

**Comment by abdulwd** [comment]
Closed via #983.
