### ISSUE TITLE
Text begin cut by the right edge on Home screen

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#968]
**Describe the bug**

In the home screen, text in the zim file description is being cut by the right edge

**Screenshots**

![screenshot_20190210-192512](https://user-images.githubusercontent.com/32238400/52534658-78eb9880-2d6a-11e9-8030-b907480b2ff9.png)

(The actual text was: From Vikidia, the encyclopedia for 8 to 13-year **-old** children that everybody can make better)
(The word "old" was cut by the right margin)
![image](https://user-images.githubusercontent.com/32238400/52534707-dc75c600-2d6a-11e9-90ff-f37f55bf4de7.png)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Samsung S6
- OS version : Android 7.0

**Comment by prajurock** [comment]
I want to work on this.

**Comment by siddharth2010** [comment]
Sure. Go Ahead

**Comment by prajurock** [comment]
@sonusourav i am working on this issue

**Comment by abdulwd** [comment]
@prajurock You may work on the issue but please don't hold the issues if you're not working on them so that other contributors may work on them. Work on at most 2 issues at a time.

**Comment by prajurock** [comment]
ok @abdulwd

**Comment by ilovrencic** [comment]
@prajurock Are you still working on this issue? I would like to help if this is still an open issue.

**Comment by abdulwd** [comment]
@ilovrencic An approved PR is there for this issue which will be merged soon.

**Comment by sonusourav** [comment]
@prajurock  Could you please close this issue?

**Comment by abdulwd** [comment]
It will be closed automatically once the PR is merged.

**Comment by abdulwd** [comment]
Closed via #984.
