### ISSUE TITLE
Enable bottom toolbar by default

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#973]
**Is your feature request related to a problem? Please describe.**

As of now, there is no way to add a bookmark without enabling the bottom toolbar.

**Describe the solution you'd like**

 Enable the bottom toolbar by default.

**Comment by abdulwd** [comment]
I think we can add more options like go to the home page of ZIM and move forward in history as we have them in the bottom toolbar. We can use Google Chrome/Firefox implementation and it looks quite good:
- **Google Chrome** 
![image](https://user-images.githubusercontent.com/20206262/52581488-e3770400-2e50-11e9-906d-0f4a1037a85a.png)
- **Firefox** 
![image](https://user-images.githubusercontent.com/20206262/52581545-099ca400-2e51-11e9-97e4-34b6134c8b28.png)

**Comment by mhutti1** [comment]
I don't think this is a priority. Imo we should enable bottom bar by default.

**Comment by codepoet2017390** [comment]
@siddharth2010 @abdulwd  I would like to work on this

**Comment by codepoet2017390** [comment]
@siddharth2010 @abdulwd @mhutti1  can i proceed with this issue.

**Comment by iadeelzafar** [comment]
@codepoet2017390 See @mhutti1 's comment.

**Comment by abdulwd** [comment]
@codepoet2017390 You can work on this issue to enable the bottom toolbar by default.

**Comment by iadeelzafar** [comment]
@codepoet2017390 Are you working on this?

**Comment by codepoet2017390** [comment]
Yes

**Comment by iadeelzafar** [comment]
Great. Good Luck.

**Comment by sonusourav** [comment]
@abdulwd Since this issue is unresolved for a long time, can I take this issue?

**Comment by abdulwd** [comment]
@sonusourav I think this is rather a simple issue so we should keep it for newcomers.

**Comment by sonusourav** [comment]
@abdulwd Can you assign this to me?

**Comment by mpannu03** [comment]
I have opened  a pull request #1079 please review it.

**Comment by sauravchandra** [comment]
@abdulwd What is the status of the issue? Can I work on it?

**Comment by mhutti1** [comment]
@sauravchandra It looks like a pull request is open for it so probably not.

**Comment by mhutti1** [comment]
I think we should now force it enabled due to this.

**Comment by jhbiggs** [comment]
I'm creating a pull request to solve this issue.  I hope it meets your standards.
