### ISSUE TITLE
Redundant Toast pops up even when storage permissions are allowed

### ISSUE THREAD

**Issue by vaibhav2000** [kiwix/kiwix-android#978]
**Describe the bug**

When the app starts up, the app asks for permissions to access the storage. Upon pressing "Yes" a toast pops up saying "To access offline content we need access to your storage" which is redundant as permissions have already been given.  

**Expected behavior**

There is no use of this toast to pop up when permissions have been allowed.

**Steps to reproduce the behavior:**

1. Open the app for the first time
2. Press "Yes" on the prompt for storage access permissions 
**Screenshots**

![screenshot_20190213-155709](https://user-images.githubusercontent.com/32796125/52705566-38c62900-2fa9-11e9-9470-fd4ea5817998.png)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Moto G5 Plus
- OS version : Android 8.0

**Comment by MisterAwesome23** [comment]
I would like to fix this. On it.

**Comment by mhutti1** [comment]
I don't think this is problematic enough to warrant changing.

**Comment by macgills** [comment]
I find it pretty annoying and it is a most a one line fix? Also this happens on ZimManageActivity

**Comment by kelson42** [comment]
@abdulwd Would you be able to help us to fix that one?

**Comment by abdulwd** [comment]
@kelson42 I will work on it this weekend. I'm busy with other stuff at the moment. :(
