### ISSUE TITLE
A Snackbar and a Toast pop up simultaneously upon denying the storage permissions

### ISSUE THREAD

**Issue by vaibhav2000** [kiwix/kiwix-android#979]
**Describe the bug**

Upon pressing "No" on the dialog for storage permission encountered when the app is launched for the first time, a toast and a snackbar conveying the same message "To access offline content we need accesss to your storage" pop up simultaneously. 

**Expected behavior**

Either the snackbar or the toast should pop up at once. The snackbar is recommended to be popped up here because it also has the option to access app info through the device settings directly which the toast lacks. 

**Steps to reproduce the behavior:**
1. Launch the app for the first time
2. Press "No" when it asks for storage permissions

**Screenshots**

![screenshot_20190213-155639](https://user-images.githubusercontent.com/32796125/52706108-93ac5000-2faa-11e9-8f81-6650c28b78da.png)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Moto G5 Plus
- OS version : Android 8.0

**Comment by namrata-jha** [comment]
Is this still an open issue? And if yes, can I go ahead on working on this?

**Comment by siddharth2010** [comment]
This issue has already been resolved by #980

**Comment by sonusourav** [comment]
@vaibhav2000 This issue is resolved. Could you please close this issue?
