### ISSUE TITLE
Fix lint warnings

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#98]
We have something like 400 lint warnings. We need to go through them and either fix or suppress.

**Comment by rishabchirania** [comment]
@mhutti1 can I start working on this....I am new to this project,,this will be a good first issue for me

**Comment by mhutti1** [comment]
@rishabchirania Yeah feel free to start working away at them.

**Comment by Koundinyalanka** [comment]
@mhutti1 I can help in this issue assign me to this

**Comment by rishabchirania** [comment]
@koundinyalanka i am already working on this..hope you dont mind :)

**Comment by Koundinyalanka** [comment]
ok dude :)

**Comment by RajaVamsi11** [comment]
@rishabchirania  any updates on this issue? are you still working on this?

**Comment by RajaVamsi11** [comment]
@mhutti1  It is about 2 weeks that @rishabchirania working on it ,but there is no update.
Can i start working on this @rishabchirania .

**Comment by brijeshshah13** [comment]
@RajaVamsi11 Please go ahead. I will assign the issue to you.

**Comment by RajaVamsi11** [comment]
@mhutti1  As you can see in screenshot (linked below) there are
1767 warnings, 181 errors and 3140 typos.


![screenshot 12](https://user-images.githubusercontent.com/30550059/36933653-1418fe14-1f03-11e8-8cbf-22ffc0c0ee56.png)

I am gonna **supress** each and every warning and error.
I will add all the typos to dictonary.

**Comment by abdulwd** [comment]
@RajaVamsi11 I don't think you're working on this issue. May I take this?
If you're working on it can we divide this task? As there are so many warnings to be removed.
We can then solve this issue by taking up classes one by one and opening PRs one by one when a class is completely fixed.

**Comment by abdulwd** [comment]
@mhutti1 May I please work on this?

**Comment by abdulwd** [comment]
@mhutti1 @kelson42 @rashiq After #617 and #696 is merged I will solve this issue to avoid merge conflicts.
But now we must have our own coding style guidelines. Using Square's [code style](https://github.com/square/java-code-styles/blob/master/configs/codestyles/SquareAndroid.xml) does not feel the solution to me as we need to place the annotation on the same line as the method signature.
I would suggest using code style guidelines of [RocketChat](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop-2.x/CODING_STYLE.md). 

There is no use of Hungarian notations and their guidelines explain almost everything. We can keep 2 spaces for tab and 4 spaces for line wrap as we currently have. While solving this issue I will be touching almost every file so this can we easily be done now. So the work of removing warning and changing code style will never have to be repeated in future. Also, we can add a code style file to the repo so that the Android Studio uses it for reformating by default.

**Comment by julianharty** [comment]
As there is a large volume of reported issues (370+) when I ran Lint today (29 May 2018) on the `master` branch, I agree with @abdulwd it's a good time to refine / establish a code style guideline, and one that includes how we address the many and various types of Lint warnings and errors. 

BTW the [RocketChat](https://github.com/RocketChat/java-code-styles/blob/master/CODING_STYLE.md) code style guidelines have moved and don't mention Lint currently. 

I'm not a fan of suppressing lots of warnings, especially if there's a practical fix for them. 

I'm willing to chip away at some of the issues. Others are beyond my immediate influence e.g. correcting typos in translated strings, or understanding for some of the code-specific issues.

**Comment by kelson42** [comment]
@mhutti1 @julianharty @abdulwd IMO this is important/urgent to work to avoid warnings. Quite a bad habit to let them "live" long.

**Comment by kelson42** [comment]
@mhutti1 @macgills Would that make sense to just get CI reporting errors if linting fails with warnings?

**Comment by macgills** [comment]
CI is currently running lint, I could open a PR where we fail all warnings. Some will definitely need disabling/ignoring

**Comment by kelson42** [comment]
@macgills You mean through a global linting configuration... or do you many locally deactivating the linting for pieces of code?

**Comment by macgills** [comment]
```
 lintOptions {
        checkAllWarnings true
        warningsAsErrors true
        // use this line to check all rules except those listed
        disable 'MissingTranslation', ...
        //OR this line to check but not worry about result (i think this is what you want)
        ignore 'MissingTranslation', ...
    }  
```
We can specify in lint.xml or my preferred way of doing it in build.gradle. It might make sense to ignore some instances of lint violations with annotations on a specific class or the like but the general case should be specified in configuration

**Comment by kelson42** [comment]
@macgills Then I'm really in favour to make the CI fail if linting fails. Would you be able to propose a base linting configuration? A tradeoff should probably found between being strict and somehow achieving to get the current code base passing.

**Comment by macgills** [comment]
I'll get working on it

**Comment by macgills** [comment]
I went about fixing some errors and then it got pretty horrible so I have went with the baseline file.
This file takes all issues we currently have and ignores the specific instances but still reports new errors.
We should however make tech debt tickets to reduce the amount of issues in baseline, which is 1500+
