### ISSUE TITLE
Set the screen orientation to portrait for some activity

### ISSUE THREAD

**Issue by prajurock** [kiwix/kiwix-android#985]
**Describe the Feature**
Set the screen orientation to portrait for some activity. Like in the library Activity
it will enhance issue #958 and remove bug of #948.

**Environment**
- Version of Kiwix Android: Latest Master 2.4 Build 55
- Device: Asus Zenfone Max M1 Pro
- OS version: Android 8.1(API 27)

**Comment by prajurock** [comment]
@abdulwd @siddharth2010 What's your view on this.

**Comment by siddharth2010** [comment]
I don't think we should good ahead with this. While it does seem like a good idea In the context of mobile devices, in case of tablets, I guess landscape is the preferred orientation.

So locking the user to portrait is probably not the way to go.

**Comment by prajurock** [comment]
We can free screen orintation in Tab And fix screen orintation to potrait in Mobile.
[https://stackoverflow.com/questions/9627774/android-allow-portrait-and-landscape-for-tablets-but-force-portrait-on-phone](url)

**Comment by abdulwd** [comment]
We already have a pull request for #958 and @iadeelzafar is working on #948. I don't think we should lock the orientation unnecessarily, instead, we should give the user more flexibility.

**Comment by prajurock** [comment]
Okay
