### ISSUE TITLE
The last item of Home screen is cutting

### ISSUE THREAD

**Issue by prajurock** [kiwix/kiwix-android#986]
**Describe the bug**
The last item of Home screen is cutting

**Steps to reproduce the behavior:**
1. Open the App.
2.Scroll Down Bottom

**Screenshots**
![whatsapp image 2019-02-14 at 7 08 17 pm](https://user-images.githubusercontent.com/26791135/52790585-eeb67380-308c-11e9-83f7-49b7cc57946e.jpeg)

**Environment**
- Version of Kiwix Android: Latest Master Android
- Device : Asus Zenfone Max M1 Pro
- OS version : Android 8.1

**Logs**

**Comment by prajurock** [comment]
I will work on this.

**Comment by sonusourav** [comment]
This issue is already addressed in issue #894.

**Comment by abdulwd** [comment]
Do not open duplicate issues, search the issue tracker before opening one. If you find duplicate issues you can close them. @sonusourav If you're not working on #894 you can let @prajurock work on it otherwise you can open a PR. :)
