### ISSUE TITLE
App Crashes on get contents

### ISSUE THREAD

**Issue by souravmunjal** [kiwix/kiwix-android#987]
Steps to get the crash :
1->Go to "Get Contents" option of menu 
2->Go to online section.
3->Start any download
4->Now go to downloading section
5->Stop the downloading (not pause)
6->Then again you press the Resume Downloading button the app crashes.
![step1](https://user-images.githubusercontent.com/30770269/52813080-fabb2900-30be-11e9-885e-5df477530b2a.png)
![step2](https://user-images.githubusercontent.com/30770269/52813082-fabb2900-30be-11e9-93e9-32886a6cda2d.png)
![step3](https://user-images.githubusercontent.com/30770269/52813083-fb53bf80-30be-11e9-925d-cbfca7393593.png)
![step4](https://user-images.githubusercontent.com/30770269/52813549-078c4c80-30c0-11e9-83f9-c80a69a4630d.png)

**Comment by siddharth2010** [comment]
@souravmunjal , are you using the app from the app store, or from the GitHub repo?

**Comment by prajurock** [comment]
@souravmunjal this not happening in my phone.App version i am using is 2.4 Build:55

**Comment by souravmunjal** [comment]
I am using it from app Store and @prajurock it happens sometimes and u just keep trying for sometime it will crash I don't know the exact issue (sometimes it does on screen rotation).

**Comment by prajurock** [comment]
Ok.If i found any i will report.

**Comment by siddharth2010** [comment]
@souravmunjal , You should use the app from GitHub, not the App Store, as the GitHub one is under active development.

The App store one is released once every few months, after adding all the patches from GitHub.

**Comment by macgills** [comment]
Fixed in #1170
