### ISSUE TITLE
A Separate Book Downloaded Successfully Notification

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#988]
**Is your feature request related to a problem? Please describe.**

When the book is downloaded, the user should be told in a conscious way about that. 

**Describe the solution you'd like**

* Currently, when the book is downloaded, the same old notification text is updated to "downloaded".
* I think it'd be much better, if once the download is finished. This notification disappears and a new notification appears, 
* "You have successfully downloaded "xyz" with a sound/vibration maybe.

**Additional context**

This is how it looks right now.

<img src = "https://user-images.githubusercontent.com/36811908/52844668-e90d6c00-3126-11e9-9b64-3113d319e608.png" height="200" width="394">

**Comment by iadeelzafar** [comment]
@abdulwd  @mhutti1 What you think about it?

**Comment by abdulwd** [comment]
Can you check how does Google Chrome do it or any client app which is used to download files? Do they use alert tone / vibration?

**Comment by iadeelzafar** [comment]
@abdulwd I checked Chrome, YouTube and TED and yes they all do it silently. So, we too should make no alert sound. Lesson learnt. Any other suggestions to refine this idea?

**Comment by abdulwd** [comment]
Do they replace the notification with a new one? Or do they hide the progress bar in the notification?

**Comment by iadeelzafar** [comment]
@abdulwd previous notification disappears and a new notification appears.

**Comment by abdulwd** [comment]
@iadeelzafar Then you can proceed with the same.

**Comment by macgills** [comment]
Added in #1170
