### ISSUE TITLE
Swipe to delete feature for list of downloaded books

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#991]
**Is your feature request related to a problem? Please describe.**
As of now if a user has to delete any file, user has to go to library section and long press it and then press delete icon for deleting a file. Using swipe to delete feature, it would be easy for someone to delete any Zim file if he/she runs out of space or in any other case where Zim files have to be deleted.

**Describe the solution you'd like**
A user just has to swipe right in the home page or library fragment list to delete the Zim file. As a protective measure, an undo snack bar should also be shown to undo-delete.

**Additional context**
This is how it would look like ( from another app)
![swipe_to_delete](https://user-images.githubusercontent.com/34706326/52900444-cad56800-321b-11e9-90d0-091621917287.jpeg)

**Comment by abdulwd** [comment]
I think it will trigger accidental deletions. Swipe to delete must be used when the items can easily be restored or are of less importance like cards in a news feed. ZIM files are expensive to download as they may be as large as 50 GB. For example, we don't use swipe to delete to delete a song from the device.

**Comment by sonusourav** [comment]
I completely agree with you so that's why I kept the option of UNDO. Only after the UNDO timeout occurs, it will get deleted from the mobile. After swiping it will be removed from the list, and after timeout from the device.

**Comment by abdulwd** [comment]
The user will expect that the memory of the phone will be freed after deletion but actually it won't be. This will create confusion for the user and it is not transparent. Also, you cannot show a snack bar for an indefinite period of time it will obstruct the screen unnecessarily. Moreover, if the user deletes more than one file by mistake he/she will only be able to restore one of them.

**Comment by sonusourav** [comment]
Let me put it this way. Let's say the snack bar is set to disappear after 5 secs. After swiping, the file name gets removed from the list but the file will get removed from the mobile only after 5 secs. So, if a user deleted accidentally, he/she could recover within that 5 secs. Since till 5 secs, it is there in the mobile, the name of the file will be visible again as soon as UNDO is pressed. This is the same way as it happens in other apps. There is no question of confusion.

For multiple deletions, I would say, that is very less probable.

**Comment by abdulwd** [comment]
Ummm... I defer it to @mhutti1, he can advise something good.

**Comment by mhutti1** [comment]
I don't think this is a good idea with the current size of ZIM files. Maybe if they were more modular it would make sense but I used to accidentally delete emails all the time on gmail until I was able to turn this off.
