### ISSUE TITLE
Online contents shows "no items available" on API 28, works normally on API 27

### ISSUE THREAD

**Issue by MisterAwesome23** [kiwix/kiwix-android#993]
**Describe the bug**
I had my AVD on android 9 and the online get content section show "no data available"
Then I tried using my actual physical device running Android 7.1.2 and it worked normally.
So I downloaded another AVD with same phone and other specs but on Android 8 (API 27) and it works normally.

**Expected behavior**
Should show online content as on other API levels.

**Steps to reproduce the behavior:**
1. Download AVD pixel 2 with API 28.
2. Run the app and test the online section to get content.

**Screenshots**
The one on left is API 27 and one on right is API 28.

![norecords](https://user-images.githubusercontent.com/36367483/52903760-6bda1800-3248-11e9-910d-518b99c6441d.png)

**Environment**
- Version of Kiwix Android : 
- Device : Pixel 2
- OS version : API 27/28

**Logs**

**Comment by MisterAwesome23** [comment]
In logcat I get this as one of the errors:
E/memtrack: Couldn't load memtrack module

Answer on this website: https://code.i-harness.com/en/q/1594cc0
Suggests changing the API to appropriate level fixed it. So is it an API problem or can be fixed via code fixes?

P.S: Tried installing official Kiwix app from google play on android 9 device and it works normally.

**Comment by mhutti1** [comment]
Seems we need to allow cleartext https://developer.android.com/training/articles/security-config
