### ISSUE TITLE
On opening a new tab from Home screen all previous tab close

### ISSUE THREAD

**Issue by prajurock** [kiwix/kiwix-android#994]
**Describe the bug**
On opening a new tab from Home screen all previous tab close

**Screenshots**

![whatsapp video 2019-02-17 at 1 10 09 am](https://user-images.githubusercontent.com/26791135/52904369-54ebf380-3251-11e9-8ef7-e9e0fcc03312.gif)

**Environment**
* Version of Kiwix Android: Latest Master 2.4 Build 55
* Device: Asus Zenfone Max M1 Pro
* OS version: Android 8.1(API 27)

**Comment by prajurock** [comment]
I will work on this.

**Comment by abdulwd** [comment]
This is because opening of multiple ZIM files simultaneously is not supported yet and already there are many issues opened regarding this. If you want to work on this issue you will have work on kiwix-lib to enable multi-ZIM support.
