### ISSUE TITLE
On clicking menu item icon new tab is open.

### ISSUE THREAD

**Issue by prajurock** [kiwix/kiwix-android#995]
**Describe the bug**
On clicking menu item new tab is open.

**Expected behavior**
Only menu option should be open

**Steps to reproduce the behavior:**
1. Click on the menu item icon after deleting all the tab
2. Click on the menu item icon
3 A new tab will open.

**Screenshots**

![whatsapp video 2019-02-17 at 1 13 22 am](https://user-images.githubusercontent.com/26791135/52904404-de032a80-3251-11e9-98ee-217c46873f42.gif)

**Environment**
   * Version of Kiwix Android: Latest Master 2.4 Build 55
   * Device: Asus Zenfone Max M1 Pro
   * OS version: Android 8.1(API 27)

**Comment by prajurock** [comment]
I will work on this.

**Comment by mhutti1** [comment]
It shouldn't be possible to delete all your tabs. We should do something like add a new default tab if you delete them all.

**Comment by prajurock** [comment]
Yes.This will be fine too

**Comment by iadeelzafar** [comment]
@prajurock What solution have you figured out for this?

**Comment by prajurock** [comment]
@iadeelzafar Check this. I open home page after closing all tab and gave the time of 1500ms. Any suggestions.
